SUBROUTINE SETUPAMB(FILENAME)
IMPLICIT NONE
        CHARACTER(*) :: FILENAME
        WRITE(*,*) 'SF344> SHOULDN`T BE IN THIS ROUTINE!  COMPILED CORRECTLY?'
END SUBROUTINE SETUPAMB

SUBROUTINE AMBERINTERFACE(DUMMY1,DUMMY2)
IMPLICIT NONE
        INTEGER         :: DUMMY1, DUMMY2

END SUBROUTINE AMBERINTERFACE

SUBROUTINE AMBER_READCOORDS(OSTRING)
IMPLICIT NONE
CHARACTER(LEN=20) OSTRING

END SUBROUTINE AMBER_READCOORDS

SUBROUTINE A9RESTOATOM(FROZENRES,FROZEN,NFREEZE,UNFREEZE)
IMPLICIT NONE
LOGICAL FROZENRES(*), FROZEN(*), UNFREEZE
INTEGER NFREEZE
END SUBROUTINE A9RESTOATOM

SUBROUTINE AMBERFINALIO(NSAVE,NUNIT,OSTRING,FILTH,COORDS2)
IMPLICIT NONE

INTEGER NSAVE,NUNIT,FILTH
CHARACTER(LEN=80) OSTRING
DOUBLE PRECISION COORDS2(*)

END SUBROUTINE AMBERFINALIO

SUBROUTINE AMBERSECDER(OLDX,STEST)
IMPLICIT NONE
DOUBLE PRECISION  :: OLDX(*)
LOGICAL    :: STEST
END SUBROUTINE AMBERSECDER

SUBROUTINE AMBERENERGIES(Y,GRAD,EREAL,GRADT,STEST)
IMPLICIT NONE
DOUBLE PRECISION :: Y(*),GRAD(*),EREAL
LOGICAL          :: GRADT,STEST

END SUBROUTINE AMBERENERGIES

SUBROUTINE CHECK_CISTRANS_RNA(COORDS,NATOMS,ATOMLABELS,GOODSTRUCTURE)
IMPLICIT NONE

INTEGER,INTENT(IN) :: NATOMS
CHARACTER(LEN=5),INTENT(IN) :: ATOMLABELS(NATOMS)
DOUBLE PRECISION,INTENT(IN) :: COORDS(3*NATOMS)
LOGICAL,INTENT(OUT) :: GOODSTRUCTURE

GOODSTRUCTURE=.FALSE.

END SUBROUTINE CHECK_CISTRANS_RNA

SUBROUTINE CHECK_CISTRANS_DNA(COORDS,NATOMS,ATOMLABELS,GOODSTRUCTURE)
IMPLICIT NONE

INTEGER,INTENT(IN) :: NATOMS
CHARACTER(LEN=5),INTENT(IN) :: ATOMLABELS(NATOMS)
DOUBLE PRECISION,INTENT(IN) :: COORDS(3*NATOMS)
LOGICAL,INTENT(OUT) :: GOODSTRUCTURE

GOODSTRUCTURE=.FALSE.

END SUBROUTINE CHECK_CISTRANS_DNA

SUBROUTINE MME2WRAPPER(COORDS,ENERGY,VNEW,TEMPHESS,ATMASS,GRAD1)
IMPLICIT NONE

DOUBLE PRECISION COORDS(*),ENERGY,VNEW(*),TEMPHESS(*),ATMASS(*),GRAD1(*)

END SUBROUTINE MME2WRAPPER

SUBROUTINE MMEINITWRAPPER(PRMTOP,IGB,SALTCON,RGBMAX,CUT)
IMPLICIT NONE

CHARACTER       :: PRMTOP
INTEGER         :: IGB
DOUBLE PRECISION :: SALTCON,RGBMAX,CUT

END SUBROUTINE MMEINITWRAPPER

SUBROUTINE CHECK_CISTRANS_PROTEIN(COORDS,NATOMS,GOODSTRUCTURE,MINOMEGA,CISARRAY)
IMPLICIT NONE

! STUFF FOR DETECTING CIS-TRANS ISOMERISATION OF OMEGA ANGLES IN PEPTIDE BONDS
LOGICAL,INTENT(OUT) :: GOODSTRUCTURE
INTEGER,INTENT(IN) :: NATOMS
DOUBLE PRECISION,INTENT(IN) :: COORDS(3*NATOMS),MINOMEGA
INTEGER :: CISARRAY(NATOMS)

GOODSTRUCTURE=.FALSE.

END SUBROUTINE CHECK_CISTRANS_PROTEIN

SUBROUTINE SET_CHECK_CHIRAL(COORDS,NATOMS,GOODSTRUCTURE,CHIARRAY)
IMPLICIT NONE

! STUFF FOR DETECTING CIS-TRANS ISOMERISATION OF OMEGA ANGLES IN PEPTIDE BONDS
LOGICAL,INTENT(OUT) :: GOODSTRUCTURE
INTEGER,INTENT(IN) :: NATOMS
DOUBLE PRECISION,INTENT(IN) :: COORDS(3*NATOMS)
INTEGER :: CHIARRAY(NATOMS)

GOODSTRUCTURE=.FALSE.

END SUBROUTINE SET_CHECK_CHIRAL

SUBROUTINE CHECK_CHIRALITY(COORDS,NATOMS,GOODSTRUCTURE)
IMPLICIT NONE

INTEGER,INTENT(IN) :: NATOMS
DOUBLE PRECISION,INTENT(IN) :: COORDS(3*NATOMS)
LOGICAL :: GOODSTRUCTURE
END SUBROUTINE CHECK_CHIRALITY

SUBROUTINE AMBER_DEALLOCATE_STACKS()

END SUBROUTINE AMBER_DEALLOCATE_STACKS

SUBROUTINE TAKESTEPAMBER(NP)
IMPLICIT NONE
INTEGER NP
END SUBROUTINE TAKESTEPAMBER

SUBROUTINE TAKESTEPAMM(Q, DEBUG, BHSTEPSIZE)
IMPLICIT NONE
DOUBLE PRECISION :: Q(3*5000)
LOGICAL :: DEBUG
DOUBLE PRECISION :: BHSTEPSIZE
END SUBROUTINE TAKESTEPAMM

SUBROUTINE  GETSEEDATM(DUMMY1,DUMMY2,DUMMY3,AT1,AT2,AT3,IRES)

CHARACTER :: DUMMY1, DUMMY2, DUMMY3
INTEGER :: AT1, AT2, AT3, IRES

END SUBROUTINE GETSEEDATM

SUBROUTINE GETICCOORDS()

END SUBROUTINE GETICCOORDS

SUBROUTINE CHECK_SIDECHAIN(I3,J3,K3,L3,IICD,IS_SIDECHAIN)
INTEGER :: I3,J3,K3,L3,IICD
LOGICAL :: IS_SIDECHAIN(100)

END SUBROUTINE CHECK_SIDECHAIN

SUBROUTINE CHGETICVAL(Q,BOND1, BOND2, THET1, THET2, PHI)
DOUBLE PRECISION :: Q(3*1000), BOND1(1000), BOND2(1000), THET1(1000)
DOUBLE PRECISION :: THET2(1000), PHI(1000)
END SUBROUTINE CHGETICVAL 

SUBROUTINE A9DUMPPDB(DUMPCOORDS,FNAMEF)
CHARACTER :: FNAMEF
DOUBLE PRECISION :: DUMPCOORDS
END SUBROUTINE A9DUMPPDB

SUBROUTINE INTEFINALIO(NSAVE,NUNIT,OSTRING,FILTH,COORDS2)
IMPLICIT NONE
INTEGER NSAVE,NUNIT,FILTH
CHARACTER(LEN=80) OSTRING
DOUBLE PRECISION COORDS2(*)
END SUBROUTINE INTEFINALIO
