!  GMIN: A PROGRAM FOR FINDING GLOBAL MINIMA
!  COPYRIGHT (C) 1999-2006 DAVID J. WALES
!  THIS FILE IS PART OF GMIN.
!
!  GMIN IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!  IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!  THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!  (AT YOUR OPTION) ANY LATER VERSION.
!
!  GMIN IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!  BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!  MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!  GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!
!  YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!  ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!  FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!
! 
! THE `BASIN-SAMPLING' ALGORITHM COMBINES `BASIN-HOPPING' AND WANG-LANDAU
! SAMPLING TECHNIQUE TO STUDY THE THERMODYNAMICS OF THE TRANSFORMED PES.
! IT PROVIDES A DIRECT TEMPERATURE-INDEPENDENT ESTIMATE OF THE DENSITY OF STATES
! ALONG WITH THERMODYNAMIC PROPERTIES SUCH AS THE FREE ENERGY AND ENTROPY VIA ENSEMBLE AVERAGES USING
! SAMPLES OF LOCAL MINIMA RATHER THAN INSTANTANEOUS CONFIGURATIONS. (TETYANA BOGDAN)
! T.V. BOGDAN, D.J. WALES AND F. CALVO, J. CHEM. PHYS., 124, 044102 (2006).
!                                            
!---======================================---
      SUBROUTINE BASINSAMPLING

      USE MODCHARMM
      USE COMMONS, ONLY: NATOMS,  COORDS, BSPTRESTART, HISTMIN, HISTMAX, HBINS, HISTFAC, TARGETWL, &
                         & HISTFACMUL, DEBUG, EQUIL , PERIODIC, TWOD, BINSTRUCTURES, SAVENTH, DUMPEVERYNTHQUENCH, &
                         & FIXEDENDMOVET, CHRMMT, RIGID, FIXCOM, MAXIT
      IMPLICIT NONE
    

      INTEGER NSTEPS, I, J, VISITS(HBINS), VISITSTOTAL(HBINS), LBFGS_ITERATIONS, BININDEXOLD, BININDEXNEW, NQUENCHES, &
              & NQUENCHESSINCEFLAT, NQUENCHESSUCCESS, NWL, NQUENCHESSINCELASTUPDATE, MINIMANUMBER(HBINS), NDUMMY, CONVERGED, &
              & FROZENVISITS(HBINS)
      REAL(8) POTEL, DUMMY, CURRENTPOINTENERGY, CURRENTPOINTCOORDINATES(3*NATOMS, 1), &
              & DISTANCEOLD, LNMODFAC, PERTURBEDCOORDINATES(3*NATOMS, 1), PERTURBEDCOORDINATESSAVE(3*NATOMS, 1), LNRATIO, &
              & HARVEST, BINLABEL(HBINS), OLDENERGY, NORM, MINDISTANCE(HBINS), MINDISTANCEOLD, LNHARVEST, QWEIGHT(HBINS,2), &
              & CURRENTQ, Q4ORDERPARAM, KNOWNENERGIES(61836), RMAT(3,3), HISTINT

      !REAL(16) LNWEIGHT(HBINS), DISTANCE(HBINS) 
      REAL(8) LNWEIGHT(HBINS), DISTANCE(HBINS) 
         
      LOGICAL YESNO, FLAT, EVAP, EVAPREJECT, ACCEPTMOVE

      COMMON /MYPOT/ POTEL

      COMMON /EV/ EVAP, EVAPREJECT

! IF THE BS RUN IS REQUESTED TO BE RESTARTED THE FOLLOWING FILES WILL BE READ IN:
      
      IF (BSPTRESTART) THEN
         OPEN(UNIT=421, FILE='LNWEIGHT.HIS', STATUS='OLD')
         DO I=1, HBINS
            READ(421, '(2G20.10)') DUMMY, LNWEIGHT(I)
         ENDDO
         PRINT *, 'FOLLOWING LN(WEIGHT) HISTOGRAM WAS READ:'
         PRINT *, LNWEIGHT
         CLOSE(421)
         OPEN(UNIT=421, FILE='DISTANCE.HIS', STATUS='OLD')
         DO I=1, HBINS
            READ(421, '(2G20.10)') DUMMY, DISTANCE(I)
         ENDDO
         PRINT *, 'FOLLOWING DISTANCE HISTOGRAM WAS READ:'
         PRINT *, DISTANCE
         CLOSE(421)
         OPEN(UNIT=421, FILE='MINDISTANCE.HIS', STATUS='OLD')
         DO I=1, HBINS
            READ(421, '(2G20.10)') DUMMY, MINDISTANCE(I)
         ENDDO
         PRINT *, 'FOLLOWING MINIMIZED DISTANCE HISTOGRAM WAS READ:'
         PRINT *, MINDISTANCE
         CLOSE(421)
      ELSE
! NOTE THAT WEIGHT ACCUMULATION IS IS DONE IN LOGARITHMS
         LNWEIGHT=0.0D0 
         QWEIGHT=0.0D0
         DISTANCE=0.0D0
         MINDISTANCE=0.0D0
      ENDIF

      IF (BSPTRESTART) THEN
         OPEN(UNIT=422, FILE='VISITS.HIS', STATUS='OLD')
         DO I=1, HBINS
            READ(422, '(2G20.10)') DUMMY, VISITS(I)
         ENDDO
         PRINT *, 'FOLLOWING VISITS HISTOGRAM WAS READ:'
         PRINT *, VISITS
         CLOSE(422)
         OPEN(UNIT=422, FILE='VISITSTOTAL.HIS', STATUS='OLD')
         DO I=1, HBINS
            READ(422, '(2G20.10)') DUMMY, VISITSTOTAL(I)
         ENDDO
         PRINT *, 'FOLLOWING VISITSTOTAL HISTOGRAM WAS READ:'
         PRINT *, VISITSTOTAL
         CLOSE(422)
         OPEN(UNIT=422, FILE='LNMODFAC.RESTART', STATUS='OLD')
         READ(422, '(G20.10)') LNMODFAC
         PRINT *, 'RESTARTING FROM MODIFICATION FACTOR', LNMODFAC
         CLOSE(422)
         OPEN(UNIT=422, FILE='NWL.RESTART', STATUS='OLD')
         READ(422, '(G20.10)') NWL
         PRINT *, 'NUMBER OF WANG LANDAU ITERATIONS ALREADY COMPLETED: ', NWL
         CLOSE(422)
      ELSE
         VISITS=0
         VISITSTOTAL=0
         MINIMANUMBER=0
         LNMODFAC=LOG(HISTFAC) ! REFER TO THE TABLE
         PRINT *, 'LNMODFAC, EXP', LNMODFAC, EXP(LNMODFAC)
         NWL=0
      ENDIF

      HISTINT=(HISTMAX-HISTMIN)/HBINS
      DO I=1, HBINS
         BINLABEL(I)=HISTMIN + HISTINT*(I-0.5)
      ENDDO


! FOR VISITPROP CONVERGENCE SCENARIO 
! IF ONE WANTS TO USE PREVIOUSLY ACCUMULATED NUMBER OF VISITS, SET EQUIL TO -1 IN DATA AND COPY 
! OLD VISITSTOTAL.HIS TO FROZEN.HIS
!
      IF (EQUIL.EQ.-1) THEN
         OPEN(UNIT=422, FILE='FROZEN.HIS', STATUS='OLD')
         DO I=1, HBINS
            READ(422, '(2G20.10)') DUMMY, FROZENVISITS(I)
         ENDDO
       ENDIF

      
      IF (FIXCOM) CALL CENTRECOM(COORDS(1:3*NATOMS,1))
      CURRENTPOINTCOORDINATES=COORDS
      PERTURBEDCOORDINATESSAVE=COORDS
      PRINT *, 'CALCULATING INITIAL ENERGY'
      CALL QUENCH(.FALSE.,1,LBFGS_ITERATIONS,DUMMY,NDUMMY,CONVERGED,CURRENTPOINTCOORDINATES)
      CURRENTPOINTENERGY=POTEL
      PRINT *, 'INITIAL ENERGY', CURRENTPOINTENERGY


      BININDEXOLD=ENERGY2INDEX(CURRENTPOINTENERGY)

      IF ((BININDEXOLD < 1 ).OR.(BININDEXOLD > HBINS)) THEN
         PRINT *, 'STARTING GEOMETRY IS OUTSIDE REQUESTED RANGE. EXITING.'
         RETURN
      ENDIF 
      DISTANCEOLD=0.0D0       

      NQUENCHES=0
      NQUENCHESSINCEFLAT=0
      NQUENCHESSUCCESS=0
      CONVERGED=0
      NQUENCHESSINCELASTUPDATE=0

! REPEAT FOR THE REQUESTED NUMBER OF WANG-LANDAU ITERATIONS. 
! THE ITERATION IS COMPLETE WHEN THE VISITS HISTOGRAM SATISFIES THE FLATNESS CRITERION.

      DO
         IF ( NWL==TARGETWL ) EXIT
! JMC DO SOMETHING DIFFERENT HERE IF CHARMM
         IF (CHRMMT) THEN

! FIXED END MOVE SCHEME
             IF (FIXEDENDMOVET) THEN ! STEALING FEM KEYWORD FOR BASIN-HOPPING GMIN IC MOVES...
!!!                 CALL FIXEDENDMOVE(1)
!!!                 PERTURBEDCOORDINATES(1:3*NATOMS,1) = COORDS(1:3*NATOMS,1)
!!!             ELSE
! STEP IN INTERNAL COORDINATES
                COORDS(1:3*NATOMS,1) = PERTURBEDCOORDINATESSAVE(1:3*NATOMS,1)
                IF(CHRIGIDTRANST) CALL MKRIGIDTRANS(1)
                IF(CHRIGIDROTT) CALL MKRIGIDROT(1)
                CALL TAKESTEPCH(1)
                ! NEW GEOMETRY IS NOW IN COORDS
                IF (FIXCOM) CALL CENTRECOM(COORDS(1:3*NATOMS,1))
                PERTURBEDCOORDINATES(1:3*NATOMS,1) = COORDS(1:3*NATOMS,1)
             ELSE
! TRY TAKING STEP IN CARTESIANS; NEED TO PRESERVE DETAILED BALANCE AND EXPLORE ALL OF CONFIGURATION SPACE.
                PERTURBEDCOORDINATES = PERTURBGEOMETRY(PERTURBEDCOORDINATESSAVE)
                IF (FIXCOM) CALL CENTRECOM(PERTURBEDCOORDINATES(1:3*NATOMS,1))
                COORDS(1:3*NATOMS,1) = PERTURBEDCOORDINATES(1:3*NATOMS,1)
                CALL FILLICT(1)
             ENDIF
         ELSE
            PERTURBEDCOORDINATES=PERTURBGEOMETRY(PERTURBEDCOORDINATESSAVE) 
            IF (FIXCOM) CALL CENTRECOM(PERTURBEDCOORDINATES(1:3*NATOMS,1))
            COORDS=PERTURBEDCOORDINATES
         ENDIF

         CALL QUENCH(.FALSE.,1,LBFGS_ITERATIONS,DUMMY,NDUMMY,CONVERGED,COORDS)
         IF (EVAPREJECT) THEN
            IF (DEBUG) PRINT *, 'EVAPORATION DURING MINIMISATION'
            IF (DEBUG) PRINT *, 'OLDENERGY, CURRENTPOINTENERGY, POTEL=',OLDENERGY, CURRENTPOINTENERGY, POTEL
            CYCLE
         ENDIF
         OLDENERGY=CURRENTPOINTENERGY
         CURRENTPOINTENERGY=POTEL
         CURRENTPOINTCOORDINATES=COORDS


         IF ((CONVERGED.EQ.1).AND.(.NOT.EVAPREJECT)) THEN
            NQUENCHESSUCCESS=NQUENCHESSUCCESS+1
            BININDEXNEW=ENERGY2INDEX(CURRENTPOINTENERGY)
            !CALL ORDERQ4(NATOMS, CURRENTPOINTCOORDINATES, Q4ORDERPARAM)
            !CURRENTQ=Q4ORDERPARAM
            !PRINT *, BININDEXNEW, CURRENTPOINTENERGY, CURRENTQ, Q4ORDERPARAM


            IF (BININDEXNEW < 1 .OR.BININDEXNEW>HBINS) THEN
               IF (DEBUG) PRINT *, 'STRUCTURE OUTSIDE ENERGY RANGE. REJECTING MOVE'
               ACCEPTMOVE=.FALSE.
            ELSE 
         	IF ((BINSTRUCTURES).AND.(MOD(NQUENCHES, SAVENTH).EQ.0)) THEN
             	   CALL SAVEBINSTRUCTURES(CURRENTPOINTENERGY, CURRENTPOINTCOORDINATES, BININDEXNEW, MINIMANUMBER, .TRUE.)
           	 ENDIF
               CALL SAVEBINSTRUCTURES(CURRENTPOINTENERGY, CURRENTPOINTCOORDINATES, BININDEXNEW, MINIMANUMBER, .FALSE.)
               LNRATIO=LNWEIGHT(BININDEXOLD)-LNWEIGHT(BININDEXNEW)
               CALL RANDOM_NUMBER(HARVEST)
               LNHARVEST=LOG(HARVEST)
               IF ((LNRATIO>0.D0).OR.(LNRATIO>LNHARVEST)) THEN
                  ACCEPTMOVE=.TRUE.
               ELSE
                  ACCEPTMOVE=.FALSE.
               ENDIF
            ENDIF

            IF (DEBUG) PRINT *, 'EOLD, ENEW, IOLD, INEW, WOLD, WNEW, CONVERGED , RATIO'
            IF (DEBUG) PRINT *, OLDENERGY, CURRENTPOINTENERGY, BININDEXOLD, BININDEXNEW, LNWEIGHT(BININDEXOLD) , &
                     & LNWEIGHT(BININDEXNEW), CONVERGED, LNRATIO

            IF (ACCEPTMOVE) THEN 
               ! MOVE ACCEPTED
               !PRINT *, 'MOVING FROM BIN', BININDEXOLD, 'TO BIN', BININDEXNEW

               VISITS(BININDEXNEW)=VISITS(BININDEXNEW)+1
               VISITSTOTAL(BININDEXNEW)=VISITSTOTAL(BININDEXNEW)+1
               LNWEIGHT(BININDEXNEW)=LNWEIGHT(BININDEXNEW)+LNMODFAC
               DISTANCEOLD=CALCULATEDDISTANCE(CURRENTPOINTCOORDINATES, PERTURBEDCOORDINATES)
!              CALL MINDGMIN(CURRENTPOINTCOORDINATES,PERTURBEDCOORDINATES,NATOMS,MINDISTANCEOLD,PERIODIC,TWOD)
               CALL NEWMINDIST(CURRENTPOINTCOORDINATES,PERTURBEDCOORDINATES,NATOMS,MINDISTANCEOLD,PERIODIC,TWOD, &
    &                            'AX    ',.FALSE.,RIGID,DEBUG,RMAT)

               DISTANCE(BININDEXNEW)=DISTANCE(BININDEXNEW)+DISTANCEOLD
               MINDISTANCE(BININDEXNEW)=MINDISTANCE(BININDEXNEW)+MINDISTANCEOLD
               BININDEXOLD=BININDEXNEW
               PERTURBEDCOORDINATESSAVE=PERTURBEDCOORDINATES
            ELSE
               ! MOVE REJECTED
               !PRINT *, 'STAYING IN BIN', BININDEXOLD
               VISITS(BININDEXOLD)=VISITS(BININDEXOLD)+1
               VISITSTOTAL(BININDEXOLD)=VISITSTOTAL(BININDEXOLD)+1
               LNWEIGHT(BININDEXOLD)=LNWEIGHT(BININDEXOLD)+LNMODFAC
               DISTANCE(BININDEXOLD)=DISTANCE(BININDEXOLD)+DISTANCEOLD
               MINDISTANCE(BININDEXOLD)=MINDISTANCE(BININDEXOLD)+MINDISTANCEOLD
            ENDIF
         ELSE
         IF (DEBUG) PRINT *, 'OPTIMISATION UNSUCCESSFUL'
         ENDIF

         IF ((MOD(NQUENCHESSUCCESS,DUMPEVERYNTHQUENCH).EQ.0).AND.(NQUENCHESSINCELASTUPDATE > EQUIL)) THEN  
            ! RECORD STATISTICS
             OPEN(UNIT=421, FILE='LNWEIGHT.HIS', STATUS='UNKNOWN')
             DO I=1, HBINS
                WRITE(421, '(2G20.10)')  BINLABEL(I), LNWEIGHT(I)
             ENDDO
             CLOSE(421)
           
             OPEN(UNIT=421, FILE='DISTANCE.HIS', STATUS='UNKNOWN')
             DO I=1, HBINS
                WRITE(421, '(2G20.10)')  BINLABEL(I), DISTANCE(I)
             ENDDO
             CLOSE(421)
           
             OPEN(UNIT=421, FILE='MINDISTANCE.HIS', STATUS='UNKNOWN')
             DO I=1, HBINS
                WRITE(421, '(2G20.10)')  BINLABEL(I), MINDISTANCE(I)
             ENDDO
             CLOSE(421)
      
             OPEN(UNIT=422, FILE='VISITS.HIS', STATUS='UNKNOWN')
             DO I=1, HBINS
                WRITE(422, '(2G20.10)')  BINLABEL(I), VISITS(I)
             ENDDO
             CLOSE(422)
      
             OPEN(UNIT=422, FILE='VISITSTOTAL.HIS', STATUS='UNKNOWN')
             DO I=1, HBINS
                WRITE(422, '(2G20.10)')  BINLABEL(I), VISITSTOTAL(I)
             ENDDO
             CLOSE(422)
           
             OPEN(UNIT=422, FILE='LNMODFAC.RESTART', STATUS='UNKNOWN')
             WRITE(422, '(G20.10)') LNMODFAC
             CLOSE(422)
           
             OPEN(UNIT=422, FILE='NWL.RESTART', STATUS='UNKNOWN')
             WRITE(422, '(G20.10)') NWL
             CLOSE(422)
      
             OPEN(UNIT=421, FILE='MINIMANUMBER.HIS', STATUS='UNKNOWN')
             DO I=1, HBINS
                WRITE(421, '(2G20.10)')  BINLABEL(I), MINIMANUMBER(I)
             ENDDO
             CLOSE(421)


             CALL RECORD_STAT(LNWEIGHT,DISTANCE, MINDISTANCE, VISITSTOTAL, BINLABEL)

             ! CHECKING HISTOGRAM FOR CONVERGENCE

             FLAT=CHECKFLATNESS(VISITS,LNMODFAC,NWL, FROZENVISITS)
             IF (FLAT) THEN
                NQUENCHESSINCELASTUPDATE=0
                PRINT *, '--===VISITS HISTOGRAM SATISFIED FLATNESS CRITERION===--'
                LNMODFAC=HISTFACMUL*LNMODFAC
                PRINT *, 'LNMODFAC, EXP', LNMODFAC, EXP(LNMODFAC)
                PRINT *, 'UPDATING MODIFICATION FACTOR TO', LNMODFAC
                FROZENVISITS=VISITS
                VISITS=0
                NWL=NWL+1
                
                OPEN(UNIT=422, FILE='LNMODFAC.RESTART', STATUS='UNKNOWN')
                WRITE(422, '(G20.10)') LNMODFAC
                CLOSE(422)
              
                OPEN(UNIT=422, FILE='NWL.RESTART', STATUS='UNKNOWN')
                WRITE(422, '(G20.10)') NWL
                CLOSE(422)
             ENDIF
      

              PRINT *, NQUENCHES, ' QUENCHES COMPLETED'
         ENDIF

      NQUENCHES=NQUENCHES+1
      NQUENCHESSINCELASTUPDATE=NQUENCHESSINCELASTUPDATE+1
      ENDDO

      CONTAINS

!---======================================---`
      FUNCTION ENERGY2INDEX(CURRENTPOINTENERGY)
      USE COMMONS
      IMPLICIT NONE

      INTEGER ENERGY2INDEX

      REAL(8) CURRENTPOINTENERGY


      IF (NINT((CURRENTPOINTENERGY-HISTMIN)/HISTINT)<0) THEN
         ENERGY2INDEX=-1
      ELSE
         ENERGY2INDEX=NINT((CURRENTPOINTENERGY-HISTMIN)/HISTINT)+1
      ENDIF

      END FUNCTION ENERGY2INDEX


!---======================================---`
      REAL(8) FUNCTION GETDISPLACEMENT(STEP)
           IMPLICIT NONE
           REAL(8),INTENT(IN) :: STEP
           REAL(8) :: HARVEST
           CALL RANDOM_NUMBER(HARVEST)
           GETDISPLACEMENT=2.0D0*HARVEST*STEP-STEP
      END FUNCTION GETDISPLACEMENT

!---======================================---`
      FUNCTION PERTURBGEOMETRY(CURRENTPOINTCOORDINATES)
           USE COMMONS, ONLY: RADIUS,NATOMS,STEP
           IMPLICIT NONE

           REAL(8),DIMENSION(3*NATOMS,1) :: PERTURBGEOMETRY

           REAL(8),INTENT(IN) :: CURRENTPOINTCOORDINATES(3*NATOMS,1)
           INTEGER I, J

           PERTURBGEOMETRY=CURRENTPOINTCOORDINATES

           DO J=1, NATOMS
                DO
                     PERTURBGEOMETRY(3*(J-1)+1,1) = PERTURBGEOMETRY(3*(J-1)+1,1) + GETDISPLACEMENT(STEP(1))
                     PERTURBGEOMETRY(3*(J-1)+2,1) = PERTURBGEOMETRY(3*(J-1)+2,1) + GETDISPLACEMENT(STEP(1))
                     PERTURBGEOMETRY(3*(J-1)+3,1) = PERTURBGEOMETRY(3*(J-1)+3,1) + GETDISPLACEMENT(STEP(1))
                     IF ( PERTURBGEOMETRY(3*(J-1)+1, 1)**2 &
                      & + PERTURBGEOMETRY(3*(J-1)+2, 1)**2 &
                      & + PERTURBGEOMETRY(3*(J-1)+3, 1)**2 < RADIUS ) THEN
                          EXIT
                     ELSE
                          PERTURBGEOMETRY(3*(J-1)+1,1) = CURRENTPOINTCOORDINATES(3*(J-1)+1,1)
                          PERTURBGEOMETRY(3*(J-1)+2,1) = CURRENTPOINTCOORDINATES(3*(J-1)+2,1)
                          PERTURBGEOMETRY(3*(J-1)+3,1) = CURRENTPOINTCOORDINATES(3*(J-1)+3,1)
                     ENDIF
		ENDDO
           ENDDO
      END FUNCTION PERTURBGEOMETRY

!---======================================---`

      FUNCTION CALCULATEDDISTANCE(CURRENTPOINTCOORDINATES, PERTURBEDCOORDINATES)
      USE COMMONS
      IMPLICIT NONE

      INTEGER I
      REAL(8) CALCULATEDDISTANCE, CURRENTPOINTCOORDINATES(3*NATOMS,1), PERTURBEDCOORDINATES(3*NATOMS,1), &
              & X1(NATOMS, 1), Y1(NATOMS, 1), Z1(NATOMS, 1), X2(NATOMS, 1), Y2(NATOMS, 1), Z2(NATOMS, 1)

      
      DO I=1,NATOMS
         X1(I,1)=CURRENTPOINTCOORDINATES(3*(I-1)+1,1)
         Y1(I,1)=CURRENTPOINTCOORDINATES(3*(I-1)+2,1)
         Z1(I,1)=CURRENTPOINTCOORDINATES(3*(I-1)+3,1)
         X2(I,1)=PERTURBEDCOORDINATES(3*(I-1)+1,1)
         Y2(I,1)=PERTURBEDCOORDINATES(3*(I-1)+2,1)
         Z2(I,1)=PERTURBEDCOORDINATES(3*(I-1)+3,1)
      ENDDO

      CALCULATEDDISTANCE=DSQRT(SUM ( (X1(:,1)-X2(:,1))**2 + (Y1(:,1)-Y2(:,1))**2 + (Z1(:,1)-Z2(:,1))**2 ) )

      IF (DEBUG) PRINT *, 'DISTANCE' , CALCULATEDDISTANCE

      END FUNCTION CALCULATEDDISTANCE

!---======================================---`
      FUNCTION CHECKFLATNESS(VISITS,LNMODFAC,NWL, FROZENVISITS)
      USE COMMONS
      IMPLICIT NONE

      INTEGER VISITS(HBINS), N, I, VISITSNONZERO(HBINS),HMIN, HMAX, DELTAHK, NWL, FROZENVISITS(HBINS)
      LOGICAL CHECKFLATNESS, FLATBIN(HBINS)
      REAL(8) HDEV, LNMODFAC
      CHARACTER (LEN =256) FILENAME
      CHARACTER (LEN= 10)  ISTR


      CHECKFLATNESS=.FALSE.
      DELTAHK=0


      HMAX=MAXVAL(VISITS)
      DO I=1, HBINS
         IF (VISITS(I).NE.0) THEN
            VISITSNONZERO(I)=VISITS(I)
         ELSE
            VISITSNONZERO(I)=HUGE(HBINS)
         ENDIF
      ENDDO
      HMIN=MINVAL(VISITSNONZERO)
      IF (DEBUG) PRINT *, 'MIN AND MAX', HMIN, HMAX

      HDEV=(1.0D0*HMAX-HMIN)/(HMAX+HMIN)
    
      OPEN(UNIT=421, FILE='HISTFLUCTUATIONS', STATUS='UNKNOWN', POSITION='APPEND')
      WRITE(421, '(G20.10)') HDEV
      CLOSE(421)

      IF (VISITPROP) THEN
          !MINIMAL NUMBER OF VISITS SHOULD BE PROPORTIONAL TO 1/SQRT(LN(F))
 
          CHECKFLATNESS=.FALSE.
          FLATBIN=.FALSE.
 
          IF ((EQUIL.NE.-1).AND.(NWL.EQ.0)) THEN
             IF ((HDEV<HPERCENT).AND.(ABS(1.0D0*HMIN-HMAX)>HPERCENT)) CHECKFLATNESS=.TRUE.
          ELSE
             DO I=1, HBINS
                IF ((VISITS(I) > 1.0D0/SQRT(LNMODFAC)).OR.((VISITS(I).EQ.0).AND.(FROZENVISITS(I).EQ.0))) FLATBIN(I)=.TRUE.
             ENDDO
             IF (DEBUG)  PRINT *, 'FLATNESS BY BIN', FLATBIN 
             IF (ALL(FLATBIN)) CHECKFLATNESS=.TRUE.
          ENDIF
      ELSE
         ! HISTOGRAM FLATNESS CRITERION: SHOULD BE USED FOR DISCONNECTED PES IN THE INITIAL RUN
         ! WHERE 1/LNF CRITERION WILL NEVER BE SATISFIED.
         IF ((HDEV<HPERCENT).AND.(ABS(1.0D0*HMIN-HMAX)>HPERCENT)) CHECKFLATNESS=.TRUE.
      ENDIF

      DO I=1, HBINS
         IF (VISITS(I).NE.0) THEN
            DELTAHK=DELTAHK+(VISITS(I)-HMIN)
         ELSE
            DELTAHK=DELTAHK+0
         ENDIF
      ENDDO
      OPEN(UNIT=421, FILE='HISTSATURATION', STATUS='UNKNOWN', POSITION='APPEND')
      WRITE(421, '(G20.10)') DELTAHK
      CLOSE(421)

      WRITE (ISTR, '(I10)') NWL
      FILENAME="HISTSATURATION."//TRIM(ADJUSTL(ISTR))
      OPEN(UNIT=421,FILE=FILENAME, STATUS="UNKNOWN", FORM="FORMATTED", POSITION="APPEND")
      WRITE(421, '(G20.10)') DELTAHK
      CLOSE(421)

      IF (CHECKFLATNESS) THEN
         OPEN(UNIT=421, FILE='DELTAHK.VS.LNMODFAC', STATUS='UNKNOWN', POSITION='APPEND')
         WRITE(421, '(2G20.10)') LNMODFAC,DELTAHK
         CLOSE(421)
      ENDIF

      END FUNCTION CHECKFLATNESS

!---======================================---`
      SUBROUTINE RECORD_STAT(LNG_J,DISTANCE, MINDISTANCE, VISITSTOTAL, BINLABEL)
      USE COMMONS
      IMPLICIT NONE

      INTEGER VISITSTOTAL(HBINS), I, T, FULLBINS

      REAL(8)  MINDISTANCE(HBINS), KB, BINLABEL(HBINS),  &
              & A, B, AP, BP, AVLNG_J, TOTLNG_J, MINIMAL_D_J, &
              & DELTAT, SUMD_JNONMIN, SUMD_JMIN, &
              & AVD_JNONMIN, AVD_JMIN, SUMD2_JNONMIN, SUMD2_JMIN, AVD2_JNONMIN, AVD2_JMIN, &
	      & STD_DEVD_JNONMIN, STD_DEVD_JMIN, STD_DEVSMOOTHD_J, AVSMOOTHD2_J, AVSMOOTHD_J, &
              & TOTLNP_J, AVLNP_J

      REAL(8) LNP_JMIN(HBINS), P_JNONMIN(HBINS), LNP_JNONMIN(HBINS), LNG_J(HBINS), KAPPA, &
              & D_JNONMIN(HBINS), DISTANCE(HBINS), D_JMIN(HBINS), SCALEDLNG_JNONMIN(HBINS),&
              & P_JNORM(HBINS), SMOOTHD_JNONMIN(HBINS) , G_J(HBINS), G_JNORM(HBINS), P_J(HBINS), SCALEDLNP_JNONMIN(HBINS)


      IF (PERIODIC) THEN
         KAPPA=3*NATOMS-3
      ELSE
         KAPPA=3*NATOMS-6
      ENDIF

      DO I=1, HBINS
         IF (VISITSTOTAL(I).NE.0) THEN
            D_JNONMIN(I)=DISTANCE(I)/VISITSTOTAL(I)
         ELSE
            D_JNONMIN(I)=0.0D0
         ENDIF
      ENDDO 

      DO I=1, HBINS
         IF (VISITSTOTAL(I).NE.0) THEN
            D_JMIN(I)=MINDISTANCE(I)/VISITSTOTAL(I)
         ELSE
            D_JMIN(I)=0.0D0
         ENDIF
      ENDDO 

      MINIMAL_D_J=1.0D100
      DO I=1, HBINS
         IF (VISITSTOTAL(I).NE.0) THEN
           IF (D_JNONMIN(I) < MINIMAL_D_J) MINIMAL_D_J=D_JNONMIN(I)
         ENDIF
      ENDDO

     ! CALCULATE DENSITY OF MINIMA IN THE BS APPROXIMATION: P_J=[G_J*(DM/D_J)**KAPPA]/NORM*DELTAV 
     ! NOW WE WILL ACTUALLY BE STORING LN(P_J)

      FULLBINS=0
      TOTLNG_J=0.D0
      AVLNG_J=0.D0

      DO I=1, HBINS
         TOTLNG_J=TOTLNG_J+LNG_J(I)
         FULLBINS=FULLBINS+1
      ENDDO

      AVLNG_J=TOTLNG_J/FULLBINS

      DO I=1, HBINS
         IF (VISITSTOTAL(I).NE.0) THEN
            SCALEDLNG_JNONMIN(I)=LNG_J(I)-AVLNG_J
         ELSE
            SCALEDLNG_JNONMIN(I)=0.D0
         ENDIF
      ENDDO
 
      DO I=1, HBINS
         IF (VISITSTOTAL(I).NE.0) THEN
            G_J(I)=EXP(SCALEDLNG_JNONMIN(I))
         ELSE
            G_J(I)=0.D0
         ENDIF
      ENDDO

	DO I=1,HBINS
	    IF (VISITSTOTAL(I).NE.0) THEN
	       G_JNORM(I)=G_J(I)/(SUM(G_J)*HISTINT)
	    ELSE
	       G_JNORM(I)=0.D0
            ENDIF
        ENDDO

         
      FULLBINS=0
      TOTLNP_J=0.D0
      AVLNP_J=0.D0

      DO I=1, HBINS
         IF (VISITSTOTAL(I).NE.0) THEN
            LNP_JNONMIN(I)=LNG_J(I)-(KAPPA+3)*LOG(D_JNONMIN(I))
            TOTLNP_J=TOTLNP_J+LNP_JNONMIN(I)
            FULLBINS=FULLBINS+1 
         ELSE 
            LNP_JNONMIN(I)=-HUGE(LNG_J(I))
         ENDIF
      ENDDO

      AVLNP_J=TOTLNP_J/FULLBINS

      DO I=1, HBINS
         IF (VISITSTOTAL(I).NE.0) THEN
            SCALEDLNP_JNONMIN(I)=LNP_JNONMIN(I)-AVLNP_J
         ELSE
            SCALEDLNP_JNONMIN(I)=0.D0
         ENDIF
      ENDDO

      DO I=1, HBINS
         IF (VISITSTOTAL(I).NE.0) THEN
            P_JNONMIN(I)=EXP(SCALEDLNP_JNONMIN(I))
         ELSE
            P_JNONMIN(I)=0.D0
         ENDIF
      ENDDO

        DO I=1,HBINS
            IF (VISITSTOTAL(I).NE.0) THEN
               P_JNORM(I)=P_JNONMIN(I)/(SUM(P_JNONMIN)*HISTINT)
            ELSE
               P_JNORM(I)=0.D0
            ENDIF
        ENDDO


      OPEN(UNIT=421, FILE='BL.PJNORM.LNGJ.DJNM.DJM.VT.HIS', STATUS='UNKNOWN')
      DO I=1, HBINS
         WRITE(421, '(6G20.10)')  BINLABEL(I), P_JNORM(I), LNG_J(I), D_JNONMIN(I), D_JMIN(I), VISITSTOTAL(I)
      ENDDO
         CLOSE(421)

      END SUBROUTINE RECORD_STAT

!---======================================---
    SUBROUTINE SAVEBINSTRUCTURES(CURRENTPOINTENERGY, CURRENTPOINTCOORDINATES, BININDEX, MINIMANUMBER, WRITESTRUCT)
        USE COMMONS, ONLY:NATOMS, HBINS,BQMAX, CHRMMT, ZSYM
        USE MODCHARMM, ONLY: OSASAT, RPRO, ODIHET
        IMPLICIT NONE

        INTEGER BININDEX, JB,  MINIMANUMBER(HBINS), JC
        INTEGER, SAVE :: BINENSAVED=0
        REAL(8) CURRENTPOINTENERGY, CURRENTPOINTCOORDINATES(3*NATOMS, 1), Q4ORDERPARAM
        REAL(8) DIHEORDERPARAM,SASAORDERPARAM
        LOGICAL NEWBINENERGY, YESNO, WRITESTRUCT
        CHARACTER (LEN =256)  BINNAME
        CHARACTER (LEN= 10)  ISTR
        REAL(8),ALLOCATABLE, SAVE :: BINENERGIES(:)
        INTEGER,ALLOCATABLE, SAVE :: BINENIMPORTANCEINDEX(:)
        
         IF (BINENSAVED.EQ.0) THEN
           ALLOCATE(BINENERGIES(100000000))
           BINENERGIES=0.0
           ALLOCATE(BINENIMPORTANCEINDEX(100000000))
           BINENIMPORTANCEINDEX=0
         ENDIF
      
         IF (BINENSAVED.EQ.SIZE(BINENERGIES)) THEN
            RETURN
         ENDIF

         INQUIRE(FILE='BINENERGIES', EXIST=YESNO)

         NEWBINENERGY=.TRUE.
         DO JB=1, BINENSAVED
             IF (ABS(BINENERGIES(JB)-CURRENTPOINTENERGY).LE.BQMAX) THEN
                NEWBINENERGY=.FALSE.
             ENDIF
         ENDDO

         IF (NEWBINENERGY) THEN
            BINENSAVED=BINENSAVED+1
            !CALL ORDERQ4(NATOMS, CURRENTPOINTCOORDINATES, Q4ORDERPARAM)
            IF (ODIHET) CALL CHCALCDIHE(DIHEORDERPARAM,CURRENTPOINTCOORDINATES(1:3*NATOMS,1))
            IF (OSASAT) CALL ORDER_SASA(SASAORDERPARAM,RPRO,CURRENTPOINTCOORDINATES(1:3*NATOMS:3,1), &
                      & CURRENTPOINTCOORDINATES(2:3*NATOMS:3,1),CURRENTPOINTCOORDINATES(3:3*NATOMS:3,1))
            BINENERGIES(BINENSAVED)=CURRENTPOINTENERGY
            IF (WRITESTRUCT)  THEN
                IF ((BINENSAVED.EQ.1).AND.(YESNO)) THEN
                   OPEN(UNIT=1979,FILE='BINENERGIES',STATUS='OLD')
                ELSE
                   OPEN(UNIT=1979,FILE='BINENERGIES',STATUS='UNKNOWN',POSITION='APPEND')
                ENDIF
! JMC                WRITE(1979,'(2G20.10)') CURRENTPOINTENERGY, Q4ORDERPARAM
                IF (ODIHET.AND.OSASAT) THEN
                   WRITE(1979,'(3G20.10)') CURRENTPOINTENERGY, DIHEORDERPARAM, SASAORDERPARAM
                ELSEIF (OSASAT) THEN
                   WRITE(1979,'(2G20.10)') CURRENTPOINTENERGY, SASAORDERPARAM
                ELSEIF (ODIHET) THEN
                   WRITE(1979,'(2G20.10)') CURRENTPOINTENERGY, DIHEORDERPARAM
                ELSE
                   WRITE(1979,'(G20.10)') CURRENTPOINTENERGY
                ENDIF
                CLOSE (1979)
                WRITE (ISTR, '(I10)') BININDEX
                BINNAME="BINSTRUCTURES."//TRIM(ADJUSTL(ISTR))
                IF ((BINENSAVED.EQ.1).AND.(YESNO)) THEN
                   OPEN(UNIT=1979,FILE=BINNAME, STATUS="OLD", FORM="FORMATTED")
                ELSE
                   OPEN(UNIT=1979,FILE=BINNAME, STATUS="UNKNOWN", FORM="FORMATTED", POSITION="APPEND")
                ENDIF
                WRITE(1979,'(I10)') NATOMS
                WRITE(1979,'(A,1G20.10)') '     STRUCTURE WITH ENERGY ', CURRENTPOINTENERGY
                IF (CHRMMT) THEN
                   DO JB=1,NATOMS
                      WRITE(1979,'(A,1X,3F20.10)') ZSYM(JB)(1:1),(CURRENTPOINTCOORDINATES(3*(JB-1)+JC,1),JC=1,3)
                   ENDDO
                ELSE
                   WRITE(1979,30) (CURRENTPOINTCOORDINATES(JB,1),JB=1,3*NATOMS)
30                 FORMAT('LA ',3F20.10)
                ENDIF
                CLOSE (1979)
             ENDIF
             MINIMANUMBER(BININDEX)=MINIMANUMBER(BININDEX)+1
         ENDIF

! IMPORTANCE INDEX 

 	 IF ((.NOT.NEWBINENERGY).AND.(WRITESTRUCT)) THEN 
		OPEN(UNIT=1979,FILE="BINENIMPORTANCEINDEX", STATUS="UNKNOWN", FORM="FORMATTED")
		DO JB=1, BINENSAVED
	             IF (ABS(BINENERGIES(JB)-CURRENTPOINTENERGY).LE.BQMAX) THEN
		     BINENIMPORTANCEINDEX(JB)=BINENIMPORTANCEINDEX(JB)+1
             	     ENDIF
         	ENDDO
		DO JB=1, BINENSAVED
		WRITE(1979,'(1G20.10, I10)') BINENERGIES(JB), BINENIMPORTANCEINDEX(JB)
		ENDDO
		CLOSE (1979)
	 ENDIF
 
         IF (BINENSAVED.EQ.SIZE(BINENERGIES)) THEN
            IF (ALLOCATED(BINENERGIES)) DEALLOCATE(BINENERGIES)
         ENDIF

         END SUBROUTINE SAVEBINSTRUCTURES



      END SUBROUTINE BASINSAMPLING

