!OP226>=================================== 
!OP226> GPL LICENSE INFO {{{
!  GMIN: A PROGRAM FOR FINDING GLOBAL MINIMA
!  COPYRIGHT (C) 1999-2006 DAVID J. WALES
!  THIS FILE IS PART OF GMIN.
!
!  GMIN IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!  IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!  THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!  (AT YOUR OPTION) ANY LATER VERSION.
!
!  GMIN IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!  BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!  MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!  GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!
!  YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!  ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!  FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!OP226> }}}
!OP226>=================================== 
!
!> \NAME COMMONS
!> \BRIEF DECLARATIONS FOR COMMON VARIABLES 
!> \PARAM MCSTEPS(3)
!> \PARAM NPAR 
!> \PARAM NSEED 
!
!OP226>=================================== 
      MODULE COMMONS
      USE NOA
      IMPLICIT NONE
      SAVE
      INTEGER :: NATOMS, NACCEPT, MAXIT, NTARGETS, NN, MM, NPAR, TIPID, PAHID, NSYMREM=0, NFREEZE, NSAVEINTE, &
     &        NINTV, NSEED, NVEC, NS, NSSTOP, MAXIT2, NSAVE, SHELLMOVEMAX, HPTGRP, NFIX, CURRENTIMP,&
     &        MCSTEPS(3), NRUNS, NVAR, MYPOWER, XMUL,  NTAB, NCARBON, NCOOP, NSYMINTERVAL, QDLIMIT, COULN, &
     &        NSUPER, NSACCEPT, NSUPERSTEP, GMODES, DUMPXYZUNIT, DUMPVUNIT, QUENCHFRQ, CHNRES, &
     &        NEVL, NEVS, NVECTORS, MUPDATE, LSYS, NHSMOVE, NRENORM, NRELAX, NHSRESTART, NRENSTUCK,&
     &        HBINS, NRBSITES, NRBSITES1, NPS, GATOM, NMSBSAVE, MAXSAVE, NSYMQMAX, EQUIL, TPAHA, ISTEP, &
     &        NINTS, NUMBEROFTRAJECTORIES, &
     &        MCCYCLES, MCCYCLESEQUILIBRATION, TARGETWL, NTEMPPOINTS, SAVENTH, DUMPEVERYNTHQUENCH, NSPLINE, HWINDOWS, & 
     &        LHBINS, SAMPLEDBINS, MYNODE, NENRPER, DUMPINT, MYUNIT, PRTFRQ, BSPTDUMPFRQ, NPERMGROUP, NMOVABLEATOMS, &
     &        CPS, CPF, ACKLANDID, PATOM1, PATOM2, CSMGPINDEX, CSMGUIDEGPINDEX, CSMSTEPS, CSMQUENCHES, CSMMAXIT, &
     &        MYEUNIT, MYMUNIT, MYBUNIT, MYRUNIT, MYPUNIT
 
     DOUBLE PRECISION RHO, GAMMA, SIG, SCEPS, SCC, TOLB, T12FAC, XMOVERENORM, RESIZE, QTSALLIS, &
     &                 CQMAX, RADIUS, BQMAX,  MAXBFGS, DECAYPARAM, SYMTOL1, SYMTOL2, SYMTOL3, SYMTOL4, SYMTOL5, &
     &                 ECONV, TOLD, TOLE, SYMREM(120,3,3), GMAX, CUTOFF, PCUT, EXPFAC, EXPD, CENTX, CENTY, CENTZ, &
     &                 BOXLX, BOXLY, BOXLZ, PCUTOFF, SUPSTEP, SQUEEZER, SQUEEZED, COOPCUT, STOCKMU, STOCKLAMBDA, &
     &                 TFAC(3), RMS, TEMPS, SACCRAT, CEIG, PNEWJUMP, EAMP, DISTFAC, ODDCHARGE, COULQ, COULSWAP, &
     &                 COULTEMP, APP, AMM, APM, XQP, XQM, ALPHAP, ALPHAM, ZSTAR, COMP, DGUESS, GUIDECUT, EFAC,& 
     &                 TRENORM, HISTMIN, HISTMAX, HISTFAC, EPSSPHERE, FINALCUTOFF, SHELLPROB, RINGROTSCALE, &
     &                 HISTFACMUL, HPERCENT, AVOIDDIST, MAXERISE, MAXEFALL, TSTART, MATDIFF, STICKYSIG, SDTOL, &
     &                 MINIMALTEMPERATURE, MAXIMALTEMPERATURE, SWAPPROB, HDISTCONSTRAINT, COREFRAC, TSTAR, &
     &                 RK_R, RK_THETA,ARMA,ARMB, EXTRAPOLATIONPERCENT, LNHARMFREQ, PTEMIN, PTEMAX, PTTMIN, PTTMAX, EXCHPROB, &
     &                 PTSTEPS, NEQUIL, NQUENCH, COLDFUSIONLIMIT, NEWRES_TEMP, MINOMEGA, LJSIGMA, LJEPSILON, TAUMAX, &
     &                 TAUMAXFULL, CPFACTORSG, CPFACTORFG, VGWTOL, ABTHRESH, ACTHRESH, CSMPMAT(3,3), &
!
!   PARAMETERS FOR ANISOTROPIC POTENTIALS
!
!    DC430 >
     &                 EPSR, GBKAPPA, GBKAPPRM, GBMU,GBNU, GBSIGNOT, GBEPSNOT, GBCHI, GBCHIPRM, &
     &                 SIGNOT, EPSNOT, SIGMAF, INVKAP, ESA(3), LPRSQ, LSQDFR, GBDPMU, GBDPEPS, GBDPFCT, &
     &                 PYSIGNOT, PYEPSNOT, PYA1(3), PYA2(3), PYDPMU, PYDPEPS, PYDPFCT, &
     &                 LWRCUT, LWCNSTA, LWCNSTB, LWRCUTSQ, LWRCUT2SQ, DELRC, &    
     &                 DBEPSBB, DBEPSAB, DBSIGBB, DBSIGAB, DBPMU, EFIELD, GEMRC, MREQ, &
     &                 EPS11, EPS22, EPS12, MRHO11, MRHO22, MRHO12, REQ11, REQ22, REQ12, &
     &                 RHOCC0, RHOCC10, RHOCC20,  RHOHH0, RHOHH10, RHOHH20, RHOCH0, RHOC10H, &
     &                 RHOCH10, RHOC20H, RHOCH20, ALPHACC, ALPHAHH, ALPHACH, DC6CC, DC6HH, DC6CH, KKJ, CCKJ, &
     &                 GBANISOTROPYR,GBWELLDEPTHR,PARAMA1,PARAMB1,PARAMC1,PARAMA2,PARAMB2,PARAMC2,PSIGMA0(2),PEPSILON0,&
     &                 PEPSILON1(3),PSCALEFAC1(2),PSCALEFAC2(2),PYA11(3),PYA21(3),PYA12(3),PYA22(3), &
     &                 PEPSILONATTR(2),PSIGMAATTR(2), PYOVERLAPTHRESH, LJSITECOORDS(3), &
     &                 MSTART,MFINISH,MBSTART1,MBFINISH1,MBSTART2,MBFINISH2,MBHEIGHT1,MBHEIGHT2,ME1,ME2,ME3, &
     &                 BSPTQMAX, BSPTQMIN, PFORCE, CSMNORM, CSMGUIDENORM, CSMEPS
!
!
      LOGICAL DEBUG, TARGET, MORSET, CUTT, SEEDT, CENT, TSALLIST, FREEZECORE, NEWJUMP, RENORM, CAPSID, FREEZE, &
     &        OTPT, LJMFT, STRANDT, PAHT, SWT, MSTRANST, STOCKT, STICKYT, BLNT, MYSDT, FREEZERES, CENTXY, &
     &        MSORIGT, SQUEEZET, PERIODIC, SCT, RESIZET, TIP, RIGID, Q4T, MPIT, JMT, LJCOULT, SETCENT, &
     &        SORTT, HIT, SAVEQ, PARALLELT, FIXD, RKMIN, BSMIN, PERMDIST, PERMOPT, BSWL, BSPT, BSPTRESTART, &
     &        SYMMETRIZE, SYMMETRIZECSM, DUMPT, NEON, ARGON, P46, NORESET, TABOOT, EVSTEPT, PACHECO, DL_POLY, QUCENTRE, &
     &        STAR, PLUS, TWOPLUS, GROUND, DIPOLE, DFTBT, SW, SUPERSTEP, EAMLJT, PBGLUET, TRACKDATAT, &
     &        EAMALT, ALGLUET, MGGLUET, GUPTAT, FST, DECAY, COOP, FIXBIN, GAUSST, QUENCHDOS, FIXDIHEFLAG, &
     &        FRAUSIT, ANGST, SELFT, STEPOUT, WENZEL, THRESHOLDT, THOMSONT, MULLERBROWNT, CHARMMENERGIES, &
     &        PROJ, RGCL2, TOSI, WELCH, AXTELL, AMBER, FIXIMAGE, BINARY, SHIFTCUT, ARNO, TUNNELT, TWOD, & 
     &        BLJCLUSTER, COMPRESST, FIX, FIXT, BFGS, LBFGST, DBRENTT, DZTEST, FNI, FAL, CPMD, TNT, ZETT1, &
     &        ZETT2, RESTART, CONJG, NEWRESTART, AVOID, NATBT, DIFFRACTT, CHRMMT, INTMINT, LB2T, & 
     &        PTMC, BINSTRUCTURES, PROGRESS, MODEL1T, NEWRESTART_MD, CHANGE_TEMP, NOCISTRANS, CHECKCHIRALITY, &
     &        GBT, GBDT, GBDPT, GEMT, LINRODT, PYGT, RADIFT, PYGDPT, DBPT, DBPTDT, DBLPYT, DMBLMT, EFIELDT, PAHAT, STOCKAAT, &
     &        MSGBT, MSPYGT, MSTBINT, MMRSDPT, MSSTOCKT, LWOTPT, NCAPT, NPAHT, NTIPT, PAHW99T, ELLIPSOIDT, GAYBERNET,& 
     &        MULTPAHAT, TDHDT, WATERDCT, WATERKZT, CHECKDT, CHECKMARKOVT, & 
     &        TETHER, HISTSMOOTH, VISITPROP, ARMT, FIXEDENDMOVET, FIXCOM, RESTORET, QUADT, AMHT, MOVESHELLT, QDT, QD2T, &
     &        PARAMONOVPBCX, PARAMONOVPBCY, PARAMONOVPBCZ, PARAMONOVCUTOFF, GAYBERNEDCT, UNFREEZERES, FREEZEALL, &
     &        PROJIT, PROJIHT, LEAPDIHE, DUMPQUT, PARAMONOVT, LJSITE, BLJSITE, LJSITEATTR, DUMPSTEPST, &
     &        AMBERT, RANDOMSEEDT, PYGPERIODICT, LJCAPSIDT, PYBINARYT, SWAPMOVEST, MOVABLEATOMST, LIGMOVET,DUMPSTRUCTURES, &
     &        LJSITECOORDST, VGW, ACKLANDT, G46, DF1T, PULLT, LOCALSAMPLET, CSMT, A9INTET, INTERESTORE, COLDFUSION, &
     &        CSMGUIDET, MULTISITEPYT

     

!
! CSW34> FREEZEGROUP VARIABLES
!
      INTEGER :: GROUPCENTRE
      DOUBLE PRECISION :: GROUPRADIUS
      CHARACTER (LEN=2) :: FREEZEGROUPTYPE
      LOGICAL :: FREEZEGROUPT
! END

!
! CSW34> DONTMOVE VARIABLES
!
      INTEGER :: NDONTMOVE, DONTMOVECENTRE
      DOUBLE PRECISION :: DONTMOVERADIUS
      CHARACTER (LEN=2) :: DONTMOVEGROUPTYPE
      LOGICAL :: DONTMOVET, DONTMOVEGROUPT, DONTMOVEREST, DONTMOVEALL, DOMOVEREST
      LOGICAL, ALLOCATABLE :: DONTMOVE(:),DONTMOVERES(:)

!
! CSW34> PAIRDIST VARIABLES
!
      INTEGER :: NPAIRS
      INTEGER, ALLOCATABLE :: PAIRDIST(:,:)
      LOGICAL :: PAIRDISTT

      INTEGER  NGBSITE, NPYSITE, PYBINARYTYPE1, PYSWAP(3), MAXINTERACTIONS
   
      DOUBLE PRECISION :: DZP1, DZP2, DZP3, DZP4, DZP5, DZP6, DZP7
      LOGICAL :: FIELDT, OHT, IHT, TDT, D5HT
      DOUBLE PRECISION :: FOH, FIH, FTD, FD5H

      CHARACTER(LEN=80) :: SYS
      CHARACTER(LEN=80) :: INFILE=''
      CHARACTER(LEN=1), ALLOCATABLE :: BEADLETTER(:), BLNSSTRUCT(:)
      CHARACTER(LEN=130) DUMPFILE, MYFILENAME, INTEDUMPFILE

      INTEGER NUMPRO_AMH, NINT_AMH, SEED_AMH,HARM_AMH, I1_AMH
      CHARACTER AMINOA(21)*3
      DATA (AMINOA(I1_AMH),I1_AMH=1,21)/'ALA','ARG','ASN','ASP','CYS','GLN','GLU','GLY', &
           'HIS','ILE','LEU','LYS','MET','PHE','PRO','SER','THR','TRP','TYR','VAL','INI'/

      DOUBLE PRECISION :: HESS(1,1)
!     DOUBLE PRECISION HESS(3*MXATMS,3*MXATMS)
      CHARACTER(LEN=3) :: CSMGP, CSMGUIDEGP


!|GD351> EXTRA VARIABLES FOR PATCHY AND ASAKURA-OOSAWA MODELS
       LOGICAL :: PATCHY, ASAOOS
       DOUBLE PRECISION :: SIGMASQ, RANGESQ, FACTOR 
!<GD351|


!   ALLOCATABLES

      INTEGER,ALLOCATABLE,DIMENSION(:) :: MOVABLEATOMLIST         ! A LIST CONTAINING THE MOVABLE ATOM INDICES
      LOGICAL,ALLOCATABLE,DIMENSION(:) :: MOVABLEATOMLISTLOGICAL  ! IS ATOM I MOVABLE?

      INTEGER, ALLOCATABLE, DIMENSION(:) :: NT, NQ, BLOCK, JUMPINT, JUMPTO, NCORE, NSURFMOVES  ! DIMENSION WILL BE NPAR
      INTEGER, ALLOCATABLE, DIMENSION(:) :: HISTVALS, LHISTVALS  ! DIMENSION DECLARED HBINS IN KEYWORD
      INTEGER, ALLOCATABLE :: NPERMSIZE(:), PERMGROUP(:)
      INTEGER, ALLOCATABLE :: NSETS(:)
      INTEGER, ALLOCATABLE :: SETS(:,:)
      INTEGER, ALLOCATABLE :: PERMUTE(:,:)
      INTEGER, ALLOCATABLE :: NCRBN(:), NCMP(:)

      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: TEMP, STEP, OSTEP, ASTEP, ACCRAT, EPREV ! DIMENSION WILL BE NPAR 
      DOUBLE PRECISION, ALLOCATABLE :: TARGETS(:) ! ALLOCATED NTARGETS IN KEYWORD.F
      DOUBLE PRECISION, ALLOCATABLE :: ESAVE(:,:) ! DIMENSION WILL BE NTAB,NPAR
      DOUBLE PRECISION, ALLOCATABLE :: XINSAVE(:,:) ! DIMENSION WILL BE NTAB,NPAR
      DOUBLE PRECISION, ALLOCATABLE :: HDIST(:), HWEIGHT(:) ! DIMENSION DECLARED HISTBINMAX IN KEYWORD
      DOUBLE PRECISION, ALLOCATABLE :: VEC(:) ! DIMENSION WOULD BE NVEC - NOT USED
      DOUBLE PRECISION, ALLOCATABLE :: MASSES(:)

      LOGICAL, ALLOCATABLE, DIMENSION(:) :: FIXBOTH, FIXTEMP, FIXSTEP, JUMPMOVE, JDUMP, TMOVE, OMOVE ! DIMENSION WILL BE NPAR
      LOGICAL, ALLOCATABLE, DIMENSION(:) :: SHELLMOVES ! DIMENSION WILL BE NPAR
      LOGICAL, ALLOCATABLE ::  IGNOREBIN(:) ! WILL BE HBINS
      LOGICAL, ALLOCATABLE, DIMENSION(:) :: FROZENRES  ! NATOMS FOR SAFETY 
      LOGICAL, ALLOCATABLE, DIMENSION(:) :: FROZEN  !  NATOMS

      INTEGER, ALLOCATABLE, DIMENSION(:) ::  IATNUM     
      INTEGER,ALLOCATABLE :: ANV(:,:,:)
      DOUBLE PRECISION, ALLOCATABLE :: LJREP_BLN(:,:), LJATT_BLN(:,:), A_BLN(:), B_BLN(:), C_BLN(:), D_BLN(:)
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) :: TCOORDS
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: VT
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) :: COORDS,COORDSO
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) ::  VAT,  VATO    
      DOUBLE PRECISION, ALLOCATABLE :: SITE(:,:), RBUV(:,:), RBSTLA(:,:), STCHRG(:), DPMU(:)
      DOUBLE PRECISION, ALLOCATABLE :: MSBCOORDS(:,:)
      DOUBLE PRECISION, ALLOCATABLE :: MSBE(:)
      DOUBLE PRECISION, ALLOCATABLE :: GAUSSKK(:,:)
      DOUBLE PRECISION, ALLOCATABLE :: GAUSSEE(:), GKSMALL(:)
      DOUBLE PRECISION, ALLOCATABLE :: CSMIMAGES(:)
      DOUBLE PRECISION, ALLOCATABLE :: QMINPCSMAV(:,:), CSMAV(:), QMINAV(:), PTGP(:,:,:), PTGPGUIDE(:,:,:)
      CHARACTER(LEN=2), ALLOCATABLE, DIMENSION(:) :: ZSYM   
      CHARACTER(LEN=4), ALLOCATABLE, DIMENSION(:) :: PTGROUP ! DIMENSION WILL BE NPAR
      REAL, ALLOCATABLE :: XVEX(:)  !  SINGLE PRECISION!!!!

      DOUBLE PRECISION, ALLOCATABLE     :: PYA1BIN(:,:), PYA2BIN(:,:)

      CONTAINS

      SUBROUTINE MODCOMMONINIT
         IMPLICIT NONE
         
         NATOMS = NUMBER_OF_ATOMS
         ALLOCATE( ANV(NATOMS,NATOMS,3))         
      END SUBROUTINE MODCOMMONINIT

      SUBROUTINE MODCOMMONDEINIT
         IMPLICIT NONE
         
         IF (ALLOCATED(ANV)) DEALLOCATE(ANV)
      END SUBROUTINE MODCOMMONDEINIT
END MODULE COMMONS
