!OP226> GPL LICENSE INFO {{{
!  GMIN: A PROGRAM FOR FINDING GLOBAL MINIMA
!  COPYRIGHT (C) 1999-2006 DAVID J. WALES
!  THIS FILE IS PART OF GMIN.
!
!  GMIN IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!  IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!  THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!  (AT YOUR OPTION) ANY LATER VERSION.
!
!  GMIN IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!  BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!  MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!  GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!
!  YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!  ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!  FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!
!OP226>}}}

MODULE NOA
      USE MODAMBER9 , ONLY : INPCRD
      IMPLICIT NONE
      SAVE
      INTEGER :: NUMBER_OF_ATOMS

      CONTAINS

      SUBROUTINE COUNTATOMS(MYUNIT)
!OP226> DECLARATIONS {{{ 
      IMPLICIT NONE
      INTEGER :: EOF,NRES,SEQ(500),I_RES,NOGLY,GLY, MYUNIT
      LOGICAL :: YESNO, YESNOA, YESNOC, YESNOAMH, YESNOA9
      CHARACTER(LEN=5) TARFL
      CHARACTER(LEN=10)  CHECK
      CHARACTER(LEN=80) MYLINE,INPCRD1
!OP226>}}} 

      YESNO=.FALSE.
      YESNOA=.FALSE.
      YESNOAMH=.FALSE.
      YESNOA9=.FALSE.
!
!  IF THE CURRENT WORKING DIRECTORY CONTAINS MORE THAN ONE OF THESE FILES
!  THEN THE PRECEDENCE IS COORDS, THEN INPUT.CRD, THEN COORDS.AMBER
!  OPTIM DOES THIS A BIT BETTER BY CALLING GETPARAMS FIRST TO SEE IF
!  WE ARE ACTUALLY DOING AMBER OR CHARMM. 
!
      INQUIRE(FILE='PRO.LIST',EXIST=YESNOAMH)
      INQUIRE(FILE='COORDS',EXIST=YESNO)
      INQUIRE(FILE='COORDS.AMBER',EXIST=YESNOA)
      INQUIRE(FILE='INPUT.CRD',EXIST=YESNOC)
      INQUIRE(FILE='COORDS.INPCRD',EXIST=YESNOA9)

      NUMBER_OF_ATOMS=0

      IF (YESNO) THEN
         OPEN(UNIT=7,FILE='COORDS',STATUS='OLD')
         DO
            READ(7,*,IOSTAT=EOF)
            IF (EOF==0) THEN
               NUMBER_OF_ATOMS = NUMBER_OF_ATOMS + 1
            ELSE
               EXIT
            ENDIF
         ENDDO
        ELSEIF (YESNOAMH) THEN
         OPEN(UNIT=30,FILE='PRO.LIST',STATUS='OLD',FORM='FORMATTED')
         READ (30,1000)TARFL
1000     FORMAT(A5)
         CLOSE(30)

          OPEN(30,FILE='PROTEINS/'//TARFL,STATUS='OLD')
            READ(30,*)
            READ(30,*)NRES
            IF (NRES.GT.500) THEN
                WRITE(6,*) 'FAILURE NRES GR THAN 500 COUNTATOMS'
                STOP
            ENDIF
            READ (30,25)(SEQ(I_RES),I_RES=1,NRES)
!            WRITE(6,25)(SEQ(I_RES),I_RES=1,NRES)
25         FORMAT(25(I2,1X))
          CLOSE(30)

          NOGLY = 0
          GLY = 0

           DO I_RES=1,NRES
             IF (SEQ(I_RES).NE.8) NOGLY = NOGLY +1
             IF (SEQ(I_RES).EQ.8) GLY = GLY +1
           ENDDO

            NUMBER_OF_ATOMS = NOGLY*3 + GLY*2
      ELSE IF (YESNOA9) THEN
!         OPEN(UNIT=7,FILE='COORDS.GAYBERNE',STATUS='OLD')
!         PRINT '(A)','READING COORDINATES FROM FILE COORDS.GAYBERNE'

         INPCRD1='COORDS.INPCRD'
!         INPCRD1=TRIM(ADJUSTL(INPCRD1))
         CALL AMBERINTERFACE(NUMBER_OF_ATOMS,1,INPCRD1,MYUNIT)

      ELSEIF (YESNOC) THEN
         OPEN(UNIT=7,FILE='INPUT.CRD',STATUS='OLD')
         DO
           READ(7,*) MYLINE
           IF (MYLINE(1:1)=='*') THEN ! SAT THIS IS THE GODDAMN CHARMM COMMENT LINE
              CYCLE
           ELSE
              READ(MYLINE,*) NUMBER_OF_ATOMS
              EXIT
           ENDIF
         ENDDO

! DAE WE ALSO NEED TO FIND OUT WHAT MAXAIM IS IN CHARMM, AND SET MXATMS IN OPTIM TO BE THE SAME, SO THAT THOSE ARRAYS WHICH
! ARE PASSED BETWEEN THE TWO CAN BE DECLARED CORRECTLY. MXATMS IS NOW STORED IN MODMXATMS.

         CALL GETMAXAIM
         WRITE(MYUNIT,'(A,I8)') 'COUNTATOMS> NUMBER_OF_ATOMS=',NUMBER_OF_ATOMS
      ELSEIF (YESNOA) THEN
         OPEN(UNIT=7,FILE='COORDS.AMBER',STATUS='OLD')
         DO
            READ(7,'(A3)',IOSTAT=EOF) CHECK
            IF (EOF.LT.0) THEN
               PRINT *,'END OF FILE BEFORE ALL INFORMATION SPECIFIED'
               STOP
            ENDIF
            IF (CHECK.EQ.'END' .OR. CHECK.EQ.'END' .OR. CHECK.EQ.'END') THEN
               CLOSE(7)
               EXIT
            ENDIF
            NUMBER_OF_ATOMS = NUMBER_OF_ATOMS + 1
         ENDDO
      ELSE
         PRINT '(A)','ERROR - NO COORDS, INPUT.CRD, COORDS.INPCRD OR COORDS.AMBER FILE'
         STOP
      ENDIF

      CLOSE(7)

!     PRINT *, NUMBER_OF_ATOMS, ' ATOMS IN THE SYSTEM'
      
      END SUBROUTINE COUNTATOMS

END MODULE NOA
