C   GMIN: A PROGRAM FOR FINDING GLOBAL MINIMA
C   COPYRIGHT (C) 1999-2006 DAVID J. WALES
C   THIS FILE IS PART OF GMIN.
C
C   GMIN IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C   (AT YOUR OPTION) ANY LATER VERSION.
C
C   GMIN IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
C   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
C   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
C   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
C
      SUBROUTINE LNSRCH(N,XOLD,FOLD,G,P,X,F,STPMAX,CHECK,COCKUP)
      INTEGER N
      LOGICAL CHECK,COCKUP
      DOUBLE PRECISION F,FOLD,STPMAX,G(N),P(N),X(N),XOLD(N),ALF
     *,TOLX,GRAD(N)
      PARAMETER (ALF=1.D-4,TOLX=1.D-7)
      INTEGER I
      DOUBLE PRECISION A,ALAM,ALAM2,ALAMIN,B,DISC,F2,FOLD2,RHS1,RHS2
     *,SLOPE,SUM,TEMP,
     *TEST,TMPLAM

      PRINT '(A)',' PLEASE SUPPLY THE LNSRCH ROUTINE!'
      STOP

      END
