! DUMMY ROUTINES THAT GMIN IS NOT CALLING, BUT THE COMPILATION FOR AMBER INTERFACE NEEDS THEM

!SUBROUTINE CHIRALH_ALIGN(COORDSB, COORDSA, I1, DEBUG)
!USE COMMONS, ONLY : MYUNIT, NATOMS
!IMPLICIT NONE
!DOUBLE PRECISION        :: COORDSB(3*NATOMS), COORDSA(3*NATOMS)
!LOGICAL                 :: DEBUG
!INTEGER                 :: I1
!
!WRITE(MYUNIT,*) ' SHOULD NOT BE IN THIS DUMMY ROUTINE!!! (DUMMYOPTIM.F90)'
!STOP
!END SUBROUTINE CHIRALH_ALIGN

SUBROUTINE INTH_ALIGN(COORDSB,COORDSA,CENTRE)
USE COMMONS, ONLY : MYUNIT, NATOMS
IMPLICIT NONE
DOUBLE PRECISION        :: COORDSB(3*NATOMS), COORDSA(3*NATOMS)
INTEGER                 :: CENTRE 

WRITE(MYUNIT,*) ' SHOULD NOT BE IN THIS DUMMY ROUTINE!!! (DUMMYOPTIM.F90)'
STOP
END SUBROUTINE INTH_ALIGN
