!  GMIN: A PROGRAM FOR FINDING GLOBAL MINIMA
!  COPYRIGHT (C) 1999-2006 DAVID J. WALES
!  THIS FILE IS PART OF GMIN.
!
!  GMIN IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!  IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!  THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!  (AT YOUR OPTION) ANY LATER VERSION.
!
!  GMIN IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!  BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!  MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!  GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!
!  YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!  ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!  FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!
SUBROUTINE ENUMERATE(NFLOAT,NEWORB,NEWORBSIZE,HARDMAXIMUM,OCCS,NPOSS,DEBUG)
USE COMMONS,ONLY : MYUNIT
IMPLICIT NONE
INTEGER, INTENT(IN) :: NFLOAT, NEWORB, HARDMAXIMUM
INTEGER, INTENT(IN) :: NEWORBSIZE(NEWORB)
INTEGER COUNTS(0:NFLOAT)
INTEGER J, I, MAXCOUNT, MAXDEGEN, J1, NDUMMY, NOK
INTEGER, ALLOCATABLE :: OCCUPATIONS(:,:,:), SAVEOCC(:,:,:)
INTEGER, INTENT(OUT) :: OCCS(HARDMAXIMUM,NEWORB), NPOSS
LOGICAL DEBUG

MAXDEGEN=MIN(HARDMAXIMUM,100)
! ALLOCATE(OCCUPATIONS(0:NFLOAT,MAXDEGEN,NEWORB))
ALLOCATE(OCCUPATIONS(0:NFLOAT,HARDMAXIMUM,NEWORB))
COUNTS(0)=1; COUNTS(1:NFLOAT)=0
MAXCOUNT=0
OCCUPATIONS(0:NFLOAT,1:MAXDEGEN,1:NEWORB)=0

IF (DEBUG) WRITE(MYUNIT,'(A,3I6)') 'ENUMERATE> NFLOAT, HARDMAXIMUM, NEWORB=',NFLOAT, HARDMAXIMUM, NEWORB

DO J=1,NEWORB
   DO I=NEWORBSIZE(J),MIN(NFLOAT,NEWORBSIZE(J)+MAXCOUNT)
      NOK=0
      DO J1=1,COUNTS(I-NEWORBSIZE(J))
         IF (OCCUPATIONS(I-NEWORBSIZE(J),J1,J).EQ.0) THEN
            NOK=NOK+1

!           IF ((I.EQ.NFLOAT).AND.(COUNTS(I)+NOK.GT.HARDMAXIMUM)) THEN
!              OCCS(1:COUNTS(I),1:NEWORB)=OCCUPATIONS(NFLOAT,1:COUNTS(I),1:NEWORB)
!              NPOSS=COUNTS(I)
!              RETURN
!           ENDIF
               
!           IF (COUNTS(I)+NOK.GT.MAXDEGEN) THEN
!              ALLOCATE(SAVEOCC(0:NFLOAT,MAXDEGEN,NEWORB))
!              SAVEOCC(0:NFLOAT,1:MAXDEGEN,1:NEWORB)=OCCUPATIONS(0:NFLOAT,1:MAXDEGEN,1:NEWORB)
!              DEALLOCATE(OCCUPATIONS)
!              MAXDEGEN=MAXDEGEN*2
!              ALLOCATE(OCCUPATIONS(0:NFLOAT,MAXDEGEN,NEWORB))
!              OCCUPATIONS(0:NFLOAT,1:MAXDEGEN/2,1:NEWORB)=SAVEOCC(0:NFLOAT,1:MAXDEGEN/2,1:NEWORB)
!              OCCUPATIONS(0:NFLOAT,MAXDEGEN/2+1:MAXDEGEN,1:NEWORB)=0
!              DEALLOCATE(SAVEOCC)
!              PRINT '(A,I10)','ALLOCATION SIZE INCREASED TO ',MAXDEGEN
!           ENDIF

            IF (COUNTS(I)+NOK.LE.HARDMAXIMUM) THEN
               OCCUPATIONS(I,COUNTS(I)+NOK,1:NEWORB)=OCCUPATIONS(I-NEWORBSIZE(J),J1,1:NEWORB)
               OCCUPATIONS(I,COUNTS(I)+NOK,J)=OCCUPATIONS(I-NEWORBSIZE(J),J1,J)+1
            ENDIF
         ENDIF
      ENDDO
      COUNTS(I)=MIN(COUNTS(I)+NOK,HARDMAXIMUM)
   ENDDO
   MAXCOUNT=MAXCOUNT+NEWORBSIZE(J)
ENDDO

IF (DEBUG) WRITE(MYUNIT,'(A)') 'FINAL COUNTS:'
IF (DEBUG) WRITE(MYUNIT,'(2I16)') (J,COUNTS(J),J=0,NFLOAT)

OCCS(1:COUNTS(NFLOAT),1:NEWORB)=OCCUPATIONS(NFLOAT,1:COUNTS(NFLOAT),1:NEWORB)
NPOSS=COUNTS(NFLOAT)
IF (DEBUG) WRITE(MYUNIT,'(A,I5)') 'NUMBER OF POSSIBILITIES=',NPOSS

RETURN

! DO J=0,NFLOAT
!    IF (COUNTS(J).GT.0) THEN
!       PRINT '(A,I5,A)','OCCUPATIONS FOR ',J,' ATOMS:'
!       DO I=1,COUNTS(J)
!          NDUMMY=0
!          DO J1=1,NEWORB
!             NDUMMY=NDUMMY+OCCUPATIONS(J,I,J1)*NEWORBSIZE(J1)
!          ENDDO
!          PRINT '(20I4)',OCCUPATIONS(J,I,1:NEWORB)
!          PRINT '(A,I5)','CHECKSUM=',NDUMMY
!       ENDDO
!    ENDIF
! ENDDO

RETURN
END
