C   GMIN: A PROGRAM FOR FINDING GLOBAL MINIMA
C   COPYRIGHT (C) 1999-2006 DAVID J. WALES
C   THIS FILE IS PART OF GMIN.
C
C   GMIN IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C   (AT YOUR OPTION) ANY LATER VERSION.
C
C   GMIN IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
C   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
C   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
C   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
C
C
C THE FUNCTION F1DIM HAS TO ACCOMPANY LINMIN
C
      FUNCTION F1DIM(XX)
      USE COMMONS
      USE F1COM
      IMPLICIT DOUBLE PRECISION (A-H,P-Z)
      DOUBLE PRECISION GRAD(3*NATOMS), XT(3*NATOMS)

      DO 10 J=1,NCOM
         XT(J)=PCOM(J)+XX*XICOM(J)
10    CONTINUE
      CALL POTENTIAL(XT,GRAD,POTEL,.FALSE.,.FALSE.)
      F1DIM=POTEL
C     PRINT*,'XX, ENERGY IN F1DIM=',XX,POTEL
C     CALL FLUSH(6)
      RETURN
      END
