C   GMIN: A PROGRAM FOR FINDING GLOBAL MINIMA
C   COPYRIGHT (C) 1999-2006 DAVID J. WALES
C   THIS FILE IS PART OF GMIN.
C   FINNIS-SINCLAIR POTENTIAL ADDED BY J.A. ELLIOTT 2009
C
C   GMIN IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C   (AT YOUR OPTION) ANY LATER VERSION.
C
C   GMIN IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
C   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
C   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
C   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
C
C
C*************************************************************************
C
C  HERE WE CALCULATE THE FINNIS-SINCLAIR POTENTIAL AND GRADIENT
C
C*************************************************************************
C
      SUBROUTINE FS (X,V,PG,GRADT)
      USE COMMONS
      IMPLICIT NONE
      INTEGER J1, J2, J, ATOMTYPE
      DOUBLE PRECISION X(3*NATOMS), PG, DIST, PTEMP, V(3*NATOMS),
     1       GA, FSRHO(NATOMS), VTEMP, RTEMP, DUMMY,
     2       VTEMP1(NATOMS), VTEMP2(NATOMS), VTEMP3(NATOMS),
     3       D, A, BETA, C, C0, C1, C2, C3, DX, DY, DZ, MIN_DIST,
     4       CUTP, CUTR1, CUTR2, TEMP_DIST(NATOMS,NATOMS)
      LOGICAL GRADT

C FINNIS-SINCLAR POTENTIAL PARAMETERS
C PHIL MAG A 50, 45 (1984)
C PARAMETERS FOR FE SUBSEQUENTLY MODIFIED IN ERRATUM
C PHIL MAG A 53, 161 (1986)
C (BOTH SETS FOR FE ARE INCLUDED)
C
C BCC METALS
C
C D = DENSITY CUT-OFF [ANGSTROMS]
C A = BINDING ENERGY [EV]
C BETA = INTRODUCES MAXIMUM VALUE OF PHI WITHIN THE FIRST-NEAREST-NEIGHBOR DISTANCE.
C C = TWO-BODY INTERACTION CUT-OFF [ANGSTROMS]
C C0,C1,C2 = FITTING PARAMETERS

      ATOMTYPE=GATOM

      IF (ATOMTYPE.EQ.1) THEN

C VANADIUM
        D=3.692767D0
        A=2.010637D0
        BETA=0.0D0
        C=3.8D0
        C0=-0.8816318D0
        C1=1.4907756D0
        C2=-0.3976370D0

      ELSE IF (ATOMTYPE.EQ.2) THEN

C NIOBIUM
        D=3.915354D0
        A=3.013789D0
        BETA=0.0D0
        C=4.2D0
        C0=-1.5640104D0
        C1=2.0055779D0
        C2=-0.4663764D0

      ELSE IF (ATOMTYPE.EQ.3) THEN

C TANTALUM
        D=4.076980D0
        A=2.591061D0
        BETA=0.0D0
        C=4.2D0
        C0=1.2157373D0
        C1=0.0271471D0
        C2=-0.1217350D0

      ELSE IF (ATOMTYPE.EQ.4) THEN

C CHROMIUM
        D=3.915720D0
        A=1.453418D0
        BETA=1.8D0
        C=2.9D0
        C0=29.1429813D0
        C1=-23.3975027D0
        C2=4.7578297D0

      ELSE IF (ATOMTYPE.EQ.5) THEN

C MOLYBDENUM
        D=4.114825D0
        A=1.887117D0
        BETA=0.0D0
        C=3.25D0
        C0=43.4475218D0
        C1=-31.9332978D0
        C2=6.0804249D0

      ELSE IF (ATOMTYPE.EQ.6) THEN

C TUNGSTEN
        D=4.400224D0
        A=1.896373D0
        BETA=0.0D0
        C=3.25D0
        C0=47.1346499D0
        C1=-33.7665655D0
        C2=6.2541999D0

      ELSE IF (ATOMTYPE.EQ.7) THEN

C IRON - ORIGINAL PARAMETERS IN PHIL MAG A VOL. 50 P.45 (1984)
        D=3.699579D0
        A=1.889846D0
        BETA=1.8D0
        C=3.4D0
        C0=1.2110601D0
        C1=-0.7510840D0
        C2=0.1380773D0

      ELSE IF (ATOMTYPE.EQ.8) THEN

C IRON - MODIFIED PARAMETERS IN ERRATUM, PHIL MAG A VOL. 53 P.161 (1986)
        D=3.569745D0
        A=1.828905D0
        BETA=1.8D0
        C=3.4D0
        C0=1.2371147D0
        C1=-0.3592185D0
        C2=-0.0385607D0

      ENDIF

C IF BETA IS NON-ZERO, SET A MINIMUM DISTANCE CUT-OFF TO AVOID RTEMP GOING NEGATIVE
      IF (BETA.NE.0D0) THEN
        MIN_DIST=D*(BETA-1.0D0)/BETA
      ELSE
        MIN_DIST=0.0D0
      ENDIF

C CALCULATE THE POTENTIAL AND GRADIENT TERMS

C FIRST, POPULATE DENSITY AND DISTANCE MATRICES

      DO J2=1,NATOMS                               ! INITIALISE DISTANCE AND DENSITY ARRAYS
        DO J1=1,NATOMS
          TEMP_DIST(J1,J2)=0.0D0
        ENDDO
        FSRHO(J2)=0.0D0
      ENDDO

      RTEMP = 0.0D0                               ! INITIALISE ENERGY ACCUMULATORS
      PTEMP = 0.0D0

      DO J1=1,NATOMS-1                              ! BEGIN OUTER LOOP OVER ALL ATOMS EXCEPT LAST

        DO J2=J1+1,NATOMS                           ! BEGIN FIRST INNER LOOP OVER ALL J2>J1

          TEMP_DIST(J2,J1)=                           ! CALC AND STORE DISTANCE BETWEEN ATOMS J1,J2
     1         DSQRT(( X(3*(J2-1)+1)-X(3*(J1-1)+1) )**2 +
     2         ( X(3*(J2-1)+2)-X(3*(J1-1)+2) )**2 +
     3         ( X(3*(J2-1)+3)-X(3*(J1-1)+3) )**2)

          DIST=TEMP_DIST(J2,J1)                       ! STORE THE ACTUAL DISTANCE USED IN INNER LOOP
          TEMP_DIST(J1,J2)=DIST                       ! IMPOSE SYMMETRY ON DISTANCE MATRIX

          CUTP=DSIGN(0.5D0,C-DIST)+0.5D0                               ! CUT-OFF FOR 2-BODY INTERACTION
          PTEMP=PTEMP
     1          +CUTP*(((DIST-C)**2)*(C0+DIST*(C1+C2*DIST)))           ! ACCUMULATE TWO-BODY POTENTIAL TERM

          CUTR1=DSIGN(0.5D0,D-DIST)+0.5D0                              ! CUT-OFF FOR MANY-BODY INTERACTION
          CUTR2=DSIGN(0.5D0,DIST-MIN_DIST)+0.5D0                       ! MINIMUM DISTANCE CUT-OFF
          RTEMP=CUTR1*CUTR2*((DIST-D)**2+(BETA*(DIST-D)**3/D))
          FSRHO(J1)=FSRHO(J1)+RTEMP                   ! ACCUMULATE CONTRIBUTION TO DENSITY MATRIX
          FSRHO(J2)=FSRHO(J2)+RTEMP                   ! ACCUMULATE CONTRIBUTION TO DENSITY MATRIX

        ENDDO                                       ! END INNER LOOP OVER ALL J2>J1

      ENDDO                                         ! END OUTER LOOP OVER ALL ATOMS EXCEPT LAST

C     NOW, SUM THE POTENTIAL ENERGY OVER ALL ATOMS

      PG=PTEMP                                    ! INITIALISE POTENTIAL ENERGY

      DO J1=1,NATOMS
        FSRHO(J1)=DSQRT(FSRHO(J1))                ! SQUARE ROOT DENSITY
        PG=PG-A*FSRHO(J1)                         ! ACCUMULATE POTENTIAL ENERGY
      ENDDO

C     CALCULATE GRADIENT TERMS, IF REQUIRED

      IF (GRADT) THEN

        DO J1=1,NATOMS                            ! INITIALISE TOTAL GRADIENT TERMS
          V(3*(J1-1)+1)=0.D0
          V(3*(J1-1)+2)=0.D0
          V(3*(J1-1)+3)=0.D0
          VTEMP1(J1)=0.0D0
          VTEMP2(J1)=0.0D0
          VTEMP3(J1)=0.0D0
        ENDDO

        DO J1=1,NATOMS-1                                ! BEGIN OUTER LOOP OVER ALL ATOMS EXCEPT LAST

          DUMMY=1.0D0/FSRHO(J1)                         ! STORE RECIPROCAL OF DENSITY ELEMENT FOR ATOM J1

          DO J2=J1+1,NATOMS                             ! BEGIN INNER LOOP OVER ALL J2>J1

            DIST=TEMP_DIST(J1,J2)                                        ! RECALL DISTANCE FROM EARLIER LOOP

            CUTP=DSIGN(0.5D0,C-DIST)+0.5D0                               ! CUT-OFF FOR 2-BODY GRADIENT
            VTEMP= CUTP*(2.0D0*(DIST-C)*(C0+DIST*(C1+C2*DIST))           ! ACCUMULATE 2-BODY GRADIENT TERM
     1             +((DIST-C)**2)*(C1+2.0D0*C2*DIST))/DIST

            CUTR1=DSIGN(0.5D0,D-DIST)+0.5D0                              ! CUT-OFF FOR MANY-BODY GRADIENT
            CUTR2=DSIGN(0.5D0,DIST-MIN_DIST)+0.5D0                       ! MINIMUM DISTANCE CUT-OFF
            VTEMP=VTEMP                                                  ! ACCUMULATE MANY-BODY GRADIENT TERM
     1            -CUTR1*CUTR2*((0.5D0*A)*(DUMMY+1.0D0/FSRHO(J2))*
     2            (2.0D0*(DIST-D)+3.0D0*(BETA/D)*(DIST-D)**2))/DIST

            DX=(X(3*(J1-1)+1)-X(3*(J2-1)+1))         ! CALCULATE CARTESIAN COMPONENTS OF DISTANCE
            DY=(X(3*(J1-1)+2)-X(3*(J2-1)+2))
            DZ=(X(3*(J1-1)+3)-X(3*(J2-1)+3))

            VTEMP1(J1)=VTEMP1(J1)+VTEMP*DX           ! ACCUMULATE PRIMARY GRADIENT COMPONENTS
            VTEMP2(J1)=VTEMP2(J1)+VTEMP*DY
            VTEMP3(J1)=VTEMP3(J1)+VTEMP*DZ

            VTEMP1(J2)=VTEMP1(J2)-VTEMP*DX           ! ACCUMULATE SYMMETRIC GRADIENT COMPONENTS
            VTEMP2(J2)=VTEMP2(J2)-VTEMP*DY
            VTEMP3(J2)=VTEMP3(J2)-VTEMP*DZ

          ENDDO

        ENDDO

C       FINALLY, SUM THE GRADIENT TERMS OVER ALL ATOMS

        DO J1=1,NATOMS
          V(3*(J1-1)+1)=V(3*(J1-1)+1)+VTEMP1(J1)
          V(3*(J1-1)+2)=V(3*(J1-1)+2)+VTEMP2(J1)
          V(3*(J1-1)+3)=V(3*(J1-1)+3)+VTEMP3(J1)
        ENDDO

      ENDIF

      RETURN
      END
