SUBROUTINE GETORBITS(NORBIT,ORBDIST,CMDIST,NATOMS,ORBSIZE,SYMTOL,LARGESIZE,NINDEX,LCOORDS,LDEBUG)
USE COMMONS,ONLY: MYUNIT
IMPLICIT NONE
INTEGER NATOMS, J, J1, ISTART
INTEGER NORBIT, IORBIT, ORBSIZE(NATOMS), LARGES, LARGESIZE, NINDEX(NATOMS)
DOUBLE PRECISION ORBDIST(NATOMS), CMDIST(NATOMS), SYMTOL, LARGEDIST, LCOORDS(3*NATOMS)
LOGICAL LDEBUG

NORBIT=1 ! NUMBER OF ORBITS
IORBIT=1
ORBDIST(NORBIT)=CMDIST(1) ! SAVE DISTANCE OF FIRST ORBIT
! THE DISTANCES MUST BE SORTED FOR THE NEXT LOOP TO WORK
DO J=2,NATOMS
!  PRINT '(A,3F15.5)','CMDIST(J),CMDIST(J-1),SYMTOL=',CMDIST(J),CMDIST(J-1),SYMTOL
   IF (ABS(CMDIST(J)-CMDIST(J-1)).LT.SYMTOL) THEN 
      IORBIT=IORBIT+1 ! OLD ORBIT, INCREMENT NUMBER OF ATOMS
      ORBDIST(NORBIT)=ORBDIST(NORBIT)+CMDIST(J)
   ELSE 
      ORBSIZE(NORBIT)=IORBIT ! SAVE SIZE OF PREVIOUS ORBIT
      ORBDIST(NORBIT)=ORBDIST(NORBIT)/IORBIT ! USE AVERAGE DISTANCE FOR ALL ATOMS
      NORBIT=NORBIT+1 ! INCREMENT NUMBER OF ORBITS
      ORBDIST(NORBIT)=CMDIST(J) ! SAVE DISTANCE OF NEW ORBIT
      IORBIT=1        ! RESET THE COUNTER FOR NUMBER OF ATOMS IN THIS ORBIT
   ENDIF
ENDDO
ORBSIZE(NORBIT)=IORBIT ! SAVE SIZE OF LAST ORBIT
ORBDIST(NORBIT)=ORBDIST(NORBIT)/IORBIT ! USE AVERAGE DISTANCE FOR ALL ATOMS

! ISTART=1
! DO J=1,NORBIT
   ! CMX(J)=0.0D0
   ! CMY(J)=0.0D0
   ! CMZ(J)=0.0D0
   ! DO J1=ISTART,ISTART+ORBSIZE(J)-1
      ! CMX(J)=CMX(J)+LCOORDS(3*(NINDEX(J1)-1)+1)
      ! CMY(J)=CMY(J)+LCOORDS(3*(NINDEX(J1)-1)+2)
      ! CMZ(J)=CMZ(J)+LCOORDS(3*(NINDEX(J1)-1)+3)
   ! ENDDO 
   ! CMX(J)=CMX(J)/ORBSIZE(J)
   ! CMY(J)=CMY(J)/ORBSIZE(J)
   ! CMZ(J)=CMZ(J)/ORBSIZE(J)
   ! ISTART=ISTART+ORBSIZE(J)
! ENDDO

LARGES=1
LARGESIZE=ORBSIZE(1)
LARGEDIST=ORBDIST(1)
ISTART=1
DO J=1,NORBIT
   IF (LDEBUG) WRITE(MYUNIT, '(A,I6,A,I6,A,F15.5)') 'ORBIT ',J,' SIZE ',ORBSIZE(J),' DISTANCE ',ORBDIST(J)
   IF (LDEBUG) WRITE(MYUNIT, '(A,I6)') 'MEMBERS OF ORBIT ',J
   IF (LDEBUG) WRITE(MYUNIT, '(12I5)') (NINDEX(J1),J1=ISTART,ISTART+ORBSIZE(J)-1)
   IF (LDEBUG) WRITE(MYUNIT, '(A)') 'DISTANCES:'
   IF (LDEBUG) WRITE(MYUNIT, '(6G20.10)') (CMDIST(J1),J1=ISTART,ISTART+ORBSIZE(J)-1)
   IF (ORBSIZE(J).GT.LARGESIZE) THEN
      LARGESIZE=ORBSIZE(J)
      LARGES=ISTART
      LARGEDIST=ORBDIST(J)
   ENDIF
   ISTART=ISTART+ORBSIZE(J)
ENDDO
IF (LDEBUG) WRITE(MYUNIT,'(A,I6,A,I6)')  'LARGEST ORBIT HAS ',LARGESIZE,' MEMBERS STARTING FROM SORTED POSITION ',LARGES

RETURN
END SUBROUTINE GETORBITS
