C   GMIN: A PROGRAM FOR FINDING GLOBAL MINIMA
C   COPYRIGHT (C) 1999-2006 DAVID J. WALES
C   THIS FILE IS PART OF GMIN.
C
C   GMIN IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C   (AT YOUR OPTION) ANY LATER VERSION.
C
C   GMIN IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
C   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
C   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
C   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
C
C
C MNBRAK IS CALLED BY LINMIN. GIVEN DISTINCT INITIAL POINTS AX AND BX,
C IT SEARCHES IN DOWNHILL DIRCTION AND RETURNS NEW POINTS AX, BX, CX
C WHICH BRACKET A MINIMUM OF THE FUNCTION.
C FUNCTION VALUES OF THE NEW POINTS: FA, FB, FC
C
      SUBROUTINE MNBRAK(AX,BX,CX,FA,FB,FC,F1DIM)
      USE COMMONS
      IMPLICIT DOUBLE PRECISION (A-H,P-Z)
      EXTERNAL F1DIM
      PARAMETER (GOLD=1.618034D00, GLIMIT=100.D0, TINY=1.D-8)
      LOGICAL FTEST
      COMMON /FAIL/ FTEST

      IF(FB.GT.FA)THEN
        DUM=AX
        AX=BX
        BX=DUM
        DUM=FB
        FB=FA
        FA=DUM
      ENDIF
      CX=BX+GOLD*(BX-AX)
      FC=F1DIM(CX)
      IF (FTEST) RETURN
10    IF(FB.GE.FC)THEN
        R=(BX-AX)*(FB-FC)
        Q=(BX-CX)*(FB-FA)
        U=BX-((BX-CX)*Q-(BX-AX)*R)/(2.0D0*SIGN(MAX(ABS(Q-R),TINY),Q-R))
        ULIM=BX+GLIMIT*(CX-BX)
        IF((BX-U)*(U-CX).GT.0.)THEN
          FU=F1DIM(U)
          IF (FTEST) RETURN
          IF(FU.LT.FC)THEN
            AX=BX
            FA=FB
            BX=U
            FB=FU
            GO TO 10
          ELSE IF(FU.GT.FB)THEN
            CX=U
            FC=FU
            GO TO 10
          ENDIF
          U=CX+GOLD*(CX-BX)
          FU=F1DIM(U)
          IF (FTEST) RETURN
        ELSE IF((CX-U)*(U-ULIM).GT.0.)THEN
          FU=F1DIM(U)
          IF (FTEST) RETURN
          IF(FU.LT.FC)THEN
            BX=CX
            CX=U
            U=CX+GOLD*(CX-BX)
            FB=FC
            FC=FU
            FU=F1DIM(U)
            IF (FTEST) RETURN
          ENDIF
        ELSE IF((U-ULIM)*(ULIM-CX).GE.0.)THEN
          U=ULIM
          FU=F1DIM(U)
          IF (FTEST) RETURN
        ELSE
          U=CX+GOLD*(CX-BX)
          FU=F1DIM(U)
          IF (FTEST) RETURN
        ENDIF
        AX=BX
        BX=CX
        CX=U
        FA=FB
        FB=FC
        FC=FU
        GO TO 10
      ENDIF
      RETURN
      END
