MODULE MOLINFO
    IMPLICIT NONE

    TYPE ATOM
        INTEGER            :: ATOM_ID    ! ATOM NUMBER
        CHARACTER (LEN=10) :: ATOM_NAME  ! ATOM NAME
        INTEGER            :: RES_ID     ! RESIDUE NUMBER
        CHARACTER (LEN=10) :: RES_NAME   ! RESIDUE NAME
        INTEGER            :: CHAIN_ID   ! CHAIN ID
        CHARACTER (LEN=10) :: SEG_NAME   ! SEGMENT NAME
        CHARACTER (LEN=5)  :: ELEMENT    ! ELEMENT NAME
        DOUBLE PRECISION   :: OCCUPANCY  ! SITE OCCUPANCY
        DOUBLE PRECISION   :: B_FACTOR   ! CRYSTALLOGRAPHIC TEMP.
        DOUBLE PRECISION   :: CHARGE     ! ATOMIC CHARGE
        DOUBLE PRECISION   :: WEIGHT     ! CHARMM WEIGHT
    END TYPE ATOM

    TYPE(ATOM), DIMENSION(:), PRIVATE, SAVE :: MOL_INFO

    CONTAINS

        TYPE(ATOM) FUNCTION GET_ATOMS(START, FINISH) RESULT(ATOMS)
            INTEGER, INTENT(IN) :: START, FINISH

            ATOMS(:) = MOL_INFO(START:FINISH)

            RETURN
        END FUNCTION GET_ATOMS

        LOGICAL FUNCTION SET_ATOMS(START, FINISH, ATOMS)
            INTEGER, INTENT(IN)                  :: START, FINISH
            TYPE(ATOM), DIMENSION(:), INTENT(IN) :: ATOMS

            MOL_INFO(START:FINISH) = ATOMS(:)
            IF (!!!ARRAYS ARE NOT EQUAL!!! ) THEN
                SET_ATOMS = .TRUE.
            ELSE
                SET_ATOMS = .FALSE.
            END IF

            RETURN
        END FUNCTION SET_ATOMS

END MODULE MOLINFO
