C   GMIN: A PROGRAM FOR FINDING GLOBAL MINIMA
C   COPYRIGHT (C) 1999-2006 DAVID J. WALES
C   THIS FILE IS PART OF GMIN.
C
C   GMIN IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C   (AT YOUR OPTION) ANY LATER VERSION.
C
C   GMIN IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
C   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
C   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
C   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
C
C   THIS PROGRAM IS SUPPOSED TO CALCULATE THE ENERGY, 
C   FIRST DERIVATIVES AND SECOND DERIVATIVES FOR SILICON 
C   CLUSTERS USING A TIGHT BINDING (TB) APPROXIMATION.  
C   THIS WILL THEN BE USED IN CONJUNCTION WITH OPTIM,
C   AS IT IS NOW KNOWN, TO SOLVE THE PROBLEMS OF THE UNIVERSE
C   AND IN PARTICULAR THOSE OF THE SILICON CLUSTER WORLD.
C   THE PARAMETERS ETC..ARE TAKEN FROM PRB 47 12754 1993
C   AND PRB 50 5645 1994 IN CASE YOU WERE WONDERING.

C   THIS IS THE VERSION WHERE YOU CAN PUT A CUTOFF INTO THE
C   THE DATA FILE AND SEE WHAT HAPPENS. (16TH APRIL 1997)

      SUBROUTINE MSORIGC(N,XS,DERIV1ST,ENERGY,GTEST)
      USE COMMONS
      USE CONSTS
      USE DISTANCE
      IMPLICIT NONE
      LOGICAL GTEST
      INTEGER I, J, K, N, AI, AJ, NDIM, NMAX, I2, J2, K2, AI2,  INFO, 
     1        MX, MY, MZ, J1
      DOUBLE PRECISION DIST,ZETA,NB,VECT(4),EPS(4),WORK(24*NATOMS),
     1                 S(4*NATOMS,4*NATOMS),ENERGY,XS(3*NATOMS),
     2                 H(4*NATOMS,4*NATOMS),VECTOR(3), DERIV1ST(3*NATOMS)
      DOUBLE PRECISION UREP,UBOND,ELEMENT
      LOGICAL FTEST
      COMMON /FAIL/ FTEST
      COMMON /NEW/ ELEMENT
      ALLOCATE(DIAG(4*NATOMS), R(NATOMS,NATOMS), S2(NATOMS,NATOMS), LAMBDA(NATOMS,NATOMS),
     &         REPULSE(NATOMS,NATOMS),BONDAGE(NATOMS,NATOMS), KAPPANEW(NATOMS,NATOMS),
     &         HORIG(4*NATOMS,4*NATOMS), SVTYPE(8*NATOMS,NATOMS), DIRCOS(NATOMS,NATOMS,3))
C
C************ START PERIODIC BOUNDARY CONDITIONS **************************
C  DEAL WITH ATOMS LEAVING THE BOX:
C
      IF (PERIODIC) THEN
C        PRINT*,'POINTS BEFORE:'
C        WRITE(*,'(3F15.7)') (XS(J1),J1=1,3*N)
         DO J1=1,N
            J2=3*(J1-1)
            XS(J2+1)=XS(J2+1) - BOXLX*DNINT(XS(J2+1)/BOXLX) 
            XS(J2+2)=XS(J2+2) - BOXLY*DNINT(XS(J2+2)/BOXLY)
            XS(J2+3)=XS(J2+3) - BOXLZ*DNINT(XS(J2+3)/BOXLZ)
         ENDDO
C        PRINT*,'POINTS AFTER:'
C        WRITE(*,'(3F15.7)') (XS(J1),J1=1,3*N)
C
C  CALCULATION OF CONNECTING VECTORS; TO IMPLEMENT THE PERIODIC
C  BOUNDARY CONDITIONS, THE SHORTEST VECTOR BETWEEN TWO ATOMS IS USED:
C
         DO I=1,N
            I2=3*(I-1)
            R(I,I)=0.0D0
            DO J=I+1,N
               J2=3*(J-1)
               VECTOR(1)=XS(J2+1)-XS(I2+1)
               VECTOR(2)=XS(J2+2)-XS(I2+2)
               VECTOR(3)=XS(J2+3)-XS(I2+3)
               MX=NINT(VECTOR(1)/BOXLX)
               MY=NINT(VECTOR(2)/BOXLY)
               MZ=NINT(VECTOR(3)/BOXLZ)
               VECTOR(1)= VECTOR(1) - BOXLX * MX
               VECTOR(2)= VECTOR(2) - BOXLY * MY
               VECTOR(3)= VECTOR(3) - BOXLZ * MZ
               DIST=VECTOR(1)**2+VECTOR(2)**2+VECTOR(3)**2
               R(I,J)=SQRT(DIST)
               R(J,I)=R(I,J)
               DO K=1,3
                  DIRCOS(I,J,K)=VECTOR(K)/R(I,J)
                  DIRCOS(J,I,K)=-DIRCOS(I,J,K)
               ENDDO
C              WRITE(*,'(2I4,3F15.7)') (I,J,(DIRCOS(I,J,K),K=1,3))
            ENDDO
            DO K=1,3
               DIRCOS(I,I,K)=0.0D0
            ENDDO
         ENDDO
C************ END PERIODIC BOUNDARY CONDITIONS ****************************
      ELSE

C   CALCULATE DISTANCE MATRIX

         DO I=1,N
          I2=3*(I-1)
          R(I,I)=0.0D0
             DO J=I+1,N
               J2=3*(J-1)
               DIST=(XS(I2+1)-XS(J2+1))**2+(XS(I2+2)-XS(J2+2))**2
     1                   +(XS(I2+3)-XS(J2+3))**2
                R(I,J)=SQRT(DIST)
                R(J,I)=R(I,J)

C   NOW THE DIRECTION COSINES
C   WHICH INCIDENTALLY ARE THE PROJECTIONS OF A UNIT VECTOR ONTO 
C   THE AXES AND NOT THE COSINES.
C   NOTE WE HAVE NOT CALCULATED DIRCOS(I,I)

               DO K=1,3
                  DIRCOS(I,J,K)=(XS(J2+K)-XS(I2+K))/R(I,J)
                  DIRCOS(J,I,K)=-DIRCOS(I,J,K)
               ENDDO
            ENDDO
            DO K=1,3
               DIRCOS(I,I,K)=0.0D0
            ENDDO
         ENDDO 
      ENDIF

C   CALCULATE REPULSIVE FREE ENERGY
C   CHI(R) IS THE REPULSIVE PAIR POTENTIAL, THE SUM OF WHICH IS 
C   EQUAL TO THE REPULSIVE ENERGY (UREP) IN EV.
C   BETA IS 4/R_0, WHERE R_0 IS ONE HALF THE DIMER BOND LENGTH.
C   D IS THE BOND LENGTH FOR THE CRYSTAL IN ANGSTROMS.

      UREP=0.0D0
      DO I=1,N
         DO J=I+1,N
            IF (R(J,I).LT.CUTOFF) THEN
             REPULSE(J,I)=CHI*DEXP(-BETA*(R(J,I)-D))
             UREP=UREP+REPULSE(J,I)
            END IF
         END DO
      END DO 
C     WRITE(6,10) 'UREP=',UREP
10    FORMAT(A8, F20.17)

C   CALCULATE AD HOC BOND COUNTING TERM UBOND IN EV.
C   THIS IS USING THE A AND B PARAMETERS DETERMINED USING THE PRB
C   50 5645 1994. IT IS JUST A CORRECTION TO THE COHESIVE ENERGY
C   FOR CLUSTERS OF DIFFERENT SIZES IN ORDER TO OBTAIN A GOOD AGREEMENT
C   WITH AB INITIO VALUES.
C   SUM IS OVER ALL BONDS.

      NB=0.0D0

      DO I=1,N
         DO J=I+1,N
            IF (R(J,I).LT.CUTOFF) THEN
             BONDAGE(J,I)=DEXP((R(J,I)-RC)/DELTA)
             NB=NB+1.0D0/(BONDAGE(J,I)+1.0D0)
            END IF
         END DO
      END DO
      UBOND=-DBLE(N)*(A*(NB/DBLE(N))+B)
C     WRITE(6,10) 'UBOND=',UBOND

C   CALCULATE ELECTRONIC ENERGY UEL
C   NOT SURE HOW THE HELL TO DO THIS BUT I'LL SEE WHAT I COME UP WITH.
C   FIRST FIND THE H(I,J) MATRIX.
C   THE INTERACTION OF THE 3S AND 3P ATOMIC ORBITALS ON ONE ATOM
C   WITH THOSE ON ANOTHER ATOM LEADS TO 8 DIFFERENT INTERACTIONS
C   OBVIOUS RIGHT? 'COS THERE ARE 8AOS INVOLVED.
C   STILL GOT TO INCLUDE THE FACT THAT ONLY THE NEAREST NEIGHBOUR
C   INTERACTIONS SHOULD BE INCLUDED...BUT I AM WORKING ON IT.



C   SUPPOSE IT WOULD HELP IF I FOUND THE UNIVERSAL PARAMETERS 
C   I AM ASSUMING THAT THE ONES QUOTED IN PRB 50 12754 1993
C   ARE AT THE CRYSTAL BOND LENGTH (D0=2.35)
C   VECT(1) IS VSSSIG, 2 VSPSIG, 3 VPPSIG AND 4 VPPPI EVALUATED AT D0
C   THUS, FOR EVERY ATOM THERE ARE 4 ATOMIC ORBITALS AND THE MATRICES
C   WILL BE (4N, 4N) IN SIZE.

      VECT(1)=VSSSIG
      VECT(2)=VSPSIG
      VECT(3)=VPPSIG
      VECT(4)=VPPPI

      EPS(1)=EPSS+EPSS
      EPS(2)=EPSS+EPSP
      EPS(3)=EPSP+EPSP
      EPS(4)=EPSP+EPSP
    
      ZETA=2.0D0*SQRT(3.0D0)
  
C   ONLY INCLUDE OVERLAP OR INTERACTION WITH DIFFERENT ATOMS HERE.
               
      DO I=1,N
         AI=4*(I-1)
         AI2=2*AI
         DO J=I+1,N
            AJ=4*(J-1)

           IF (R(J,I).LT.CUTOFF) THEN

C   DEPENDENCE OF V ON DISTANCE BETWEEN ATOMS R(I,J)
C   SIMILARLY, S MUST SCALE WITH R(I,J)

            DO K=1,4
               SVTYPE(AI2+4+K,J)=VECT(K)*DEXP(-ALPHA*(R(I,J)-D))
               SVTYPE(AI2+K,J)=2.0D0*SVTYPE(AI2+4+K,J)/(KAPPA*EPS(K))
            END DO

C   SET DIRCOS2 TO SPECIFIC VALUE OF DIRCOS(I,J,K) SO THAT
C   IT IS EASIER TO READ THE EQUATIONS

C           DO K=1,3
C              DIRCOS2(K)=DIRCOS(I,J,K)
C           END DO
C   CALCULATE THE OVERLAP MATRIX S(I,J), RELATED TO THESE PARAMETERS
C   BY THE SLATER-KOSTER SCHEME

            S((AI+1),(AJ+1))=SVTYPE(AI2+1,J)
            S((AI+1),(AJ+2))=DIRCOS(I,J,1)*SVTYPE(AI2+2,J)
            S((AI+1),(AJ+3))=DIRCOS(I,J,2)*SVTYPE(AI2+2,J)
            S((AI+1),(AJ+4))=DIRCOS(I,J,3)*SVTYPE(AI2+2,J)

            S((AI+2),(AJ+1))=-S((AI+1),(AJ+2))
            S((AI+2),(AJ+2))=DIRCOS(I,J,1)**2*SVTYPE(AI2+3,J)+(1.0D0-
     1                       DIRCOS(I,J,1)**2)*SVTYPE(AI2+4,J)
            S((AI+2),(AJ+3))=DIRCOS(I,J,1)*DIRCOS(I,J,2)*(SVTYPE(AI2+3,J)
     1                       -SVTYPE(AI2+4,J))
            S((AI+2),(AJ+4))=DIRCOS(I,J,1)*DIRCOS(I,J,3)*(SVTYPE(AI2+3,J)
     1                       -SVTYPE(AI2+4,J))

            S((AI+3),(AJ+1))=-S((AI+1),(AJ+3))
            S((AI+3),(AJ+2))=S((AI+2),(AJ+3))
            S((AI+3),(AJ+3))=DIRCOS(I,J,2)**2*SVTYPE(AI2+3,J)+(1.0D0-
     1                       DIRCOS(I,J,2)**2)*SVTYPE(AI2+4,J)
            S((AI+3),(AJ+4))=DIRCOS(I,J,2)*DIRCOS(I,J,3)*(SVTYPE(AI2+3,J)
     1                       -SVTYPE(AI2+4,J))
            
            S((AI+4),(AJ+1))=-S((AI+1),(AJ+4))
            S((AI+4),(AJ+2))=S((AI+2),(AJ+4))
            S((AI+4),(AJ+3))=S((AI+3),(AJ+4))
            S((AI+4),(AJ+4))=DIRCOS(I,J,3)**2*SVTYPE(AI2+3,J)+(1.0D0-
     1                       DIRCOS(I,J,3)**2)*SVTYPE(AI2+4,J)
            
            S2(I,J)=(SVTYPE(AI2+1,J)-ZETA*SVTYPE(AI2+2,J)-3.0D0*
     1                        SVTYPE(AI2+3,J))/4.0D0

C   HAMILTONIAN IS FOUND USING THE SLATER-KOSTER SCHEME
C   AS SHOWN IN THEIR PAPER AND HARRISON'S BOOK P.481
C   WHICH RELATES H TO THE PARAMETER V USING DIRECTION COSINES.
C   LAMBDA CHANGES FOR EACH I AND J
      
      LAMBDA(I,J)=1.0D0+1.0D0/KAPPA-S2(I,J)**2

            H((AI+1),(AJ+1))=SVTYPE(AI2+5,J)*LAMBDA(I,J)
            H((AI+1),(AJ+2))=DIRCOS(I,J,1)*SVTYPE(AI2+6,J)*LAMBDA(I,J)
            H((AI+1),(AJ+3))=DIRCOS(I,J,2)*SVTYPE(AI2+6,J)*LAMBDA(I,J)
            H((AI+1),(AJ+4))=DIRCOS(I,J,3)*SVTYPE(AI2+6,J)*LAMBDA(I,J)

            H((AI+2),(AJ+1))=-H((AI+1),(AJ+2))
            H((AI+2),(AJ+2))=(DIRCOS(I,J,1)**2*SVTYPE(AI2+7,J)+(1.0D0-
     1           DIRCOS(I,J,1)**2)*SVTYPE(AI2+8,J))*LAMBDA(I,J)
            H((AI+2),(AJ+3))=DIRCOS(I,J,1)*DIRCOS(I,J,2)*(SVTYPE(AI2+7,J)
     1           -SVTYPE(AI2+8,J))*LAMBDA(I,J)
            H((AI+2),(AJ+4))=DIRCOS(I,J,1)*DIRCOS(I,J,3)*(SVTYPE(AI2+7,J)
     1           -SVTYPE(AI2+8,J))*LAMBDA(I,J)
            
            H((AI+3),(AJ+1))=-H((AI+1),(AJ+3))
            H((AI+3),(AJ+2))=H((AI+2),(AJ+3))
            H((AI+3),(AJ+3))=(DIRCOS(I,J,2)**2*SVTYPE(AI2+7,J)+(1.0D0-
     1           DIRCOS(I,J,2)**2)*SVTYPE(AI2+8,J))*LAMBDA(I,J)
            H((AI+3),(AJ+4))=DIRCOS(I,J,2)*DIRCOS(I,J,3)*(SVTYPE(AI2+7,J)
     1           -SVTYPE(AI2+8,J))*LAMBDA(I,J)
            
            H((AI+4),(AJ+1))=-H((AI+1),(AJ+4))
            H((AI+4),(AJ+2))=H((AI+2),(AJ+4))
            H((AI+4),(AJ+3))=H((AI+3),(AJ+4))
            H((AI+4),(AJ+4))=(DIRCOS(I,J,3)**2*SVTYPE(AI2+7,J)+(1.0D0-
     1           DIRCOS(I,J,3)**2)*SVTYPE(AI2+8,J))*LAMBDA(I,J)

           ELSE
            DO K=1,4
              DO K2=1,4
                 S(AI+K2,AJ+K)=0.0D0
                 H(AI+K2,AJ+K)=0.0D0
              END DO
            END DO
           END IF
          END DO

C   INTERACTION/OVERLAP OF DIFFERENT AOS ON THE SAME ATOM
         
          DO K=1,4
           DO K2=K+1,4
             S((AI+K),(AI+K2))=0.0D0
             H((AI+K),(AI+K2))=0.0D0
           END DO
          END DO

C   INTERACTION OF SAME AO ON THE SAME ATOM

          H((AI+1),(AI+1))=EPSS
          H((AI+2),(AI+2))=EPSP
          H((AI+3),(AI+3))=EPSP
          H((AI+4),(AI+4))=EPSP
          

      END DO

C   NOW WE HAVE TO MAKE SURE THE MATRIX S AND H ARE SYMMETRIC.
C   ERGO, HAVE TO GET THE UPPER DIAGONAL 'COS MUST HAVE COMPLETE
C   MATRIX FOR CHOLESKY DECOMPOSITION.

C     ELEMENT=S(1,6)
      
      DO I=1,4*N
          DO J=I+1,4*N
             S(J,I)=S(I,J)
             H(J,I)=H(I,J)
          END DO
    

C   INTERACTION/OVERLAP OF THE SAME AO ON THE SAME ATOM
         S(I,I)=1.0D0

      END DO
      DO I=1,4*N
         DO J=1,4*N
            HORIG(I,J)=H(I,J)
         END DO
      END DO
      
      NDIM=4*N
      NMAX=4*NATOMS

      FTEST=.FALSE.
 
C     CALL LANCZOS(NDIM,H,DIAG,1.0D0,-1.0D0,NFOUND)
C     CALL CGMIN(H,S,DIAG)
C     INFO=0

      CALL DSYGV( 1, 'V', 'U', NDIM, H, NMAX, S, NMAX, DIAG, WORK, 24*NATOMS, INFO )

C
C  THIS SORT ISN'T NEEDED FOR THE SGI LAPACK.F ROUTINE WHICH
C  INCORPORATES IT. 
C

      CALL EIGSRT(DIAG,H,NDIM,NMAX)
C     CALL EIGSRT(DIAG,H,NFOUND,NMAX)
C     WRITE(*,'(6F15.7)') (DIAG(J1),J1=1,NDIM)

      IF (INFO.NE.0) THEN
         FTEST=.TRUE.
         ENERGY=1.0D6
         PRINT*,'DSYGV FAILED - INFO=',INFO
         RETURN
      ENDIF

      ENERGY=0.0D0
      DO J=4*N,(2*N+1),-1
         ENERGY=ENERGY+DIAG(J)
      END DO

C   FOR SINGLE ATOM THERE SHOULD BE NO CONTRIBUTION FROM THE 
C   BOND COUNTING TERM      

      IF (N .EQ. 1) THEN
         ENERGY=2*ENERGY
      ELSE
         ENERGY=UREP+UBOND+2*ENERGY
      END IF

C   NOW CALL THE ALL NEW ORIGINALLY CRAFTED SUBROUTINE TO CALCULATE
C   THE FIRST DERIVATIVES.

       IF (GTEST) THEN
          CALL DERIVS1C(N,DERIV1ST,H)
       ELSE
          RETURN
       ENDIF

      RETURN
      END

C   THIS IS PHASE TWO WHERE WE CALCULATE THE FIRST DERIVATIVES
C   OF THE SILICON POTENTIAL CODED IN TB.SI.F. IT IS IN TIGHT
C   BINDING PARAMETERISED FORM.
C   OFF I GO...
C   THIS IS DERIVS1.F.JLOOP.BETTERISH IN THE RESRVES DIRECTORY
C   FOR THE RECORD

C   THIS IS THE MODIFIES VERSION IMPLEMENTING A CUTOFF IF ONE EXISTS
C   FOR PERIODIC BOUNDARY CONDITIONS.

      SUBROUTINE DERIVS1C(N,DERIV1ST,EIGVEC)
      USE COMMONS
      USE CONSTS
      USE DISTANCE
      IMPLICIT NONE 
      INTEGER I, J, K , N, AI, AJ, LEV, SV, ASV, NUM1, NUM2, I2, J2
      DOUBLE PRECISION REP1ST(NATOMS,3),BOND1ST(NATOMS,3), RR, D1, D2, D3,
     1                 ELEC1ST(NATOMS,3), DIFFH, E1, E2, AS1, DUMMY,
     2                 DIFFSV(2,4,4), SDC1, SDC2, SDC3, SQC1, SQC2, SQC3,
     3                 DIFFS2,R1ST(NATOMS,NATOMS),EIGVEC(4*NATOMS,4*NATOMS),
     4                 B1ST(NATOMS,NATOMS), DERIV1ST(3*NATOMS)
      DOUBLE PRECISION LMC(NATOMS,NATOMS),ALPHASUM1(NATOMS,NATOMS),ALPHASUM2,SVSUB,
     1                 SQDIRCOS(3*NATOMS,NATOMS),SUBDIRCOS(3*NATOMS,NATOMS),LONG,OPTION(3)
C
C  TAKE THE TRANSPOSE OF EIGVEC - MAKES LOOPS MORE EFFICIENT
C
      DO J=1,4*N
         DO I=J+1,4*N
            DUMMY=EIGVEC(J,I)
            EIGVEC(J,I)=EIGVEC(I,J)
            EIGVEC(I,J)=DUMMY
         ENDDO
      ENDDO
C
C   CAN PUT ARRAYS INTO A BLOCK DATA FORMAT INSTEAD OF PARAMETER
C   SO CAN JUST PUT IN ONCE IN A FILE TO BE INCLUDED

C   CAN'T START AN ARRAY WITH A NO. IE. 1STDERIV...SYNTAX ERROR

C   FIRST OF ALL CALCULATE DERIVATIVES OF REPULSIVE ENERGY TERM
C   THIS IS CALLED REP1ST.

      DO K=1,3
         DO I=1,N
                   DO J=I+1,N
              IF (R(J,I).LT.CUTOFF) THEN
               R1ST(J,I)=DIRCOS(I,J,K)*REPULSE(J,I)
              ELSE
               R1ST(J,I)=0.0D0
              END IF
               R1ST(I,J)=-R1ST(J,I)
            END DO
            R1ST(I,I)=0.0D0
            D1=0.0D0
            DO J=1,N
               D1=D1+BETA*R1ST(J,I)
            END DO
            REP1ST(I,K)=D1
         END DO
      END DO

C   EASY ISN'T IT.
C   NOW DO THE BOND COUNTING TERM DERIVATIVE.

      DO K=1,3
         DO I=1,N
            DO J=I+1,N
              IF (R(J,I).LT.CUTOFF) THEN
               B1ST(J,I)=DIRCOS(I,J,K)*BONDAGE(J,I)/(BONDAGE(J,I)+1.0D0)**2
              ELSE 
               B1ST(J,I)=0.0D0
              END IF
               B1ST(I,J)=-B1ST(J,I)
            END DO
            B1ST(I,I)=0.0D0
            D1=0.0D0
            DO J=1,N
               D1=D1-A*B1ST(J,I)/DELTA
            END DO
            BOND1ST(I,K)=D1
         END DO
      END DO

C   CO=1,2 OR 3 REPRESENTS THE X,Y OR Z COORDINATE AND THUS DIFFERENTIATION
C   THAT COORDINATE. CRIPES, I HOPE MY WORK IS MORE COMPACT THAN MY COMMENT
C   STATEMENTS.
      DO I=1,N
        DO J=I+1,N
           J2=3*(J-1)
                 DO NUM1=1,3
                    SQDIRCOS(J2+NUM1,I)=DIRCOS(J,I,NUM1)**2
                    SUBDIRCOS(J2+NUM1,I)=SQDIRCOS(J2+NUM1,I)-1.0D0
                 END DO

                 LMC(J,I)=DIRCOS(J,I,1)*DIRCOS(J,I,2)*DIRCOS(J,I,3)

                 ALPHASUM1(J,I)=(ALPHA+2.0D0/R(J,I))
        END DO
      END DO

C     ENTERING THE DIFFERENTIATION OF ELECTRONIC ENERGY ZONE
        DO K=1,N
          ELEC1ST(K,1)=0.0D0
        ENDDO
        DO I=1,N
         AI=4*(I-1)

C   DIFF OF INTERACTIONS OF AOS ON SAME ATOM
C   DON'T NEED TO INCLUDE FOR DIFFSV SINCE NOT USED - LOOP
C   IS ONLY FOR J=I+1,N

         DO J=I+1,N
          IF (R(I,J).LT.CUTOFF) THEN
           RR=1.0D0/R(J,I)
           AJ=4*(J-1)
           J2=3*(J-1)

C   A GOOD IDEA APPEARS TO BE SIMPLIFY THE EXPRESSIONS IN THE
C   DIFFERENTIATING SECTION AND REDUCE THE NUMBER OF INDICES


C   EXT IS FOR WHEN CO+X IS GREATER THAN 3 FOR CO=3 AND 2 IE. Z AND Y
C   EXT2 IS FOR WHEN THIS ONLY THE CASE FOR CO=3
C   IT IS JUST A METHOD TO PERMUTE THE X, Y AND Z VALUES ETC.

           D1=DIRCOS(J,I,1)
           D2=DIRCOS(J,I,2)
           D3=DIRCOS(J,I,3)

           AS1=ALPHASUM1(J,I)
           SDC1=SUBDIRCOS(J2+1,I)
           SDC2=SUBDIRCOS(J2+2,I)
           SDC3=SUBDIRCOS(J2+3,I)
           SQC1=SQDIRCOS(J2+1,I)
           SQC2=SQDIRCOS(J2+2,I)
           SQC3=SQDIRCOS(J2+3,I)

                 LONG=RR*(2.0D0*SQC1-1.0D0)+SQC1*ALPHA

                 OPTION(1)=-D2*LONG
                 OPTION(2)=-D3*LONG
                 OPTION(3)=-LMC(J,I)*AS1

C   DIFFSV(DIFF. OF S OR V,AO NO.,AO NO.)

C   DIFFERENTIATION OF OVERLAP OR INTERACTION BETWEEN ORBITALS
C   ON DIFFERENT ATOMS

                 DO SV=1,2
                    ASV=2*AI+4*(SV-1)
                    ALPHASUM2=D1*SVTYPE(ASV+2,J)*(ALPHA+RR)
                    SVSUB=SVTYPE(ASV+3,J)-SVTYPE(ASV+4,J)

                    DIFFSV(SV,1,1)=-ALPHA*D1*SVTYPE(ASV+1,J)
C                 DIFFSV(SV,1,2)=-SVTYPE(ASV+2,J)*(RR*SDC1+ALPHA*SQC1)
C             DIFFSV(SV,1,3)=-D2*ALPHASUM2
C                 DIFFSV(SV,1,4)=-D3*ALPHASUM2
                  DIFFSV(SV,1,2)= SVTYPE(ASV+2,J)*(RR*SDC1+ALPHA*SQC1)
              DIFFSV(SV,1,3)= D2*ALPHASUM2
                  DIFFSV(SV,1,4)= D3*ALPHASUM2

                  DIFFSV(SV,2,1)=-DIFFSV(SV,1,2)
                  DIFFSV(SV,2,2)=-D1*(SVTYPE(ASV+3,J)*(ALPHA*SQC1+2.0D0*RR*SDC1)-SVTYPE(ASV+4,J)*SDC1*AS1)
                  DIFFSV(SV,2,3)=SVSUB*OPTION(1)
                  DIFFSV(SV,2,4)=SVSUB*OPTION(2)
              
                  DIFFSV(SV,3,1)=-DIFFSV(SV,1,3)
                  DIFFSV(SV,3,2)= DIFFSV(SV,2,3)
                  DIFFSV(SV,3,3)=-D1*(SVTYPE(ASV+3,J)*SQC2*AS1+SVTYPE(ASV+4,J)*(-ALPHA*SDC2-2.0D0*SQC2*RR))
                  DIFFSV(SV,3,4)=SVSUB*OPTION(3)

                  DIFFSV(SV,4,1)=-DIFFSV(SV,1,4)
                  DIFFSV(SV,4,2)= DIFFSV(SV,2,4)
                  DIFFSV(SV,4,3)= DIFFSV(SV,3,4)
                  DIFFSV(SV,4,4)=-D1*(SVTYPE(ASV+3,J)*SQC3*AS1+SVTYPE(ASV+4,J)*(-ALPHA*SDC3-2.0D0*SQC3*RR))
               ENDDO

           DIFFS2=ALPHA*DIRCOS(I,J,1)*S2(I,J)
           E1=0.0D0
           DO NUM2=1,4   
             DO NUM1=1,4

C             DIFFH=DIFFSV(2,NUM1,NUM2)*LAMBDA(I,J)-2.0D0*S2(I,J)*HORIG((AJ+NUM1),(AI+NUM2))/LAMBDA(I,J)*DIFFS2
              DIFFH=DIFFSV(2,NUM1,NUM2)*LAMBDA(I,J)-2.0D0*S2(I,J)*HORIG((AJ+NUM2),(AI+NUM1))/LAMBDA(I,J)*DIFFS2
              E2=DIFFSV(1,NUM1,NUM2)
C             WRITE(*,'(A,4I3,2F15.7)') 'I,J,NUM1,NUM2,DIFFH,DIFFS=',I,J,NUM1,NUM2,DIFFH,E2


              DO LEV=4*N,2*N+1,-1
C              E1=E1+EIGVEC(LEV,AI+NUM2)*EIGVEC(LEV,AJ+NUM1)*(DIFFH-DIAG(LEV)*E2)
               E1=E1+EIGVEC(LEV,AJ+NUM2)*EIGVEC(LEV,AI+NUM1)*(DIFFH-DIAG(LEV)*E2)
              END DO !LEV
             END DO !NUM2
           END DO !NUM1
          ELSE
           E1=0.0D0
          END IF
           ELEC1ST(I,1)=ELEC1ST(I,1)+2.0D0*E1
           ELEC1ST(J,1)=ELEC1ST(J,1)-2.0D0*E1

         END DO  !J (1ST TIME)
        END DO  !I(1ST TIME)

        DO K=1,N
          ELEC1ST(K,2)=0.0D0
        ENDDO
        DO I=1,N
         AI=4*(I-1)

C   DIFF OF INTERACTIONS OF AOS ON SAME ATOM
C   DON'T NEED TO INCLUDE FOR DIFFSV SINCE NOT USED - LOOP
C   IS ONLY FOR J=I+1,N

         DO J=I+1,N
          IF (R(J,I).LT.CUTOFF) THEN
           RR=1.0D0/R(J,I)
           AJ=4*(J-1)
           J2=3*(J-1)

           D1=DIRCOS(J,I,2)
           D2=DIRCOS(J,I,3)
           D3=DIRCOS(J,I,1)

           AS1=ALPHASUM1(J,I)
           SDC1=SUBDIRCOS(J2+2,I)
           SDC2=SUBDIRCOS(J2+3,I)
           SDC3=SUBDIRCOS(J2+1,I)
           SQC1=SQDIRCOS(J2+2,I)
           SQC2=SQDIRCOS(J2+3,I)
           SQC3=SQDIRCOS(J2+1,I)

               LONG=RR*(2.0D0*SQC1-1.0D0)+SQC1*ALPHA

               OPTION(1)=-D2*LONG
               OPTION(2)=-D3*LONG
               OPTION(3)=-LMC(J,I)*AS1

C   DIFFSV(DIFF. OF S OR V,AO NO.,AO NO.)

C   DIFFERENTIATION OF OVERLAP OR INTERACTION BETWEEN ORBITALS
C   ON DIFFERENT ATOMS

               DO SV=1,2
                  ASV=2*AI+4*(SV-1)
                  ALPHASUM2=D1*SVTYPE(ASV+2,J)*(ALPHA+RR)
                  SVSUB=SVTYPE(ASV+3,J)-SVTYPE(ASV+4,J)

                  DIFFSV(SV,1,1)=-ALPHA*D1*SVTYPE(ASV+1,J)
                  DIFFSV(SV,1,3)= SVTYPE(ASV+2,J)*(RR*SDC1+ALPHA*SQC1)
              DIFFSV(SV,1,4)= D2*ALPHASUM2
                  DIFFSV(SV,1,2)= D3*ALPHASUM2

                  DIFFSV(SV,2,1)=-DIFFSV(SV,1,2)
                  DIFFSV(SV,3,3)=-D1*(SVTYPE(ASV+3,J)*(ALPHA*SQC1+2.0D0*RR*SDC1)-SVTYPE(ASV+4,J)*SDC1*AS1)
                  DIFFSV(SV,2,3)=SVSUB*OPTION(2)
                  DIFFSV(SV,2,4)=SVSUB*OPTION(3)
              
                  DIFFSV(SV,3,1)=-DIFFSV(SV,1,3)
                  DIFFSV(SV,3,2)= DIFFSV(SV,2,3)
                  DIFFSV(SV,4,4)=-D1*(SVTYPE(ASV+3,J)*SQC2*AS1+SVTYPE(ASV+4,J)*(-ALPHA*SDC2-2.0D0*SQC2*RR))
                  DIFFSV(SV,3,4)=SVSUB*OPTION(1)

                  DIFFSV(SV,4,1)=-DIFFSV(SV,1,4)
                  DIFFSV(SV,4,2)= DIFFSV(SV,2,4)
                  DIFFSV(SV,4,3)= DIFFSV(SV,3,4)
                  DIFFSV(SV,2,2)=-D1*(SVTYPE(ASV+3,J)*SQC3*AS1+SVTYPE(ASV+4,J)*(-ALPHA*SDC3-2.0D0*SQC3*RR))

               END DO ! SV

           DIFFS2=ALPHA*DIRCOS(I,J,2)*S2(I,J)
           E1=0.0D0
           DO NUM2=1,4   
             DO NUM1=1,4

              DIFFH=DIFFSV(2,NUM1,NUM2)*LAMBDA(I,J)-2.0D0*S2(I,J)*HORIG((AJ+NUM2),(AI+NUM1))/LAMBDA(I,J)*DIFFS2

              E2=DIFFSV(1,NUM1,NUM2)
              DO LEV=4*N,2*N+1,-1
               E1=E1+EIGVEC(LEV,AJ+NUM2)*EIGVEC(LEV,AI+NUM1)*(DIFFH-DIAG(LEV)*E2)
              END DO !LEV
             END DO !NUM2
           END DO !NUM1
          ELSE
           E1=0.0D0
          END IF
           ELEC1ST(I,2)=ELEC1ST(I,2)+2.0D0*E1
           ELEC1ST(J,2)=ELEC1ST(J,2)-2.0D0*E1

         END DO  !J (1ST TIME)
        END DO  !I(1ST TIME)

        DO K=1,N
          ELEC1ST(K,3)=0.0D0
        ENDDO
        DO I=1,N
         AI=4*(I-1)

         DO J=I+1,N
          IF (R(J,I).LT.CUTOFF) THEN
           RR=1.0D0/R(J,I)
           AJ=4*(J-1)
           J2=3*(J-1)

           D1=DIRCOS(J,I,3)
           D2=DIRCOS(J,I,1)
           D3=DIRCOS(J,I,2)

           AS1=ALPHASUM1(J,I)
           SDC1=SUBDIRCOS(J2+3,I)
           SDC2=SUBDIRCOS(J2+1,I)
           SDC3=SUBDIRCOS(J2+2,I)
           SQC1=SQDIRCOS(J2+3,I)
           SQC2=SQDIRCOS(J2+1,I)
           SQC3=SQDIRCOS(J2+2,I)

               LONG=RR*(2.0D0*SQC1-1.0D0)+SQC1*ALPHA

               OPTION(1)=-D2*LONG
               OPTION(2)=-D3*LONG
               OPTION(3)=-LMC(J,I)*AS1

C   DIFFSV(DIFF. OF S OR V,AO NO.,AO NO.)

C   DIFFERENTIATION OF OVERLAP OR INTERACTION BETWEEN ORBITALS
C   ON DIFFERENT ATOMS

               DO SV=1,2
                  ASV=2*AI+4*(SV-1)
                  ALPHASUM2=D1*SVTYPE(ASV+2,J)*(ALPHA+RR)
                  SVSUB=SVTYPE(ASV+3,J)-SVTYPE(ASV+4,J)

                  DIFFSV(SV,1,1)=-ALPHA*D1*SVTYPE(ASV+1,J)
                  DIFFSV(SV,1,4)= SVTYPE(ASV+2,J)*(RR*SDC1+ALPHA*SQC1)
              DIFFSV(SV,1,2)= D2*ALPHASUM2
                  DIFFSV(SV,1,3)= D3*ALPHASUM2

                  DIFFSV(SV,2,1)=-DIFFSV(SV,1,2)
                  DIFFSV(SV,4,4)=-D1*(SVTYPE(ASV+3,J)*(ALPHA*SQC1+2.0D0*RR*SDC1)-SVTYPE(ASV+4,J)*SDC1*AS1)
                  DIFFSV(SV,2,3)=SVSUB*OPTION(3)
                  DIFFSV(SV,2,4)=SVSUB*OPTION(1)
              
                  DIFFSV(SV,3,1)=-DIFFSV(SV,1,3)
                  DIFFSV(SV,3,2)= DIFFSV(SV,2,3)
                  DIFFSV(SV,2,2)=-D1*(SVTYPE(ASV+3,J)*SQC2*AS1+SVTYPE(ASV+4,J)*(-ALPHA*SDC2-2.0D0*SQC2*RR))
                  DIFFSV(SV,3,4)=SVSUB*OPTION(2)

                  DIFFSV(SV,4,1)=-DIFFSV(SV,1,4)
                  DIFFSV(SV,4,2)= DIFFSV(SV,2,4)
                  DIFFSV(SV,4,3)= DIFFSV(SV,3,4)
                  DIFFSV(SV,3,3)=-D1*(SVTYPE(ASV+3,J)*SQC3*AS1+SVTYPE(ASV+4,J)*(-ALPHA*SDC3-2.0D0*SQC3*RR))

               END DO ! SV

           DIFFS2=ALPHA*DIRCOS(I,J,3)*S2(I,J)
           E1=0.0D0
           DO NUM2=1,4   
             DO NUM1=1,4

              DIFFH=DIFFSV(2,NUM1,NUM2)*LAMBDA(I,J)-2.0D0*S2(I,J)*HORIG((AJ+NUM2),(AI+NUM1))/LAMBDA(I,J)*DIFFS2

              E2=DIFFSV(1,NUM1,NUM2)
              DO LEV=4*N,2*N+1,-1
               E1=E1+EIGVEC(LEV,AJ+NUM2)*EIGVEC(LEV,AI+NUM1)*(DIFFH-DIAG(LEV)*E2)
              END DO !LEV
             END DO !NUM2
           END DO !NUM1
          ELSE
           E1=0.0D0
          END IF
           ELEC1ST(I,3)=ELEC1ST(I,3)+2.0D0*E1
           ELEC1ST(J,3)=ELEC1ST(J,3)-2.0D0*E1

         END DO  !J (1ST TIME)
        END DO  !I(1ST TIME)

C   IN ORDER TO DIFFERENTIATE BY THE COORDINATE OF ATOM K, YOU ONLY GET 
C   A VALUE FOR THE DERIVATIVE IF ONE OF THE TWO ATOMS INVOLVED IN THE
C   PAIR INTERACTION IS K OTHERWISE IT IS ZERO. THIS IS ACHIEVED BY USE
C   OF THE FACTOR TERM. I'M SURE THIS IS HIGHLY INEFFICIENT BUT IF IT
C   WORKS THEN THAT IS WORTHWHILE. I CAN IMPROVE IT LATER....WHEN I'M 
C   DRAWING MY PENSION.            
C   HAVE TO KEEP IT IN A LOOP WHERE I AND J ARE THE ATOM NUMBER RATHER
C   THAN THE AO.

C   RECENT CHANGES INVOLVE REPLACING DERIVV WITH ITS SPECIFIC VALUE 
C   FACTOR*DIFFSV(2,X,Y) AND PERHAPS SIMILARLY FOR DERIVS.
C   DIFFSV AND DIFFH WILL BE ZERO.
C   MUST BE AWARE THAT ALTHOUGH NONE OF THE DIAGONAL ELEMENTS ARE DEFINED
C   THEY ARE EQUAL TO ZERO. NOT DEEMED NECESSARY TO CALC. THEM SINCE
C   THE LOOP NEVER REACHES I=J.  GOOD TO USE J=I+1 SINCE USES SYMMETRY TO 
C   CUT DOWN ON CALCULATIONS.

C   KEEP DIFFS2 SINCE IT IS ONLY DEPENDENT ON WHICH ATOMS ARE INTERACTING 
C   NOT THE AOS

C   INCLUDE FACTOR OF 2 FOR ELEC1ST SINCE TWO ELECTRONS FILL EACH MO

      DO K=1,3
         DO I=1,N
            I2=3*(I-1)
            DERIV1ST(I2+K)=2.0D0*ELEC1ST(I,K)+BOND1ST(I,K)+REP1ST(I,K)
         END DO
      END DO

      END
