C   GMIN: A PROGRAM FOR FINDING GLOBAL MINIMA
C   COPYRIGHT (C) 1999-2006 DAVID J. WALES
C   THIS FILE IS PART OF GMIN.
C
C   GMIN IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C   (AT YOUR OPTION) ANY LATER VERSION.
C
C   GMIN IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
C   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
C   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
C   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
C
      SUBROUTINE NEWINERTIA(X,MXATMS,NATOMS,SUM)
      IMPLICIT NONE
      INTEGER NATOMS, J1, J3, MXATMS
      DOUBLE PRECISION X(3*MXATMS), XM, YM, ZM, SUM

      XM=0.0D0
      YM=0.0D0
      ZM=0.0D0
      DO J1=1,NATOMS
         XM=XM+X(3*(J1-1)+1)
         YM=YM+X(3*(J1-1)+2)
         ZM=ZM+X(3*(J1-1)+3)
      ENDDO
      XM=XM/NATOMS
      YM=YM/NATOMS
      ZM=ZM/NATOMS
     
C     DUMMY=0.0D0
C     DO J3=1,NATOMS
C        DUMMY=DUMMY+(X(3*(J3-1)+2)-YM)**2+(X(3*(J3-1)+3)-ZM)**2
C     ENDDO
C     XIN=DUMMY
C     DUMMY=0.0D0
C     DO J3=1,NATOMS
C        DUMMY=DUMMY+(X(3*(J3-1)+1)-XM)**2+(X(3*(J3-1)+3)-ZM)**2
C     ENDDO
C     YIN=DUMMY
C     DUMMY=0.0D0
C     DO J3=1,NATOMS
C        DUMMY=DUMMY+(X(3*(J3-1)+1)-XM)**2+(X(3*(J3-1)+2)-YM)**2
C     ENDDO
C     ZIN=DUMMY
C
C  SUM OF EIGENVALUES IS THE TRACE OF THE MATRIX.

C     SUM=XIN+YIN+ZIN
      SUM=0.0D0
      DO J3=1,NATOMS
         SUM=SUM+(X(3*(J3-1)+1)-XM)**2+(X(3*(J3-1)+2)-YM)**2+(X(3*(J3-1)+3)-ZM)**2
      ENDDO
      SUM=2.0D0*SUM
C

      RETURN
      END
