! OPERATIONS.F90 IS INTENDED TO CONTAIN SIMPLE TRANSFORMS AND OPERATIONS THAT
! ARE OFTEN DONE ELSEWHERE IN THE CODE. IT IS TO BE GRADUALLY EXPANDED TO REDUCE
! THE NUMBER OF TIMES WE ARE REPEATING OUTSELVES.

! CONTENTS

! FUNCTION PAIRDISTANCE(ATOM1,ATOM2) - RETURNS THE DISTANCE BETWEEN ATOMS GIVEN
! THEIR COORDINATES


!
!> \BRIEF FUNCTION TO DETERMINE THE DISTANCE BETWEEN TWO POINTS IN 3D SPACE 
!> \AUTHOR CHRIS WHITTLESTON, CSW34@CAM.AC.UK
!
FUNCTION PAIRDISTANCE(ATOM1,ATOM2)
IMPLICIT NONE
! PAIRDISTANCE IS DEFINED AS IT IS THE FUNCTION NAME AND HENCE THE RETURNED
! VALUE
DOUBLE PRECISION :: PAIRDISTANCE 
DOUBLE PRECISION, INTENT(IN) :: ATOM1(3),ATOM2(3)
   
PAIRDISTANCE=DSQRT((ATOM1(1)-ATOM2(1))**2+(ATOM1(2)-ATOM2(2))**2+(ATOM1(3)-ATOM2(3))**2)
RETURN 
END FUNCTION PAIRDISTANCE
