C   GMIN: A PROGRAM FOR FINDING GLOBAL MINIMA
C   COPYRIGHT (C) 1999-2006 DAVID J. WALES
C   THIS FILE IS PART OF GMIN.
C
C   GMIN IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C   (AT YOUR OPTION) ANY LATER VERSION.
C
C   GMIN IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
C   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
C   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
C   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
C
      SUBROUTINE ORTHO(VEC1,COORDS,NOPT,NDEC,NATOMS)
      IMPLICIT NONE
      INTEGER J2,NOPT,NDEC,NATOMS,J3
      DOUBLE PRECISION DUMMY1, DUMMY2, VEC1(NDEC), COORDS(NDEC)
C
C  X TRANS
C
      DUMMY1=0.0D0
      DO J2=1,NOPT,3
         DUMMY1=DUMMY1+VEC1(J2)
      ENDDO
      DUMMY1=DUMMY1/(1.0D0*NATOMS)
      DO J2=1,NOPT,3
         VEC1(J2)=VEC1(J2)-DUMMY1
      ENDDO
C
C  Y TRANS
C
      DUMMY1=0.0D0
      DO J2=2,NOPT,3
         DUMMY1=DUMMY1+VEC1(J2)
      ENDDO
      DUMMY1=DUMMY1/(1.0D0*NATOMS)
      DO J2=2,NOPT,3
         VEC1(J2)=VEC1(J2)-DUMMY1
      ENDDO
C
C  Z TRANS
C
      DUMMY1=0.0D0
      DO J2=3,NOPT,3
         DUMMY1=DUMMY1+VEC1(J2)
      ENDDO
      DUMMY1=DUMMY1/(1.0D0*NATOMS)
      DO J2=3,NOPT,3
         VEC1(J2)=VEC1(J2)-DUMMY1
      ENDDO
C
C  FOR A PERIODIC SYSTEM WE SHOULD NOW RETURN
C

C
C  X ROT
C
      DUMMY1=0.0D0
      DUMMY2=0.0D0
      DO J2=1,NATOMS
         J3=3*J2
         DUMMY1=DUMMY1+VEC1(J3-1)*COORDS(J3)-VEC1(J3)*COORDS(J3-1)
         DUMMY2=DUMMY2+COORDS(J3)**2+COORDS(J3-1)**2
      ENDDO
      IF (DUMMY2.GT.0.0D0) THEN
         DUMMY2=DUMMY1/DUMMY2
         DO J2=1,NATOMS
            J3=3*J2
            VEC1(J3-1)=VEC1(J3-1)-DUMMY2*COORDS(J3)
            VEC1(J3)=VEC1(J3)+DUMMY2*COORDS(J3-1)
         ENDDO
      ENDIF
C
C  Y ROT
C
      DUMMY1=0.0D0
      DUMMY2=0.0D0
      DO J2=1,NATOMS
         J3=3*J2
         DUMMY1=DUMMY1-VEC1(J3-2)*COORDS(J3)+VEC1(J3)*COORDS(J3-2)
         DUMMY2=DUMMY2+COORDS(J3)**2+COORDS(J3-2)**2
      ENDDO
      IF (DUMMY2.GT.0.0D0) THEN
         DUMMY2=DUMMY1/DUMMY2
         DO J2=1,NATOMS
            J3=3*J2
            VEC1(J3-2)=VEC1(J3-2)+DUMMY2*COORDS(J3)
            VEC1(J3)=VEC1(J3)-DUMMY2*COORDS(J3-2)
         ENDDO
      ENDIF
C
C  Z ROT
C
      DUMMY1=0.0D0
      DUMMY2=0.0D0
      DO J2=1,NATOMS
         J3=3*J2
         DUMMY1=DUMMY1+VEC1(J3-2)*COORDS(J3-1)-VEC1(J3-1)*COORDS(J3-2)
         DUMMY2=DUMMY2+COORDS(J3)**2+COORDS(J3-2)**2
      ENDDO
      IF (DUMMY2.GT.0.0D0) THEN
         DUMMY2=DUMMY1/DUMMY2
         DO J2=1,NATOMS
            J3=3*J2
            VEC1(J3-2)=VEC1(J3-2)-DUMMY2*COORDS(J3-1)
            VEC1(J3-1)=VEC1(J3-1)+DUMMY2*COORDS(J3-2)
         ENDDO
      ENDIF

      RETURN
      END
