MODULE PORFUNCS
IMPLICIT NONE
CONTAINS
SUBROUTINE FLUSH(UNIT,ISTAT) ! FLUSHES THE OUTPUT BUFFER OF LOGICAL UNIT UNIT WHICH MUST BE

IMPLICIT NONE ! CONNECTED FOR FORMATTED SEQUENTIAL OUTPUT; ISTAT IS IGNORED

INTEGER,INTENT(IN) :: UNIT
INTEGER,INTENT(OUT),OPTIONAL :: ISTAT
!              CALL FLUSH(UNIT)

END SUBROUTINE FLUSH
          SUBROUTINE GETARG_SUBR(POSITION,VALUE) ! WRAPS GETARG FUNCTION SO IT CAN BE USE-ASSOCIATED

IMPLICIT NONE

INTEGER,INTENT(IN) :: POSITION
CHARACTER(LEN=*),INTENT(OUT) :: VALUE

CALL GETARG(POSITION,VALUE)

END SUBROUTINE GETARG_SUBR

SUBROUTINE IARGC_SUBR(N) ! WRAPS IARGC FUNCTION SO IT CAN BE USE-ASSOCIATED


IMPLICIT NONE
INTEGER,INTENT(OUT) :: N

INTEGER IARGC
N = IARGC()
END SUBROUTINE IARGC_SUBR

          SUBROUTINE FORK_SUBR(PID) ! RETURNS ZERO IN THE CHILD PROCESS, PID OF CHILD IN PARENT PROCESS
               IMPLICIT NONE
               INTEGER, INTENT(INOUT) :: PID
 
 
          END SUBROUTINE FORK_SUBR
 
          SUBROUTINE SYSTEM_SUBR(JOBSTRING,EXITSTATUS)
               IMPLICIT NONE
 
               CHARACTER(LEN=*),INTENT(IN) :: JOBSTRING
               INTEGER,INTENT(OUT) :: EXITSTATUS
          END SUBROUTINE SYSTEM_SUBR
 
          SUBROUTINE WAIT_SUBR(PID,EXITSTATUS)
               IMPLICIT NONE
 
               INTEGER,INTENT(INOUT) :: PID,EXITSTATUS
END SUBROUTINE WAIT_SUBR
          SUBROUTINE GETPID_SUBR(PID)
               IMPLICIT NONE
 
               INTEGER,INTENT(OUT) :: PID
               PID=GETPID()
          END SUBROUTINE GETPID_SUBR
END MODULE PORFUNCS
