C   GMIN: A PROGRAM FOR FINDING GLOBAL MINIMA
C   COPYRIGHT (C) 1999-2006 DAVID J. WALES
C   THIS FILE IS PART OF GMIN.
C
C   GMIN IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C   (AT YOUR OPTION) ANY LATER VERSION.
C
C   GMIN IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
C   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
C   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
C   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
C
C
C  SYMMETRY ANALYSIS - SAVE THE GENERATORS OF SYMMETRY
C  OPERATIONS DETECTED FOR A SUBSET OF ATOMS (OR ALL OF THEM).
C  TO APPLY THESE LATER WE NEED ALL ATOMS IN THE CORRESPONDING
C  ORIENTATION. NATOMS IS THE NUMBER OF ATOMS AT THE BEGINNING OF
C  Q WHOSE SYMMETRY ELEMENTS WE SEEK.
C
      SUBROUTINE PTGRP(Q,NATOMS,DEBUG,SYMTOL1,SYMTOL2,SYMTOL3,GENMAT,IGEN,FPGRP,CM,MATDIFF)
      USE COMMONS,ONLY : MYUNIT,HPTGRP
      IMPLICIT NONE
      INTEGER NATOMS
      DOUBLE PRECISION IT(3,3),CM(3),IV(3,3),TOLD,QREF(3*NATOMS),DIST2,
     1                 RM(3,3),QSORT(3*NATOMS),TATB(3), XTEMP(3,3), RMAT(3,3), DUM(3,3), DUM2(3,3),
     2                 SCRATCH(9*NATOMS), Q(3*NATOMS), GENMAT(100,3,3), 
     3                 MATDIFF, DISTANCE(120), QSAVE(3*NATOMS),
     4                 ANG,ANGLE2,ARGU,CMX,CMY,CMZ,RMINV(3,3),DUMMY,DUMMYSINV,WORSTRAD
      DOUBLE PRECISION NEWQ(3*NATOMS), MYDOT, ANGMAG, ANGMG, ANGIAX, DIP, TEST, BILEN, DIST, ZANG2, ZANGS, SYMTOL2, SYMTOL3, TOLO
      DOUBLE PRECISION ARG, ANGL, DPROJ, ZANG, Z, X, ATMP, XXX, RANG, TOLE, DTOR, ORDIS, SYMTOL1
      INTEGER IGEN, JPLANE, J3, IAXORD, ICLIP, INDEX, LOOK, IBOT2, ISIGMV, IMNAX, ISTART
      INTEGER MINORB, IK, IORBIT, NORBIT, IBOT, IDIR, IXX, IDEGEN, J2, J1, J, I, ISKIP, ICOMPX, JCOMP
      INTEGER JCOMPX, IHIGHX, ISAXIS, ICOMP2, NUMB, ISET, IERR, IIAX, ICOMPQ, ISINV
      INTEGER IDONE, ICOUNT, ICOMP, ILINEAR, IDGRP, IINV, IREF, IROT, IHIGH, IPRNT, IBTOR, PERM(NATOMS), IDUMMY
      LOGICAL NEW, DEBUG
C
C     SYMMETRY INFORMATION
C     FPGRP   FULL POINT GROUP
C     BPGRP   LARGEST ABELIAN SUBGROUP
C     PGRP    "COMPUTATIONAL" POINT GROUP
C
      CHARACTER(LEN=4) FPGRP, BPGRP, PGRP
C     INTEGER NORD(2*NATOMS+1)
      INTEGER NORD2(2*NATOMS+1)
      LOGICAL AGAIN
      CHARACTER(LEN=4) STRING, JNKSTR
      CHARACTER GPSTRING*80
 
      IBTOR(I,J) =IOR(I,J)
 
      IPRNT=0
      IF (DEBUG) IPRNT=3
      HPTGRP=1
      FPGRP='   '
      DTOR=ACOS(-1.D0)/180.D0
      AGAIN=.FALSE.
      TOLO=SYMTOL1
      TOLD=SYMTOL2
      TOLE=SYMTOL3
      QSAVE(1:3*NATOMS)=Q(1:3*NATOMS)
C
C INITIALIZE.
C
651   Q(1:3*NATOMS)=QSAVE(1:3*NATOMS) ! OTHERWISE THE COFM CAN BE RESET DIFFERENTLY 
      IHIGH=0
      IGEN=0
      IROT=0
      IREF=0
      IINV=0
      IDGRP=0
      ILINEAR=0
C     ICOMP=0
      ICOUNT=0
      IDONE=0
C     ISINV=0
C     ICOMPQ=0
C     IIAX=0
      ORDIS=0
      IERR=0
      ISET=0
      NUMB=0
C     ICOMP2=0
      IHIGHX=0
      ISAXIS=0
      JCOMPX=0
      JCOMP=0
C     ICOMPX=0
      ISKIP=0
C
C  TRANSLATE TO CENTER OF MASS.
C
      CMX=0.D0
      CMY=0.D0
      CMZ=0.D0
      DO I=1,NATOMS
         CMX=Q(3*I-2)+CMX
         CMY=Q(3*I-1)+CMY
         CMZ=Q(3*I)+CMZ
      ENDDO
      CM(1)=CMX/NATOMS
      CM(2)=CMY/NATOMS
      CM(3)=CMZ/NATOMS
      DO I=1,NATOMS
         DO J=0,2
            Q(3*I-J)=Q(3*I-J)-CM(3-J)
         ENDDO
      ENDDO
      QREF(1:3*NATOMS)=Q(1:3*NATOMS)
50    FORMAT(3(2X,F12.6))
C
C     BUILD INERTIA TENSOR
C
      CALL INERTIA(Q,IT,NATOMS)
C
C DIAGONALIZE INERTIA TENSOR. THE 0 FLAG REORDERS THE E/VALUES AND
C E/VECTORS FROM SMALLEST TO LARGEST.
C
      CALL EIG(IT,IV,3,3,0)
C
C  CHECK *NOW* FOR DEGENERACY OF EIGENVALUES -- IF PRESENT, THEN SEE IF
C  UNIQUE MOMENT OF INERTIA IS ALONG X.  IF SO, CHANGE THIS AXIS TO Z
C  BY ROTATING THE EIGENVECTOR MATRIX ABOUT Y.  THIS GUARANTEES THAT
C  THE UNIQUE AXIS WILL LIE ALONG Z.
C
C  THE MOMENTS COULD BE LARGE, SO THIS SHOULD BE A DIFFERENT TOLERANCE
C  TO THE DISTANCE CHECKING, I.E. A RELATIVE TOLERANCE.
C
      IF (ABS((IT(2,2)-IT(3,3))/(IT(1,1)+IT(2,2)+IT(3,3))).LT.TOLE) THEN
         RANG=90.0D0
         CALL ROTM(2,RANG,1,RM)
         CALL MATMUL(XTEMP,IV,RM,3,3,3,3,3,3)
         DO J1=1,3
            DO J2=1,3
               IV(J2,J1)=XTEMP(J2,J1)
            ENDDO
         ENDDO
         ATMP=IT(1,1)
         IT(1,1)=IT(3,3)
         IT(3,3)=ATMP
      ENDIF

      IF (IPRNT.GE.4) WRITE(MYUNIT,*)' DIAGONALIZED INERTIA TENSOR '
      IF (IPRNT.GE.4) WRITE(MYUNIT,50) ((IT(I,J),J=1,3),I = 1,3)
      CALL MATMULV(NEWQ,Q,IV,NATOMS,3,3)
      IF (IPRNT.GE.4) WRITE(MYUNIT,*) ' PRINCIPAL AXIS ORIENTATION FOR MOLECULAR SYSTEM '
      IF (IPRNT.GE.4) WRITE(MYUNIT,50) (NEWQ(I),I=1,3*NATOMS)
      AGAIN=.TRUE.
C
C  CHECK HANDEDNESS OF INERTIAL AXES.
C  IF DOT PRODUCT IS NEGATIVE; SWITCH SIGN OF
C  Y AXIS (THE CHOICE OF AXIS TO CHANGE IS ARBITRARY).
C
      CALL MYCROSS(IV(1,1),IV(1,2),TATB,1)
      XXX=MYDOT(TATB,IV(1,3),3)
      IF (XXX.LT.0.D0) THEN
         DO I=2,3*NATOMS-1,3
            NEWQ(I)=-NEWQ(I)
         ENDDO
      ENDIF
C
C  THE GEOMETRY USED TO FIND THE
C  SYMMETRY OPERATIONS CHANGES ORIENTATION THROUGHOUT PTGRP. USE NEW SUBROUTINE REORIENT TO
C  FIND THE MATRIX THAT MAPS THE REFERENCE CONFIGURATION IN QREF ONTO THE CURRENT
C  CONFIGURATION, AND GET THE GENERATOR FOR THE REFERENCE CONFIGURATION FROM A
C  SUITABLE MATRIX TRANSFORMATION.
C
C  GENERATE WELL-DEFINED SORTED COORDINATE VECTOR NOW. USED IN
C  SYMMETRY EVALUATION ROUTINES WHICH FOLLOW.
C  IF QSORT CHANGES THEN THE REFERENCE ORIENTATION HAS CHANGED, AND
C  SUBSEQUENT GENERATORS WILL BE WITH RESPECT TO THE NEW ORIENTATION.
C
C     CALL SORTXYZ(NEWQ,QSORT,NORD,TOLD,NATOMS)
      QSORT(1:3*NATOMS)=NEWQ(1:3*NATOMS)
      IF (IPRNT.GE.4) WRITE(MYUNIT,*) ' SORTED COORDINATE VECTOR'
      IF (IPRNT.GE.4) WRITE(MYUNIT,50) (QSORT(J),J=1,NATOMS*3)
C
C  CHECK TO SEE IF POINT GROUP IS ABELIAN - IF SO, SKIP TO THE ABELIAN
C  OPERATIONS BLOCK.
C
      X=-1.D0
      IDEGEN=0
      DO I=1,3
         Z=IT(I,I)
         IF (ABS((Z-X)/(IT(1,1)+IT(2,2)+IT(3,3))).LT.TOLE) IDEGEN=IDEGEN+1 
         X=Z
      ENDDO
      IF (IDEGEN.EQ.0) THEN
         IF (IPRNT.GE.3) WRITE(MYUNIT,'(A)') ' THE MOLECULE BELONGS TO AN ABELIAN GROUP.'
         GOTO 630
      ENDIF
C
C  *** START OF THE BIG IDEGEN=1 BLOCK.  ***
C
      IF (IDEGEN.EQ.1) THEN
C
C  CHECK TO MAKE SURE THAT THE PRINCIPAL AXES
C  ARE PARALLEL TO X, Y AND Z. IF NOT, ROTATE ORIENTATION TO THIS POINT.
C
C  USE A DIFFERENT TOLERANCE FOR ZERO MOMENT OF INERTIA CHECKING.
C
         FPGRP='   '
         IF (IPRNT.GE.3) WRITE(MYUNIT,110)
110      FORMAT(' THE MOLECULE BELONGS TO A POINT GROUP WITH DOUBLY',
     1        ' DEGENERATE REPRESENTATIONS.')
         DO I=1,3
            IF (ABS(IT(I,I)).LT.5.0D-2) ILINEAR=1
         ENDDO
         IF (ILINEAR.EQ.1) THEN
            IF (IPRNT.GE.3) WRITE(MYUNIT,'(A)') ' THE MOLECULE IS LINEAR.'
            GOTO 630
         ENDIF
C
C  CHECK FOR ROTATIONAL AXES FROM C2 TO 6. 
C
         DO I=2,6
            ZANG=360.D0/(1.0D0*I)
            DO J=1,3
               CALL ROTM(J,ZANG,1,RM)
               CALL MATMULV(SCRATCH,NEWQ,RM,NATOMS,3,3)
C              CALL COMPARE2(SCRATCH,QSORT,NORD,ICOMP,TOLD,NATOMS,IPRNT)
C              CALL MINPERM(NATOMS,QSORT,SCRATCH,0.0D0,0.0D0,0.0D0,.FALSE.,PERM,DUMMY,DIST2,WORSTRAD)
               CALL TESTSYMOP(NATOMS,QSORT,SCRATCH,PERM,TOLD,DIST2,WORSTRAD)
C              CALL BIPARTITE(NATOMS,QSORT,SCRATCH,PERM,DUMMY,DIST2,WORSTRAD)
C              IF (IPRNT.GE.4) WRITE(MYUNIT,*) ICOMP
C              IF (ICOMP.EQ.0) THEN
               IF (IPRNT.GE.4) WRITE(MYUNIT,'(A,I5,3F12.3)') 'IAXORD,DUMMY,DIST2,TOLD=',I,DUMMY,DIST2,TOLD
               IF (DIST2.LT.TOLD) THEN
                  IHIGH=I
                  IHIGHX=J
                  IGEN=1 ! JUST SAVE THE GENERATOR FOR THE PRINCIPAL AXIS AT THIS POINT
C                  IF (IGEN.LT.100) THEN
C                     DO J2=1,IGEN
C                        CALL CMPMAT(GENMAT,100,J2,RM,NEW,MATDIFF)
C                        IF (.NOT.NEW) GOTO 10
C                     ENDDO
C                     IGEN=IGEN+1
CC                    PRINT*,'HERE A IGEN=',IGEN
                     IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,*) 'AXIS ',J,' IS A ROTATION AXIS OF ORDER ',I
C
C   MAKE THE TRANSFORMATION MATRIX CORRESPONDING TO THE REFERENCE STATE IN QREF
C
!                    IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,*) 'CALLING REORIENT A'
                     CALL REORIENT(NATOMS,SCRATCH,QREF,RMAT)
                     CALL MYMATMUL(DUM,RM,RMAT,3,3,3)
                     CALL MATMULV(DUM2,DUM,RMAT,3,3,3)
                     GENMAT(IGEN,1:3,1:3)=DUM2(1:3,1:3)
!                    IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,*) 'HERE A IGEN=',IGEN,' NEW GENMAT:'
!                    IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,'(9F12.4)') GENMAT(IGEN,1:3,1:3)
10                   CONTINUE
C                  ENDIF
C
C  STUFF ORDERING INTO NORD2
C
C                 DO IXX=1,2*NATOMS
C                    NORD2(IXX)=NORD(IXX)
C                 ENDDO
                  DO IXX=1,NATOMS
                     NORD2(IXX)=IXX
                     NORD2(IXX+NATOMS)=PERM(IXX)
                  ENDDO
               ENDIF
            ENDDO
         ENDDO
C
C  CATCH PROBLEM IF IHIGH=0 BECAUSE TWO OF THE INERTIA TENSOR
C  E/VALUES JUST HAPPEN TO BE VERY CLOSE - START ALL OVER AGAIN
C  WITH SMALLER TOLE.
C
         IF (IHIGH.EQ.0) THEN
            IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,*) 'ACCIDENTAL DEGENERACY DETECTED'
            TOLE=TOLE/10.0D0
            IF (TOLE.GT.1.0D-7) THEN
               GOTO 651
            ELSE
               IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,*) ' THE FULL MOLECULAR POINT GROUP IS UNDETERMINED'
               WRITE(GPSTRING,653) ' THE FULL MOLECULAR POINT GROUP IS UNDETERMINED'
653            FORMAT(A80)
               GOTO 652
            ENDIF
         ENDIF

         IF (IPRNT.GE.3) WRITE(MYUNIT,160) IHIGH,IHIGHX
160      FORMAT(' THE HIGHEST ORDER ROTATIONAL AXIS IS C',I2,' ABOUT ',I2)
C
C  IF HIGHEST ORDER AXIS IS 2, AND THERE IS TWOFOLD DEGENERACY, THE
C  GROUP MUST BE D2D. PROCEED TO FIND THE S4 AXIS WHICH DETERMINES
C  THE UNIQUE ROTATIONAL AXIS. THIS IS SUBSEQUENTLY USED TO ROTATE
C  MOLECULE TO A USEFUL ORIENTATION. (NORD2 NOW CONTAINS AN EFFECTIVE
C  PERMUTATION LIST).
C
         IF (IHIGH.EQ.2) THEN
            IHIGHX=0
            FPGRP='D2D'
            HPTGRP=8
            ZANG=90.0D0
            DO IDIR=1,3
               CALL ROTM(IDIR,ZANG,1,RM)
               CALL MATMULV(SCRATCH(NATOMS*3+1),NEWQ,RM,NATOMS,3,3)
               CALL REFLECT(SCRATCH(NATOMS*3+1),SCRATCH,NATOMS,IDIR)
C              CALL COMPARE2(SCRATCH,QSORT,NORD,ICOMP,TOLD,NATOMS,IPRNT)
C              IF (ICOMP.EQ.0) THEN
C              CALL MINPERM(NATOMS,QSORT,SCRATCH,0.0D0,0.0D0,0.0D0,.FALSE.,PERM,DUMMY,DIST2,WORSTRAD)
               CALL TESTSYMOP(NATOMS,QSORT,SCRATCH,PERM,TOLD,DIST2,WORSTRAD)
C              CALL BIPARTITE(NATOMS,QSORT,SCRATCH,PERM,DUMMY,DIST2,WORSTRAD)
               IF (DIST2.LT.TOLD) THEN
                  IHIGHX=IDIR
C                 DO I=1,2*NATOMS
C                    NORD2(I)=NORD(I)
C                 ENDDO
                  DO I=1,NATOMS
                     NORD2(I)=I
                     NORD2(I+NATOMS)=PERM(I)
                  ENDDO
               ENDIF
            ENDDO
            IF (IHIGHX.EQ.0) THEN
               IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,*) 'ACCIDENTAL DEGENERACY DETECTED'
               TOLE=TOLE/10.0D0
               IF (TOLE.GT.1.0D-7) THEN
                  GOTO 651
               ELSE
                  IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,*) ' THE FULL MOLECULAR POINT GROUP IS UNDETERMINED'
                  WRITE(GPSTRING,653) ' THE FULL MOLECULAR POINT GROUP IS UNDETERMINED'
                  GOTO 652
               ENDIF
            ENDIF
            IF (IPRNT.GE.3) WRITE(MYUNIT,190) IHIGHX
190         FORMAT(' THE UNIQUE ROTATIONAL AXIS IS ',I1,'.')
         ENDIF
C
C  NOW, THE UNIQUE AXIS IS KNOWN, NO MATTER WHAT THE GROUP IS.
C  PROCEED TO ROTATE AROUND UNIQUE AXIS SUCH THAT THE PROJECTION
C  OF ONE OF THE ATOMS WHICH ARE EQUIVALENT UNDER THE ROTATION LIES
C  ALONG ONE OF THE OTHER TWO CARTESIAN AXES.
C
C  FIND AN ATOM WHICH IS PERMUTED UNDER THE ROTATION.
C  NEW PROBLEM - IN A LARGE MOLECULE IT IS POSSIBLE TO HAVE, SAY,
C  A 10-ORBIT, WITH A PRINCIPAL AXIS OF ORDER ONLY 5. IN THIS CASE
C  WE NEED TO FIND AN ATOM FROM AN ORBIT OF ORDER EQUAL TO THE
C  ORDER OF THE PRINCIPAL AXIS TO LOOK FOR VERTICAL MIRROR PLANES.
C  IF WE PUT AN ATOM FROM THE 10-ORBIT IN THE XZ OR YZ PLANE WE
C  HAVE NOT PUT A VERTICAL MIRROR PLANE COINCIDENT WITH THE AXIS.
C  ON THE OTHER HAND, FOR D_{ND} GROUPS WITH ODD N WE ACTUALLY
C  MAY NOT HAVE AN ORBIT OF SIZE EQUAL TO THE ORDER OF THE PRINCIPAL
C  AXIS - THERE IS SURE TO BE ONE OF TWICE THE SIZE THOUGH. HERE
C  THE ORIGINAL ALGORITHM WOULD HAVE WORKED.
C  THE PRINCIPAL AXIS ORDER IS IHIGH - THIS IS ONLY NEEDED IF
C  IHIGH IS ODD.
C
         IF (MOD(IHIGH,2).EQ.1) THEN
            IF (IPRNT.GE.4) WRITE(MYUNIT,*)' BEFORE ROTATION'
            IF (IPRNT.GE.4) WRITE(MYUNIT,50) (NEWQ(J),J=1,NATOMS*3)
            CALL ZERO(SCRATCH,3*NATOMS*3)
            DO J=1,NATOMS
               NORD2(J)=J
               IBOT=3*J-2
               SCRATCH(J)=SQRT(MYDOT(NEWQ(IBOT),NEWQ(IBOT),3))
            ENDDO
            CALL PIKSR2(NATOMS,SCRATCH,NORD2)
            IF (IPRNT.GE.3) WRITE(MYUNIT,440) (SCRATCH(J),J=1,NATOMS)
440         FORMAT(' ORBIT MATRIX:',(F10.6,/))
            NORBIT=1
            IORBIT=1
            DO J=2,NATOMS+1
C              IF (ABS(SCRATCH(J)-SCRATCH(J-1)).LT.TOLD) IORBIT=IORBIT+1
C              IF (ABS(SCRATCH(J)-SCRATCH(J-1)).GT.TOLD) THEN
               IF (ABS(SCRATCH(J)-SCRATCH(J-1)).LT.TOLO) IORBIT=IORBIT+1
               IF (ABS(SCRATCH(J)-SCRATCH(J-1)).GT.TOLO) THEN
                  NORD2(NATOMS+NORBIT)=IORBIT
                  SCRATCH(6*NATOMS+NORBIT)=ABS(SCRATCH(J-1))
                  IF (J.LE.NATOMS) THEN
                     NORBIT=NORBIT+1
                     IORBIT=1
                  ENDIF
               ENDIF
            ENDDO

            IF (IPRNT.GE.130) THEN
                WRITE(MYUNIT,*)' SCRATCH VECTOR '
                WRITE(MYUNIT,*) (SCRATCH(IK),IK=1,NATOMS)
                WRITE(MYUNIT,*)' ORBIT DISTANCES: '
                WRITE(MYUNIT,*) (SCRATCH(6*NATOMS+IK),IK=1,NORBIT)
            ENDIF
            NUMB=0
            IREF=0
C
C  HERE WE ARE TRYING TO FIND AN ORBIT WHOSE SIZE NORD2 IS A MULTIPLE
C  OF IHIGH. IF SUCH AN ORBIT IS NOT FOUND THEN IREF WILL REMAIN ZERO 
C  AND WE MUST FIND MORE SELF-CONSISTENT TOLERANCES.
C
            DO I=1,NORBIT
               NUMB=NORD2(NATOMS+I)+NUMB
C              WRITE(MYUNIT,*) 'I,IHIGH,NORD2=',I,IHIGH,NORD2(NATOMS+I)
               IF (NORD2(NATOMS+I).EQ.IHIGH) THEN
                  MINORB=NORD2(NATOMS+I)
                  IREF=1+NUMB-NORD2(NATOMS+I)
                  GOTO 250
               ENDIF
            ENDDO
250         IF (IREF.NE.0) THEN
               IF (IPRNT.GE.13) WRITE(MYUNIT,260) MINORB, NORD2(IREF) 
260            FORMAT(' THE PRINCIPAL AXIS HAS ORDER ',I3,/,
     1         ' ATOM NUMBER ',I3,' BELONGS TO AN ORBIT OF THIS ORDER AND', 
     2         ' WILL BE USED AS A REFERENCE.')
               IF (IPRNT.GE.13) WRITE(MYUNIT,520) (NORD2(IREF+J),J=1,MINORB-1)
               ICOUNT=NORD2(IREF)
            ELSE
               NUMB=0
               IREF=0
               DO I=1,NORBIT
                  NUMB=NORD2(NATOMS+I)+NUMB
                  IF (NORD2(NATOMS+I).EQ.2*IHIGH) THEN
                     MINORB=NORD2(NATOMS+I)
                     IREF=1+NUMB-NORD2(NATOMS+I)
                     GOTO 255
                  ENDIF
               ENDDO
255            IF (IREF.NE.0) THEN
                  IF (IPRNT.GE.13) WRITE(MYUNIT,265) MINORB, NORD2(IREF)
265               FORMAT(' THE PRINCIPAL AXIS HAS ORDER ',I3,/,
     1                   ' ATOM NUMBER ',I3,' BELONGS TO AN ORBIT OF TWICE THIS ORDER', 
     2                   ' AND WILL BE USED AS A REFERENCE.')
                  IF (IPRNT.GE.13) WRITE(MYUNIT,520) (NORD2(IREF+J),J=1,MINORB-1)
                  ICOUNT=NORD2(IREF)
               ELSE
                  NUMB=0
                  IREF=0
                  DO I=1,NORBIT
                     NUMB=NORD2(NATOMS+I)+NUMB
                     IF (NORD2(NATOMS+I).EQ.4*IHIGH) THEN
                        MINORB=NORD2(NATOMS+I)
                        IREF=1+NUMB-NORD2(NATOMS+I)
                        GOTO 256
                     ENDIF
                  ENDDO
256               IF (IREF.EQ.0) THEN
                     IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,'(A,G20.10)')
     &   'ORBIT SIZE INCONSISTENT WITH AXIS ORDER - TRY DECREASING TOLD TO ',TOLD/10.0D0
                     TOLD=TOLD/10.0D0
                     IF (TOLD.GT.1.0D-7) THEN
                        GOTO 651
                     ELSE
                        IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,*) ' THE FULL MOLECULAR POINT GROUP IS UNDETERMINED'
                        WRITE(GPSTRING,653) ' THE FULL MOLECULAR POINT GROUP IS UNDETERMINED'
                        GOTO 652
                     ENDIF
                  ENDIF
                  IF (IPRNT.GE.13) WRITE(MYUNIT,266) MINORB, NORD2(IREF)
266               FORMAT(' THE PRINCIPAL AXIS HAS ORDER ',I3,/,
     1' ATOM NUMBER ',I3,' BELONGS TO AN ORBIT OF FOUR TIMES THIS ORDER'
     2            ,' AND WILL BE USED AS A REFERENCE.')
                  IF (IPRNT.GE.13) WRITE(MYUNIT,520) (NORD2(IREF+J),J=1,MINORB-1)
                  ICOUNT=NORD2(IREF)
               ENDIF
            ENDIF
         ELSE
            DO I=NATOMS,1,-1
C              PRINT*,'I,ICOUNT,NORD2,NORD2(I+NATOMS)=',I,ICOUNT,NORD2(I),NORD2(I+NATOMS)
C              IF (NORD2(I).NE.NORD2(I+NATOMS)) ICOUNT=NORD2(I)
               IF (I.NE.PERM(I)) ICOUNT=I
C              PRINT '(A,3I5)','I,PERM(I),ICOUNT=',I,PERM(I),ICOUNT
            ENDDO
         ENDIF
C
C   CALCULATE ANGLE BETWEEN PROJECTION OF THIS VECTOR AND ONE OF THE 
C   CARTESIAN AXES
C
         ISTART=3*(ICOUNT-1)
         IF (ICOUNT.LT.1) THEN
            WRITE(MYUNIT,*) 'ERROR - ICOUNT=',ICOUNT
         ENDIF
         DPROJ=SQRT( NEWQ(ISTART+1)**2 + NEWQ(ISTART+2)**2 +
     1        NEWQ(ISTART+3)**2 - NEWQ(ISTART+IHIGHX)**2 )
         IF (DPROJ.EQ.0.0D0) THEN
            WRITE(MYUNIT,'(A)') 'WARNING IN PTGRP, ZERO PROJECTION, THIS SHOULD NEVER HAPPEN'
            DPROJ=1.0D-3
         ENDIF
C
C   FIND FIRST CARTESIAN AXIS WHICH IS NOT THE UNIQUE AXIS.
C   (HAS TO BE X OR Y)
C
         IMNAX=2-IHIGHX/2
         ARG=NEWQ(ISTART+IMNAX)/DPROJ
         IF (ABS(ARG).GT.1.0D0) ARG=1.0D0*ARG/ABS(ARG)
         ANGL=ACOS(ARG)/DTOR
C
C   SKIP OUT OF LOOP IF ALIGNMENT ALREADY SATISFIED
C
         DO I=0,2
            X=ANGL-1.0D0*(I*90)
C           IF (ABS(X).LT.TOLD) ISKIP=1
            IF (ABS(X).LT.TOLO) ISKIP=1
         ENDDO
         IF (ISKIP.EQ.1) GOTO 340
C
C   GET SIGN OF ANGLE NEEDED TO ROTATE MOLECULE INTO POSITION
C
C   I FOUND A CASE WHERE THIS DIDN'T WORK. THERE ARE ONLY TWO
C   POSSIBILITIES (+ AND -) SO IF ONE DOESN'T WORK, JUST USE 
C   THE OTHER!
C
C        Z0=1
C        DO I=1,3
C           IF (I.NE.IHIGHX) Z0=Z0*NEWQ(ISTART+I)
C        ENDDO
C        IF (Z0.GT.0.D0) ANGL=-ANGL
C
C   ROTATE MOLECULE INTO POSITION - ALL NATOMS 
C
         CALL ZERO(SCRATCH,NATOMS*2*3)
         CALL VADD(SCRATCH(1),SCRATCH(NATOMS*3+1),NEWQ,NATOMS*3,1) ! PUTS NEWQ IN SCRATCH
         CALL ROTM(IHIGHX,ANGL,1,RM)
         CALL ROTM(IHIGHX,-ANGL,1,RMINV)
C        PRINT*,'NEWQ BEFORE TRANSFORMATION:'
C        PRINT '(3G20.10)',NEWQ(1:3*NATOMS)
         CALL MATMULV(NEWQ,SCRATCH,RM,NATOMS,3,3) ! PUTS ROTATED STRUCTURE IN NEWQ
         IF (IPRNT.GE.3) WRITE(MYUNIT,310) ANGL,IHIGHX
310      FORMAT(' MOLECULE ROTATED THROUGH ',F20.10,' DEGREES ',
     1        'ABOUT THE ',I1,' AXIS.')
         IF (IPRNT.GE.4) WRITE(MYUNIT,*)' AFTER ROTATION:'
         IF (IPRNT.GE.4) WRITE(MYUNIT,50) (NEWQ(J),J=1,NATOMS*3)

         DO 320 J1=1,3
            IF (J1.EQ.IHIGHX) GOTO 320
            IF (J1.EQ.IMNAX) GOTO 320
            IF (ABS(NEWQ(ISTART+J1)).GT.1.0D-6) THEN
               ANGL=-2.0D0*ANGL
               CALL ZERO(SCRATCH,NATOMS*2*3)
               CALL VADD(SCRATCH(1),SCRATCH(NATOMS*3+1),NEWQ,NATOMS*3,1) ! PUTS NEWQ IN SCRATCH
               CALL ROTM(IHIGHX,ANGL,1,RM)
               CALL ROTM(IHIGHX,-ANGL,1,RMINV)
               CALL MATMULV(NEWQ,SCRATCH,RM,NATOMS,3,3) ! PUTS TRANSFORMED STRUCTURE IN NEWQ
               IF (IPRNT.GE.3) WRITE(MYUNIT,310) ANGL,IHIGHX
               IF (IPRNT.GE.4) WRITE(MYUNIT,*)' AFTER ROTATION:'
               IF (IPRNT.GE.4) WRITE(MYUNIT,50) (NEWQ(J),J=1,NATOMS*3)  
            ENDIF
320      CONTINUE
C
C   NEW REFERENCE STRUCTURE, SO WE NEED TO GENERATE NEW SORTED VECTOR
C   AND UPDATE THE TRANSFORMATION MATRIX FOR THE REFERENCE STRUCTURE
C
C        CALL SORTXYZ(NEWQ,QSORT,NORD,TOLD,NATOMS)
         QSORT(1:3*NATOMS)=NEWQ(1:3*NATOMS)
C     PRINT*,'B QSORT:'
C     PRINT '(3G20.10)',QSORT(1:3*NATOMS)
C     PRINT*,'NEWQ:'
C     PRINT '(3G20.10)',NEWQ(1:3*NATOMS)
         IF (IPRNT.GE.4) WRITE(MYUNIT,*) ' NEW SORTED COORDINATES'
         IF (IPRNT.GE.4) WRITE(MYUNIT,50) (QSORT(J),J=1,NATOMS*3)
C
C   CHECK FOR SIGMA(V) PLANES NOW.
C
         CALL ZERO(SCRATCH,NATOMS*3*2)
         ISIGMV=0
         DO 330 J=1,3
            IF (J.EQ.IHIGHX) GOTO 330
            CALL REFLECT(NEWQ,SCRATCH,NATOMS,J)
C           CALL COMPARE2(SCRATCH,QSORT,NORD,ICOMPX,TOLD,NATOMS,IPRNT)
C           IF (ICOMPX.EQ.0) ISIGMV=1
C           CALL MINPERM(NATOMS,QSORT,SCRATCH,0.0D0,0.0D0,0.0D0,.FALSE.,PERM,DUMMY,DIST2,WORSTRAD)
            CALL TESTSYMOP(NATOMS,QSORT,SCRATCH,PERM,TOLD,DIST2,WORSTRAD)
C           CALL BIPARTITE(NATOMS,QSORT,SCRATCH,PERM,DUMMY,DIST2,WORSTRAD)
            IF (DIST2.LT.TOLD) ISIGMV=1
330      CONTINUE
C
C   CHECK FOR S(2N) AXIS
C
340      ZANGS=180.D0/(1.0D0*IHIGH)
         CALL ROTM(IHIGHX,ZANGS,1,RM)
         CALL MATMULV(SCRATCH(NATOMS*3+1),NEWQ,RM,NATOMS,3,3)
         CALL REFLECT(SCRATCH(NATOMS*3+1),SCRATCH,NATOMS,IHIGHX)
C        CALL COMPARE2(SCRATCH,QSORT,NORD,ICOMP,TOLD,NATOMS,IPRNT)
C        IF (ICOMP.EQ.0) THEN
C        CALL MINPERM(NATOMS,QSORT,SCRATCH,0.0D0,0.0D0,0.0D0,.FALSE.,PERM,DUMMY,DIST2,WORSTRAD)
         CALL TESTSYMOP(NATOMS,QSORT,SCRATCH,PERM,TOLD,DIST2,WORSTRAD)
C        PRINT '(A,G20.10,A,I6,A,G20.10,I6)','DIST2 AFTER CHECK FOR S(2N) AXIS=',DIST2,' IHIGH=',IHIGH,' TOLD,IPRNT=',TOLD,IPRNT
C        CALL BIPARTITE(NATOMS,QSORT,SCRATCH,PERM,DUMMY,DIST2,WORSTRAD)
         IF (DIST2.LT.TOLD) THEN
            ISAXIS=1
            IF (IPRNT.GE.3) THEN
               WRITE(MYUNIT,350) 2*IHIGH
350            FORMAT(' S',I3,' AXIS EXISTS.')
            ENDIF
            IF (IGEN.LT.100) THEN
               DO J1=1,3
                  RM(J1,IHIGHX)=-RM(J1,IHIGHX)
               ENDDO
C
C   MAKE THE TRANSFORMATION MATRIX CORRESPONDING TO THE REFERENCE STATE IN QREF 
C
!              IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,*) 'CALLING REORIENT F'
               CALL REORIENT(NATOMS,SCRATCH,QREF,RMAT) 
               CALL MYMATMUL(DUM,RM,RMAT,3,3,3)
               CALL MATMULV(DUM2,DUM,RMAT,3,3,3)
               DO J2=1,IGEN
                  CALL CMPMAT(GENMAT,100,J2,DUM2,NEW,MATDIFF)
                  IF (.NOT.NEW) GOTO 61
               ENDDO
               IGEN=IGEN+1
               GENMAT(IGEN,1:3,1:3)=DUM2(1:3,1:3)
!              IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,*) 'HERE F IGEN=',IGEN,' NEW GENMAT:'
!              IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,'(9F12.4)') GENMAT(IGEN,1:3,1:3)
61          CONTINUE
            ENDIF
         ENDIF
C        PRINT*,'DUMMY AFTER CHECK FOR S(2N) AXIS = ',DUMMY,' ISAXIS=',ISAXIS
C
C   LOOK FOR PERPENDICULAR C2 AXES - CHECK ALONG CARTESIAN AXES AND
C   ALONG ANGLE BISECTORS OF S2N OPERATIONS
C
C   FIRST ROTATE MOLECULE BY 1/2 S(2N) ANGLE AROUND IHIGH X AND PUT IN
C   SCRATCH(6*NATOMS+1)
C
         ZANG=180.D0
         ZANG2=180.D0/(2.D0*IHIGH)
         CALL ROTM(IHIGHX,ZANG2,1,RM)
         CALL MATMULV(SCRATCH(6*NATOMS+1),NEWQ,RM,NATOMS,3,3)
         CALL ZERO(SCRATCH(3*NATOMS+1),3*NATOMS)
C        CALL SORTXYZ(SCRATCH(6*NATOMS+1),SCRATCH(3*NATOMS+1),NORD,TOLD,NATOMS)
         SCRATCH(3*NATOMS+1:6*NATOMS)=SCRATCH(6*NATOMS+1:9*NATOMS)
         DO 360 I=1,3
            IF (I.EQ.IHIGHX) GOTO 360
C
C   CHECKING CARTESIAN AXES FOR BOTH ROTATED AND UNROTATED MOLECULE
C
            CALL ROTM(I,ZANG,1,RM)
            CALL MATMULV(SCRATCH,NEWQ,RM,NATOMS,3,3)
C           CALL COMPARE2(SCRATCH,QSORT,NORD,ICOMP,TOLD,NATOMS,IPRNT)
C           CALL MINPERM(NATOMS,QSORT,SCRATCH,0.0D0,0.0D0,0.0D0,.FALSE.,PERM,DUMMY,DIST2,WORSTRAD)
            CALL TESTSYMOP(NATOMS,QSORT,SCRATCH,PERM,TOLD,DIST2,WORSTRAD)
C           CALL BIPARTITE(NATOMS,QSORT,SCRATCH,PERM,DUMMY,DIST2,WORSTRAD)
            IF (DIST2.LT.TOLD) JCOMP=JCOMP+1
            CALL MATMULV(SCRATCH,SCRATCH(6*NATOMS+1),RM,NATOMS,3,3)
C           CALL COMPARE2(SCRATCH,SCRATCH(3*NATOMS+1),NORD,ICOMPX,TOLD,NATOMS,IPRNT)
C           CALL MINPERM(NATOMS,SCRATCH(3*NATOMS+1),SCRATCH,0.0D0,0.0D0,0.0D0,.FALSE.,PERM,DUMMY,DIST2,WORSTRAD)
            CALL TESTSYMOP(NATOMS,SCRATCH(3*NATOMS+1),SCRATCH,PERM,TOLD,DIST2,WORSTRAD)
C           CALL BIPARTITE(NATOMS,SCRATCH(3*NATOMS+1),SCRATCH,PERM,DUMMY,DIST2,WORSTRAD)
            IF (DIST2.LT.TOLD) JCOMPX=JCOMPX+1
C           IF (ICOMP.EQ.0) JCOMP=JCOMP+1
C           IF (ICOMPX.EQ.0) JCOMPX=JCOMPX+1
360      CONTINUE
         IF (JCOMP.GE.1) THEN
            IF (IPRNT.GE.3) WRITE(MYUNIT,'(A)') ' ON-AXIS PERPENDICULAR C2 ELEMENTS FOUND.'
            IDGRP=1
         ELSEIF (JCOMPX.GE.1) THEN
            IF (IPRNT.GE.3) WRITE(MYUNIT,'(A)') ' OFF-AXIS PERPENDICULAR C2 ELEMENTS FOUND.'
            IDGRP=1
         ENDIF
C
C   CHECK FOR SIGMA(H)
C
         IF (IDGRP.EQ.1) THEN
            CALL REFLECT(NEWQ,SCRATCH,NATOMS,IHIGHX)
C           CALL COMPARE2(SCRATCH,QSORT,NORD,ICOMP2,TOLD,NATOMS,IPRNT)
C           IF (ICOMP2.EQ.0) THEN
C           CALL MINPERM(NATOMS,QSORT,SCRATCH,0.0D0,0.0D0,0.0D0,.FALSE.,PERM,DUMMY,DIST2,WORSTRAD)
            CALL TESTSYMOP(NATOMS,QSORT,SCRATCH,PERM,TOLD,DIST2,WORSTRAD)
C           CALL BIPARTITE(NATOMS,QSORT,SCRATCH,PERM,DUMMY,DIST2,WORSTRAD)
            IF (DIST2.LT.TOLD) THEN
               FPGRP='DNH'
               HPTGRP=4*IHIGH
               IF (IPRNT.GE.3) WRITE(MYUNIT,390)
            ENDIF
         ELSE
            CALL REFLECT(NEWQ,SCRATCH,NATOMS,IHIGHX)
390         FORMAT(' HORIZONTAL PLANE OF SYMMETRY FOUND.')
C           CALL COMPARE2(SCRATCH,QSORT,NORD,ICOMP2,TOLD,NATOMS,IPRNT)
C           IF (ICOMP2.EQ.0) THEN
C           CALL MINPERM(NATOMS,QSORT,SCRATCH,0.0D0,0.0D0,0.0D0,.FALSE.,PERM,DUMMY,DIST2,WORSTRAD)
            CALL TESTSYMOP(NATOMS,QSORT,SCRATCH,PERM,TOLD,DIST2,WORSTRAD)
C           CALL BIPARTITE(NATOMS,QSORT,SCRATCH,PERM,DUMMY,DIST2,WORSTRAD)
            IF (DIST2.LT.TOLD) THEN
               FPGRP='CNH'
               HPTGRP=2*IHIGH
               IF (IPRNT.GE.3) WRITE(MYUNIT,390)
            ELSE
               FPGRP='CN '
               HPTGRP=IHIGH
               IF (ISAXIS.EQ.1) THEN
                  FPGRP='SN '
                  IHIGH=2*IHIGH
                  HPTGRP=IHIGH
               ENDIF
               DO 400 J=1,3
                  IF (J.EQ.IHIGHX) GOTO 400
                  CALL REFLECT(NEWQ,SCRATCH,NATOMS,J)
C                 CALL COMPARE2(SCRATCH,QSORT,NORD,ICOMP2,TOLD,NATOMS,IPRNT)
C                 IF (ICOMP2.EQ.0) FPGRP='CNV'
C                 CALL MINPERM(NATOMS,QSORT,SCRATCH,0.0D0,0.0D0,0.0D0,.FALSE.,PERM,DUMMY,DIST2,WORSTRAD)
                  CALL TESTSYMOP(NATOMS,QSORT,SCRATCH,PERM,TOLD,DIST2,WORSTRAD)
C                 CALL BIPARTITE(NATOMS,QSORT,SCRATCH,PERM,DUMMY,DIST2,WORSTRAD)
                  IF (DIST2.LT.TOLD) THEN
                     FPGRP='CNV'
                     HPTGRP=2*IHIGH
                  ENDIF
400            CONTINUE
            ENDIF
         ENDIF
      ENDIF
C
C  *** END OF IDEGEN=1 BLOCK. *** 
C
      IF (IDEGEN.EQ.2) THEN
         IF (IPRNT.GE.3) WRITE(MYUNIT,*) ' IN CUBIC LOOP '
         IF (IPRNT.GE.3) WRITE(MYUNIT,410)
410      FORMAT(' THE MOLECULE BELONGS TO A POINT GROUP WITH DOUBLY', 
     1          ' AND TRIPLY DEGENERATE REPRESENTATIONS.')
C
C   NOW WE KNOW THAT THE POINT GROUP IS EITHER T, TD, O, OH, T, I, TH
C   OR IH.  FOR THESE GROUPS, HOWEVER, THE INERTIA TENSOR
C   IS ROTATIONALLY INVARIANT; THEREFORE DIFFERENT (AND SIGNIFICANTLY
C   MORE COMPLICATED) METHODS NEED TO BE USED.  THIS ONE SEEMS TO
C   BE PARTICULARLY EFFICIENT.
C
C   CHECK FOR INVERSION SYMMETRY. THIS WILL TELL US A GREAT DEAL.
C   (IF INVERSION CENTER PRESENT, THEN GROUP IS EITHER OH, TH OR IH.
C
         DO I=1,NATOMS*3
            SCRATCH(I)=-NEWQ(I)
         ENDDO
C        CALL COMPARE2(SCRATCH,QSORT,NORD,ISINV,TOLD,NATOMS,IPRNT)
C        CALL MINPERM(NATOMS,QSORT,SCRATCH,0.0D0,0.0D0,0.0D0,.FALSE.,PERM,DUMMY,DUMMYSINV,WORSTRAD)
         CALL TESTSYMOP(NATOMS,QSORT,SCRATCH,PERM,TOLD,DUMMYSINV,WORSTRAD)
C        CALL BIPARTITE(NATOMS,QSORT,SCRATCH,PERM,DUMMY,DUMMYSINV,WORSTRAD)
C
C   LOCATE ALL ORBITS (GROUPS OF EQUIVALENT ATOMS AT DISTANCE R) -
C   DO THIS BY GENERATING AND THEN SORTING THE C.O.M-OUTER ATOM
C   DISTANCE MATRIX (MASS-WEIGHTED). USE NORD2 TO KEEP TRACK OF
C   WHICH ATOMS ARE IN WHICH ORBIT.
C
         CALL ZERO(SCRATCH,3*NATOMS*3)
         DO J=1,NATOMS
            NORD2(J)=J
            IBOT=3*J-2
            SCRATCH(J)=SQRT(MYDOT(NEWQ(IBOT),NEWQ(IBOT),3))
         ENDDO
         CALL PIKSR2(NATOMS,SCRATCH,NORD2)
         IF (IPRNT.GE.3) WRITE(MYUNIT,440) (SCRATCH(J),J=1,NATOMS)
C
C   NOW COUNT NUMBER OF ORBITS; PLACE PERTINENT INFO (DISTANCES) IN TOP
C   END OF SCRATCH ARRAY AND USE TOP END OF NORD2 TO HOLD NUMBER
C   OF CENTERS/ORBIT.  THIS BOOKKEEPING FACILITATES THINGS DOWN
C   THE ROAD.  
C
         NORBIT=1
         IORBIT=1
         DO J=2,NATOMS+1
C           IF (ABS(SCRATCH(J)-SCRATCH(J-1)).LT.TOLD) IORBIT=IORBIT+1
C           IF (ABS(SCRATCH(J)-SCRATCH(J-1)).GT.TOLD) THEN
            IF (ABS(SCRATCH(J)-SCRATCH(J-1)).LT.TOLO) IORBIT=IORBIT+1
            IF (ABS(SCRATCH(J)-SCRATCH(J-1)).GT.TOLO) THEN
               NORD2(NATOMS+NORBIT)=IORBIT
               SCRATCH(6*NATOMS+NORBIT)=ABS(SCRATCH(J-1))
               IF (J.LE.NATOMS) THEN
                  NORBIT=NORBIT+1
                  IORBIT=1
               ENDIF
            ENDIF
         ENDDO

         IF (IPRNT.GE.130) THEN
            WRITE(MYUNIT,*)' SCRATCH VECTOR '
            WRITE(MYUNIT,*)(SCRATCH(IK),IK=1,NATOMS)
            WRITE(MYUNIT,*)' ORBIT DISTANCES: '
            WRITE(MYUNIT,*)(SCRATCH(6*NATOMS+IK),IK=1,NORBIT)
         ENDIF
C
C   DEBUG PRINT TO MAKE SURE WE'VE GOT ALL THE ORBITS CORRECT.
C
         IF (IPRNT.GE.3) THEN
            WRITE(MYUNIT,470) NORBIT
470         FORMAT(' NUMBER OF DISTINCT ORBITS: ',I3,/,' SUMMARY OF ORBIT SIZES:')
            DO I=1,NORBIT
               WRITE(MYUNIT,480) I, NORD2(NATOMS+I)
480            FORMAT(2I3)
            ENDDO
         ENDIF
C
C  THE PROGRAMMER THINKS THAT ONLY THE SMALLEST ORBIT OF NON-UNIT
C  MAGNITUDE WILL BE NEEDED TO IDENTIFY THE POINT GROUP UNIQUELY
C  BY THE FOLLOWING METHOD.  FIND THIS ORBIT AND PROCEED.  
C
C  SCRATCH(6*NATOMS+ORBIT NUMBER) WILL BE THE RADIUS OF THE ORBIT.
C
         MINORB=NATOMS
         NUMB=0
         IREF=0
         DO 500 I=1,NORBIT
            NUMB=NORD2(NATOMS+I)+NUMB
            IF (SCRATCH(6*NATOMS+I).LT.1.0D-8) GOTO 500
            IF ((NORD2(NATOMS+I).GT.1).AND.(NORD2(NATOMS+I).LE.MINORB)) THEN
               MINORB=NORD2(NATOMS+I)
               ORDIS=SCRATCH(6*NATOMS+I)
               IREF=1+NUMB-NORD2(NATOMS+I)
            ENDIF
500      CONTINUE
         IF (IREF.EQ.0) THEN
            IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,*) 'ACCIDENTAL DEGENERACY DETECTED'
            TOLE=TOLE/10.0D0
            IF (TOLE.GT.1.0D-7) THEN
               GOTO 651
            ELSE
               IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,*) ' THE FULL MOLECULAR POINT GROUP IS UNDETERMINED'
               WRITE(GPSTRING,653) ' THE FULL MOLECULAR POINT GROUP IS UNDETERMINED'
               GOTO 652
            ENDIF
         ENDIF
         IF (IPRNT.GE.13) WRITE(MYUNIT,510) MINORB,NORD2(IREF)
510      FORMAT(' THE SMALLEST NON-UNIT ORBIT CONTAINS ',I3,' MEMBERS.',/,
     1    ' ATOM NUMBER ',I3,' BELONGS TO THIS ORBIT AND WILL BE',
     2    ' USED AS A REFERENCE.')
         IF (IPRNT.GE.13) WRITE(MYUNIT,520)(NORD2(IREF+J),J=1,MINORB-1)  
520      FORMAT(' OTHER MEMBERS OF THIS ORBIT ARE: ',100I4)
         CALL ZERO(SCRATCH,9*NATOMS)
         IBOT=3*NORD2(IREF)-2
C
C   REORDER NORD2(IREF+J), J=1,MINORB-1 IN TERMS OF DECREASING DISTANCE FROM
C   ATOM NORD2(IREF). COORDINATES ARE IN NEWQ. HOPEFULLY, THIS REORDERING
C   WILL MEAN THAT GENERATORS ARE NOT MISSED IN THE LOOP BELOW.
C
C   APPEARS TO MAKE NO DIFFERENCE AT ALL.
C
CC        PRINT*,'REORDERING'
CC        PRINT*,'NORD2: ',NORD2(IREF+1:IREF+MINORB-1)
C         DO J=1,MINORB-1
C            DISTANCE(J)=(NEWQ(3*(NORD2(IREF)-1)+1)-NEWQ(3*(NORD2(IREF+J)-1)+1))**2
C     &                 +(NEWQ(3*(NORD2(IREF)-1)+2)-NEWQ(3*(NORD2(IREF+J)-1)+2))**2
C     &                 +(NEWQ(3*(NORD2(IREF)-1)+3)-NEWQ(3*(NORD2(IREF+J)-1)+3))**2
CC           PRINT '(A,2I5,G20.10)','J,NORD2(IREF+J),DISTANCE=',J,NORD2(IREF+J),DISTANCE(J)
C            DISTLOOP: DO J1=1,J-1 
C               IF (DISTANCE(J).GT.DISTANCE(J1)) THEN
C                  DUMMY=DISTANCE(J)
C                  IDUMMY=NORD2(IREF+J)
C                  DO J2=J,J1+1,-1
CC                    PRINT*,'CHANGING NORD2 ',IREF+J2,' TO NORD2 ',IREF+J2-1
C                     NORD2(IREF+J2)=NORD2(IREF+J2-1)
C                     DISTANCE(J2)=DISTANCE(J2-1)
C                  ENDDO
CC                 PRINT*,'CHANGING NORD2 ',IREF+J1,' TO ',IDUMMY
C                  NORD2(IREF+J1)=IDUMMY
C                  DISTANCE(J1)=DUMMY
C                  EXIT DISTLOOP
C               ENDIF
C            ENDDO DISTLOOP
C         ENDDO
CC        PRINT*,'NEWORDER'
CC        PRINT*,'NORD2: ',NORD2(IREF+1:IREF+MINORB-1)
CC        CALL FLUSH(6)

C
C   NOW USE REFERENCE ATOM FROM ORBIT AND LOOP OVER ALL OTHER ATOMS,
C   THIS IS THE SECOND LOOP (610) BELOW.
C   OUTER LOOP BELOW (620) IS FULLY EXECUTED TWO TIMES
C   IF AND ONLY IF THE FPGRP IS OF THE T OR I VARIETY AND NO
C   C2 AXIS APPROPRIATE FOR ORIENTATION FUDGING WAS FOUND AFTER
C   IDENTIFICATION OF THE GROUP.
C   FIRST ROTATE MOLECULE SO THAT THE INTERATOMIC DISTANCE VECTOR
C   IS PARALLEL TO THE Z-AXIS, WITH BISECTOR ALONG X-AXIS.
C   STRUCTURE NOW IN SCRATCH(1). HERE ONE HAS TO ALLOW FOR THE
C   POSSIBILITY THAT ATOMS I AND J ARE 180 DEGREES APART; IF THIS
C   IS THE CASE, LOOP THROUGH OTHER ATOMS IN ORBIT AND FIND ONE
C   THAT IS PERPENDICULAR (THERE HAS TO BE ONE FOR CUBIC GROUPS)
C   AND USE THIS VECTOR AS THE "BISECTOR". IF
C   IT ISN'T DONE THIS WAY, THE ORIENTATION FUDGING GETS FUDGED UP.
C
         DO 620 ICOUNT=1,2
            IF (IPRNT.GE.3) WRITE(MYUNIT,*)' PASS ',ICOUNT,' THROUGH ROT. FINDER '
            DO 610 J=1,MINORB-1
               IF (IDONE.EQ.1) GOTO 610
               IF (IPRNT.GE.3) WRITE(MYUNIT,*)' ATOMS ',NORD2(IREF),NORD2(IREF+J)
               IBOT2=3*NORD2(IREF+J)-2
               CALL XVEC(NEWQ(IBOT),NEWQ(IBOT2),SCRATCH(1),0)
               DIST=SQRT(MYDOT(SCRATCH(1),SCRATCH(1),3))
C              CALL VADD(SCRATCH(1),NEWQ(IBOT),NEWQ(IBOT2),3*NATOMS,1) ! BUG DJW
               CALL VADD(SCRATCH(1),NEWQ(IBOT),NEWQ(IBOT2),3,1)
C
C   DEAL WITH THE LINEAR PROBLEM RIGHT NOW.
C
               BILEN=MYDOT(SCRATCH(1),SCRATCH(1),3)
C              IF (BILEN.LT.TOLD) THEN
               IF (BILEN.LT.TOLO) THEN
                  ISET=0
                  DO 530 LOOK=1,MINORB-1
                     IF (ISET.EQ.1) GOTO 530
                     INDEX=3*NORD2(IREF+LOOK)-2
                     TEST=MYDOT(NEWQ(IBOT),NEWQ(INDEX),3)
                     IF (IPRNT.GT.13) WRITE(MYUNIT,*) TEST
C                    IF (ABS(TEST).LT.TOLD) THEN
                     IF (ABS(TEST).LT.TOLO) THEN
                        CALL ZERO(SCRATCH,3)
                        CALL VADD(SCRATCH(1),SCRATCH(1),NEWQ(INDEX),3,1) 
                        ISET=1
                     ENDIF
530               CONTINUE
               ENDIF
               CALL SIAZ(SCRATCH(1),RM,1)
               CALL ZERO(SCRATCH,3*NATOMS*3)
               CALL MATMULV(SCRATCH(3*NATOMS+1),NEWQ,RM,NATOMS,3,3)
C
C   NOW YOU HAVE BISECTOR ALONG X. ROTATE ABOUT X TO BRING THE TWO
C   ATOMS INTO POSITION PARALLEL TO Z.
C
               DIP=SQRT(MYDOT(SCRATCH(3*NATOMS+IBOT+1),SCRATCH(3*NATOMS+IBOT+1),2))
               ARGU=SCRATCH(3*NATOMS+IBOT+2)/DIP
               IF (ABS(ARGU).GT.1.D0) ARGU=ARGU/ABS(ARGU)
               ANGLE2=-ACOS(ARGU)/DTOR
               IF (SCRATCH(3*NATOMS+IBOT+1).GT.0.D0)ANGLE2=-ANGLE2
               CALL ROTM(1,ANGLE2,1,RM)
               CALL MATMULV(SCRATCH,SCRATCH(3*NATOMS+1),RM,NATOMS,3,3)
C
C   NOW FIND NEW VECTOR WHICH BISECTS THE TWO ATOMS IN QUESTION -
C   IT HAD BEST BE X! (UNLESS LINEAR CASE WHERE TATB IS FORCED.)
C
               CALL VADD(TATB,SCRATCH(IBOT),SCRATCH(IBOT2),3,1)
               IF (ISET.EQ.1) THEN
                  CALL ZERO(TATB,3)
                  TATB(1)=1.D0
               ENDIF
C
C 1. TEST IF THE TWO ATOMS ARE CONNECTED BY SYMMETRY AXES, LOOPING
C    OVER POSSIBILITIES (2,3,4 AND 5). T1 CONTAINS THE MATRIX TRANSFORMATION
C    REQUIRED UP TO THIS POINT FROM NEWQ, AND T1T IS ITS TRANSPOSE (INVERSE).
C
C    THE ALGORITHM USES THE FACT THAT IF THERE IS AN N-FOLD AXIS THEN THE
C    EDGE CHOSEN FOR THE REFERENCE ATOMS IS PART OF AN N-SIDED POLYGON. ANGMAG
C    IS THE ANGLE BETWEEN THE VECTOR THROUGH THE CENTRE OF THIS HYPOTHETICAL
C    POLYGON AND THE VECTOR WHICH BISECTS THE REFERENCE EDGE. SIAZ IS THEN
C    CALLED TO DETERMINE THE ROTATION NEEDED TO MAP THE HYPOTHETICAL N-FOLD
C    AXIS ONTO THE Z AXIS. THIS TRANSFORMATION IS SAVED IN T2, AND ITS
C    TRANSPOSE IN T2T.
C
               DO 600 IAXORD=5,2,-1
                  ICLIP=0
                  ANGIAX=360.D0/(1.0D0*IAXORD)
                  ANGMG=ANGMAG(ORDIS,DIST,IAXORD,IERR)
                  IF (IERR.EQ.1) GOTO 600
570               CALL ROTM(3,ANGMG,1,RM)
                  CALL MATMULV(SCRATCH(3*NATOMS+4),TATB,RM,1,3,3)
                  CALL SIAZ(SCRATCH(3*NATOMS+4),RM,3)
                  CALL ZERO(SCRATCH(3*NATOMS+1),NATOMS*3*2)
                  CALL MATMULV(SCRATCH(3*NATOMS+1),SCRATCH,RM,NATOMS,3,3)  
C                 CALL SORTXYZ(SCRATCH(3*NATOMS+1),QSORT,NORD,TOLD,NATOMS)
                  QSORT(1:3*NATOMS)=SCRATCH(3*NATOMS+1:6*NATOMS)
                  CALL ROTM(3,ANGIAX,1,RM)
                  CALL MATMULV(SCRATCH(6*NATOMS+1),SCRATCH(3*NATOMS+1),RM,NATOMS,3,3)
C                 CALL COMPARE2(SCRATCH(6*NATOMS+1),QSORT,NORD,IIAX,TOLD,NATOMS,IPRNT) 
C                 CALL MINPERM(NATOMS,QSORT,SCRATCH(6*NATOMS+1),0.0D0,0.0D0,0.0D0,.FALSE.,PERM,DUMMY,DIST2,WORSTRAD)
                  CALL TESTSYMOP(NATOMS,QSORT,SCRATCH(6*NATOMS+1),PERM,TOLD,DIST2,WORSTRAD)
C                 CALL BIPARTITE(NATOMS,QSORT,SCRATCH(6*NATOMS+1),PERM,DUMMY,DIST2,WORSTRAD)
C
C   POINT GROUP DETERMINATION HAPPENS HERE, AS WELL AS ORIENTATION
C   FUDGING.
C
C                 IF (IIAX.EQ.0) THEN
                  IF (IPRNT.GT.4) WRITE(MYUNIT,'(A,I5,3F12.3)') 'IAXORD,DUMMY,DIST2,TOLD=',IAXORD,DUMMY,DIST2,TOLD
C                 PRINT*,'QSORT:'
C                 PRINT '(3G20.10)',QSORT(1:3*NATOMS)
C                 PRINT*,'SCRATCH(6*NATOMS+1):'
C                 PRINT '(3G20.10)',SCRATCH(6*NATOMS+1:9*NATOMS)
                  IF (DIST2.LT.TOLD) THEN
                     IF (IGEN.LT.100) THEN
C
C   MAKE THE TRANSFORMATION MATRIX CORRESPONDING TO THE REFERENCE STATE IN QREF
C
!                       IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,*) 'CALLING REORIENT B'
                        CALL REORIENT(NATOMS,SCRATCH(6*NATOMS+1),QREF,RMAT)
                        CALL MYMATMUL(DUM,RM,RMAT,3,3,3)
                        CALL MATMULV(DUM2,DUM,RMAT,3,3,3)
                        DO J2=1,IGEN
                           CALL CMPMAT(GENMAT,100,J2,DUM2,NEW,MATDIFF)
                           IF (.NOT.NEW) GOTO 20
                        ENDDO
                        IGEN=IGEN+1
                        GENMAT(IGEN,1:3,1:3)=DUM2(1:3,1:3)
!                       IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,*) 'HERE B IGEN=',IGEN,' NEW GENMAT:'
!                       IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,'(9F12.4)') GENMAT(IGEN,1:3,1:3)
20                      CONTINUE
                     ENDIF
                     IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,580) IAXORD
580                  FORMAT(' AXIS OF ORDER ',I1,' IDENTIFIED.')
                     IF (IAXORD.EQ.5) THEN
                        FPGRP='I  '
                        HPTGRP=60
C                       IF (ISINV.EQ.0) FPGRP='I H'
                        IF (DUMMYSINV.LT.TOLD) THEN
                           FPGRP='I H'
                           HPTGRP=120
                        ENDIF
                     ENDIF
                     IF (IAXORD.EQ.4) THEN
                        FPGRP='O  '
                        HPTGRP=24
C                       IF (ISINV.EQ.0) FPGRP='O H'
                        IF (DUMMYSINV.LT.TOLD) THEN
                           FPGRP='O H'
                           HPTGRP=48
                        ENDIF
C
C   ORIENTATION IS GOOD. PUT STRUCTURE INTO NEWQ AND LEAVE LOOP.
C
                        CALL ZERO(NEWQ,3*NATOMS)
                        CALL VADD(NEWQ,NEWQ,SCRATCH(3*NATOMS+1),3*NATOMS,1)
C                       CALL SORTXYZ(NEWQ,QSORT,NORD,TOLD,NATOMS)
                        QSORT(1:3*NATOMS)=NEWQ(1:3*NATOMS)
                        IDONE=1
                        GOTO 610
                     ENDIF
                     IF (IAXORD.EQ.3) THEN
                        IF (FPGRP.EQ.'   ') THEN
                           FPGRP='T  '
                           HPTGRP=12
C                          IF (ISINV.EQ.0) FPGRP='T H'
                           IF (DUMMYSINV.LT.TOLD) THEN
                              FPGRP='T H'
                              HPTGRP=24
                           ENDIF
                        ENDIF
                     ENDIF
                     IF (IAXORD.EQ.2) THEN
                        IF (FPGRP.NE.'   '.AND.FPGRP.NE.'O H'.AND.FPGRP.NE.'O  ') THEN
C
C   HAVE A C2 AXIS FOR I OR T GROUP. THIS IS VERY GOOD. TD AND T CAN BE DIFFERENTIATED
C   HERE.  DO THIS NOW IF APPROPRIATE. THEN PUT STRUCTURE INTO NEWQ AND
C   LEAVE LOOP IF IT IS AN I GROUP. OTHERWISE, NEED TO CONTINUE THROUGH
C   (SINCE THERE MIGHT BE A HIGHER ORDER AXIS DOWN THE LINE.) IF
C   PASS TWO, HOWEVER, THEN EXIT FOR T SINCE IT MUST BE THE CORRECT GROUP.
C
                           IF (ICOUNT.EQ.2.AND.(FPGRP.EQ.'T  '.OR.FPGRP.EQ.'T H')) THEN
                              DO 590 JPLANE=1,3
                                 CALL REFLECT(SCRATCH(3*NATOMS+1),SCRATCH,NATOMS,JPLANE)
C                                CALL COMPARE2(SCRATCH,QSORT,NORD,ICOMPQ,TOLD,NATOMS,IPRNT)
C                                CALL MINPERM(NATOMS,QSORT,SCRATCH,0.0D0,0.0D0,0.0D0,.FALSE.,PERM,DUMMY,DIST2,WORSTRAD)
                                 CALL TESTSYMOP(NATOMS,QSORT,SCRATCH,PERM,TOLD,DIST2,WORSTRAD)
C                                CALL BIPARTITE(NATOMS,QSORT,SCRATCH,PERM,DUMMY,DIST2,WORSTRAD)
C                                IF (ICOMPQ.EQ.0.AND.ISINV.NE.0) FPGRP='T D'
                                 IF ((DIST2.LT.TOLD).AND.(DUMMYSINV.GT.TOLD)) THEN
                                    FPGRP='T D'
                                    HPTGRP=24
                                 ENDIF
                                 CALL ZERO(NEWQ,3*NATOMS)
                                 CALL VADD(NEWQ,NEWQ,SCRATCH(3*NATOMS+1),3*NATOMS,1)
C                                CALL SORTXYZ(NEWQ,QSORT,NORD,TOLD,NATOMS)
                                 QSORT(1:3*NATOMS)=NEWQ(1:3*NATOMS)
                                 IDONE=1
                                 GOTO 610
590                           CONTINUE
                           ENDIF
                        ENDIF
                     ENDIF
                  ENDIF
                  ANGMG=-ANGMG
                  IF (ICLIP.EQ.0) THEN
                     ICLIP=1
                     GOTO 570
                  ENDIF
600            CONTINUE
610         CONTINUE
620      CONTINUE
         IF (FPGRP.EQ.'   ') THEN
            IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,*) 'ACCIDENTAL DEGENERACY DETECTED'
            TOLE=TOLE/10.0D0
            IF (TOLE.GT.1.0D-7) THEN
               GOTO 651
            ELSE
               IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,*) ' THE FULL MOLECULAR POINT GROUP IS UNDETERMINED'
               WRITE(GPSTRING,653) ' THE FULL MOLECULAR POINT GROUP IS UNDETERMINED'
               GOTO 652
            ENDIF
         ENDIF
      ENDIF
C
C   *** THIS IS THE END OF THE IDEGEN=2 BLOCK. ***
C
C   CHECK SYMMETRY OPERATIONS BELONGING TO ABELIAN GROUPS
C
630   ANG=180.D0
      IREF=0
      DO I=3,1,-1
         CALL REFLECT(NEWQ,SCRATCH,NATOMS,I)
C        CALL COMPARE2(SCRATCH,QSORT,NORD,ICOMP,TOLD,NATOMS,IPRNT)
C        IF (ICOMP.EQ.0) THEN
C        CALL MINPERM(NATOMS,QSORT,SCRATCH,0.0D0,0.0D0,0.0D0,.FALSE.,PERM,DUMMY,DIST2,WORSTRAD)
         CALL TESTSYMOP(NATOMS,QSORT,SCRATCH,PERM,TOLD,DIST2,WORSTRAD)
C        CALL BIPARTITE(NATOMS,QSORT,SCRATCH,PERM,DUMMY,DIST2,WORSTRAD)
         IF (DIST2.LT.TOLD) THEN
            IF (IGEN.LT.100) THEN
               DO J1=1,3
                  DO J2=1,3
                     RM(J2,J1)=0.0D0
                  ENDDO
                  RM(J1,J1)=1.0D0
                  IF (J1.EQ.I) RM(J1,J1)=-1.0D0
               ENDDO
C
C   MAKE THE TRANSFORMATION MATRIX CORRESPONDING TO THE REFERENCE STATE IN QREF 
C
!              IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,*) 'CALLING REORIENT C'
               CALL REORIENT(NATOMS,SCRATCH,QREF,RMAT) 
               CALL MYMATMUL(DUM,RM,RMAT,3,3,3)
               CALL MATMULV(DUM2,DUM,RMAT,3,3,3)
               DO J2=1,IGEN
                  CALL CMPMAT(GENMAT,100,J2,DUM2,NEW,MATDIFF)
                  IF (.NOT.NEW) GOTO 30
               ENDDO
               IGEN=IGEN+1
               GENMAT(IGEN,1:3,1:3)=DUM2(1:3,1:3)
!              IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,*) 'HERE C IGEN=',IGEN,' NEW GENMAT:'
!              IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,'(9F12.4)') GENMAT(IGEN,1:3,1:3)
30             CONTINUE
            ENDIF
            IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,640) I
640         FORMAT(' REFLECTION IN PLANE ',I2,' IS A VALID SYMMETRY OPERATION.')
            IREF=IBTOR(IREF,2**I/2)
         ENDIF
         CALL ROTM(I,ANG,1,RM)
         CALL MATMULV(SCRATCH,NEWQ,RM,NATOMS,3,3)
C        CALL COMPARE2(SCRATCH,QSORT,NORD,ICOMP,TOLD,NATOMS,IPRNT)
C        IF (ICOMP.EQ.0) THEN
C        CALL MINPERM(NATOMS,QSORT,SCRATCH,0.0D0,0.0D0,0.0D0,.FALSE.,PERM,DUMMY,DIST2,WORSTRAD)
         CALL TESTSYMOP(NATOMS,QSORT,SCRATCH,PERM,TOLD,DIST2,WORSTRAD)
C        CALL BIPARTITE(NATOMS,QSORT,SCRATCH,PERM,DUMMY,DIST2,WORSTRAD)
         IF (DIST2.LT.TOLD) THEN
            IF (IGEN.LT.100) THEN
C
C   MAKE THE TRANSFORMATION MATRIX CORRESPONDING TO THE REFERENCE STATE IN QREF 
C
!              IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,*) 'CALLING REORIENT D'
               CALL REORIENT(NATOMS,SCRATCH,QREF,RMAT) 
               CALL MYMATMUL(DUM,RM,RMAT,3,3,3)
               CALL MATMULV(DUM2,DUM,RMAT,3,3,3)
               DO J2=1,IGEN
                  CALL CMPMAT(GENMAT,100,J2,DUM2,NEW,MATDIFF)
                  IF (.NOT.NEW) GOTO 40
               ENDDO
               IGEN=IGEN+1
               GENMAT(IGEN,1:3,1:3)=DUM2(1:3,1:3)
!              IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,*) 'HERE D IGEN=',IGEN,' NEW GENMAT:'
!              IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,'(9F12.4)') GENMAT(IGEN,1:3,1:3)
40             CONTINUE
            ENDIF
            IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,650) I
650         FORMAT(' C2 ROTATION ABOUT ',I2,' IS A VALID SYMMETRY OPERATION ')
            IROT=IBTOR(IROT,2**I/2)
         ENDIF
      ENDDO
      DO I=1,NATOMS*3
C        SCRATCH(I)=-NEWQ(I)
         SCRATCH(I)=-QSORT(I)
      ENDDO
C     CALL COMPARE2(SCRATCH,QSORT,NORD,ICOMP,TOLD,NATOMS,IPRNT)
C     IF (ICOMP.EQ.0) THEN
C     CALL MINPERM(NATOMS,QSORT,SCRATCH,0.0D0,0.0D0,0.0D0,.FALSE.,PERM,DUMMY,DIST2,WORSTRAD)
      CALL TESTSYMOP(NATOMS,QSORT,SCRATCH,PERM,TOLD,DIST2,WORSTRAD)
C     CALL BIPARTITE(NATOMS,QSORT,SCRATCH,PERM,DUMMY,DIST2,WORSTRAD)
C
C  EVEN DND DO NOT HAVE THE INVERSION OPERATION - BUG FIXED DJW 13/5/92
C
C     PRINT '(A,I6,G20.10)','ISAXIS,DIST2=',ISAXIS,DIST2
C     IF ((ISAXIS.EQ.1).OR.(DIST2.LT.TOLD)) THEN
      IF (DIST2.LT.TOLD) THEN
         IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,680)
680      FORMAT(' THE MOLECULE POSSESSES AN INVERSION CENTER. ')
         IF (IGEN.LT.100) THEN
            DO J1=1,3
               DO J2=1,3
                  RM(J2,J1)=0.0D0
               ENDDO
               RM(J1,J1)=-1.0D0
            ENDDO
C
C   MAKE THE TRANSFORMATION MATRIX CORRESPONDING TO THE REFERENCE STATE IN QREF 
C
!           IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,*) 'CALLING REORIENT E'
            CALL REORIENT(NATOMS,SCRATCH,QREF,RMAT) 
            CALL MYMATMUL(DUM,RM,RMAT,3,3,3)
            CALL MATMULV(DUM2,DUM,RMAT,3,3,3)
            DO J2=1,IGEN
               CALL CMPMAT(GENMAT,100,J2,DUM2,NEW,MATDIFF)
               IF (.NOT.NEW) GOTO 60
            ENDDO
            IGEN=IGEN+1
            GENMAT(IGEN,1:3,1:3)=DUM2(1:3,1:3)
!           IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,*) 'HERE E IGEN=',IGEN,' NEW GENMAT:'
!           IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,'(9F12.4)') GENMAT(IGEN,1:3,1:3)
60          CONTINUE
         ENDIF
         IF (ILINEAR.EQ.1) THEN
            FPGRP='DXH'
            HPTGRP=2
         ENDIF
         IF (FPGRP.EQ.'   '.AND.IDGRP.EQ.1) THEN
            FPGRP='DND'
            HPTGRP=4*IHIGH
         ENDIF
         IINV=1
      ELSE
         IF (ILINEAR.EQ.1) THEN
            FPGRP='CXV'
            HPTGRP=1
         ENDIF
         IF (FPGRP.EQ.'   '.AND.IDGRP.EQ.1) THEN
            FPGRP='DN '
            HPTGRP=2*IHIGH
         ENDIF
      ENDIF
C
C   DETERMINE LARGEST ABELIAN SUBGROUP OF MOLECULE
C
      IF (IROT.EQ.0.AND.IREF.EQ.0.AND.IINV.EQ.0) PGRP='C1 '
      IF (IROT.EQ.0.AND.IREF.EQ.0.AND.IINV.EQ.1) PGRP='C I'
      IF (IROT.EQ.0.AND.IREF.NE.0.AND.IINV.EQ.0) PGRP='C S'
      IF (IROT.NE.0.AND.IREF.EQ.0.AND.IINV.EQ.0) PGRP='C2 '
      IF (IROT.NE.0.AND.IREF.NE.0.AND.IINV.EQ.0) PGRP='C2V'
      IF (IROT.NE.0.AND.IREF.NE.0.AND.IINV.EQ.1) PGRP='C2H'
      IF (IROT.EQ.7.AND.IREF.EQ.0.AND.IINV.EQ.0) PGRP='D2 '
      IF (IROT.EQ.7.AND.IREF.EQ.7.AND.IINV.EQ.1) PGRP='D2H'
      IF (IPRNT.GE.4) WRITE(MYUNIT,690) IREF,IROT,IINV
690   FORMAT ('SYMMETRY BITS: ',3(1X,I3))
C
C   PUT NEWQ INTO Q.
C
      BPGRP=PGRP
      CALL ZERO(SCRATCH,NATOMS*3)
      CALL VADD(Q,NEWQ,SCRATCH(1),NATOMS*3,1)

      IF (PGRP.EQ.'C2H') PGRP='C S'

      IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,770)
770   FORMAT(80('*'))
C
C  THIS SHOULD COPE WITH ANYTHING WE ARE LIKELY TO COME UP AGAINST,
C  UNTIL MARK TRIES A RING WITH 100 ATOMS!
C
      IF (IHIGH.EQ.0) THEN 
         WRITE(JNKSTR,'(A3)') FPGRP(1:3)
      ELSE IF (IHIGH.LT.10) THEN
         WRITE(JNKSTR,'(A1,I1,A1)') FPGRP(1:1),IHIGH,FPGRP(3:3)
      ELSE
         WRITE(JNKSTR,'(A1,I2,A1)') FPGRP(1:1),IHIGH,FPGRP(3:3)
      ENDIF
      FPGRP=JNKSTR
      IF (IDEGEN.GT.0) THEN
         IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,750) FPGRP
750      FORMAT(' THE FULL MOLECULAR POINT GROUP IS ',A4,'.')
         WRITE(GPSTRING,750) FPGRP
      ENDIF
      IF (IDEGEN.EQ.0) THEN
         IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,750) STRING(BPGRP,IHIGH)
         FPGRP= STRING(BPGRP,IHIGH)
         WRITE(GPSTRING,750) STRING(BPGRP,IHIGH)
      ENDIF
      IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,790) BPGRP
790   FORMAT(' THE LARGEST ABELIAN SUBGROUP OF THE FULL MOLECULAR POINT GROUP IS ',A4,'.')
      IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,760) TOLD, TOLE, TOLO
760   FORMAT(' DISTANCE TOLERANCE=',F12.5,' INERTIA TOLERANCE=',F12.5,' ORBIT TOLERANCE=',F12.5)  
      IF (DEBUG.OR.(IPRNT.GE.3)) WRITE(MYUNIT,770)

652   CONTINUE

      RETURN
      END

      SUBROUTINE SIAZ(VEC,ROT,IAXIS)
      IMPLICIT NONE
      INTEGER IAXIS,J1,J2
      DOUBLE PRECISION VEC(3),ROT(3,3),RM(3,3),XTEMP(3,3),ANG1,ARG2,DISP,AZIM,ARG1,DIS,MYDOT
C
C     WRITE (6,*) 'SIAZ: VEC, IAXIS'
C     WRITE (6,'(A,3F12.6,I3)') 'SIAZ: ',VEC, IAXIS
C 
C DETERMINE LENGTH OF VECTOR.
C
      ROT(1,1)=1.0D0
      ROT(2,2)=1.0D0
      ROT(3,3)=1.0D0
      ROT(1,2)=0.0D0
      ROT(1,3)=0.0D0
      ROT(2,1)=0.0D0
      ROT(2,3)=0.0D0
      ROT(3,1)=0.0D0
      ROT(3,2)=0.0D0
      DIS=SQRT(MYDOT(VEC,VEC,3))
      IF (ABS(DIS).LT.1.0D-10) RETURN
C     WRITE (6,'(A,F12.6)') 'SIAZ: DIS', DIS
C
C   RETURNS ROTATION MATRIX NEEDED TO PLACE VECTOR
C   VEC ALONG THE X (IAXIS=1), Y (IAXIS=2) OR Z (IAXIS=3)
C   AXIS.  TAIL OF VECTOR IMPLICITLY ASSUMED TO BE AT 
C   THE ORIGIN.
C
      IF(IAXIS.EQ.3)THEN
        ARG1=VEC(3)/DIS
        IF(ABS(ARG1).GT.1.D0)ARG1=ARG1/ABS(ARG1)
        AZIM=-1.D0*ACOS(ARG1)
        DISP=SQRT(MYDOT(VEC,VEC,2))
        IF (ABS(DISP).LT.1.0D-10) RETURN
        ARG2=VEC(1)/DISP
        IF(ABS(ARG2).GT.1.D0)ARG2=ARG2/ABS(ARG2)
        ANG1=ACOS(ARG2)
        ANG1=SIGN(ANG1,-1.D0*VEC(2))
        CALL ROTM(3,ANG1,0,RM)
        CALL ROTM(2,AZIM,0,ROT)
        CALL MATMUL(XTEMP,RM,ROT,3,3,3,3,3,3)
        DO 17 J1=1,3
           DO 18 J2=1,3
              ROT(J2,J1)=XTEMP(J2,J1)
18         CONTINUE
17      CONTINUE
      ELSEIF(IAXIS.EQ.1)THEN
        ARG1=VEC(1)/DIS
        IF(ABS(ARG1).GT.1.D0)ARG1=ARG1/ABS(ARG1)
        AZIM=-1.D0*ACOS(ARG1)
        DISP=SQRT(MYDOT(VEC(2),VEC(2),2))
        IF (ABS(DISP).LT.1.0D-10) RETURN
        ARG2=VEC(2)/DISP
        IF(ABS(ARG2).GT.1.D0)ARG2=ARG2/ABS(ARG2)
        ANG1=ACOS(ARG2)
        ANG1=SIGN(ANG1,-1.D0*VEC(3))
        CALL ROTM(1,ANG1,0,RM)
        CALL ROTM(3,AZIM,0,ROT)
        CALL MATMUL(XTEMP,RM,ROT,3,3,3,3,3,3)
        DO 27 J1=1,3
           DO 28 J2=1,3
              ROT(J2,J1)=XTEMP(J2,J1)
28         CONTINUE
27      CONTINUE
      ELSEIF(IAXIS.EQ.2)THEN
        ARG1=VEC(2)/DIS
        IF(ABS(ARG1).GT.1.D0)ARG1=ARG1/ABS(ARG1)
        AZIM=-1.D0*ACOS(ARG1)
        DISP=SQRT(DIS**2-VEC(2)**2)
        IF (ABS(DISP).LT.1.0D-10) RETURN
        ARG2=VEC(3)/DISP
        IF(ABS(ARG2).GT.1.D0)ARG2=ARG2/ABS(ARG2)
        ANG1=ACOS(ARG2)
        ANG1=SIGN(ANG1,-1.D0*VEC(1))
        CALL ROTM(2,ANG1,0,RM)
        CALL ROTM(1,AZIM,0,ROT)
        CALL MATMUL(XTEMP,RM,ROT,3,3,3,3,3,3)
        DO 37 J1=1,3
           DO 38 J2=1,3
              ROT(J2,J1)=XTEMP(J2,J1)
38         CONTINUE
37      CONTINUE
       ENDIF
       RETURN
       END

      SUBROUTINE REFLECT(A,SCRATCH,NATOM,IPLANE)
C
C REFLECTS POINTS IN PLANE
C
      IMPLICIT NONE
      INTEGER NATOM,IPLANE,IX,I,J
      DOUBLE PRECISION A(3,NATOM),SCRATCH(3,NATOM)
 
      IX(I,J)=MIN(I,J)/MAX(I,J)
 
      DO I=1,NATOM
         DO J=1,3
            SCRATCH(J,I)=A(J,I)*(1.0D0-2.D0*IX(IPLANE,J))
         ENDDO
      ENDDO
      RETURN
      END
C
      SUBROUTINE ZERO(A,NA)
      IMPLICIT NONE
      INTEGER NA,I
      DOUBLE PRECISION A(NA)

      DO 10 I=1,NA
10    A(I)=0.D0
      CONTINUE
      RETURN
      END

      SUBROUTINE VADD(A,B,C,N,IP)
      USE COMMONS,ONLY : MYUNIT
      IMPLICIT NONE
      INTEGER N,IP,I
      DOUBLE PRECISION A(N),B(N),C(N)

      DO 10 I=1,N
10    A(I)=B(I)+C(I)*IP
      RETURN
      END         
      SUBROUTINE COMPARE2(VECS,VECR,NORD,ICOMP,TOL,NATOMS,IPRNT)
C
C     ROBUST EQUIVALENCE CHECK - DO WELL DEFINED SORT ON COORDINATE
C     MATRIX AND COMPARE ELEMENT BY ELEMENT.  SHOULD BE FOOLPROOF.
C
C     VECS     COORDINATE VECTOR TO BE CHECKED (MODIFIED)
C     VECR     SORTED REFERENCE COORDINATE VECTOR (INPUT ONLY)
C     NORD     ???
C     ICOMP    NUMBER OF COORDINATES OUTSIDE OF TOL (OUTPUT ONLY)
C     TOL      TOLERANCE FOR COMPARISON OF COORDS (INPUT ONLY)
C
      IMPLICIT NONE
      INTEGER I,JAP,NATOMS,ICOMP,IPRNT
      DOUBLE PRECISION VECS(3*NATOMS),VECR(3*NATOMS),Z,TOL
      INTEGER NORD(2*NATOMS+1)
 
      ICOMP=0
      CALL SORTXYZ(VECS,VECS,NORD(NATOMS+1),TOL,NATOMS)
      IF (IPRNT.GT.10) THEN
         WRITE(6,*)'SORTED REFERENCE VECTOR (INPUT)'
         WRITE(6,'(3G20.10)')(VECR(JAP),JAP=1,3*NATOMS)
         WRITE(6,*)'SORTED TRANSFORMED VECTOR'
         WRITE(6,'(3G20.10)')(VECS(JAP),JAP=1,3*NATOMS)
      ENDIF
      DO I=1,NATOMS*3
         Z=ABS(VECR(I)-VECS(I))
         IF (Z.GT.TOL) THEN
C           PRINT '(A,I5,4G20.10)','I,VECR,VECS,DIFF,TOL=',I,VECR(I),VECS(I),Z,TOL
            ICOMP=ICOMP+1
            RETURN
         ENDIF
      ENDDO
      RETURN
      END

      SUBROUTINE SORTXYZ(XX,Y,NORD,TOL,NATOMS)
C
C     SORTS VECTOR OF NUCLEAR COORDINATES - TO CHECK FOR EQUIVALENCE
C     OF TWO ORIENTATIONS - NEEDS Q VECTOR 
C
      IMPLICIT NONE
      INTEGER NATOMS,J,JK,I,NORD(NATOMS*2+1),J1
      DOUBLE PRECISION X(3*NATOMS),XX(3*NATOMS),Y(3*NATOMS),TOL
C
C     SORT ON THE X - IF TWO X'S ARE EQUIVALENT, SORT ON Y AND SO ON.
C     IF THE COORDINATE < THE TOLERANCE WE SHOULD IGNORE IT! HOWEVER,
C     IF THE TOLERANCE IS SLOPPY THAT CAN LEAD TO THE SORTING IGNORING
C     GENUINE SMALL DIFFERENCES BETWEEN COORDINATES. SIGH. 
C
C     PRINT '(A)','IN SORTXYZ'
      DO 10 I=1,3*NATOMS
         X(I)=XX(I)
10    CONTINUE
      JK=1
40    J=1
C     PRINT*,'TOL=',TOL
      OUTER: DO I=1,3*NATOMS-2,3
C        DO J1=1,NATOMS
C           PRINT '(A,I5,3G20.10)','J1,COORDS: ',J1,X(3*(J1-1)+1),X(3*(J1-1)+2),X(3*(J1-1)+3)
C        ENDDO
C        PRINT '(A,2I5,3G20.10)','I,J,X(I),X(J),DIFF    =',I,J,X(I),X(J),X(I)-X(J)
         IF (X(I)-X(J).GT.TOL) THEN
            J=I          ! J IS SET TO THE INDEX OF THE X COORDINATE OF THE
            CYCLE OUTER  ! THE CORRESPONDING COORDINATE IS SET TO -99999.D0, SO IT WON;T BE USED AGAIN.
         ENDIF
         IF (ABS(X(I)-X(J)).LT.TOL) THEN
C           PRINT '(A,2I5,3G20.10)','I,J,X(I+1),X(J+1),DIFF=',I,J,X(I+1),X(J+1),X(I+1)-X(J+1)
            IF (X(I+1)-X(J+1).GT.TOL) J=I
            IF (ABS(X(I+1)-X(J+1)).LT.TOL) THEN
               IF (X(I+2)-X(J+2).GT.TOL) J=I
            ENDIF
         ENDIF
      ENDDO OUTER
      DO 60 I=0,2
         Y(3*JK-2+I)=X(J+I)
60       X(J)=-99999.D0
      NORD(JK)=(J+2)/3
      JK=JK+1
      IF (JK.EQ.NATOMS+1) GOTO 70
      GOTO 40
70    CONTINUE
      RETURN
      END

      SUBROUTINE ROTM(IDIR,ANG,IX,RT)
C
C     FORMS THREE DIMENSIONAL ROTATION MATRIX (IX=0 IF ANG IN RADS,
C     IX=1 IF DEG,  ADD 10 TO IX TO GET TRANSPOSE)
C
      IMPLICIT NONE
      INTEGER IDIR,IX,I,J,IBTAND,IEO
      DOUBLE PRECISION RT(3,3),ANG,ATOR,TANG,INK

      IBTAND(I,J)=IAND(I,J)
      IEO(I)=2*IBTAND(I,1)-1
C
      ATOR=ACOS(-1.D0)/180.D0
      INK=IX/10
      CALL ZERO(RT,9)
      TANG=ANG
      IF(IX.EQ.1)TANG=ANG*ATOR
      DO 10 J=1,3
         RT(J,J)=DCOS(TANG)
 10      RT(IDIR,J)=IBTAND(IDIR,J)/MAX(IDIR,J)
      DO 20 I=1,3
         DO 20 J=1,I
            IF(I.NE.J.AND.I.NE.IDIR.AND.J.NE.IDIR)THEN
               RT(I,J)=IEO(I*J)*DSIN(TANG)
               RT(J,I)=-RT(I,J)
            ENDIF
 20   CONTINUE
      IF(INK.NE.0)CALL MTRANS(RT,RT,3,3,3,3)
      RETURN
      END

      SUBROUTINE INERTIA(Q,IT,NATOMS)
C
C BUILD INERTIA TENSOR
C
      IMPLICIT NONE
      INTEGER I,J,IND,K,NATOMS
      DOUBLE PRECISION IT(3,3),SCRATCH(9),Q(3*NATOMS),FDIST
 
      IND(I,J)=3*(I-1)+J
 
      CALL ZERO(SCRATCH,9)
      CALL ZERO(IT,9)
      DO I=1,3
         DO K=1,NATOMS
            IT(I,I)=(FDIST(Q(3*K-2),SCRATCH(1))**2-Q(3*(K-1)+I)**2)+IT(I,I)
         ENDDO
      ENDDO
      DO I=1,3
         DO J=1,3
            IF (I.NE.J) THEN
               DO K=1,NATOMS
                  IT(I,J)=-(Q(IND(K,I))*Q(IND(K,J)))+IT(I,J)
               ENDDO
            ENDIF
         ENDDO
      ENDDO
      RETURN
      END
    
      SUBROUTINE XVEC(A,B,V,IX)
C
C CALCULATES THE VECTOR V BETWEEN CARTESIAN POINTS A AND B
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION A(3),B(3),V(3)
      DO 10 I=1,3
 10   V(I)=B(I)-A(I)
      IF(IX.EQ.1)CALL NORMAL(V,3)
      RETURN
      END 

      SUBROUTINE MYCROSS(A,B,C,IX)
C
C CALCULATES THE (OPTIONALLY) NORMALIZED VECTOR CROSS PRODUCT C=A X B
C
      IMPLICIT NONE
      INTEGER IX
      DOUBLE PRECISION A(3),B(3),C(3)

      C(3)=A(1)*B(2)-B(1)*A(2)
      C(2)=-A(1)*B(3)+A(3)*B(1)
      C(1)=A(2)*B(3)-A(3)*B(2)
      IF(IX.EQ.1)CALL NORMAL(C,3)
      RETURN
      END
C
C********************************************************************
C
      SUBROUTINE EIG(A,B,L,N,N1)
C
C DIAGONALIZATION BY THE JACOBI METHOD.
C A - MATRIX TO BE DIAGONALIZED (EIGENVALUES RETURNED IN DIAGONAL
C        ELEMENTS OF A).  IF YOU WANT TO SAVE A, YOU MUST DO THIS BEFORE
C        CALLING EIG.  SET N TO THE SAME VALUE AS L.
C B - EIGENVECTORS
C L - DIMENSION OF A AND B
C N - SIZE OF SUBMATRIX USED
C N1 - A FLAG INDICATING WHETHER THE EIGENVECTORS AND
C      EIGENVALUES ARE TO BE REORDERED.
C
CSW      1
      IMPLICIT NONE
      INTEGER L,N,N1,JJ,IOFF,I,IM1,MU,MM,JI,II,J
      DOUBLE PRECISION A(L,L),B(L,L),W2,W1,C,T,ALP,ALN,D,SUM,S,DIFF,R,Q,P,TOL2,TOL,ZER,ONE
      DATA ZER/0.D00/,ONE/1.D00/
CSW     2
      TOL=1.D-14
      TOL2=1.D-10
      JJ=0
      IOFF=0
      B(1,1)=ONE
      IF(N.EQ.1) RETURN
      DO 20 I=2,N
      IM1=I-1
      DO 10 J=1,IM1
      B(I,J)=ZER
10    B(J,I)=ZER
20    B(I,I)=ONE
C
C FIRST SEE IF MATRIX IS ALREADY DIAGONAL- IF SO THEN
C  TAKE APPROPRIATE ACTION
C
      DO 30 II=1,L
      DO 30 JI=II+1,L
      IF(ABS(A(II,JI)).GT.TOL2)IOFF=IOFF+1
30    IF(ABS(A(JI,II)).GT.TOL2)IOFF=IOFF+1
      IF(IOFF.EQ.0)THEN
          CALL ZERO(B,L*L)
          DO 40 I=1,L
          B(I,I)=ONE
40        CONTINUE
      ELSE
50    P=ZER
      DO 70 I=2,N
      IM1=I-1
      DO 60 J=1,IM1
      Q=A(I,J)
      IF(P.GE. ABS(Q)) GO TO 60
      P= ABS(Q)
      II=I
      JJ=J
60    CONTINUE
70    CONTINUE
      IF(P.EQ.0.) GO TO 140
      P=A(II,II)
      Q=A(II,JJ)
      R=A(JJ,JJ)
      DIFF=0.5D0*(P-R)
      IF( ABS(DIFF).LT. ABS(Q)) GO TO 80
      IF( ABS(Q/DIFF).GT.TOL) GO TO 80
      A(II,JJ)=ZER
      A(JJ,II)=ZER
      GO TO 50
80    S=SQRT(0.250D0*(P-R)**2+Q**2)
      SUM=0.5D0*(P+R)
      D=R*P-Q**2
      IF(SUM.GT.ZER) GO TO 90
      ALN=SUM-S
      ALP=D/ALN
      GO TO 100
90    ALP=SUM+S
      ALN=D/ALP
100   IF(DIFF.GT.ZER) GO TO 110
      T=Q/(DIFF-S)
      A(II,II)=ALN
      A(JJ,JJ)=ALP
      GO TO 120
110   T=Q/(DIFF+S)
      A(II,II)=ALP
      A(JJ,JJ)=ALN
120   C=1.0D0/SQRT(1.0D0+T**2)
      S=T*C
      A(II,JJ)=ZER
      A(JJ,II)=ZER
      DO 130 I=1,N
      P=B(I,II)
      Q=B(I,JJ)
      B(I,II)=C*P+S*Q
      B(I,JJ)=C*Q-S*P
      IF(I.EQ.II.OR.I.EQ.JJ) GO TO 130
      P=A(I,II)
      Q=A(I,JJ)
      R=C*P+S*Q
       A(I,II)=R
      A(II,I)=R
      R=Q*C-P*S
      A(I,JJ)=R
      A(JJ,I)=R
130   CONTINUE
      GO TO 50
      ENDIF
140   IF(N1.EQ.1) RETURN
      MM=N-1
      DO 170 I=1,MM
      II=I+1
      DO 170 J=II,N
      IF(A(I,I)-A(J,J)) 170,150,150
150   W1=A(I,I)
      A(I,I)=A(J,J)
      A(J,J)=W1
      DO 160 MU=1,N
      W2=B(MU,I)
      B(MU,I)=B(MU,J)
160   B(MU,J)=W2
170   CONTINUE
      RETURN
      END

C
C  RETURNS A = B C
C
      SUBROUTINE MATMUL(A,B,C,NA,NB,NC,NTA,NTB,NTC)
      IMPLICIT NONE
      INTEGER NA,NB,NC,NTA,NTB,NTC,I,J1,J,K
      DOUBLE PRECISION B(NA,NB),C(NB,NC),A(NA,NC),T1(NTB),Z

      DO 10 I=1,NTA
         DO 15 J1=1,NTB
            T1(J1)=B(I,J1)
15       CONTINUE
         DO 30 J=1,NTC
            Z=0.0D0
            DO 20 K=1,NTB
               Z=Z+T1(K)*C(K,J)
20          CONTINUE
            A(I,J)=Z
30       CONTINUE
10    CONTINUE
      RETURN
      END     
      
C
C               T
C  RETURNS A = C B
C
      SUBROUTINE MATMULV(A,B,C,NA,NB,NC)
      IMPLICIT NONE
      INTEGER NA, NB, NC, I, K, J
      DOUBLE PRECISION A(NC,NA),B(NB,NA),C(NB,NC),Z

      DO I=1,NA
         DO K=1,NC
            Z=0.D0
            DO J=1,NB
               Z=Z+B(J,I)*C(J,K)
            ENDDO
            A(K,I)=Z
         ENDDO
      ENDDO
      RETURN 
      END
C                
C  RETURNS A = B C
C
      SUBROUTINE MYMATMUL(A,B,C,NA,NB,NC)
      IMPLICIT NONE
      INTEGER NA, NB, NC, I, K, J
      DOUBLE PRECISION A(NC,NA),B(NB,NA),C(NB,NC),Z

      DO I=1,NA
         DO K=1,NC
            Z=0.D0
            DO J=1,NB
               Z=Z+B(K,J)*C(J,I)
            ENDDO
            A(K,I)=Z
         ENDDO
      ENDDO
      RETURN 
      END

      DOUBLE PRECISION FUNCTION MYDOT(A,B,N)
      IMPLICIT NONE
      INTEGER N, I
      DOUBLE PRECISION A(N),B(N)

      MYDOT=0.D0
      DO 10 I=1,N
10    MYDOT=MYDOT+A(I)*B(I)
      RETURN
      END

        SUBROUTINE PIKSR2(N,ARR,NLIST)
C
C SIMPLE SORTER MODIFIED TO MAKE JFS HAPPY.
C
        IMPLICIT NONE
        INTEGER N, J, I
        DOUBLE PRECISION ARR(N), A
        INTEGER NLIST(N), NLST

        DO 12 J=2,N
        A=ARR(J)
        NLST=NLIST(J)
        DO 11 I=J-1,1,-1
         IF(ARR(I).LE.A)GOTO 10
         ARR(I+1)=ARR(I)
         NLIST(I+1)=NLIST(I)
   11   CONTINUE
        I=0
   10   ARR(I+1)=A
        NLIST(I+1)=NLST
   12   CONTINUE
        RETURN
        END

        DOUBLE PRECISION FUNCTION ANGMAG(ORBIT,D,IORDER,IRETURN)
        IMPLICIT NONE
        INTEGER IRETURN, IORDER
        DOUBLE PRECISION DTOR, ORDER, A1, X, TOP, BOT, ORBIT, D

        IRETURN=0
        ANGMAG=0.D0
        DTOR=ACOS(-1.D0)/180.D0
        ORDER=1.0D0*(IORDER)
        A1=180.D0/ORDER
        IF(ABS(A1-90.D0).LT.1.D-3)THEN
          ANGMAG=0.D0
           RETURN
        ENDIF
        X=ORBIT**2-0.25D0*D**2/DSIN(DTOR*A1)**2
        TOP=D/DTAN(DTOR*A1)
        IF (X.LT.-1.D-12) THEN
C
C THE ROTATION IS IMPOSSIBLE
C
           IRETURN=1
           RETURN
        ENDIF
        IF(ABS(X).LT.1.D-6)THEN
          ANGMAG=90.D0
        ELSE
           BOT=2.D0*SQRT(X)
          ANGMAG=DATAN(TOP/BOT)/DTOR
        ENDIF
        RETURN
        END         

      CHARACTER(LEN=4) FUNCTION STRING(NAME,IORD)
      CHARACTER(LEN=4) NAME, ITOA*3
      IF (NAME(2:2) .EQ. 'N') THEN
         STRING(1:1)=NAME(1:1)
         STRING(2: )=ITOA(IORD, 0)
         STRING(LNBLNK(STRING)+1:)=NAME(3:3)
      ELSE
         STRING=NAME
      ENDIF
      RETURN
      END

      SUBROUTINE MTRANS(A,AT,NR,NC,NTR,NTC)
      IMPLICIT NONE
      INTEGER NR,NC,NTR,NTC, I, J
      DOUBLE PRECISION A(NR,NC),AT(NC,NR)
      DO 10 I=1,NTR
      DO 10 J=1,NTC
10    AT(J,I)=A(I,J)
      RETURN
      END
      DOUBLE PRECISION FUNCTION FDIST(A,B)
C
C CALCULATES THE DISTANCE BETWEEN TWO POINTS IN CARTESIAN SPACE
C
      IMPLICIT NONE
      DOUBLE PRECISION A(3),B(3),Z
      INTEGER I

      Z=0.D0
      DO 10 I=1,3
10    Z=Z+(A(I)-B(I))**2
      FDIST=SQRT(Z)
      RETURN
      END

      SUBROUTINE NORMAL(X,N)
C
C NORMALIZES VECTOR X
C
      DOUBLE PRECISION X(N), Q, P
      INTEGER N, I
      Q=0.D0
      DO 10 I=1,N
10    Q=Q+X(I)**2
      P=SQRT(Q)
      IF(P.LT.1D-14)THEN
      WRITE(6,*)' NULL VECTOR RETURNED FROM NORMAL'
      RETURN
      ENDIF
      DO 11 I=1,N
11    X(I)=X(I)/P    
      RETURN
      END 
       CHARACTER*(*) FUNCTION ITOA(NR, FRCPLS)
C:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
C PURPOSE:      CONVERT NR TO A LEFT JUSTIFIED STRING
C
C ARGUMENTS:
C     NR       NUMBER TO BE CONVERTED (INPUT ONLY)
C     FRCPLS   FORCE LEADING '+' IF NR POSITIVE (INPUT ONLY)
C
C LIMITATIONS:
C     MAY RETURN WITH INCOMPLETE CONVERSION IF LENGTH OF ITOA IS TOO
C     SHORT.  PUTS '*' IN LAST POSITION OF ITOA TO INDICATE OVERLOW.
C:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
C $HEADER: ITOA.F,V 4.0 89/03/14 01:15:45 BERNHOLD EXP $
C
C $LOG:	ITOA.F,V $
C REVISION 4.0  89/03/14  01:15:45  BERNHOLD
C BASELINE FOR SUN & VAX PRIOR TO PORTING EVERYWHERE
C 
C REVISION 3.0  89/01/29  23:10:22  BERNHOLD
C FIRST WORKING RELEASE FOR VAX
C 
C REVISION 2.1  89/01/02  20:36:12  BERNHOLD
C TO KEEP CONSISTENT WITH .U FILE JUST CHECKED IN.
C 
C     REVISION 1.1  88/12/07  13:38:51  BERNHOLD
C     INITIAL REVISION
C     
C
C SYSTEM:       STANDARD FORTRAN 77
C
C COPYRIGHT 1988 DAVID E. BERNHOLDT
C:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
      INTEGER NR, FRCPLS, NRABS
      INTEGER I, J
C
C     CLEAR OUT THE STRING
C
      DO 10 I=1, LEN(ITOA)
         ITOA=' '
 10   CONTINUE
C
C     START COUNTING POSITION IN STRING
C
      J=1
      NRABS=ABS (NR)
C
C     PUT IN SIGN AS APPROPRIATE
C
      IF (NR .LT. 0) THEN
         ITOA(J:J)='-'
         J=J + 1
      ENDIF
      IF (FRCPLS .NE. 0 .AND. NR .GT. 0) THEN
         ITOA(J:J)='+'
         J=J + 1
      ENDIF
C
C     CHECK IF WE ARE ABOUT TO OVERFLOW THE STRING
C
      IF (J .GT. LEN(ITOA)) THEN
         ITOA(J-1:J-1)='*'
         RETURN
      ENDIF
C
C     LOOP OVER NR OF DIGITS IN NUMBER
C
      NDIG=INT( LOG10( FLOAT(NRABS)) ) + 1
      DO 100 I=NDIG, 1, -1
         N=MOD ( ( NRABS / (10**(I-1) ) ), 10)
         ITOA(J:J)=CHAR(N + 48)
         J=J + 1
C
C        CHECK FOR OVERFLOW OF THE STRING, BUT IF THIS IS LAST DIGIT
C        THEN ITS OKAY.
C
         IF (J .GT. LEN(ITOA) .AND. I .GT. 1) THEN
            ITOA(J-1:J-1)='*'
            RETURN
         ENDIF
 100  CONTINUE
C
      RETURN
      END
       INTEGER FUNCTION LNBLNK (STRING)
C:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
C PURPOSE:   RETURNS THE POSITION OF THE LAST NON-BLANK CHARACTER
C
C ARGUMENTS: STRING   CHARACTER STRING (INPUT ONLY)
C
C REMARKS:   ALL FORTRAN 77 CHARACTER VARIABLES ARE BLANK PADDED ON THE
C            RIGHT.  THE INTRINSIC FUNCTION LEN RETURNS THE DIMENSION
C            OF THE CHARACTER OBJECT, NOT THE LENGTH OF THE CONTENTS.
C            
C:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
C $HEADER: LNBLNK.F,V 1.1 88/01/11 22:08:15 BERNHOLD EXP $
C
C    REVISION 0.0  87/07/24  BERNHOLDT (VAX)
C $LOG:	LNBLNK.F,V $
C    REVISION 1.1  88/01/11  22:08:15  BERNHOLD
C    INITIAL REVISION
C    
C
C SYSTEM:     STANDARD FORTRAN 77
C
C COPYRIGHT 1987 DAVID E. BERNHOLDT
C:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
       INTEGER I
       CHARACTER*(*) STRING
       CHARACTER(LEN=1) BLANK
       PARAMETER (BLANK = ' ')
C
C      START AT THE END AND WORK BACKWARDS
C
       DO 100 I = LEN(STRING), 1, -1
C         LOOK FOR FIRST NON-WHITESPACE CHARACTER
          IF (STRING(I:I) .NE. BLANK) THEN
             LNBLNK = I
             RETURN
          ENDIF
  100  CONTINUE
C
C      IF WE GET THIS FAR, THE STRING IS EMPTY
       LNBLNK = 0
       RETURN
       END

      SUBROUTINE CMPMAT(XMAT1,D1,N1,XMAT2,TEST,MATDIFF)
      IMPLICIT NONE
      LOGICAL TEST
      INTEGER D1, N1, J1, J2
      DOUBLE PRECISION XMAT1(D1,3,3), XMAT2(3,3), MATDIFF

      TEST=.FALSE.
      DO J2=1,3
         DO J1=1,3
            IF (ABS(XMAT1(N1,J2,J1)-XMAT2(J2,J1)).GT.MATDIFF) THEN
               TEST=.TRUE.
               RETURN
            ENDIF
         ENDDO
      ENDDO

      RETURN
      END
C
C  TEST FOR WHETHER WE HAVE A SYMMETRY OPERATION OR NOT BY CHECKING
C  THAT EACH ATOM IN VECTOR Q1 HAS A PARTNER WITHIN DISTANCE TOLD IN
C  VECTOR Q2.
C       Q1(I) <--> Q2(PERM(I))
C
      SUBROUTINE TESTSYMOP(NATOMS,Q1,Q2,PERM,TOLD,DIST2,WORSTRAD)
      USE COMMONS,ONLY : MYUNIT,DEBUG
      IMPLICIT NONE
      INTEGER NATOMS
      DOUBLE PRECISION Q1(3*NATOMS), Q2(3*NATOMS), TOLD, DIST2, DIST, TOLDSQ, WORSTRAD, DMIN
      LOGICAL PARTNER, ASSIGNED(NATOMS)
      INTEGER J1, J2, PERM(NATOMS), JWORST
   
      TOLDSQ=TOLD*TOLD
      PERM(1:NATOMS)=0
      ASSIGNED(1:NATOMS)=.FALSE.
      DIST2=-1.0D0
      DO J1=1,NATOMS
         PARTNER=.FALSE.
         DMIN=1.0D100
         INNERLOOP: DO J2=1,NATOMS
            IF (ASSIGNED(J2)) CYCLE INNERLOOP
            DIST=(Q1(3*(J1-1)+1)-Q2(3*(J2-1)+1))**2+ 
     &           (Q1(3*(J1-1)+2)-Q2(3*(J2-1)+2))**2+ 
     &           (Q1(3*(J1-1)+3)-Q2(3*(J2-1)+3))**2
C           IF (DEBUG) WRITE(MYUNIT,'(A,2I6,G20.10)') 'TESTSYMOP> J1,J2,DIST=',J1,J2,DIST
            IF (DIST.LT.TOLDSQ) THEN
               PARTNER=.TRUE.
               PERM(J1)=J2
               ASSIGNED(J2)=.TRUE.
               IF (DIST.GT.DIST2) THEN
                  DIST2=DIST
                  JWORST=J1
               ENDIF
C              WRITE(MYUNIT,'(A,2I6,G20.10)') 'TESTSYMOP> MATCH J1,J2,DIST=',J1,J2,DIST
               EXIT INNERLOOP
            ENDIF
         ENDDO INNERLOOP
         IF (.NOT.PARTNER) THEN
!           IF (DEBUG) WRITE(MYUNIT,'(A,I6)') 'TESTSYMOP> NO PARTNER FOR ATOM ',J1
            DIST2=1.0D3
            RETURN
         ENDIF
      ENDDO 
!
!  IF WE REACH HERE THEN THE TWO STRUCTURES ARE PERMUTATIONAL ISOMERS TO WITHIN THE TOLERANCE TOLD.
!
      DIST2=SQRT(DIST2)
      WORSTRAD=SQRT(Q1(3*(JWORST-1)+1)**2+Q1(3*(JWORST-1)+2)**2+Q1(3*(JWORST-1)+3)**2)

      RETURN
      END
