C   GMIN: A PROGRAM FOR FINDING GLOBAL MINIMA
C   COPYRIGHT (C) 1999-2006 DAVID J. WALES
C   THIS FILE IS PART OF GMIN.
C
C   GMIN IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C   (AT YOUR OPTION) ANY LATER VERSION.
C
C   GMIN IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
C   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
C   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
C   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
C
C
C  ENERGY AND GRADIENT FOR HARMONIC OSCILLATOR OF DIMENSION 3*NATOMS
C
      SUBROUTINE QDTEST(X,V,EQD,GTEST)
      USE COMMONS, ONLY : NATOMS
      IMPLICIT NONE
      LOGICAL GTEST
      INTEGER J1
      DOUBLE PRECISION X(3*NATOMS), V(3*NATOMS), EQD
      LOGICAL EVAP, EVAPREJECT
      COMMON /EV/ EVAP, EVAPREJECT
  
      EVAP=.FALSE.
      EVAPREJECT=.FALSE.

      EQD=0.0D0
!
! SHIFT ONE MINIMUM FROM THE ORIGIN.
!
!     EQD=EQD+0.5D0*(X(1)-1.0D0)**2
!     V(1)=X(1)-1.0D0

      DO J1=1,3*NATOMS
         EQD=EQD+0.5D0*X(J1)**2
         V(J1)=X(J1)
!
! TRY IT WITH FORCE CONSTANT = J1
!
!        EQD=EQD+0.5D0*J1*X(J1)**2
!        V(J1)=J1*X(J1)
!
! ALL DEGREES OF FREEDOM SHIFTED FROM THE ORIGIN
!
!        EQD=EQD+0.5D0*J1*(X(J1)-1.0D0/J1)**2
!        V(J1)=J1*(X(J1)-1.0D0/J1)
      ENDDO

      RETURN
      END
