!  GMIN: A PROGRAM FOR FINDING GLOBAL MINIMA
!  COPYRIGHT (C) 1999-2006 DAVID J. WALES
!  THIS FILE IS PART OF GMIN.
!
!  GMIN IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!  IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!  THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!  (AT YOUR OPTION) ANY LATER VERSION.
!
!  GMIN IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!  BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!  MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!  GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!
!  YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!  ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!  FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!
!
! TETHER PERFORMS A CONVENTIONAL WL RUN FOR SELECTED LOCAL MINIMA THAT HAVE THE HIGHEST BINIMPORTANCEINDEX
! WITH THE ADDITIONAL CONSTRAINT THAT THE DISTANCE BETWEEN THE GIVEN MINIMUM AND ANY STRUCTURE THAT IS ACCEPTED DURING THE 
! SAMPLE IS LESS THAN THE AVERAGE DISTANCE D_JMIN FOR THE BS BIN TO WHICH THE MINIMUM BELONGS. 
! IT IS POSSIBLE TO SPLIT THE ENERGY RANGE INTO A NUMBER OF WINDOWS 'HWINDOWS'. SETTING 'HWINDOWS' TO 1 
! USING A KEYWORD PRODUCES A WL
! RUN OF THE WHOLE RANGE. (TETYANA BOGDAN)
! T.V. BOGDAN, D.J. WALES AND F. CALVO, J. CHEM. PHYS., 124, 044102 (2006).
!
!---======================================---
      SUBROUTINE TETHEREDWL
      USE COMMONS, ONLY: NATOMS,  COORDS, HISTMIN, HISTMAX, HBINS, HISTFAC, TARGETWL, &
                         & HISTFACMUL, DEBUG, EQUIL , PERIODIC, TWOD, BINSTRUCTURES, SAVENTH, HDISTCONSTRAINT, &
                         & DUMPEVERYNTHQUENCH, HWINDOWS, LHBINS, SAMPLEDBINS, LNHARMFREQ, CHRMMT, FIXEDENDMOVET
      USE TETHERFUNC

      IMPLICIT NONE
    

      INTEGER NSTEPS, I, J, K, VISITS(HBINS), VISITSTOTAL(HBINS), LBFGS_ITERATIONS, BININDEXOLD, BININDEXNEW, NQUENCHES, &
              & NQUENCHESSINCEFLAT, NQUENCHESSUCCESS, NWL, NQUENCHESSINCELASTUPDATE, ESCAPEDFROMTETHER, NQUENCHESMAX, &
              & LVISITS(LHBINS,HWINDOWS), LVISITSTOTAL(LHBINS,HWINDOWS), NDUMMY, CONVERGED, &
              & LVISITS_S(SAMPLEDBINS,HWINDOWS), LVISITSTOTAL_S(SAMPLEDBINS,HWINDOWS) 
      REAL(8) POTEL, WEIGHT(HBINS) , DISTANCE(HBINS), DUMMY, CURRENTPOINTENERGY, CURRENTPOINTCOORDINATES(3*NATOMS, 1), &
              & DISTANCEOLD, LNMODFAC, PERTURBEDCOORDINATES(3*NATOMS, 1), PERTURBEDCOORDINATESSAVE(3*NATOMS, 1), LNRATIO, &
              & HARVEST, BINLABEL(HBINS), NORM, MINDISTANCE(HBINS), MINDISTANCEOLD, GRAD(3*NATOMS), &
              & SOURCEMINIMUM(3*NATOMS, 1), HISTINT, &
              & CHECKTETHER, LNHARVEST, OLDENERGY, DELTA, &
              &  WINDOW_COORDS(3*NATOMS, HWINDOWS), & 
              & LBINLABEL(HBINS/HWINDOWS,HWINDOWS ), L_LNWEIGHT(LHBINS,HWINDOWS), TOT_LNWEIGHT(HBINS-HWINDOWS+1), SCALEFAC, &
              & LBINLABEL_S(SAMPLEDBINS,HWINDOWS ), L_LNWEIGHT_S(SAMPLEDBINS,HWINDOWS), EXTRAPOLFAC, SHIFTFAC, BOTTOMWEIGHT

!!!! THINK ABOUT THIS:, TOT_LNWEIGHT_S(HBINS-HWINDOWS+1)


      REAL(8) LNWEIGHT(HBINS)

      CHARACTER (LEN =256)  HISTFILENAME
      CHARACTER (LEN= 10)  ISTR

      LOGICAL YESNO, FLAT, EVAP, EVAPREJECT, ACCEPTMOVE, ALLFOUND

      COMMON /MYPOT/ POTEL

      COMMON /EV/ EVAP, EVAPREJECT

      HISTINT=(HISTMAX-HISTMIN)/HBINS
      WINDOW_COORDS=0.0D0
      PRINT *, 'TETHERING IN ', HWINDOWS, ' WINDOWS STARTED. SAMPLING FOR COORDINATES:'
      PRINT *, 'ENERGY RANGE SPLIT AS FOLLOWS: WINDOW, EMIN, EMAX:'
      DO J=1, HWINDOWS
          PRINT *, J ! THIS IS A ROUGH NOT EXACT ESTIMATION OF ENERGY RANGES
          PRINT *, HISTMIN+(J-1)*HISTINT*(HBINS/HWINDOWS), HISTMIN+(J)*HISTINT*(HBINS/HWINDOWS)
      ENDDO


      CURRENTPOINTCOORDINATES(:,1)=COORDS(:,1)
      PERTURBEDCOORDINATESSAVE(:,1)=COORDS(:,1)
      PRINT *, 'CALCULATING INITIAL ENERGY'
      CALL QUENCH(.FALSE.,1,LBFGS_ITERATIONS,DUMMY,NDUMMY,CONVERGED,CURRENTPOINTCOORDINATES)
      CURRENTPOINTENERGY=POTEL
      SOURCEMINIMUM(:,1)=COORDS(:,1) 
      PRINT *, 'INITIAL ENERGY', CURRENTPOINTENERGY

      DO
        ALLFOUND=.FALSE.
        DO J=1, HWINDOWS
           DO I=1, 3*NATOMS
             IF (WINDOW_COORDS(I,J).NE.0.0D0) THEN
               ALLFOUND=.TRUE.
             ELSE
               ALLFOUND=.FALSE.
             ENDIF
            ENDDO
        ENDDO
        
        IF (ALLFOUND) EXIT       
    
        CURRENTPOINTCOORDINATES(:,1)=COORDS(:,1)
        
        DO I=1, 3*NATOMS
             PERTURBEDCOORDINATESSAVE(I,1)=COORDS(I,1)
        ENDDO

        IF (CHRMMT) THEN
            IF (FIXEDENDMOVET) THEN ! ACTUALLY BASIN-HOPPING-TYPE STEP IN INTERNAL COORDINATES
!!!                 CALL FIXEDENDMOVE(1)
!!!                 PERTURBEDCOORDINATES(:3*NATOMS,1) = COORDS(:3*NATOMS,1)
!!!             ELSE
               COORDS(:3*NATOMS,1) = PERTURBEDCOORDINATESSAVE(:3*NATOMS,1)
               CALL FILLICT(1)
               CALL TAKESTEPCH(1)
               ! NEW GEOMETRY IS NOW IN COORDS
               PERTURBEDCOORDINATES(:3*NATOMS,1) = COORDS(:3*NATOMS,1)
            ELSE ! TRY TAKING STEP IN CARTESIANS
               PERTURBEDCOORDINATES = PERTURBGEOMETRY(PERTURBEDCOORDINATESSAVE)
               COORDS(1:3*NATOMS,1) = PERTURBEDCOORDINATES(1:3*NATOMS,1)
               CALL FILLICT(1)
            ENDIF
        ELSE
           PERTURBEDCOORDINATES=PERTURBGEOMETRY(PERTURBEDCOORDINATESSAVE)
           COORDS(:,1)=PERTURBEDCOORDINATES(:,1)
        ENDIF

   
        !CALL PRINTXYZ(NATOMS,COORDS(:,1)) 
        CALL POTENTIAL(COORDS, GRAD, POTEL, .TRUE., .FALSE.)
        CURRENTPOINTENERGY=POTEL
        !CALL PRINTXYZ(NATOMS,COORDS(:,1)) 
        CURRENTPOINTCOORDINATES(:,1)=COORDS(:,1)

        DO J=1, HWINDOWS

           IF ((CURRENTPOINTENERGY.GT.HISTMIN+(LHBINS-SAMPLEDBINS)*HISTINT+(J-1)*HISTINT*(HBINS/HWINDOWS)).AND. &
              & (CURRENTPOINTENERGY.LT.HISTMIN+(LHBINS-SAMPLEDBINS)*HISTINT+(J)*HISTINT*(HBINS/HWINDOWS)).AND. & 
              & WINDOW_COORDS(1,J).EQ.0.D0) THEN

              DO I=1, 3*NATOMS
                 WINDOW_COORDS(I,J)=CURRENTPOINTCOORDINATES(I,1)
              ENDDO
              PRINT *, WINDOW_COORDS(1,J), 'E', CURRENTPOINTENERGY
            ENDIF
        ENDDO

      ENDDO

      PRINT *, 'SEEDING WINDOWS WITH STARTING GEOMETRIES SUCCESSFUL'

      PRINT *, 'SAMPLING REQUESTED FOR ', SAMPLEDBINS, 'BINS'


    
!     GLOBAL DENSITY OF STATES VARIABLES: 
      LNWEIGHT=0.0D0
      VISITS=0
      VISITSTOTAL=0
      DO I=1, HBINS
         BINLABEL(I)=HISTMIN + HISTINT*(I-0.5)
      ENDDO

      

!****  VARIABLES FOR EACH WINDOW:

      PRINT *, 'EACH WINDOW IS DIVIDED INTO ', LHBINS, 'BINS.'

      
   DO J=1, HWINDOWS

      PRINT *, 'WL SIMULATION FOR WINDOW' , J


      DO I=1, LHBINS
         LVISITS(I,J)=0
         LVISITSTOTAL(I,J)=0       
      ENDDO

      DO I=1, SAMPLEDBINS 
         LVISITS_S(I,J)=0
         LVISITSTOTAL_S(I,J)=0       
      ENDDO

      DO I=1, LHBINS
         LBINLABEL(I,J)=(HISTMIN+(J-1)*HISTINT*LHBINS) + HISTINT*(I-0.5)
      ENDDO

      DO I=1, SAMPLEDBINS 
         LBINLABEL_S(I,J)=(HISTMIN+(LHBINS-SAMPLEDBINS)*HISTINT+(J-1)*HISTINT*LHBINS) + HISTINT*(I-0.5)
      ENDDO
      
      IF (J.NE.1) THEN
        DO I=1, LHBINS
           LBINLABEL(I,J)=LBINLABEL(I,J)-HISTINT*(J-1)
        ENDDO
      ENDIF


      !DO I=1, SAMPLEDBINS
      !   PRINT *, LBINLABEL_S(I,J), LVISITS_S(I,J), L_LNWEIGHT_S(I,J)
      !ENDDO


 !****    SEEDING W(X) WITH HARMONIC DENSITY OF STATES FOR EACH WINDOW ****

      PRINT *, 'HARMONIC FREQUENCY FOR THE MINIMUM: ', LNHARMFREQ
      DO I=1, LHBINS
         L_LNWEIGHT(I,J)=LOG((LBINLABEL(I,J)-HISTMIN)**((3*NATOMS/2)-1))-LNHARMFREQ
      ENDDO

      L_LNWEIGHT_S=L_LNWEIGHT(LHBINS-SAMPLEDBINS+1:LHBINS,:)

!*** OR NOT:
      !L_LNWEIGHT_S=0.D0

       OPEN(UNIT=422, FILE='HARMVIBDOS.UNWEIGHTED', STATUS='UNKNOWN')
       DO I=1, LHBINS
          WRITE(422, '(2G20.10)') LBINLABEL(I,J), L_LNWEIGHT(I,J)
       ENDDO
       CLOSE(422)

       OPEN(UNIT=422, FILE='HARMVIBDOS_S.UNWEIGHTED', STATUS='UNKNOWN')
       DO I=1, SAMPLEDBINS 
          WRITE(422, '(2G20.10)') LBINLABEL_S(I,J), L_LNWEIGHT_S(I,J)
       ENDDO
       CLOSE(422)

      PRINT *, 'SEEDING WITH STARTING GEOMETRY:'

      DO      
        
        IF (J==1) THEN
           IF (CHRMMT) THEN
               IF (FIXEDENDMOVET) THEN ! ACTUALLY BASIN-HOPPING-TYPE STEPS IN INTERNAL COORDINATES
!!!                 CALL FIXEDENDMOVE(1)
!!!                 PERTURBEDCOORDINATES(:3*NATOMS,1) = COORDS(:3*NATOMS,1)
!!!             ELSE
                  COORDS(:3*NATOMS,1) = WINDOW_COORDS(:,J)
                  CALL FILLICT(1)
                  CALL TAKESTEPCH(1)
                  ! NEW GEOMETRY IS NOW IN COORDS
                  PERTURBEDCOORDINATES(:3*NATOMS,1) = COORDS(:3*NATOMS,1)
               ELSE ! TRY TAKING STEP IN CARTESIANS
                  PERTURBEDCOORDINATES=PERTURBGEOMETRY(WINDOW_COORDS(:,J))
                  COORDS(1:3*NATOMS,1) = PERTURBEDCOORDINATES(1:3*NATOMS,1)
                  CALL FILLICT(1)
               ENDIF
           ELSE
              PERTURBEDCOORDINATES=PERTURBGEOMETRY(WINDOW_COORDS(:,J))
              COORDS(:,1)=PERTURBEDCOORDINATES(:,1)
           ENDIF

        ELSE
           IF (CHRMMT) THEN
               IF (FIXEDENDMOVET) THEN ! ACTUALLY BASIN-HOPPING-TYPE STEPS IN INTERNAL COORDINATES
!!!                 CALL FIXEDENDMOVE(1)
!!!                 PERTURBEDCOORDINATES(:3*NATOMS,1) = COORDS(:3*NATOMS,1)
!!!             ELSE
                  COORDS(:3*NATOMS,1) = WINDOW_COORDS(:,(J-1))
                  CALL FILLICT(1)
                  CALL TAKESTEPCH(1)
                  ! NEW GEOMETRY IS NOW IN COORDS
                  PERTURBEDCOORDINATES(:3*NATOMS,1) = COORDS(:3*NATOMS,1)
               ELSE ! TRY TAKING STEP IN CARTESIANS
                  PERTURBEDCOORDINATES=PERTURBGEOMETRY(WINDOW_COORDS(:,(J-1)))
                  COORDS(1:3*NATOMS,1) = PERTURBEDCOORDINATES(1:3*NATOMS,1)
                  CALL FILLICT(1)
               ENDIF
           ELSE
              PERTURBEDCOORDINATES=PERTURBGEOMETRY(WINDOW_COORDS(:,(J-1)))
              COORDS(:,1)=PERTURBEDCOORDINATES(:,1)
           ENDIF
        ENDIF

        CALL POTENTIAL(COORDS, GRAD, POTEL, .TRUE., .FALSE.)
        CURRENTPOINTENERGY=POTEL
        CURRENTPOINTCOORDINATES(:,1)=COORDS(:,1)
        BININDEXOLD=ENERGY2INDEX(CURRENTPOINTENERGY, LBINLABEL_S(1,J))
        PRINT *, CURRENTPOINTENERGY, BININDEXOLD, LBINLABEL_S(1,J), LBINLABEL_S(SAMPLEDBINS,J)
        IF ((BININDEXOLD.GE.1 ).AND.(BININDEXOLD.LE.SAMPLEDBINS)) THEN
          DO I=1, 3*NATOMS
             WINDOW_COORDS(I,J)=CURRENTPOINTCOORDINATES(I,1)
          ENDDO
          PRINT *, WINDOW_COORDS(1,J), 'E', CURRENTPOINTENERGY
          EXIT
        ELSE
          DO I=1, 3*NATOMS
             WINDOW_COORDS(I,(J-1))=CURRENTPOINTCOORDINATES(I,1)
          ENDDO
        ENDIF

      ENDDO


      LNMODFAC=LOG(HISTFAC)
      NWL=0

      DO I=1, 3*NATOMS
         CURRENTPOINTCOORDINATES(I,1)=WINDOW_COORDS(I,J)
      ENDDO

      DO I=1, 3*NATOMS
         PERTURBEDCOORDINATESSAVE(I,1)=WINDOW_COORDS(I,J)
      ENDDO
      COORDS=CURRENTPOINTCOORDINATES
      CALL POTENTIAL(COORDS, GRAD, POTEL, .TRUE., .FALSE.)
      !CALL QUENCH(.FALSE.,1,LBFGS_ITERATIONS,DUMMY,DUMMY,CONVERGED,COORDS)
      CURRENTPOINTENERGY=POTEL
      OLDENERGY=POTEL
      PRINT *, 'INITIAL ENERGY', CURRENTPOINTENERGY, 'FOR WINDOW', J



      BININDEXOLD=ENERGY2INDEX(CURRENTPOINTENERGY, LBINLABEL_S(1,J))

      !IF (DEBUG) PRINT *, CURRENTPOINTENERGY, BININDEXOLD, 'HERE'

      IF ((BININDEXOLD < 1 ).OR.(BININDEXOLD > SAMPLEDBINS)) THEN
         PRINT *, 'STARTING GEOMETRY IS OUTSIDE REQUESTED RANGE. EXITING.'
         RETURN
      ENDIF 

      NQUENCHES=0
      NQUENCHESSINCEFLAT=0
      NQUENCHESSUCCESS=0
      ESCAPEDFROMTETHER=0
      NQUENCHESSINCELASTUPDATE=0


!REPEAT FOR THE REQUESTED NUMBER OF WANG-LANDAU ITERATIONS. 


      DO
         IF ( NWL==TARGETWL )  THEN
          PRINT *, 'WL RUN FOR WINDOW', J, 'COMPLETE.'
          EXIT
         ENDIF

         IF (CHRMMT) THEN
             IF (FIXEDENDMOVET) THEN ! ACTUALLY BASIN-HOPPING-TYPE STEP IN INTERNAL COORDINATES
!!!                 CALL FIXEDENDMOVE(1)
!!!                 PERTURBEDCOORDINATES(:3*NATOMS,1) = COORDS(:3*NATOMS,1)
!!!             ELSE
                COORDS(:3*NATOMS,1) = PERTURBEDCOORDINATESSAVE(:3*NATOMS,1)
                CALL FILLICT(1)
                CALL TAKESTEPCH(1)
                ! NEW GEOMETRY IS NOW IN COORDS
                PERTURBEDCOORDINATES(:3*NATOMS,1) = COORDS(:3*NATOMS,1)
             ELSE ! TRY TAKING STEP IN CARTESIANS
                PERTURBEDCOORDINATES = PERTURBGEOMETRY(PERTURBEDCOORDINATESSAVE)
                COORDS(1:3*NATOMS,1) = PERTURBEDCOORDINATES(1:3*NATOMS,1)
                CALL FILLICT(1)
             ENDIF
         ELSE
            PERTURBEDCOORDINATES=PERTURBGEOMETRY(PERTURBEDCOORDINATESSAVE)
            COORDS(:,1)=PERTURBEDCOORDINATES(:,1)
         ENDIF

         CHECKTETHER=CALCULATEDDISTANCE(SOURCEMINIMUM, PERTURBEDCOORDINATES)
         !PRINT *, 'DISTANCE2',CHECKTETHER,HDISTCONSTRAINT
         CALL POTENTIAL(COORDS, GRAD, POTEL, .TRUE., .FALSE.)
         !PRINT *, 'DISTANCE3', CHECKTETHER, HDISTCONSTRAINT
         IF ((EVAPREJECT).OR.(CHECKTETHER.GT.HDISTCONSTRAINT)) THEN
            ESCAPEDFROMTETHER=ESCAPEDFROMTETHER+1
            CYCLE
         ENDIF
         OLDENERGY=CURRENTPOINTENERGY
         CURRENTPOINTENERGY=POTEL
         CURRENTPOINTCOORDINATES=COORDS


         IF (.NOT.EVAPREJECT) THEN
            NQUENCHESSUCCESS=NQUENCHESSUCCESS+1
            BININDEXNEW=ENERGY2INDEX(CURRENTPOINTENERGY, LBINLABEL_S(1,J))


            IF (BININDEXNEW < 1 .OR.BININDEXNEW>SAMPLEDBINS) THEN
               !PRINT *, 'STRUCTURE OUTSIDE ENERGY RANGE. REJECTING MOVE'
                ACCEPTMOVE=.FALSE. 
            ELSE 
               LNRATIO=L_LNWEIGHT_S(BININDEXOLD,J)-L_LNWEIGHT_S(BININDEXNEW,J)
               CALL RANDOM_NUMBER(HARVEST)
               LNHARVEST=LOG(HARVEST)

                  IF ((LNRATIO>0.D0).OR.(LNRATIO>LNHARVEST)) THEN
                     ACCEPTMOVE=.TRUE.
                  ELSE
                     ACCEPTMOVE=.FALSE.
                  ENDIF
            ENDIF

            !PRINT *, 'EOLD, ENEW, IOLD, INEW, WOLD, WNEW, ACCEPTMOVE , RATIO'
            !PRINT *, OLDENERGY, CURRENTPOINTENERGY, BININDEXOLD, BININDEXNEW, L_LNWEIGHT(BININDEXOLD,J) , &
            !         & L_LNWEIGHT(BININDEXNEW,J), ACCEPTMOVE, LNRATIO


            IF (ACCEPTMOVE) THEN 
               ! MOVE ACCEPTED
                 LVISITS_S(BININDEXNEW,J)=LVISITS_S(BININDEXNEW,J)+1
                 LVISITSTOTAL_S(BININDEXNEW,J)=LVISITSTOTAL_S(BININDEXNEW,J)+1
                 L_LNWEIGHT_S(BININDEXNEW,J)=L_LNWEIGHT_S(BININDEXNEW,J)+LNMODFAC
               PERTURBEDCOORDINATESSAVE=PERTURBEDCOORDINATES
               BININDEXOLD=BININDEXNEW
               OLDENERGY=CURRENTPOINTENERGY
            ELSE
               ! MOVE REJECTED
               !PRINT *, 'STAYING IN BIN', BININDEXOLD
                  LVISITS_S(BININDEXOLD,J)=LVISITS_S(BININDEXOLD,J)+1
                  LVISITSTOTAL_S(BININDEXOLD,J)=LVISITSTOTAL_S(BININDEXOLD,J)+1
                  L_LNWEIGHT_S(BININDEXOLD,J)=L_LNWEIGHT_S(BININDEXOLD,J)+LNMODFAC
            ENDIF
         ELSE
         IF (DEBUG) PRINT *, 'OPTIMISATION UNSUCCESSFUL'
         ENDIF

         IF ((MOD(NQUENCHESSUCCESS,DUMPEVERYNTHQUENCH).EQ.0).AND.(NQUENCHESSINCELASTUPDATE > EQUIL)) THEN 
            ! RECORD STATISTICS
            ! PRINT *, NQUENCHESSUCCESS
             WRITE (ISTR, '(I10)') J 

             HISTFILENAME="LNWEIGHT.HIS."//TRIM(ADJUSTL(ISTR))
             OPEN(UNIT=421, FILE=HISTFILENAME, STATUS='UNKNOWN')
             DO I=1, SAMPLEDBINS
                WRITE(421, '(2G20.10)')  LBINLABEL_S(I,J), L_LNWEIGHT_S(I,J)
             ENDDO
             CLOSE(421)
           
             HISTFILENAME="VISITS.HIS."//TRIM(ADJUSTL(ISTR))
             OPEN(UNIT=422, FILE=HISTFILENAME, STATUS='UNKNOWN')
             DO I=1, SAMPLEDBINS
                WRITE(422, '(2G20.10)')  LBINLABEL_S(I,J), LVISITS_S(I,J)
             ENDDO
             CLOSE(422)
      
             HISTFILENAME="VISITSTOTAL.HIS."//TRIM(ADJUSTL(ISTR))
             OPEN(UNIT=422, FILE=HISTFILENAME, STATUS='UNKNOWN')
             DO I=1, SAMPLEDBINS
                WRITE(422, '(2G20.10)')  LBINLABEL_S(I,J), LVISITSTOTAL_S(I,J)
             ENDDO
             CLOSE(422)
           
             OPEN(UNIT=422, FILE='NWL.RESTART', STATUS='UNKNOWN')
             WRITE(422, '(4G20.10)') NWL, NINT(1.0D0/LNMODFAC), J, NQUENCHES
             CLOSE(422)
      
             OPEN(UNIT=422, FILE='ESCAPEDFROMTETHER', STATUS='UNKNOWN')
             WRITE(422, '(G20.10)') ESCAPEDFROMTETHER
             CLOSE(422)
 

             FLAT=CHECKFLATNESS(LVISITS_S(:,J), LNMODFAC, NWL) 
             IF (FLAT) THEN
                NQUENCHESSINCELASTUPDATE=0
                PRINT *, '--===VISITS HISTOGRAM SATISFIED FLATNESS CRITERION===--'
                LNMODFAC=HISTFACMUL*LNMODFAC
                PRINT *, 'UPDATING MODFAC TO', LNMODFAC, 'NEXT WL ITERATION:', NWL+1, 'VISITS NEEDED:', NINT(1.0D0/LNMODFAC)
                DO I=1, SAMPLEDBINS
                   LVISITS_S(I,J)=0
                ENDDO
                NWL=NWL+1
                ENDIF
      
         ENDIF

      NQUENCHES=NQUENCHES+1
      NQUENCHESSINCELASTUPDATE=NQUENCHESSINCELASTUPDATE+1
      IF (NQUENCHES.GT.200000) EXIT
      ENDDO

    ENDDO


    PRINT *, 'VIBRATIONAL DENSITY OF STATES GENERATION IN WINDOWS COMPLETE. STARTING SCALING:'

    TOT_LNWEIGHT=0.D0


    IF (HWINDOWS.GT.1) THEN
       SCALEFAC=1.0D0
       DO J=1, HWINDOWS
           IF (J.EQ.1) THEN
              DO I=1, LHBINS
                 LNWEIGHT(I+(J-1)*LHBINS)=L_LNWEIGHT(I, J)
              ENDDO
           ELSE
              SCALEFAC=L_LNWEIGHT(LHBINS, J-1)/L_LNWEIGHT(1, J)
              PRINT *, L_LNWEIGHT(LHBINS, J-1), L_LNWEIGHT(1, J), SCALEFAC, L_LNWEIGHT(1, J)*SCALEFAC 
              DO I=1, LHBINS
                 L_LNWEIGHT(I, J)=L_LNWEIGHT(I, J)*SCALEFAC
              ENDDO
              WRITE (ISTR, '(I10)') J 
              HISTFILENAME="LNWEIGHT2.HIS."//TRIM(ADJUSTL(ISTR))
              OPEN(UNIT=421, FILE=HISTFILENAME, STATUS='UNKNOWN')
              DO I=1, LHBINS
                 WRITE(421, '(2G20.10)')  LBINLABEL(I,J), L_LNWEIGHT(I,J)
              ENDDO
              CLOSE(421)
              DO I=1, LHBINS
                 LNWEIGHT(I+(J-1)*LHBINS)=L_LNWEIGHT(I, J)
              ENDDO
           ENDIF
        ENDDO
      ELSE
       DO J=1, HWINDOWS

         PRINT *, LBINLABEL(LHBINS-SAMPLEDBINS+1,J), LBINLABEL_S(1,J) 
         PRINT *, L_LNWEIGHT(LHBINS-SAMPLEDBINS+1,J), L_LNWEIGHT_S(1,J) 

         EXTRAPOLFAC=ABS(L_LNWEIGHT_S(1,J)-L_LNWEIGHT((LHBINS-SAMPLEDBINS+1),J))
         PRINT *, 'EXTRAPOLFAC', EXTRAPOLFAC 

        DO I=1, SAMPLEDBINS
           L_LNWEIGHT_S(I,J)=L_LNWEIGHT_S(I,J)-EXTRAPOLFAC
        ENDDO
        L_LNWEIGHT(LHBINS-SAMPLEDBINS+1:LHBINS,:)=L_LNWEIGHT_S

!        SHIFTFAC=(LOG((LBINLABEL(I,J)-HISTMIN)**((3*NATOMS/2)-1))-LNHARMFREQ)-L_LNWEIGHT(1,J)
!        PRINT *, SHIFTFAC
!
!        DO I=1, LHBINS
!              L_LNWEIGHT(I,J)=L_LNWEIGHT(I,J)+SHIFTFAC
!        ENDDO

    
        LNWEIGHT=L_LNWEIGHT(:,J) 
       ENDDO
      ENDIF

           

    HISTFILENAME="LNWEIGHT.HIS"
    OPEN(UNIT=422, FILE=HISTFILENAME, STATUS='UNKNOWN')
    !DO I=1, HBINS-HWINDOWS+1
    DO I=1, HBINS
        WRITE(422, '(2G20.10)')  BINLABEL(I), LNWEIGHT(I)
    ENDDO
    CLOSE(422)
    END SUBROUTINE TETHEREDWL

