!  GMIN: A PROGRAM FOR FINDING GLOBAL MINIMA
!  COPYRIGHT (C) 1999-2006 DAVID J. WALES
!  THIS FILE IS PART OF GMIN.
!
!  GMIN IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!  IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!  THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!  (AT YOUR OPTION) ANY LATER VERSION.
!
!  GMIN IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!  BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!  MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!  GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!
!  YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!  ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!  FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!


! FUNCTIONS MODULE TO SERVE TETHERED WL SUBROUTINE (TETYANA BOGDAN)
!---======================================---
      MODULE TETHERFUNC 
         IMPLICIT NONE
      CONTAINS

!---======================================---`
      FUNCTION ENERGY2INDEX(CURRENTPOINTENERGY, BINLABELBOTTOM)
      USE COMMONS
      IMPLICIT NONE

      INTEGER ENERGY2INDEX 

      REAL(8) CURRENTPOINTENERGY, BINLABELBOTTOM, HISTINT

      HISTINT=(HISTMAX-HISTMIN)/HBINS
      IF (NINT((CURRENTPOINTENERGY-(BINLABELBOTTOM-HISTINT/2.0D0))/HISTINT)<0) THEN
         ENERGY2INDEX=-1
      ELSE
         ENERGY2INDEX=NINT((CURRENTPOINTENERGY-(BINLABELBOTTOM-HISTINT/2.0D0))/HISTINT)+1
      ENDIF
!     WRITE(MYUNIT,'(A,3G20.10,I6)') 'ENERGY2INDEX> CURRENTPOINTENERGY,BINLABELBOTTOM,HISTINT,ENERGY2INDEX=', &
!    &                                              CURRENTPOINTENERGY,BINLABELBOTTOM,HISTINT,ENERGY2INDEX

      END FUNCTION ENERGY2INDEX


!---======================================---`
      REAL(8) FUNCTION GETDISPLACEMENT(STEP)
           IMPLICIT NONE
           REAL(8),INTENT(IN) :: STEP
           REAL(8) :: HARVEST
           CALL RANDOM_NUMBER(HARVEST)
           GETDISPLACEMENT=2.0D0*HARVEST*STEP-STEP
      END FUNCTION GETDISPLACEMENT

!---======================================---`
      FUNCTION PERTURBGEOMETRY(CURRENTPOINTCOORDINATES)
           USE COMMONS, ONLY: RADIUS,NATOMS,STEP
           IMPLICIT NONE

           REAL(8),DIMENSION(3*NATOMS,1) :: PERTURBGEOMETRY

           REAL(8),INTENT(IN) :: CURRENTPOINTCOORDINATES(3*NATOMS,1)
           !REAL(8) GETDISPLACEMENT
           INTEGER I, J

           PERTURBGEOMETRY=CURRENTPOINTCOORDINATES

           DO J=1, NATOMS
                DO
                 PRINT *, 'PERT'
                     PERTURBGEOMETRY(3*(J-1)+1,1) = PERTURBGEOMETRY(3*(J-1)+1,1) + GETDISPLACEMENT(STEP(1))
                     PERTURBGEOMETRY(3*(J-1)+2,1) = PERTURBGEOMETRY(3*(J-1)+2,1) + GETDISPLACEMENT(STEP(1))
                     PERTURBGEOMETRY(3*(J-1)+3,1) = PERTURBGEOMETRY(3*(J-1)+3,1) + GETDISPLACEMENT(STEP(1))
                     IF ( PERTURBGEOMETRY(3*(J-1)+1, 1)**2 &
                      & + PERTURBGEOMETRY(3*(J-1)+2, 1)**2 &
                      & + PERTURBGEOMETRY(3*(J-1)+3, 1)**2 < RADIUS ) THEN
                          EXIT
                     ELSE
                          PERTURBGEOMETRY(3*(J-1)+1,1) = CURRENTPOINTCOORDINATES(3*(J-1)+1,1)
                          PERTURBGEOMETRY(3*(J-1)+2,1) = CURRENTPOINTCOORDINATES(3*(J-1)+2,1)
                          PERTURBGEOMETRY(3*(J-1)+3,1) = CURRENTPOINTCOORDINATES(3*(J-1)+3,1)
                     ENDIF
		ENDDO
           ENDDO
      END FUNCTION PERTURBGEOMETRY

!---======================================---`

      FUNCTION CALCULATEDDISTANCE(CURRENTPOINTCOORDINATES, PERTURBEDCOORDINATES)
      USE COMMONS
      IMPLICIT NONE

      INTEGER I
      REAL(8) CALCULATEDDISTANCE, CURRENTPOINTCOORDINATES(3*NATOMS,1), PERTURBEDCOORDINATES(3*NATOMS,1), &
              & X1(NATOMS, 1), Y1(NATOMS, 1), Z1(NATOMS, 1), X2(NATOMS, 1), Y2(NATOMS, 1), Z2(NATOMS, 1)


      DO I=1,NATOMS
         X1(I,1)=CURRENTPOINTCOORDINATES(3*(I-1)+1,1)
         Y1(I,1)=CURRENTPOINTCOORDINATES(3*(I-1)+2,1)
         Z1(I,1)=CURRENTPOINTCOORDINATES(3*(I-1)+3,1)
         X2(I,1)=PERTURBEDCOORDINATES(3*(I-1)+1,1)
         Y2(I,1)=PERTURBEDCOORDINATES(3*(I-1)+2,1)
         Z2(I,1)=PERTURBEDCOORDINATES(3*(I-1)+3,1)
      ENDDO

      CALCULATEDDISTANCE=DSQRT(SUM ( (X1(:,1)-X2(:,1))**2 + (Y1(:,1)-Y2(:,1))**2 + (Z1(:,1)-Z2(:,1))**2 ) )

      !PRINT *, 'DISTANCE' , CALCULATEDDISTANCE

      !IF (CALCULATEDDISTANCE>0.8) THEN
      !    CALL PRINTXYZ(NATOMS,PERTURBEDCOORDINATES(:,1))
      !    CALL PRINTXYZ(NATOMS,CURRENTPOINTCOORDINATES(:,1))
      !ENDIF
      END FUNCTION CALCULATEDDISTANCE

!---======================================---`
      SUBROUTINE PRINTXYZ(NATOMS,X)
          IMPLICIT NONE

          INTEGER,INTENT(IN) :: NATOMS
          REAL(8),INTENT(IN) :: X(3*NATOMS)

          INTEGER :: I

          PRINT *, NATOMS
          PRINT *
          DO I=1,NATOMS
             WRITE(*,'(A4,3F20.10)') 'C   ',X(3*(I-1)+1),X(3*(I-1)+2),X(3*(I-1)+3)
          ENDDO
      END SUBROUTINE PRINTXYZ
!---======================================---`
      FUNCTION CHECKFLATNESS(LVISITS_S,LNMODFAC,NWL)
      USE COMMONS, ONLY: NATOMS, HBINS, HWINDOWS, HPERCENT, DEBUG, LHBINS, SAMPLEDBINS
      IMPLICIT NONE

      INTEGER LVISITS(LHBINS), N, I, VISITSNONZERO(LHBINS),HMIN, HMAX, DELTAHK, NWL, LVISITS_S(SAMPLEDBINS)
      LOGICAL CHECKFLATNESS, FLATBIN(LHBINS), FLATBIN_S(SAMPLEDBINS)
      REAL(8) HDEV, LNMODFAC
      CHARACTER (LEN =256) FILENAME
      CHARACTER (LEN= 10)  ISTR


      CHECKFLATNESS=.FALSE.


!      HMAX=MAXVAL(LVISITS)
!      DO I=1, LHBINS
!         IF (LVISITS(I).NE.0) THEN
!            VISITSNONZERO(I)=LVISITS(I)
!         ELSE
!            VISITSNONZERO(I)=HUGE(LHBINS)
!         ENDIF
!      ENDDO
!      HMIN=MINVAL(VISITSNONZERO)
!      IF (DEBUG) PRINT *, 'MIN AND MAX', HMIN, HMAX
!
!      HDEV=(1.0D0*HMAX-HMIN)/(HMAX+HMIN)
    
!  
!     (ABS(HMIN-HMAX)>HPERCENT)) NEEDED TO PREVENT THE RUN FROM EXITING RIGHT AFTER THE EQUILIBRATION

!     FLATNESS CONDITION
!     IF ((HDEV<HPERCENT).AND.(ABS(1.0D0*HMIN-HMAX)>HPERCENT)) CHECKFLATNESS=.TRUE.


!     VISITPROP:MINIMAL NUMBER OF VISITS SHOULD BE PROPORTIONAL TO 1/SQRT(LN(F))

         CHECKFLATNESS=.FALSE.
         FLATBIN_S=.FALSE.
 
         DO I=1, SAMPLEDBINS
            IF (LVISITS_S(I) > 1.0D0/SQRT(LNMODFAC)) FLATBIN_S(I)=.TRUE.
         ENDDO
 
         IF (ALL(FLATBIN_S)) CHECKFLATNESS=.TRUE.

      END FUNCTION CHECKFLATNESS

!---======================================---
    SUBROUTINE SAVEBINSTRUCTURES(CURRENTPOINTENERGY, CURRENTPOINTCOORDINATES, BININDEX, MINIMANUMBER, WRITESTRUCT)
        USE COMMONS, ONLY:NATOMS, HBINS,BQMAX, CHRMMT, ZSYM
        USE MODCHARMM, ONLY: OSASAT, RPRO, ODIHET
        IMPLICIT NONE

        INTEGER BININDEX, JB, JC, MINIMANUMBER(HBINS)
        INTEGER, SAVE :: BINENSAVED=0
        REAL(8) CURRENTPOINTENERGY, CURRENTPOINTCOORDINATES(3*NATOMS, 1), Q4ORDERPARAM
        REAL(8) DIHEORDERPARAM,SASAORDERPARAM
        LOGICAL NEWBINENERGY, YESNO, WRITESTRUCT
        CHARACTER (LEN =256)  BINNAME
        CHARACTER (LEN= 10)  ISTR
        REAL(8),ALLOCATABLE, SAVE :: BINENERGIES(:)
        INTEGER,ALLOCATABLE, SAVE :: BINENIMPORTANCEINDEX(:)
        
         IF (BINENSAVED.EQ.0) THEN
           ALLOCATE(BINENERGIES(100000000))
           BINENERGIES=0.0
           ALLOCATE(BINENIMPORTANCEINDEX(100000000))
           BINENIMPORTANCEINDEX=0
         ENDIF
      
         IF (BINENSAVED.EQ.SIZE(BINENERGIES)) THEN
            RETURN
         ENDIF

         INQUIRE(FILE='BINENERGIES', EXIST=YESNO)

         NEWBINENERGY=.TRUE.
         DO JB=1, BINENSAVED
             IF (ABS(BINENERGIES(JB)-CURRENTPOINTENERGY).LE.BQMAX) THEN
                NEWBINENERGY=.FALSE.
             ENDIF
         ENDDO

         IF (NEWBINENERGY) THEN
            BINENSAVED=BINENSAVED+1
            !CALL ORDERQ4(NATOMS, CURRENTPOINTCOORDINATES, Q4ORDERPARAM)
            IF (ODIHET) CALL CHCALCDIHE(DIHEORDERPARAM,CURRENTPOINTCOORDINATES(1:3*NATOMS,1))
            IF (OSASAT) CALL ORDER_SASA(SASAORDERPARAM,RPRO,CURRENTPOINTCOORDINATES(1:3*NATOMS:3,1), &
                      & CURRENTPOINTCOORDINATES(2:3*NATOMS:3,1),CURRENTPOINTCOORDINATES(3:3*NATOMS:3,1))
            BINENERGIES(BINENSAVED)=CURRENTPOINTENERGY
            IF (WRITESTRUCT)  THEN
                IF ((BINENSAVED.EQ.1).AND.(YESNO)) THEN
                   OPEN(UNIT=1979,FILE='BINENERGIES',STATUS='OLD')
                ELSE
                   OPEN(UNIT=1979,FILE='BINENERGIES',STATUS='UNKNOWN',POSITION='APPEND')
                ENDIF
! JMC                WRITE(1979,'(2G20.10)') CURRENTPOINTENERGY, Q4ORDERPARAM
                IF (ODIHET.AND.OSASAT) THEN
                   WRITE(1979,'(3G20.10)') CURRENTPOINTENERGY, DIHEORDERPARAM, SASAORDERPARAM
                ELSEIF (OSASAT) THEN
                   WRITE(1979,'(2G20.10)') CURRENTPOINTENERGY, SASAORDERPARAM
                ELSEIF (ODIHET) THEN
                   WRITE(1979,'(2G20.10)') CURRENTPOINTENERGY, DIHEORDERPARAM
                ELSE
                   WRITE(1979,'(G20.10)') CURRENTPOINTENERGY
                ENDIF
                CLOSE (1979)
                WRITE (ISTR, '(I10)') BININDEX
                BINNAME="BINSTRUCTURES."//TRIM(ADJUSTL(ISTR))
                IF ((BINENSAVED.EQ.1).AND.(YESNO)) THEN
                   OPEN(UNIT=1979,FILE=BINNAME, STATUS="OLD", FORM="FORMATTED")
                ELSE
                   OPEN(UNIT=1979,FILE=BINNAME, STATUS="UNKNOWN", FORM="FORMATTED", POSITION="APPEND")
                ENDIF
                WRITE(1979,'(I10)') NATOMS
                WRITE(1979,'(A,1G20.10)') '     STRUCTURE WITH ENERGY ', CURRENTPOINTENERGY
                IF (CHRMMT) THEN
                   DO JB=1,NATOMS
                      WRITE(1979,'(A,1X,3F20.10)') ZSYM(JB)(1:1),(CURRENTPOINTCOORDINATES(3*(JB-1)+JC,1),JC=1,3)
                   ENDDO
                ELSE
                   WRITE(1979,30) (CURRENTPOINTCOORDINATES(JB,1),JB=1,3*NATOMS)
30                 FORMAT('LA ',3F20.10)
                ENDIF
                CLOSE (1979)
             ENDIF
             MINIMANUMBER(BININDEX)=MINIMANUMBER(BININDEX)+1
         ENDIF

! IMPORTANCE INDEX 

 	 IF ((.NOT.NEWBINENERGY).AND.(WRITESTRUCT)) THEN 
		OPEN(UNIT=1979,FILE="BINENIMPORTANCEINDEX", STATUS="UNKNOWN", FORM="FORMATTED")
		DO JB=1, BINENSAVED
	             IF (ABS(BINENERGIES(JB)-CURRENTPOINTENERGY).LE.BQMAX) THEN
		     BINENIMPORTANCEINDEX(JB)=BINENIMPORTANCEINDEX(JB)+1
             	     ENDIF
         	ENDDO
		DO JB=1, BINENSAVED
		WRITE(1979,'(1G20.10, I10)') BINENERGIES(JB), BINENIMPORTANCEINDEX(JB)
		ENDDO
		CLOSE (1979)
	 ENDIF
 
         IF (BINENSAVED.EQ.SIZE(BINENERGIES)) THEN
            IF (ALLOCATED(BINENERGIES)) DEALLOCATE(BINENERGIES)
         ENDIF

         END SUBROUTINE SAVEBINSTRUCTURES

!---======================================---
    SUBROUTINE SAVEBINSTRUCTURESMPI(CURRENTPOINTENERGY,CURRENTPOINTCOORDINATES,BININDEX,WRITESTRUCT,NODE, NEWBINENERGY)

        USE COMMONS, ONLY:NATOMS, HBINS,BQMAX, CHRMMT, ZSYM,NPAR
        USE MODCHARMM, ONLY: OSASAT, RPRO, ODIHET
        IMPLICIT NONE

        INTEGER BININDEX, JB, JC, NODE, I, MINIMANUMBER(HBINS,0:NPAR-1)
        INTEGER, SAVE :: BINENSAVED=0
        REAL(8) CURRENTPOINTENERGY, CURRENTPOINTCOORDINATES(3*NATOMS, 1), Q4ORDERPARAM
        REAL(8) DIHEORDERPARAM,SASAORDERPARAM
        LOGICAL NEWBINENERGY, YESNO, WRITESTRUCT
        CHARACTER (LEN =256)  BINNAME, FILENAME
        CHARACTER (LEN= 10)  ISTR, JSTR

        REAL(8),ALLOCATABLE, SAVE :: BINENERGIES(:)
        INTEGER,ALLOCATABLE, SAVE :: BINENIMPORTANCEINDEX(:,:)
        
         IF (BINENSAVED.EQ.0) THEN
           ALLOCATE(BINENERGIES(100000000))
           BINENERGIES=0.0
           ALLOCATE(BINENIMPORTANCEINDEX(10000,0:NPAR-1))
           BINENIMPORTANCEINDEX(:,NODE)=0
         ENDIF
      
         IF (BINENSAVED.EQ.SIZE(BINENERGIES)) THEN
            RETURN
         ENDIF

         WRITE (ISTR, '(I10)') NODE
         FILENAME="BINENERGIES."//TRIM(ADJUSTL(ISTR))
         INQUIRE(FILE='BINENERGIES', EXIST=YESNO)

         NEWBINENERGY=.TRUE.
         DO JB=1, BINENSAVED
             IF (ABS(BINENERGIES(JB)-CURRENTPOINTENERGY).LE.BQMAX) THEN
                NEWBINENERGY=.FALSE.
             ENDIF
         ENDDO

         IF (NEWBINENERGY) THEN
            BINENSAVED=BINENSAVED+1
            !CALL ORDERQ4(NATOMS, CURRENTPOINTCOORDINATES, Q4ORDERPARAM)
            IF (ODIHET) CALL CHCALCDIHE(DIHEORDERPARAM,CURRENTPOINTCOORDINATES(1:3*NATOMS,1))
            IF (OSASAT) CALL ORDER_SASA(SASAORDERPARAM,RPRO,CURRENTPOINTCOORDINATES(1:3*NATOMS:3,1), &
                      & CURRENTPOINTCOORDINATES(2:3*NATOMS:3,1),CURRENTPOINTCOORDINATES(3:3*NATOMS:3,1))
            BINENERGIES(BINENSAVED)=CURRENTPOINTENERGY
            IF (WRITESTRUCT)  THEN
                IF ((BINENSAVED.EQ.1).AND.(YESNO)) THEN
                   OPEN(UNIT=1979,FILE=FILENAME, STATUS="OLD", FORM="FORMATTED")
                ELSE
                   OPEN(UNIT=1979,FILE=FILENAME,FORM="FORMATTED",STATUS='UNKNOWN',POSITION='APPEND')
                ENDIF
! JMC                WRITE(1979,'(2G20.10)') CURRENTPOINTENERGY, Q4ORDERPARAM
                IF (ODIHET.AND.OSASAT) THEN
                   WRITE(1979,'(3G20.10)') CURRENTPOINTENERGY, DIHEORDERPARAM, SASAORDERPARAM
                ELSEIF (OSASAT) THEN
                   WRITE(1979,'(2G20.10)') CURRENTPOINTENERGY, SASAORDERPARAM
                ELSEIF (ODIHET) THEN
                   WRITE(1979,'(2G20.10)') CURRENTPOINTENERGY, DIHEORDERPARAM
                ELSE
                   WRITE(1979,'(G20.6)') CURRENTPOINTENERGY
                ENDIF
                CLOSE (1979)
                WRITE (JSTR, '(I10)') BININDEX
                BINNAME="BINSTRUCTURES."//TRIM(ADJUSTL(ISTR))//"T."//TRIM(ADJUSTL(JSTR))
                IF ((BINENSAVED.EQ.1).AND.(YESNO)) THEN
                   OPEN(UNIT=1979+NODE,FILE=BINNAME, STATUS="OLD", FORM="FORMATTED")
                ELSE
                   OPEN(UNIT=1979+NODE,FILE=BINNAME, STATUS="UNKNOWN", FORM="FORMATTED", POSITION="APPEND")
                ENDIF
                WRITE(1979+NODE,'(I10)') NATOMS
                WRITE(1979+NODE,'(A,1G20.10)') '     STRUCTURE WITH ENERGY ', CURRENTPOINTENERGY
                IF (CHRMMT) THEN
                   DO JB=1,NATOMS
                      WRITE(1979+NODE,'(A,1X,3F20.10)') ZSYM(JB)(1:1),(CURRENTPOINTCOORDINATES(3*(JB-1)+JC,1),JC=1,3)
                   ENDDO
                ELSE
                   WRITE(1979+NODE,30) (CURRENTPOINTCOORDINATES(JB,1),JB=1,3*NATOMS)
30                 FORMAT('LA ',3F20.10)
                ENDIF
                CLOSE (1979+NODE)
            ENDIF
             MINIMANUMBER(BININDEX, NODE)=MINIMANUMBER(BININDEX, NODE)+1
         ENDIF



! IMPORTANCE INDEX 

 	 IF ((.NOT.NEWBINENERGY).AND.(WRITESTRUCT)) THEN 
                BINNAME="BINENIMPORTANCEINDEX."//TRIM(ADJUSTL(ISTR))
		OPEN(UNIT=1980+NODE,FILE=BINNAME, STATUS="UNKNOWN", FORM="FORMATTED")
		DO JB=1, BINENSAVED
	             IF (ABS(BINENERGIES(JB)-CURRENTPOINTENERGY).LE.BQMAX) THEN
		     BINENIMPORTANCEINDEX(JB,NODE)=BINENIMPORTANCEINDEX(JB,NODE)+1
             	     ENDIF
         	ENDDO
		DO JB=1, BINENSAVED
		WRITE(1980+NODE,'(1G20.10, I10)') BINENERGIES(JB), BINENIMPORTANCEINDEX(JB,NODE)
		ENDDO
		CLOSE (1980+NODE)
	 ENDIF
 
         IF (BINENSAVED.EQ.SIZE(BINENERGIES)) THEN
            IF (ALLOCATED(BINENERGIES)) DEALLOCATE(BINENERGIES)
         ENDIF

         END SUBROUTINE SAVEBINSTRUCTURESMPI
   
    END MODULE TETHERFUNC
