!op226>=================================== 
!op226> GPL License Info {{{
!  GMIN: A program for finding global minima
!  Copyright (C) 1999-2006 David J. Wales
!  This file is part of GMIN.
!
!  GMIN is free software; you can redistribute it and/or modify
!  it under the terms of the GNU General Public License as published by
!  the Free Software Foundation; either version 2 of the License, or
!  (at your option) any later version.
!
!  GMIN is distributed in the hope that it will be useful,
!  but WITHOUT ANY WARRANTY; without even the implied warranty of
!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!  GNU General Public License for more details.
!
!  You should have received a copy of the GNU General Public License
!  along with this program; if not, write to the Free Software
!  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
!op226> }}}
!op226>=================================== 
!
!> \name COMMONS
!> \brief Declarations for common variables 
!> \param MCSTEPS(3)
!> \param NPAR 
!> \param NSEED 
!
!op226>=================================== 
      MODULE COMMONS
      IMPLICIT NONE
      SAVE
      INTEGER :: NATOMS, NACCEPT, MAXIT, NTARGETS, NN, MM, NPAR, NPATCH, TIPID, PAHID, NSYMREM=0, NFREEZE, NSAVEINTE, &
     &        NINTV, NSEED, NVEC, NS, NSSTOP, MAXIT2, NSAVE, SHELLMOVEMAX, HPTGRP, NFIX, CURRENTIMP,&
     &        MCSTEPS(3), NRUNS, NVAR, MYPOWER, XMUL,  NTAB, NCARBON, NCOOP, NSYMINTERVAL, QDLIMIT, COULN, &
     &        NSUPER, NSACCEPT, NSUPERSTEP, GMODES, DUMPXYZUNIT, DUMPVUNIT, QUENCHFRQ, CHNRES, &
     &        NEVL, NEVS, NVECTORS, MUPDATE, LSYS, NHSMOVE, NRENORM, NRELAX, NHSRESTART, NRENSTUCK,&
     &        HBINS, NRBSITES, NRBSITES1, NPS, GATOM, NMSBSAVE, MAXSAVE, NSYMQMAX, EQUIL, TPAHA, ISTEP, &
     &        NINTS, NumberOfTrajectories, &
     &        MCCycles, MCCyclesEquilibration, TargetWL, NTempPoints, SaveNth, DumpEveryNthQuench, NSpline, Hwindows, & 
     &        lhbins, sampledbins, MYNODE, NENRPER, DUMPINT, LFH, PRTFRQ, BSPTDUMPFRQ, NPERMGROUP, NMOVABLEATOMS, &
     &        CPS, CPF, ACKLANDID, PATOM1, PATOM2, CSMGPINDEX, CSMGUIDEGPINDEX, CSMSTEPS, CSMQUENCHES, CSMMAXIT, &
     &        MYEUNIT, MYMUNIT, MYBUNIT, MYRUNIT, MYPUNIT
 
     DOUBLE PRECISION RHO, GAMMA, SIG, SCEPS, SCC, TOLB, T12FAC, XMOVERENORM, RESIZE, QTSALLIS, &
     &                 CQMAX, RADIUS, BQMAX,  MAXBFGS, DECAYPARAM, SYMTOL1, SYMTOL2, SYMTOL3, SYMTOL4, SYMTOL5, &
     &                 ECONV, TOLD, TOLE, SYMREM(120,3,3), GMAX, CUTOFF, PCUT, EXPFAC, EXPD, CENTX, CENTY, CENTZ, &
     &                 BOXLX, BOXLY, BOXLZ, PCUTOFF, SUPSTEP, SQUEEZER, SQUEEZED, COOPCUT, STOCKMU, STOCKLAMBDA, &
     &                 TFAC(3), RMS, TEMPS, SACCRAT, CEIG, PNEWJUMP, EAMP, DISTFAC, ODDCHARGE, COULQ, COULSWAP, &
     &                 COULTEMP, APP, AMM, APM, XQP, XQM, ALPHAP, ALPHAM, ZSTAR, COMP, DGUESS, GUIDECUT, EFAC,& 
     &                 TRENORM, HISTMIN, HISTMAX, HISTFAC, EPSSPHERE, FINALCUTOFF, SHELLPROB, RINGROTSCALE, &
     &                 HISTFACMUL, HPERCENT, AVOIDDIST, MAXERISE, MAXEFALL, TSTART, MATDIFF, STICKYSIG, SDTOL, &
     &                 MinimalTemperature, MaximalTemperature, SwapProb, hdistconstraint, COREFRAC, TSTAR, &
     &                 RK_R, RK_THETA,ARMA,ARMB, ExtrapolationPercent, lnHarmFreq, PTEMIN, PTEMAX, PTTMIN, PTTMAX, EXCHPROB, &
     &                 PTSTEPS, NEQUIL, NQUENCH, COLDFUSIONLIMIT, NEWRES_TEMP, MINOMEGA, LJSIGMA, LJEPSILON, TAUMAX, &
     &                 TAUMAXFULL, CPFACTORSG, CPFACTORFG, VGWTOL, ABTHRESH, ACTHRESH, CSMPMAT(3,3), &
     &                 RADIUS_CONTAINER, HYDROPHOBIC, &
!
!   parameters for anisotropic potentials
!
!    DC430 >
     &                 EPSR, GBKAPPA, GBKAPPRM, GBMU,GBNU, GBSIGNOT, GBEPSNOT, GBCHI, GBCHIPRM, &
     &                 SIGNOT, EPSNOT, SIGMAF, INVKAP, ESA(3), LPRSQ, LSQDFR, GBDPMU, GBDPEPS, GBDPFCT, &
     &                 PYSIGNOT, PYEPSNOT, PYA1(3), PYA2(3), PYDPMU, PYDPEPS, PYDPFCT, &
     &                 LWRCUT, LWCNSTA, LWCNSTB, LWRCUTSQ, LWRCUT2SQ, DELRC, PAPALP, PAPS, PAPCD, PAPEPS, &    
     &                 DBEPSBB, DBEPSAB, DBSIGBB, DBSIGAB, DBPMU, EFIELD, GEMRC, MREQ, &
     &                 EPS11, EPS22, EPS12, MRHO11, MRHO22, MRHO12, REQ11, REQ22, REQ12, &
     &                 RHOCC0, RHOCC10, RHOCC20,  RHOHH0, RHOHH10, RHOHH20, RHOCH0, RHOC10H, &
     &                 RHOCH10, RHOC20H, RHOCH20, ALPHACC, ALPHAHH, ALPHACH, DC6CC, DC6HH, DC6CH, KKJ, CCKJ, &
     &                 GBANISOTROPYR,GBWELLDEPTHR,PARAMa1,PARAMb1,PARAMc1,PARAMa2,PARAMB2,PARAMc2,PSIGMA0(2),PEPSILON0,&
     &                 PEPSILON1(3),PSCALEFAC1(2),PSCALEFAC2(2),PYA11(3),PYA21(3),PYA12(3),PYA22(3), &
     &                 PEPSILONATTR(2),PSIGMAATTR(2), PYOVERLAPTHRESH, LJSITECOORDS(3), &
     &                 MSTART,MFINISH,MBSTART1,MBFINISH1,MBSTART2,MBFINISH2,MBHEIGHT1,MBHEIGHT2,ME1,ME2,ME3, &
     &                 BSPTQMAX, BSPTQMIN, PFORCE, CSMNORM, CSMGUIDENORM, CSMEPS, PERCCUT
!
!
      LOGICAL DEBUG, TARGET, MORSET, CUTT, SEEDT, CENT, TSALLIST, FREEZECORE, NEWJUMP, RENORM, CAPSID, FREEZE, &
     &        OTPT, LJMFT, STRANDT, PAHT, SWT, MSTRANST, STOCKT, STICKYT, BLNT, MYSDT, FREEZERES, CENTXY, &
     &        MSORIGT, SQUEEZET, PERIODIC, SCT, RESIZET, TIP, RIGID, Q4T, MPIT, JMT, LJCOULT, SETCENT, &
     &        SORTT, HIT, SAVEQ, PARALLELT, FIXD, RKMIN, BSMIN, PERMDIST, PERMOPT, BSWL, BSPT, BSPTRESTART, &
     &        SYMMETRIZE, SYMMETRIZECSM, DUMPT, NEON, ARGON, P46, NORESET, TABOOT, EVSTEPT, PACHECO, DL_POLY, QUCENTRE, &
     &        STAR, PLUS, TWOPLUS, GROUND, DIPOLE, DFTBT, SW, SUPERSTEP, EAMLJT, PBGLUET, TRACKDATAT, &
     &        EAMALT, ALGLUET, MGGLUET, GUPTAT, FST, DECAY, COOP, FIXBIN, GAUSST, QUENCHDOS, FIXDIHEFLAG, &
     &        FRAUSIT, ANGST, SELFT, STEPOUT, WENZEL, THRESHOLDT, THOMSONT, MULLERBROWNT, CHARMMENERGIES, &
     &        PROJ, RGCL2, TOSI, WELCH, AXTELL, AMBER, FIXIMAGE, BINARY, SHIFTCUT, ARNO, TUNNELT, TWOD, & 
     &        BLJCLUSTER, COMPRESST, FIX, FIXT, BFGS, LBFGST, DBRENTT, DZTEST, FNI, FAL, CPMD, TNT, ZETT1, &
     &        ZETT2, RESTART, CONJG, NEWRESTART, AVOID, NATBT, DIFFRACTT, CHRMMT, INTMINT, LB2T, & 
     &        PTMC, BINSTRUCTURES, PROGRESS, MODEL1T, NEWRESTART_MD, CHANGE_TEMP, NOCISTRANS, CHECKCHIRALITY, &
     &        GBT, GBDT, GBDPT, GEMT, LINRODT, PYGT, RADIFT, PYGDPT, DBPT, DBPTDT, DBLPYT, DMBLMT, EFIELDT, PAHAT, STOCKAAT, &
     &        MSGBT, MSPYGT, MSTBINT, MMRSDPT, MSSTOCKT, LWOTPT, NCAPT, NPAHT, NTIPT, PAHW99T, ELLIPSOIDT, GAYBERNET,& 
     &        MULTPAHAT, PAPT, SILANET, TDHDT, WATERDCT, WATERKZT, CHECKDT, CHECKMARKOVT, & 
     &        TETHER, HISTSMOOTH, VISITPROP, ARMT, FixedEndMoveT, FIXCOM, RESTORET, QUADT, AMHT, MOVESHELLT, QDT, QD2T, &
     &        PARAMONOVPBCX, PARAMONOVPBCY, PARAMONOVPBCZ, PARAMONOVCUTOFF, GAYBERNEDCT, UNFREEZERES, FREEZEALL, &
     &        PROJIT, PROJIHT, LEAPDIHE, DUMPQUT, DUMPBESTT, PARAMONOVT, LJSITE, BLJSITE, LJSITEATTR, DUMPSTEPST, &
     &        AMBERT, RANDOMSEEDT, PYGPERIODICT, LJCAPSIDT, PYBINARYT, SWAPMOVEST, MOVABLEATOMST, LIGMOVET,DUMPSTRUCTURES, &
     &        LJSITECOORDST, VGW, ACKLANDT, G46, DF1T, PULLT, LOCALSAMPLET, CSMT, A9INTET, INTERESTORE, COLDFUSION, &
     &        CSMGUIDET, MULTISITEPYT, CHAPERONINT, AVOIDRESEEDT, OHCELLT, UNFREEZEFINALQ, PERCOLATET, PERCT, PERCACCEPTED,&
     &        GENALT, MINDENSITYT

!
! csw34> FREEZEGROUP variables
!
      INTEGER :: GROUPCENTRE
      DOUBLE PRECISION :: GROUPRADIUS
      CHARACTER (LEN=2) :: FREEZEGROUPTYPE
      LOGICAL :: FREEZEGROUPT
! END

!
! csw34> DONTMOVE variables
!
      INTEGER :: NDONTMOVE, DONTMOVECENTRE
      DOUBLE PRECISION :: DONTMOVERADIUS
      CHARACTER (LEN=2) :: DONTMOVEGROUPTYPE
      LOGICAL :: DONTMOVET, DONTMOVEGROUPT, DONTMOVEREST, DONTMOVEALL, DOMOVEREST
      LOGICAL, ALLOCATABLE :: DONTMOVE(:),DONTMOVERES(:)

!
! csw34> PAIRDIST variables
!
      INTEGER :: NPAIRS
      INTEGER, ALLOCATABLE :: PAIRDIST(:,:)
      LOGICAL :: PAIRDISTT
!
! csw34> Reporter for chirality and cis/trans checks in quench.f
!
      LOGICAL :: GOODSTRUCTURE

! GROUP ROTATION MOVE PARAMETERS
      INTEGER :: GROUPROTFREQ, NGROUPS
      LOGICAL :: GROUPROTT, DOGROUPROT=.FALSE.
      CHARACTER(LEN=10), ALLOCATABLE :: ATOMGROUPNAMES(:)
      INTEGER, ALLOCATABLE :: ATOMGROUPAXIS(:,:)
      DOUBLE PRECISION, ALLOCATABLE :: ATOMGROUPSCALING(:),ATOMGROUPPSELECT(:)
      LOGICAL, ALLOCATABLE :: ATOMGROUPS(:,:)
      
! END OF GROUP ROTATION MOVE PARAMETERS
      INTEGER  NGBSITE, NPYSITE, PYBINARYTYPE1, PYSWAP(3), MAXINTERACTIONS
   
      DOUBLE PRECISION :: DZP1, DZP2, DZP3, DZP4, DZP5, DZP6, DZP7
      LOGICAL :: FIELDT, OHT, IHT, TDT, D5HT
      DOUBLE PRECISION :: FOH, FIH, FTD, FD5H

      CHARACTER(LEN=80) :: SYS
      CHARACTER(LEN=80) :: INFILE=''
      CHARACTER(LEN=1), ALLOCATABLE :: BEADLETTER(:), BLNSSTRUCT(:)
      CHARACTER(LEN=130) DUMPFILE, MYFILENAME, INTEDUMPFILE

      INTEGER NUMPRO_AMH, NINT_AMH, SEED_AMH,HARM_AMH, I1_AMH
      CHARACTER AMINOA(21)*3
      DATA (AMINOA(I1_AMH),I1_AMH=1,21)/'ALA','ARG','ASN','ASP','CYS','GLN','GLU','GLY', &
           'HIS','ILE','LEU','LYS','MET','PHE','PRO','SER','THR','TRP','TYR','VAL','INI'/

      !DOUBLE PRECISION :: HESS(1,1)
!     DOUBLE PRECISION HESS(3*MXATMS,3*MXATMS)
      CHARACTER(LEN=3) :: CSMGP, CSMGUIDEGP


!|gd351> extra variables for patchy and asakura-oosawa models
       LOGICAL :: PATCHY, ASAOOS
       DOUBLE PRECISION :: SIGMASQ, RANGESQ, FACTOR, SIGMAP 
!<gd351|


!   allocatables

      INTEGER,ALLOCATABLE,DIMENSION(:) :: MOVABLEATOMLIST         ! a list containing the movable atom indices
      LOGICAL,ALLOCATABLE,DIMENSION(:) :: MOVABLEATOMLISTLOGICAL  ! is atom i movable?

      INTEGER, ALLOCATABLE, DIMENSION(:) :: NT, NQ, BLOCK, JUMPINT, JUMPTO, NCORE, NSURFMOVES  ! dimension will be NPAR
      INTEGER, ALLOCATABLE, DIMENSION(:) :: HISTVALS, LHISTVALS  ! dimension declared HBINS in keyword
      INTEGER, ALLOCATABLE :: NPERMSIZE(:), PERMGROUP(:)
      INTEGER, ALLOCATABLE :: NSETS(:)
      INTEGER, ALLOCATABLE :: SETS(:,:)
      INTEGER, ALLOCATABLE :: PERMUTE(:,:)
      INTEGER, ALLOCATABLE :: NCRBN(:), NCMP(:)

      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: TEMP, STEP, OSTEP, ASTEP, ACCRAT, EPREV ! dimension will be NPAR 
      DOUBLE PRECISION, ALLOCATABLE :: TARGETS(:) ! allocated NTARGETS in keyword.f
      DOUBLE PRECISION, ALLOCATABLE :: ESAVE(:,:) ! dimension will be NTAB,NPAR
      DOUBLE PRECISION, ALLOCATABLE :: XINSAVE(:,:) ! dimension will be NTAB,NPAR
      DOUBLE PRECISION, ALLOCATABLE :: HDIST(:), HWEIGHT(:) ! dimension declared HISTBINMAX in keyword
      DOUBLE PRECISION, ALLOCATABLE :: VEC(:) ! dimension would be NVEC - not used
      DOUBLE PRECISION, ALLOCATABLE :: MASSES(:)

      LOGICAL, ALLOCATABLE, DIMENSION(:) :: FIXBOTH, FIXTEMP, FIXSTEP, JUMPMOVE, JDUMP, TMOVE, OMOVE ! dimension will be NPAR
      LOGICAL, ALLOCATABLE, DIMENSION(:) :: SHELLMOVES ! dimension will be NPAR
      LOGICAL, ALLOCATABLE ::  IGNOREBIN(:) ! will be HBINS
      LOGICAL, ALLOCATABLE, DIMENSION(:) :: FROZENRES  ! NATOMS for safety 
      LOGICAL, ALLOCATABLE, DIMENSION(:) :: FROZEN  !  NATOMS

      INTEGER, ALLOCATABLE, DIMENSION(:) ::  IATNUM     
      INTEGER,ALLOCATABLE :: ANV(:,:,:)
      DOUBLE PRECISION, ALLOCATABLE :: LJREP_BLN(:,:), LJATT_BLN(:,:), A_BLN(:), B_BLN(:), C_BLN(:), D_BLN(:), HYDRO_BLN(:)
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) :: TCOORDS
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: VT
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) :: COORDS,COORDSO
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) ::  VAT,  VATO    
      DOUBLE PRECISION, ALLOCATABLE :: SITE(:,:), RBUV(:,:), RBSTLA(:,:), STCHRG(:), DPMU(:)
      DOUBLE PRECISION, ALLOCATABLE :: MSBCOORDS(:,:)
      DOUBLE PRECISION, ALLOCATABLE :: MSBE(:)
      DOUBLE PRECISION, ALLOCATABLE :: GAUSSKK(:,:)
      DOUBLE PRECISION, ALLOCATABLE :: GAUSSEE(:), GKSMALL(:)
      DOUBLE PRECISION, ALLOCATABLE :: CSMIMAGES(:)
      DOUBLE PRECISION, ALLOCATABLE :: QMINPCSMAV(:,:), CSMAV(:), QMINAV(:), PTGP(:,:,:), PTGPGUIDE(:,:,:)
      CHARACTER(LEN=2), ALLOCATABLE, DIMENSION(:) :: ZSYM   
      CHARACTER(LEN=4), ALLOCATABLE, DIMENSION(:) :: PTGROUP ! dimension will be NPAR
      REAL, ALLOCATABLE :: xvEX(:)  !  single precision!!!!

      DOUBLE PRECISION, ALLOCATABLE     :: PYA1bin(:,:), PYA2bin(:,:)

      ! Variables for LJGSITE keyword:
      ! LJGSITET indicates if LJGSITE keyword is in data file
      LOGICAL :: LJGSITET  
      ! Parameters for LJ potential read from data file
      DOUBLE PRECISION :: LJGSITESIGMA, LJGSITEEPS
      !BLN/Go parameters
      LOGICAL :: GOTYPE=.FALSE.
      DOUBLE PRECISION :: GOFACTOR=0D0

END MODULE COMMONS
