      SUBROUTINE EV_GAMMA(PRO_CORD,F_CORD,E,TEMPAV)

! EXCLUDED VOLUME BETWEEN GAMMA ATOMS

      USE AMHGLOBALS,  ONLY:SO, AMHMAXSIZ,MAXCRD,NMRES,PEXCLD_GAMMA, & 
           EXVMIN_GAMMA, I_TYPE_EV_GAMMA,C_OF_M_DIST

      IMPLICIT NONE

       DOUBLE PRECISION, INTENT(IN):: PRO_CORD(AMHMAXSIZ,3,MAXCRD)
       DOUBLE PRECISION, INTENT(OUT):: F_CORD(AMHMAXSIZ,3,MAXCRD),E(:,:)
      LOGICAL, INTENT(IN):: TEMPAV

      DOUBLE PRECISION :: GAMMA_CORD(AMHMAXSIZ,3),DIFF(3),DIST,FACTOR(3),XI
      INTEGER :: I,J

!     ZERO FORCE AND ENERGY

      F_CORD=0.0D0
      E=0.0D0
      
! CALCULATE GAMMA POSITIONS

      DO I=1,NMRES
        GAMMA_CORD(I,:)=PRO_CORD(I,:,1)+C_OF_M_DIST(I)*(PRO_CORD(I,:,2)-PRO_CORD(I,:,1))
      ENDDO
      
      IF (I_TYPE_EV_GAMMA.EQ.1) THEN !QUADRATIC (HARD FUNCTION)
        DO I=1,NMRES-13
        DO J=I+13,NMRES 
          DIFF(:)=GAMMA_CORD(I,:)-GAMMA_CORD(J,:)
          DIST=DSQRT( DOT_PRODUCT( DIFF,DIFF ) )
          IF (DIST.GT.EXVMIN_GAMMA(I,J)) CYCLE
          FACTOR(:)=-2.0D0*PEXCLD_GAMMA*( DIST-EXVMIN_GAMMA(I,J) )*DIFF(:)/DIST
          F_CORD(I,:,1)=F_CORD(I,:,1)+FACTOR*(1.0D0-C_OF_M_DIST(I))
          F_CORD(J,:,1)=F_CORD(J,:,1)-FACTOR*(1.0D0-C_OF_M_DIST(J))
          F_CORD(I,:,2)=F_CORD(I,:,2)+FACTOR*C_OF_M_DIST(I)
          F_CORD(J,:,2)=F_CORD(J,:,2)-FACTOR*C_OF_M_DIST(J)
          IF (TEMPAV) E(1,9)=E(1,9)+PEXCLD_GAMMA*( DIST-EXVMIN_GAMMA(I,J) )**2
        ENDDO
        ENDDO
      ELSEIF (I_TYPE_EV_GAMMA.EQ.2) THEN !TANH (SOFT FUNCTION)
        XI=0.5D0
        DO I=1,NMRES-5
        DO J=I+5,NMRES
          DIFF(:)=GAMMA_CORD(I,:)-GAMMA_CORD(J,:)
          DIST=DSQRT( DOT_PRODUCT( DIFF,DIFF ) )
          FACTOR(:)=(PEXCLD_GAMMA/(2.0D0*XI))*( COSH((EXVMIN_GAMMA(I,J)-DIST)/XI)**(-2) ) *DIFF(:)/DIST
          F_CORD(I,:,1)=F_CORD(I,:,1)+FACTOR*(1.0D0-C_OF_M_DIST(I))
          F_CORD(J,:,1)=F_CORD(J,:,1)-FACTOR*(1.0D0-C_OF_M_DIST(J))
          F_CORD(I,:,2)=F_CORD(I,:,2)+FACTOR*C_OF_M_DIST(I)
          F_CORD(J,:,2)=F_CORD(J,:,2)-FACTOR*C_OF_M_DIST(J)
          IF (TEMPAV) E(1,9)=E(1,9)+0.5D0*PEXCLD_GAMMA*(1.0D0+TANH((EXVMIN_GAMMA(I,J)-DIST)/XI))
        ENDDO
        ENDDO
      ELSEIF (I_TYPE_EV_GAMMA.EQ.3) THEN !TANH (SOFT FUNCTION MCP)
        XI=0.5D0

        DO I=1,NMRES
        GAMMA_CORD(I,:)=PRO_CORD(I,:,1)+C_OF_M_DIST(I)*(PRO_CORD(I,:,2)-PRO_CORD(I,:,1))
        ENDDO

        DO I=1,NMRES-5
        DO J=I+5,NMRES
          DIFF(:)=GAMMA_CORD(I,:)-GAMMA_CORD(J,:)
          DIST=DSQRT( DOT_PRODUCT( DIFF,DIFF ) )
          FACTOR(:)=(PEXCLD_GAMMA/(2.0D0*XI))*( COSH((EXVMIN_GAMMA(I,J)-DIST)/XI)**(-2) ) *DIFF(:)/DIST
          F_CORD(I,:,1)=F_CORD(I,:,1)+FACTOR*(1.0D0-C_OF_M_DIST(I))
          F_CORD(J,:,1)=F_CORD(J,:,1)-FACTOR*(1.0D0-C_OF_M_DIST(J))
          F_CORD(I,:,2)=F_CORD(I,:,2)+FACTOR*C_OF_M_DIST(I)
          F_CORD(J,:,2)=F_CORD(J,:,2)-FACTOR*C_OF_M_DIST(J)

          IF (TEMPAV) E(1,9)=E(1,9)+0.5D0*PEXCLD_GAMMA*(1.0D0+TANH((EXVMIN_GAMMA(I,J)-DIST)/XI))
        ENDDO
        ENDDO

!        DO I=1,NMRES
!          GAMMA_CORD(I,:)=PRO_CORD(I,:,3)
!        ENDDO

!        DO I=1,NMRES-5
!        DO J=I+5,NMRES
!          DIFF(:)=GAMMA_CORD(I,:)-GAMMA_CORD(J,:)
!          DIST=DSQRT( DOT_PRODUCT( DIFF,DIFF ) )
!          FACTOR(:)=(PEXCLD_GAMMA/(2.0D0*XI))*( COSH((EXVMIN_GAMMA(I,J)-DIST)/XI)**(-2) ) *DIFF(:)/DIST
!         F_CORD(I,:,1)=F_CORD(I,:,1)+FACTOR(:)
!          F_CORD(J,:,1)=F_CORD(J,:,1)-FACTOR(:)
!          F_CORD(I,:,2)=F_CORD(I,:,2)+FACTOR(:)
!          F_CORD(J,:,2)=F_CORD(J,:,2)-FACTOR(:)
!          IF (TEMPAV) E(1,11)=E(1,11)+0.5D0*PEXCLD_GAMMA*(1.0D0+TANH((EXVMIN_GAMMA(I,J)-DIST)/XI))
!        ENDDO
!        ENDDO

      ELSE
        WRITE(SO,*) 'I_TYPE_EV_GAMMA COCK-UP',I_TYPE_EV_GAMMA
        STOP

      ENDIF

      RETURN
      END
