
C     --------------------- HPROFL ----------------------

      SUBROUTINE HPROFL(AMHMAXSIZ,NMRES,IRES,HYDSEQ,HYDSCL)

C     ---------------------------------------------------

C     HPROFL SET HYDROPHOBICITY PROFILE FOR CODED AMINO
C            ACID SEQUENCE IN THE ARRAY IRES

C     ARGUMENTS:

C        AMHMAXSIZ- MAXIMUM PROTEIN LENGTH (I)
C        NMRES - LENGTH OF CURRENT PROTEIN (I)
C        IRES  - CODED AMINO ACID SEQUENCE (I)
C        HYDSEQ- HYDROPHOBICITY PROFILE (O)
C        HYDSCL- HYDROPHOBICITY SCALE (I)

C     ---------------------------------------------------

C     SET REQUIRED PARAMETERS

      IMPLICIT NONE

C     ARGUMENT DECLARATIONS:

         INTEGER AMHMAXSIZ,NMRES,IRES(AMHMAXSIZ)

         DOUBLE PRECISION HYDSEQ(AMHMAXSIZ),HYDSCL(0:21)

C     INTERNAL VARIABLES:

         INTEGER I500,I501
     
C     --------------------- BEGIN -----------------------

C     SET HYDROPHOBICITY PROFILE

C     PUT H VALUE FROM ARRAY HYDSCL IN 'UTILITY'

      DO 500 I500=1,NMRES
         HYDSEQ(I500)=HYDSCL(IRES(I500))
  500 CONTINUE

C     TRANSLATE H VALUES TO BINARY SCALE

      DO 501 I501=1,NMRES
         IF( HYDSEQ(I501).LT.0.0 )THEN
            HYDSEQ(I501)=-1.0
         ELSEIF( HYDSEQ(I501).GT.0.0 )THEN
            HYDSEQ(I501)=1.0
         ENDIF
  501 CONTINUE

C     ---------------------- DONE -----------------------

      RETURN
      END
