MODULE BOWMANWATER

IMPLICIT NONE

CONTAINS

SUBROUTINE BOWMANINIT(NW, PES, DNAME)
USE PES_SHELL, ONLY : IWATERFCN, PES_INIT
INTEGER, INTENT(IN) :: NW, PES
CHARACTER (LEN=*), INTENT(IN) :: DNAME
CALL PES_INIT(NW, DNAME)
IWATERFCN = PES
END SUBROUTINE BOWMANINIT

DOUBLE PRECISION FUNCTION BOWMANPOT(X)
USE PES_SHELL, ONLY : F, AUANG
DOUBLE PRECISION, DIMENSION(:), INTENT(IN) :: X
REAL, DIMENSION(:,:), ALLOCATABLE :: XX
INTEGER :: NATOM, I
NATOM = SIZE(X) / 3
ALLOCATE(XX(3,NATOM))
FORALL(I=1:NATOM) XX(:,I) = X(3*I-2:3*I) / AUANG
BOWMANPOT = F(XX)
DEALLOCATE(XX)
END FUNCTION BOWMANPOT

END MODULE  BOWMANWATER
