#!/bin/bash

queue_name="s1"
add_opts="-q $queue_name"

check_max_num=0

force_min=0.0
force_max=0.01
force_max=0.02
force_i=0.001

case "$1" in
	  	-h) 
cat << EOF
SCRIPT NAME: 	rr0
USAGE: rr0 OPTS
OPTS:	
	-f f_min f_max f_incr 
	-q queue
	-m max_num
EOF
exit
;;
	  	-f)  
			force_min=$2; force_max=$3; force_i=$4
			;;
		-q) 	
			queue_name=$2 
			add_opts="$add_opts -q $queue_name"
			;;
		-m) 
			max_num=$2
			check_max_num=1 
			;;
esac	 

source define_forces_0.sh

let i=0
for f in ${forces[@]}
	do
		rr 0 -force $f -ap $add_opts 
		sleep 3
		cp data.old data.G46
		i=$(($i+1))

		#if [ [  $i -ge $max_num ] && [ $check_max_num -eq 1 ] ]; then
			  #break	
		#fi
done
