SUBROUTINE READ_CMD_ARGS

USE PORFUNCS
!USE COMMONS,ONLY : INFILE

IMPLICIT NONE

INTEGER NARGS, I
CHARACTER(LEN=80) BFF

! EXTERNAL DISPLAY_VERSION

CALL IARGC_SUBR(NARGS)    
I=0

DO WHILE(I.LT.NARGS) ; I=I+1 ; CALL GETARG_SUBR(I,BFF) !
   SELECTCASE(BFF)
   CASE('-v') 
      CALL DISPLAY_VERSION(0)
      STOP
   !case(-hk)
      !call display_keyword_help()
   ENDSELECT
ENDDO

!IF (NARGS.GT.0) INFILE=TRIM(ADJUSTL(BFF))

END SUBROUTINE READ_CMD_ARGS
