SUBROUTINE SETUPAMB(FILENAME)
IMPLICIT NONE
        CHARACTER(*) :: FILENAME
        WRITE(*,*) 'SF344> SHOULDN`T BE IN THIS ROUTINE!  COMPILED CORRECTLY?'
END SUBROUTINE SETUPAMB

SUBROUTINE AMBERINTERFACE(DUMMY1,DUMMY2)
IMPLICIT NONE
        INTEGER         :: DUMMY1, DUMMY2

END SUBROUTINE AMBERINTERFACE

SUBROUTINE AMBER_READCOORDS(OSTRING)
IMPLICIT NONE
CHARACTER(LEN=20) OSTRING

END SUBROUTINE AMBER_READCOORDS

SUBROUTINE AMBERFINALIO(NSAVE,NUNIT,OSTRING,FILTH,COORDS2)
IMPLICIT NONE

INTEGER NSAVE,NUNIT,FILTH
CHARACTER(LEN=80) OSTRING
DOUBLE PRECISION COORDS2(*)

END SUBROUTINE AMBERFINALIO

SUBROUTINE AMBERSECDER(OLDX,STEST)
IMPLICIT NONE
DOUBLE PRECISION  :: OLDX(*)
LOGICAL    :: STEST
END SUBROUTINE AMBERSECDER

SUBROUTINE AMBERENERGIES(Y,GRAD,EREAL,GRADT,STEST)
IMPLICIT NONE
DOUBLE PRECISION :: Y(*),GRAD(*),EREAL
LOGICAL          :: GRADT,STEST

END SUBROUTINE AMBERENERGIES

SUBROUTINE CHECK_CISTRANS_RNA(COORDS,NATOMS,ATOMLABELS,GOODSTRUCTURE)
IMPLICIT NONE

INTEGER,INTENT(IN) :: NATOMS
CHARACTER(LEN=5),INTENT(IN) :: ATOMLABELS(NATOMS)
DOUBLE PRECISION,INTENT(IN) :: COORDS(3*NATOMS)
LOGICAL,INTENT(OUT) :: GOODSTRUCTURE

END SUBROUTINE CHECK_CISTRANS_RNA

SUBROUTINE CHECK_CISTRANS_DNA(COORDS,NATOMS,ATOMLABELS,GOODSTRUCTURE)
IMPLICIT NONE

INTEGER,INTENT(IN) :: NATOMS
CHARACTER(LEN=5),INTENT(IN) :: ATOMLABELS(NATOMS)
DOUBLE PRECISION,INTENT(IN) :: COORDS(3*NATOMS)
LOGICAL,INTENT(OUT) :: GOODSTRUCTURE

END SUBROUTINE CHECK_CISTRANS_DNA


SUBROUTINE MME2WRAPPER(COORDS,ENERGY,VNEW,TEMPHESS,ATMASS,GRAD1)
IMPLICIT NONE

DOUBLE PRECISION COORDS(*),ENERGY,VNEW(*),TEMPHESS(*),ATMASS(*),GRAD1(*)

END SUBROUTINE MME2WRAPPER

SUBROUTINE MMEINITWRAPPER(PRMTOP,IGB,SALTCON,RGBMAX,CUT)
IMPLICIT NONE

CHARACTER       :: PRMTOP
INTEGER         :: IGB
DOUBLE PRECISION :: SALTCON,RGBMAX,CUT

END SUBROUTINE MMEINITWRAPPER

SUBROUTINE CHECK_CISTRANS_PROTEIN(COORDS,NATOMS,GOODSTRUCTURE,MINOMEGA,CISARRAY)
IMPLICIT NONE

! STUFF FOR DETECTING CIS-TRANS ISOMERISATION OF OMEGA ANGLES IN PEPTIDE BONDS
LOGICAL,INTENT(OUT) :: GOODSTRUCTURE
INTEGER,INTENT(IN) :: NATOMS
DOUBLE PRECISION,INTENT(IN) :: COORDS(3*NATOMS),MINOMEGA
INTEGER :: CISARRAY(NATOMS)

END SUBROUTINE CHECK_CISTRANS_PROTEIN

SUBROUTINE CHECK_CHIRALITY(COORDS,NATOMS,GOODSTRUCTURE)
IMPLICIT NONE

INTEGER,INTENT(IN) :: NATOMS
DOUBLE PRECISION,INTENT(IN) :: COORDS(3*NATOMS)
LOGICAL :: GOODSTRUCTURE
END SUBROUTINE CHECK_CHIRALITY

SUBROUTINE AMBER_DEALLOCATE_STACKS()

END SUBROUTINE AMBER_DEALLOCATE_STACKS

SUBROUTINE TAKESTEPAMBER(NP)
IMPLICIT NONE
INTEGER NP
END SUBROUTINE TAKESTEPAMBER


SUBROUTINE  AMBERDIHEDR(Q,NATOMS,I,J,K,L,ORDER)
IMPLICIT NONE
DOUBLE PRECISION Q(*),ORDER
INTEGER NATOMS,I,J,K,L
PRINT*,'ERROR IN AMBERDIHEDR - THIS DUMMY ROUTINE SHOULD NEVER BE CALLED - WRONG EXECUTABLE?'
RETURN
END


SUBROUTINE  GETSEEDATM(DUMMY1,DUMMY2,DUMMY3,AT1,AT2,AT3,IRES)

CHARACTER :: DUMMY1, DUMMY2, DUMMY3
INTEGER :: AT1, AT2, AT3, IRES

END SUBROUTINE GETSEEDATM

SUBROUTINE GETICCOORDS()

END SUBROUTINE GETICCOORDS

SUBROUTINE CHECK_SIDECHAIN(I3,J3,K3,L3,IICD,IS_SIDECHAIN)
INTEGER :: I3,J3,K3,L3,IICD
LOGICAL :: IS_SIDECHAIN(100)

END SUBROUTINE CHECK_SIDECHAIN

SUBROUTINE CHGETICVAL(Q,BOND1, BOND2, THET1, THET2, PHI, DIHED_ONLY)
DOUBLE PRECISION :: Q(3*5000), BOND1(5000), BOND2(5000), THET1(5000)
DOUBLE PRECISION :: THET2(5000), PHI(5000)
LOGICAL :: DIHED_ONLY
END SUBROUTINE CHGETICVAL

DOUBLE PRECISION FUNCTION PHI_INTERP(ST_PHI,FI_PHI,SFRAC)
DOUBLE PRECISION:: ST_PHI,FI_PHI,PHI,SFRAC
END FUNCTION PHI_INTERP

DOUBLE PRECISION FUNCTION PROBABIL(X, XMAX, CHPMAX,CHPMIN, MAX_X_FUNC, SLOPE_PAR)
DOUBLE PRECISION :: CHPMAX, CHPMIN
INTEGER :: X, XMAX, MAX_X_FUNC, SLOPE_PAR
END FUNCTION PROBABIL

SUBROUTINE  TAKESTEPAMDIHED(COORDS, CSTART, CFINISH,SFRAC)
DOUBLE PRECISION :: COORDS(3*5000), CSTART(3*5000), CFINISH(3*5000), SFRAC
END SUBROUTINE TAKESTEPAMDIHED

SUBROUTINE SETDIHEAM()
END SUBROUTINE SETDIHEAM

SUBROUTINE ICTYPECHECKAM(LPHIPSI,LOMEGAC,LSIDECHAIN, LCHIRAL,IICD)
LOGICAL:: LPHIPSI,LOMEGAC,LSIDECHAIN,LCHIRAL
INTEGER :: IICD
END SUBROUTINE ICTYPECHECKAM

SUBROUTINE GET_TWISTABLE(ST_PHI, FI_PHI)
DOUBLE PRECISION:: ST_PHI(3000), FI_PHI(3000)
END SUBROUTINE GET_TWISTABLE

SUBROUTINE CHARMMBILDC(NSTART,NSTOP,Q, BOND1,BOND2,THET1,THET2,PIC)
INTEGER::NSTART,NSTOP
DOUBLE PRECISION ::Q(3*5000), BOND1(5000), BOND2(5000), THET1(5000)
DOUBLE PRECISION :: THET2(5000), PIC(5000)
END SUBROUTINE CHARMMBILDC

SUBROUTINE  CHREBUILD(Q, BOND1, BOND2, THET1, THET2, PIC)
DOUBLE PRECISION :: Q(3*5000), BOND1(5000), BOND2(5000), THET1(5000)
DOUBLE PRECISION :: THET2(5000), PIC(5000)
END SUBROUTINE CHREBUILD

SUBROUTINE TAKESTEPAMM(Q, DEBUG, BHSTEPSIZE)
DOUBLE PRECISION :: Q(3*5000)
LOGICAL :: DEBUG
DOUBLE PRECISION :: BHSTEPSIZE
END SUBROUTINE TAKESTEPAMM

SUBROUTINE PERTDIHAM(Q,CHPMIN,CHPMAX,CHNMIN,CHNMAX,ISEED, DEBUG, BHSTEPSIZE)
DOUBLE PRECISION :: Q(3*5000)
INTEGER::  CHNMIN,CHNMAX,ISEED, CHPMIN,CHPMAX
LOGICAL :: DEBUG
DOUBLE PRECISION :: BHSTEPSIZE
END SUBROUTINE  PERTDIHAM

!SUBROUTINE AMBALIGNDIH(PHI,DIHC,RELPHI,PREVRELPHI,N)
!DOUBLE PRECISION::PHI, RELPHI, PREVRELPHI, DRP, PHIORIG
!INTEGER:: DIHC, N
!END SUBROUTINE AMBALIGNDIH

!SUBROUTINE AMBGETOUTOFPLANE(I, J, K, L, PHI, DPDI, DPDJ, DPDK, DPDL, NOCOOR,NODERV)
!DOUBLE PRECISION:: I(0:2), J(0:2), K(0:2), L(0:2), PHI
!DOUBLE PRECISION:: DPDI(0:2), DPDJ(0:2), DPDK(0:2), DPDL(0:2)
!LOGICAL:: NOCOOR, NODERV
!END SUBROUTINE AMBGETOUTOFPLANE

!SUBROUTINE AMBGETANGLE(I, J, K, THETA, DTDI, DTDJ, DTDK, NOCOOR,NODERV)
!LOGICAL:: NOCOOR,NODERV
!DOUBLE PRECISION:: I(3), J(3), K(3), THETA
!DOUBLE PRECISION:: DTDI(3), DTDJ(3), DTDK(3)
!END SUBROUTINE AMBGETANGLE

!SUBROUTINE AMBGETTORSION(I, J, K, L, PHI, DPDI, DPDJ, DPDK, DPDL, NOCOOR, NODERV)
!LOGICAL:: NOCOOR, NODERV
!DOUBLE PRECISION:: I(3), J(3), K(3), L(3), PHI
!DOUBLE PRECISION:: DPDI(3), DPDJ(3), DPDK(3), DPDL(3)
!END SUBROUTINE AMBGETTORSION

!SUBROUTINE AMB_GETKDNAT(KD)
!INTEGER::KD
!END SUBROUTINE AMB_GETKDNAT

!SUBROUTINE AMBGETNNZNAT(NNZ)
!INTEGER::NNZ
!END SUBROUTINE AMBGETNNZNAT

!SUBROUTINE AMBTRANSFORM(XCART,GCART,XINT,GINT,NINTC,NCART,NNZ,NOCOOR,NODERV,KD,INTEPSILON)
!INTEGER:: NNZ,NINTC,NCART,KD
!DOUBLE PRECISION:: XCART(3*MXATMS),GCART(3*MXATMS),XINT(NINTC),GINT(NINTC)
!DOUBLE PRECISION:: INTEPSILON
!LOGICAL:: NOCOOR, NODERV
!END SUBROUTINE AMBTRANSFORM

!SUBROUTINE AMB_TRANSBACKDELTA(X,CARTX,COORDS,NINTC,NCART,NNZ,KD,FAILED,PTEST2,INTEPSILON)
!DOUBLE PRECISION INTEPSILON,CARTX(NCART),X(NINTC),COORDS(3*NATOM)
!INTEGER NNZ,NINTC,NCART
!LOGICAL PTEST2,FAILED
!END SUBROUTINE AMB_TRANSBACKDELTA

SUBROUTINE CHECK_VALLEU_CHIRALITY(COORDSB, COORDSA,DEBUG)
DOUBLE PRECISION :: COORDSB(:), COORDSA(:)
LOGICAL :: DEBUG
END SUBROUTINE CHECK_VALLEU_CHIRALITY

SUBROUTINE VALLEU_SWAP(COORDSB,COORDSA,I1,I4, DEBUG)
DOUBLE PRECISION, INTENT(IN):: COORDSB(:)
DOUBLE PRECISION, INTENT(INOUT) :: COORDSA(:)
INTEGER, INTENT(IN) ::I1,I4
LOGICAL :: DEBUG
END SUBROUTINE VALLEU_SWAP

SUBROUTINE A9RESTOATOM(FROZENRES,FROZEN,NFREEZE)
INTEGER I1, RESNUMBER, CURRENTRESIDUE,NFREEZE
LOGICAL FROZENRES(:), FROZEN(:)

END SUBROUTINE A9RESTOATOM

SUBROUTINE A9ATOMTORES(ATOM,RESIDUE)
INTEGER, INTENT(IN) :: ATOM
INTEGER, INTENT(OUT) :: RESIDUE
INTEGER :: I1, RESNUMBER,CURRENTRESIDUE

END SUBROUTINE A9ATOMTORES

SUBROUTINE A9DUMPMODES(DIAG,ZT,N,M)
INTEGER :: N,M
DOUBLE PRECISION :: DIAG(M)
LOGICAL :: ZT(M)

END SUBROUTINE A9DUMPMODES


!      SUBROUTINE GET_TWISTABLE(ST_PHI,FI_PHI)
!      IMPLICIT NONE
!      DOUBLE PRECISION ST_PHI(*), FI_PHI(*)
!
!      PRINT*,'ERROR - THIS DUMMY ROUTINE SHOULD NEVER BE CALLED - WRONG EXECUTABLE?'
!      STOP
!
!      RETURN
!      END

 !     SUBROUTINE TAKESTEPAMM(Q,DEBUG, BHSTEPSIZE)
 !     IMPLICIT NONE
 !     DOUBLE PRECISION Q(*), BHSTEPSIZE
 !     LOGICAL             DEBUG
 !
 !     PRINT*,'ERROR - THIS DUMMY ROUTINE SHOULD NEVER BE CALLED - WRONG EXECUTABLE?'
 !     STOP
 !
 !     RETURN
 !     END

