C   OPTIM: A PROGRAM FOR OPTIMIZING GEOMETRIES AND CALCULATING REACTION PATHWAYS
C   COPYRIGHT (C) 1999-2006 DAVID J. WALES
C   THIS FILE IS PART OF OPTIM.
C
C   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C   (AT YOUR OPTION) ANY LATER VERSION.
C
C   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
C   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
C   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
C   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
C
      SUBROUTINE APARAMS
      IMPLICIT NONE

      PRINT*,'ERROR - THIS DUMMY ROUTINE SHOULD NEVER BE CALLED - WRONG EXECUTABLE?'
      STOP
 
      RETURN
      END

      SUBROUTINE AREAD
      IMPLICIT NONE

      PRINT*,'ERROR - THIS DUMMY ROUTINE SHOULD NEVER BE CALLED - WRONG EXECUTABLE?'
      STOP
 
      RETURN
      END

      SUBROUTINE AMB(XVEC,GRAD,EREAL,GRADT,SECT)
      IMPLICIT NONE
      DOUBLE PRECISION XVEC(*), GRAD(*), EREAL
      LOGICAL GRADT, SECT

      PRINT*,'ERROR - THIS DUMMY ROUTINE SHOULD NEVER BE CALLED - WRONG EXECUTABLE?'
      STOP

      RETURN
      END

      SUBROUTINE AMOVIEDUMP(FRAME)
      IMPLICIT NONE
      INTEGER FRAME

      PRINT*,'ERROR - THIS DUMMY ROUTINE SHOULD NEVER BE CALLED - WRONG EXECUTABLE?'
      STOP

      RETURN
      END
