! **************************************************************************
     
      SUBROUTINE AMB_GETKDNAT(KD)
!GET WIDTH OF DIAGONAL FOR GCS MATRIX, FOR NATURAL INTERNALS
!FOR NOW, ASSUME THE DIHEDRALS OR BONDS GIVE THE MAXIMUM WIDTH
      USE MODAMBER9


      INTEGER KD,ATOMWIDTH,DIFF,IPHI
      INTEGER I,J,K,L
!
      ATOMWIDTH=0
      DIFF=0
      DO IPHI=1,NPHIA
        I=IX(I50+IPHI)/3 + 1
        J=IX(I52+IPHI)/3 + 1
        K=IABS(IX(I54+IPHI))/3 + 1
        L=IABS(IX(I56+IPHI))/3 + 1
!     PRINT *,'PDIHE I J K L',I,J,K,L
        DIFF=ABS(I-J)
        IF (DIFF.GT.ATOMWIDTH) ATOMWIDTH=DIFF
        DIFF=ABS(I-K)
        IF (DIFF.GT.ATOMWIDTH) ATOMWIDTH=DIFF
        DIFF=ABS(I-L)
        IF (DIFF.GT.ATOMWIDTH) ATOMWIDTH=DIFF
        DIFF=ABS(J-K)
        IF (DIFF.GT.ATOMWIDTH) ATOMWIDTH=DIFF
        DIFF=ABS(J-L)
        IF (DIFF.GT.ATOMWIDTH) ATOMWIDTH=DIFF
        DIFF=ABS(K-L)
        IF (DIFF.GT.ATOMWIDTH) ATOMWIDTH=DIFF
      ENDDO
      DO IPHI=1,NPHIH
        I=IX(I40+IPHI)/3 + 1
        J=IX(I42+IPHI)/3 + 1
        K=IABS(IX(I44+IPHI))/3 + 1
        L=IABS(IX(I46+IPHI))/3 + 1
!     PRINT *,'PDIHE I J K L',I,J,K,L
        DIFF=ABS(I-J)
        IF (DIFF.GT.ATOMWIDTH) ATOMWIDTH=DIFF
        DIFF=ABS(I-K)
        IF (DIFF.GT.ATOMWIDTH) ATOMWIDTH=DIFF
        DIFF=ABS(I-L)
        IF (DIFF.GT.ATOMWIDTH) ATOMWIDTH=DIFF
        DIFF=ABS(J-K)
        IF (DIFF.GT.ATOMWIDTH) ATOMWIDTH=DIFF
        DIFF=ABS(J-L)
        IF (DIFF.GT.ATOMWIDTH) ATOMWIDTH=DIFF
        DIFF=ABS(K-L)
        IF (DIFF.GT.ATOMWIDTH) ATOMWIDTH=DIFF
      ENDDO

      IF(.NOT.ALLOCATED(IBIB)) THEN
         PRINT*, "IB GOING WRONG!"
         ALLOCATE(IBIB(NBONA+NBONH))
         DO I =1,NBONA
            IBIB(I) = IX(IIBA+I-1)/3+1
         ENDDO
         DO I=1, NBONH
            IBIB(NBONA+I) = IX(IIBH+I-1)/3+1
         ENDDO
      ENDIF

      IF(.NOT.ALLOCATED(JBJB)) THEN
          ALLOCATE(JBJB(NBONA+NBONH))
          DO I =1,NBONA
             JBJB(I) = IX(IJBA+I-1)/3+1
          ENDDO
          DO I=1, NBONH
             JBJB(NBONA+I) = IX(IJBH+I-1)/3+1
          ENDDO
      ENDIF

      DO IPHI = 1,NBONA+NBONH
         I = IBIB(IPHI)
         J = JBJB(IPHI)
         DIFF=ABS(I-J)
         IF (DIFF.GT.ATOMWIDTH) ATOMWIDTH=DIFF
      ENDDO
!
      KD=3*ATOMWIDTH+2
!     PRINT *,'AMB_GETKDNAT> ',KD
!
      RETURN
      END


! ***************************************************************************

      SUBROUTINE AMBGETANGLE(I, J, K, THETA, DTDI, DTDJ, DTDK, NOCOOR,NODERV)
! GIVEN THE COORDINATES FOR THREE ATOMS I, J, K
! FIND THE ANGLE WITH J AS THE CENTRAL ATOM; RETURN IT IN THETA
! ALSO RETURN ALL DERIVATIVES: DT/DIX, DT/DIY, DT/DIZ IN TRIPLET DTDI
!SAME WITH DTDJ AND DTDK

      LOGICAL NOCOOR,NODERV
      DOUBLE PRECISION I(3), J(3), K(3), THETA
      DOUBLE PRECISION DTDI(3), DTDJ(3), DTDK(3)
      DOUBLE PRECISION DXI, DYI, DZI, DXJ, DYJ, DZJ, RI2, RJ2, RI, RJ, RIR, RJR
      DOUBLE PRECISION DXIR, DYIR, DZIR, DXJR, DYJR, DZJR, CST, ISNT

      DXI=I(1)-J(1)
      DYI=I(2)-J(2)
      DZI=I(3)-J(3)
      DXJ=K(1)-J(1)
      DYJ=K(2)-J(2)
      DZJ=K(3)-J(3)
      RI2=DXI*DXI+DYI*DYI+DZI*DZI
      RJ2=DXJ*DXJ+DYJ*DYJ+DZJ*DZJ
      RI=SQRT(RI2)
      RJ=SQRT(RJ2)
      RIR=1/RI
      RJR=1/RJ
      DXIR=DXI*RIR
      DYIR=DYI*RIR
      DZIR=DZI*RIR
      DXJR=DXJ*RJR
      DYJR=DYJ*RJR
      DZJR=DZJ*RJR
      
      CST=DXIR*DXJR+DYIR*DYJR+DZIR*DZJR
      IF (.NOT.NOCOOR) THETA = ACOS(CST)

      IF (.NOT.NODERV) THEN
      ISNT=1/SQRT(1-CST*CST)
      DTDI(1)=(DXIR*CST-DXJR)*RIR*ISNT
      DTDI(2)=(DYIR*CST-DYJR)*RIR*ISNT
      DTDI(3)=(DZIR*CST-DZJR)*RIR*ISNT
      DTDJ(1)=(DXIR*(RI-RJ*CST)+DXJR*(RJ-RI*CST))*RIR*RJR*ISNT
      DTDJ(2)=(DYIR*(RI-RJ*CST)+DYJR*(RJ-RI*CST))*RIR*RJR*ISNT
      DTDJ(3)=(DZIR*(RI-RJ*CST)+DZJR*(RJ-RI*CST))*RIR*RJR*ISNT
      DTDK(1)=(DXJR*CST-DXIR)*RJR*ISNT
      DTDK(2)=(DYJR*CST-DYIR)*RJR*ISNT
      DTDK(3)=(DZJR*CST-DZIR)*RJR*ISNT
      ENDIF

      RETURN
      END SUBROUTINE

      SUBROUTINE AMBGETOUTOFPLANE(I, J, K, L, PHI, DPDI, DPDJ, DPDK, DPDL, NOCOOR,NODERV)
!EFK:
!GIVEN THE COORDINATES FOR FOUR ATOMS I, J, K, L WITH I THE CENTRAL ATOM
!FIND THE ANGLE BETWEEN J AND THE PLANE DEFINED BY I,K,L; RETURN IT IN PHI
!ALSO RETURN ALL DERIVATIVES: DP/DIX, DP/DIY, DP/DIZ IN TRIPLET DPDI
!SAME WITH DPDJ, DPDK, AND DPDL
!CALCULATIONS FROM WILSON, DELCIUS, AND CROSS (WDC) CH.4
!
      LOGICAL NOCOOR, NODERV
      DOUBLE PRECISION I(0:2), J(0:2), K(0:2), L(0:2), PHI
      DOUBLE PRECISION DPDI(0:2), DPDJ(0:2), DPDK(0:2), DPDL(0:2)
      DOUBLE PRECISION JIX, JIY, JIZ, KIX, KIY, KIZ, LIX, LIY, LIZ
      DOUBLE PRECISION RJI2, RKI2, RLI2, RJI, RKI, RLI, RJIR, RKIR, RLIR
      DOUBLE PRECISION AX, AY, AZ, BX, BY, BZ, CX, CY, CZ
      DOUBLE PRECISION RA2, RA, RB2, RB, RC2, RC, RCR
      DOUBLE PRECISION SNP, CSP2, CSP, CSPR, TNP, DUMMY
      INTEGER X

!GET VECTOR DIFFERENCES
      JIX=J(0)-I(0) ! R41 IN WDC
      JIY=J(1)-I(1)
      JIZ=J(2)-I(2)
      KIX=K(0)-I(0) ! R42 IN WDC
      KIY=K(1)-I(1)
      KIZ=K(2)-I(2)
      LIX=L(0)-I(0) ! R43 IN WDC
      LIY=L(1)-I(1)
      LIZ=L(2)-I(2)
!GET VECTOR NORMS
      RJI2 = JIX*JIX+JIY*JIY+JIZ*JIZ
      RKI2 = KIX*KIX+KIY*KIY+KIZ*KIZ
      RLI2 = LIX*LIX+LIY*LIY+LIZ*LIZ
      RJI = SQRT(RJI2)
      RKI = SQRT(RKI2)
      RLI = SQRT(RLI2)
      RJIR = 1/RJI
      RKIR = 1/RKI
      RLIR = 1/RLI
!GET A = R41 X R42
      AX = JIY*KIZ-KIY*JIZ
      AY = -JIX*KIZ+KIX*JIZ
      AZ = JIX*KIY-KIX*JIY
!GET B = R43 X R41
      BX = LIY*JIZ-JIY*LIZ
      BY = -LIX*JIZ +JIX*LIZ
      BZ = LIX*JIY-JIX*LIY
!GET C = R42 X R43
      CX = KIY*LIZ-LIY*KIZ
      CY = -KIX*LIZ+LIX*KIZ
      CZ = KIX*LIY-LIX*KIY
      RC2 = CX*CX+CY*CY+CZ*CZ
      RC = SQRT(RC2)
      RCR = 1/RC
!SIN(PHI1) = |R42 X R43| / (|R42| *|R43|)
!DUMMY = (R42 X R43)*R41
      DUMMY = CX*JIX+CY*JIY+CZ*JIZ
!SIN(PHI) = DUMMY / (SIN(PHI1) * |R42||R43||R41|)
      SNP = DUMMY * RCR*RJIR 
!NOTE: POSSIBLE BUG; MAY RUN INTO PROBLEMS IF ANGLE OVER 90 DEGREES
!SHOULD FIX THIS LATER
      IF (.NOT.NOCOOR) PHI = ASIN(SNP)

      IF (NODERV) RETURN

!CALCULATE DERIVATIVES FOR B MATRIX
      CSP2 = 1-SNP*SNP
      CSP = SQRT(CSP2) !COS(PHI)
      CSPR = 1/CSP !SEC(PHI)
      TNP = SNP*CSPR !TAN(PHI)
!POTENTIAL BUG: SINGULARITY AT PHI->PI/2
!
      DPDJ(0) = RJIR*(CX*CSPR*RCR - JIX*TNP*RJIR)
      DPDJ(1) = RJIR*(CY*CSPR*RCR - JIY*TNP*RJIR)
      DPDJ(2) = RJIR*(CZ*CSPR*RCR - JIZ*TNP*RJIR)
!
!CONTINUE CHECKING WITH 2ND TERM HERE....
      DUMMY = LIX*KIX+LIY*KIY+LIZ*KIZ !R43*R42
      DPDK(0) = BX*CSPR*RCR*RJIR - KIX*TNP*RLI2*RCR*RCR &
     &     + LIX*TNP*DUMMY*RCR*RCR
      DPDK(1) = BY*CSPR*RCR*RJIR - KIY*TNP*RLI2*RCR*RCR &
     &     + LIY*TNP*DUMMY*RCR*RCR
      DPDK(2) = BZ*CSPR*RCR*RJIR - KIZ*TNP*RLI2*RCR*RCR &
     &     + LIZ*TNP*DUMMY*RCR*RCR
!    
      DPDL(0) = AX*CSPR*RCR*RJIR - LIX*TNP*RKI2*RCR*RCR &
     &     + KIX*TNP*DUMMY*RCR*RCR
      DPDL(1) = AY*CSPR*RCR*RJIR - LIY*TNP*RKI2*RCR*RCR &
     &     + KIY*TNP*DUMMY*RCR*RCR
      DPDL(2) = AZ*CSPR*RCR*RJIR - LIZ*TNP*RKI2*RCR*RCR &
     &     + KIZ*TNP*DUMMY*RCR*RCR
!
      DO X = 0,2
         DPDI(X) = -DPDJ(X)-DPDK(X)-DPDL(X)
      ENDDO
!
      RETURN
      END

      SUBROUTINE AMBGETTORSION(I, J, K, L, PHI, DPDI, DPDJ, DPDK, DPDL, NOCOOR, NODERV)
!GIVEN THE COORDINATES FOR FOUR ATOMS I, J, K, L, BOUND IN ORDER, 
!FIND THE DIHEDRAL TORSION ANGLE; RETURN IT IN PHI
!ALSO RETURN ALL DERIVATIVES: DP/DIX, DP/DIY, DP/DIZ IN TRIPLET DPDI
!SAME WITH DPDJ, DPDK, AND DPDL

      LOGICAL NOCOOR, NODERV
      DOUBLE PRECISION I(3), J(3), K(3), L(3), PHI
      DOUBLE PRECISION DPDI(3), DPDJ(3), DPDK(3), DPDL(3)
      DOUBLE PRECISION FX, FY, FZ, GX, GY, GZ, HX, HY, HZ
      DOUBLE PRECISION AX, AY, AZ, BX, BY, BZ
      DOUBLE PRECISION RF, RG, RH, RF2, RG2, RH2, RFR, RGR, RHR
      DOUBLE PRECISION CSTTWO, SNTTWO2, CSTTHREE, SNTTHREE2, SNTTWO2R, SNTTHREE2R
      DOUBLE PRECISION RA2, RB2, RA2R, RB2R, RABR, CP
      DOUBLE PRECISION MYTX, MYTY, MYTZ, MYSCALAR
      DOUBLE PRECISION DUMMY, DUMMY2

      FX=I(1)-J(1)
      FY=I(2)-J(2)
      FZ=I(3)-J(3)
      GX=J(1)-K(1)
      GY=J(2)-K(2)
      GZ=J(3)-K(3)
      HX=L(1)-K(1)
      HY=L(2)-K(2)
      HZ=L(3)-K(3)
!A=F^G, B=H^G
      AX=FY*GZ-FZ*GY
      AY=FZ*GX-FX*GZ
      AZ=FX*GY-FY*GX
      BX=HY*GZ-HZ*GY
      BY=HZ*GX-HX*GZ
      BZ=HX*GY-HY*GX
!RG=|G|, RGR=1/|G|
      RG2=GX*GX+GY*GY+GZ*GZ
      RG=SQRT(RG2)
      RGR=1/RG
!DAE FOR USE IN EVALUATING B-MATRIX
      RF2=FX*FX+FY*FY+FZ*FZ
      RF=SQRT(RF2)
      RFR=1/RF
      RH2=HX*HX+HY*HY+HZ*HZ
      RH=SQRT(RH2)
      RHR=1/RH
!    JMC        CSTTWO=(FX*GX+FY*GY+FZ*GZ)*RFR*RGR
      CSTTWO=-(FX*GX+FY*GY+FZ*GZ)*RFR*RGR
      SNTTWO2=1-CSTTWO*CSTTWO
      SNTTWO2R=1/SNTTWO2
      CSTTHREE=(HX*GX+HY*GY+HZ*GZ)*RHR*RGR
      SNTTHREE2=1-CSTTHREE*CSTTHREE
      SNTTHREE2R=1/SNTTHREE2      
!
      IF (.NOT.NOCOOR) THEN
         RA2=AX*AX+AY*AY+AZ*AZ
         RB2=BX*BX+BY*BY+BZ*BZ
         RA2R=1/RA2
         RB2R=1/RB2
         RABR=SQRT(RA2R*RB2R)
!    CP=COS(PHI)
         CP=(AX*BX+AY*BY+AZ*BZ)*RABR
         IF (CP.GT.1.0D0) THEN
            PHI=0.0D0
         ELSEIF (CP.LT.-1.0D0) THEN
            PHI=PI
         ELSE
            PHI=ACOS(CP)
         ENDIF

!    JMC TEST TO DETERMINE WHETHER THE DIHEDRAL ANGLE SHOULD BE > 0 OR < 0, FROM UNRES (INTCOR.F)
!    > 0 IF CW ROTATION FROM 2-> 1 TO 3-> 4.
         MYTX=AY*BZ-BY*AZ
         MYTY=-AX*BZ+BX*AZ
         MYTZ=AX*BY-BX*AY
         MYSCALAR=MYTX*GX+MYTY*GY+MYTZ*GZ
         IF (MYSCALAR.GT.0.0D0) PHI = -PHI
      ENDIF

      IF (NODERV) RETURN

!DAE CALCULATE B-MATRIX ELEMENTS
      DUMMY=RFR*RFR*RGR*SNTTWO2R
      DPDI = (/-AX*DUMMY, -AY*DUMMY, -AZ*DUMMY/)

      DUMMY=RFR*RFR*RGR*RGR*SNTTWO2R*(RG-RF*CSTTWO)
      DUMMY2=RHR*RGR*RGR*SNTTHREE2R*CSTTHREE
      DPDJ = (/AX*DUMMY-BX*DUMMY2, AY*DUMMY-BY*DUMMY2, AZ*DUMMY-BZ*DUMMY2/)

      DUMMY=RHR*RHR*RGR*RGR*SNTTHREE2R*(RG-RH*CSTTHREE)
      DUMMY2=RFR*RGR*RGR*SNTTWO2R*CSTTWO
      DPDK = (/-BX*DUMMY+AX*DUMMY2, -BY*DUMMY+AY*DUMMY2,-BZ*DUMMY+AZ*DUMMY2/)

      DUMMY=RHR*RHR*RGR*SNTTHREE2R
      DPDL = (/BX*DUMMY,BY*DUMMY,BZ*DUMMY/)

      RETURN
      END SUBROUTINE


!************************************************************************************************

      SUBROUTINE AMBALIGNDIH(PHI,DIHC,RELPHI,PREVRELPHI,N)
!ALIGNING DIHEDRAL ANGLES PROPERLY
!IF ALIGNDIR IS SET, AND IT'S NOT THE FIRST DIHEDRAL IN THE GROUP (N.NE.1) THEN 
!ADJUST ANGLE TO MINIMISE CHANGE IN RELATIVE DIHEDRAL TO THE FIRST IN THE GROUP
!OTHERWISE ADJUST ANGLE TO MINIMISE CHANGE FROM PREVIOUS VALUE OF SAME ANGLE

      USE INTCOMMONS, ONLY : PREVDIH, ALIGNDIR

      IMPLICIT NONE

      DOUBLE PRECISION PHI, RELPHI, PREVRELPHI, DRP, PHIORIG
      INTEGER DIHC, N
      DOUBLE PRECISION PI, TWOPI
      PARAMETER(PI=3.141592653589793D0)

      TWOPI = 2.0D0*PI
      PHIORIG = PHI

      IF (ALIGNDIR.AND.N.NE.1) THEN
         DRP = RELPHI-PREVRELPHI
         IF (DRP.GT.PI) THEN
            PHI = PHI - TWOPI
         ELSE IF (DRP.LT.-PI) THEN
            PHI = PHI + TWOPI
         ENDIF         
      ELSE
         IF (PHI-PREVDIH(DIHC).GT.PI) THEN
            PHI = PHI - TWOPI
         ELSE IF (PHI-PREVDIH(DIHC).LT.-PI) THEN
            PHI = PHI + TWOPI
         ENDIF
      ENDIF

      PREVDIH(DIHC) = PHI

      RETURN
      END SUBROUTINE


!*********************************************************************
      SUBROUTINE AMBGETNNZNAT(NNZ)
!    GET NUMBER OF NONZERO ELEMENTS IN B MATRIX, FOR NATURAL INTERNALS      
      USE COMMONS, ONLY : NATOMS
      USE INTCOMMONS, ONLY : CARTATMSTART, ATOMXPOSINC, CENTERS, NBDS,&
     &     NIMP, NFRG, NCRT, NCNT, LINDIH, RINGS, NRNG, NLDH

      IMPLICIT NONE

      INTEGER NNZ, I, NANGC, CNTTYPE, NATMSC

      NNZ = 6*NBDS+12*NIMP+18*NFRG + 3*NCRT
      DO I=1,NCNT
         CNTTYPE = CENTERS(I,0)
         IF (CNTTYPE.LT.3) THEN 
            NNZ = NNZ + ATOMXPOSINC(CNTTYPE,5,5) + 3
         ELSE IF (CNTTYPE.EQ.3) THEN
            NNZ = NNZ + ATOMXPOSINC(CNTTYPE,5,4) + 3
         ELSE IF (CNTTYPE.EQ.4.OR.CNTTYPE.EQ.5) THEN
            NNZ = NNZ + ATOMXPOSINC(CNTTYPE,2,4) + 3
         ELSE IF (CNTTYPE.EQ.6) THEN
            NNZ = NNZ + ATOMXPOSINC(CNTTYPE,1,3) + 3
         ELSE IF (CNTTYPE.EQ.7) THEN
            NNZ = NNZ + ATOMXPOSINC(CNTTYPE,1,4) + 3
         ELSE IF (CNTTYPE.EQ.8) THEN
            NNZ = NNZ +ATOMXPOSINC(CNTTYPE,4,5) +3
!    ELSE IF (CNTTYPE.EQ.8) THEN
!    NNZ = NNZ + ATOMXPOSINC(3,4,4) + 3
!    ELSE IF (CNTTYPE.EQ.9) THEN
!    NNZ = NNZ + ATOMXPOSINC(2,4,5) + 3
         ENDIF
      ENDDO
      DO I=1,NRNG
         IF(RINGS(I,6).EQ.-1) THEN
            NNZ = NNZ + 3*5*4
         ELSE
            NNZ = NNZ + 3*6*6
         ENDIF
      ENDDO
      DO I=1,NLDH
         NNZ = NNZ + 6 + 3*(LINDIH(I,-1)+LINDIH(I,0))
      ENDDO
!     PRINT*, 'GETNNZNAT>> NONZEROS FOUND IS:', NNZ
      RETURN
      END


!***********************************************************************
!
!SUBROUTINE TO DO INTERNAL COORDINATE MANIPULATIONS USING B-MATRIX
!CALLS GETBEE TO CALCUALTE INTERNAL COORDINATES AND B-MATRIX
!THEN TRANSFORMS CARTESIAN GRADIENTS TO INTERNAL GRADIENTS
!NEMETH ET AL. JCP 113,5598(2000)
!

      SUBROUTINE AMBTRANSFORM(XCART,GCART,XINT,GINT,NINTC,NCART,NNZ,NOCOOR,NODERV,KD,INTEPSILON)
      USE MODMXATMS, ONLY: MXATMS
 
       USE SPFUNCTS, ONLY : DUMPCOORDS

       IMPLICIT NONE
!SAT: TWO IMPLICIT NONE - LINE BELOW COMMENTED!
!#INCLUDE '~/CHARMMCODE/FCM/DIMENS.FCM'
!#INCLUDE '~/CHARMMCODE/FCM/PSF.FCM'
!NNZ IS NUMBER OF NON-ZERO ELEMENTS IN B-MATRIX
!NINTC IS NUMBER OF INTERNAL COORDINATES
!NCART IS NUMBER OF CARTESIANS
!
       INTEGER NNZ,NINTC,NCART,KD,K
!
       DOUBLE PRECISION XCART(3*MXATMS),GCART(3*MXATMS),XINT(NINTC),GINT(NINTC)
       DOUBLE PRECISION VAL(NNZ)
       INTEGER INDX(NNZ),JNDX(NNZ)
       INTEGER TRANSA,M,N,DESCRA(9),I1,J1,K1,LDGCS,LDA,LDB,INFO,NRHS,LWORK,ATOMWIDTH
       DOUBLE PRECISION ALPHA,BETA,WORK(NINTC),GCS(KD+1,NCART),GCS2(2*KD+1,NCART)
       DOUBLE PRECISION INTEPSILON,GX(NCART),GY(NINTC),SUM,SUMGY2,MEANSUMGY2,GCSREAL
       CHARACTER*1 UPLO
       LOGICAL NOCOOR,LCONVERGE, NODERV
       DOUBLE PRECISION :: GCARTORIG(NCART), GNORM, GCARTINPUT(NCART)
       INTEGER :: NITS

!---------------------------------

!GET B-MATRIX AND INTERNAL COORDIANTES
!

       CALL AMB_GETBEENAT(XCART,XINT,VAL,INDX,JNDX,NINTC,NCART, NNZ,GCS2,NOCOOR,NODERV,KD)
       IF (NODERV) RETURN

       GINT(1:NINTC) = 0.0D0
!     PRINT *,'TF HERE1'
!
!VAL IS COLUMN OF NON-ZERO BEE ELEMENTS INDEXED BY INDX AND JNDX
!GCS2 = BEETBEE AS CALCULATED IN GETBEE, STORED IN SPARSE FORMAT
!NEED TO CONVERT DOUBLE SPARSE FORMAT OF GCS2 TO LAPACK UPPERDIAGONAL ONLY GCS
!KD IS NUMBER OF SUPERDIAGONALS OF GC
!SEE DPBTRF.F HTTP://WWW.NETLIB.ORG/LAPACK/DOUBLE/DPBTRF.F
!     
!MOVE TO ARRAY OF DIMENSION KD+1
       DO J1=1,KD
          DO I1=1,J1
             GCS(KD+1+I1-J1,J1)=GCS2(KD+1+I1-J1,J1)
          ENDDO
       ENDDO
       DO J1=KD+1,NCART
          DO I1=J1-KD,J1
             GCS(KD+1+I1-J1,J1)=GCS2(KD+1+I1-J1,J1)
          ENDDO
       ENDDO

!
!XINT NOW CONTAINS INTERNAL COORDINATES
!NOW NEED TO TRANSFORM GRADIENTS
!
!FORM GC = GC + EI WHERE E IS SMALL
!
       DO I1=1,NCART
          GCS(KD+1,I1)=GCS(KD+1,I1)+INTEPSILON
       ENDDO

!
!CHOLESKY DECOMPOSE GCS
!USE LAPACK ROUTINE DPBTRF
!LDGCS IS LEADING DIMENSION OF GCS
!
          UPLO='U'
          N=NCART
          LDGCS=KD+1

          CALL DPBTRF(UPLO,N,KD,GCS,LDGCS,INFO)

          IF (INFO.NE.0) PRINT*,'WARNING - AFTER DPBTRF INFO=',INFO
!     PRINT *,'TF HERE2'
!
!GCS IS NOW THE UPPER TRIANGULAR MATRIX AFTER DECOMPOSITION
!SOLVE G*GCART2=GCART FOR GCART2, WHERE G IS ORIGINAL GC(=BEETBEE)+INTEPSILON*I
!DONE USING LAPACK ROUTINE DPBTRS WITH INPUT OF THE UPPER MATRIX FROM
!CHOLESKY DECOMPOSITION
!
          NRHS=1
          LDB=NCART
          CALL DPBTRS(UPLO,N,KD,NRHS,GCS,LDGCS,GCART,LDB,INFO)
          IF (INFO.NE.0) PRINT*,'WARNING - AFTER DPBTRS INFO=',INFO

!    PRINT *,'TF HERE3'
!
!GCART IS NOW GCART2
!GINT = BEE*GCART AS FIRST APPROXIMATION
!USE DCOOMM TO DO THIS SPARSE MULTIPLICATION
!SPARSE MATRIX MULTIPLICATION ROUTINE FROM BLAS
!HTTP://MATH.NIST.GOV/~KREMINGTON/FSPBLAS/
!
       TRANSA=0
       M=NINTC
       N=1
       K=NCART
       ALPHA=1.0D0
       BETA=0.0D0
       DO I1=1,9
         DESCRA(I1)=0
       ENDDO
         DESCRA(4)=1
       LWORK=NINTC
!     PRINT *,'TF HERE3.5'
       CALL DCOOMM(TRANSA,M,N,K,ALPHA,DESCRA,VAL,INDX,JNDX,NNZ,GCART,NCART,BETA,GINT,NINTC,WORK,LWORK)
       IF (INFO.NE.0) PRINT*,'WARNING - AFTER DCOOMM INFO=',INFO

!      IF(ITERATEG) PREITGRAD(:) = GINT(:)
!     PRINT *,'TF HERE4'
!
!CAN SKIP BELOW ITERATION AND USE THIS FIRST APPROXIMATION
!
!PRINT OUT GINT
!     DO I1=1,NINTC
!      PRINT *,'GINT',GINT(I1)
!     ENDDO
!C
!NOW ITERATE GINT
!GINT(K+1)=GINT(K)+AT(GRAD-BEET*GINT(K))
!MULTIPLICATION AT*GX IS THE SAME AS SOLVING G*GCART2=GX
!C
!     PRINT *,'TRANSFORM HERE4'
!      LCONVERGE = .FALSE.
!      NITS = 0
!      IF (ITERATEG) THEN
!         DO WHILE (.NOT.LCONVERGE)
!    GX=BEET*GINT
!GX=GCART-GX
!            TRANSA=1
!            M=NINTC; N = 1; K = NCART
!            ALPHA=1.0D0
!            BETA=0.0D0
!            DO I1=1,9
!               DESCRA(I1)=0
!            ENDDO
!            DESCRA(4)=1
!            LWORK=NINTC
!            GX(:) = 0.0D0
!            CALL DCOOMM(TRANSA,M,N,K,ALPHA,DESCRA,VAL,INDX,JNDX,NNZ,
!    $            GINT,NINTC,BETA,GX,NCART,WORK,LWORK)
!            DO I1=1,NCART
!               GX(I1)=GCARTORIG(I1)-GX(I1)
!            ENDDO
!C!             PRINT*, 'TESTXC: ', SQRT(DOT_PRODUCT(GX,GX)/NCART)
!C!GY=AT(GRAD-BEET*GINT(K))=AT*GX
!            NRHS=1
!            LDB=NCART
!            UPLO='U'
!            N=NCART
!            LDGCS=KD+1
!            CALL DPBTRS(UPLO,N,KD,NRHS,GCS,LDGCS,GX,LDB,INFO)
!            IF (INFO.NE.0) PRINT*,'WARNING - AFTER DPBTRS 2 INFO=',INFO
!C!       CALL DPOTRS(UPLO,N,NRHS,GC,LDA,GX,LDB,INFO)
!            TRANSA=0
!            M=NINTC; N = 1; K=NCART
!            GY(:) = 0.0D0
!            CALL DCOOMM(TRANSA,M,N,K,ALPHA,DESCRA,VAL,INDX,JNDX,NNZ,GX,
!    $            NCART,BETA,GY,NINTC,WORK,LWORK) 

!             PRINT*, 'TESTXI: ', SQRT(DOT_PRODUCT(GY,GY)/NINTC)
!UPDATE GINT 
!            SUMGY2=0.0
!            DO I1=1,NINTC
!               GINT(I1)=GINT(I1)+GY(I1)
!               SUMGY2=SUMGY2+GY(I1)*GY(I1)
!            ENDDO
!            MEANSUMGY2=SQRT(SUMGY2/NINTC)
!            IF (MEANSUMGY2.LT.ITGRADCUTOFF) THEN
!               LCONVERGE=.TRUE.
!            ENDIF
!            
!            NITS = NITS+1
!            IF (NITS.GT.1000) THEN
!               PRINT*, 'ERROR: GRAD ITERATION FAILED TO CONVERGE!'
!               CALL DUMPCOORDS(XCART,'BADCOORDS.XYZ', .FALSE.)
!               CALL DUMPCOORDS(GCARTORIG, 'BADGRAD.XYZ', .FALSE.)
!               STOP
!            ENDIF
!      PRINT *,'TRANSFORM MEANSUMGY2',MEANSUMGY2
!         ENDDO
!      ENDIF
!C
!MOVE FINAL INTERNAL GRADIENTS TO GRAD
!C
!     DO I1=1,NINTC
!       GRAD(I1)=GINT(I1)
!     ENDDO
!C
!ZERO GCS2 FOR NEXT CALL TO GETBEE
!     DO J1=1,KD
!       DO I1=1,J1
!         GCS2(KD+1+I1-J1,J1)=0.0
!         GCS2(KD+1+J1-I1,I1)=0.0
!       ENDDO
!     ENDDO
!     DO J1=KD+1,NCART
!       DO I1=J1-KD,J1
!         GCS2(KD+1+I1-J1,J1)=0.0
!         GCS2(KD+1+J1-I1,I1)=0.0
!       ENDDO
!     ENDDO
!C
       RETURN
       END
!


! *************************************************************************

!     
!     SUBROUTINE TO DO INTERNAL COORDINATE MANIPULATIONS USING B-MATRIX
!     CALLS GETBEE TO CALCUALTE B-MATRIX
!     THEN TRANSFORMS A STEP IN INTERNALS TO A STEP IN CARTESIANS 
!     NEMETH ET AL. JCP 113,5598(2000)
!     
      SUBROUTINE AMB_TRANSBACKDELTA(X,CARTX,COORDS,NINTC,NCART,NNZ,KD,FAILED,PTEST2,INTEPSILON)
      USE COMMONS, ONLY: NATOMS
      USE MODAMBER9, ONLY: NBONA, NBONH, NTHETH, NTHETA
      USE INTCOMMONS, ONLY : INTNEWT, NATINT, BACKTCUTOFF, BACKTPRINTERR
      USE SPFUNCTS, ONLY : DUMPCOORDS

      IMPLICIT NONE
!     

!     REAL*8 PREVDIH
!     COMMON /DIHINFO/ PREVDIH(MAXP)
!     
!     NNZ IS NUMBER OF NON-ZERO ELEMENTS IN B-MATRIX
!     NINTC IS NUMBER OF INTERNAL COORDINATES
!     NCART IS NUMBER OF CARTESIANS
!    E 
      INTEGER NNZ,NINTC,NCART
!     
!     COORDS IS CARTESIAN COORDINATES
!     OLDQ IS OLD INTERNAL COORDINATES
!     X IS EIGENVECTOR IN INTERNALS, CARTX IS EV IN CARTESIANS WHICH WE NEED TO CALCULATE
!     NEED TO ZERO CARTX
!     
      DOUBLE PRECISION COORDS(3*NATOMS),DUMCOORDS(3*NATOMS)
      DOUBLE PRECISION VAL(NNZ),WORK(NINTC)
      INTEGER INDX(NNZ),JNDX(NNZ),NITS
      DOUBLE PRECISION ALPHA,BETA
      INTEGER TRANSA,M,N,DESCRA(9),I1,LDGCS,LDB,INFO,NRHS,LWORK,ATOMWIDTH,KD
      DOUBLE PRECISION INTEPSILON,CARTX(NCART),X(NINTC),NEWX(NINTC),XNEW2(NINTC),DUMX(NINTC),SUMDC2,DUMMYQ(NINTC)
      DOUBLE PRECISION MEANDC2,GCS2(2*KD+1,NCART),GCS(KD+1,NCART)
      DOUBLE PRECISION CARTDOTX,CARTDOTY,CARTDOTZ
      CHARACTER*1 UPLO
      LOGICAL NOCOOR,LCONVERGE,FAILED,PTEST, NODERV
      INTEGER J1, J2, K
!    EFK
      INTEGER DUMINDX(NNZ), DUMJNDX(NNZ)
      DOUBLE PRECISION DUMVAL(NNZ), DUMGCS2(2*KD+1,NCART), DUMXINT1(NINTC), DUMXINT2(NINTC)
      DOUBLE PRECISION QORIG(NINTC), TESTQ(NINTC), QTARGET(NINTC)
      LOGICAL PTEST2


!      INTEGER CENTERS, RINGS, FRINGS, LINDIH, IMPDIH, NCNT, NRNG, NFRG,
!     $     NLDH, NIMP, NBDS, ATOMXPOSINC
!      REAL*8 COEFF
!      COMMON /NATINTERN/ COEFF(30,6,6),
!     $     CENTERS(MAXA, 0:5), RINGS(MAXA, 6),
!     $     FRINGS(MAXA, 6), LINDIH(MAXA, -1:8), IMPDIH(MAXA, 4), NCNT,
!     $     NRNG, NFRG, NLDH, NIMP, NBDS, ATOMXPOSINC(10,5,5)
      
      CHARACTER*30 FNAME
!MSB50
      INTEGER NBOND, NTHETS
      DOUBLE PRECISION PI, TWOPI
      PARAMETER(PI=3.141592653589793D0)


      TWOPI = 2.0D0*PI
      NBOND = NBONA+NBONH 
      NTHETS = NTHETA +NTHETH

!      PTEST=.TRUE.
      PTEST = .FALSE.

!     MAKE DUMMY ARRAY NEWX THAT CAN CHANGE (ERROR IN ESTIMATE OF X)
!     AND DUMX WHICH IS CUMULATIVE ESTIMATE OF X
!     AND DUMMY ARRAY DUMCOORDS THAT CAN CHANGE
!     
      DO I1=1,NINTC
         NEWX(I1)=X(I1)
         DUMX(I1)=0.0D0
      ENDDO
      DO I1=1,NCART
         CARTX(I1)=0.0D0
         DUMCOORDS(I1)=COORDS(I1)
      ENDDO
!    
!    START ITERATIVE LOOP TO DO CONVERSION OF INTERNAL COORDINATES TO CARTESIANS
!    HAVE X, NEED TO SATISFY CARTX=A*X AND X=B*CARTX
!    
      LCONVERGE=.FALSE.
      FAILED=.TRUE.
      NITS=0
!    
!    ATTEMPT TO PREVENT NAN ON SOLARIS
!    
      DUMMYQ(1:NINTC) = 0.0D0
      XNEW2(1:NINTC)=0.0D0

      DO WHILE (.NOT.LCONVERGE)
!        IF (PTEST) PRINT '(A,I6,G20.10)',
!    $        'TRANSBACKDELTA>> INTERNALS ERROR', NITS,
!    $        SQRT(DOT_PRODUCT(NEWX(1:NINTC),NEWX(1:NINTC)))
!    
!    GET B-MATRIX WITHOUT CHANGING CARTESIANS TO INTERNALS
!    ADDED DUMMYQ ARGUMENT 13/2/04 DJW
!    
         IF (PTEST) THEN
            PRINT*,'DUMCOORDS BEFORE GETBEE, INTEPSILON=',INTEPSILON
            WRITE(*,'(6G18.10)') (DUMCOORDS(J1),J1=1,NCART)
            PRINT*,'DUMMYQ BEFORE GETBEE'
            WRITE(*,'(6G18.10)') (DUMMYQ(J1),J1=1,NINTC)
         ENDIF

         IF (NITS.EQ.0) THEN ! STORE ORIGINAL AND TARGET INTERNALS
            NOCOOR = .FALSE.; NODERV = .FALSE.
            CALL AMB_GETBEENAT(DUMCOORDS,QORIG,VAL,INDX,JNDX,NINTC,NCART,NNZ,GCS2,NOCOOR,NODERV,KD)
            QTARGET(:) = QORIG(:) + X(:)
         ELSE
            NOCOOR = .TRUE.; NODERV = .FALSE.
            CALL AMB_GETBEENAT(DUMCOORDS,DUMMYQ,VAL,INDX,JNDX,NINTC,NCART,NNZ,GCS2,NOCOOR,NODERV,KD)
         ENDIF

        IF (PTEST) THEN
           PRINT*,'GCS2 AFTER GETBEE:',INTEPSILON
           WRITE(*,'(6G18.10)') ((GCS2(J1,J2),J1=1,2*KD+1),J2=1,NCART)
        ENDIF

!    
!    WANT TO FIND CARTX=A*X
!    A = G^-1*BEET
!    SAME AS SOLVING G*CARTX=BEET*X
!    G=GC+INTEPSILON*I
!    GC=BEETBEE (AS IN TRANSFORM), STORED AS SPARSE GCS
!    KD IS NUMBER OF SUPERDIAGONALS OF GC
!    SEE DPBTRF.F HTTP://WWW.NETLIB.ORG/LAPACK/DOUBLE/DPBTRF.F
!    
!    KD=3*ATOMWIDTH+2       
!    NEED TO MOVE GCS2 INTO GCS

         GCS(:,:) = 0.0D0
         DO J1=1,KD
            DO I1=1,J1
               GCS(KD+1+I1-J1,J1)=GCS2(KD+1+I1-J1,J1)
            ENDDO
         ENDDO
         DO J1=KD+1,NCART
            DO I1=J1-KD,J1
               GCS(KD+1+I1-J1,J1)=GCS2(KD+1+I1-J1,J1)
               !PRINT*, GCS(KD+1+I1-J1,J1)
            ENDDO
         ENDDO
           
!    
!    FORM G = GC + EI WHERE E IS SMALL
!    
         DO I1=1,NCART
            GCS(KD+1,I1)=GCS(KD+1,I1)+INTEPSILON
         ENDDO
!    
!    NEWX IS ERROR IN INTERNALS AT END OF LAST CYCLE
!    MULTIPLY NEWX BY BEET TO GIVE CARTX
!    USES SPARSE MATRIX MULTIPLICATION ROUTINE FROM BLAS
!    HTTP://MATH.NIST.GOV/~KREMINGTON/FSPBLAS/
!    
         TRANSA=1
         M=NINTC
         N=1
         K=NCART
         ALPHA=1.0D0
         BETA=0.0D0
         DO I1=1,9
            DESCRA(I1)=0
         ENDDO
         DESCRA(4)=1
         LWORK=NINTC
         IF (PTEST) THEN
            PRINT*,'BEFORE DCOOMM 1 NEWX:'
            WRITE(*,'(6G20.10)') (NEWX(J1),J1=1,NINTC)
            PRINT*,'BEFORE DCOOMM 1 CARTX:'
            WRITE(*,'(6G20.10)') (CARTX(J1),J1=1,NCART)
         ENDIF
         CALL DCOOMM(TRANSA,M,N,K,ALPHA,DESCRA,VAL,INDX,JNDX,NNZ, &
     &        NEWX,NINTC,BETA,CARTX,NCART,WORK,LWORK)
         IF (PTEST) THEN
            PRINT*,'AFTER DCOOMM 1 NEWX:'
            WRITE(*,'(6G20.10)') (NEWX(J1),J1=1,NINTC)
            PRINT*,'AFTER DCOOMM 1 CARTX:'
            WRITE(*,'(6G20.10)') (CARTX(J1),J1=1,NCART)
         ENDIF         
!    
!    CHOLESKY DECOMPOSE GCS
!    USE LAPACK ROUTINE DPBTRF
!    LDGCS IS LEADING DIMENSION OF GCS
!    
         UPLO='U'
         N=NCART
         LDGCS=KD+1
        IF (PTEST) THEN
           PRINT*,'GCS BEFORE DPBTRF:'
           WRITE(*,'(6G18.10)') ((GCS(J1,J2),J1=1,KD+1),J2=1,NCART)
        ENDIF
!    CALL MYCPU_TIME(TESTTIME1, .FALSE.)
         CALL DPBTRF(UPLO,N,KD,GCS,LDGCS,INFO)
!    CALL MYCPU_TIME(TESTTIME2, .FALSE.)
!    TOTCHOLTIME = TOTCHOLTIME + TESTTIME2 - TESTTIME1
         IF (INFO.NE.0) PRINT*,'AFTER DPBTRF INFO=',INFO

!MSB50
!        IF (PTEST) THEN
!           PRINT*,'GCS AFTER DPBTRF:'
!           WRITE(*,'(6G18.10)') ((GCS(J1,J2),J1=1,KD+1),J2=1,NCART)
!        ENDIF
!    
!    GCS IS NOW THE UPPER TRIANGULAR MATRIX AFTER DECOMPOSITION
!    SOLVE G*DELTAX=CARTX FOR DELTAX, WHERE G IS ORIGINAL BEETBEE+INTEPSILON*I
!    DONE USING LAPACK ROUTINE DPBTRS WITH INPUT OF THE UPPER MATRIX FROM
!    CHOLESKY DECOMPOSITION
!    
         NRHS=1
         LDB=NCART
         CALL DPBTRS(UPLO,N,KD,NRHS,GCS,LDGCS,CARTX,LDB,INFO)
         IF (INFO.NE.0) PRINT*,'AFTER DPBTRS INFO=',INFO
        IF (PTEST) THEN
           PRINT*,'GCS AFTER DPBTRS:'
           WRITE(*,'(6G18.10)') ((GCS(J1,J2),J1=1,KD+1),J2=1,NCART)
           PRINT*,'AFTER DPBTRS CARTX:'
           WRITE(*,'(6G20.10)') (CARTX(J1),J1=1,NCART)
        ENDIF

!    
!    CARTX IS NOW SOLUTION OF CARTX=A*X
!    EVALUATE XNEW2=B*CARTX
!    

         IF (INTNEWT) THEN
            ! EVALUATE XNEW2 DIRECTLY FROM NEW CARTESIAN COORDS
            NOCOOR = .FALSE.; NODERV = .TRUE.
            CALL AMB_GETBEENAT(DUMCOORDS+CARTX,DUMXINT2,DUMVAL,DUMINDX, &
     &           DUMJNDX,NINTC,NCART,NNZ,DUMGCS2,NOCOOR,NODERV,KD)

            ! ALIGN DIHEDRAL ANGLES IF USING PRIMITIVE INTERNALS
            IF (.NOT.NATINT) THEN 
               !MSB 50 - PROBABLY BUG FOR AMBER
               PRINT*, "WARNING - AMB_TRANSBACKDELTA HAS NATINT .FALSE.&
               &- ARE YOU SURE? -> UNCOMMENT STOP IN AMBNATINERN_EXTRAS"
               STOP 
               DO I1 = NBOND+NTHETS+1, NINTC
                  IF (DUMXINT2(I1) - QTARGET(I1).GT.PI) THEN
                     DUMXINT2(I1) = DUMXINT2(I1) - TWOPI
                  ELSE IF (DUMXINT2(I1) - QTARGET(I1).LT.-PI) THEN
                     DUMXINT2(I1) = DUMXINT2(I1) + TWOPI
                  ENDIF                  
               ENDDO
            ENDIF
            NEWX = QTARGET - DUMXINT2

         ELSE ! SOLVE LINEAR EQUATION ONLY; ITERATE AWAY EFFECT OF EPSILON
            TRANSA=0
            N=1
            CALL DCOOMM(TRANSA,M,N,K,ALPHA,DESCRA,VAL,INDX,JNDX,NNZ, &
     &           CARTX,NCART,BETA,XNEW2,NINTC,WORK,LWORK)

            IF (PTEST) THEN
               PRINT*,'XNEW2 AFTER DCOOMM 2:'
               WRITE(*,'(6G18.10)') (XNEW2(J1),J1=1,NINTC)
               PRINT*,'AFTER DCOOMM 2 CARTX:'
               WRITE(*,'(6G20.10)') (CARTX(J1),J1=1,NCART)
            ENDIF
            DO I1=1,NINTC
               DUMX(I1)=DUMX(I1)+XNEW2(I1) ! SUM OF F(X_I) INSTEAD OF F(SUM(X_I))
               NEWX(I1)=X(I1)-DUMX(I1)
            ENDDO
         ENDIF

!    PROJECT TRANSLATION OUT OF CARTX
         CARTDOTX=0.0D0
         CARTDOTY=0.0D0
         CARTDOTZ=0.0D0
         DO I1=1,NATOMS
            CARTDOTX=CARTDOTX+CARTX(3*(I1-1)+1)
            CARTDOTY=CARTDOTY+CARTX(3*(I1-1)+2)
            CARTDOTZ=CARTDOTZ+CARTX(3*(I1-1)+3)
         ENDDO
         DO I1=1,NATOMS
            CARTX(3*(I1-1)+1)=CARTX(3*(I1-1)+1)-CARTDOTX/NATOMS
            CARTX(3*(I1-1)+2)=CARTX(3*(I1-1)+2)-CARTDOTY/NATOMS
            CARTX(3*(I1-1)+3)=CARTX(3*(I1-1)+3)-CARTDOTZ/NATOMS
         ENDDO
!    UPDATE DUMCOORDS FOR NEXT CALL TO GETBEE; CHECK FOR CONVERGENCE
         SUMDC2=0.0D0
         DO I1=1,NCART
            DUMCOORDS(I1)=DUMCOORDS(I1)+CARTX(I1)
            SUMDC2=SUMDC2+CARTX(I1)*CARTX(I1)
         ENDDO
         MEANDC2=SUMDC2/NINTC

         IF (MEANDC2.LT.BACKTCUTOFF) THEN                  
            LCONVERGE=.TRUE.
            FAILED=.FALSE.
         ENDIF
         NITS=NITS+1

         IF (PTEST2) PRINT '(A,I5,2G20.10)',&
             'TRANSBACKDELTA>> NITS,MEANDC2, INT ERRO =',NITS, MEANDC2,&
             SQRT(DOT_PRODUCT(NEWX(1:NINTC),NEWX(1:NINTC)))

         IF (SQRT(DOT_PRODUCT(NEWX(1:NINTC),NEWX(1:NINTC))).GT.100) THEN
            PRINT*, 'ERROR! DELTATRANSFORM DIVERGED.'
            CALL DUMPCOORDS(COORDS,'DIVERGED.XYZ', .FALSE.)
            OPEN(UNIT=88,FILE='BADSTP', STATUS = 'UNKNOWN')
            WRITE(88,'(G25.15)') (X(J1), J1 = 1,NINTC)
            CLOSE(88)
            LCONVERGE = .TRUE.
            FAILED = .TRUE.
            CARTX(:) = 0.0D0
            RETURN
         ENDIF

         IF (NITS.GT.100) THEN
            PRINT*,'WARNING INTERNAL COORDINATE TRANSFORMATION&
               & DID NOT CONVERGE, MEANDC2=',MEANDC2
            FAILED = .TRUE.
            LCONVERGE=.TRUE.
         ENDIF
!    
      ENDDO

!    UPDATE CARTX SO THAT IT IS THE DIFFERENCE BETWEEN FINAL DUMCOORDS AND COORDS
!    PRINT *,'TDB HERE1'

      DO I1=1,3*NATOMS
         CARTX(I1)=DUMCOORDS(I1)-COORDS(I1)
      ENDDO
!    
!    PROJECT TRANSLATION OUT OF CARTX
      CARTDOTX=0.0D0
      CARTDOTY=0.0D0
      CARTDOTZ=0.0D0
      DO I1=1,NATOMS
         CARTDOTX=CARTDOTX+CARTX(3*(I1-1)+1)
         CARTDOTY=CARTDOTY+CARTX(3*(I1-1)+2)
         CARTDOTZ=CARTDOTZ+CARTX(3*(I1-1)+3)
      ENDDO
      DO I1=1,NATOMS
         CARTX(3*(I1-1)+1)=CARTX(3*(I1-1)+1)-CARTDOTX/NATOMS
         CARTX(3*(I1-1)+2)=CARTX(3*(I1-1)+2)-CARTDOTY/NATOMS
         CARTX(3*(I1-1)+3)=CARTX(3*(I1-1)+3)-CARTDOTZ/NATOMS
      ENDDO

      IF(BACKTPRINTERR) PRINT*, 'TRANSBACKDELTA>>> ERROR = ', SQRT(DOT_PRODUCT(NEWX(1:NINTC),NEWX(1:NINTC)))

      RETURN
      END


      SUBROUTINE GETDIHONLY(XCART)
!SUBROUTINE FROM AMBGETBEENAT -- ONLY DIHEDRAL PARTS TO PROVIDE EASIER ACCESS
      USE COMMONS, ONLY: NATOMS
      USE INTCOMMONS
      USE MODAMBER9, ONLY: IH, M04

      IMPLICIT NONE

      DOUBLE PRECISION, INTENT(IN):: XCART(3*NATOMS)     
      INTEGER DIHC, RATMS, NANGC, NDIHC
      INTEGER XIND(8),INFO(-1:8)
      DOUBLE PRECISION PHI, DPDI(0:2), DPDJ(0:2), DPDK(0:2), DPDL(0:2)  
      DOUBLE PRECISION NANGCR
      INTEGER RNG, FRG,LDH, I1, TCOUNT, J1, K1,L1
      INTEGER CURPHI
      INTEGER IX, JX, KX, LX
      DOUBLE PRECISION PHI2, DPDI2(0:2), DPDJ2(0:2), DPDK2(0:2), DPDL2(0:2)
      LOGICAL NOCOOR
      DOUBLE PRECISION PHI1, PREVPHI1
      INTEGER ATOMS2PERM

      DIHC=0 
      NOCOOR = .FALSE.
      DO 25 RNG=1,NRNG

         IF(RINGS(RNG,6).EQ.-1) THEN
            RATMS = 5 ! 5 ATOMS IN RING
            NANGC = 2; NDIHC = 2 ! 2 ANGLE & 2 DIHEDRAL COORDS
         ELSE
            RATMS = 6 ! 6 ATOMS IN RING
            NANGC = 3; NDIHC = 3
         ENDIF

         DO I1=1,RATMS
            XIND(I1) = 3*(RINGS(RNG,I1) - 1) + 1
         ENDDO

         TCOUNT = 1
         DO I1 = 1,RATMS
            J1 = MOD(I1,RATMS)+1
            K1 = MOD(I1+1,RATMS)+1
            L1 = MOD(I1+2,RATMS)+1

            CALL AMBGETTORSION(XCART(XIND(I1):XIND(I1)+2),                 &
     &           XCART(XIND(J1):XIND(J1)+2), XCART(XIND(K1):XIND(K1)+2),&
     &           XCART(XIND(L1):XIND(L1)+2), PHI, DPDI, DPDJ, DPDK, DPDL,&
     &           .FALSE.,.TRUE.)

            DIHC = DIHC + 1

            IF (TCOUNT.EQ.1) PREVPHI1 = PREVDIH(DIHC)
            IF (.NOT.NOCOOR) CALL AMBALIGNDIH(PHI, DIHC, PHI-PHI1, PREVDIH(DIHC)-PREVPHI1,TCOUNT)
            IF (TCOUNT.EQ.1) PHI1 = PHI
            TCOUNT = TCOUNT + 1
!           PRINT '(A5,I4,4A4, F11.6,F11.6)',"RING", DIHC,IH(M04+RINGS(RNG,I1)-1), IH(M04+RINGS(RNG,J1)-1), &
! &                  IH(M04+RINGS(RNG,K1)-1), IH(M04+RINGS(RNG,L1)-1), PREVDIH(DIHC),(PREVDIH(DIHC)/3.14159265358979)*180.0
          ENDDO

 25   CONTINUE

      DO FRG = 1,NFRG
          DO I1=1,6
             XIND(I1) = 3*(FRINGS(FRG,I1) - 1)+1
          ENDDO
    
          CALL AMBGETTORSION(XCART(XIND(3):XIND(3)+2),&
     &         XCART(XIND(1):XIND(1)+2), XCART(XIND(2):XIND(2)+2), &
     &         XCART(XIND(6):XIND(6)+2), PHI, DPDI, DPDJ, DPDK, DPDL,&
     &         NOCOOR,.TRUE.)   
          DIHC = DIHC + 1
          PREVPHI1 = PREVDIH(DIHC)
          IF (.NOT.NOCOOR) CALL AMBALIGNDIH(PHI, DIHC, 0.0D0, 0.0D0, 1) 
!         PRINT '(A5,I4,4A4,F11.6,F11.6)',"FRNG", DIHC,IH(M04+RINGS(RNG,3)-1), IH(M04+RINGS(RNG,1)-1), 
!                IH(M04+RINGS(RNG,2)-1), IH(M04+RINGS(RNG,6)-1), PREVDIH(DIHC),  (PREVDIH(DIHC)/3.14159265358979)*180.0
 
          CALL AMBGETTORSION(XCART(XIND(5):XIND(5)+2),&
     &         XCART(XIND(1):XIND(1)+2), XCART(XIND(2):XIND(2)+2),  &
     &         XCART(XIND(4):XIND(4)+2), PHI2, DPDI2, DPDJ2, DPDK2, &
     &         DPDL2, NOCOOR,.TRUE.)
         DIHC = DIHC + 1

         IF (.NOT.NOCOOR) CALL AMBALIGNDIH(PHI2, DIHC, PHI2-PHI, PREVDIH(DIHC)-PREVPHI1, 2)         
!           PRINT '(A5,I4,4A4,F11.6,F11.6)',"FRNG", DIHC,IH(M04+RINGS(RNG,5)-1), IH(M04+RINGS(RNG,1)-1), 
!                   IH(M04+RINGS(RNG,2)-1), IH(M04+RINGS(RNG,4)-1), PREVDIH(DIHC), (PREVDIH(DIHC)/3.14159265358979)*180.0
         TCOUNT = TCOUNT + 1
      ENDDO 

      DO 30 LDH=1,NLDH
         INFO(-1:8) = LINDIH(LDH,-1:8)
         !INFO(-1) AND INFO(0) DENOTE THE NUMBER OF POSSIBLE I AND L ATOMS
         DO I1=1,INFO(0)+INFO(-1)+2
            XIND(I1) = 3*(INFO(I1) - 1) + 1
         ENDDO
         NANGC = INFO(-1)*INFO(0) ! NUMBER OF TORSIONS INVOLVED

         NANGCR = 1.0D0/NANGC

         CURPHI = 0
         DO I1=3,INFO(-1)+2
            DO L1=INFO(-1)+3,INFO(-1)+INFO(0)+2
               CURPHI = CURPHI + 1

               IX = XIND(I1)
               JX = XIND(1)
               KX = XIND(2)
               LX = XIND(L1)
               
!               PRINT*, "GETDIHONLY PHI1", PHI1
!               IF (CURPHI.EQ.1) THEN
!                  DO I2 = 1, NPERMGROUP
!                     IF (PERMNEIGHBOURS(I2,4)==LDH) THEN
!                        PERMNEIGHBOURS(I2, 8)==PHI1
!                        I3= PERMNEIGHBOURS(I2,1)
!                        PERMNEIGHBOURS(I3,
!                      IF (PERMNEIGHBOURS(I2,5)==LDH) THEN
               CALL AMBGETTORSION(XCART(IX:IX+2), XCART(JX:JX+2),  &
     &              XCART(KX:KX+2), XCART(LX:LX+2), PHI, DPDI, DPDJ,   &
     &              DPDK, DPDL, NOCOOR,.TRUE.)                              

               DIHC = DIHC + 1
               IF (CURPHI.EQ.1) PREVPHI1 = PREVDIH(DIHC)

               IF (.NOT.NOCOOR) CALL AMBALIGNDIH(PHI, DIHC, PHI-PHI1, PREVDIH(DIHC)-PREVPHI1,CURPHI)
!              PRINT '(A5,I4,X,4A4,F11.6, F11.6)',"LDH", DIHC,IH(M04+INFO(I1)-1), IH(M04+INFO(1)-1), 
!    &                 IH(M04+INFO(2)-1), IH(M04+INFO(L1)-1), PREVDIH(DIHC) , (PREVDIH(DIHC)/3.14159265358979)*180.0

               IF (CURPHI.EQ.1) PHI1 = PHI
            ENDDO
         ENDDO
 30   CONTINUE 

      END SUBROUTINE GETDIHONLY
! *****************************************
      SUBROUTINE GETLDH(LDH, STDIHC,PHI1,XCART)
         USE INTCOMMONS, ONLY: LINDIH, PREVDIH
         USE MODAMBER9, ONLY: IH, M04
         USE COMMONS, ONLY: NATOMS
         IMPLICIT NONE
         INTEGER, INTENT(IN) :: LDH, STDIHC
         DOUBLE PRECISION, INTENT(INOUT):: PHI1 
         DOUBLE PRECISION, INTENT(IN):: XCART(3*NATOMS)
         INTEGER :: INFO(-1:8), XIND(8), NANGC, CURPHI, IX,JX,KX,LX,DIHC
         DOUBLE PRECISION :: NANGCR, PHI, DPDI(3), DPDJ(3), DPDK(3), DPDL(3)
         DOUBLE PRECISION :: PREVPHI1
         INTEGER :: I1,L1
         DIHC = STDIHC -1 
!FIND PH1
         INFO(-1:8) = LINDIH(LDH,-1:8)
         INFO(-1:8) = LINDIH(LDH,-1:8)
         !INFO(-1) AND INFO(0) DENOTE THE NUMBER OF POSSIBLE I AND L ATOMS
         DO I1=1,INFO(0)+INFO(-1)+2
            XIND(I1) = 3*(INFO(I1) - 1) + 1
         ENDDO
         NANGC = INFO(-1)*INFO(0) ! NUMBER OF TORSIONS INVOLVED

         NANGCR = 1.0D0/NANGC

         CURPHI = 0
         DO I1=3,INFO(-1)+2
            DO L1=INFO(-1)+3,INFO(-1)+INFO(0)+2
               CURPHI = CURPHI + 1

               IX = XIND(I1)
               JX = XIND(1)
               KX = XIND(2)
               LX = XIND(L1)

               CALL AMBGETTORSION(XCART(IX:IX+2), XCART(JX:JX+2),  &
     &              XCART(KX:KX+2), XCART(LX:LX+2), PHI, DPDI, DPDJ,   &
     &              DPDK, DPDL, .FALSE., .TRUE.)                      
               DIHC = DIHC + 1
               IF (CURPHI.EQ.1) PREVPHI1 = PREVDIH(DIHC)

!               PRINT '(A15,3I4,4(I4,A4),F8.2)','GETBEE>DIH', & 
!     &       LDH,DIHC, INFO(I1), IH(M04+INFO(I1)-1),INFO(1),IH(M04+INFO(1)-1),&
!              INFO(2), IH(M04+INFO(2)-1),INFO(L1),IH(M04+INFO(L1)-1), PHI
               CALL AMBALIGNDIH(PHI, DIHC, PHI-PHI1, PREVDIH(DIHC)-PREVPHI1,CURPHI)

               IF (CURPHI.EQ.1) PHI1 = PHI
            ENDDO
         ENDDO
      END SUBROUTINE GETLDH
        



! ******************************************
      SUBROUTINE FINDPERMDIH
!MSB50 - FIND DIHEDRAL ANGLES WHICH INVOLVE ATOMS FROM DIFFERENT PERMGROUPS
!        S.T. FOR INTMINPERM THE MINIMUM DIHEDRAL CAN BE FOUND
      USE KEY, ONLY: NPERMGROUP, DEBUG
      USE INTCOMMONS
      USE MODAMBER9, ONLY: IH, M04, NRES, IX,I02,M02
      USE COMMONS, ONLY: NATOMS     

      IMPLICIT NONE
      INTEGER I1, A1, A2, B, K1, J1,L1, B1P,H2,HH, BH,B1, NCTA
      INTEGER :: PGH, PGH2, PGBH
      CHARACTER(LEN=4) :: RESNAME,  B1PN,HNAME,BHN
      CHARACTER(LEN=4) :: PERMAC(10,3)
      INTEGER :: RESNUM
      INTEGER ATOMS2PERM(NATOMS) !INCLUDES PG OF SOME (IMPORTANT ATOMS, REST 0)
      INTEGER ATCENTRE2PERM(NATOMS) !PG FOR CERTAIN CENTRES (I.E. THE ATOMS AROUND IT!!)
      INTEGER THISROUNDFOUND
      LOGICAL CRITICAL, ARGININE
      INTEGER PG_CENTRE, PG_CENTRE2, PG_CENTREAC
      INTEGER ALREADYPG(NATOMS)
      DATA PERMAC(1,:) /'LEU ', 'NLEU','CLEU'/
      DATA PERMAC(2,:) /'ILE ', 'NILE', 'CILE'/
      DATA PERMAC(3,:) /'LYS ', 'NLYS', 'CLYS'/
      DATA PERMAC(4,:) /'PHE ', 'NPHE', 'CPHE'/
      DATA PERMAC(5,:) /'TYR ', 'NTYR', 'CTYR'/ 
      DATA PERMAC(6,:) /'GLU ', 'NGLU', 'CGLU'/
      DATA PERMAC(7,:) /'ASP ', 'NASP', 'CASP'/
      DATA PERMAC(8,:) /'MET', 'NMET', 'CMET'/
      DATA PERMAC(9,:) /'GLN', 'NGLN', 'CGLN'/
      DATA PERMAC(10,:) /'ARG', 'NARG','CARG'/
      CHARACTER(LEN=2) :: BONDEDHS(4)
      DATA BONDEDHS /'HB','HE', 'HD', 'HG'/
     

      IF (.NOT.ALLOCATED(MBADJACENT)) THEN
          CALL AMB_NATINTSETUP
          CALL AMBGETNATINTERN
      ENDIF
      IF (.NOT.ALLOCATED(PERMNANGLE)) ALLOCATE(PERMNANGLE(NPERMGROUP,2))
      ATOMS2PERM(:)=0
      PGH = 0; PGH2 = 0; PGBH = 0
      IF (.NOT.ALLOCATED(PERMNEIGHBOURS)) ALLOCATE(PERMNEIGHBOURS(NPERMGROUP,7))
      PERMNEIGHBOURS(:,:) = 0
      ALREADYPG(:)=0
      !ALREADYPG(ATOM)=ATOM2 IF THIS CENTRE HAS ALREADY BEEN FOUND AND IS IN PERMNEIGHBOURS
      IF (DEBUG) PRINT*, "NCNT2", NCNT2
      !THIS SCHEME ONLY WORKS IF OF THE TWO ADJACENT PERMGROUPS AT LEAST ONE IS CENTRE2 - 
      ! WHICH IT IS FOR THE AMINO ACIDS I HAVE
      ARGININE = .FALSE.
      DO I1 = 1, NCNT2
         PGH = 0; PGH2 = 0; PGBH = 0
         HH = 0; H2 = 0; BH=0
         PG_CENTRE2=0;PG_CENTREAC=0;PG_CENTRE=0
         THISROUNDFOUND=0
         NCTA = CENTER2(I1)
         A1 = CENTERS(NCTA, 1)
         CALL GETRESID(A1, RESNAME, RESNUM)
         CRITICAL = .FALSE.
         DO K1=1,10
            IF (PERMAC(K1,1).EQ.RESNAME.OR.PERMAC(K1,2).EQ.RESNAME &
     &        .OR.PERMAC(K1,3).EQ.RESNAME) THEN
               CRITICAL = .TRUE.
               IF (K1==10) ARGININE=.TRUE.
               EXIT
            ENDIF
         ENDDO
         !PRINT*,I1, "FINDMINPERMN, NEIGBOURS OF", A1, "CRITICAL", CRITICAL, RESNAME
         IF (.NOT.CRITICAL) CYCLE !NO TWO GROUPS AFTER ONE ANOTHER
         !NEED TO FIND HYDROGENS/PERMGROUP ATOMS TO FIND PERMGROUP
         IF (IH(M04+A1-1)=="CA") CYCLE !HAPPEN TO BE CENTER2S AS WELL
         DO J1 = 2, 5 !LOOP OVER ATOMS BONDED TO A1
            B1 = CENTERS(NCTA,J1)
            DO K1= 1, NCNT2 !CENTER 2
               IF(CENTERS(CENTER2(K1),1)==B1.AND.ALREADYPG(A1).NE.B1) THEN !FOUND 2-2
                  DO L1 = 5, 2,-1
                    PG_CENTRE2=B1
                    HNAME=IH(M04+CENTERS(CENTER2(K1),L1)-1)
                    IF ((HNAME.EQ.('HB2').OR.HNAME.EQ.('HG2')).OR. &
     &              (HNAME.EQ.('HD2').OR.HNAME.EQ.('HE23')).OR.HNAME.EQ.('HE2 ')) THEN
                      H2 = CENTERS(CENTER2(K1),L1)
                      THISROUNDFOUND = THISROUNDFOUND + 1
                      ALREADYPG(B1)=A1
                      !PRINT*, "NEIGHBOUR", B1, "H", H2
                      !PRINT*, "ALREADYPG", ALREADYPG(A1), "B1", B1,ALREADYPG(B1)
                      EXIT
                    ENDIF
                  ENDDO !ONCE A PARTICULAR NEIGHBOUR WITH CENTERTYPE 2 IS FOUND 
                  EXIT  !EXIT LOOP OVER 2CENTRES IN THAT CASE
               ENDIF
            ENDDO 
            DO K1 = 1,3  !ALL OTHER CENTERS
               IF ((RESNAME.EQ.PERMAC(1,K1).AND.IH(M04+B1-1).EQ.'CG  ').OR.&
     &             (IH(M04+B1-1).EQ.'CG  '.AND.RESNAME.EQ.PERMAC(4,K1)).OR.&
     &             (IH(M04+B1-1).EQ.'CG  '.AND.RESNAME.EQ.PERMAC(5,K1)))THEN
                  PG_CENTREAC=B1
                  DO L1 = 1, MBBONDNUM(B1)
                   BHN = IH(M04+MBADJACENT(B1,L1)-1)
                   IF (BHN.EQ.'CD1 '.OR.BHN.EQ.'CD2 ') THEN
!                     CALL FINDPERMGROUP(BH, PGBH)
                      BH=MBADJACENT(B1,L1)
                      THISROUNDFOUND = THISROUNDFOUND +1
                      EXIT                     
                    ENDIF 
                  ENDDO   
                  EXIT               
               ELSEIF (IH(M04+B1-1).EQ.'CD1 '.AND.RESNAME.EQ.PERMAC(2,K1))THEN
                   PG_CENTREAC=B1
                  DO L1 = 1, MBBONDNUM(B1)    
                   BHN = IH(M04+MBADJACENT(B1,L1)-1)
                   IF (BHN.EQ.'HD11 '.OR.BHN.EQ.'HD22'.OR.&
     &                     BHN.EQ.'HD33') THEN
                      BH=MBADJACENT(B1,L1)
                      THISROUNDFOUND = THISROUNDFOUND +1
                      EXIT
                    ENDIF
                  ENDDO                  
                  EXIT
               ELSEIF (IH(M04+B1-1).EQ.'NZ  '.AND.RESNAME.EQ.PERMAC(3,K1))THEN
                  PG_CENTREAC=B1
                  DO L1 = 1, MBBONDNUM(B1)
                   BHN = IH(M04+MBADJACENT(B1,L1)-1)
                   IF (BHN.EQ.'HZ1 '.OR.BHN.EQ.'HZ2 '.OR.&
     &                     BHN.EQ.'HZ3 ') THEN
                      BH=MBADJACENT(B1,L1)
                      THISROUNDFOUND = THISROUNDFOUND +1
                      EXIT
                    ENDIF
                  ENDDO                  
                  EXIT
!               ELSEIF (IH(M04+B1-1).EQ.'CG  '.AND.RESNAME.EQ.PERMAC(4,K1)).OR. &
!    &               (IH(M04+B1-1).EQ.'CG  '.AND.RESNAME.EQ.PERMAC(5,K1)) THEN

               ELSEIF(((IH(M04+B1-1).EQ.'CD  '.AND.RESNAME.EQ.PERMAC(6,K1))).OR. &
     &              (IH(M04+B1-1).EQ.'CG  '.AND.RESNAME.EQ.PERMAC(7,K1))) THEN
                  PG_CENTREAC=B1
                  DO L1 = 1, MBBONDNUM(B1)
                   BHN = IH(M04+MBADJACENT(B1,L1)-1)
                   IF (BHN.EQ.'OE1 '.OR.BHN.EQ.'OE2 ' .OR.&
     &                  BHN.EQ.'OD1 '.OR.BHN.EQ.'OD2 ') THEN
                      THISROUNDFOUND = THISROUNDFOUND +1
                      BH=MBADJACENT(B1,L1)
                      EXIT
                    ENDIF
                  ENDDO
                  EXIT
               ENDIF
            ENDDO

            IF ((IH(M04+B1-1).EQ.('HB2 ').OR.IH(M04+B1-1).EQ.('HG2 ')).OR. &
     &        (IH(M04+B1-1).EQ.('HD2 ').OR.IH(M04+B1-1).EQ.('HE23').OR.    &
     &         IH(M04+B1-1).EQ.('HE2 ').OR.IH(M04+B1-1).EQ.('HG12'))) THEN
               HH = B1
               PG_CENTRE=A1
!               CALL FINDPERMGROUP(J1, PGH)  
               THISROUNDFOUND = THISROUNDFOUND +1
               EXIT !EXIT WHOLE LOOP - H WILL BE FOUND LAST
            ENDIF
         ENDDO 

         IF ((THISROUNDFOUND.GT.3).OR.(THISROUNDFOUND.LE.1)) THEN
            IF ((ALREADYPG(A1).NE.0).AND.(THISROUNDFOUND.EQ.1)) THEN !COULD BE IF WE'VE ALREADY INCLUDED THIS
               PRINT*, "CYCLE"
               CYCLE
            ELSE
            PRINT*, "IMPOSSIBLE NUMBERS OF NEIGHBOURS FOUND FOR",A1, THISROUNDFOUND
            PRINT*, "ERROR IN FINDPERMDIH"
            STOP
            ENDIF
         ENDIF
         IF (J1==0) THEN
           PRINT*, "NO HYDROGEN FOUND"; STOP
         ELSE
            CALL FINDPERMGROUP(HH,H2,BH,PGH,PGH2,PGBH)
            !PRINT*, "AFTER FINDPG HH,H2,BH,PGH,PGH2,PGBH", HH,H2,BH,PGH,PGH2,PGBH
            IF (PGBH.NE.0) THEN
               PERMNEIGHBOURS(PGH,1) = PERMNEIGHBOURS(PGH,1)+1
               PERMNEIGHBOURS(PGBH,1) = PERMNEIGHBOURS(PGBH,1)+1
               IF (PERMNEIGHBOURS(PGH, PERMNEIGHBOURS(PGH,1)+1).NE.0 .OR. &
     &              PERMNEIGHBOURS(PGBH,PERMNEIGHBOURS(PGBH,1)+1).NE.0) THEN
                   PRINT*,I1, "ERROR", PGH, PERMNEIGHBOURS(PGH,1),PGBH
                   STOP
               ENDIF
               PERMNEIGHBOURS(PGH,PERMNEIGHBOURS(PGH,1)+1) = PGBH
               PERMNEIGHBOURS(PGBH,PERMNEIGHBOURS(PGBH,1)+1) = PGH
               ATOMS2PERM(HH)=PGH
               ATOMS2PERM(BH)=PGBH
               ATCENTRE2PERM(PG_CENTRE) = PGH
               ATCENTRE2PERM(PG_CENTREAC)= PGBH
            ENDIF
            IF (PGH2.NE.0) THEN !NOT BONDED TO ANYTHING NEW
               PERMNEIGHBOURS(PGH,1) = PERMNEIGHBOURS(PGH,1)+1
               PERMNEIGHBOURS(PGH2,1) = PERMNEIGHBOURS(PGH2,1)+1
               IF( PERMNEIGHBOURS(PGH, PERMNEIGHBOURS(PGH,1)+1).NE.0 .OR. &
     &              PERMNEIGHBOURS(PGH2,PERMNEIGHBOURS(PGH2,1)+1).NE.0) THEN
               PRINT*,I1, "ERROR", PGH, PERMNEIGHBOURS(PGH,1),PGH2
               STOP
               ENDIF
               PERMNEIGHBOURS(PGH, PERMNEIGHBOURS(PGH,1)+1) = PGH2
               PERMNEIGHBOURS(PGH2,PERMNEIGHBOURS(PGH2,1)+1) = PGH
               ATOMS2PERM(HH)=PGH
               ATOMS2PERM(H2)=PGH2
               ATCENTRE2PERM(PG_CENTRE) = PGH
               ATCENTRE2PERM(PG_CENTRE2)= PGH2
            ENDIF
         ENDIF

      ENDDO


      !ONE SPECIAL PERMGROUP FOR ARGININE, NOT INVOLVING A CENTRE 2
      IF (ARGININE) THEN
         DO I1=1,NRES
               H2=0;BH=0;HH=0; PG_CENTRE2=0;PG_CENTRE=0; PG_CENTREAC=0
               IF (IH(M02+I1-1)=='ARG'.OR.IH(M02+I1-1)=='NARG' &
     &                 .OR.IH(M02+I1-1)=='CARG') THEN
                   DO K1=IX(I02+I1-1),IX(I02+I1)-1
                      SELECT CASE (IH(M04+K1-1))
                         CASE ('NH1 ')
                              PG_CENTRE2=K1
                         CASE ('CZ  ')
                              PG_CENTRE=K1
                         CASE ('NH2 ')
                              PG_CENTREAC=K1; HH=K1
                         CASE ('HH11')
                              H2=K1
                         CASE ('HH21')
                              BH=K1
                      END SELECT 
                   ENDDO
                   CALL FINDPG_NOSWAPS(HH,H2,BH,PGH,PGH2,PGBH)
            !PRINT*, "AFTER FINDPG HH,H2,BH,PGH,PGH2,PGBH", HH,H2,BH,PGH,PGH2,PGBH
                   IF (PERMNEIGHBOURS(PGH,1).NE.0) THEN
                      PRINT*, "ERROR, ONLY 1 PERMGROUP ABOUT", PGH
                      STOP
                   ENDIF
                   PERMNEIGHBOURS(PGH,1)= 2
                   PERMNEIGHBOURS(PGH2,1)= 1
                   PERMNEIGHBOURS(PGBH,1)= 1
                   PERMNEIGHBOURS(PGH,2) = PGBH;PERMNEIGHBOURS(PGH,3)=PGH2
                   PERMNEIGHBOURS(PGBH,2) = PGH  
                   PERMNEIGHBOURS(PGH2,2)= PGH
                   ATOMS2PERM(HH)=PGH;ATOMS2PERM(H2)=PGH2;ATOMS2PERM(BH)=PGBH
                   ATCENTRE2PERM(PG_CENTRE) = PGH
                   ATCENTRE2PERM(PG_CENTRE2)= PGH2 
                   ATCENTRE2PERM(PG_CENTREAC)=PGBH
               ENDIF
         ENDDO
      ENDIF
         
      IF (DEBUG) THEN
         DO I1=1, NPERMGROUP
            PRINT '(A15,I2,2I4)', "PERMNEIGHBOURS", PERMNEIGHBOURS(I1,1), PERMNEIGHBOURS(I1,2), PERMNEIGHBOURS(I1,3)
         ENDDO
      ENDIF
      DO I1=1, NPERMGROUP
         !IF (I1.EQ.8.OR.I1.EQ.10.OR.I1.EQ.20.OR.I1.EQ.30.OR.I1.EQ.124.OR.I1.EQ.29.OR.I1.EQ.41.OR.I1.EQ.43.OR.I1.EQ.38) CYCLE
         CALL FINDPGCHAIN(I1)
      ENDDO
      IF (DEBUG) THEN
         DO I1=1, NPERMGROUP
            PRINT*, PERMCHAIN(I1,:)
         ENDDO
      ENDIF

      !THIS WOULD BE IF I JUST WANTED TO CALCULATE THE RELEVANT DIHEDRALS
      !CALL LINDH2PERMG(ATOMS2PERM, ATCENTRE2PERM)
 
      DEALLOCATE(MBBONDNUM)
      DEALLOCATE(MBADJACENT)
      DEALLOCATE(CENTER2)


      END SUBROUTINE FINDPERMDIH
! *************************************************
      SUBROUTINE LINDH2PERMG(ATOMS2PERM,ATCENTRE2PERM)
!MSB50 SEE AMB_NATINTERS.F90
!FINIDING NUMBER OF DIHEDRAL (LDH) FOR PARTICULAR PERMGROUP
!ALSO NEED DIHC TO FIND PHI1 (FROM PREVIOUS LDH FIRST PREVDIH IN GROUP?)
!               AND FOR ALIGNMENT
      USE INTCOMMONS, ONLY: STARTLINDH, NLDH, LINDIH, PERMNEIGHBOURS
      USE COMMONS, ONLY: NATOMS
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: ATOMS2PERM(NATOMS)
      INTEGER, INTENT(IN) ::ATCENTRE2PERM(NATOMS)
      INTEGER:: LDH, I1, DIHC, CURPHI, PG
      INTEGER:: INFO(-1:8)
      INTEGER:: FIRST(NATOMS), SECOND(NATOMS)
      INTEGER:: ATOMS(2)

      FIRST(NATOMS)=0; SECOND(NATOMS) = 0
      DO LDH =1, NLDH
         IF (LINDIH(LDH,-1).NE.1.AND.LINDIH(LDH,0).NE.1) THEN
            ATOMS(1) = LINDIH(LDH,1)
            ATOMS(2) = LINDIH(LDH,2)
            DO I1 = 1,2
            IF (ATCENTRE2PERM(ATOMS(I1)).NE.0) THEN
!               PG = ATOMS2PERM(ATOMS(I1)) !DUNNO?
                PG = ATCENTRE2PERM(ATOMS(I1))
               IF (FIRST(ATOMS(I1))==0) THEN
                  FIRST(ATOMS(I1))=1
                  PERMNEIGHBOURS(PG, 3+PERMNEIGHBOURS(PG,1))=LDH 
               !SECOND DIHEDRAL INVOLVED
! EVERY GROUP HAS GOT TWO DIHEDRALS THAT CHANGE THOUGH, SO THIS IS NOT QUITE RIGHT YET. STORE THE OTHER ONE TOO!
               ELSEIF (FIRST(ATOMS(I1))==1.AND.SECOND(ATOMS(I1))==0) THEN
                  SECOND(ATOMS(I1))=1
                  PERMNEIGHBOURS(PG, 5+PERMNEIGHBOURS(PG,1))=LDH 
               ELSEIF (FIRST(ATOMS(I1))==1.AND.SECOND(ATOMS(I1))==1) THEN
                  PRINT*, "ERROR IN LINDH2PERM"; STOP
               ENDIF
            ENDIF
            ENDDO
            !MAYBE DO THE ABOVE FOR ALL PGS, COULD FACILITATE THINGS
        ENDIF
      ENDDO
      END SUBROUTINE LINDH2PERMG
            
!*****************************************************
      SUBROUTINE FINDPERMGROUP(I1,I2, I3,PG1, PG2, PG3)
!MSB50 - FOR ATOMS IN THREE DIFF PERMGROUPS FIND PERMGROUP (SEE KEYWORDS.F, PERMDIST)
      USE KEY
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: I1, I2, I3
      INTEGER, INTENT(OUT) :: PG1, PG2, PG3
      INTEGER :: START, III, TOTAL, SW,II,JJ
      INTEGER :: PGATOMS(8), PGS(3), ATOMS(3)
      LOGICAL :: FOUND(3)

      ATOMS(:)=0; PGS(:)=0; FOUND(:)=.FALSE.
      ATOMS(1)=I1; ATOMS(2)=I2; ATOMS(3)=I3
      PG1=0;PG2=0;PG3=0
!      PG1(1)=PG1; PGS(2)=PG2; PGS(3)=PG3
      IF (I2.EQ.0) FOUND(2)=.TRUE.
      IF (I3.EQ.0) FOUND(3)=.TRUE.
      START = 1
!       WRITE(*,*) 'IN FINDPERMGROUP, PGS(:)', PGS(:)
!       STOP
      DO III = 1, NPERMGROUP !LOOP OVER ALL PG'S
         PGATOMS(:) = 0 !PGATOMS ARE ALL ATOMS IN THIS PERMGROUP
         IF (NPERMSIZE(III) == 2) THEN
            PGATOMS(1) = PERMGROUP(START);PGATOMS(2)= PERMGROUP(START+1)
            DO SW = 1, NSETS(III)
!              PGATOMS(2+2*(SW-1)+1) = SWAP1(III, SW)
!              PGATOMS(2+2*SW)=SWAP2(III, SW)
               PGATOMS(2+2*(SW-1)+1) = SETS(PGATOMS(1), SW)
               PGATOMS(2+2*SW)=SETS(PGATOMS(2), SW)
            ENDDO
            TOTAL = 2 + 2*NSETS(III)
         ELSEIF (NPERMSIZE(III) == 3) THEN
            PGATOMS(1) = PERMGROUP(START);PGATOMS(2)= PERMGROUP(START+1)
            PGATOMS(3) = PERMGROUP(START+2)
            TOTAL = 3
         ELSE 
            STOP
         ENDIF

         START = START + NPERMSIZE(III)
         DO II = 1, TOTAL
            DO JJ = 1,3 !CHECK WHETHER ONE OF YOUR ATOMS IS IN THIS PERMGROUP
               IF (ATOMS(JJ).EQ.PGATOMS(II)) THEN
                  PGS(JJ)=III   
                  FOUND(JJ)=.TRUE. 
               ENDIF
            ENDDO
         ENDDO
         IF (FOUND(1).AND.FOUND(2).AND.FOUND(3)) THEN
            PG1=PGS(1); PG2=PGS(2);PG3=PGS(3)
            EXIT
         ENDIF
      ENDDO
     
      END SUBROUTINE FINDPERMGROUP
! **************************************************************
      SUBROUTINE FINDPG_NOSWAPS(I1,I2,I3,PG1,PG2,PG3)
!MSB50 - FOR ATOMS IN THREE DIFF PERMGROUPS FIND PERMGROUP (SEE KEYWORDS.F, PERMDIST)
!HERE DON'T INCLUDE SWAPS, SO IF I2 AND I3 ARE IN PG1, BUT ALSO TURN OUT IN PGS INDEPENDENTLY
      USE KEY
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: I1, I2, I3
      INTEGER, INTENT(OUT) :: PG1, PG2, PG3
      INTEGER :: START, III, TOTAL, II,JJ
      INTEGER :: PGATOMS(3), PGS(3), ATOMS(3)
      LOGICAL :: FOUND(3) 

      ATOMS(:)=0; PGS(:)=0; FOUND(:)=.FALSE.
      ATOMS(1)=I1; ATOMS(2)=I2; ATOMS(3)=I3
      PGS(1)=PG1; PGS(2)=PG2; PGS(3)=PG3
      IF (I2.EQ.0) FOUND(2)=.TRUE.
      IF (I3.EQ.0) FOUND(3)=.TRUE.
      START = 1
      DO III = 1, NPERMGROUP !LOOP OVER ALL PG'S
         PGATOMS(:) = 0 !PGATOMS ARE ALL ATOMS IN THIS PERMGROUP
         IF (NPERMSIZE(III) == 2) THEN
            PGATOMS(1) = PERMGROUP(START);PGATOMS(2)= PERMGROUP(START+1)
            TOTAL = 2 
         ELSEIF (NPERMSIZE(III) == 3) THEN
            PGATOMS(1) = PERMGROUP(START);PGATOMS(2)= PERMGROUP(START+1)
            PGATOMS(3) = PERMGROUP(START+2)
            TOTAL = 3
         ELSE
            STOP
         ENDIF

         START = START + NPERMSIZE(III)
         DO II = 1, TOTAL
            DO JJ = 1,3 !CHECK WHETHER ONE OF YOUR ATOMS IS IN THIS PERMGROUP
               IF (ATOMS(JJ).EQ.PGATOMS(II)) THEN
                  PGS(JJ)=III
                  FOUND(JJ)=.TRUE.
               ENDIF
            ENDDO
         ENDDO
         IF (FOUND(1).AND.FOUND(2).AND.FOUND(3)) THEN
            PG1=PGS(1); PG2=PGS(2);PG3=PGS(3)
            EXIT
         ENDIF
      ENDDO
      END SUBROUTINE FINDPG_NOSWAPS

! ***************************************************
      SUBROUTINE LOOPCENTERS(CN1, CT2, CN2, CN3,I1)
!MSB50 - FINDS ATOM OF CERTAIN CENTERTYPE BONDED TO CENTERTYPES 2 OR 4
        USE INTCOMMONS
        IMPLICIT NONE
        INTEGER, INTENT(IN) :: CN1 ! FIRST CENTER - NUMBER, NOT ATOM
        INTEGER, INTENT(IN) :: CT2! CENTERTYPE OF ATOM ADJACENT TO IT -NOT ATOM
        INTEGER, INTENT(OUT) :: CN2, CN3 ! NUMBER OF ABOVE CENTER (MAXIMALLY 2)
        INTEGER, INTENT(IN)  :: I1 !WHERE TO LOOP FROM, IN CASE YOU KNOW
        INTEGER :: L1, A2, M1,A3, CT1
     
        CN2 = 0
        CN3 = 0
        CT1 = CENTERS(CN1, 0)
        IF (CT1 == 2) THEN
           A2 = CENTERS(CN1,1) !ADJACENT TO IT -CAN DO THIS AS NON-TERMINAL AT BEGINNING
           A3 = CENTERS(CN1,2)
           DO M1 = I1, NCNT
              IF ((CENTERS(M1,1)==A2 .AND. CENTERS(M1,0)==CT2)) THEN
                 CN2 = M1
              ELSEIF ((CENTERS(M1,1)==A3 .AND. CENTERS(M1,0)==CT2)) THEN
                 CN3 = M1
              ENDIF
              IF (CN2 .NE. 0 .AND. CN3 .NE. 0 ) EXIT 
           ENDDO
        ELSEIF (CT1 == 4) THEN
           A2 = CENTERS(CN1, 1)
           DO M1 = I1, NCNT
             IF ((CENTERS(M1,1)==A2 .AND. CENTERS(M1,0)==CT2)) THEN
                 CN2 = M1
                 EXIT
             ENDIF
           ENDDO
        ENDIF
      END SUBROUTINE LOOPCENTERS

! ****************************************************
      SUBROUTINE FINDPGCHAIN(I)
!MSB50 - STORES PER PERMGROUP WHICH PERMNEIGHBOURS(PG,1) .GT. 1 (I.E. COUPLED
! PERMGROUPS) HOW LARGE THE SET IS IT IS PART OF - I.E. FOR LYSINE IT WOULD BE
! FIVE, WHICH IS CURRENTLY MAXIMUM
         USE INTCOMMONS, ONLY: PERMNEIGHBOURS, PERMCHAIN
         USE KEY, ONLY: NPERMGROUP
         IMPLICIT NONE
         INTEGER, INTENT(IN) ::I
         INTEGER :: PGCHAIN(5)
         INTEGER :: PG2, PG3, PG4, PG5, II, LEN_CHAIN,START_PG

         IF (.NOT.ALLOCATED(PERMCHAIN)) THEN
             ALLOCATE(PERMCHAIN(NPERMGROUP,6))
             PERMCHAIN(:,:)=0
         ENDIF

         LEN_CHAIN=0; PGCHAIN(:)=0
         IF (PERMNEIGHBOURS(I,1).EQ.0) THEN
            RETURN
         ELSEIF (PERMNEIGHBOURS(I,1).EQ.1) THEN
            START_PG=I
         ELSEIF (PERMNEIGHBOURS(I,1).EQ.2) THEN
            PG2=PERMNEIGHBOURS(I,2); PG3= PERMNEIGHBOURS(I,3)
            IF (PERMNEIGHBOURS(PG2,1)==1) THEN
              START_PG= PG2
            ELSEIF (PERMNEIGHBOURS(PG3,1)==1) THEN
              START_PG= PG3
            ELSE
              IF (PERMNEIGHBOURS(PG2,2).NE.I) THEN
                 IF (PERMNEIGHBOURS(PERMNEIGHBOURS(PG2,2),1).NE.1) THEN
                     PRINT*, "FINDPGCHAIN: ERROR! CHAIN TOO LONG"
                 ELSE
                     START_PG=PERMNEIGHBOURS(PG2,2)
                 ENDIF
              ELSE
                 IF (PERMNEIGHBOURS(PERMNEIGHBOURS(PG2,1),1).NE.1) THEN
                     PRINT*, "FINDPGCHAIN: ERROR! CHAIN TOO LONG"
                 ELSE
                     START_PG=PERMNEIGHBOURS(PG2,1)
                 ENDIF
              ENDIF
            ENDIF
         ENDIF

         PG2=0;PG3=0;PG4=0;PG5=0; PGCHAIN(:)=0
         LEN_CHAIN = LEN_CHAIN+1
         PGCHAIN(1) = START_PG
         PG2=PERMNEIGHBOURS(START_PG,2) !HAS ONLY ONE NEIGHBOUR
         LEN_CHAIN = LEN_CHAIN+1; PGCHAIN(2) = PG2
         IF (PERMNEIGHBOURS(PG2,1).EQ.2) THEN !ANOTHER NEIGHBOUR THAN START_PG
            IF (PERMNEIGHBOURS(PG2,2).NE.START_PG) THEN
                PG3=PERMNEIGHBOURS(PG2,2)
                LEN_CHAIN=LEN_CHAIN+1; PGCHAIN(3)=PG3
            ELSE
                PG3=PERMNEIGHBOURS(PG2,3)
                LEN_CHAIN=LEN_CHAIN+1; PGCHAIN(3)=PG3
            ENDIF
            IF (PG3.NE.0.AND.PERMNEIGHBOURS(PG3,1).EQ.2) THEN !ANOTHER NEIGHBOUR-OTHER SIDE 
                IF (PERMNEIGHBOURS(PG3,2).NE.PG2) THEN
                   PG4=PERMNEIGHBOURS(PG3,2)
                   LEN_CHAIN=LEN_CHAIN+1; PGCHAIN(4)=PG4
                ELSE
                   PG4=PERMNEIGHBOURS(PG3,3)
                   LEN_CHAIN=LEN_CHAIN+1; PGCHAIN(4)=PG4
                ENDIF
                IF (PG4.NE.0.AND.(PERMNEIGHBOURS(PG4,1).EQ.2)) THEN
                   IF (PERMNEIGHBOURS(PG4,2).NE.PG3) THEN
                      PG5=PERMNEIGHBOURS(PG4,2)
                      LEN_CHAIN=LEN_CHAIN+1; PGCHAIN(5)=PG5
                   ELSE
                      PG5=PERMNEIGHBOURS(PG4,3)
                      LEN_CHAIN=LEN_CHAIN+1; PGCHAIN(5)=PG5
                   ENDIF
                   IF (PG5.NE.0.AND.(PERMNEIGHBOURS(PG5,1).EQ.2)) THEN
                      PRINT*,"FINDPGCHAIN>CHAIN LONGER THAN ATM ALLOWED"
                      !AS ONLY LYSINE - 5 COUPLED PERMGROUPS
                      STOP
                   ENDIF
                ENDIF
             ENDIF
         ENDIF

         IF (LEN_CHAIN.LT.2.OR.LEN_CHAIN.GT.5) THEN
            PRINT*, "FINDPGCHAIN - STH GONE WRONG"
            STOP
         ELSE
            PERMCHAIN(START_PG,1) = LEN_CHAIN; PERMCHAIN(PG2,1) = LEN_CHAIN
            PERMCHAIN(START_PG,2:)=PGCHAIN(:); PERMCHAIN(PG2,2:)=PGCHAIN(:)
            IF (LEN_CHAIN.GE.3) THEN
               PERMCHAIN(PG3,1)=LEN_CHAIN
               PERMCHAIN(PG3,2:)=PGCHAIN(:)
               IF (LEN_CHAIN.GE.4) THEN
                  PERMCHAIN(PG4,1)=LEN_CHAIN
                  PERMCHAIN(PG4,2:)=PGCHAIN(:)
                  IF (LEN_CHAIN.GE.5) THEN
                     PERMCHAIN(PG5,1)=LEN_CHAIN
                     PERMCHAIN(PG5,2:)=PGCHAIN(:)
                  ENDIF
               ENDIF
            ENDIF
         ENDIF

      END SUBROUTINE FINDPGCHAIN



! *****************************************************
!MSB50 - GIVE IT ATOM INDEX AND IT RETURNS NAME OF RESIDUE AND RESIDUE NUMBER
      SUBROUTINE GETRESID(ATNUM, RESNAME, RESNUM)
      USE MODAMBER9, ONLY: IX, I02, NRES, M02,IH
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: ATNUM
      CHARACTER(LEN=4), INTENT(OUT):: RESNAME
      INTEGER, INTENT(OUT) :: RESNUM
      INTEGER II

      DO II=1, NRES 
          IF (IX(I02+II-1).LE.ATNUM .AND. IX(I02+II).GT.ATNUM) THEN
             RESNUM = II
             RESNAME = IH(M02+II-1)
          EXIT
          ENDIF
      ENDDO

      END SUBROUTINE GETRESID

!*********************************************************
      SUBROUTINE PROL_PERMUTE(A1,A2,PTEST, RS,RF, DISTANCE)
      USE MODAMBER9, ONLY:  NRES, M02, IH, M04
      USE COMMONS, ONLY: NATOMS
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: A1, A2
      LOGICAL, INTENT(IN)::PTEST
      DOUBLE PRECISION, INTENT(IN) ::RS(3*NATOMS)
      DOUBLE PRECISION, INTENT(INOUT)::RF(3*NATOMS)
      DOUBLE PRECISION, INTENT(OUT):: DISTANCE
      DOUBLE PRECISION:: RFTMP(3*NATOMS)
      DOUBLE PRECISION:: DIST_ORIG

      RFTMP(:)=RF(:)
      DIST_ORIG=DOT_PRODUCT(RF-RS, RF-RS)
      IF (((IH(M04+A1-1).EQ.'HB2 '.OR.IH(M04+A1-1).EQ.'HB3 ').AND.&
     &  (IH(M04+A2-1).EQ.'HB2 '.OR.IH(M04+A2-1).EQ.'HB3 ')).OR.   &
     & ((IH(M04+A1-1).EQ.'HG2 '.OR.IH(M04+A1-1).EQ.'HG3 ').AND.&
     &  (IH(M04+A2-1).EQ.'HG2 '.OR.IH(M04+A2-1).EQ.'HG3 ')).OR.   &
     & ((IH(M04+A1-1).EQ.'HD2 '.OR.IH(M04+A1-1).EQ.'HD3 ').AND.&
     &  (IH(M04+A2-1).EQ.'HD2 '.OR.IH(M04+A2-1).EQ.'HD3 '))) THEN
         
          IF (PTEST) PRINT*, "PROL FOUND"
          RF(3*(A1-1)+1:3*A1)=RFTMP(3*(A2-1)+1:3*A2)
          RF(3*(A2-1)+1:3*A2)=RFTMP(3*(A1-1)+1:3*A1)
          DISTANCE=DOT_PRODUCT(RF-RS, RF-RS)
          IF (PTEST) PRINT*, "PROL_PERMUTE> DISTANCE OLD, NEW", DIST_ORIG, DISTANCE
          IF (DISTANCE.LT.DIST_ORIG) THEN
             IF (PTEST) PRINT*, "PROL_PERMUTE> KEEP PERMUTATION", & 
     &          DIST_ORIG,A1, A2, DISTANCE
          ELSE
             RF(:) =RFTMP(:)
          ENDIF
      ELSE
         PRINT*, "PROL_PERMUTE> ERROR! NOT PROLINE -CHECK INTMINPERM"
         STOP
      ENDIF
      RETURN
 
      END SUBROUTINE PROL_PERMUTE 


