C
! GPL LICENSE INFO {{{
C   OPTIM: A PROGRAM FOR OPTIMIZING GEOMETRIES AND CALCULATING REACTION PATHWAYS
C   COPYRIGHT (C) 1999-2006 DAVID J. WALES
C   THIS FILE IS PART OF OPTIM.
C
C   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C   (AT YOUR OPTION) ANY LATER VERSION.
C
C   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
C   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
C   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
C   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
C
C   }}}
C
!BFGSTS: HYBRID EIGENVECTOR-FOLLOWING/GRADIENT MINIMIZATION {{{
C***********************************************************************
C
C  THIS SUBROUTINE IS DESIGNED TO PERFORM A HYBRID EIGENVECTOR-FOLLOWING/GRADIENT
C  MINIMIZATION OPTIMIZATION FOR LARGE SYSTEMS WHERE WE DO NOT WANT TO 
C  DIAGONALIZE THE WHOLE HESSIAN.
C
C***********************************************************************
C
      SUBROUTINE BFGSTS(ITMAX,COORDS,ENERGY,GRAD,MFLAG,RMS,EVALMIN,EVALMAX,VECS,ITER,POTCALL,PTEST)
! DOXYGEN COMMENTS {{{
!> \NAME BFGSTS
!> \BRIEF PERFORM HYBRID EIGENVECTOR-FOLLOWING/GRADIENT MINIMIZATION FOR LARGE SYSTEMS 
!> \PARAM ITMAX
!> \PARAM COORDS
!> \PARAM ENERGY
!> \PARAM GRAD
!> \PARAM MFLAG
!> \PARAM RMS 
!> \PARAM EVALMIN
!> \PARAM EVALMAX
!> \PARAM VECS
!> \PARAM ITER
!> \PARAM POTCALL
!> \PARAM PTEST
! }}}
! MODULES {{{
      USE COMMONS
      USE KEY
      USE VECCK
      USE ZWK
      USE MODCHARMM
      USE MODHESS
      USE PORFUNCS
! }}}
      IMPLICIT NONE
! SUBROUTINE PARAMETERS {{{

      INTEGER ITMAX, ITER 
      LOGICAL POTCALL, PTEST, MFLAG
      DOUBLE PRECISION, DIMENSION(3*NATOMS) :: COORDS, GRAD, VECS
      DOUBLE PRECISION  ENERGY,RMS, EVALMAX, EVALMIN 
!}}}
! LOCAL PARAMETERS  {{{

      INTEGER J1, J2, INEG, J, NS, I, K1, NBFGS, FRAME, ITDONE, J3, NSTEPMINSAVE
      DOUBLE PRECISION SCRATCH(6*NATOMS),SUM,AVG,FOBNEW,DUMMY,
     1                 FOB,PSTEP,DPRAND,FIXDIR(3*NATOMS),TEMPA(9*NATOMS),
     2                 STPMAG,COORDSN(3*NATOMS),VECSP(3*NATOMS),
     3                 XP1,XP2,E1,E2,DELE,SCALE,EPER,EOLD,RMS2,SOVER,EREAL,XRAT(3*NATOMS),
     4                 XFOB(3*NATOMS), STEP(3*NATOMS), XPSTEP(3*NATOMS), CSTEP(3*NATOMS), PFOB(3*NATOMS),
     5                 AV(6),SSTPMAG,RAT1,RAT2,TEMP,LP1,LP2,LP,VECL(3*NATOMS),DOTOPT,PROJ1,PROJ2
C     EXTERNAL OP, IOVECT
      CHARACTER(LEN=80) :: FNAME
      LOGICAL AWAY, LINE, PVFLAG, RESET, STEST,  FIXDSAVE
      COMMON /PVF/ PVFLAG
      LOGICAL CONNECTT, DUMPPATH, READPATH, CALCRATES, STOPFIRST, CONVERGED
      INTEGER NCONNECT
      DOUBLE PRECISION TEMPERATURE, HRED
      COMMON /CONN/ STOPFIRST, CONNECTT, NCONNECT, DUMPPATH, READPATH, CALCRATES, TEMPERATURE, HRED
C
C  ASSIGN ENOUGH MEMORY TO WORK FOR A BLOCKSIZE OF 32 TO BE POSSIBLE.
C  THIS IS FOR DSYEVR.
C
      INTEGER IWORK(33*3*NATOMS)
      INTEGER ILWORK, LWORK, NFOUND, ISUPPZ(2*3*NATOMS)
      INTEGER INFO, ISTAT
      DOUBLE PRECISION WORK(33*3*NATOMS), ABSTOL, DIAG(3*NATOMS), DLAMCH
      LOGICAL KNOWE, KNOWG, KNOWH
      COMMON /KNOWN/ KNOWE, KNOWG, KNOWH
! }}}
      SAVE
! SUBROUTINE BODY  {{{

      LWORK=33*3*NATOMS
      ILWORK=33*3*NATOMS

      IF ((ZSYM(1)(1:1).EQ.'W').AND.(.NOT.BFGSSTEP)) THEN
         PRINT*,'BFGSTS PROCEDURES HAVE NOT BEEN PROGRAMMED FOR TIP POTENTIALS'
         CALL FLUSH(6,ISTAT)
         STOP
      ENDIF
      FIXDSAVE=FIXD
      IF ((HINDEX.GT.1).AND.(.NOT.NOIT)) THEN
         WRITE(*,'(A)') 'FOR HINDEX > 1 YOU MUST USE NOIT WITH BFGSTS'
         CALL FLUSH(6,ISTAT)
         STOP
      ENDIF
!
! CHECK FOR CONSISTENT CONVERGENCE CRITERIA ON RMS GRADIENT IN MYLBFGS AND EF PART.
!     
      IF (GMAX.NE.CONVR) THEN
         IF (DEBUG) PRINT '(2(A,G20.10),A)','BFGSTS> WARNING - GMAX ',GMAX,' IS DIFFERENT FROM CONVR ',CONVR,' - RESETTING'
         GMAX=MIN(CONVR,GMAX)
         CONVR=MIN(CONVR,GMAX)
      ENDIF
      IF (MINMAX.GE.CONVU) THEN
         IF (DEBUG) PRINT '(2(A,G20.10),A)','BFGSTS> WARNING - CONVU <= MINMAX - RESETTING CONVU'
         CONVU=2*MINMAX
      ENDIF
!
!  RESET MAXIMUM STEP SIZES IN CASE THIS ISN'T THE FIRST CALL TO EFOL.
!
      IF (DEBUG) PRINT '(A,G20.10)',' BFGSTS> RESETTING MAXIMUM STEP SIZES TO ',MXSTP
      DO J1=1,NOPT
         STPMAX(J1)=MXSTP
      ENDDO

      ITER=1
      FRAME=1
      CONVERGED=.TRUE.
C
C  IF DUMPV IS .TRUE. THEN VECTOR.DUMP IS ALREADY OPEN AND ATTACHED TO UNIT 44.
C  SGI COMPILER WON;T ALLOW US TO ATTACH IT TO ANOTHER UNIT.
C  VECTOR.DUMP COULD CONTAIN MULTIPLE DUMPS FOR MORE THAN THE LAST STEP, SO WE 
C  HAVE TO MAKE SURE WE GET THE RESULTS FOR THE LAST STEP.
C
      IF (READV.AND.(ITER.EQ.1)) THEN   
         IF (DUMPV) THEN
            REWIND(44)
211         READ(44,*,END=111) EVALMIN
            READ(44,*) (VECS(J1),J1=1,NOPT)
            GOTO 211
111         CONTINUE
         ELSE
            IF (FILTH.EQ.0) THEN
               FNAME='VECTOR.DUMP'
            ELSE
               WRITE(FNAME,'(A)') 'VECTOR.DUMP.'//TRIM(ADJUSTL(FILTHSTR))
            ENDIF
   
            OPEN(UNIT=45,FILE=FNAME,STATUS='OLD')
20          READ(45,*,END=10) EVALMIN
            READ(45,*) (VECS(J1),J1=1,NOPT)
            GOTO 20
10          CLOSE(45)
         ENDIF
         WRITE(*,'(A,F20.10)') ' REACTION VECTOR READ SUCCESSFULLY. EIGENVALUE=   ',EVALMIN
         NS=100
      ENDIF
      IF (FREEZE) THEN
         DO J1=1,NATOMS
            IF (FROZEN(J1)) THEN
               VECS(3*(J1-1)+1)=0.0D0
               VECS(3*(J1-1)+2)=0.0D0
               VECS(3*(J1-1)+3)=0.0D0
            ENDIF
         ENDDO
      ENDIF

      STEST=.TRUE.
      IF (NOHESS) STEST=.FALSE.
      IF (READV.AND.(ITER.EQ.1)) STEST=.FALSE.
90    IF (PTEST) PRINT*
      NUP=HINDEX
      IF ((.NOT.BFGSSTEP).AND.PTEST) WRITE(*,11) ITER
11          FORMAT (' BFGSTS> BEGINNING OF OPTIMIZATION CYCLE ', I4,'.',/
     1              ' ---------------------------------------')
      FIXIMAGE=.FALSE.
      IF ((FIXAFTER.GT.0).AND.(ITER.GT.FIXAFTER)) FIXIMAGE=.TRUE.
      IF (CHRMMT) NCHENCALLS = 999 ! MAKE SURE NON-BOND LIST IS UPDATED AT THE START OF EACH TS SEARCH.
      IF (POTCALL) THEN
         IF (PV.AND.(.NOT.BFGSSTEP)) THEN
            IF (.NOT.KNOWE) CALL POTENTIAL(COORDS,ENERGY,GRAD,.FALSE.,.FALSE.,RMS,.FALSE.,.FALSE.)
            PVFLAG=.FALSE.
            CALL PVOPT(COORDS,ENERGY,GRAD)
         ENDIF
         IF ((.NOT.KNOWG).OR.(STEST.AND.(.NOT.KNOWH))) CALL POTENTIAL(COORDS,ENERGY,GRAD,.TRUE.,STEST,RMS,PTEST,.FALSE.)
      ENDIF
      CALL DUMPP(COORDS,ENERGY)
      IF ((.NOT.VARIABLES).AND.NOIT.AND.STEST) THEN
         IF (RINGPOLYMERT.AND.(RPSYSTEM(1:4).EQ.'AECK')) THEN
         ELSE IF (ZSYM(NATOMS).EQ.'SY') THEN
            CALL SHIFTSTOCK(COORDS,NATOMS)
         ELSEIF (RBAAT) THEN
            CALL SHIFTRIGID(COORDS,NATOMS)
         ELSEIF (ZSYM(NATOMS).EQ.'TH') THEN
            CALL SHIFTHTH(COORDS,NATOMS)
         ELSE
            CALL SHIFTH(COORDS,.TRUE.,NOPT,NATOMS,ATMASS)
            IF (TWOD) THEN
               DO J1=1,NATOMS
                  J2=3*J1
                  DO J3=1,NATOMS
                     HESS(J2,3*(J3-1)+1)=0.0D0
                     HESS(J2,3*(J3-1)+2)=0.0D0
                     HESS(J2,3*(J3-1)+3)=0.0D0
                     HESS(3*(J3-1)+1,J2)=0.0D0
                     HESS(3*(J3-1)+2,J2)=0.0D0
                     HESS(3*(J3-1)+3,J2)=0.0D0
                  ENDDO
                  HESS(J2,J2)=SHIFTV
               ENDDO
            ENDIF
         ENDIF
      ENDIF
      IF (.NOT.((READV.AND.BFGSSTEP).OR.(.NOT.POTCALL))) THEN
C        IF (DEBUG) PRINT*,'THIS LINE IS NEEDED TO PREVENT MISCOMPILATION BY SUN FORTE DEVELOPER 7' ! SIGH !!!
         IF (FIXD.AND.(ITER.EQ.1)) THEN
            IF (CONNECTT) THEN
               DO J1=1,NOPT
                  FIXDIR(J1)=VECS(J1)
               ENDDO
            ELSE
               DO J1=1,NOPT
                  DUMMY=2*(DPRAND()-0.5D0)
                  FIXDIR(J1)=DUMMY
               ENDDO
            ENDIF
            CALL ORTHOGOPT(FIXDIR,COORDS,.TRUE.)
            IF (.TRUE.) CALL HSMOVE(COORDS,COORDSN,FIXDIR,PSTEP,PTEST)
            EVALMIN=1.0D0
         ELSE IF (FIXD) THEN
            CALL ORTHOGOPT(FIXDIR,COORDS,.TRUE.)
            IF (.TRUE.) CALL HSMOVE(COORDS,COORDSN,FIXDIR,PSTEP,PTEST)
            EVALMIN=1.0D0
         ENDIF
         IF (.NOT.NOHESS) THEN 
            IF (.NOT.NOIT) THEN
               CALL ITEIG(ITER,COORDS,VECS,EVALMIN,EVALMAX,NS,SOVER,PTEST,VECL,CONVERGED)
            ELSE
               ABSTOL=DLAMCH('SAFE  MINIMUM')
               IF (ITER.GT.1) THEN
                  DO J1=1,NOPT
                     VECSP(J1)=VECS(J1)
                  ENDDO
               ENDIF
               CALL DSYEVR('V','I','U',NOPT,HESS,SIZE(HESS,1),0.0D0,1.0D0,1,HINDEX,ABSTOL,NFOUND,DIAG,
     1                        ZWORK,3*NATOMS,ISUPPZ,WORK,
     2                        LWORK, IWORK, ILWORK, INFO )
               IF (INFO.NE.0) PRINT*,'WARNING - INFO=',INFO,' IN DSYEVR'
C              PRINT*,'OPTIMAL AND ACTUAL VALUES OF LWORK=',WORK(1),LWORK
C              PRINT*,'OPTIMAL AND ACTUAL VALUES OF ILWORK=',IWORK(1),ILWORK
               EVALMIN=DIAG(1)
               SOVER=0.0D0
               DO J1=1,NOPT
                  VECS(J1)=ZWORK(J1,1)
                  IF (ITER.GT.1) SOVER=SOVER+VECS(J1)*VECSP(J1)
               ENDDO
               IF (PTEST) THEN
                  IF (ITER.GT.1) THEN
                     WRITE(*,'(A,F15.7,A,F15.7)') ' SMALLEST EIGENVALUE=',EVALMIN,' OVERLAP WITH PREVIOUS VECTOR=',SOVER
                  ELSE
                     WRITE(*,'(A,F15.7,A,F15.7)') ' SMALLEST EIGENVALUE=',EVALMIN
                  ENDIF
               ENDIF
               DO I=1,NOPT
                  SCRATCH(I) = COORDS(I)
               ENDDO
               DO I=1,HINDEX
                  XFOB(I)=0.0D0
                  DO J = 1,NOPT
                     XFOB(I)=XFOB(I)+GRAD(J)*ZWORK(J,I)
                  ENDDO
               ENDDO
C
C  FIND THE VECTOR OF STPMAX VALUES BY COMPARING PREDICTED AND
C  ACTUAL SECOND DERIVATIVES FOR EACH EIGENVECTOR.
C
               IF ((ITER.GT.1).AND.(ISTCRT.EQ.10)) THEN
                  DO J1=1,NOPT
                     TEMPA(J1)=STPMAX(J1)
                  ENDDO
                  K1=0
                  DO J1=1,HINDEX
                     XRAT(J1)=0.0D0
                     K1=K1+1
                     IF (DABS(XPSTEP(K1)).GT.1.0D-40) THEN
C
C  ALLOW FOR POSSIBLE PHASE CHANGE IN THE EIGENVECTOR. JUST TAKE THE SMALLER VALUE.
C
                        RAT1=DABS(( XFOB(J1)-PFOB(K1))/(DIAG(J1)*XPSTEP(K1))-1.0D0)
                        RAT2=DABS((-XFOB(J1)-PFOB(K1))/(DIAG(J1)*XPSTEP(K1))-1.0D0)
                        XRAT(J1)=MIN(RAT1,RAT2)
C                       WRITE(*,'(A,2I4,5E15.7)') 'J1,K1,FOB,PFOB,PSTEP,RAT1,DIAG=', J1,K1,XFOB(J1),PFOB(K1),PSTEP(K1),RAT1,DIAG(J1)
                        IF (XRAT(J1).GT.TRAD) THEN
                           STPMAX(J1)=MAX(TEMPA(K1)/1.11D0,MINMAX)
                        ELSE
                           IF (MASST) THEN
                              SUM=0
                              DO J2=1,NATOMS
                                 SUM=SUM+ATMASS(J2)
                              ENDDO
                              AVG=SQRT(SUM/NATOMS)
C                             PRINT *,'THE AVERAGE IS',AVG
                              STPMAX(J1)=MIN(MAX(TEMPA(K1)*1.09D0,MINMAX),AVG*MAXMAX)
                           ELSE
                              STPMAX(J1)=MIN(MAX(TEMPA(K1)*1.09D0,MINMAX),MAXMAX)
                           ENDIF
                        ENDIF
                     ELSE
                        STPMAX(J1)=MAX(TEMPA(K1),MINMAX)
                     ENDIF
                  ENDDO
               ENDIF
               TEMP=-1.0D0
            ENDIF
C
C  DO NOT USE.
C
C           CALL ITEIGN(ITER,COORDS,VECS,EVALMIN,EVALMAX,PTEST)
C
C  LANCZOS ROUTINE - DOES WORK BUT SEEMS TO BE SLOWER? FOR NFIG=3 IT IS ONLY
C  A BIT SLOWER THAN ITEIG WITH CEIG=0.01.
C
C           NVAL=-10
C           ANV=ABS(NVAL)
C           NFIG=3
C           NPERM=0
C           IF (ITER.GT.1) NPERM=1
C           MAXOP=NEVS
C           NBLOCK=1
C           IF ((ANV.GT.MANV).OR.(NBLOCK.GT.MAXBLOCK)) THEN
C              WRITE(*,'(A)') ' TOO MANY EIGENVECTORS OR TOO LARGE A LANCZOS BLOCKSIZE REQUESTED'
C              STOP
C           ENDIF
C
C           CALL DNLASO(HESS, Q, NATOMS, OP, IOVECT, 3*NATOMS, NVAL, NFIG, NPERM,
C    *                  NMVAL, VAL, NMVEC, LVEC, NBLOCK, MAXOP, MAXJ, LWORK,
C    *                  IND, IERR)
C           WRITE(*,'(I3,A,100F20.10)') NPERM,' EIGENVECTORS DETERMINED: ',(VAL(J1,1),J1=1,NPERM)
C           IF (IERR.NE.0) THEN
C              WRITE(*,'(A,I4)') 'LANCZOS CALL COMPLETED WITH ERROR CODE ',IERR
C           ELSE
C              WRITE(*,'(A,F20.10)') ' SMALLEST EIGENVALUE=',VAL(1,1)
C           ENDIF

C           EVALMIN=VAL(1,1)
C           DO J1=1,NOPT
C              VECS(J1)=LVEC(J1,1)
C           ENDDO
         ELSE
            CALL BEIG(ITER,COORDS,ENERGY,VECS,EVALMIN,NS,SOVER,PTEST,CONVERGED)

C
C  THE FOLLOWING TWO ROUTINES ARE ALSO OBSOLETE.
C
C           CALL POWEIG(ITER,COORDS,ENERGY,VECS,EVALMIN)
C           CALL MCEIG(ITER,COORDS,ENERGY,VECS,EVALMIN)
         ENDIF
      ENDIF

      IF ((EVALMIN.LT.0.0D0).AND.FIXD) THEN
         IF (PTEST) WRITE(*,'(A)') ' NEGATIVE EIGENVALUE, CHANGING TO HYBRID EF'
         FIXD=.FALSE.
         CALL VECNORM(VECS,NOPT)
         DO J1=1,NOPT
            ZWORK(J1,1)=VECS(J1)
         ENDDO
      ELSE IF (FIXD) THEN
C     IF (FIXD) THEN
         DO J1=1,NOPT
            ZWORK(J1,1)=FIXDIR(J1)
            VECS(J1)=FIXDIR(J1)
         ENDDO
      ELSE
         CALL VECNORM(VECS,NOPT)
         DUMMY=0.0D0
         DO J1=1,NOPT
            ZWORK(J1,1)=VECS(J1)
            DUMMY=DUMMY+VECS(J1)**2
         ENDDO
      ENDIF
C
C  DUMP THE SMALLEST NON-ZERO EIGENVALUE AND EIGENVECTOR 
C  IN FILE VECTOR.DUMP, IF REQUIRED.
C
      IF (DUMPV) THEN
         IF (.NOT.ALLSTEPS) REWIND(44)
         WRITE(44,'(E20.10)') EVALMIN
         WRITE(44,'(3F20.10)') (ZWORK(J1,1),J1=1,NOPT)
         CALL FLUSH(44,ISTAT)
      ENDIF
C
C  TAKE AN EIGENVECTOR-FOLLOWING STEP UPHILL ALONG THE DIRECTION CORRESPONDING
C  TO THE SMALLEST NON-ZERO EIGENVALUE. THEN DO A LINE MINIMIZATION ALONG THE
C  GRADIENT VECTOR WITH COMPONENT ALONG THE UPHILL DIRECTION PROJECTED OUT. 
C  DO WE NEED A NEW GRADIENT VECTOR OR WILL THE OLD ONE FROM THE POINT BEFORE
C  STEPPING UPHILL DO?
C
      FOB=0.0D0
      DO J1=1,NOPT
         FOB=FOB+ZWORK(J1,1)*GRAD(J1)
      ENDDO
      XFOB(1)=FOB
      REDOPATH1=.FALSE.; REDOPATH2=.FALSE.
      IF (REDOPATH.AND.BFGSSTEP) THEN
         PROJ1=0.0D0
         PROJ2=0.0D0
         DO J1=1,NOPT
            PROJ1=PROJ1+ZWORK(J1,1)*(MIN1REDO(J1)-COORDS(J1))/D1INIT
            PROJ2=PROJ2+ZWORK(J1,1)*(MIN2REDO(J1)-COORDS(J1))/D2INIT
         ENDDO
         IF (IVEC.LT.0) THEN
            PROJ1=-PROJ1
            PROJ2=-PROJ2
         ENDIF
         IF (PROJ1.GT.PROJ2) REDOPATH1=.TRUE.
         IF (PROJ2.GT.PROJ1) REDOPATH2=.TRUE.
         PRINT '(A,2G20.10)',' BFGSTS> PROJECTIONS OF STEP ONTO DIRECTIONS OF MINIMA 1 AND 2 ARE: ',PROJ1,PROJ2 
      ENDIF
      IF (FIXD) GOTO 666
      IF (HINDEX.LE.1) THEN
         IF (EVALMIN.LT.0.0D0) THEN
C           PRINT*,'THERE IS AT LEAST ONE NEGATIVE EIGENVALUE'
            INEG=1
         ELSE
C           PRINT*,'THERE ARE NO NEGATIVE EIGENVALUES'
            INEG=0
         ENDIF
      ELSE
         INEG=0
         DO J1=1,HINDEX
            IF (DIAG(J1).LT.0.0D0) INEG=INEG+1
         ENDDO
         WRITE(*,'(A,I5,A)') ' THERE ARE AT LEAST ',INEG,' NEGATIVE HESSIAN EIGENVALUES'
      ENDIF
C
C  TAKE A STEP AWAY FROM A STATIONARY POINT ALONG THE APPROPRIATE
C  HESSIAN EIGENVECTOR. THIS ENABLES US TO START FROM CONVERGED MINIMA.
C  DISTINGUISH THE CASE WHERE WE WANT TO TAKE A VERY SMALL STEP AWAY
C  FROM A TRANSITION STATE FROM OTHERS WHERE WE WANT A BIG DISPLACEMENT
C  TO GET UNSTUCK. 
C
      AWAY=.FALSE.
      IF ((RMS.LT.PUSHCUT).AND.(.NOT.FIXD)) THEN
         IF ((INEG.NE.HINDEX).AND.CONVERGED) THEN ! DON;T TRY PUSHOFF IF CONVERGED IS .FALSE.
            IF (HINDEX.LE.1) THEN
               IF ((ITER.EQ.1).AND.(INEG.EQ.0)) THEN
                  IF (PTEST) THEN
                     IF (IVEC.GE.0) PRINT*,'STEPPING AWAY FROM MINIMUM ALONG SOFTEST MODE + DIRECTION'
                     IF (IVEC.LT.0) PRINT*,'STEPPING AWAY FROM MINIMUM ALONG SOFTEST MODE - DIRECTION'
                  ENDIF
                  AWAY=.TRUE.
               ELSE IF (MOD(ITER-1,4).EQ.0) THEN
                  PRINT*,'STEPPING AWAY FROM SOLUTION OF WRONG INDEX'
                  IF (PUSHOFF.EQ.0.0D0) THEN
                     FOB=STPMAX(1)
                  ELSE 
                     FOB=PUSHOFF
                  ENDIF
               ENDIF
            ELSE
               DO J1=1,HINDEX
                  IF (DIAG(J1).GT.0.0D0) THEN
                     WRITE(*,'(A,I6)') 'STEPPING AWAY FROM SOLUTION OF WRONG INDEX ALONG EIGENVECTOR ',J1
                     IF (PUSHOFF.EQ.0.0D0) THEN
                        XFOB(J1)=STPMAX(J1)
                     ELSE
                        XFOB(J1)=PUSHOFF
                     ENDIF
                  ENDIF
               ENDDO
            ENDIF
         ENDIF
      ENDIF
      IF (BFGSSTEP) THEN
         IF (INEG.EQ.0) THEN
            PRINT*,'****WARNING - BFGSSTEP SET FOR A MINIMUM'
         ELSE
            IF (PTEST) THEN
               IF (IVEC.GE.0) PRINT*,'STEPPING AWAY FROM SADDLE ALONG SOFTEST MODE + DIRECTION'
               IF (IVEC.LT.0) PRINT*,'STEPPING AWAY FROM SADDLE ALONG SOFTEST MODE - DIRECTION'
            ENDIF
            AWAY=.TRUE.
         ENDIF
      ENDIF
C
C  EF DETERMINATION OF STEPS
C
      IF (HINDEX.LE.1) THEN
         XP1=DABS(EVALMIN)/2.0D0
         IF (MASST) THEN
            SUM=0
            DO J2=1,NATOMS
               SUM=SUM+ATMASS(J2)
            ENDDO
            AVG=SUM/NATOMS
            XP2=1.0D0 + 4.0D0*(FOB/EVALMIN)**2/AVG
         ELSE
            XP2=1.0D0 + 4.0D0*(FOB/EVALMIN)**2
         ENDIF
         XP1=-XP1*(1.0D0+DSQRT(XP2))
         PSTEP=-FOB/XP1
   
         IF (AWAY) THEN
            IF (PUSHOFF.NE.0.0D0) THEN
               PSTEP=PUSHOFF
            ELSE
               PSTEP=STPMAX(1)/1.0D1
            ENDIF
            IF (IVEC.LT.0) PSTEP=-PSTEP
         ENDIF
C        WRITE(*,'(A,F20.10)') ' UNSCALED STEP=',PSTEP
C
C  SCALE ACCORDING TO STEP SIZE IN EV BASIS:
C
         STPMAG=ABS(PSTEP)
         IF (.NOT.AWAY) THEN
            SCALE=MIN(STPMAX(1)/MAX(DABS(PSTEP),1D-10),1.0D0)
            PSTEP=SCALE*PSTEP
         ENDIF
         STEP(1)=PSTEP ! BECAUSE WE SAVE THIS VALUE IN XPSTEP LATER FROM STEP ARRAY
      ELSE
         DO I=HINDEX,1,-1
            STEP(I)=0.0D0
            NZERO=0
            IF (DABS(DIAG(NZERO+1)/MAX(DABS(DIAG(I)),1.0D-10)).GT.TEMP) TEMP=DABS(DIAG(NZERO+1)/MAX(DABS(DIAG(I)),1.0D-10))
            LP1=DABS(DIAG(I))/2.0D0
            IF (MASST) THEN
               SUM=0
               DO J2=1,NATOMS
                  SUM=SUM+ATMASS(J2)
               ENDDO
               AVG=SUM/NATOMS
               LP2=1.0D0 + 4.0D0*((XFOB(I)/DIAG(I))**2)/AVG
            ELSE
               LP2=1.0D0 + 4.0D0*(XFOB(I)/DIAG(I))**2
            ENDIF
            LP=LP1*(1.0D0+DSQRT(LP2))
            WRITE(*,'(A,I4,A,4X,F19.10)') ' MODE ',I,' WILL BE SEARCHED UPHILL. EIGENVALUE=',DIAG(I)
            LP=-LP
            STEP(I)=-XFOB(I)/LP
         ENDDO
         DO J1=1,NOPT
            SCRATCH(NOPT+J1)=STEP(J1)
         ENDDO
C
C  CONVERT THE STEPS TO THE CARTESIAN RATHER THAN THE EV BASIS
C
         DO J=1,NOPT
            SCRATCH(J+NOPT)=0.0D0
            DO I=1,HINDEX
               SCRATCH(J+NOPT)=SCRATCH(J+NOPT)+STEP(I)*ZWORK(J,I)
            ENDDO
         ENDDO
C
C  SCALE ACCORDING TO STEP SIZE IN EV BASIS:
C
         CALL VSTAT(STEP(1),AV,NOPT,3*NATOMS)
         STPMAG=MAX(AV(1),1D-10)
         DO J1=1,NOPT
            SCALE=MIN(STPMAX(J1)/MAX(DABS(STEP(J1)),1D-10),1.0D0)
            STEP(J1)=SCALE*STEP(J1)
         ENDDO
         CALL VSTAT(STEP(1),AV,NOPT,3*NATOMS)
         SSTPMAG=MAX(AV(1),1D-10)
         SCALE=1.0D0
         E1=0.0D0
         DO J1=1,NOPT
            E1=E1+STEP(J1)*XFOB(J1)
         ENDDO
         E2=0.0D0
         DO J1=1,NOPT
            E2=E2+DIAG(J1)*STEP(J1)**2
         ENDDO
         E2=E2/2.0D0
         DELE=E1*SCALE+E2*SCALE**2
         CALL VADD(SCRATCH(1),SCRATCH(1),SCRATCH(NOPT+1),NOPT,1)

         IF (EFSTEPST.AND.(MOD(ITER-1,EFSTEPS).EQ.0)) THEN
            DO I=NZERO+1,HINDEX
                WRITE(*,360) I, STEP(I)
360             FORMAT(' UNSCALED STEP FOR MODE ',I3,'=',F20.10)
            ENDDO
         ENDIF
      ENDIF
C
C  USE MAXMAX UNTIL WE HAVE A NEGATIVE EIGENVALUE. BE SURE TO
C  STEP UPHILL!
C
      LINE=.FALSE.
      IF (CONVERGED) THEN
         IF (((EVALMIN.GT.0.0D0).OR.FIXD).AND.(HINDEX.LE.1)) THEN
            PSTEP=FOB*MAXMAX/ABS(FOB)
            STEP(1)=PSTEP
         ELSE IF (HINDEX.GT.1) THEN
            DO J1=1,HINDEX
               IF (DIAG(J1).GT.0.0D0) STEP(J1)=XFOB(J1)*MAXMAX/ABS(XFOB(J1))
            ENDDO
         ENDIF
      ENDIF

      IF (HINDEX.LE.1) THEN
         E1=PSTEP*FOB
         E2=EVALMIN*PSTEP**2/2.0D0
         DELE=E1+E2
      ENDIF
C
C  REGENERATE FULL Q VECTOR. 
C
666   IF (.NOT.FIXD) THEN
         IF (HINDEX.LE.1) THEN
            DO J=1,NOPT
               COORDS(J)=COORDS(J)+PSTEP*ZWORK(J,1)
            ENDDO
         ELSE
C
C  UNPACK SCRATCH(1:NOPT) TO REGENERATE FULL Q VECTOR.
C  CSTEP CONTAINS THE STEP IN THE CARTESIAN BASIS.
C
            DO J=1,NOPT
               COORDS(J)=SCRATCH(J)
               CSTEP(J)=SCRATCH(NOPT+J)
            ENDDO
         ENDIF
      ELSE
         DO J=1,NOPT
            COORDS(J)=COORDSN(J)
         ENDDO
      ENDIF

!     WRITE(667,'(I8)') NATOMS
!     WRITE(667,'(F20.10)') EVALMIN
!     DO J1=1,NATOMS
!        WRITE(667,'(A2,1X,6F20.10)') ZSYM(J1),COORDS(3*(J1-1)+1),COORDS(3*(J1-1)+2),COORDS(3*(J1-1)+3),
!    &                            ZWORK(3*(J1-1)+1,1),ZWORK(3*(J1-1)+2,1),ZWORK(3*(J1-1)+3,1)
!     ENDDO
!     CALL FLUSH(667,ISTAT)
      KNOWE=.FALSE.
      KNOWG=.FALSE.
      KNOWH=.FALSE.

      IF (.NOT.LINE) THEN
         EOLD=ENERGY
         IF (.NOT.BFGSSTEP) THEN
C
C  OPTIMISING THE BOX LENGTHS HERE WOULD CHANGE THE CRITICAL EIGENVALUE AND
C  EIGENVECTOR.
C
C           IF (PV) THEN
C              CALL POTENTIAL(COORDS,ENERGY,GRAD,.FALSE.,.FALSE.,RMS,.FALSE.,.FALSE.)
C              PVFLAG=.FALSE.
C              CALL PVOPT(COORDS,ENERGY,GRAD)
C           ENDIF
C
            CALL POTENTIAL(COORDS,ENERGY,GRAD,.TRUE.,.FALSE.,RMS,.FALSE.,.FALSE.)
            KNOWE=.TRUE.
            KNOWG=.TRUE.
            CALL DUMPP(COORDS,ENERGY)
         ENDIF
      ENDIF
C
C  IF REOPT IS TRUE THEN REOPTIMISE THE EIGENVECTOR CORRESPONDING TO THE UPHILL DIRECTION
C  BEFORE DOING THE TANGENT SPACE MINIMISATION. DOES NOT MAKE SENSE WITH FIXD.
C
      IF (REOPT) THEN
         WRITE(*,'(A)') 'REOPTIMISING UPHILL DIRECTION AFTER EF STEP'
         IF (.NOT.NOHESS) THEN
            IF (NOIT) THEN
               PRINT*,'REOPTIMISATION WITH NOIT NOT IMPLEMENTED'
               CALL FLUSH(6,ISTAT)
               STOP
            ENDIF
            CALL ITEIG(2,COORDS,VECS,EVALMIN,EVALMAX,NS,SOVER,PTEST,VECL,CONVERGED)
         ELSE
            CALL BEIG(2,COORDS,ENERGY,VECS,EVALMIN,NS,SOVER,PTEST,CONVERGED)
         ENDIF
         DO J1=1,NOPT
            ZWORK(J1,1)=VECS(J1)
         ENDDO
      ENDIF
      CALL FLUSH(6,ISTAT)

      FOBNEW=0.0D0
      DO J1=1,NOPT
         FOBNEW=FOBNEW+GRAD(J1)*ZWORK(J1,1)
      ENDDO
C
C  ONLY SCALE IF WE HAVE A -VE EIGENVALUE
C
      IF ((EOLD.NE.0.0D0).AND.(EVALMIN.LT.0.0D0).AND.(.NOT.FIXD)) THEN
         EPER=MIN(DABS(1.0D0-(FOBNEW-FOB)/(PSTEP*EVALMIN)),DABS(1.0D0-(-FOBNEW-FOB)/(PSTEP*EVALMIN)))
C        WRITE(*,'(A,4F20.10)') 'FOB,FOBNEW,PSTEP,EVALMIN=',FOB,FOBNEW,PSTEP,EVALMIN
C        WRITE(*,'(A,3F20.10)') 'EPER,EPER1,EPER2=',
C    1          EPER,DABS(1.0D0-(FOBNEW-FOB)/(PSTEP*EVALMIN)),DABS(1.0D0-(-FOBNEW-FOB)/(PSTEP*EVALMIN))
         IF (EPER.GT.TRAD) THEN
            STPMAX(1)=MAX(STPMAX(1)/1.1D0,MINMAX)
C           WRITE(*,'(A,E12.4,A,E12.4)') ' DECREASING ALLOWED EF STEP; TRUST RADIUS=',TRAD,' CALCULATED RATIO=',EPER
         ELSE
            STPMAX(1)=MIN(STPMAX(1)*1.1D0,MAXMAX)
C           WRITE(*,'(A,E12.4,A,E12.4)') ' INCREASING ALLOWED EF STEP; TRUST RADIUS=',TRAD,' CALCULATED RATIO=',EPER
         ENDIF
      ENDIF
C
C SUMMARIZE
C
C     IF (SUMMARYT.AND.(MOD(ITER-1,NSUMMARY).EQ.0)) THEN
         IF (PTEST) THEN
            IF (HINDEX.LE.1) THEN
               WRITE(*,30)
30             FORMAT(1X,79('-'))
               WRITE(*,40)
40             FORMAT(' VECTOR      GRADIENT        SECDER       STEP          MAX STEP    TRUST RATIO')
               WRITE(*,30)
               WRITE(*,50) 1,FOB,EVALMIN,PSTEP,STPMAX(1),EPER
50             FORMAT(1X,I4,1X,E15.6,1X,E15.6,1X,E13.6,1X,E12.6,1X,E15.6)
               WRITE(*,30)
            ELSE
               WRITE(*,30)
               WRITE(*,40)
               WRITE(*,30)
               DO I=HINDEX,1,-1
                  WRITE(*,50) I,XFOB(I),DIAG(I),STEP(I),STPMAX(I),XRAT(I)
               ENDDO
               WRITE(*,30)
            ENDIF
         ELSE IF (.NOT.BFGSSTEP) THEN
C           WRITE(*,'(A,I6,A,F20.10,A,F15.7,A,F12.4,A,F12.4)') 
C    1          ' CYCLE ',ITER,' E=',ENERGY,' RMS=',RMS,' EIGENVALUE=',EVALMIN,' OVERLAP=',SOVER
         ENDIF
C     ENDIF
C
      IF (BFGSSTEP) THEN
         FIXIMAGE=.FALSE.
         FIXD=FIXDSAVE
         RETURN
      ENDIF
C
C  TANGENT SPACE MINIMIZATION NEXT.
C  UPHILL DIRECTION IS PROJECTED OUT OF THE STEP IN MYLBFGS
C  THE NEXT IF BLOCK ALLOWS FOR ZERO TANGENT SPACE STEPS IN THE INITIAL PHASE
C
      IF ((NBFGSMAX1.EQ.0).AND.((1.0D0-DABS(SOVER).GT.BFGSTSTOL).OR.(INEG.EQ.0))) THEN
         FIXIMAGE=.FALSE.
         ITER=ITER+1
         FIXD=FIXDSAVE
         MFLAG=.FALSE.
         IF (ITER.GT.ITMAX) RETURN
         GOTO 90
      ENDIF

      IF (((1.0D0-DABS(SOVER).GT.BFGSTSTOL).OR.(HINDEX.NE.INEG)).OR.(INEG.EQ.0).OR.(TWOENDS.AND.(ITER.EQ.1)).OR.(ITER.EQ.1)) THEN
          NBFGS=NBFGSMAX1
      ELSE
          NBFGS=NBFGSMAX2
      ENDIF

!
! IF WE DON'T RESET THEN THE PREVIOUS STEPS AND GRADIENTS SAVED IN MYLBFGS
! WILL NOT NECESSARILY BE PERPENDICULAR TO THE NEW UPHILL DIRECTION.
!
      RESET=.TRUE.
      IF (ITER.EQ.1) RESET=.TRUE.
!     RMS2=RMS
      NSTEPMINSAVE=NSTEPMIN
      NSTEPMIN=0
      IF (CHRMMT.AND.INTMINT) THEN
         CALL MYLBFGS(NINTS,MUPDATE,COORDS,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,NBFGS,
     1                RESET,ITDONE,PTEST,GRAD,.TRUE.,.TRUE.)
      ELSE
         CALL MYLBFGS(NOPT,MUPDATE,COORDS,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,NBFGS,
     1                RESET,ITDONE,PTEST,GRAD,.TRUE.,.TRUE.)
      ENDIF
      NSTEPMIN=NSTEPMINSAVE
      IF (CFUSIONT) THEN
         MFLAG=.FALSE.
         RETURN
      ENDIF

      IF (REPELTST) CALL REPELSP(COORDS,RMS,INEG,MFLAG)

      RMS2=RMS ! SAVE SUBSPACE RMS
      RMS=DSQRT(DOTOPT(GRAD(1),GRAD(1),NOPT))/SQRT(1.0D0*NOPT) ! TRUE RMS
      IF (PTEST) WRITE(*,'(A,F15.7,A,F15.7,A,F15.7)') ' BFGSTS> RMS GRAD=',RMS,
     &         ' SUBSPACE GRAD=',RMS2,' UNSCALED EF STEP LENGTH=',STPMAG
      IF (MFLAG) THEN
!        IF (NFREEZE.GT.0) THEN
!           PRINT '(A,I8,A)',' BFGSTS> UNFREEZING ',NFREEZE,' ATOMS'
!           MFLAG=.FALSE.
!           FROZEN(1:NATOMS)=.FALSE.
!           NFREEZE=0
!        ENDIF
         IF (((RMS.GT.CONVR).OR.(INEG.EQ.0)).OR.(STPMAG.GT.CONVU)) MFLAG=.FALSE.
         IF (MFLAG) THEN
            FIXD=FIXDSAVE
            RETURN
         ENDIF
      ENDIF
!
! BUG FIX 11/4/08 DJW - WOULD HAVE CONVERGED ON SUBSPACE GRADIENT, NOT TOTAL AFTER SUBSPACE MINIMISATION
! WITHOUT PROJECTION. PROBABLY CAUSED WHEN PROJECTION WAS CHANGED IN MYLBFGS.
!
      ITER=ITER+1
      IF (ITER.GT.ITMAX) THEN
         FIXD=FIXDSAVE
         RETURN
      ENDIF
C     IF ((AMBER).AND.(MOVIE)) CALL AMOVIEDUMP(FRAME)
      EOLD=ENERGY
      DO J1=1,NOPT
         XPSTEP(J1)=STEP(J1)
         PFOB(J1)=XFOB(J1)
      ENDDO
      GOTO 90
! }}}
      RETURN
      END
! }}}
C
!ITEG: ORTHOGONALISE VEC1 TO OVERALL TRANSLATIONS AND ROTATIONS.{{{
C
      SUBROUTINE ORTHOGOPT(VEC1,COORDS,OTEST) 
! {{{
      USE COMMONS
      USE KEY
      USE VECCK
      IMPLICIT NONE
      INTEGER J2, J3, NCHECK
      DOUBLE PRECISION COORDS(*), VEC1(*), DUMMY1, DUMMY2, ROOTN, VDOT,
     1                 CMX, CMY, CMZ, AMASS(NATOMS), TMASS, RMASS(NATOMS)
      LOGICAL OTEST

      IF (RINGPOLYMERT.AND.(RPSYSTEM(1:4).EQ.'AECK')) THEN
         IF (OTEST) CALL VECNORM(VEC1,NOPT)
         RETURN
      ENDIF
      IF (ZSYM(NATOMS).EQ.'TH') THEN
         CALL ORTHOGTH(VEC1,COORDS,OTEST)
         RETURN
      ENDIF
      IF (STOCKT) THEN
         CALL ORTHOGSTOCK(VEC1,COORDS,OTEST)
         RETURN
      ENDIF
      IF (RBAAT) THEN
         CALL ORTHOGRIGID(VEC1,COORDS,OTEST)
         RETURN
      ENDIF 
      IF (.NOT.ALLOCATED(VECCHK)) ALLOCATE(VECCHK(3*NATOMS,30))
      ROOTN=SQRT(1.0D0*NATOMS)
      NCHECK=0
      CMX=0.0D0
      CMY=0.0D0
      CMZ=0.0D0
      TMASS=0.0D0
      DO J2=1,NATOMS
         AMASS(J2)=1.0D0
         RMASS(J2)=1.0D0
         IF (MASST) AMASS(J2)=ATMASS(J2)
         IF (MASST) RMASS(J2)=SQRT(ATMASS(J2))
         TMASS=TMASS+AMASS(J2)
      ENDDO
C
C  IF MASST THEN THE COORDINATES ALREADY HAVE A SQUARE ROOT OF THE MASS IN THEM
C
      DO J2=1,NATOMS
         CMX=CMX+COORDS(3*(J2-1)+1)*RMASS(J2)
         CMY=CMY+COORDS(3*(J2-1)+2)*RMASS(J2)
         CMZ=CMZ+COORDS(3*(J2-1)+3)*RMASS(J2)
      ENDDO
      CMX=CMX/TMASS
      CMY=CMY/TMASS
      CMZ=CMZ/TMASS
C     WRITE(*,'(A,3F20.10)') 'CENTRE AT ',CMX,CMY,CMZ
1     VDOT=0.0D0
      NCHECK=NCHECK+1
C
C  ORTHOGONALIZE TO KNOWN EIGENVECTORS CORRESPONDING TO NEGATIVE EIGENVALUES
C  FOR CHECKINDEX RUN WITH NOHESS.
C
      IF (CHECKINDEX) THEN
         DO J2=1,NMDONE
            DUMMY1=0.0D0
            DO J3=1,NOPT
               DUMMY1=DUMMY1+VECCHK(J3,J2)*VEC1(J3)
            ENDDO
            VDOT=MAX(VDOT,ABS(DUMMY1))
            DUMMY2=0.0D0
            DO J3=1,NOPT
               VEC1(J3)=VEC1(J3)-DUMMY1*VECCHK(J3,J2)
               DUMMY2=DUMMY2+VEC1(J3)**2
            ENDDO
            DUMMY2=1.0D0/DSQRT(DUMMY2)
            DO J3=1,NOPT
               VEC1(J3)=VEC1(J3)*DUMMY2
            ENDDO
         ENDDO
         IF (OTEST) CALL VECNORM(VEC1,NOPT)
      ENDIF
C
      IF ((VDOT.GT.1.0D-6).AND.(SHIFTED).AND.(NCHECK.LT.100)) GOTO 1
      IF (NCHECK.GE.100) THEN
         PRINT*,'*** WARNING, CANNOT ORTHOGONALISE TO KNOWN EIGENVECTORS IN ORTHOGOPT'
      ENDIF
      IF ((SHIFTED).AND.(.NOT.FIXD)) RETURN  ! ZEROS ARE SHIFTED - LOWEST EIGENVECTOR SHOULD BE UNCONTAMINATED

      IF (ZSYM(1).EQ.'BE') GOTO 10
      IF (EYTRAPT) GOTO 10
      IF (RTEST.AND.(JZ.EQ.0.0D0)) GOTO 20
      IF (RTEST.AND.(JZ.NE.0.0D0)) GOTO 30

      DUMMY1=0.0D0
      DO J2=1,NOPT,3
         DUMMY1=DUMMY1+VEC1(J2)
      ENDDO
      DUMMY1=DUMMY1/ROOTN
      VDOT=MAX(VDOT,ABS(DUMMY1))
C     WRITE(*,'(A,F20.10)') 'X DOT:',DUMMY1
      DO J2=1,NOPT,3
         VEC1(J2)=VEC1(J2)-DUMMY1/ROOTN
      ENDDO
      IF (OTEST) CALL VECNORM(VEC1,NOPT)

      DUMMY1=0.0D0
      DO J2=2,NOPT,3
         DUMMY1=DUMMY1+VEC1(J2)
      ENDDO
      DUMMY1=DUMMY1/ROOTN
      VDOT=MAX(VDOT,ABS(DUMMY1))
C     WRITE(*,'(A,F20.10)') 'Y DOT:',DUMMY1
      DO J2=2,NOPT,3
         VEC1(J2)=VEC1(J2)-DUMMY1/ROOTN
      ENDDO
      IF (OTEST) CALL VECNORM(VEC1,NOPT)

30    DUMMY1=0.0D0
      DO J2=3,NOPT,3
         DUMMY1=DUMMY1+VEC1(J2)
      ENDDO
      DUMMY1=DUMMY1/ROOTN
      VDOT=MAX(VDOT,ABS(DUMMY1))
C     WRITE(*,'(A,F20.10)') 'Z DOT:',DUMMY1
      DO J2=3,NOPT,3
         VEC1(J2)=VEC1(J2)-DUMMY1/ROOTN
      ENDDO
      IF (OTEST) CALL VECNORM(VEC1,NOPT)

31    CONTINUE
      IF ((VDOT.GT.1.0D-6).AND.BULKT.AND.(NCHECK.LT.100)) GOTO 1
!     PRINT*,'AFTER NEXT PART VDOT=',VDOT
      IF (NCHECK.GE.100) THEN
         PRINT*,'*** WARNING, CANNOT ORTHOGONALISE TO KNOWN EIGENVECTORS IN ORTHOGOPT'
      ENDIF
      IF (BULKT.AND.TWOD) GOTO 20
      IF (BULKT) RETURN
      IF (DFTP) RETURN
      IF (RTEST.AND.(JZ.NE.0.0D0)) GOTO 20
      IF (PULLT.OR.EFIELDT) GOTO 20

10    DUMMY1=0.0D0
      DUMMY2=0.0D0
      DO J2=1,NATOMS
         J3=3*J2
         DUMMY1=DUMMY1+RMASS(J2)*(VEC1(J3-1)*(COORDS(J3)-CMZ)-VEC1(J3)*(COORDS(J3-1)-CMY))
         DUMMY2=DUMMY2+AMASS(J2)*((COORDS(J3)-CMZ)**2+(COORDS(J3-1)-CMY)**2)
      ENDDO
      IF (DUMMY2.GT.0.0D0) THEN
!        WRITE(*,'(A,F20.10)') 'XRDOT:',DUMMY1/SQRT(DUMMY2)
         VDOT=MAX(VDOT,ABS(DUMMY1)/SQRT(DUMMY2))
         DUMMY2=DUMMY1/DUMMY2
         DO J2=1,NATOMS
            J3=3*J2
            VEC1(J3-1)=VEC1(J3-1)-DUMMY2*RMASS(J2)*(COORDS(J3)-CMZ)
            VEC1(J3)=VEC1(J3)+DUMMY2*RMASS(J2)*(COORDS(J3-1)-CMY)
         ENDDO
      ENDIF
      IF (OTEST) CALL VECNORM(VEC1,NOPT)
!     PRINT*,'ROT X COMPONENT=',DUMMY2

      DUMMY1=0.0D0
      DUMMY2=0.0D0
      DO J2=1,NATOMS
         J3=3*J2
         DUMMY1=DUMMY1-VEC1(J3-2)*RMASS(J2)*(COORDS(J3)-CMZ)+VEC1(J3)*RMASS(J2)*(COORDS(J3-2)-CMX)
         DUMMY2=DUMMY2+AMASS(J2)*((COORDS(J3)-CMZ)**2+(COORDS(J3-2)-CMX)**2)
      ENDDO
      IF (DUMMY2.GT.0.0D0) THEN
!        WRITE(*,'(A,F20.10)') 'YRDOT:',DUMMY1/SQRT(DUMMY2)
         VDOT=MAX(VDOT,ABS(DUMMY1)/SQRT(DUMMY2))
         DUMMY2=DUMMY1/DUMMY2
         DO J2=1,NATOMS
            J3=3*J2
            VEC1(J3-2)=VEC1(J3-2)+DUMMY2*RMASS(J2)*(COORDS(J3)-CMZ)
            VEC1(J3)=VEC1(J3)-DUMMY2*RMASS(J2)*(COORDS(J3-2)-CMX)
         ENDDO
      ENDIF
      IF (OTEST) CALL VECNORM(VEC1,NOPT)
!     PRINT*,'ROT Y COMPONENT=',DUMMY2

20    DUMMY1=0.0D0
      DUMMY2=0.0D0
      DO J2=1,NATOMS
         J3=3*J2
         DUMMY1=DUMMY1+VEC1(J3-2)*RMASS(J2)*(COORDS(J3-1)-CMY)-VEC1(J3-1)*RMASS(J2)*(COORDS(J3-2)-CMX)
         DUMMY2=DUMMY2+AMASS(J2)*((COORDS(J3-1)-CMY)**2+(COORDS(J3-2)-CMX)**2)
      ENDDO
      IF (DUMMY2.GT.0.0D0) THEN
!        WRITE(*,'(A,F20.10)') 'ZRDOT:',DUMMY1/SQRT(DUMMY2)
         VDOT=MAX(VDOT,ABS(DUMMY1)/SQRT(DUMMY2))
         DUMMY2=DUMMY1/DUMMY2
         DO J2=1,NATOMS
            J3=3*J2
            VEC1(J3-2)=VEC1(J3-2)-DUMMY2*RMASS(J2)*(COORDS(J3-1)-CMY)
            VEC1(J3-1)=VEC1(J3-1)+DUMMY2*RMASS(J2)*(COORDS(J3-2)-CMX)
         ENDDO
      ENDIF
      IF (OTEST) CALL VECNORM(VEC1,NOPT)
!     PRINT*,'ROT Z COMPONENT=',DUMMY2

C     WRITE(*,'(A,F20.10)') 'LARGEST REMAINING COMPONENT IN ORTHOGOPT=',VDOT
      IF ((VDOT.GT.1.0D-6).AND.(NCHECK.LT.100)) GOTO 1
C     PRINT*,'AFTER NEXT PART VDOT=',VDOT
      IF (NCHECK.GE.100) THEN
         PRINT*,'*** WARNING, CANNOT ORTHOGONALISE TO KNOWN EIGENVECTORS IN ORTHOGOPT'
      ENDIF
! }}}
      RETURN
      END
! }}}

!ITEIG: EST. SMALLEST NON-ZERO EIGENVALUE & EIGENVECTOR BY REPEATED ITERATION {{{
C
C  ESTIMATE THE SMALLEST NON-ZERO EIGENVALUE AND THE ASSOCIATED
C  EIGENVECTOR BY REPEATED ITERATION. MODIFIED TO FIND MORE THAN
C  ONE EIGENVECTOR. THE EIGENVALUE OF THE CHOSEN EIGENVECTOR IS
C  RETURNED AS EVALMIN, THOUGH IT MAY NOT BE THE MINIMUM VALUE.
C  VECS CONTAINS THE CHOSEN EIGENVECTOR, AND IS NOT ALTERED BY THE
C  CALLING ROUTINE.
C
      SUBROUTINE ITEIG(ITER,COORDS,VECS,EVALMIN,EVALMAX,NS,SOVER,PTEST,VECL,CONVERGED)
! DOXYGEN {{{
!>
!> \NAME ITEIG
!> \BRIEF ESTIMATE THE SMALLEST NON-ZERO EIGENVALUE AND THE ASSOCIATED
!> \BRIEF EIGENVECTOR BY REPEATED ITERATION. 
!>  MODIFIED TO FIND MORE THAN
!>  ONE EIGENVECTOR. THE EIGENVALUE OF THE CHOSEN EIGENVECTOR IS
!>  RETURNED AS EVALMIN, THOUGH IT MAY NOT BE THE MINIMUM VALUE.
!>  VECS CONTAINS THE CHOSEN EIGENVECTOR, AND IS NOT ALTERED BY THE
!>  CALLING ROUTINE.
!> \PARAM[IN]
!> \PARAM[IN]
!> \PARAM[OUT]
!> \PARAM[OUT]
!>
! }}}
! MODULES {{{

        USE COMMONS
        USE KEY
        USE MODTWOEND
        USE VECCK
        USE MODHESS
! }}}

      IMPLICIT NONE

! SUBROUTINE PARAMETERS {{{

      INTEGER ITER 
      DOUBLE PRECISION, DIMENSION(3*NATOMS) :: COORDS, VECS 
      DOUBLE PRECISION EVALMIN, EVALMAX
      INTEGER NS  
      DOUBLE PRECISION SOVER
      LOGICAL PTEST
      DOUBLE PRECISION,DIMENSION(3*NATOMS) :: VECL
      LOGICAL CONVERGED

! }}}
! LOCAL PARAMETERS {{{

      INTEGER J1, J2, ISEED
      DOUBLE PRECISION DUMMY1,VEC1(3*NATOMS),XSIGN,
     1                 VEC2(3*NATOMS),DUMMY2,DUMMY, DUMMY4,
     2                 PERCENT,OVLAP(30), OVMAX, DPRAND, EVALS(30)
      INTEGER JVEC, NDUM, NMPREV, JVECP
      COMMON /IS/ ISEED
      SAVE

! }}}
! SUBROUTINE BODY {{{

      NMPREV=NMDONE
      IF (ITER.EQ.1) JVECP=30
C
C  FIRST ESTIMATE THE LARGEST EIGENVALUE OF HESS. 
C
      IF ((ITER.EQ.1).AND.(.NOT.TTDONE)) THEN
         DO J1=1,NOPT
            VEC1(J1)=2*(DPRAND()-0.5D0)
         ENDDO
         CALL VECNORM(VEC1,NOPT)

C        DO J1=1,NOPT
C           VEC1(J1)=0.0D0
C        ENDDO
C        VEC1(1)=1.0D0

      ELSE
         DO J1=1,NOPT
            VEC1(J1)=VECL(J1)
         ENDDO
      ENDIF
      IF (FREEZE) THEN
         DO J1=1,NATOMS
            IF (FROZEN(J1)) THEN
               VEC1(3*(J1-1)+1)=0.0D0
               VEC1(3*(J1-1)+2)=0.0D0
               VEC1(3*(J1-1)+3)=0.0D0
            ENDIF
         ENDDO
         CALL VECNORM(VEC1,NOPT)
      ENDIF

      DUMMY1=-1.0D10
      DO J1=1,NEVL
         IF (.NOT.FREEZE) THEN
            CALL ORTHOGOPT(VEC1,COORDS,.TRUE.)
         ELSE
            CALL VECNORM(VEC1,NOPT)
         ENDIF
         CALL DSYMV('U',NOPT,1.0D0,HESS,SIZE(HESS,1),VEC1,1,0.0D0,VEC2,1)
C        CALL MATMUL(VEC2,HESS,VEC1,3*NATOMS,3*NATOMS,1,NOPT,NOPT,1)
         DUMMY2=0.0D0
         DO J2=1,NOPT
            DUMMY2=DUMMY2+VEC2(J2)**2
         ENDDO
         EVALMAX=DSQRT(DUMMY2)
         DO J2=1,NOPT
            VEC2(J2)=VEC2(J2)/EVALMAX
         ENDDO
         PERCENT=100.0D0*DABS((DUMMY1-EVALMAX)/DUMMY1)
C        CALL EXTRAP(J1,NOPT,VEC2,PERCENT)
C        WRITE(*,'(A,4F20.10)') 'DUMMY1,EVALMAX,PERCENT,CEIG=',DUMMY1,EVALMAX,PERCENT,CEIG
         IF (100.0D0*DABS((DUMMY1-EVALMAX)/DUMMY1).LT.CEIG) THEN
            IF (PTEST) WRITE(*,'(A,I4,A,F15.7)') ' LARGEST  EIGENVALUE CONVERGED IN ',J1,' STEPS. EIGENVALUE=',EVALMAX
            GOTO 10
         ENDIF
C        WRITE(*,'(A,I4,A,F15.7,A,F15.7)') ' AT STEP ',J1,' % CHANGE=',PERCENT,' EIGENVALUE=',EVALMAX
         DUMMY1=EVALMAX

         DO J2=1,NOPT
            VEC1(J2)=VEC2(J2)
         ENDDO
      ENDDO

      IF (PTEST) WRITE(*,'(A,F15.7)') ' ****WARNING - LARGEST  EIGENVALUE DID NOT CONVERGE, VALUE=',EVALMAX
10    IF (ITER.GT.1) THEN
         DUMMY1=0.0D0
         DO J2=1,NOPT
            DUMMY1=DUMMY1+VECL(J2)*VEC2(J2)
         ENDDO
         IF (PTEST) WRITE(*,'(A,G12.4)') 
     1          ' OVERLAP BETWEEN PREVIOUS AND NEW EIGENVECTORS FOR LARGEST  EIGENVALUE=',DUMMY1
      ENDIF
      DO J2=1,NOPT
         VECL(J2)=VEC2(J2)
      ENDDO
C
C  SHIFT ALL THE EIGENVALUES ACCORDING TO THE SIZE OF EVALMAX.
C
      DO J1=1,NATOMS
         J2=3*(J1-1)
C        IF (.NOT.FROZEN(J1)) THEN
            HESS(J2+1,J2+1)=HESS(J2+1,J2+1)-EVALMAX*0.55D0
            HESS(J2+2,J2+2)=HESS(J2+2,J2+2)-EVALMAX*0.55D0
            HESS(J2+3,J2+3)=HESS(J2+3,J2+3)-EVALMAX*0.55D0
C        ENDIF
      ENDDO
C
C  NOW ESTIMATE THE NEW LARGEST MAGNITUDE EIGENVALUE OF HESS.
C
      IF ((ITER.EQ.1).AND.(.NOT.TWOENDS).AND.(.NOT.READV)) THEN
         DO J1=1,NOPT
            VEC1(J1)=2*(DPRAND()-0.5D0)
         ENDDO
         CALL VECNORM(VEC1,NOPT)
C        DO J1=1,NOPT
C           VEC1(J1)=0.0D0
C        ENDDO
C        VEC1(1)=1.0D0
      ELSE
         DO J1=1,NOPT
            VEC1(J1)=VECS(J1)
         ENDDO
      ENDIF
      IF (FREEZE) THEN
         DO J1=1,NATOMS
            IF (FROZEN(J1)) THEN
               VEC1(3*(J1-1)+1)=0.0D0
               VEC1(3*(J1-1)+2)=0.0D0
               VEC1(3*(J1-1)+3)=0.0D0
            ENDIF
         ENDDO
         CALL VECNORM(VEC1,NOPT)
      ENDIF
      DUMMY1=-1.0D10
      DO J1=1,NEVS
         IF (.NOT.FREEZE) THEN
            CALL ORTHOGOPT(VEC1,COORDS,.TRUE.)
         ELSE
            CALL VECNORM(VEC1,NOPT)
         ENDIF
         CALL DSYMV('U',NOPT,1.0D0,HESS,SIZE(HESS,1),VEC1,1,0.0D0,VEC2,1)

         DUMMY2=0.0D0
         DO J2=1,NOPT
            DUMMY2=DUMMY2+VEC2(J2)**2
         ENDDO
         EVALMIN=DSQRT(DUMMY2)
C
C  NORMALIZE. CHANGING THE PHASE MAY BE NECESSARY FOR EXTRAPOLATION TO WORK.
C
         DO J2=1,NOPT
            VEC2(J2)=-VEC2(J2)/EVALMIN
         ENDDO
         EVALMIN=-EVALMIN+EVALMAX*0.55D0
         PERCENT=100.0D0*DABS((DUMMY1-EVALMIN)/DUMMY1)
C        CALL EXTRAP(J1,NOPT,VEC2,PERCENT)
         IF (PERCENT.LT.CEIG) THEN
            IF (PTEST) WRITE(*,'(A,I4,A,F15.7)') ' SMALLEST EIGENVALUE CONVERGED IN ',J1,' STEPS. EIGENVALUE=',EVALMIN
            CONVERGED=.TRUE.
            GOTO 20
         ENDIF
C        WRITE(*,'(A,I4,A,F15.7,A,F15.7)') ' AT STEP ',J1,' % CHANGE=',PERCENT,' EIGENVALUE=',EVALMIN
         DUMMY1=EVALMIN

         DO J2=1,NOPT
            VEC1(J2)=VEC2(J2)
         ENDDO
      ENDDO
      IF (PTEST) WRITE(*,'(A,F15.7)') ' **WARNING - SMALLEST EIGENVALUE DID NOT CONVERGE, VALUE=',EVALMIN
      CONVERGED=.FALSE.
     
C 20    EVALMIN=-EVALMIN+EVALMAX*0.55D0
20    CONTINUE
      NS=J1
      IF (ITER.GT.1) THEN
         SOVER=0.0D0
         DO J1=1,NOPT
            SOVER=SOVER+VECS(J1)*VEC2(J1)
         ENDDO
         IF (PTEST) WRITE(*,'(A,G12.4)') ' OVERLAP BETWEEN PREVIOUS AND NEW EIGENVECTORS FOR SMALLEST EIGENVALUE=',SOVER
      ENDIF
C
C  THE FOLLOWING CODE SHOULD ALLOW US TO SEARCH ALONG OTHER EIGENVECTORS.
C
      IF ((IVEC.EQ.0).OR.((ITER.EQ.1).AND.(ABS(IVEC).EQ.1))) THEN
         DO J1=1,NOPT
            VECS(J1)=VEC2(J1)
         ENDDO
         JVECP=1
         RETURN
      ENDIF

      EVALS(1)=EVALMIN
      DO J1=1,NOPT
         VECCHK(J1,1)=VEC2(J1)
      ENDDO
      IF (ITER.GT.1) THEN
         DUMMY=0.0D0
         DO J1=1,NOPT
            DUMMY=DUMMY+VECS(J1)*VEC2(J1)
         ENDDO
         OVLAP(1)=ABS(DUMMY)
         IF (ABS(DUMMY).GT.0.8D0) THEN
            DO J1=1,NOPT
               VECS(J1)=VEC2(J1)
            ENDDO
            IF (PTEST) WRITE(*,'(A,F12.5,A,F12.5)') ' MODE    1 WILL BE SEARCHED UPHILL, OVERLAP=',OVLAP(1),' EIGENVALUE=',EVALMIN
            JVECP=1
            RETURN
         ENDIF
      ENDIF
      NMDONE=1
      JVEC=1
      OVMAX=OVLAP(1)
C
C  THE LARGEST EIGENVALUE IN MAGNITUDE OF THE SHIFTED HESSIAN IS 
C  GUARANTEED TO BE NEGATIVE. HOWEVER, IF WE NEED TO FIND OTHER
C  (SHIFTED) EIGENVALUES WE MUST ALLOW FOR THE POSSIBILITY THAT THEY COULD
C  BE POSITIVE.
C
      CHECKINDEX=.TRUE.
80    CONTINUE
      IF ((ITER.GT.1).AND.(NMDONE+1.LE.NMPREV)) THEN
         DO J1=1,NOPT
            VEC1(J1)=VECCHK(J1,NMDONE+1)
         ENDDO
      ELSE
         DO J1=1,NOPT
            VEC1(J1)=2*(DPRAND()-0.5D0)
         ENDDO
         CALL VECNORM(VEC1,NOPT)
      ENDIF
      IF (FREEZE) THEN
         DO J1=1,NATOMS
            IF (FROZEN(J1)) THEN
               VEC1(3*(J1-1)+1)=0.0D0
               VEC1(3*(J1-1)+2)=0.0D0
               VEC1(3*(J1-1)+3)=0.0D0
            ENDIF
         ENDDO
         CALL VECNORM(VEC1,NOPT)
      ENDIF

      DUMMY4=-1.0D10
      DO J1=1,NEVS
         IF (.NOT.FREEZE) THEN
            CALL ORTHOGOPT(VEC1,COORDS,.TRUE.)
         ELSE
            CALL VECNORM(VEC1,NOPT)
         ENDIF

         CALL DSYMV('U',NOPT,1.0D0,HESS,SIZE(HESS,1),VEC1,1,0.0D0,VEC2,1)
C        CALL MATMUL(VEC2,HESS,VEC1,3*NATOMS,3*NATOMS,1,NOPT,NOPT,1)

         DUMMY2=0.0D0
         DUMMY1=0.0D0
         NDUM=0
         DO J2=1,NOPT
            DUMMY2=DUMMY2+VEC2(J2)**2
            IF (VEC1(J2).NE.0.0D0) THEN
               DUMMY1=DUMMY1+VEC2(J2)/VEC1(J2)
               NDUM=NDUM+1
            ENDIF
         ENDDO
         EVALMIN=DSQRT(DUMMY2)
         DUMMY1=DUMMY1/MAX(NDUM,1)
         XSIGN=-1.0D0
         IF (DABS((DABS(DUMMY1)-DABS(EVALMIN))/EVALMIN).LT.0.1D0) XSIGN=DUMMY1/DABS(DUMMY1)
         EVALMIN=EVALMIN*XSIGN
C
C  NORMALIZE.
C
         DO J2=1,NOPT
            VEC2(J2)=VEC2(J2)/EVALMIN
         ENDDO

         EVALMIN=EVALMIN+EVALMAX*0.55D0
         PERCENT=100.0D0*DABS((DUMMY4-EVALMIN)/DUMMY4)
         IF (PERCENT.LT.CEIG) THEN
            IF (PTEST) WRITE(*,'(A,I4,A,F15.7)') ' NEW EIGENVALUE CONVERGED IN      ',J1,' STEPS. EIGENVALUE=',EVALMIN
            GOTO 90
         ENDIF
         DUMMY4=EVALMIN

         DO J2=1,NOPT
            VEC1(J2)=VEC2(J2)
         ENDDO
      ENDDO
      IF (PTEST) WRITE(*,'(A,F15.7)') ' ****WARNING - NEW EIGENVALUE  DID NOT CONVERGE, VALUE=  ',EVALMIN

90    CONTINUE

      NMDONE=NMDONE+1

      EVALS(NMDONE)=EVALMIN
      DO J2=1,NOPT
         VECCHK(J2,NMDONE)=VEC2(J2)
      ENDDO

      IF (ITER.GT.1) THEN
         DUMMY=0.0D0
         DO J1=1,NOPT
            DUMMY=DUMMY+VECS(J1)*VEC2(J1)
         ENDDO
         OVLAP(NMDONE)=ABS(DUMMY)
C        WRITE(*,'(A,I4,F15.5)') 'NMDONE,OVLAP=',NMDONE,OVLAP(NMDONE)
         IF (OVLAP(NMDONE).GT.OVMAX) THEN
            JVEC=NMDONE
            OVMAX=OVLAP(NMDONE)
         ENDIF
         IF (ABS(DUMMY).GT.0.8D0) THEN
            DO J1=1,NOPT
               VECS(J1)=VEC2(J1)
            ENDDO
            IF (PTEST) WRITE(*,'(A,I4,A,F12.5,A,F12.5)') ' MODE ',NMDONE,' WILL BE SEARCHED UPHILL, OVERLAP=',OVLAP(NMDONE),
     1                                ' EIGENVALUE=',EVALS(NMDONE)
            CHECKINDEX=.FALSE.
            JVECP=NMDONE
            RETURN
         ENDIF
      ELSE
         IF (NMDONE.EQ.ABS(IVEC)) THEN
            DO J1=1,NOPT
               VECS(J1)=VEC2(J1)
            ENDDO
            WRITE(*,'(A,I4,A,F12.5)') 'MODE ',NMDONE,' WILL BE SEARCHED UPHILL, EIGENVALUE=',EVALS(NMDONE)
            CHECKINDEX=.FALSE.
            JVECP=NMDONE
            RETURN
         ENDIF
      ENDIF

C     IF (NMDONE.EQ.30) THEN
      IF ((NMDONE.EQ.30).OR.(NMDONE.EQ.JVECP+3)) THEN
         DO J1=1,NOPT
            VECS(J1)=VECCHK(J1,JVEC)
         ENDDO
         EVALMIN=EVALS(JVEC)
         IF (PTEST) WRITE(*,'(I3,A,I3,A,F12.5,A,F12.5)') NMDONE,' EIGENVECTORS FOUND; USING NUMBER ',JVEC,
     1                                               ' EIGENVALUE=',EVALS(JVEC),' OVERLAP=',OVMAX
         CHECKINDEX=.FALSE.
         JVECP=JVEC
         RETURN
      ENDIF

      GOTO 80
! }}}
      RETURN
      END
! }}}
C
C  ESTIMATE THE SMALLEST NON-ZERO EIGENVALUE AND THE ASSOCIATED
C  EIGENVECTOR BY REPEATED ITERATION USING NESBET'S ALGORITHM.
C  THIS SEEMS TO GIVE THE LARGEST NOT THE SMALLEST EIGENVECTOR?
C     NOT USED
C
      SUBROUTINE ITEIGN(ITER,COORDS,VECS,EVALMIN,EVALMAX,PTEST)
      USE COMMONS
      USE KEY
      USE VECCK
      USE MODHESS
      IMPLICIT NONE

      INTEGER J1, J2, J3
      DOUBLE PRECISION COORDS(3*NATOMS),DUMMY1,VEC1(3*NATOMS),
     1                 VEC2(3*NATOMS),DUMMY2,EVALMAX,EVALMIN,
     2                 VECS(3*NATOMS),DELC,VECL(3*NATOMS)
      INTEGER ITER
      LOGICAL PTEST
      SAVE

      IF (ITER.EQ.1) THEN
         DO J1=1,NOPT
            VEC1(J1)=0.0D0
         ENDDO
         VEC1(1)=1.0D0
      ELSE
         DO J1=1,NOPT
            VEC1(J1)=VECL(J1)
         ENDDO
      ENDIF

      CALL DSYMV('U',NOPT,1.0D0,HESS,SIZE(HESS,1),VEC1,1,0.0D0,VEC2,1)

      DUMMY1=0.0D0
      DUMMY2=0.0D0
      DO J1=1,NOPT
         DUMMY1=DUMMY1+VEC1(J1)*VEC2(J1)
         DUMMY2=DUMMY2+VEC1(J1)**2
      ENDDO
      EVALMAX=DUMMY1/DUMMY2
      DUMMY1=EVALMAX
      
      DO J1=1,NEVL
         DO J2=2,NOPT
            DELC=(VEC2(J2)-DUMMY1*VEC1(J2))/(DUMMY1-HESS(J2,J2))
            VEC1(J2)=VEC1(J2)+DELC

            CALL DSYMV('U',NOPT,1.0D0,HESS,SIZE(HESS,1),VEC1,1,0.0D0,VEC2,1)
   
            DUMMY1=0.0D0
            DUMMY2=0.0D0
            DO J3=1,NOPT
               DUMMY1=DUMMY1+VEC1(J3)*VEC2(J3)
               DUMMY2=DUMMY2+VEC1(J3)**2
            ENDDO
            DUMMY1=DUMMY1/DUMMY2
            DUMMY2=1.0D0/DSQRT(DUMMY2)
         ENDDO
         IF ((100.0D0*DABS((DUMMY1-EVALMAX)/DUMMY1).LT.CEIG).AND.(J1.GT.1)) THEN
            IF (PTEST) WRITE(*,'(A,I4,A,F15.7)') ' LARGEST EIGENVALUE CONVERGED IN ',J1,' STEPS. EIGENVALUE=',DUMMY1
            GOTO 20
         ENDIF
         IF (PTEST) WRITE(*,'(A,I4,A,F15.7,A,F15.7)') ' AT STEP ',J1,' CONVERGENCE=',DABS(DUMMY1-EVALMAX),' EIGENVALUE=',DUMMY1
         EVALMAX=DUMMY1
      ENDDO
      IF (PTEST) WRITE(*,'(A,F15.7)') ' ****WARNING - LARGEST EIGENVALUE DID NOT CONVERGE, VALUE=',EVALMAX
     
20    CONTINUE
      DO J2=1,NOPT
         VECL(J2)=VEC1(J2)
      ENDDO
C
C  SHIFT ALL THE EIGENVALUES ACCORDING TO THE SIZE OF EVALMAX.
C
      DO J1=1,NOPT
         HESS(J1,J1)=HESS(J1,J1)-EVALMAX*0.55D0
      ENDDO
C
C  NOW ESTIMATE THE NEW LARGEST MAGNITUDE EIGENVALUE OF HESS.
C
      IF (ITER.EQ.1) THEN
         DO J1=1,NOPT
            VEC1(J1)=0.0D0
         ENDDO
         VEC1(1)=1.0D0
      ELSE
         DO J1=1,NOPT
            VEC1(J1)=VECS(J1)
         ENDDO
      ENDIF

      CALL DSYMV('U',NOPT,1.0D0,HESS,SIZE(HESS,1),VEC1,1,0.0D0,VEC2,1)

      DUMMY1=0.0D0
      DUMMY2=0.0D0
      DO J1=1,NOPT
         DUMMY1=DUMMY1+VEC1(J1)*VEC2(J1)
         DUMMY2=DUMMY2+VEC1(J1)**2
      ENDDO
      EVALMIN=DUMMY1/DUMMY2
      DUMMY1=EVALMIN

      DO J1=1,NEVS
         DO J2=1,NOPT-1
            DELC=(VEC2(J2)-DUMMY1*VEC1(J2))/(DUMMY1-HESS(J2,J2))
            VEC1(J2)=VEC1(J2)+DELC

            CALL DSYMV('U',NOPT,1.0D0,HESS,SIZE(HESS,1),VEC1,1,0.0D0,VEC2,1)
   
            DUMMY1=0.0D0
            DUMMY2=0.0D0
            DO J3=1,NOPT
               DUMMY1=DUMMY1+VEC1(J3)*VEC2(J3)
               DUMMY2=DUMMY2+VEC1(J3)**2
            ENDDO

            DUMMY1=DUMMY1/DUMMY2

            DUMMY2=1.0D0/DSQRT(DUMMY2)
            DO J3=1,NOPT
               VEC1(J3)=VEC1(J3)*DUMMY2
            ENDDO
            CALL ORTHOGOPT(VEC1,COORDS,.TRUE.)
         ENDDO
         IF (100.0D0*DABS((DUMMY1-EVALMIN)/DUMMY1).LT.CEIG) THEN
            IF (PTEST) WRITE(*,'(A,I4,A,F15.7)') ' SMALLEST EIGENVALUE CONVERGED IN ',J1,' STEPS. EIGENVALUE=', EVALMIN+EVALMAX*0.55D0
            GOTO 30
         ENDIF
         IF (PTEST) WRITE(*,'(A,I4,A,F15.7,A,F15.7)') ' AT STEP ',J1,' CONVERGENCE=',DABS(DUMMY1-EVALMIN),
     1           ' EIGENVALUE=', EVALMIN+EVALMAX*0.55D0
         EVALMIN=DUMMY1
      ENDDO
      IF (PTEST) WRITE(*,'(A,F15.7)') ' **WARNING - SMALLEST EIGENVALUE DID NOT CONVERGE, VALUE=', EVALMIN+EVALMAX*0.55D0
     
30    EVALMIN= EVALMIN+EVALMAX*0.55D0
      DUMMY1=0.0D0
      DO J2=1,NOPT
         DUMMY1=DUMMY1+VEC1(J2)**2
      ENDDO
      DUMMY1=1.0D0/SQRT(DUMMY1)
      DO J2=1,NOPT
         VECS(J2)=VEC1(J2)*DUMMY1
      ENDDO

      RETURN
      END
C
C  COUNT THE NUMBER OF NEGATIVE HESSIAN EIGENVALUES BY FURTHER ITERATION AND
C  ORTHOGONALIZATION IF REQUIRED.
C
      SUBROUTINE CHECKIND(COORDS,MFLAG,INEG,ENERGY,EVALMIN,EVALMAX,PTEST)
      USE COMMONS
      USE KEY
      USE VECCK
      USE ZWK
      USE MODHESS
      IMPLICIT NONE

      INTEGER J1, J2, INEG, ISEED, NDUM, NS
      DOUBLE PRECISION COORDS(3*NATOMS),DUMMY1,VEC1(3*NATOMS),
     1                 VEC2(3*NATOMS),DUMMY2,EVALMAX,EVALMIN,
     2                 ENERGY,DPRAND,XSIGN,VECS(3*NATOMS),
     3                 DUMMY4,SOVER,VECL(3*NATOMS)
      LOGICAL MFLAG,PTEST,CONVERGED
      COMMON /IS/ ISEED
C
C  ASSIGN ENOUGH MEMORY TO WORK FOR A BLOCKSIZE OF 32 TO BE POSSIBLE.
C  THIS IS FOR DSYEVR.
C
      INTEGER ILWORK, LWORK, NFOUND, ISUPPZ(2*3*NATOMS)
      INTEGER IWORK(33*3*NATOMS), INFO
      DOUBLE PRECISION WORK(33*3*NATOMS),  ABSTOL, DIAG(3*NATOMS), DLAMCH

      FIXIMAGE=.TRUE.
      LWORK=33*3*NATOMS
      ILWORK=33*3*NATOMS

      IF (NOIT) THEN
         CALL POTENTIAL(COORDS,ENERGY,VEC1,.TRUE.,.TRUE.,DUMMY1,PTEST,.FALSE.) 
         IF (.NOT.VARIABLES) THEN
            IF (ZSYM(NATOMS).EQ.'TH') THEN
               CALL SHIFTHTH(COORDS,NATOMS)
            ELSEIF (RBAAT) THEN
               CALL SHIFTRIGID(COORDS,NATOMS)
            ELSE
               CALL SHIFTH(COORDS,.TRUE.,NOPT,NATOMS,ATMASS)
            ENDIF
         ENDIF
         ABSTOL=DLAMCH('SAFE  MINIMUM')
         CALL DSYEVR('V','I','U',NOPT,HESS,SIZE(HESS,1),0.0D0,1.0D0,1,10,ABSTOL,NFOUND,DIAG,ZWORK,3*NATOMS,ISUPPZ,WORK,
     1                        LWORK, IWORK, ILWORK, INFO )
         IF (INFO.NE.0) PRINT*,'WARNING - INFO=',INFO,' IN DSYEVR'
C        PRINT*,'OPTIMAL AND ACTUAL VALUES OF LWORK=',WORK(1),LWORK
C        PRINT*,'OPTIMAL AND ACTUAL VALUES OF ILWORK=',IWORK(1),ILWORK
         EVALMIN=DIAG(1)
         SOVER=0.0D0
         WRITE(*,'(A)') 'LOWEST 10 NON-ZERO HESSIAN EIGENVALUES:'
         WRITE(*,'(5F15.5)') (DIAG(J1),J1=1,10)
         DO J1=1,10
            DO J2=1,NOPT
               VECCHK(J2,J1)=ZWORK(J2,J1)
            ENDDO
         ENDDO
      ELSE
         DO J1=1,NOPT
            VECS(J1)=ZWORK(J1,1)
         ENDDO
C
C  GET THE LARGEST AND SMALLEST EIGENVALUES IF WE DON'T ALREADY KNOW THEM.
C
         IF (BFGSMINT.OR.RKMIN.OR.BSMIN) THEN
            CALL ITEIG(1,COORDS,VECS,EVALMIN,EVALMAX,NS,SOVER,PTEST,VECL,CONVERGED)
            IF (.NOT.CONVERGED) WRITE(*,'(A,F15.7)') ' **WARNING - SMALLEST EIGENVALUE DID NOT CONVERGE, VALUE=',EVALMIN
            IF (EVALMIN.LT.0.0D0) THEN
               INEG=1
            ELSE
               INEG=0
            ENDIF
         ENDIF
         NMDONE=INEG
         IF (EVALMIN.GT.0.0D0) THEN
            WRITE(*,'(A,F20.10)') ' HESSIAN INDEX IS 0, SMALLEST EIGENVECTOR=',EVALMIN
            GOTO 666
         ENDIF
   
         IF (INEG.EQ.1) THEN
            DO J1=1,NOPT
               VECCHK(J1,1)=VECS(J1)
            ENDDO
         ENDIF
C
C  THE LARGEST EIGENVALUE IN MAGNITUDE OF THE SHIFTED HESSIAN IS 
C  GUARANTEED TO BE NEGATIVE. HOWEVER, IF WE NEED TO FIND OTHER
C  (SHIFTED) EIGENVALUES WE MUST ALLOW FOR THE POSSIBILITY THAT THEY COULD
C  BE POSITIVE.
C

80       NMDONE=INEG
         DO J1=1,NOPT
            VEC1(J1)=2*(DPRAND()-0.5D0)
         ENDDO
         CALL VECNORM(VEC1,NOPT)
   
         DUMMY4=-1.0D10
         DO J1=1,NEVS
            CALL ORTHOGOPT(VEC1,COORDS,.TRUE.)

            CALL DSYMV('U',NOPT,1.0D0,HESS,SIZE(HESS,1),VEC1,1,0.0D0,VEC2,1)
C           CALL MATMUL(VEC2,HESS,VEC1,3*NATOMS,3*NATOMS,1,NOPT,NOPT,1)

            DUMMY2=0.0D0
            DUMMY1=0.0D0
            NDUM=0
            DO J2=1,NOPT
               DUMMY2=DUMMY2+VEC2(J2)**2
               IF (VEC1(J2).NE.0.0D0) THEN
                  DUMMY1=DUMMY1+VEC2(J2)/VEC1(J2)
                  NDUM=NDUM+1
               ENDIF
            ENDDO
            EVALMIN=DSQRT(DUMMY2)
            DUMMY1=DUMMY1/MAX(NDUM,1)
            XSIGN=-1.0D0
            IF (DABS((DABS(DUMMY1)-DABS(EVALMIN))/EVALMIN).LT.0.1D0) XSIGN=DUMMY1/DABS(DUMMY1)
            EVALMIN=EVALMIN*XSIGN
C
C  NORMALIZE.
C
            DO J2=1,NOPT
               VEC2(J2)=VEC2(J2)/EVALMIN
            ENDDO
            IF (100.0D0*DABS((DUMMY4-EVALMIN)/DUMMY4).LT.CEIG) THEN
               IF (PTEST) WRITE(*,'(A,I4,A,F15.7)') ' NEW EIGENVECTOR CONVERGED IN ',J1,' STEPS. EIGENVALUE=',EVALMIN+EVALMAX*0.55D0
               GOTO 90
            ENDIF
C           WRITE(*,'(A,I4,A,F15.7,A,F15.7)') ' AT STEP ',J1,' % CHANGE=',100.0D0*DABS((DUMMY4-EVALMIN)/DUMMY4),
C    1              ' EIGENVALUE=',EVALMIN+EVALMAX*0.55D0
            DUMMY4=EVALMIN

            DO J2=1,NOPT
               VEC1(J2)=VEC2(J2)
            ENDDO
         ENDDO
         IF (PTEST) WRITE(*,'(A,F15.7)') ' ****WARNING - NEW EIGENVECTOR DID NOT CONVERGE, VALUE=',EVALMIN+EVALMAX*0.55D0

90       EVALMIN=EVALMIN+EVALMAX*0.55D0
         IF (EVALMIN.GT.0.0D0) THEN
            PRINT*,'HESSIAN INDEX=',INEG
         ELSE
            INEG=INEG+1
            IF (INEG.GT.10) THEN
               PRINT*,'HESSIAN INDEX IS 10 OR GREATER'
               FIXIMAGE=.FALSE.
               RETURN
            ENDIF
            DO J2=1,NOPT
               VECCHK(J2,INEG)=VEC2(J2)
            ENDDO
            GOTO 80
         ENDIF
      ENDIF

666   CONTINUE

      IF (((BFGSMINT).AND.(INEG.NE.0)).AND.CHECKCONT) THEN
         MFLAG=.FALSE.
         IF (IVEC.GE.0) PRINT*,'STEPPING AWAY FROM SADDLE ALONG MODE ',1,' + DIRECTION'
         IF (IVEC.LT.0) PRINT*,'STEPPING AWAY FROM SADDLE ALONG MODE ',1,' - DIRECTION'
         DUMMY1=PUSHOFF
         IF (IVEC.LT.0) DUMMY1=-DUMMY1
         DO J1=1,NOPT
            COORDS(J1)=COORDS(J1)+DUMMY1*VECCHK(J1,1)
         ENDDO
         INEG=0
         NMDONE=0
      ENDIF
      IF (((BFGSTST).AND.(INEG.NE.1)).AND.CHECKCONT) THEN
         MFLAG=.FALSE.
         IF (IVEC.GE.0) PRINT*,'STEPPING AWAY FROM SADDLE ALONG MODE ',1,' + DIRECTION'
         IF (IVEC.LT.0) PRINT*,'STEPPING AWAY FROM SADDLE ALONG MODE ',1,' - DIRECTION'
         DUMMY1=PUSHOFF
         IF (IVEC.LT.0) DUMMY1=-DUMMY1
         DO J1=1,NOPT
            COORDS(J1)=COORDS(J1)+DUMMY1*VECCHK(J1,2)
         ENDDO
         INEG=0
         NMDONE=0
      ENDIF

      FIXIMAGE=.FALSE.
      RETURN
      END
C
C*************************************************************************
C
C  CHECK THE HESSIAN INDEX - ASSUMES NO HESSIAN IS AVAILABLE.
C
      SUBROUTINE CHECKIND2(COORDS,MFLAG,INEG,ENERGY)
      USE COMMONS
      USE KEY
      USE VECCK
      USE ZWK
      IMPLICIT NONE

      INTEGER J1, J2, INEG, NS, ISEED
      DOUBLE PRECISION COORDS(3*NATOMS),ENERGY,DUMMY1, VEC2(3*NATOMS),EVALMIN, VECS(3*NATOMS),DPRAND, SOVER
      LOGICAL MFLAG, CONVERGED
      COMMON /IS/ ISEED

      DO J1=1,NOPT
         VECS(J1)=ZWORK(J1,1)
      ENDDO
      FIXIMAGE=.TRUE.

      IF (INEG.EQ.1) THEN
         DO J1=1,NOPT
            VECCHK(J1,1)=VECS(J1)
         ENDDO
      ENDIF

80    NMDONE=INEG
      DO J1=1,NOPT
         VEC2(J1)=2*(DPRAND()-0.5D0)
      ENDDO
      CALL VECNORM(VEC2,NOPT)

      CALL BEIG(1,COORDS,ENERGY,VEC2,EVALMIN,NS,SOVER,.TRUE.,CONVERGED)

      IF (EVALMIN.GT.0.0D0) THEN
         PRINT*,'HESSIAN INDEX=',INEG
      ELSE
         INEG=INEG+1
         IF (INEG.GT.10) THEN
            PRINT*,' HESSIAN INDEX IS 10 OR GREATER'
            FIXIMAGE=.FALSE.
            RETURN
         ENDIF
         DO J2=1,NOPT
            VECCHK(J2,INEG)=VEC2(J2)
         ENDDO
         GOTO 80
      ENDIF

      IF (((BFGSMINT).AND.(INEG.NE.0)).AND.CHECKCONT) THEN
         MFLAG=.FALSE.
         IF (IVEC.GE.0) PRINT*,'STEPPING AWAY FROM SADDLE ALONG MODE ',1,' + DIRECTION'
         IF (IVEC.LT.0) PRINT*,'STEPPING AWAY FROM SADDLE ALONG MODE ',1,' - DIRECTION'
         DUMMY1=PUSHOFF
         IF (IVEC.LT.0) DUMMY1=-DUMMY1
         DO J1=1,NOPT
            COORDS(J1)=COORDS(J1)+DUMMY1*VECCHK(J1,1)
         ENDDO
         INEG=0
         NMDONE=0
      ENDIF
      IF (((BFGSTST).AND.(INEG.NE.1)).AND.CHECKCONT) THEN
         MFLAG=.FALSE.
         IF (IVEC.GE.0) PRINT*,'STEPPING AWAY FROM SADDLE ALONG MODE ',1,' + DIRECTION'
         IF (IVEC.LT.0) PRINT*,'STEPPING AWAY FROM SADDLE ALONG MODE ',1,' - DIRECTION'
         DUMMY1=PUSHOFF
         IF (IVEC.LT.0) DUMMY1=-DUMMY1
         DO J1=1,NOPT
            COORDS(J1)=COORDS(J1)+DUMMY1*VECCHK(J1,2)
         ENDDO
         INEG=0
         NMDONE=0
      ENDIF

      FIXIMAGE=.FALSE.
      RETURN
      END

C
C  AITKEN'S EXTRAPOLATION METHOD. SEE "NUMERICAL METHODS THAT WORK"  P. 216.
C
      SUBROUTINE EXTRAP(NSTEP,NOPT,VEC,PERCENT)
      IMPLICIT NONE
      INTEGER I,NOPT,NSTEP
      DOUBLE PRECISION VECT(NOPT,3),VEC(NOPT),Z,B,D,DUMMY,PERCENT

      DO I=1,NOPT
         VECT(I,1)=VECT(I,2)
         VECT(I,2)=VECT(I,3)
         VECT(I,3)=VEC(I)   !  IS THIS RIGHT? 
      ENDDO
      IF ((NSTEP.LT.3).OR.(MOD(NSTEP,3).NE.0)) RETURN
      IF (PERCENT.GT.10.0D0) RETURN

      DO I=1,NOPT
         D=VECT(I,1)-2.0*VECT(I,2)+VECT(I,3)
         B=VECT(I,2)-VECT(I,3)
         IF (D.EQ.0.0D0) THEN
            Z=0.0D0
         ELSE
            Z=B*B/D
         ENDIF
         IF (ABS(Z).GT.ABS(VEC(I))/20.0D0) Z=0.0D0
         VECT(I,1)=Z
      ENDDO
      PRINT*,'EXTRAPOLATING'
      DUMMY=0.0D0
      DO I=1,NOPT
         VEC(I)=VECT(I,3)-VECT(I,1)
         DUMMY=DUMMY+VEC(I)**2
      ENDDO
      DUMMY=1.0D0/SQRT(DUMMY)
      PRINT*,'DUMMY=',DUMMY
      DO I=1,NOPT
         VEC(I)=VEC(I)*DUMMY
      ENDDO

      RETURN
      END

      DOUBLE PRECISION FUNCTION MINIM(A,B,BOXL)
      IMPLICIT NONE
      DOUBLE PRECISION A, B, BOXL

      MINIM=A-B-BOXL*ANINT((A-B)/BOXL)

      RETURN
      END

      SUBROUTINE HSMOVE(COORDS,COORDSN,FIXDIR,STEP,PTEST)
      USE COMMONS
      USE KEY
      USE PORFUNCS
      IMPLICIT NONE
      INTEGER J1, J2, PARTNR(NATOMS), J3, NTYPEA, NMOVE, NUMBERS(NATOMS), NPAIR, ISTAT, NCOLL
      DOUBLE PRECISION COORDS(3*NATOMS), FIXDIR(3*NATOMS), COLTIM(NATOMS), TIMBIG, RX12, RY12, RZ12, MINIM, STEP,
     1                 VX12, VY12, VZ12, B12, R12SQ, V12SQ, DISCR, SIGSQ, T12, COLTIM2(NATOMS), T122, DNEW, COORDSN(3*NATOMS)
      DOUBLE PRECISION EPSAB, EPSBB, SIGAB, SIGBB
      LOGICAL PTEST
      COMMON /BIN/ EPSAB, EPSBB, SIGAB, SIGBB, NTYPEA
      COMMON /HS/ NMOVE

      TIMBIG=1.0D100
      IF (.NOT.BINARY) SIGSQ=1.0D0
      IF (ZSYM(1)(1:2).EQ.'C6') SIGSQ=7.0D0
      IF (ZSYM(1)(1:2).EQ.'CA') SIGSQ=45.0D0

      DO J1=1,NATOMS
         COLTIM(J1)=TIMBIG
      ENDDO
      NCOLL=0

      DO J1=1,3*NATOMS
         COORDSN(J1)=COORDS(J1)
      ENDDO
     
C     DO J1=1,NATOMS
C        J2=3*(J1-1)
C        WRITE(*,'(A4,6G17.10)') 'AX  ',COORDS(J2+1),COORDS(J2+2),COORDS(J2+3),FIXDIR(J2+1),FIXDIR(J2+2),FIXDIR(J2+3)
C     ENDDO

      IF (TWOD) THEN
         DO J1=1,NATOMS
            FIXDIR(3*(J1-1)+3)=0.0D0
         ENDDO
      ENDIF

      DO J1=1,NATOMS
         DO J2=J1+1,NATOMS

            IF (BULKT) THEN
               RX12=MINIM(COORDSN(3*(J1-1)+1),COORDSN(3*(J2-1)+1),PARAM1)
               RY12=MINIM(COORDSN(3*(J1-1)+2),COORDSN(3*(J2-1)+2),PARAM2)
               RZ12=MINIM(COORDSN(3*(J1-1)+3),COORDSN(3*(J2-1)+3),PARAM3)
            ELSE
               RX12=COORDSN(3*(J1-1)+1)-COORDSN(3*(J2-1)+1)
               RY12=COORDSN(3*(J1-1)+2)-COORDSN(3*(J2-1)+2)
               RZ12=COORDSN(3*(J1-1)+3)-COORDSN(3*(J2-1)+3)
            ENDIF

            VX12=FIXDIR(3*(J1-1)+1)-FIXDIR(3*(J2-1)+1)
            VY12=FIXDIR(3*(J1-1)+2)-FIXDIR(3*(J2-1)+2)
            VZ12=FIXDIR(3*(J1-1)+3)-FIXDIR(3*(J2-1)+3)

            B12=RX12*VX12+RY12*VY12+RZ12*VZ12
C           PRINT*,'J1,J2,B12=',J1,J2,B12

            IF (B12.LT.0.0D0) THEN
               R12SQ=RX12**2+RY12**2+RZ12**2
               V12SQ=VX12**2+VY12**2+VZ12**2
               IF (BINARY) THEN
                  IF (J1.LE.NTYPEA) THEN
                     IF (J2.LE.NTYPEA) THEN
                        DISCR=B12**2-V12SQ*(R12SQ-1.0D0)
                     ELSE
                        DISCR=B12**2-V12SQ*(R12SQ-SIGAB**2*0.81D0)
                     ENDIF
                  ELSE
                     DISCR=B12**2-V12SQ*(R12SQ-SIGBB**2*0.81D0)
                  ENDIF
               ELSE
                  DISCR=B12**2-V12SQ*(R12SQ-SIGSQ)
               ENDIF
C              WRITE(*,'(A,5G20.10)') 'B12,V12SQ,R12SQ,SIGSQ,DISCR=',B12,V12SQ,R12SQ,SIGSQ,DISCR
               IF (DISCR.GT.0.0D0) THEN
                  T12=(-B12-SQRT(DISCR))/V12SQ
C                 WRITE(*,'(A,2I4,4G20.10)') 'J1,J2,T12,B12,SQRT(DISCR),V12SQ=',J1,J2,T12,B12,SQRT(DISCR),V12SQ
   
                  IF (ABS(T12).LT.COLTIM(J1)) THEN
                     NCOLL=NCOLL+1
                     COLTIM(J1)=ABS(T12)
                     COLTIM2(J1)=(-B12+SQRT(DISCR))/V12SQ
                     PARTNR(J1)=J2
                  ENDIF
   
                  IF (ABS(T12).LT.COLTIM(J2)) THEN
                     COLTIM(J2)=ABS(T12)
                     COLTIM2(J2)=(-B12+SQRT(DISCR))/V12SQ
                     PARTNR(J2)=J1
                  ENDIF
               ENDIF
            ENDIF
         ENDDO
      ENDDO

      IF (NCOLL.LT.NMOVE) THEN
         WRITE(*,'(A)') ' WARNING - INSUFFICIENT  COLLISIONS FOR INPUT VELOCITIES'
         COORDSN(1:3*NATOMS)=COORDSN(1:3*NATOMS)+FIXDIR(1:3*NATOMS)/2.0D0
         FIXDIR(1:3*NATOMS)=COORDSN(1:3*NATOMS)-COORDS(1:3*NATOMS)
         STEP=0.0D0
         DO J3=1,3*NATOMS
            STEP=STEP+(COORDSN(J3)-COORDS(J3))**2
         ENDDO
         STEP=SQRT(STEP)
         CALL ORTHOGOPT(FIXDIR,COORDS,.TRUE.)
         RETURN
      ENDIF

      DO J1=1,NATOMS
         NUMBERS(J1)=J1
      ENDDO
      CALL SORTN(NATOMS,COLTIM,NUMBERS)

C     T12=TIMBIG
C     DO J1=1,NATOMS
C        IF (COLTIM(J1).LT.T12) THEN
C           T12=COLTIM(J1)
C           T122=COLTIM2(J1)
C           J2=J1
C        ENDIF
C     ENDDO

      DO NPAIR=1,NMOVE

      J2=NUMBERS(NPAIR)
      J1=PARTNR(J2)
C     PRINT*,'NPAIR,J2,J1=',NPAIR,J2,J1
      T12=COLTIM(NPAIR)
      T122=COLTIM2(J2)

      IF (PTEST) WRITE(*,'(A,I4,A,I4,A,I4,A,G15.6)') ' COLLISION ',NPAIR,' IS BETWEEN ATOMS ',J1,' AND ',J2,' AT TIME ',T12
C
C  ADVANCE ALL POSITIONS TO TIME T12*T12FAC. 
C
      IF (T12FAC.LE.1.0D0) THEN
         DO J3=1,NATOMS
            COLTIM(J3)=COLTIM(J3)-T12*T12FAC
            COORDSN(3*(J3-1)+1)=COORDSN(3*(J3-1)+1)+FIXDIR(3*(J3-1)+1)*T12*T12FAC
            COORDSN(3*(J3-1)+2)=COORDSN(3*(J3-1)+2)+FIXDIR(3*(J3-1)+2)*T12*T12FAC
            COORDSN(3*(J3-1)+3)=COORDSN(3*(J3-1)+3)+FIXDIR(3*(J3-1)+3)*T12*T12FAC
C
C  COULD PUT ATOMS LEAVING THE PRIMARY SUPERCELL BACK IN THE BOX HERE
C  IF DESIRED.
C
         ENDDO
C
C  ADVANCE POSITIONS OF THE COLLIDING PAIR ONLY TO TIME T12. 
C
C        COORDSN(3*(J1-1)+1)=COORDSN(3*(J1-1)+1)+FIXDIR(3*(J1-1)+1)*T12
C        COORDSN(3*(J1-1)+2)=COORDSN(3*(J1-1)+2)+FIXDIR(3*(J1-1)+2)*T12
C        COORDSN(3*(J1-1)+3)=COORDSN(3*(J1-1)+3)+FIXDIR(3*(J1-1)+3)*T12
C        COORDSN(3*(J2-1)+1)=COORDSN(3*(J2-1)+1)+FIXDIR(3*(J2-1)+1)*T12
C        COORDSN(3*(J2-1)+2)=COORDSN(3*(J2-1)+2)+FIXDIR(3*(J2-1)+2)*T12
C        COORDSN(3*(J2-1)+3)=COORDSN(3*(J2-1)+3)+FIXDIR(3*(J2-1)+3)*T12

         IF (BULKT) THEN
            IF (PTEST) PRINT*,'SEPARATION BETWEEN THESE ATOMS IS NOW ',
     1                                  SQRT(MINIM(COORDSN(3*(J1-1)+1),COORDSN(3*(J2-1)+1),PARAM1)**2
     2                                      +MINIM(COORDSN(3*(J1-1)+2),COORDSN(3*(J2-1)+2),PARAM2)**2
     3                                      +MINIM(COORDSN(3*(J1-1)+3),COORDSN(3*(J2-1)+3),PARAM3)**2)
         ELSE
            IF (PTEST) PRINT*,'SEPARATION BETWEEN THESE ATOMS IS NOW ',SQRT((COORDSN(3*(J1-1)+1)-COORDSN(3*(J2-1)+1))**2
     1                                      +(COORDSN(3*(J1-1)+2)-COORDSN(3*(J2-1)+2))**2
     2                                      +(COORDSN(3*(J1-1)+3)-COORDSN(3*(J2-1)+3))**2)
         ENDIF
      ELSE 
C
C  PUT THE FIRST COLLIDING PAIR HALF WAY BETWEEN THEIR ENTRANCE/EXIT POSITIONS
C

         COORDSN(3*(J1-1)+1)=COORDSN(3*(J1-1)+1)+FIXDIR(3*(J1-1)+1)*(T122-T12)/2
         COORDSN(3*(J1-1)+2)=COORDSN(3*(J1-1)+2)+FIXDIR(3*(J1-1)+2)*(T122-T12)/2
         COORDSN(3*(J1-1)+3)=COORDSN(3*(J1-1)+3)+FIXDIR(3*(J1-1)+3)*(T122-T12)/2
         COORDSN(3*(J2-1)+1)=COORDSN(3*(J2-1)+1)+FIXDIR(3*(J2-1)+1)*(T122-T12)/2
         COORDSN(3*(J2-1)+2)=COORDSN(3*(J2-1)+2)+FIXDIR(3*(J2-1)+2)*(T122-T12)/2
         COORDSN(3*(J2-1)+3)=COORDSN(3*(J2-1)+3)+FIXDIR(3*(J2-1)+3)*(T122-T12)/2

         IF (BULKT) THEN
            DNEW=SQRT(MINIM(COORDSN(3*(J1-1)+1),COORDSN(3*(J2-1)+1),PARAM1)**2
     1            +MINIM(COORDSN(3*(J1-1)+2),COORDSN(3*(J2-1)+2),PARAM2)**2
     2            +MINIM(COORDSN(3*(J1-1)+3),COORDSN(3*(J2-1)+3),PARAM3)**2)
         ELSE
            DNEW=SQRT((COORDSN(3*(J1-1)+1)-COORDSN(3*(J2-1)+1))**2
     1            +(COORDSN(3*(J1-1)+2)-COORDSN(3*(J2-1)+2))**2
     2            +(COORDSN(3*(J1-1)+3)-COORDSN(3*(J2-1)+3))**2)
         ENDIF
         IF (PTEST) PRINT*,'SEPARATION HALF WAY BETWEEN ENTRANCE AND EXIT=',DNEW

         IF (BINARY) THEN
            IF (J1.LE.NTYPEA) THEN
               IF (J2.LE.NTYPEA) THEN
                  SIGSQ=1.0D0
               ELSE
                  SIGSQ=SIGAB**2*0.81D0
               ENDIF
            ELSE
               SIGSQ=SIGBB**2*0.81D0
            ENDIF
         ENDIF
C
C  RESCALE THE DISTANCE BETWEEN THE FIRST COLLIDING PAIR
C
         IF (BULKT) THEN
            RX12=MINIM(COORDSN(3*(J1-1)+1),COORDSN(3*(J2-1)+1),PARAM1)*SQRT(SIGSQ)/DNEW/2
            RY12=MINIM(COORDSN(3*(J1-1)+2),COORDSN(3*(J2-1)+2),PARAM2)*SQRT(SIGSQ)/DNEW/2
            RZ12=MINIM(COORDSN(3*(J1-1)+3),COORDSN(3*(J2-1)+3),PARAM3)*SQRT(SIGSQ)/DNEW/2

            VX12=MINIM(COORDSN(3*(J1-1)+1),COORDSN(3*(J2-1)+1),PARAM1)
            VY12=MINIM(COORDSN(3*(J1-1)+2),COORDSN(3*(J2-1)+2),PARAM2)
            VZ12=MINIM(COORDSN(3*(J1-1)+3),COORDSN(3*(J2-1)+3),PARAM3)

            COORDSN(3*(J1-1)+1)=COORDSN(3*(J1-1)+1)-VX12/2+RX12
            COORDSN(3*(J1-1)+2)=COORDSN(3*(J1-1)+2)-VY12/2+RY12
            COORDSN(3*(J1-1)+3)=COORDSN(3*(J1-1)+3)-VZ12/2+RZ12
            COORDSN(3*(J2-1)+1)=COORDSN(3*(J2-1)+1)+VX12/2-RX12
            COORDSN(3*(J2-1)+2)=COORDSN(3*(J2-1)+2)+VY12/2-RY12
            COORDSN(3*(J2-1)+3)=COORDSN(3*(J2-1)+3)+VZ12/2-RZ12

            DNEW=SQRT(MINIM(COORDSN(3*(J1-1)+1),COORDSN(3*(J2-1)+1),PARAM1)**2
     1            +MINIM(COORDSN(3*(J1-1)+2),COORDSN(3*(J2-1)+2),PARAM2)**2
     2            +MINIM(COORDSN(3*(J1-1)+3),COORDSN(3*(J2-1)+3),PARAM3)**2)
         ELSE
            RX12=(COORDSN(3*(J1-1)+1)-COORDSN(3*(J2-1)+1))*SQRT(SIGSQ)/DNEW/2
            RY12=(COORDSN(3*(J1-1)+2)-COORDSN(3*(J2-1)+2))*SQRT(SIGSQ)/DNEW/2
            RZ12=(COORDSN(3*(J1-1)+3)-COORDSN(3*(J2-1)+3))*SQRT(SIGSQ)/DNEW/2
            VX12=(COORDSN(3*(J1-1)+1)+COORDSN(3*(J2-1)+1))/2
            VY12=(COORDSN(3*(J1-1)+2)+COORDSN(3*(J2-1)+2))/2
            VZ12=(COORDSN(3*(J1-1)+3)+COORDSN(3*(J2-1)+3))/2
            COORDSN(3*(J1-1)+1)=VX12+RX12
            COORDSN(3*(J1-1)+2)=VY12+RY12
            COORDSN(3*(J1-1)+3)=VZ12+RZ12

            COORDSN(3*(J2-1)+1)=VX12-RX12
            COORDSN(3*(J2-1)+2)=VY12-RY12
            COORDSN(3*(J2-1)+3)=VZ12-RZ12

            DNEW=SQRT((COORDSN(3*(J1-1)+1)-COORDSN(3*(J2-1)+1))**2
     1               +(COORDSN(3*(J1-1)+2)-COORDSN(3*(J2-1)+2))**2
     2               +(COORDSN(3*(J1-1)+3)-COORDSN(3*(J2-1)+3))**2)
         ENDIF
         IF (PTEST) PRINT*,'SEPARATION RESET TO ',DNEW
      ENDIF

      STEP=0.0D0
      DO J3=1,3*NATOMS
         FIXDIR(J3)=COORDSN(J3)-COORDS(J3)
         STEP=STEP+(COORDSN(J3)-COORDS(J3))**2
      ENDDO
      STEP=SQRT(STEP)
      CALL ORTHOGOPT(FIXDIR,COORDS,.TRUE.)

      ENDDO

      CALL FLUSH(6,ISTAT)

      RETURN
      END

      SUBROUTINE SORTN(N,A,NA)
      IMPLICIT NONE
      INTEGER J1, L, N, J2, NA(N), NTEMP
      DOUBLE PRECISION TEMP, A(N)
C
      DO J1=1,N-1
         L=J1
         DO J2=J1+1,N
            IF (A(L).GT.A(J2)) L=J2
         ENDDO
         TEMP=A(L)
         A(L)=A(J1)
         A(J1)=TEMP
         NTEMP=NA(L)
         NA(L)=NA(J1)
         NA(J1)=NTEMP
      ENDDO
      RETURN
      END
