!   OPTIM: A PROGRAM FOR OPTIMIZING GEOMETRIES AND CALCULATING REACTION PATHWAYS
!   COPYRIGHT (C) 1999-2006 DAVID J. WALES
!   THIS FILE IS PART OF OPTIM.
!   
!   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!   (AT YOUR OPTION) ANY LATER VERSION.
!   
!   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!   
!   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!

! SAT&TVB  MON APR 18 21:08:26 BST 2005
MODULE BINARYIO
     IMPLICIT NONE
     CONTAINS

     SUBROUTINE READINPFILE(Q) 
          USE KEY,ONLY: FILTH2
          USE COMMONS,ONLY: NATOMS
          USE PORFUNCS
          IMPLICIT NONE
          DOUBLE PRECISION,DIMENSION(:),INTENT(INOUT)::Q

          INTEGER :: I,J
          CHARACTER(LEN=256) :: FILENAME

          ! GENERATE FILENAME
          IF (FILTH2==0) THEN
               FILENAME='POINTS1.INP'
          ELSE
               WRITE(FILENAME,*) FILTH2
               FILENAME='POINTS1.INP.'//TRIM(ADJUSTL(FILENAME))
          ENDIF

          ! READ IN THE COORDINATES
          INQUIRE(IOLENGTH=I) (Q(J),J=1,3*NATOMS)
          OPEN(113,FILE=TRIM(FILENAME),ACCESS='DIRECT',FORM='UNFORMATTED',STATUS='OLD',RECL=I)
          READ(113,REC=1) (Q(J),J=1,3*NATOMS)
          CLOSE(113)

          ! CHECK THE COORDINATES LOOK SENSIBLE
          IF (MAXVAL(Q)==0.0D0) THEN
              PRINT *, 'ZERO COORDINATES - STOP'
              STOP
          ENDIF
     END SUBROUTINE READINPFILE

     SUBROUTINE WRITEOUTFILE(Q,FILENAME) 
          USE COMMONS,ONLY: NATOMS
          IMPLICIT NONE
          DOUBLE PRECISION,DIMENSION(:),INTENT(INOUT)::Q
          CHARACTER(LEN=*),INTENT(IN) :: FILENAME

          INTEGER :: I,J

          ! WRITE OUT THE COORDINATES
          INQUIRE(IOLENGTH=I) (Q(J),J=1,3*NATOMS)
          OPEN(113,FILE=FILENAME,ACCESS='DIRECT',FORM='UNFORMATTED',STATUS='UNKNOWN',RECL=I)
          WRITE(113,REC=1) (Q(J),J=1,3*NATOMS)
          CLOSE(113)
     END SUBROUTINE WRITEOUTFILE
END MODULE BINARYIO
