!   OPTIM: A PROGRAM FOR OPTIMIZING GEOMETRIES AND CALCULATING REACTION PATHWAYS
!   COPYRIGHT (C) 1999-2006 DAVID J. WALES
!   THIS FILE IS PART OF OPTIM.
!   
!   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!   (AT YOUR OPTION) ANY LATER VERSION.
!   
!   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!   
!   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!
!  BISECT FINDS A LOCAL MINIMA BETWEEN TWO STARTING POINTS IN A SYSTEMATIC WAY.
!
SUBROUTINE BISECT_OPT(NATOMS,ESTART,CSTART,EFINISH,CFINISH,DENDPT)
USE KEY,ONLY : BISECTSTEPS, DEBUG, MUPDATE, BULKT, TWOD, RIGIDBODY, AMBER, BISECTMINDIST, BISECTMAXATTEMPTS, DUMPDATAT, &
  &            BFGSSTEPS, BISECTDEBUG, BISECTMAXENERGY, GEOMDIFFTOL, EDIFFTOL, PERMDIST, GMAX, BHSFRAC, AMBERT, NABT, &
  &            REOPTIMISEENDPOINTS
USE MODCHARMM,ONLY : CHRMMT, ICINTERPT, CHECKOMEGAT,CHECKCHIRALT,INTMINT,NOCISTRANS
USE MODAMBER9, ONLY : NOCISTRANSRNA, GOODSTRUCTURE1
USE PORFUNCS
USE COMMONS,ONLY: PARAM1,PARAM2,PARAM3,ZSYM
! USE MODEFOL
IMPLICIT NONE
INTEGER ITDONE, NATOMS, J1, J2, ISTAT, K, NSTEPS, NBISECT, MAXBISECT, NCOUNT, NMIN, NDO
DOUBLE PRECISION CSTART(3*NATOMS), CFINISH(3*NATOMS)
DOUBLE PRECISION COORDS(3*NATOMS), VNEW(3*NATOMS), DSTART, DFINISH, RMAT(3,3), &
  &              EREAL, RMS2, EBEST, EPREV, RMS, ENERGY, DELTAX(3*NATOMS), &
  &              TEMPSTART(3*NATOMS), TEMPFINISH(3*NATOMS), CTEMP(3*NATOMS)
DOUBLE PRECISION SFRAC, DSTARTSAVE, DFINISHSAVE, ESTART, EFINISH, SLIMIT, FLIMIT, MAXDIST
DOUBLE PRECISION DIST, DIST2, GMAXSAVE, DENDPT
LOGICAL MFLAG, ATEST, PTEST, HITS, HITF, CHIRALFAIL, AMIDEFAIL
INTEGER :: MAXMIN=10
DOUBLE PRECISION, ALLOCATABLE :: EMIN(:), MINCOORDS(:,:), DISTANCES(:)
LOGICAL, ALLOCATABLE :: TRIED(:)
LOGICAL KNOWE, KNOWG, KNOWH
COMMON /KNOWN/ KNOWE, KNOWG, KNOWH
DOUBLE PRECISION, ALLOCATABLE :: VDP(:), VDIST(:,:)
LOGICAL, ALLOCATABLE :: VLOG(:)
DOUBLE PRECISION BISECTENERGY
COMMON /BISECTE/ BISECTENERGY
CHARACTER(LEN=80) FNAMEF
CHARACTER(LEN=20) EFNAME

IF (CHRMMT.AND.INTMINT) THEN
   PRINT '(A)',' BISECT> CHARMM INTERNAL COODINATE MINIMISATION NOT ALLOWED WITH BISECT'
   STOP
ENDIF
IF (.NOT.ALLOCATED(EMIN)) ALLOCATE(EMIN(MAXMIN))
IF (.NOT.ALLOCATED(MINCOORDS)) ALLOCATE(MINCOORDS(3*NATOMS,MAXMIN))
IF (.NOT.ALLOCATED(DISTANCES)) ALLOCATE(DISTANCES(MAXMIN))
IF (.NOT.ALLOCATED(TRIED)) ALLOCATE(TRIED(MAXMIN))
EMIN(1)=ESTART; EMIN(2)=EFINISH
MINCOORDS(1:3*NATOMS,1)=CSTART(1:3*NATOMS)
MINCOORDS(1:3*NATOMS,2)=CFINISH(1:3*NATOMS)
NMIN=2
DISTANCES(1)=DENDPT
TRIED(1:MAXMIN)=.FALSE.
!
! MOVE THROUGH LIST OF MINIMA TO FIND THE LARGEST DISTANCE FOR WHICH WE HAVE NOT YET
! TRIED TO QUENCH TO AN INTERVENING MINIMUM. STOP IF THIS GAP IS LARGER THAN BISECTMINDIST
! MUST DISTINGUISH JUMPS THAT SIMPLY CHANGE SFRAC AND WHERE WE WANT TO TRY A NEW PAIR OF
! MINIMA.
!
NSTEPS=0

11 CONTINUE ! JUMP HERE TO TRY NEW ENDPOINTS
IF (BISECTDEBUG) THEN
   PRINT '(A,I8,A)',' BISECT> AFTER ',NSTEPS,' STEPS '
   PRINT '(A)','   MINIMUM       ENERGY       DISTANCE TO NEXT MIN       TRIED'
   DO J1=1,NMIN-1
      PRINT '(I8,F20.10,F20.10,7X,L5)',J1,EMIN(J1),DISTANCES(J1),TRIED(J1)
   ENDDO
   PRINT '(I8,F20.10)',NMIN,EMIN(NMIN)
ENDIF
NSTEPS=NSTEPS+1
SLIMIT=1.0D0
FLIMIT=0.0D0
IF (NSTEPS.GT.BISECTSTEPS) GOTO 13
NCOUNT=1
NBISECT=0
SFRAC=0.5D0
NDO=-1
MAXDIST=-10.0D0
DO J1=1,NMIN-1
   IF (TRIED(J1)) CYCLE
   IF (DISTANCES(J1).LT.BISECTMINDIST) CYCLE
   IF (DISTANCES(J1).GT.MAXDIST) THEN
      MAXDIST=DISTANCES(J1)
      NDO=J1
   ENDIF
ENDDO
IF (NDO.EQ.-1) THEN
   PRINT '(A)',' BISECT> NO ELIGIBLE GAPS LEFT IN BISECT'
   STOP !!! NEED TO DUMP MINIMA FIRST !!! DJW
ENDIF
12 CONTINUE ! JUMP HERE FOR SAME ENDPOINTS, DIFFERENT SFRAC
NBISECT=NBISECT+1
PRINT '(A,I8,A,I8,A,F15.5,2(A,I8))',' BISECT> TRYING MINIMA IN POSITIONS ',NDO,' AND ',NDO+1,' FRACTION=',SFRAC,' STEP ', &
  &                        NSTEPS,' ATTEMPT ',NBISECT
HITS=.FALSE.
HITF=.FALSE.
TEMPSTART(1:3*NATOMS)=MINCOORDS(1:3*NATOMS,NDO)
TEMPFINISH(1:3*NATOMS)=MINCOORDS(1:3*NATOMS,NDO+1)
IF (BULKT) THEN
   DO K=1,NATOMS
      DELTAX(3*(K-1)+1)=MINCOORDS(3*(K-1)+1,NDO+1) - MINCOORDS(3*(K-1)+1,NDO) &
  &       -PARAM1*NINT((MINCOORDS(3*(K-1)+1,NDO+1) - MINCOORDS(3*(K-1)+1,NDO))/PARAM1)
      DELTAX(3*(K-1)+2)=MINCOORDS(3*(K-1)+2,NDO+1) - MINCOORDS(3*(K-1)+2,NDO) &
  &       -PARAM2*NINT((MINCOORDS(3*(K-1)+2,NDO+1) - MINCOORDS(3*(K-1)+2,NDO))/PARAM2)
      DELTAX(3*(K-1)+3)=MINCOORDS(3*(K-1)+3,NDO+1) - MINCOORDS(3*(K-1)+3,NDO) &
  &       -PARAM3*NINT((MINCOORDS(3*(K-1)+3,NDO+1) - MINCOORDS(3*(K-1)+3,NDO))/PARAM3)
   ENDDO
   COORDS(1:3*NATOMS)=SFRAC*MINCOORDS(1:3*NATOMS,NDO)+(1.0D0-SFRAC)*DELTAX(1:3*NATOMS)
ELSE
   COORDS(1:3*NATOMS)=SFRAC*CSTART(1:3*NATOMS)+(1.0D0-SFRAC)*CFINISH(1:3*NATOMS)
   IF(CHRMMT.AND.ICINTERPT) CALL ICINTERPOL(COORDS,TEMPSTART,TEMPFINISH,SFRAC)
ENDIF
!
! MINIMSATION
!
KNOWE=.FALSE.
PTEST=DEBUG
CALL MYLBFGS(3*NATOMS,MUPDATE,COORDS,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,.TRUE.,ITDONE,PTEST,VNEW,.TRUE.,.FALSE.)
!
! ACTION FOR AMIDEFAIL OR CHIRALFAIL IN INTERPOLATED MINIMUM.
!
IF (CHRMMT) THEN
   AMIDEFAIL=.FALSE.
   IF (CHECKOMEGAT) THEN
      CALL CHECKOMEGA(COORDS,AMIDEFAIL)
      IF(BISECTDEBUG) PRINT '(A,L5)',' BISECT> INTERPOLATED GEOMETRY: AMIDEFAIL  = ',AMIDEFAIL
   ENDIF
   CHIRALFAIL=.FALSE.
   IF (CHECKCHIRALT) THEN
      CALL CHECKCHIRAL(COORDS,CHIRALFAIL)
      IF(BISECTDEBUG) PRINT '(A,L5)',' BISECT> INTERPOLATED GEOMETRY: CHIRALFAIL = ',CHIRALFAIL
   ENDIF
   IF (CHIRALFAIL.OR.AMIDEFAIL) THEN
      SFRAC=0.5D0+(-1.D0)**NBISECT*NCOUNT*0.1D0
      IF ((SFRAC.LE.0).OR.(SFRAC.GE.1.D0)) THEN
         PRINT *,' BISECT> BISECTION ATTEMPT FAILED FOR THIS PAIR OF MINIMA'
         GOTO 11
      ENDIF
      IF(MOD(NBISECT,2).EQ.0) NCOUNT=NCOUNT+1
      PRINT '(A,F8.3)',' BISECT> RETRY INTERPOLATION, SFRAC= ',SFRAC
      GOTO 12
   ENDIF
ENDIF
IF (.NOT.MFLAG) THEN
   SFRAC=0.5D0+(-1.D0)**NBISECT*NCOUNT*0.1D0
   IF ((SFRAC.LE.0).OR.(SFRAC.GE.1.D0)) THEN
      PRINT *,' BISECT> BISECTION ATTEMPT FAILED FOR THIS PAIR OF MINIMA'
      GOTO 11
   ENDIF
   IF(MOD(NBISECT,2).EQ.0) NCOUNT=NCOUNT+1
   PRINT '(A,F8.3)',' BISECT> RETRY INTERPOLATION, SFRAC= ',SFRAC
   GOTO 12
ENDIF
IF ((.NOT.MFLAG).OR.(EREAL.GT.BISECTMAXENERGY)) THEN
   TRIED(NDO)=.TRUE.
   GOTO 11
ENDIF

CALL MINPERMDIST(COORDS,TEMPSTART,NATOMS,DEBUG,PARAM1,PARAM2,PARAM3,BULKT,TWOD,DIST,DIST2,RIGIDBODY,RMAT)
DSTART=DIST
CALL MINPERMDIST(COORDS,TEMPFINISH,NATOMS,DEBUG,PARAM1,PARAM2,PARAM3,BULKT,TWOD,DIST,DIST2,RIGIDBODY,RMAT)
DFINISH=DIST
! PRINT '(A,4G18.8,I8)','EREAL,DS,DF,SFRAC,ITDONE=',EREAL,DSTART,DFINISH,SFRAC,ITDONE
IF (.NOT.MFLAG) THEN
   PRINT '(A,G20.10,A,I8)',' BISECT> WARNING - INITIAL QUENCH FAILED TO CONVERGE, ENERGY=',EREAL, &
  &  ' LBFGS STEPS=',ITDONE
   PRINT '(A,2G15.5)',' BISECT> DISTANCES FROM BRACKETING MINIMA: ',DSTART,DFINISH
ENDIF
IF (BISECTDEBUG) PRINT '(A,G20.10,A,I8)',' BISECT> QUENCH ENERGY=',EREAL,' LBFGS STEPS=',ITDONE
IF (BISECTDEBUG) PRINT '(A,2G15.5)',' BISECT> DISTANCES FROM BRACKETING MINIMA: ',DSTART,DFINISH

IF ((DSTART.LT.GEOMDIFFTOL).AND.(ABS(EREAL-EMIN(NDO)).LT.EDIFFTOL)) THEN
   IF (NBISECT.EQ.BISECTMAXATTEMPTS) THEN
      IF (BISECTDEBUG) PRINT '(A)',' BISECT> BISECTION LIMIT REACHED - ABANDON INTERPOLATION FOR THIS PAIR'
      CALL FLUSH(6,ISTAT)
      TRIED(NDO)=.TRUE.
      GOTO 11
   ENDIF
   IF (HITF) THEN
      IF (BISECTDEBUG) PRINT '(A)',' BISECT> BOTH END POINTS HIT - ABANDON INTERPOLATION FOR THIS PAIR'
      CALL FLUSH(6,ISTAT)
      TRIED(NDO)=.TRUE.
      GOTO 11
   ENDIF
   SLIMIT=MIN(SFRAC,SLIMIT)
   SFRAC=(SFRAC+FLIMIT)/2.0D0
   IF (BISECTDEBUG) PRINT '(A,G20.10)',' BISECT> INITIAL GUESS MINIMISED TO FIRST END POINT - CHANGE FRACTION TO ',SFRAC
   HITS=.TRUE.
   GOTO 12
ENDIF
IF ((DFINISH.LT.GEOMDIFFTOL).AND.(ABS(EREAL-EMIN(NDO+1)).LT.EDIFFTOL)) THEN
   IF (NBISECT.EQ.BISECTMAXATTEMPTS) THEN
      IF (BISECTDEBUG) PRINT '(A)',' BISECT> BISECTION LIMIT REACHED - ABANDON INTERPOLATION FOR THIS PAIR'
      CALL FLUSH(6,ISTAT)
      TRIED(NDO)=.TRUE.
      GOTO 11
   ENDIF
   IF (HITS) THEN
      IF (BISECTDEBUG) PRINT '(A)',' BISECT> BOTH END POINTS HIT - ABANDON INTERPOLATION FOR THIS PAIR'
      CALL FLUSH(6,ISTAT)
      TRIED(NDO)=.TRUE.
      GOTO 11
   ENDIF
   FLIMIT=MAX(SFRAC,FLIMIT)
   SFRAC=(SFRAC+SLIMIT)/2.0D0
   IF (BISECTDEBUG) PRINT '(A,G20.10)',' BISECT> INITIAL GUESS MINIMISED TO SECOND END POINT - CHANGE FRACTION TO ',SFRAC
   HITF=.TRUE.
   GOTO 12
ENDIF
!
! NOW CHECK THAT THE MINIMUM ISN;T IDENTICAL TO ANY OF THE OTHERS. DON'T ADD IT TO THE LIST IF SO.
!
DO J1=1,NMIN
   IF (ABS(EREAL-EMIN(J1)).GT.EDIFFTOL) CYCLE
   CTEMP(1:3*NATOMS)=MINCOORDS(1:3*NATOMS,J1)
   CALL MINPERMDIST(COORDS,CTEMP,NATOMS,DEBUG,PARAM1,PARAM2,PARAM3,BULKT,TWOD,DIST,DIST2,RIGIDBODY,RMAT)
   IF (DIST.LT.GEOMDIFFTOL) THEN
      PRINT '(A,I8,A)',' BISECT> QUENCH MINIMUM IS THE SAME AS NUMBER ',J1,' NOT ADDING IT TO THE LIST'
      TRIED(NDO)=.TRUE.
      GOTO 11
   ENDIF
ENDDO

!
! IF WE HAVE REACHED THIS POINT THEN WE NEED TO ADD THE NEW MINIMUM TO THE LIST AND 
! THEN GO BACK TO THE BEGINNING. MUST SET THE TRIED VALUES APPROPRIATELY. CONNECTIONS TO 
! THE NEW MINIMUM WILL BE UNTRIED.
!
NMIN=NMIN+1
IF (NMIN.GT.MAXMIN) THEN

   ALLOCATE(VDP(MAXMIN),VLOG(MAXMIN),VDIST(3*NATOMS,MAXMIN))

   VDP(1:MAXMIN)=EMIN(1:MAXMIN)
   DEALLOCATE(EMIN)
   ALLOCATE(EMIN(2*MAXMIN))
   EMIN(1:MAXMIN)=VDP(1:MAXMIN)

   VDP(1:MAXMIN)=DISTANCES(1:MAXMIN)
   DEALLOCATE(DISTANCES)
   ALLOCATE(DISTANCES(2*MAXMIN))
   DISTANCES(1:MAXMIN)=VDP(1:MAXMIN)

   VDIST(1:3*NATOMS,1:MAXMIN)=MINCOORDS(1:3*NATOMS,1:MAXMIN)
   DEALLOCATE(MINCOORDS)
   ALLOCATE(MINCOORDS(3*NATOMS,2*MAXMIN))
   MINCOORDS(1:3*NATOMS,1:MAXMIN)=VDIST(1:3*NATOMS,1:MAXMIN)

   VLOG(1:MAXMIN)=TRIED(1:MAXMIN)
   DEALLOCATE(TRIED)
   ALLOCATE(TRIED(2*MAXMIN))
   TRIED(1:MAXMIN)=VLOG(1:MAXMIN)

   MAXMIN=2*MAXMIN
   DEALLOCATE(VDP,VLOG,VDIST)
ENDIF
!
!  MOVE EXISTING ENTRIES DOWN AFTER NDO.
!
DO J1=NMIN,NDO+2,-1
   EMIN(J1)=EMIN(J1-1)
   DISTANCES(J1)=DISTANCES(J1-1)
   TRIED(J1)=TRIED(J1-1)
   MINCOORDS(1:3*NATOMS,J1)=MINCOORDS(1:3*NATOMS,J1-1)
ENDDO
EMIN(NDO+1)=EREAL
DISTANCES(NDO)=DSTART
DISTANCES(NDO+1)=DFINISH
TRIED(NDO)=.FALSE.
TRIED(NDO+1)=.FALSE.
MINCOORDS(1:3*NATOMS,NDO+1)=COORDS(1:3*NATOMS)

GOTO 11

13 CONTINUE

IF (DUMPDATAT) THEN 
   FNAMEF='POINTS.FINAL.BH'
   EFNAME='  '
   DO J1=2,NMIN-1 ! DON'T INCLUDE THE END POINT MINIMA
      REOPTIMISEENDPOINTS=.FALSE.
      BISECTENERGY=EMIN(J1)
      CTEMP(1:3*NATOMS)=MINCOORDS(1:3*NATOMS,J1)
      CALL GEOPT(FNAMEF,EFNAME,CTEMP) ! FILE NAMES ARE DUMMIES HERE
      CALL FLUSH(881,ISTAT)    ! FLUSH MIN.DATA.INFO UNIT AGAIN
   ENDDO
ENDIF

STOP

CALL FLUSH(6,ISTAT)

END SUBROUTINE BISECT_OPT
