!   OPTIM: A PROGRAM FOR OPTIMIZING GEOMETRIES AND CALCULATING REACTION PATHWAYS
!   COPYRIGHT (C) 1999-2006 DAVID J. WALES
!   THIS FILE IS PART OF OPTIM.
!
!   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!   (AT YOUR OPTION) ANY LATER VERSION.
!
!   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!
!   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!
SUBROUTINE BULKMINDIST(DUMMYB,DUMMYA,NATOMS,DISTANCE,TWOD,DEBUG,BOXLX,BOXLY,BOXLZ,PITEST,RESETA)
USE KEY,ONLY : NPERMGROUP, NPERMSIZE, PERMGROUP, GEOMDIFFTOL

IMPLICIT NONE
INTEGER J1, NATOMS, NPMIN, NGMIN, J2, PERM(NATOMS), PBEST(NATOMS), NDUMMY, NMATCHED, PATOMS, J3, J4, NMBEST, ND1
DOUBLE PRECISION DUMMYB(3*NATOMS),DUMMYA(3*NATOMS),DISTANCE,BOXLX,BOXLY,BOXLZ,XSHIFT,YSHIFT,ZSHIFT,XTEMP(3*NATOMS)
DOUBLE PRECISION XBEST(3*NATOMS), DMIN, DTOTAL, DIST, GDSQ
LOGICAL TWOD,DEBUG,PITEST,SAMEMIN,RESETA
COMMON /BULKSHIFT/ XSHIFT,YSHIFT,ZSHIFT
!
! FIND SMALLEST GROUP OF PERMUTABLE ATOMS.
! TRANSLATE FIRST ATOM OF GROUP TO ALL POSITIONS AND THEN FIND NEAREST ATOM WITHIN
! THE SAME GROUP FOR EVERY OTHER ATOM.
! KEEP THE BEST TRANSLATION/PERMUTATION, WHICH CORRESPONDS TO THE SMALLEST
! MINIMUM IMAGE DISTANCE.
!
DISTANCE=1.0D100
PITEST=.FALSE.
SAMEMIN=.TRUE.
GDSQ=GEOMDIFFTOL**2
NPMIN=HUGE(1)
! PRINT *,'DUMMYA IN BULKMINDIST:'
! PRINT '(3G20.10)',DUMMYA(1:3*NATOMS)
! PRINT *,'DUMMYB IN BULKMINDIST:'
! PRINT '(3G20.10)',DUMMYB(1:3*NATOMS)
DO J1=1,NPERMGROUP
   IF (NPERMSIZE(J1).LT.NPMIN) THEN
      NPMIN=NPERMSIZE(J1)
      NGMIN=J1
   ENDIF
ENDDO
ND1=0
DO J1=1,NGMIN-1
   ND1=ND1+NPERMSIZE(J1)
ENDDO
IF (DEBUG) PRINT '(3(A,I6))',' BULKMINDIST> SMALLEST GROUP OF PERMUTABLE ATOMS IS NUMBER ',NGMIN,' WITH ',NPMIN,' MEMBERS'
OUTER: DO J1=ND1+1,ND1+NPMIN
   J2=PERMGROUP(J1)
   XSHIFT=DUMMYA(3*(J2-1)+1)-DUMMYB(3*(ND1)+1)-BOXLX*NINT((DUMMYA(3*(J2-1)+1)-DUMMYB(3*(ND1)+1))/BOXLX)
   YSHIFT=DUMMYA(3*(J2-1)+2)-DUMMYB(3*(ND1)+2)-BOXLY*NINT((DUMMYA(3*(J2-1)+2)-DUMMYB(3*(ND1)+2))/BOXLY)
   IF (.NOT.TWOD) ZSHIFT=DUMMYA(3*(J2-1)+3)-DUMMYB(3*(ND1)+3)-BOXLZ*NINT((DUMMYA(3*(J2-1)+3)-DUMMYB(3*(ND1)+3))/BOXLZ)
   DO J2=1,NATOMS
      XTEMP(3*(J2-1)+1)=DUMMYA(3*(J2-1)+1)-XSHIFT
      XTEMP(3*(J2-1)+2)=DUMMYA(3*(J2-1)+2)-YSHIFT
      IF (.NOT.TWOD) XTEMP(3*(J2-1)+3)=DUMMYA(3*(J2-1)+3)-ZSHIFT
   ENDDO
   NDUMMY=1
   PERM(1:NATOMS)=-1
   NMATCHED=0
   DTOTAL=0.0D0
   DO J2=1,NPERMGROUP
      PATOMS=NPERMSIZE(J2)
      LOOP1: DO J3=1,PATOMS    ! FOR EACH ATOM IN FIXED STRUCTURE B IN GROUP J2
         DMIN=1.0D100
         DO J4=1,PATOMS ! WHICH IS THE CLOSEST ATOM IN THE SAME GROUP FOR THE STRUCTURE IN XTEMP (SHIFTED A)?
            DIST=(XTEMP(3*(PERMGROUP(NDUMMY+J4-1)-1)+1)-DUMMYB(3*(PERMGROUP(NDUMMY+J3-1)-1)+1) &
 &  - BOXLX*NINT((XTEMP(3*(PERMGROUP(NDUMMY+J4-1)-1)+1)-DUMMYB(3*(PERMGROUP(NDUMMY+J3-1)-1)+1))/BOXLX))**2 &
            &  + (XTEMP(3*(PERMGROUP(NDUMMY+J4-1)-1)+2)-DUMMYB(3*(PERMGROUP(NDUMMY+J3-1)-1)+2) &
 &  - BOXLY*NINT((XTEMP(3*(PERMGROUP(NDUMMY+J4-1)-1)+2)-DUMMYB(3*(PERMGROUP(NDUMMY+J3-1)-1)+2))/BOXLY))**2 
            IF (.NOT.TWOD) DIST=DIST+(XTEMP(3*(PERMGROUP(NDUMMY+J4-1)-1)+3)-DUMMYB(3*(PERMGROUP(NDUMMY+J3-1)-1)+3) &
 &  - BOXLZ*NINT((XTEMP(3*(PERMGROUP(NDUMMY+J4-1)-1)+3)-DUMMYB(3*(PERMGROUP(NDUMMY+J3-1)-1)+3))/BOXLZ))**2
            IF (DIST.LT.DMIN) THEN
               DMIN=DIST
               PERM(PERMGROUP(NDUMMY+J3-1))=PERMGROUP(NDUMMY+J4-1)
               IF (DIST.LT.GDSQ) THEN
!                 PRINT '(A,I6,A,I6,A,G20.10)',' MATCH FOUND BETWEEN ATOM ',PERMGROUP(NDUMMY+J3-1), &
! &                                            ' AND ',PERMGROUP(NDUMMY+J4-1),' DIST=',DIST
                  NMATCHED=NMATCHED+1
                  DTOTAL=DTOTAL+DMIN
                  IF (PERM(PERMGROUP(NDUMMY+J3-1)).NE.PERMGROUP(NDUMMY+J3-1)) SAMEMIN=.FALSE.
                  CYCLE LOOP1
               ENDIF
            ENDIF
         ENDDO
         DTOTAL=DTOTAL+DMIN
!        PRINT '(A,I6,A,G20.10,A,I6)',' MATCH FAILED FOR ATOM ',PERMGROUP(NDUMMY+J3-1),' DMIN=',DMIN,' J1=',J1
         CYCLE OUTER ! IF WE REACHED HERE THEN WE DON'T HAVE A PERMUTATIONAL ISOMER BECAUSE
                     ! THE ATOM SPECIFIED IN THE J3 LOOP DOES NOT HAVE A PARTNER.
      ENDDO LOOP1
      NDUMMY=NDUMMY+NPERMSIZE(J2)
   ENDDO
   IF (SAMEMIN) THEN
      IF (DEBUG) PRINT '(A,G20.10)',' BULKMINDIST> IDENTICAL ISOMERS IDENTIFIED, DISTANCE=',SQRT(DTOTAL)
   ELSE
      IF (DEBUG) PRINT '(A,G20.10)',' BULKMINDIST> PERMUTATIONAL ISOMERS IDENTIFIED, DISTANCE=',SQRT(DTOTAL)
   ENDIF
   PITEST=.TRUE.
   DISTANCE=DTOTAL
   IF (RESETA) THEN
      DO J2=1,NATOMS
         DUMMYA(3*(J2-1)+1)=XTEMP(3*(PERM(J2)-1)+1)-BOXLX*NINT(XTEMP(3*(PERM(J2)-1)+1)/BOXLX)
         DUMMYA(3*(J2-1)+2)=XTEMP(3*(PERM(J2)-1)+2)-BOXLY*NINT(XTEMP(3*(PERM(J2)-1)+2)/BOXLY)
         IF (.NOT.TWOD) DUMMYA(3*(J2-1)+3)=XTEMP(3*(PERM(J2)-1)+3)-BOXLZ*NINT(XTEMP(3*(PERM(J2)-1)+3)/BOXLZ)
      ENDDO
   ENDIF

   RETURN
ENDDO OUTER

IF (DEBUG) PRINT '(A)',' BULKMINDIST> STRUCTURES ARE NOT PERMUTATIONAL ISOMERS'

RETURN

END SUBROUTINE BULKMINDIST
