C   OPTIM: A PROGRAM FOR OPTIMIZING GEOMETRIES AND CALCULATING REACTION PATHWAYS
C   COPYRIGHT (C) 1999-2006 DAVID J. WALES
C   THIS FILE IS PART OF OPTIM.
C
C   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C   (AT YOUR OPTION) ANY LATER VERSION.
C
C   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
C   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
C   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
C   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
C
      SUBROUTINE CLATMIN(COORDS,V)
      USE COMMONS
      IMPLICIT NONE
      INTEGER NELEMENTS, NTYPE(105), NCOUNT
      DOUBLE PRECISION F1,F2,F3,GRAD,SECOND, V(3*NATOMS),
     1                 AMAT(3,3), AINV(3,3), COORDS(3*NATOMS), DIF, TEMP1, RMS
      COMMON /CAS/ AMAT, AINV, NELEMENTS, NTYPE
C
C  VALUE OF DIF IS THE ORDER OF MAGNITUDE TO WHICH THE LATTICE CONSTANT CAN BE OPTIMISED. 
C
      DIF=1.0D-3
      NCOUNT=1

10    TEMP1=AMAT(1,1)
      CALL POTENTIAL(COORDS,F3,V,.FALSE.,.FALSE.,RMS,.FALSE.,.FALSE.)

      AMAT(1,1)=AMAT(1,1)+DIF
      AMAT(2,2)=AMAT(2,2)+DIF
      AMAT(3,3)=AMAT(3,3)+DIF

      CALL POTENTIAL(COORDS,F1,V,.FALSE.,.FALSE.,RMS,.FALSE.,.FALSE.)

      AMAT(1,1)=AMAT(1,1)-2*DIF
      AMAT(2,2)=AMAT(2,2)-2*DIF
      AMAT(3,3)=AMAT(3,3)-2*DIF
      CALL POTENTIAL(COORDS,F2,V,.FALSE.,.FALSE.,RMS,.FALSE.,.FALSE.)

      GRAD=(F1-F2)/(2.0D0*DIF)

      SECOND=(F1+F2-2.0D0*F3)/(DIF*DIF)
      PRINT*,'ENERGY FOR LATTICE CYCLE ',NCOUNT,' IS ',F3,' LENGTH=',TEMP1
      PRINT*,'GRADIENT WRT BOX LENGTH=',GRAD
      PRINT*,'SECOND DERIVATIVE WRT BOX LENGTH=',SECOND
      WRITE(*,'(A,3F20.10)') 'F1,F2,F3=',F1,F2,F3
      NCOUNT=NCOUNT+1
      IF (ABS(GRAD/SECOND).GT.5.0D-2) THEN
         AMAT(1,1)=TEMP1-5.0D-2*GRAD/DABS(GRAD)
         AMAT(2,2)=AMAT(1,1)
         AMAT(3,3)=AMAT(1,1)
         PRINT*,'STEP=',-5.0D-2*GRAD/DABS(GRAD)
         GOTO 10
      ELSE
         AMAT(1,1)=TEMP1-GRAD/ABS(SECOND)
         AMAT(2,2)=AMAT(1,1)
         AMAT(3,3)=AMAT(1,1)
         PRINT*,'STEP=',-GRAD/ABS(SECOND)
         IF (DABS(GRAD/SECOND).GT.DIF/10) GOTO 10
      ENDIF
      RETURN
      END
