!   OPTIM: A PROGRAM FOR OPTIMIZING GEOMETRIES AND CALCULATING REACTION PATHWAYS
!   COPYRIGHT (C) 1999-2006 DAVID J. WALES
!   THIS FILE IS PART OF OPTIM.
!   
!   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!   (AT YOUR OPTION) ANY LATER VERSION.
!   
!   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!   
!   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!
MODULE COMMONS
      IMPLICIT NONE

      INTEGER :: NATOMS, ISTATUS, NUNIQUE, NOPT, IPRNT, INR, IVEC, IVEC2, ISTCRT, NMOL, NINTS, NRBSITES
      DOUBLE PRECISION :: ZSTAR, RHO, PARAM1=0.0D0, PARAM2, PARAM3, PARAM4, PARAM5, PARAM6, PARAM7, EVDISTTHRESH, NEWRES_TEMP
      LOGICAL REDOPATH, REDOPATHXYZ, RATIOS, REDOPATHNEB

      INTEGER, ALLOCATABLE, DIMENSION(:) :: NR, IATNUM      !   MXATMS
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: ATMASS !   MXATMS
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: STPMAX ! 3*MXATMS
      CHARACTER(LEN=5), ALLOCATABLE, DIMENSION(:) :: ZSYM   !   MXATMS
      DOUBLE PRECISION, ALLOCATABLE :: TAGFAC(:)
      DOUBLE PRECISION, ALLOCATABLE :: RBSITE(:,:), RBSTLA(:,:), STCHRG(:), DPMU(:)
      INTEGER, ALLOCATABLE :: TAGNUM(:)
      INTEGER NTAG
      LOGICAL TAGT, CHANGE_TEMP

END MODULE COMMONS
