!   OPTIM: A PROGRAM FOR OPTIMIZING GEOMETRIES AND CALCULATING REACTION PATHWAYS
!   COPYRIGHT (C) 1999-2006 DAVID J. WALES
!   THIS FILE IS PART OF OPTIM.
!   
!   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!   (AT YOUR OPTION) ANY LATER VERSION.
!   
!   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!   
!   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!
SUBROUTINE DRVMSEVB(NCOORD, Q, DQ, ENERGY, COMPUTEGRAD, COMPUTEHESS)
	USE COMMONS
	USE MSEVB_COMMON
	USE MSEVB_INTERFACES
        USE MODHESS

	IMPLICIT NONE

!###################################################################

	INTEGER NCOORD
	DOUBLE PRECISION :: Q(NCOORD), DQ(NCOORD)
	DOUBLE PRECISION ENERGY
	LOGICAL COMPUTEGRAD, COMPUTEHESS

        DOUBLE PRECISION :: DELTA_COORD

! DEBUGGING VARIABLES

	INTEGER :: I,J
        DOUBLE PRECISION RMS_DHESS

!	DOUBLE PRECISION RMS_DQ, NUMERICAL_RMS_DQ
!	DOUBLE PRECISION DELTA_Q, UPPER_ENERGY, LOWER_ENERGY, UPPER_DIAG, LOWER_DIAG
!	DOUBLE PRECISION NUMERICAL_DQ(NCOORD)
!	DOUBLE PRECISION DQ_DIAGONAL(3*MXATMS), NUMERICAL_DQ_DIAGONAL(3*MXATMS)

!	DOUBLE PRECISION UPPER_Q_LJ(MXEIG), UPPER_Q_COULOMB(MXEIG)
!	DOUBLE PRECISION UPPER_Q_REP(MXEIG)

!	DOUBLE PRECISION UPPER_Q_H3O_INTRA(MXEIG)
!	DOUBLE PRECISION UPPER_Q_H2O_INTRA(MXEIG)
!	DOUBLE PRECISION UPPER_Q_H3O_H2O(MXEIG)
!	DOUBLE PRECISION UPPER_Q_H2O_H2O(MXEIG)

!	DOUBLE PRECISION LOWER_Q_H3O_INTRA(MXEIG)
!	DOUBLE PRECISION LOWER_Q_H2O_INTRA(MXEIG)
!	DOUBLE PRECISION LOWER_Q_H3O_H2O(MXEIG)
!	DOUBLE PRECISION LOWER_Q_H2O_H2O(MXEIG)

!	DOUBLE PRECISION UPPER_Q_OFF_DIAG(MXEIG,MXEIG)

!	DOUBLE PRECISION NUM_FORCE

!	INTEGER REQUIREDCOORDCOUNT
!	INTEGER REQUIREDCOORD(3*MXATMS)
!	INTEGER NEWCOORD

! CALCULATE THE ENERGY

	CALL MSEVB(NCOORD, Q, .TRUE., ENERGY, .FALSE.)

        IF (PRINTCOEFFICIENTS) THEN
           PRINT *, '#########################'
           PRINT *, 'MSEVB COEFFICIENTS:'
           DO I = 1, REDUCED_NUM_EIG
              PRINT *, I, GRSTWFU(I)
           ENDDO
           PRINT *, '#########################'
        END IF

!	PRINT *, 'ENERGY:', ENERGY

!	PRINT *, 'POINTS:'
!	J = 1
!	DO I = 1, NATOMS

!	   IF (MOD(I,3).EQ.0) THEN
!	      PRINT *, 'O', Q(J), Q(J+1), Q(J+2)
!	   ELSE
!	      PRINT *, 'H', Q(J), Q(J+1), Q(J+2)
!	   ENDIF

!	   J = J + 3
!	ENDDO

! 	PRINT *, 'VB STATES:'

! 	DO I=1,REDUCED_NUM_EIG
! 	   PRINT *, 'STATE:', I

! 	   DO J=1, NATOMS
! 	      PRINT *, J, ATMPL(I,J)
!  	   ENDDO
!  	ENDDO

! 	PRINT *, 'GROUND STATE COEFFICIENTS AND DIAGONAL ENERGIES:'
! 	DO I=1, REDUCED_NUM_EIG
! 	   PRINT *, I, GRSTWFU(I), HAM(I,I)
! 	ENDDO

! 	PRINT *, 'HAMILTONIAN:'

! 	DO I=1,REDUCED_NUM_EIG
! 	   DO J=I, REDUCED_NUM_EIG
! 	      PRINT *, I , J, HAM(I,J)
! 	   ENDDO
! 	ENDDO

!	PRINT *, 'ZUNDEL SPECIES:'

! 	DO I=1, REDUCED_NUM_EIG-1
! 	   DO J=I+1, REDUCED_NUM_EIG

!	      IF (STATESINTERACT(I,J)) THEN
! 		 PRINT *, 'STATE 1:', I, 'STATE 2:', J

!		 DO K=1,7
!		    PRINT *, K, ZUNDEL_SPECIES(I,J,K)
!		 ENDDO
!	      ENDIF
! 	   ENDDO
!  	ENDDO

!	DO I=1,NUM_EIG
!	   PRINT *, '*** VB STATE:', I, '***'
!	   PRINT *, 'H3O INTRA ENERGY:', H3O_INTRA_ENERGY(I)
!	   PRINT *, 'H2O INTRA ENERGY:', H2O_INTRA_ENERGY(I)
!	   PRINT *, 'H3O-H2O INTER ENERGY:', H3O_H2O_ENERGY(I)
!	   PRINT *, 'H2O-H2O INTER ENERGY:', H2O_H2O_ENERGY(I)
!	   PRINT *, ' '
!	ENDDO

!	PRINT *, 'EXCHANGE INTERACTIONS:'
!	DO I=1, NUM_EIG-1
!	   DO J=I+1, NUM_EIG
!	      PRINT *, I, J, HAM(I,J)
!	   ENDDO
!	ENDDO

!	STOP

	IF (COMPUTEGRAD) CALL FMSEVB(NCOORD, Q, DQ, .FALSE.)

        IF (COMPUTEHESS) THEN
           DELTA_COORD = 1.0D-6
           CALL MSEVB_HESS (NCOORD, Q, DELTA_COORD)

!           RMS_DHESS=0.0D0

!           DO I=1, NCOORD-1
!              DO J = I+1, NCOORD
!                 RMS_DHESS = RMS_DHESS + (HESS(I,J)-HESS(J,I))**2
!              ENDDO
!           ENDDO

!           RMS_DHESS = DSQRT(2.0D0*RMS_DHESS/(NCOORD**2 - NCOORD))
           
!           PRINT *, 'RMS DHESS:', RMS_DHESS

!           STOP
        ENDIF

! DEALLOCATE MEMORY

	DEALLOCATE(VIJEXCH, GRSTWFU)

!	ENDIF

!	PRINT *, 'FORCES:'
!	J=1
!	DO I=1,NCOORD,3
!	   PRINT *, J, DQ(I), DQ(I+1), DQ(I+2)
!	   J = J + 1
!	ENDDO

! CALCULATE THE NUMERICAL GRADIENTS

!	DELTA_Q = 1D-7
!	DO I=1, NCOORD

!	   PRINT *, '*** COORDINATE:', I, '***'

!	   Q(I) = Q(I) + DELTA_Q
! 	   CALL MSEVB(NCOORD, Q, .FALSE., UPPER_ENERGY)

!	   DO J=1,REDUCED_NUM_EIG
!	      UPPER_Q_H3O_INTRA(J) = H3O_INTRA_ENERGY(J)
!	      UPPER_Q_H2O_INTRA(J) = H2O_INTRA_ENERGY(J)
!	      UPPER_Q_H3O_H2O(J) = H3O_H2O_ENERGY(J)
!	      UPPER_Q_H2O_H2O(J) = H2O_H2O_ENERGY(J)
!	   ENDDO

!  	   Q(I) = Q(I) - 2*DELTA_Q
! 	   CALL MSEVB(NCOORD, Q, .FALSE., LOWER_ENERGY)
!  	   NUMERICAL_DQ(I) = (UPPER_ENERGY-LOWER_ENERGY)/(2*DELTA_Q)

!	   DO J=1,REDUCED_NUM_EIG
!	      PRINT *, 'VB STATE:', J

!	      NUM_FORCE = (UPPER_Q_H3O_INTRA(J)-H3O_INTRA_ENERGY(J))/(2*DELTA_Q)
!	      PRINT *, 'H3O INTRA FORCES:', H3O_INTRA_FORCES(J,I), NUM_FORCE, (H3O_INTRA_FORCES(J,I)-NUM_FORCE)

!	      NUM_FORCE = (UPPER_Q_H2O_INTRA(J)-H2O_INTRA_ENERGY(J))/(2*DELTA_Q)
!	      PRINT *, 'H2O INTRA FORCES:', H2O_INTRA_FORCES(J,I), NUM_FORCE, (H2O_INTRA_FORCES(J,I)-NUM_FORCE)

!	      NUM_FORCE = (UPPER_Q_H3O_H2O(J)-H3O_H2O_ENERGY(J))/(2*DELTA_Q)
!	      PRINT *, 'H3O-H2O FORCES:', H3O_H2O_FORCES(J,I), NUM_FORCE, (H3O_H2O_FORCES(J,I)-NUM_FORCE)

!	      NUM_FORCE = (UPPER_Q_H2O_H2O(J)-H2O_H2O_ENERGY(J))/(2*DELTA_Q)
!	      PRINT *, 'H2O-H2O FORCES:', H2O_H2O_FORCES(J,I), NUM_FORCE, (H2O_H2O_FORCES(J,I)-NUM_FORCE)

!	   ENDDO

!  	   Q(I) = Q(I) + DELTA_Q
!  	ENDDO

! CALCULATE THE NUMERICAL GRADIENTS

!	DELTA_Q = 1D-7

!	REQUIREDCOORDCOUNT = 6
!	REQUIREDCOORD(1)=52
!	REQUIREDCOORD(2)=53
!	REQUIREDCOORD(3)=54
!	REQUIREDCOORD(4)=61
!	REQUIREDCOORD(5)=62
!	REQUIREDCOORD(6)=63

!	DO I=1, REQUIREDCOORDCOUNT

!	   NEWCOORD = 3*NEW_ORDER(INT((REQUIREDCOORD(I)-1)/3)+1) - 2 + MOD(REQUIREDCOORD(I)-1, 3)

!	   PRINT *, ' '
!	   PRINT *, '*** COORDINATE:', REQUIREDCOORD(I), NEWCOORD, '***'
!	   PRINT *, ' '

!	   PRINT *, '*** CALCULATING UPPER ENERGY BOUND ***'
!	   Q(I) = Q(I) + DELTA_Q
!	   CALL MSEVB_IND(NCOORD, Q, UPPER_ENERGY, WF_BUFFER)

!	   DO J=1, NUM_EIG
!	      UPPER_Q_LJ(J)=LJ_VALUES(J)
!	      UPPER_Q_COULOMB(J)=COULOMB_VALUES(J)
!	      UPPER_Q_REP(J)=REP_VALUES(J)
! 	   UPPER_Q_H3O_INTRA(J)=H3O_INTRA_ENERGY(J)
!	      UPPER_Q_H2O_INTRA(J)=H2O_INTRA_ENERGY(J)
!	      UPPER_Q_H3O_H2O(J)=H3O_H2O_ENERGY(J)
!	      UPPER_Q_H2O_H2O(J)=H2O_H2O_ENERGY(J)
! 	   ENDDO

! 	   DO J=1,NUM_EIG-1
! 	      DO K=J+1, NUM_EIG
! 		 UPPER_Q_OFF_DIAG(J,K)=OFF_DIAG_ENERGIES(J,K)
! 	      ENDDO
! 	   ENDDO

! 	   PRINT *, '*** CALCULATING LOWER ENERGY BOUND ***'
!	   Q(I) = Q(I) - 2*DELTA_Q
!	   CALL MSEVB_IND(NCOORD, Q, LOWER_ENERGY, WF_BUFFER)

!	   NUMERICAL_DQ(I) = (UPPER_ENERGY-LOWER_ENERGY)/(2*DELTA_Q)

!	   Q(I) = Q(I) + DELTA_Q

! 	   PRINT *, 'DIAGONAL COMPONENTS:'

! 	   DO J=1, NUM_EIG
!	      PRINT *, ' '
! 	      PRINT *, 'VB STATE:', J

! 	      NUM_FORCE=(UPPER_Q_H3O_INTRA(J)-H3O_INTRA_ENERGY(J))/(2*DELTA_Q)
! 	      PRINT *, 'H3O+ INTRAMOLECULAR CONTRIBUTION:'
! 	      PRINT *, H3O_INTRA_FORCES(J,I), NUM_FORCE, (H3O_INTRA_FORCES(J,I)-NUM_FORCE)
!	      PRINT *, H3O_INTRA_FORCES(J,NEWCOORD)


! 	      NUM_FORCE=(UPPER_Q_H2O_INTRA(J)-H2O_INTRA_ENERGY(J))/(2*DELTA_Q)
! 	      PRINT *, 'H2O INTRAMOLECULAR CONTRIBUTION:'
! 	      PRINT *, H2O_INTRA_FORCES(J,I), NUM_FORCE, (H2O_INTRA_FORCES(J,I)-NUM_FORCE)
! 	      PRINT *, H2O_INTRA_FORCES(J,NEWCOORD)

! 	      NUM_FORCE=(UPPER_Q_H3O_H2O(J)-H3O_H2O_ENERGY(J))/(2*DELTA_Q)
! 	      PRINT *, 'H3O+-H2O INTERMOLECULAR CONTRIBUTION:'
! 	      PRINT *, H3O_H2O_FORCES(J,I), NUM_FORCE, (H3O_H2O_FORCES(J,I)-NUM_FORCE)
! 	      PRINT *, H3O_H2O_FORCES(J,NEWCOORD)

! 	      NUM_FORCE=(UPPER_Q_H2O_H2O(J)-H2O_H2O_ENERGY(J))/(2*DELTA_Q)
! 	      PRINT *, 'H2O-H2O INTERMOLECULAR CONTRIBUTION:'
! 	      PRINT *, H2O_H2O_FORCES(J,I), NUM_FORCE, (H2O_H2O_FORCES(J,I)-NUM_FORCE)
! 	      PRINT *, H2O_H2O_FORCES(J,NEWCOORD)

! 	      PRINT *, 'H2O-H3O INTERACTION:'
! 	      PRINT *, 'COMPONENT, ANALYTIC, NUMERICAL, DIFFERENCE'

! 	      NUM_FORCE=(UPPER_Q_LJ(J)-LJ_VALUES(J))/(2*DELTA_Q)
! 	      PRINT *, 'LJ FORCE:', LJ_FORCES(J,I), NUM_FORCE, (LJ_FORCES(J,I)-NUM_FORCE)
! 	      PRINT *, 'LJ FORCE:', LJ_FORCES(J,NEWCOORD)

! 	      NUM_FORCE=(UPPER_Q_COULOMB(J)-COULOMB_VALUES(J))/(2*DELTA_Q)
! 	      PRINT *, 'COULOMB FORCE:', COULOMB_FORCES(J,I), 
!     &                 NUM_FORCE, (COULOMB_FORCES(J,I)-NUM_FORCE)
!	      PRINT *, 'COULOMB FORCE:', COULOMB_FORCES(J,NEWCOORD)

! 	      NUM_FORCE=(UPPER_Q_REP(J)-REP_VALUES(J))/(2*DELTA_Q)
! 	      PRINT *, 'REPULSIVE FORCE:', REP_FORCES(J,I), NUM_FORCE, 
!     &                 (REP_FORCES(J,I)-NUM_FORCE) 
! 	      PRINT *, 'REPULSIVE FORCE:', REP_FORCES(J,NEWCOORD)

! 	   ENDDO

! 	   PRINT *, ' '
! 	   PRINT *, 'OFF-DIAGONAL COMPONENTS:'

! 	   DO J=1, NUM_EIG-1
! 	      DO K=J+1,NUM_EIG
! 		 NUM_FORCE=(UPPER_Q_OFF_DIAG(J,K)-OFF_DIAG_ENERGIES(J,K))/(2*DELTA_Q)
! 		 PRINT *, 'VB STATE 1, STATE 2, ANALYTIC FORCE, NUMERIC, DIFFERENCE'
! 		 PRINT *, J, K, OFF_DIAG_FORCES(J,K,I),NUM_FORCE,(OFF_DIAG_FORCES(J,K,I)-NUM_FORCE)
! 		 PRINT *, 'VB STATE 1, STATE 2, ANALYTIC FORCE'
!		 PRINT *, J, K, OFF_DIAG_FORCES(J,K,NEWCOORD)

! 		 PRINT *, 'NUMERICAL ENERGY BOUNDS:'
! 		 PRINT *, 'UPPER:', UPPER_Q_OFF_DIAG(J,K), 'LOWER:',OFF_DIAG_ENERGIES(J,K)
! 	      ENDDO
! 	   ENDDO

! 	   PRINT *, ' '

!	ENDDO   

!  	PRINT *, 'DERIVATIVES: '
!  	PRINT *, 'COORDINATE NUMBER'
!  	PRINT *, 'ANALYTICAL, NUMERICAL, DIFFERENCE'

!   	RMS_DQ = 0.0D0
!   	NUMERICAL_RMS_DQ = 0.0D0

!   	DO I=1,NCOORD
!   	   RMS_DQ = RMS_DQ + (DQ(I)*DQ(I))
!   	   NUMERICAL_RMS_DQ = NUMERICAL_RMS_DQ + (NUMERICAL_DQ(I)*NUMERICAL_DQ(I))
!   	   PRINT *, I, DQ(I), NUMERICAL_DQ(I), (DQ(I)-NUMERICAL_DQ(I))
!   	ENDDO

!   	RMS_DQ = SQRT(RMS_DQ/NCOORD)
!   	NUMERICAL_RMS_DQ = SQRT(NUMERICAL_RMS_DQ/NCOORD)

!   	PRINT *, 'RMS DERIVATIVES: ', RMS_DQ, ' ', NUMERICAL_RMS_DQ, ' ', (RMS_DQ-NUMERICAL_RMS_DQ) 
!   	PRINT *, 'DELTA_Q: ', DELTA_Q

!   	STOP

! END DEBUGGING

	RETURN
	END

! ##################################################################################################
	
! NUMERICAL HESSIAN ROUTINE FOR MSEVB POTENTIAL
! DO NOT CALL THIS DIRECTLY, ONLY VIA DRVMSEVB

SUBROUTINE MSEVB_HESS (NCOORD, COORDS, DELTA_COORD)
  USE MSEVB_INTERFACES
  USE MODHESS, HESSIAN => HESS

  IMPLICIT NONE

! SUBROUTINE ARGUMENTS

  INTEGER, INTENT(IN) :: NCOORD
  DOUBLE PRECISION, INTENT(IN) :: COORDS(NCOORD)
  DOUBLE PRECISION, INTENT(IN) :: DELTA_COORD

! LOCAL VARIABLES

  INTEGER :: CURRENTCOORD, CURRENTCHANGE
  DOUBLE PRECISION :: LOCALCOORDS(NCOORD)
  DOUBLE PRECISION :: PLUSSIDEGRAD(NCOORD), MINUSSIDEGRAD(NCOORD)
  DOUBLE PRECISION :: ENERGY

! TRY TO AVOID PROBLEMS WITH ARITHMETIC BY REFERRING ALWAYS TO THE ORIGINAL COPY OF THE COORDINATES

  LOCALCOORDS = COORDS

  DO CURRENTCOORD = 1, NCOORD

     LOCALCOORDS(CURRENTCOORD) = COORDS(CURRENTCOORD) + DELTA_COORD

! WE DO NOT WANT TO RECOMPUTE THE VB STATES BECAUSE WE ASSUME THAT THEY DON`T CHANGE

     CALL MSEVB(NCOORD, LOCALCOORDS, .FALSE., ENERGY, .FALSE.)
     CALL FMSEVB(NCOORD, LOCALCOORDS, PLUSSIDEGRAD, .FALSE.)

     LOCALCOORDS(CURRENTCOORD) = COORDS(CURRENTCOORD) - DELTA_COORD     

     CALL MSEVB(NCOORD, LOCALCOORDS, .FALSE., ENERGY, .FALSE.)
     CALL FMSEVB(NCOORD, LOCALCOORDS, MINUSSIDEGRAD, .FALSE.)     

     DO CURRENTCHANGE = CURRENTCOORD, NCOORD
        HESSIAN(CURRENTCHANGE,CURRENTCOORD) = &
        (PLUSSIDEGRAD(CURRENTCHANGE)-MINUSSIDEGRAD(CURRENTCHANGE))/(2.0D0*DELTA_COORD)

        IF (CURRENTCHANGE.NE.CURRENTCOORD) THEN
           HESSIAN(CURRENTCOORD,CURRENTCHANGE) = HESSIAN(CURRENTCHANGE,CURRENTCOORD)
        ENDIF
     ENDDO
     
     LOCALCOORDS(CURRENTCOORD) = COORDS(CURRENTCOORD)      
  ENDDO

END SUBROUTINE MSEVB_HESS	

! ##################################################################################################











