C   OPTIM: A PROGRAM FOR OPTIMIZING GEOMETRIES AND CALCULATING REACTION PATHWAYS
C   COPYRIGHT (C) 1999-2006 DAVID J. WALES
C   THIS FILE IS PART OF OPTIM.
C
C   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C   (AT YOUR OPTION) ANY LATER VERSION.
C
C   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
C   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
C   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
C   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
C
C
C*************************************************************************
C
C PAIR POTENTIAL FOR A 2D TRAPPED ION CLUSTER
C                                        
      SUBROUTINE ECTRAP (N, X, POTEL, C1, C2, C3)
      USE KEY
      IMPLICIT NONE 
      INTEGER N, I, J, J1, J2
      DOUBLE PRECISION X(3*N), K, POTEL, R, RO, C1, C2, C3
      PARAMETER (K=20.0D0)

C      C1=0.0D0
C      C2=0.0D0
C      DO 27 J1=1,N
C         C2=C2+X(3*J1-1)
C         C1=C1+X(3*J1-2)
C27    CONTINUE
C      C2=C2/N
C      C1=C1/N

C     DO I=1,N
C        X(3*(J1-1)+1)=X(3*(J1-1)+1)-C1
C        X(3*(J1-1)+2)=X(3*(J1-1)+2)-C2
C     ENDDO
C     C2=0.0D0
C     C1=0.0D0

      POTEL=0.0D0
      DO I=1,N
         J1=3*(I-1)+1
C        RO=(X(J1)-C1)**2 + (X(J1+1)-C2)**2
         RO=X(J1)**2 + X(J1+1)**2
         POTEL=POTEL+0.5D0*K*RO
         DO J=I+1,N
            J2=3*(J-1)+1
            R=(X(J1)-X(J2))**2+(X(J1+1)-X(J2+1))**2
            POTEL=POTEL+CHARGE(J)*CHARGE(I)/DSQRT(R)
         ENDDO
      ENDDO
      RETURN
      END
