C   OPTIM: A PROGRAM FOR OPTIMIZING GEOMETRIES AND CALCULATING REACTION PATHWAYS
C   COPYRIGHT (C) 1999- DAVID J. WALES
C   THIS FILE IS PART OF OPTIM.
C
C   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C   (AT YOUR OPTION) ANY LATER VERSION.
C
C   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
C   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
C   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
C   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
C
C
C*************************************************************************
C
C PAIR POTENTIAL FOR A TRAPPED ION CLUSTER CODED BY ERSIN YURTSEVER
C FOR 0.5*TRAPK * R^NTRAPPOW, WHERE R IS THE DISTANCE FROM THE ORIGIN (FIXED).
C                                        
      SUBROUTINE EYETRAP (N, X, POTEL, C1, C2, C3)
      USE KEY,ONLY : NTRAPPOW, TRAPK
      IMPLICIT NONE 
      INTEGER N, I, J, J1, J2
      INTEGER NTRAPPOW2
      DOUBLE PRECISION X(3*N), POTEL, R, RO, C1, TEMP1, TEMP3, VOMIT, C2, C3
C
C     THIS VERSION HAS THE TRAP POTENTIAL R**NTRAPPOW
C
      C1=0.0D0
      C2=0.0D0
      C3=0.0D0
C
C  WE MUST FIX THE CENTRE OF MASS AT THE ORIGIN, OTHERWISE THE FIRST AND SECOND
C  DERIVATIVES NEED EXTRA TERMS CORRESPONDING TO THE DERIVATIVE OF THE CENTRE OF
C  MASS WITH RESPECT TO CARTESIAN COORDINATES.
C
C      DO 27 J1=1,N
C         C3=C3+X(3*J1)
C         C2=C2+X(3*J1-1)
C         C1=C1+X(3*J1-2)
C 27    CONTINUE
C      C3=C3/N
C      C2=C2/N
C      C1=C1/N
      POTEL=0.0D0
      DO 20 I=1,N
         J1=3*(I-1)+1
         TEMP1=(X(J1)-C1)**2
         VOMIT=(X(J1+1)-C2)**2
         TEMP3=(X(J1+2)-C3)**2
         RO=TEMP1+VOMIT+TEMP3
         POTEL=POTEL+0.5D0*TRAPK*SQRT(RO)**NTRAPPOW

         DO 10 J=I+1,N
            J2=3*(J-1)+1
               R=(X(J1)-X(J2))**2+(X(J1+1)-X(J2+1))**2+(X(J1+2)-X(J2+2))**2
            POTEL=POTEL+1.0D0/DSQRT(R)
10       CONTINUE
20    CONTINUE

      RETURN
      END
C
C*************************************************************************
C
C  SUBROUTINE DTRAP CALCULATES THE CARTESIAN GRADIENT AND SECOND
C  DERIVATIVE MATRIX ANALYTICALLY.
C
C*************************************************************************
C
      SUBROUTINE EYDTRAP(N, X, V, C1, C2, C3, GTEST, STEST)
      USE KEY,ONLY : NTRAPPOW, TRAPK
      USE MODHESS
      IMPLICIT NONE
      INTEGER N, J1, J2, J3, J4, J5, J6
      INTEGER J, I, II, POW2, TERM3, RM4XY, RM2Z, RM2Y, RM4XX, RM4XZ 
      INTEGER RM4ZZ, RM4YZ, RM4YY, RM2X
 
      DOUBLE PRECISION X(3*N), V(3*N),DIST,K
      DOUBLE PRECISION R3(N,N), R5(N,N), CENTRE(3), C1, C2, C3 
      LOGICAL STEST, GTEST

      INTEGER NPOW2
      DOUBLE PRECISION R2,RNM2(N),RNM4(N)
C 
      IF (.NOT.GTEST) RETURN
C
C  ASSUME THE FIXED ORIGIN FOR THE HARMONIC POTENTIAL IS AT THE ORIGIN, NOT THE
C  CENTRE OF MASS, OTHERWISE THE DERIVATIVES MUST INCLUDE TERMS FOR THE VARIATION
C  OF THE CENTRE OF MASS WITH RESPECT TO COORDINATES.
C
C     CENTRE(1)=C1
C     CENTRE(2)=C2
C     CENTRE(3)=C3
C *************************************************
C
C  STORE DISTANCE MATRICES.
C
      DO 10 J1=1,N
         R3(J1,J1)=0.0D0
         R5(J1,J1)=0.0D0
         DO 20 J2=J1+1,N
            DIST=(X(3*(J1-1)+1)-X(3*(J2-1)+1))**2
     1              +(X(3*(J1-1)+2)-X(3*(J2-1)+2))**2
     2              +(X(3*(J1-1)+3)-X(3*(J2-1)+3))**2
            R3(J1,J2)=1.0D0/DIST**(1.5D0)
            R5(J1,J2)=1.0D0/DIST**(2.5D0)
            R3(J2,J1)=R3(J1,J2)
            R5(J2,J1)=R5(J1,J2)
20       CONTINUE
10    CONTINUE
C
C  FIRST CALCULATE THE GRADIENT ANALYTICALLY.
C
      DO J1=1,N
      RNM2(J1)=0.0D0
      RNM4(J1)=0.0D0
      ENDDO

      DO 30 J1=1,N

         R2=X(3*(J1-1)+1)**2+X(3*(J1-1)+2)**2+X(3*(J1-1)+3)**2
         IF(ABS(R2).GT.1.0E-5) THEN
         DIST=SQRT(R2)
         RNM2(J1)=DIST**(NTRAPPOW-2)
         RNM4(J1)=RNM2(J1)/R2
         ELSE
         IF(NTRAPPOW.EQ.2) RNM2(J1)=1.0D0
         ENDIF
         DO 40 J2=1,3
            J3=3*(J1-1)+J2

            V(J3)=0.50*TRAPK*NTRAPPOW*RNM2(J1)*X(J3)

            DO 50 J4=1,N
               V(J3)=V(J3)+(X(3*(J4-1)+J2)-X(J3))*R3(J4,J1)
50          CONTINUE
40       CONTINUE
30    CONTINUE
      IF (.NOT.STEST) RETURN
C
C  NOW DO THE HESSIAN. FIRST ARE THE ENTIRELY DIAGONAL TERMS.
C
      DO 60 J1=1,N

         DO 70 J2=1,3
            J3=3*(J1-1)+J2

            HESS(J3,J3)=0.5*TRAPK*NTRAPPOW*(RNM2(J1)+(NTRAPPOW-2)*X(J3)*X(J3)*RNM4(J1))

            DO 80 J4=1,N
               HESS(J3,J3)=HESS(J3,J3)+3.0D0*(X(J3)-X(3*(J4-1)+J2))**2*R5(J4,J1)-R3(J4,J1)
80          CONTINUE
70       CONTINUE
60    CONTINUE
C
C  NEXT ARE THE TERMS WHERE X_I AND X_J ARE ON THE SAME ATOM
C  BUT ARE DIFFERENT, E.G. Y AND Z.
C
      DO 90 J1=1,N
         DO 100 J2=1,3
            J3=3*(J1-1)+J2
            DO 110 J4=J2+1,3

      HESS(J3,3*(J1-1)+J4)=0.5*TRAPK*NTRAPPOW*(NTRAPPOW-2)*X(J3)*X(3*(J1-1)+J4)*RNM4(J1)

               DO 120 J5=1,N
                  HESS(J3,3*(J1-1)+J4)=HESS(J3,3*(J1-1)+J4)
     1           +(X(J3)-X(3*(J5-1)+J2))*(X(3*(J1-1)+J4)-X(3*(J5-1)+J4))*3.0D0*R5(J5,J1)
120            CONTINUE
               HESS(3*(J1-1)+J4,J3)=HESS(J3,3*(J1-1)+J4)
110         CONTINUE
100      CONTINUE
90    CONTINUE
C
C  CASE III, DIFFERENT ATOMS, SAME CARTESIAN COORDINATE.
C
      DO 130 J1=1,N
         DO 140 J2=1,3
            J3=3*(J1-1)+J2
            DO 150 J4=J1+1,N
            J5=3*(J4-1)+J2

            HESS(J3,3*(J4-1)+J2)=-3.0D0*R5(J4,J1)*(X(J3)-X(3*(J4-1)+J2))**2+R3(J4,J1)

               HESS(3*(J4-1)+J2,J3)=HESS(J3,3*(J4-1)+J2)
150         CONTINUE
140      CONTINUE
130   CONTINUE
C
C  CASE IV: DIFFERENT ATOMS AND DIFFERENT CARTESIAN COORDINATES.
C
      DO 180 J1=1,N
         DO 170 J2=1,3
            J3=3*(J1-1)+J2
            DO 160 J4=J1+1,N
               DO 155 J5=J2+1,3
                  J6=3*(J4-1)+J5


                  HESS(J3,J6)=-R5(J4,J1)*3.0D0
     1                       *(X(J3)-X(3*(J4-1)+J2))
     2                       *(X(3*(J1-1)+J5)-X(J6))
C
C ************************************************************************

                  HESS(J6,J3)=HESS(J3,J6)
                  HESS(3*(J4-1)+J2,3*(J1-1)+J5)=HESS(J3,J6)
                  HESS(3*(J1-1)+J5,3*(J4-1)+J2)=HESS(J3,J6)
155            CONTINUE
160         CONTINUE
170      CONTINUE
180   CONTINUE

      RETURN
      END
