C   OPTIM: A PROGRAMFOR OPTIMIZING GEOMETRIES AND CALCULATING REACTION PATHWAYS
C   COPYRIGHT (C) 1999-2006 DAVID J. WALES
C   THIS FILE IS PART OF OPTIM.
C
C   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C   (AT YOUR OPTION) ANY LATER VERSION.
C
C   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
C   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
C   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
C   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
C
      SUBROUTINE FETCHZ(Q)
      USE COMMONS
      USE KEY
      USE MODTWOEND
      USE SYMINF
      USE MODNEB
      USE MODCHARMM
      USE MODAMBER9, ONLY : KTWNT
      USE MODUNRES
      USE KEYCONNECT
      USE MODGUESS
      USE MODMEC
      USE PORFUNCS
      USE MSEVB_COMMON
      USE BINARYIO
      USE SDWATER, ONLY : SDINIT
      !USE BOWMANWATER, ONLY : BOWMANINIT
      USE AMHGLOBALS

      IMPLICIT NONE
      INTEGER J1, J, NN, MM, NTYPE(105), J2, IDUM1, IDUM2, LNATOMS, NUSE
      LOGICAL YESNO
      DOUBLE PRECISION EPSAB, EPSBB, SIGAB, SIGBB, EPS, CSC, SIG, AMAT(3,3), TEMPX, TEMPY, TEMPZ, AINV(3,3), DETER, Q(3*NATOMS)
      INTEGER NTYPEA, NELEMENTS, NOXYGEN, NCHARGE
      COMMON /BIN/ EPSAB, EPSBB, SIGAB, SIGBB, NTYPEA
      CHARACTER FNAME*80, TSTRING*80, CD1*1, CD2*2
      COMMON /CAS/ AMAT, AINV, NELEMENTS, NTYPE
      LOGICAL CONNECTT, DUMPPATH, READPATH, CALCRATES, STOPFIRST
      INTEGER NCONNECT,I500
      DOUBLE PRECISION TEMPERATURE, HRED
      COMMON /CONN/ STOPFIRST, CONNECTT, NCONNECT, DUMPPATH, READPATH, CALCRATES, TEMPERATURE, HRED
      LOGICAL PATHT, DRAGT
      INTEGER NPATHFRAME, ISTAT
      COMMON // DRAGT, PATHT, NPATHFRAME
C     DOUBLE PRECISION REPELTS(3*NATOMS,100), REPELPUSH
C     INTEGER NREPELTS, REPELFROM
C     LOGICAL REPELTST, REPEL
C     COMMON /OTS/ NREPELTS, REPELTST, REPELPUSH, REPEL, REPELFROM
      LOGICAL CUBIC
      COMMON /CUB/ CUBIC
      DOUBLE PRECISION CAPSRHO, EPS2, RAD, HEIGHT
      COMMON /CAPS/ CAPSRHO, EPS2, RAD, HEIGHT
      CHARACTER(LEN=20) :: STR,STR2,FTEMP,FINSTRING
      CHARACTER(LEN=21) :: WW
      INTEGER ITEM, NITEMS, LOC, LINE, NCR, NERROR, IR, LAST
      LOGICAL END, SKIPBL, CLEAR, ECHO, CAT
      COMMON /BUFINF/ ITEM, NITEMS, LOC(132), LINE, SKIPBL, CLEAR, NCR, NERROR, IR, ECHO, LAST, CAT

C    LOCAL AMH VARIABLES
      INTEGER GLY_COUNT, III
      DOUBLE PRECISION X, Y, Z

C
C  THOMSON PROBLEM:
C
      DOUBLE PRECISION, PARAMETER :: HALFPI=1.570796327D0
      DOUBLE PRECISION THTEMP(3*NATOMS), DIST


      IF (CHRMMT.OR.UNRST.OR.AMBERT.OR.NABT) THEN
         ALLOCATE (IATNUM(NATOMS))   ! ATMASS ALREADY SET UP
      ELSE IF (PYGPERIODICT.OR.PYBINARYT.OR.PYGT) THEN
         ALLOCATE (IATNUM(NATOMS),ATMASS(NATOMS))
         ATMASS(:)=1.0D0
      ELSE
         ALLOCATE (IATNUM(NATOMS),ATMASS(NATOMS))
C        SF344> INITIALISE ATMASS VALUES TO NOT DEFAULT TO ZERO 
C               UNINITIALISED STUFF (MAY CAUSE PROBLEMS IN INERTIA OTHERWISE)
         ATMASS(:)=1.0D0 
      ENDIF

C
C  REMIND USERS IN CASE THEY HAVE NOT CHANGED THE TIGHTER DEFAULT SETTING OF MAXERISE FOR
C  PV, CASTEP, ONETEP AND CP2K RUNS. 
C
      IF (PV.AND.(MAXERISE.LT.1.0D-7)) WRITE(*,'(A,G20.10)') 
     1          ' FETCHZ> WARNING - MAXIMUM PERMITTED ENERGY RISE SEEMS A BIT SMALL: ',MAXERISE
      IF ((CASTEP.OR.ONETEP.OR.CP2K).AND.(MAXERISE.LT.1.0D-7)) WRITE(*,'(A,G20.10)') 
     1          ' FETCHZ> WARNING - MAXIMUM PERMITTED ENERGY RISE SEEMS A BIT SMALL: ',MAXERISE 

      IF (MACHINE) THEN
          IF (FILTH2==0) THEN
               FINSTRING='POINTS2.INP'
          ELSE
               WRITE(FTEMP,*) FILTH
               WRITE(FINSTRING,'(A)') 'POINTS2.INP.' // TRIM(ADJUSTL(FTEMP))
          ENDIF
      ELSE
           IF (FILTH2.EQ.0) THEN
              FINSTRING='FINISH'
           ELSE
              WRITE(FTEMP,*) FILTH
              WRITE(FINSTRING,'(A)') 'FINISH.' // TRIM(ADJUSTL(FTEMP))
           ENDIF
      ENDIF

      IF (HYBRIDMINT) THEN
         PRINT '(3(A,I5),A)',' FETCHZ> HYBRID MINIMISATION, MAXIMUM STEPS=',HMNSTEPS,
     &      ', MAXIMUM TANGENT SPACE STEPS=',HMNBFGSMAX1,' OR ',HMNBFGSMAX2,' AT CONVERGENCE'
         IF (NUSEEV.GT.0) WRITE(*,'(A,I5,A,G20.10)') '         MAXIMUM NUMBER OF EIGENVALUES/EIGENVECTORS TO BE CALCULATED=',NUSEEV,
     &                       ' MAXIMUM STEP SIZE ALONG AN EIGENVECTOR=',HMMXSTP
         IF (NOHESS) THEN
            WRITE(*,'(A,I4,A,F12.4)') 
     1       '         NO HESSIAN: USING RAYLEIGHT-RITZ; ALLOWED STEPS=',HMNEVS,' CONVERGENCE FOR RMS < ',HMCEIG
         WRITE(*,'(A,A2,A,G20.10)') '         STEP TYPE IS ',HMMETHOD,
     &                ' AND WILL REVERT TO LBFGS IF THE LOWEST NONZERO EIGENVALUE > ',HMEVMAX
         ELSE
            WRITE(*,'(A,I4,A,I4,A,F12.4,A)') 
     1        '         ALLOWED STEPS FOR LARGEST HESSIAN EIGENVECTOR=',HMNEVL,
     2        ', SMALLEST EIGENVECTOR=',HMNEVS,' CONVERGENCE AT ',HMCEIG,'%'
         ENDIF
      ENDIF
      IF (BFGSMINT.AND.(.NOT.BFGSTST)) THEN
         WRITE(*,'(A,I8)') ' FETCHZ> LBFGS MINIMIZATION, MAXIMUM STEPS=',BFGSSTEPS
      ELSE IF (BFGSTST) THEN
         IF (BFGSSTEP.AND.(.NOT.HYBRIDMINT)) THEN
            WRITE(*,'(A)') ' FETCHZ> ONE EF STEP WILL BE TAKEN BEFORE BFGS MINIMIZATION'
         ELSE
            WRITE(*,'(A,I4)') ' FETCHZ> HYBRID EF/BFGS TRANSITION STATE SEARCH, MAXIMUM STEPS=',NSTEPS
            WRITE(*,'(A,I4,A,I4,A,F12.6)') '         MAXIMUM TANGENT SPACE STEPS=',NBFGSMAX1, 
     &                               ' OR ',NBFGSMAX2,' WHEN OVERLAP IS BETTER THAN ',1.0D0-BFGSTSTOL
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> UPHILL MODE IS ',IVEC,' FOR INITIAL STEP AND ',IVEC2,' AFTER THAT'
         ENDIF
         IF (.NOT.(READV.AND.BFGSSTEP)) THEN
            IF (NOHESS) THEN
               WRITE(*,'(A,I4,A,F12.4)') 
     1          ' FETCHZ> NO HESSIAN: USING RAYLEIGH-RITZ, ALLOWED STEPS=',NEVS,' CONVERGENCE FOR RMS < ',CEIG
            ELSE
               WRITE(*,'(A,I4,A,I4,A,F12.4,A)') 
     1           ' FETCHZ> ALLOWED STEPS FOR LARGEST HESSIAN EIGENVECTOR=',NEVL,
     2           ', SMALLEST EIGENVECTOR=',NEVS,' CONVERGENCE AT ',CEIG,'%'
            ENDIF
         ENDIF
         IF ((NSECDIAG.NE.1).AND.(NSECDIAG.NE.2)) THEN
            PRINT '(A)',' FETCHZ> UNRECOGNISED VALUE FOR NSECDIAG - RESETTING TO ONE'
            NSECDIAG=1
         ENDIF
         IF (.NOT.NOIT) WRITE(*,'(A,I4)') 
     &         ' FETCHZ> HESSIAN EIGENVECTOR IN RAYLEIGH-RITZ SCHEME CALCULATED USING METHOD ',NSECDIAG
      ELSE IF (BBRSDMT) THEN
         WRITE(*,'(A,I5,A,G20.10)')   ' FETCHZ> BBR STEEPEST-DESCENT METHOD, MAXIMUM STEPS=',BBRSTEPS,' RMS CONVERGENCE ',BBRCONV
         WRITE(*,'(5(A,F15.5),A,I5)') '         GAMMA=',BBRGAM,' EPS=',BBREPS,' SIG1=',BBRSIGMA1,' SIG2=',BBRSIGMA2, 
     &                                ' ALPHA=',BBRALPHA,' M=',BBRM
      ELSE IF (BSMIN) THEN
         NUSE=NSTEPS
         IF (PATHSDSTEPS.GT.0) NUSE=PATHSDSTEPS
         WRITE(*,'(A,I5)') ' FETCHZ> BULIRSCH-STOER GRADIENT ONLY STEEPEST-DESCENT, MAXIMUM STEPS=',NUSE
      ELSE IF (RKMIN) THEN
         NUSE=NSTEPS
         IF (PATHSDSTEPS.GT.0) NUSE=PATHSDSTEPS
         WRITE(*,'(A,I5)') ' FETCHZ> 5TH ORDER RUNGE-KUTTA GRADIENT ONLY STEEPEST-DESCENT, MAXIMUM STEPS=',NUSE
      ELSE
         IF (NUSEEV.GT.0) WRITE(*,'(A,I5)') ' FETCHZ> MAXIMUM NUMBER OF EIGENVALUES/EIGENVECTORS TO BE CALCULATED=',NUSEEV
         IF (INR.EQ.0) WRITE(*,'(A,I5)') ' FETCHZ> EIGENVECTOR-FOLLOWING MINIMIZATION, MAXIMUM STEPS=',NSTEPS
         IF (INR.EQ.1) WRITE(*,'(A,I5)') ' FETCHZ> MODIFIED NEWTON-RAPHSON STEPS, MAXIMUM STEPS=',NSTEPS
         IF (INR.EQ.2) WRITE(*,'(A,I5)') ' FETCHZ> EIGENVECTOR-FOLLOWING TRANSITION STATE SEARCH, MAXIMUM STEPS=',NSTEPS
         IF (INR.EQ.3) WRITE(*,'(A,I5)') 
     1' FETCHZ> EIGENVECTOR-FOLLOWING MINIMIZATION, NO REORIENTATION AND PSEUDO-THIRD DERIVATIVE CORRECTION, MAXIMUM STEPS=',NSTEPS
         IF (INR.EQ.4) WRITE(*,'(A,I5)') 
     1    ' FETCHZ> EIGENVECTOR-FOLLOWING TRANSITION STATE SEARCH WITH PSEUDO-THIRD DERIVATIVE CORRECTION, MAXIMUM STEPS=',NSTEPS
         IF (INR.EQ.5) WRITE(*,'(A,I5)') 
     1    ' FETCHZ> EIGENVECTOR-FOLLOWING MINIMIZATION, GEOMETRY SHIFTED TO PRINCIPAL AXES AT FIRST STEP, MAXIMUM STEPS=',NSTEPS
         IF (INR.EQ.6) WRITE(*,'(A,I5)') 
     1    ' FETCHZ> STEEPEST-DESCENT MINIMIZATION USING FIRST AND SECOND DERIVATIVES, MAXIMUM STEPS=',NSTEPS
         IF (INR.EQ.7) WRITE(*,'(A,I5)') 
     1    ' FETCHZ> STEEPEST-DESCENT MINIMIZATION USING FIRST AND SECOND DERIVATIVES - CAN STOP AT A SADDLE, MAXIMUM STEPS=',NSTEPS
         IF ((INR.EQ.2).OR.(INR.EQ.4)) THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> UPHILL MODE IS ',IVEC,' FOR INITIAL STEP AND ',IVEC2,' AFTER THAT'
         ENDIF
         IF ((PATHSDSTEPS.GT.0).AND.(INR.LE.6)) PRINT '(A,I8)',
     &                  ' FETCHZ> MAXIMUM NUMBER OF STEPS FOR PATHWAY MINIMISATION=',PATHSDSTEPS
      ENDIF

      IF (GRADSQ) WRITE(*,'(A)') ' FETCHZ> USING THE MODULUS GRADIENT AS THE OBJECTIVE FUNCTION'
      PRINT*
      CALL FLUSH(6,ISTAT)

      IF (AMBER.OR.AMBERT.OR.NABT) THEN
         NOPT=3*NATOMS
         WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' AMBER ATOMS'
         IF (MOVIE) WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> MOVIE WILL BE DUMPED IN XYZ FORMAT'
         IF (TWOENDS.OR.CONNECTT.OR.NEBT.OR.NEWNEBT.OR.DRAGT.OR.GUESSPATHT
     $     .OR.MECCANOT.OR.MORPHT.OR.GREATCIRCLET.OR.GROWSTRINGT.OR.BHINTERPT.OR.BISECTT) THEN
            OPEN (UNIT=7,FILE=FINSTRING,STATUS='OLD')
          IF(AMBERT.OR.NABT) THEN      ! READ COORDINATES FROM FILE FINISH (CONTAINING ONLY COORDINATES)
            DO J1=1,NATOMS
               READ(7,*)  FIN(3*(J1-1)+1),FIN(3*(J1-1)+2),FIN(3*(J1-1)+3)
            ENDDO
            CLOSE(7)
          ELSE
            DO J1=1,NATOMS
               READ(7,*) CD1, CD2, IDUM1, IDUM2, FIN(3*(J1-1)+1),FIN(3*(J1-1)+2),FIN(3*(J1-1)+3)
C              WRITE(*,*) CD1, CD2, IDUM1, IDUM2, FIN(3*(J1-1)+1),FIN(3*(J1-1)+2),FIN(3*(J1-1)+3)
            ENDDO
          END IF
         ENDIF

      ELSEIF (RINGPOLYMERT) THEN
         NOPT=0
160      CALL INPUT(END)
         IF (.NOT.END) THEN
            DO J1=1,NITEMS
               NOPT=NOPT+1
               CALL READF(Q(NOPT))
            ENDDO
            GOTO 160
         ENDIF
         RPDOF=NOPT/RPIMAGES
         IF (RPDOF*RPIMAGES.NE.NOPT) THEN
            PRINT '(2(A,I6))','FETCHZ> ERROR *** NUMBER OF VARIABLES READ, ',
     &                         NOPT,' IS NOT A MULTIPLE OF THE NUMBER OF BEADS ',RPIMAGES
            STOP
         ENDIF
         WRITE(*,'(A,I6,A,I6,A)')' SYSTEM ',NOPT,' COORDINATES WILL BE OPTIMISED FOR A RING POLYMER OF ',RPIMAGES,' BEADS'
         IF (RPSYSTEM(1:4).EQ.'AECK') THEN
            WRITE(*,'(A,G20.10,A)') '               1/KT (A.U.)=',RPBETA,' POTENTIAL TYPE=' // TRIM(ADJUSTL(RPSYSTEM))
            NATOMS=NOPT
         ELSEIF (RPSYSTEM(1:2).EQ.'SD') THEN
            NOXYGEN=(RPDOF/3+1)/3
            NCHARGE=(RPDOF/3)-3*NOXYGEN
            WRITE(*,'(A,G20.10,A)') '               1/KT (MOL/KCAL)=',RPBETA,' POTENTIAL TYPE=' // TRIM(ADJUSTL(RPSYSTEM))
            WRITE(*,'(A,2I6)')     '               NUMBER OF O AND H ATOMS=',NOXYGEN,(RPDOF/3)-NOXYGEN
            CALL SDINIT(NOXYGEN,NCHARGE)
            NATOMS=NOPT/3
         ELSEIF (RPSYSTEM(1:2).EQ.'TT') THEN
            WRITE(*,'(A,G20.10,A)')  '              1/KT A.U.=',RPBETA,' POTENTIAL TYPE=' // TRIM(ADJUSTL(RPSYSTEM))
            RPBETA=RPBETA*0.00159360144367 ! CONVERT TO KCAL/MOL UNITS
            WRITE(*,'(A,G20.10,A)')  '              1/KT (MOL/KCAL)=',RPBETA
            WRITE(*,'(A,I0,A)') '              TTM3-F POTENTIAL FOR A CLUSTER OF ', RPDOF/9, ' WATER MOLECULES'
            NATOMS=NOPT/3
         ELSEIF (RPSYSTEM(1:3).EQ.'MCY') THEN
            WRITE(*,'(A,G20.10,A)')  '              1/KT (A.U.)=',RPBETA,' POTENTIAL TYPE=' // TRIM(ADJUSTL(RPSYSTEM))
            WRITE(*,'(A,I1,A,I0,A)') '              VRT(MCY-5F) FLEXIBLE WATER DIMER POTENTIAL'
            NOXYGEN=RPDOF/9
            IF (NOXYGEN /= 2) THEN
               PRINT *, 'ERROR: VRT(MCY-5F) ONLY FOR WATER DIMER; NOXYGEN = ', NOXYGEN
               STOP
            ENDIF
            NATOMS=NOPT/3
         ELSEIF (RPSYSTEM(1:2).EQ.'JB') THEN
            NOXYGEN=RPDOF/9
            WRITE(*,'(A,G20.10,A)')  '              1/KT (A.U.)=',RPBETA,' POTENTIAL TYPE=' // TRIM(ADJUSTL(RPSYSTEM))
            WRITE(*,'(A,I1,A,I0,A)') '              BOWMAN''S PES#',BOWMANPES,' FOR A CLUSTER OF ',NOXYGEN,' WATER MOLECULES'
            !CALL BOWMANINIT(NOXYGEN, BOWMANPES, TRIM(BOWMANDIR))
            NATOMS=NOPT/3
         ELSE
            PRINT *, ' FETCHZ> UNKNOWN RPSYSTEM: ', RPSYSTEM
            STOP
         ENDIF
         WRITE(*,'(A,I6,A)')     '               READING PARTICLE MASSES FOR ',RPDOF,' DEGREES OF FREEDOM FROM FILE RPMASSES:'
         ALLOCATE(RPMASSES(RPDOF))
!
! MUST NOT USE UNIT 1 HERE - THE POINTS AND ENERGIES FILES ARE CONNECTED TO
! UNITS 1 AND 2 IF PRINTPTS OR MORPHT IS TRUE.
!
         IF (RPFIXT) THEN
            ALLOCATE(XMINA(RPDOF), XMINB(RPDOF))
            OPEN(UNIT=121,FILE='XMINA',STATUS='OLD')
            READ(121,*) XMINA
            CLOSE(121)
            OPEN(UNIT=122,FILE='XMINB',STATUS='OLD')
            READ(122,*) XMINB
            CLOSE(122)
         ENDIF
         OPEN(UNIT=123,FILE='RPMASSES',STATUS='OLD')
         READ(123,*) RPMASSES(1:RPDOF)
         CLOSE(123)
         WRITE(*,'(6G20.10)') RPMASSES(1:RPDOF)
         IF (RPSYSTEM(1:4).EQ.'AECK') THEN
            DO J1=1,NOPT
               IATNUM(J1)=1
               ZSYM(J1)='RP'
            ENDDO
         ELSE IF (RPSYSTEM.EQ.'SD') THEN
            DO J1=1,RPIMAGES
               DO J2=1,NOXYGEN
                  IATNUM((RPDOF/3)*(J1-1)+J2)=16
                  ZSYM((RPDOF/3)*(J1-1)+J2)='O '
               ENDDO
               DO J2=NOXYGEN+1,RPDOF/3
                  IATNUM((RPDOF/3)*(J1-1)+J2)=1
                  ZSYM((RPDOF/3)*(J1-1)+J2)='H '
               ENDDO
            ENDDO
         ELSE IF (RPSYSTEM.EQ.'JB') THEN
            DO J1=1,RPIMAGES
               DO J2=1,2*NOXYGEN
                  IATNUM((RPDOF/3)*(J1-1)+J2)=1
                  ZSYM((RPDOF/3)*(J1-1)+J2)='H '
               ENDDO
               DO J2=2*NOXYGEN+1,RPDOF/3
                  IATNUM((RPDOF/3)*(J1-1)+J2)=16
                  ZSYM((RPDOF/3)*(J1-1)+J2)='O '
               ENDDO
            ENDDO
         ENDIF
      ELSE IF (AMHT) THEN
         NOPT=3*NATOMS
         WRITE(*,'(A,I4,A,I4,A)') ' SYSTEM ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' AMH ATOMS'

         IF (TWOENDS.OR.CONNECTT.OR.NEBT.OR.NEWNEBT.OR.DRAGT.OR.GUESSPATHT.OR.MECCANOT) THEN
              IF (FILTH2.EQ.0) THEN
                 FINSTRING='FINISH'
              ELSE
                 WRITE(FTEMP,*) FILTH
                 WRITE(FINSTRING,'(A)') 'FINISH.' // TRIM(ADJUSTL(FTEMP))
              ENDIF

           OPEN(UNIT=80,FILE=FINSTRING,STATUS='OLD',FORM='FORMATTED')

                  WRITE(6,*)'FINISH ', NRES_AMH_TEMP
                  WRITE(6,201)(SEQ(J),J=1,NRES_AMH_TEMP)
201               FORMAT (25(I2,1X))
            DO 500 I500=1,NRES_AMH_TEMP
                  READ(80,*)X,Y,Z

76                FORMAT(3(G25.15))
C                  WRITE(6,76) X,Y,Z
                  FINCORD(I500,1,1,1)=X
                  FINCORD(I500,2,1,1)=Y
                  FINCORD(I500,3,1,1)=Z

                  READ(80,*)X,Y,Z
C                  WRITE(6,76)X,Y,Z
                  FINCORD(I500,1,1,2)=X
                  FINCORD(I500,2,1,2)=Y
                  FINCORD(I500,3,1,2)=Z

                  READ(80,*)X,Y,Z
C                  WRITE(6,76)X,Y,Z
                  FINCORD(I500,1,1,3)=X
                  FINCORD(I500,2,1,3)=Y
                  FINCORD(I500,3,1,3)=Z
500              CONTINUE

       GLY_COUNT = 0
       DO 764 III = 1,NRES_AMH_TEMP ! AMH MCP HACK

       IF (SEQ(III).EQ.8) THEN
         FIN(9*(III-1)+1- GLY_COUNT*3) = FINCORD(III, 1, 1, 1) !  CA X
         FIN(9*(III-1)+2- GLY_COUNT*3) = FINCORD(III, 2, 1, 1) !  CA Y
         FIN(9*(III-1)+3- GLY_COUNT*3) = FINCORD(III, 3, 1, 1) !  CA Z
         FIN(9*(III-1)+4- GLY_COUNT*3) = FINCORD(III, 1, 1, 3) !  O X
         FIN(9*(III-1)+5- GLY_COUNT*3) = FINCORD(III, 2, 1, 3) !  O Y
         FIN(9*(III-1)+6- GLY_COUNT*3) = FINCORD(III, 3, 1, 3) !  O Z
         GLY_COUNT = GLY_COUNT +1
       ELSE
         FIN(9*(III-1)+1 - GLY_COUNT*3) = FINCORD(III, 1, 1, 1) !  CA X
         FIN(9*(III-1)+2 - GLY_COUNT*3) = FINCORD(III, 2, 1, 1) !  CA Y
         FIN(9*(III-1)+3 - GLY_COUNT*3) = FINCORD(III, 3, 1, 1) !  CA Z
         FIN(9*(III-1)+4 - GLY_COUNT*3) = FINCORD(III, 1, 1, 2) !  CB X
         FIN(9*(III-1)+5 - GLY_COUNT*3) = FINCORD(III, 2, 1, 2) !  CB Y
         FIN(9*(III-1)+6 - GLY_COUNT*3) = FINCORD(III, 3, 1, 2) !  CB Z
         FIN(9*(III-1)+7 - GLY_COUNT*3) = FINCORD(III, 1, 1, 3) !  O X
         FIN(9*(III-1)+8 - GLY_COUNT*3) = FINCORD(III, 2, 1, 3) !  O Y
         FIN(9*(III-1)+9 - GLY_COUNT*3) = FINCORD(III, 3, 1, 3) !  O Z
       ENDIF

764    CONTINUE

         ENDIF

        DO J1=1,NATOMS
               IATNUM(J1)=1
               ZSYM(J1)='AM'
        ENDDO

      ELSE IF (CHRMMT) THEN
         NOPT=3*NATOMS
         IF (.NOT.INTMINT) THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' CHARMM ATOMS'
         ELSE
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> INTERNAL COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' CHARMM ATOMS'
         ENDIF
         IF (TWOENDS.OR.CONNECTT.OR.NEBT.OR.NEWNEBT.OR.DRAGT.OR.GUESSPATHT
     $     .OR.MECCANOT.OR.MORPHT.OR.GREATCIRCLET.OR.GROWSTRINGT.OR.BHINTERPT.OR.BISECTT) THEN
            IF (MACHINE) THEN
                 OPEN(7,FILE=FINSTRING,ACCESS='DIRECT',FORM='UNFORMATTED',STATUS='OLD',RECL=3*8*NATOMS)
                 READ(7,REC=1) (FIN(J1),J1=1,3*NATOMS)
                 CLOSE(7)
            ELSE
                 OPEN (UNIT=7,FILE=FINSTRING,STATUS='OLD')
                 READ (7,*)
                 DO J1=1,NATOMS
!                   READ (7,*) IDUM1,IDUM2,CD1,CD2,FIN(3*(J1-1)+1),FIN(3*(J1-1)+2),FIN(3*(J1-1)+3),IDUM1,IDUM2
                    READ (7,*) IDUM1,IDUM2,CD1,CD2,FIN(3*(J1-1)+1),FIN(3*(J1-1)+2),FIN(3*(J1-1)+3)
                 ENDDO
            ENDIF
         ENDIF
      ELSE IF (UNRST) THEN
         NOPT=3*NATOMS
C JMC NOW SET IN KEYWORDS.F         NINTS=2*NRES-5+2*NSIDE
         IF (.NOT.INTMINT) THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' UNRES ATOMS'
         ELSE
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NINTS,' INTERNAL COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' UNRES ATOMS'
         ENDIF
         IF (TWOENDS.OR.CONNECTT.OR.NEBT.OR.NEWNEBT.OR.DRAGT.OR.GUESSPATHT
     $     .OR.MECCANOT.OR.MORPHT.OR.GREATCIRCLET.OR.GROWSTRINGT.OR.BHINTERPT.OR.BISECTT) THEN
            OPEN (UNIT=7,FILE=FINSTRING,STATUS='OLD')
            READ (7,*) 
            DO J1=1,NATOMS
               READ (7,*) CD1,FIN(3*(J1-1)+1),FIN(3*(J1-1)+2),FIN(3*(J1-1)+3)
            ENDDO
         ENDIF
      ELSE IF (CASTEP) THEN
         WRITE(*,'(A,I4,A)') ' FETCHZ> CASTEP RUN FOR ',NATOMS,' ATOMS'
         WRITE(*,'(A,A)') ' FETCHZ> CASTEP RUN COMMAND IS ',TRIM(ADJUSTL(CASTEPJOB))
         FNAME=SYS(1:LSYS) // '.CELL'
         IF (DEBUG) WRITE(*,'(A,A)') ' FETCHZ> READING CELL PARAMETERS FROM FILE ',FNAME
         OPEN(UNIT=7,FILE=FNAME,STATUS='OLD')
         READCELL: DO 
            READ(7,'(A19)') WW
            CALL UPPERCASE(WW)
            IF (WW(1:19).EQ.'%BLOCK LATTICE_CART') THEN
               READ(7,*) WW ! THE LINE WITH THE UNITS ON IT
               READ(7,*) AMAT(1,1), AMAT(2,1), AMAT(3,1)
               READ(7,*) AMAT(1,2), AMAT(2,2), AMAT(3,2)
               READ(7,*) AMAT(1,3), AMAT(2,3), AMAT(3,3)
               IF (DEBUG) PRINT '(A)',' FETCHZ> CELL MATRIX:'
               IF (DEBUG) PRINT '(3F20.10)',((AMAT(J1,J2),J2=1,3),J1=1,3)
               EXIT READCELL
            ENDIF
         ENDDO READCELL
         CLOSE(7)

         DETER=-AMAT(1,3)*AMAT(2,2)*AMAT(3,1)
     1         +AMAT(1,2)*AMAT(2,3)*AMAT(3,1)
     2         +AMAT(1,3)*AMAT(2,1)*AMAT(3,2)
     3         -AMAT(1,1)*AMAT(2,3)*AMAT(3,2)
     4         -AMAT(1,2)*AMAT(2,1)*AMAT(3,3)
     5         +AMAT(1,1)*AMAT(2,2)*AMAT(3,3)
         AINV(1,1)=(-AMAT(2,3)*AMAT(3,2)+AMAT(2,2)*AMAT(3,3))/DETER
         AINV(1,2)=( AMAT(1,3)*AMAT(3,2)-AMAT(1,2)*AMAT(3,3))/DETER
         AINV(1,3)=(-AMAT(1,3)*AMAT(2,2)+AMAT(1,2)*AMAT(2,3))/DETER
         AINV(2,1)=( AMAT(2,3)*AMAT(3,1)-AMAT(2,1)*AMAT(3,3))/DETER
         AINV(2,2)=(-AMAT(1,3)*AMAT(3,1)+AMAT(1,1)*AMAT(3,3))/DETER
         AINV(2,3)=( AMAT(1,3)*AMAT(2,1)-AMAT(1,1)*AMAT(2,3))/DETER
         AINV(3,1)=(-AMAT(2,2)*AMAT(3,1)+AMAT(2,1)*AMAT(3,2))/DETER
         AINV(3,2)=( AMAT(1,2)*AMAT(3,1)-AMAT(1,1)*AMAT(3,2))/DETER
         AINV(3,3)=(-AMAT(1,2)*AMAT(2,1)+AMAT(1,1)*AMAT(2,2))/DETER

            FNAME=SYS(1:LSYS) // '.CELL'
            WRITE(*,'(A,A)') ' FETCHZ> READING COORDINATES FROM FILE ',FNAME
            OPEN(UNIT=7,FILE=FNAME,STATUS='OLD')
            READX: DO 
            READ(7,'(A20)') WW
            CALL UPPERCASE(WW)
            IF (WW(1:16).EQ.'%BLOCK POSITIONS') THEN
               IF (WW(18:20).EQ.'ABS') THEN ! DONT NEED TO CONVERT FROM FRACTIONAL COORDINATES
                  AMAT(1:3,1:3)=0.0D0; AINV(1:3,1:3)=0.0D0
                  AMAT(1,1)=1.0D0;AMAT(2,2)=1.0D0;AMAT(3,3)=1.0D0
                  AINV(1,1)=1.0D0;AINV(2,2)=1.0D0;AINV(3,3)=1.0D0
               ENDIF
               DO J1=1,NATOMS
                  READ(7,*) WW(1:2),Q(3*(J1-1)+1),Q(3*(J1-1)+2),Q(3*(J1-1)+3)
                  CALL UPPERCASE(WW)
                  ZSYM(J1)=WW(1:2)
C                 PRINT *,ZSYM(J1)(1:2),Q(3*(J1-1)+1),Q(3*(J1-1)+2),Q(3*(J1-1)+3)
                  TEMPX=AMAT(1,1)*Q(3*(J1-1)+1)+AMAT(1,2)*Q(3*(J1-1)+2)+AMAT(1,3)*Q(3*(J1-1)+3)
                  TEMPY=AMAT(2,1)*Q(3*(J1-1)+1)+AMAT(2,2)*Q(3*(J1-1)+2)+AMAT(2,3)*Q(3*(J1-1)+3)
                  TEMPZ=AMAT(3,1)*Q(3*(J1-1)+1)+AMAT(3,2)*Q(3*(J1-1)+2)+AMAT(3,3)*Q(3*(J1-1)+3)
                  Q(3*(J1-1)+1)=TEMPX
                  Q(3*(J1-1)+2)=TEMPY
                  Q(3*(J1-1)+3)=TEMPZ
!                 IATNUM(J1)=1
!                 ZSYM(J1)='H'
               ENDDO
               EXIT READX
            ENDIF
         ENDDO READX
         CLOSE(7)

         NOPT=3*NATOMS
C        WRITE(*,'(A)') 'THE ABSOLUTE COORDINATES FROM FETCHZ'
C        WRITE(*,'(6F15.5)') (Q(J1),J1=1,NOPT)

         IF (TWOENDS.OR.CONNECTT.OR.NEBT.OR.NEWNEBT.OR.DRAGT.OR.GUESSPATHT
     $     .OR.MECCANOT.OR.MORPHT.OR.GREATCIRCLET.OR.GROWSTRINGT.OR.BHINTERPT.OR.BISECTT) THEN
            OPEN (UNIT=7,FILE=FINSTRING,STATUS='OLD') 
            DO J1=1,NATOMS
               READ(7,*) FIN(3*(J1-1)+1),FIN(3*(J1-1)+2),FIN(3*(J1-1)+3)
            ENDDO
            CLOSE(7)
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> COORDINATES OF SECOND POINT READ FROM FILE FINISH'
         ENDIF
C        PRINT*,' FETCHZ> COORDINATES:'
C        WRITE(*,'(3F20.10)') (Q(J1),J1=1,3*NATOMS)

      ELSE IF (ONETEP) THEN
         WRITE(*,'(A,I4,A)') ' FETCHZ> ONETEP RUN FOR ',NATOMS,' ATOMS'
         FNAME=SYS(1:LSYS) // '.DAT'
         IF (DEBUG) WRITE(*,'(A,A)') ' FETCHZ> READING CELL PARAMETERS FROM FILE ',FNAME
         OPEN(UNIT=7,FILE=FNAME,STATUS='OLD')
         READCELL2: DO 
            READ(7,'(A19)') WW
            CALL UPPERCASE(WW)
            IF (WW(1:19).EQ.'%BLOCK LATTICE_CART') THEN
C              READ(7,*) WW ! THE LINE WITH THE UNITS ON IT ! EVERYTHING MUST BE IN A.U.! THIS LINE MUST NOT BE PRESENT!
               READ(7,*) AMAT(1,1), AMAT(1,2), AMAT(1,3)
               READ(7,*) AMAT(2,1), AMAT(2,2), AMAT(2,3)
               READ(7,*) AMAT(3,1), AMAT(3,2), AMAT(3,3)
               IF (DEBUG) PRINT '(A)',' FETCHZ> CELL MATRIX:'
               IF (DEBUG) PRINT '(3F20.10)',((AMAT(J1,J2),J2=1,3),J1=1,3)
               EXIT READCELL2
            ENDIF
         ENDDO READCELL2
         CLOSE(7)

         DETER=-AMAT(1,3)*AMAT(2,2)*AMAT(3,1)
     1         +AMAT(1,2)*AMAT(2,3)*AMAT(3,1)
     2         +AMAT(1,3)*AMAT(2,1)*AMAT(3,2)
     3         -AMAT(1,1)*AMAT(2,3)*AMAT(3,2)
     4         -AMAT(1,2)*AMAT(2,1)*AMAT(3,3)
     5         +AMAT(1,1)*AMAT(2,2)*AMAT(3,3)
         AINV(1,1)=(-AMAT(2,3)*AMAT(3,2)+AMAT(2,2)*AMAT(3,3))/DETER
         AINV(1,2)=( AMAT(1,3)*AMAT(3,2)-AMAT(1,2)*AMAT(3,3))/DETER
         AINV(1,3)=(-AMAT(1,3)*AMAT(2,2)+AMAT(1,2)*AMAT(2,3))/DETER
         AINV(2,1)=( AMAT(2,3)*AMAT(3,1)-AMAT(2,1)*AMAT(3,3))/DETER
         AINV(2,2)=(-AMAT(1,3)*AMAT(3,1)+AMAT(1,1)*AMAT(3,3))/DETER
         AINV(2,3)=( AMAT(1,3)*AMAT(2,1)-AMAT(1,1)*AMAT(2,3))/DETER
         AINV(3,1)=(-AMAT(2,2)*AMAT(3,1)+AMAT(2,1)*AMAT(3,2))/DETER
         AINV(3,2)=( AMAT(1,2)*AMAT(3,1)-AMAT(1,1)*AMAT(3,2))/DETER
         AINV(3,3)=(-AMAT(1,2)*AMAT(2,1)+AMAT(1,1)*AMAT(2,2))/DETER

         FNAME=SYS(1:LSYS) // '.DAT'
         WRITE(*,'(A,A)') ' FETCHZ> READING COORDINATES FROM FILE ',FNAME
         OPEN(UNIT=7,FILE=FNAME,STATUS='OLD')
         READX2: DO 
            READ(7,'(A20)') WW
            CALL UPPERCASE(WW)
            IF (WW(1:16).EQ.'%BLOCK POSITIONS') THEN
               IF (WW(18:20).EQ.'ABS') THEN ! DONT NEED TO CONVERT FROM FRACTIONAL COORDINATES
                  AMAT(1:3,1:3)=0.0D0; AINV(1:3,1:3)=0.0D0
                  AMAT(1,1)=1.0D0;AMAT(2,2)=1.0D0;AMAT(3,3)=1.0D0
                  AINV(1,1)=1.0D0;AINV(2,2)=1.0D0;AINV(3,3)=1.0D0
               ENDIF
               DO J1=1,NATOMS
                  READ(7,*) WW(1:2),Q(3*(J1-1)+1),Q(3*(J1-1)+2),Q(3*(J1-1)+3)
                  CALL UPPERCASE(WW)
                  ZSYM(J1)=WW(1:2)
C                 PRINT *,WW(1:2),Q(3*(J1-1)+1),Q(3*(J1-1)+2),Q(3*(J1-1)+3)
                  TEMPX=AMAT(1,1)*Q(3*(J1-1)+1)+AMAT(1,2)*Q(3*(J1-1)+2)+AMAT(1,3)*Q(3*(J1-1)+3)
                  TEMPY=AMAT(2,1)*Q(3*(J1-1)+1)+AMAT(2,2)*Q(3*(J1-1)+2)+AMAT(2,3)*Q(3*(J1-1)+3)
                  TEMPZ=AMAT(3,1)*Q(3*(J1-1)+1)+AMAT(3,2)*Q(3*(J1-1)+2)+AMAT(3,3)*Q(3*(J1-1)+3)
                  Q(3*(J1-1)+1)=TEMPX
                  Q(3*(J1-1)+2)=TEMPY
                  Q(3*(J1-1)+3)=TEMPZ
!                 IATNUM(J1)=6
!                 ZSYM(J1)='C'
               ENDDO
               EXIT READX2
            ENDIF
         ENDDO READX2
         CLOSE(7)

         NOPT=3*NATOMS
C        WRITE(*,'(A)') 'THE ABSOLUTE COORDINATES FROM FETCHZ'
C        WRITE(*,'(6F15.5)') (Q(J1),J1=1,NOPT)

         IF (TWOENDS.OR.CONNECTT.OR.NEBT.OR.NEWNEBT.OR.DRAGT.OR.GUESSPATHT
     $     .OR.MECCANOT.OR.MORPHT.OR.GREATCIRCLET.OR.GROWSTRINGT.OR.BHINTERPT.OR.BISECTT) THEN
            OPEN (UNIT=7,FILE=FINSTRING,STATUS='OLD') 
            DO J1=1,NATOMS
               READ(7,*) FIN(3*(J1-1)+1),FIN(3*(J1-1)+2),FIN(3*(J1-1)+3)
            ENDDO
            CLOSE(7)
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> COORDINATES OF SECOND POINT READ FROM FILE FINISH'
         ENDIF
C        PRINT*,' FETCHZ> COORDINATES:'
C        WRITE(*,'(3F20.10)') (Q(J1),J1=1,3*NATOMS)

C     READING THE CELL PARAMETERS AND THE ATOMIC COORDINATES FROM THE CP2K INPUT FILE 
C     ($FNAME.INP). FOR SIMPLICITY WE ASUME THAT THE CELL-VECTORS ARE ALWAYS GIVEN IN THE FORMAT
C
C     &CELL
C     A AMAT(1,1), AMAT(1,2), AMAT(1,3) 
C     B AMAT(2,1), AMAT(2,2), AMAT(2,3)
C     C AMAT(3,1), AMAT(3,2), AMAT(3,3)
C     PERIODIC NONE/X/Y/Z/XY/XZ/YX/XYZ 
C     &END CELL
C   
C     THE PERIODIC KEYWORD IS NOT NECESSARY BUT IF IT IS PRESENT IT SHOULD ALWAYS FOLLOW THE CELL PARAMETER SETTINGS
C     IF NOT PRESENT FULL PERIODICITY NAMELY PERIODIC XYZ IS ASSUMED.
C     NOTICE THAT CP2K LISTS THE THREE LATTICE VECTORS AS ROWS WHILE OPTIM WANTS THEM AS COLUMS. 
C     FOR THE READING OF THE ATOMIC COORDINATES WE ASUME THE FOLLOWING FORMAT
C
C     &COORD
C     SCALED .TRUE. OR .FALSE.
C     ATOMICSYMBOL1 X1 Y1 Z1 
C     ATOMICSYMBOL2 X2 Y2 Z2 
C     ......................
C     ATOMICSYMBOLN XN YN ZN 
C     &END COORD
C
C     NOTICE THAT THE UNIT FOR THE CELL DIMENSIONS AS WELL AS FOR THE ATOMIC COORDINATES IS ANGSTROM 
C     ------------------

      ELSE IF (CP2K) THEN
         WRITE(*,'(A,I4,A)') ' FETCHZ> CP2K RUN FOR ',NATOMS,' ATOMS'
         WRITE(*,'(A,A)') ' FETCHZ> CP2K RUN COMMAND IS ',TRIM(ADJUSTL(CP2KJOB))
         FNAME=SYS(1:LSYS) // '.INP'
         IF (DEBUG) WRITE(*,'(A,A)') ' FETCHZ> READING CELL PARAMETERS FROM FILE ',FNAME
         OPEN(UNIT=7,FILE=FNAME,STATUS='OLD')
         READCELL3: DO
            READ(7,'(A21)') WW
            WW=ADJUSTL(WW)
            CALL UPPERCASE(WW)
            IF (WW(1:5).EQ.'&CELL') THEN
               READ(7,*) WW, AMAT(1,1), AMAT(2,1), AMAT(3,1)
               READ(7,*) WW, AMAT(1,2), AMAT(2,2), AMAT(3,2)
               READ(7,*) WW, AMAT(1,3), AMAT(2,3), AMAT(3,3)
               IF (DEBUG) PRINT '(A)',' FETCHZ> CELL MATRIX:'
               IF (DEBUG) PRINT '(3F20.10)',((AMAT(J1,J2),J2=1,3),J1=1,3)
               EXIT READCELL3
            ENDIF
         ENDDO READCELL3
         CLOSE(7)

         DETER=-AMAT(1,3)*AMAT(2,2)*AMAT(3,1)
     1         +AMAT(1,2)*AMAT(2,3)*AMAT(3,1)
     2         +AMAT(1,3)*AMAT(2,1)*AMAT(3,2)
     3         -AMAT(1,1)*AMAT(2,3)*AMAT(3,2)
     4         -AMAT(1,2)*AMAT(2,1)*AMAT(3,3)
     5         +AMAT(1,1)*AMAT(2,2)*AMAT(3,3)
         AINV(1,1)=(-AMAT(2,3)*AMAT(3,2)+AMAT(2,2)*AMAT(3,3))/DETER
         AINV(1,2)=( AMAT(1,3)*AMAT(3,2)-AMAT(1,2)*AMAT(3,3))/DETER
         AINV(1,3)=(-AMAT(1,3)*AMAT(2,2)+AMAT(1,2)*AMAT(2,3))/DETER
         AINV(2,1)=( AMAT(2,3)*AMAT(3,1)-AMAT(2,1)*AMAT(3,3))/DETER
         AINV(2,2)=(-AMAT(1,3)*AMAT(3,1)+AMAT(1,1)*AMAT(3,3))/DETER
         AINV(2,3)=( AMAT(1,3)*AMAT(2,1)-AMAT(1,1)*AMAT(2,3))/DETER
         AINV(3,1)=(-AMAT(2,2)*AMAT(3,1)+AMAT(2,1)*AMAT(3,2))/DETER
         AINV(3,2)=( AMAT(1,2)*AMAT(3,1)-AMAT(1,1)*AMAT(3,2))/DETER
         AINV(3,3)=(-AMAT(1,2)*AMAT(2,1)+AMAT(1,1)*AMAT(2,2))/DETER

         FNAME=SYS(1:LSYS) // '.INP'
         WRITE(*,'(A,A)') ' FETCHZ> READING COORDINATES FROM FILE ',FNAME
         OPEN(UNIT=7,FILE=FNAME,STATUS='OLD')
         READX3: DO
            READ(7,'(A21)') WW
            WW=ADJUSTL(WW)
            CALL UPPERCASE(WW)
            IF (WW(1:6).EQ.'&COORD') THEN
               READ(7,'(A21)') WW 
               WW=ADJUSTL(WW)
               CALL UPPERCASE(WW)
               IF (WW(1:6).EQ.'SCALED') THEN 
                  IF (WW(1:14).EQ.'SCALED .FALSE.') THEN ! NO CONVERSION NEEDED
                     AMAT(1:3,1:3)=0.0D0; AINV(1:3,1:3)=0.0D0
                     AMAT(1,1)=1.0D0;AMAT(2,2)=1.0D0;AMAT(3,3)=1.0D0
                     AINV(1,1)=1.0D0;AINV(2,2)=1.0D0;AINV(3,3)=1.0D0
                  ENDIF
               ENDIF
               DO J1=1,NATOMS
                  READ(7,*) ZSYM(J1),Q(3*(J1-1)+1),Q(3*(J1-1)+2),Q(3*(J1-1)+3)
C                 PRINT *,ZSYM(J1),Q(3*(J1-1)+1),Q(3*(J1-1)+2),Q(3*(J1-1)+3)
                  TEMPX=AMAT(1,1)*Q(3*(J1-1)+1)+AMAT(1,2)*Q(3*(J1-1)+2)+AMAT(1,3)*Q(3*(J1-1)+3)
                  TEMPY=AMAT(2,1)*Q(3*(J1-1)+1)+AMAT(2,2)*Q(3*(J1-1)+2)+AMAT(2,3)*Q(3*(J1-1)+3)
                  TEMPZ=AMAT(3,1)*Q(3*(J1-1)+1)+AMAT(3,2)*Q(3*(J1-1)+2)+AMAT(3,3)*Q(3*(J1-1)+3)
                  Q(3*(J1-1)+1)=TEMPX
                  Q(3*(J1-1)+2)=TEMPY
                  Q(3*(J1-1)+3)=TEMPZ
               ENDDO
               EXIT READX3
            ENDIF
         ENDDO READX3
         CLOSE(7)

         NOPT=3*NATOMS
C        WRITE(*,'(A)') 'THE ABSOLUTE COORDINATES FROM FETCHZ'
C        WRITE(*,'(6F15.5)') (Q(J1),J1=1,NOPT)

         IF (TWOENDS.OR.CONNECTT.OR.NEBT.OR.NEWNEBT.OR.DRAGT.OR.GUESSPATHT
     $     .OR.MECCANOT.OR.MORPHT.OR.GREATCIRCLET.OR.GROWSTRINGT.OR.BHINTERPT.OR.BISECTT) THEN
            OPEN (UNIT=7,FILE=FINSTRING,STATUS='OLD') 
            DO J1=1,NATOMS
               READ(7,*) FIN(3*(J1-1)+1),FIN(3*(J1-1)+2),FIN(3*(J1-1)+3)
            ENDDO
            CLOSE(7)
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> COORDINATES OF SECOND POINT READ FROM FILE FINISH'
         ENDIF
C        PRINT*,' FETCHZ> COORDINATES:'
C        WRITE(*,'(3F20.10)') (Q(J1),J1=1,3*NATOMS)

      ELSE IF (CPMD) THEN
         FNAME=SYS(1:LSYS)
         WRITE(*,'(A,A)') ' FETCHZ> READING COORDINATES FROM FILE ',FNAME
         OPEN(UNIT=7,FILE=FNAME,STATUS='OLD')
         LNATOMS=0
11       READ(7,'(A)') FNAME
         IF (FNAME(1:6).EQ.'&ATOMS') THEN
            J1=0
12          READ(7,'(A)') TSTRING
            IF (TSTRING(1:1).EQ.'*') THEN
               J1=J1+1
               READ(7,'(A)') FNAME
               READ(7,*) NTYPE(J1)
               DO J2=1,NTYPE(J1)
                  IATNUM(LNATOMS+J2)=1
C                 ZSYM(LNATOMS+J2)=TSTRING(2:3)
                  ZSYM(LNATOMS+J2)='CP'
                  READ(7,*) Q(3*(LNATOMS+J2-1)+1),Q(3*(LNATOMS+J2-1)+2),Q(3*(LNATOMS+J2-1)+3)
               ENDDO
               LNATOMS=LNATOMS+NTYPE(J1)
               GOTO 12
            ELSE IF (TSTRING(1:1).EQ.' ') THEN
               GOTO 12
            ELSE IF (TSTRING(1:4).EQ.'&END') THEN
               GOTO 13
            ENDIF
         ELSE
            GOTO 11
         ENDIF
         IF (PARALLEL) WRITE(*,'(3A)') ' FETCHZ> AUXILLIARY PROGRAM WILL BE RUN ON ' // NPROC // ' PROCESSORS'

13       CONTINUE
         CLOSE(7)

         NOPT=3*NATOMS
         CALL SYSTEM(' GREP -C ANGSTROM ' // SYS(1:LSYS) // ' > TEMP')
         OPEN(UNIT=7,FILE='TEMP',STATUS='OLD')
         READ(7,*) J1
         CLOSE(7)
         IF (J1.EQ.1) THEN
            WRITE(*,'(A)') ' FETCHZ> CONVERTING INITIAL COORDINATES FROM ANGSTROM TO BOHR'
            DO J1=1,NOPT
               Q(J1)=Q(J1)*1.889726164D0
            ENDDO
         ENDIF
         IF (TWOENDS.OR.CONNECTT.OR.NEBT.OR.NEWNEBT.OR.DRAGT.OR.GUESSPATHT
     $     .OR.MECCANOT.OR.MORPHT.OR.GREATCIRCLET.OR.GROWSTRINGT.OR.BHINTERPT.OR.BISECTT) THEN
            OPEN (UNIT=7,FILE=FINSTRING,STATUS='OLD') 
            DO J1=1,NATOMS
               READ(7,*) FIN(3*(J1-1)+1),FIN(3*(J1-1)+2),FIN(3*(J1-1)+3)
            ENDDO
            CLOSE(7)
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> COORDINATES OF SECOND POINT READ FROM FILE FINISH'
         ENDIF
C        PRINT*,'COORDINATES:'
C        WRITE(*,'(3F20.10)') (Q(J1),J1=1,3*NATOMS)
      ELSE IF (VARIABLES) THEN
         NATOMS=0
100      CALL INPUT(END)
         IF (.NOT.END) THEN
            NATOMS=NATOMS+1
            CALL READF(Q(NATOMS))
            GOTO 100
         ENDIF
         NOPT=NATOMS
         WRITE(*,'(A,I4,A,I4)') ' FETCHZ> ',NOPT,' VARIABLES WILL BE OPTIMISED, NUMBER OF ZERO EIGENVALUES=',NZERO
         WRITE(*,'(A,G20.10)') ' FETCHZ> COUPLING PARAMETER=',PARAM1 ! DJW FOR MICHAEL KASTNER POTENTIAL
         IF (TWOENDS.OR.CONNECTT.OR.NEBT.OR.NEWNEBT.OR.DRAGT.OR.GUESSPATHT
     $     .OR.MECCANOT.OR.MORPHT.OR.GREATCIRCLET.OR.GROWSTRINGT.OR.BHINTERPT.OR.BISECTT) THEN
            OPEN (UNIT=7,FILE=FINSTRING,STATUS='OLD') 
            IF (VARIABLES) THEN
               READ(7,*) (FIN(J1),J1=1,NOPT)
               PRINT'(A)',' FETCHZ> FINISH VARIABLES:'
               WRITE(*,'(6G20.10)') (FIN(J1),J1=1,NOPT)
            ELSE
               DO J1=1,NATOMS
                  READ(7,*) FIN(3*(J1-1)+1),FIN(3*(J1-1)+2),FIN(3*(J1-1)+3)
               ENDDO
            ENDIF
            CLOSE(7)
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> COORDINATES OF SECOND POINT READ FROM FILE FINISH'
         ENDIF
      ELSE 
C
C  CONTINUE READING COORDINATES FROM ODATA FILE. THIS IS THE DEFAULT.
C
         LNATOMS=0
300      CALL INPUT(END)
         IF (.NOT.END) THEN
            IF (LNATOMS+1.GT.NATOMS) THEN
               PRINT*,'ERROR CHECK FOR BLANK LINE IN ODATA: LNATOMS,NATOMS=',LNATOMS,NATOMS
               CALL FLUSH(6,ISTAT)
               STOP
            ENDIF
            J=3*LNATOMS
            CALL READA(ZSYM(LNATOMS+1))
            IF ((LNATOMS.EQ.0).AND.(ZSYM(1).EQ.'CK')) ALLOCATE (CHARGE(NATOMS))
            IF (ZSYM(LNATOMS+1)(1:2).EQ.'  ') GOTO 300
            CALL UPPERCASE(ZSYM(LNATOMS+1))
            CALL READF(Q(J+1))
            CALL READF(Q(J+2))
            CALL READF(Q(J+3))
            LNATOMS=LNATOMS+1
            IF (ZSYM(1).EQ.'CK') THEN
               CHARGE(LNATOMS)=Q(J+3)  ! SAVE CHARGE FOR CK IONS
               Q(J+3)=0.0D0
C              PRINT*,'LNATOMS,CHARGE,Q=',LNATOMS,CHARGE(LNATOMS),Q(J+3)
            ENDIF
            GOTO 300
         ENDIF
         CLOSE(5)

!        IF (DEBUG) THEN
!           PRINT '(A)',' FETCHZ> COORDINATES:'
!           PRINT '(3F20.10)',Q(1:3*NATOMS)
!        ENDIF
         IF (QSPCFWT) THEN
            WRITE(*,'(3(A,I6))') ' SYSTEM ',NATOMS/3,' QSPCFW FLEXIBLE WATER MOLECULES'
         ENDIF
         IF (QTIP4PFT) THEN
            WRITE(*,'(3(A,I6))') ' SYSTEM ',NATOMS/3,' QTIP4PF FLEXIBLE WATER MOLECULES'
         ENDIF
         IF (SDT) THEN
            WRITE(*,'(3(A,I6))') ' SYSTEM STILLINGER-DAVID POTENTIAL FOR ',
     &         SDOXYGEN,' OXYGEN AND ',SDHYDROGEN,' HYDROGEN ATOMS; CHARGE=',SDCHARGE
            IF (SDHYDROGEN-2*SDOXYGEN.NE.SDCHARGE) THEN
               PRINT '(A)',' FETCHZ> ERROR IN STILLINGER-DAVID INITIALIZATION'
               STOP
            END IF
            CALL SDINIT(SDOXYGEN,SDCHARGE)
C
C  PATHSAMPLE WILL SET THE ATOM TYPE TO SD. TO GET THE RIGHT MASSES
C  CHANGE TO O AND H NOW.
C
            DO J1=1,SDOXYGEN
               ZSYM(J1)='O '
            ENDDO
            DO J1=SDOXYGEN+1,SDOXYGEN+SDHYDROGEN
               ZSYM(J1)='H '
            ENDDO
         ENDIF
       !  IF (BOWMANT) THEN
            !WRITE(*,'(A,I1,A,I0,A)') ' SYSTEM BOWMAN''S PES#',BOWMANPES,' FOR A CLUSTER OF ',NATOMS/3,' WATER MOLECULES'
            !CALL BOWMANINIT(NATOMS/3, BOWMANPES, TRIM(BOWMANDIR))
            !DO J1=1,2*NATOMS/3
               !ZSYM(J1)='H '
            !ENDDO
            !DO J1=2*NATOMS/3+1,NATOMS
               !ZSYM(J1)='O '
            !ENDDO
         !ENDIF
C 
C  DIRTY TRICK TO TRY AND RUN THOMSON PROBLEM AS NATOMS/3 *2 EFFECTIVE ATOMS
C  USING ANGULAR COORDINATES INSTEAD OF XYZ.
C
         IF (ZSYM(NATOMS).EQ.'TH') THEN
            IF ((NATOMS/3)*1.0D0.NE.(NATOMS*1.0D0/3)) THEN
               PRINT '(A)',' FETCHZ> ERROR, THE NUMBER OF ATOMS NEEDS TO BE DIVISIBLE BY 3 FOR THOMSON FUDGE'
               CALL FLUSH(6,ISTAT)
               STOP
            ENDIF
            DO J1=1,NATOMS
               DIST=SQRT(Q(3*(J1-1)+1)**2+Q(3*(J1-1)+2)**2+Q(3*(J1-1)+3)**2)
               Q(3*(J1-1)+1)=Q(3*(J1-1)+1)/DIST
               Q(3*(J1-1)+2)=Q(3*(J1-1)+2)/DIST
               Q(3*(J1-1)+3)=Q(3*(J1-1)+3)/DIST
               THTEMP(2*(J1-1)+1)=ACOS(Q(3*(J1-1)+3))
               IF (ABS(Q(3*(J1-1)+3)-COS(THTEMP(2*(J1-1)+1))).GT.1.0D-10) THEN
                  PRINT '(A)','INCONSISTENT CONVERSION FOR Z'
                  CALL FLUSH(6,ISTAT)
                  STOP
               ENDIF
               IF (Q(3*(J1-1)+1).EQ.0.0D0) THEN
                  IF (Q(3*(J1-1)+2).GT.0.0D0) THEN
                     THTEMP(2*(J1-1)+2)=HALFPI
                  ELSE 
                     THTEMP(2*(J1-1)+2)=-HALFPI
                  ENDIF
               ELSE IF (Q(3*(J1-1)+2).EQ.0.0D0) THEN
                  IF (Q(3*(J1-1)+1).GT.0.0D0) THEN
                     THTEMP(2*(J1-1)+2)=0.0D0
                  ELSE
                     THTEMP(2*(J1-1)+2)=2*HALFPI
                  ENDIF
               ELSE
                  THTEMP(2*(J1-1)+2)=ATAN(Q(3*(J1-1)+2)/Q(3*(J1-1)+1))
               ENDIF
               IF (ABS(Q(3*(J1-1)+1)-SIN(THTEMP(2*(J1-1)+1))*COS(THTEMP(2*(J1-1)+2))).GT.1.0D-5) THEN
                  THTEMP(2*(J1-1)+2)=THTEMP(2*(J1-1)+2)+2*HALFPI
                  IF (ABS(Q(3*(J1-1)+1)-SIN(THTEMP(2*(J1-1)+1))*COS(THTEMP(2*(J1-1)+2))).GT.1.0D-5) THEN
                     PRINT '(A)','INCONSISTENT CONVERSION FOR X'
                     CALL FLUSH(6,ISTAT)
                     STOP
                  ENDIF
               ENDIF
               IF (ABS(Q(3*(J1-1)+2)-SIN(THTEMP(2*(J1-1)+1))*SIN(THTEMP(2*(J1-1)+2))).GT.1.0D-5) THEN
                  THTEMP(2*(J1-1)+2)=-THTEMP(2*(J1-1)+2)
                  IF (ABS(Q(3*(J1-1)+2)-SIN(THTEMP(2*(J1-1)+1))*SIN(THTEMP(2*(J1-1)+2))).GT.1.0D-5) THEN
                     PRINT '(A)','INCONSISTENT CONVERSION FOR Y'
                     PRINT '(A,3G20.10)','X,Y,Z:      ',Q(3*(J1-1)+1),Q(3*(J1-1)+2),Q(3*(J1-1)+3)
                     PRINT '(A,3G20.10)','THETA,PHI: ',THTEMP(2*(J1-1)+1),THTEMP(2*(J1-1)+2)
                     PRINT '(A,3G20.10)','X,Y,Z CALC: ',SIN(THTEMP(2*(J1-1)+1))*COS(THTEMP(2*(J1-1)+2)),
     &                                                  SIN(THTEMP(2*(J1-1)+1))*SIN(THTEMP(2*(J1-1)+2)),
     &                                                  COS(THTEMP(2*(J1-1)+1))
                     CALL FLUSH(6,ISTAT)
                     STOP
                  ENDIF
               ENDIF
            ENDDO
            NATOMS=(NATOMS/3)*2 ! THE GREAT BIG FUDGE
            LNATOMS=NATOMS
            Q(1:3*NATOMS)=THTEMP(1:3*NATOMS) ! COORDINATES SAVED AS THETA, PHI
            PRINT '(A,I6)',' FETCHZ> NUMBER OF ATOMS CHANGED FOR THE THOMSON PROBLEM TO ',NATOMS
         ENDIF

         IF (MACHINE) THEN
             CALL READINPFILE(Q)
         ENDIF

         IF (ZSYM(NATOMS)(1:1).EQ.'W') THEN
            RIGIDBODY=.TRUE.
C            OPEN(UNIT=18,FILE='EULER',STATUS='OLD')   !   WCOMMENT
C            READ(18,*) (Q(3*LNATOMS+J1),J1=1,3*LNATOMS)
C            CLOSE(18)
         ENDIF

         IF (TWOENDS.OR.CONNECTT.OR.NEBT.OR.NEWNEBT.OR.DRAGT.OR.GUESSPATHT
     $     .OR.MECCANOT.OR.MORPHT.OR.GREATCIRCLET.OR.GROWSTRINGT.OR.BHINTERPT.OR.BISECTT) THEN
            OPEN (UNIT=7,FILE=FINSTRING,STATUS='OLD') 
            DO J1=1,LNATOMS
               READ(7,*) FIN(3*(J1-1)+1),FIN(3*(J1-1)+2),FIN(3*(J1-1)+3)
            ENDDO
            CLOSE(7)
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> COORDINATES OF SECOND POINT READ FROM FILE FINISH'
C           IF (ZSYM(1)(1:1).EQ.'W') THEN   !  WCOMMENT
C              OPEN (UNIT=7,FILE='EULER.FINISH',STATUS='OLD')
C              DO J1=1,LNATOMS
C                 READ(7,*) FIN(3*LNATOMS+3*(J1-1)+1),FIN(3*LNATOMS+3*(J1-1)+2),FIN(3*LNATOMS+3*(J1-1)+3)
C              ENDDO
C              CLOSE(7)
C              WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> EULER ANGLES OF SECOND POINT READ FROM FILE FINISH'
C           ENDIF
         ENDIF

         IF (LNATOMS.NE.NATOMS) THEN
            PRINT*,'ERROR CHECK FOR BLANK LINE IN ODATA: LNATOMS,NATOMS=',LNATOMS,NATOMS
         ENDIF
         NOPT=3*NATOMS
         IF (NTAG.GT.0) THEN
            PRINT '(A,I6,A)',' FETCHZ> ',NTAG,' TAGGED ATOMS AND MASS FACTORS:'
            PRINT '(I6,F12.2)',(TAGNUM(J1),TAGFAC(TAGNUM(J1)),J1=1,NTAG)
         ENDIF
         IF (ZSYM(NATOMS).EQ.'IN') THEN
            WRITE(*,'(A,I4,A,I4,A)') 
     1        ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' SHIELDED BORN-MEYER IONS'
            WRITE(*,'(A,F12.8,A,I2,A,F12.8,A,F12.8,A,F12.8,A,F12.8)') 
     1         ' FETCHZ> GAMMA=',PARAM1,' CHARGE=',INT(PARAM2),' RHO=',PARAM3,' A++=',PARAM4,' A--=',PARAM5,' A+-=',PARAM6
         ELSE IF (ZSYM(1).EQ.'CA') THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' CA+AR ATOMS'
         ELSE IF (ZSYM(1).EQ.'LM') THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,
     1              ' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ONE ION + ',NATOMS,' INERT GAS ATOMS'
            WRITE(*,'(A,3G12.4)') ' FETCHZ> MASON-SCHAMP POTENTIAL WITH EPSILON, RM, GAMMA=',PARAM1,PARAM2,PARAM3
         ELSE IF (ZSYM(NATOMS).EQ.'AR') THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' LENNARD-JONES ATOMS'
            WRITE(*,'(A)') ' FETCHZ> COORDINATES WILL BE SCALED (DIVIDED) BY 3.4 BEFORE AFTER INPUT'
         ELSE IF (WELCH) THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' WELCH IONS'
            WRITE(*,'(A,F12.8,A,F12.8,A,F12.8,A,F12.8)') ' FETCHZ> A++=',APP,' A--=',AMM,' A+-=',APM,' RHO=',RHO
            WRITE(*,'(A,F12.8,A,F12.8,A,F12.8,A,F12.8)') ' FETCHZ> Q+=',XQP,' Q-=',XQM,' ALPHA+=',ALPHAP,' ALPHA-=',ALPHAM
         ELSE IF (ZSYM(NATOMS).EQ.'SY') THEN
            WRITE(*,'(A,I4,A,F15.5,A,F15.5)') ' FETCHZ> ',(NATOMS/2),' STOCKMAYER ATOMS WITH MU=',
     &                                            STOCKMU,' AND LAMBDA=',STOCKLAMBDA
         ELSE IF (ZSYM(NATOMS).EQ.'CD') THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' RIGID BODY COORDINATES WILL BE OPTIMISED FOR ',NATOMS/2,' CAPSID PENTAMERS'
            WRITE(*,'(4(A,F12.8))') ' FETCHZ> MORSE RHO=',CAPSRHO,' REPULSIVE SITE EPSILON=',
     1                                     EPS2,' PENTAMER RADIUS=',RAD,' HEIGHT=',HEIGHT
         ELSE IF (TOSI) THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' TOSI-FUMI IONS'
            WRITE(*,'(4(A,F12.8))') ' FETCHZ> A++=',PARAM1,' A--=',PARAM2,' A+-=',PARAM3,' RHO=',PARAM4
            IF (TOSIC6) THEN
               WRITE(*,'(A)') ' FETCHZ> C6 COEFFICIENTS: '
               WRITE(*,'(A,F12.8,A,F12.8,A,F12.8)') ' FETCHZ> C6++=',C6PP,' C6--=',C6MM,' C6+-=',C6PM
            ENDIF
            IF (TOSIPOL) THEN
               WRITE(*,'(A)') ' FETCHZ> POLARIZABILITIES:'
               WRITE(*,'(A,F12.8,A,F12.8)') ' FETCHZ> ALPHA+=',ALPHAP,' ALPHA-=',ALPHAM
               WRITE(*,'(A,F12.8,A)') ' FETCHZ> DAMPING COEFFICENT=',DAMP,' PER BOHR'
            ENDIF
         ELSE IF (ZSYM(NATOMS).EQ.'AZ') THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' AZIZ AR ATOMS'
            IF (PARAM1.NE.0.0D0) THEN
               WRITE(*,'(A,F12.8)') ' FETCHZ> AXILROD-TELLER POTENTIAL WILL BE ADDED WITH Z*=',PARAM1
            ENDIF
         ELSE IF (ZSYM(NATOMS).EQ.'DZ') THEN
            WRITE(*,'(A,I4,A,I4,A)') 
     1        ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' DZUGUTOV ATOMS'
            WRITE(*,'(A,F12.8,A,F12.8,A,F12.8,A,F12.8,A,F12.8,A,F12.8,A,F12.8)') 
     1         ' FETCHZ> M=',PARAM1,' A=',PARAM2,' C=',PARAM3,' AA=',PARAM4,' B=',PARAM5,' D=',PARAM6,' BB=',PARAM7
         ELSE IF (ZSYM(NATOMS).EQ.'AX') THEN
            WRITE(*,'(A,I4,A,I4,A)') 
     1        ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' LENNARD-JONES+AXILROD-TELLER ATOMS'
            WRITE(*,'(A,F12.8)') ' FETCHZ> AXILROD-TELLER Z*=',PARAM1
         ELSE IF (NATBT) THEN
            WRITE(*,'(A,I4,A,I4,A)') 
     1        ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' TB NA ATOMS'
         ELSE IF (ZSYM(NATOMS).EQ.'SW') THEN
            WRITE(*,'(A,I4,A,I4,A)') 
     1        ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' STILLINGER-WEBER SI ATOMS'
            WRITE(*,'(A,F15.8,A,F15.8,A,F15.8)') ' FETCHZ> BOX LENGTHS: X ',PARAM1,', Y ',PARAM2,', Z ',PARAM3
         ELSE IF (ZSYM(NATOMS).EQ.'SM') THEN
            WRITE(*,'(A,I4,A,I4,A)') 
     1        ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' STILLINGER-WEBER SI ATOMS'
            WRITE(*,'(A)') ' WITH THE THREE-BODY TERM MULTIPLIED BY 1.5'
            WRITE(*,'(A,F15.8,A,F15.8,A,F15.8)') ' FETCHZ> BOX LENGTHS: X ',PARAM1,', Y ',PARAM2,', Z ',PARAM3
         ELSE IF (ZSYM(NATOMS).EQ.'SI') THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' MURRELL SI POTENTIAL'
         ELSE IF (ZSYM(NATOMS).EQ.'JC') THEN
            WRITE(*,'(A,I4,A,I4,A)') 
     1        ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' GENERAL MURRELL POTENTIAL'
         ELSE IF (ZSYM(NATOMS).EQ.'CC') THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' MURRELL C POTENTIAL'
         ELSE IF (ZSYM(NATOMS).EQ.'JM') THEN
            WRITE(*,'(A,I4,A,I4,A)') 
     1        ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' GENERAL MURRELL POTENTIAL'
            WRITE(*,'(A,F15.8,A,F15.8,A,F15.8,A,F15.8)') 
     1        ' FETCHZ> BOX LENGTHS: X ',PARAM1,', Y ',PARAM2,', Z ',PARAM3,', CUTOFF ',PARAM4
         ELSE IF (ZSYM(NATOMS).EQ.'M') THEN
            WRITE(*,'(A,I4,A,I4,A,F12.4)') 
     1        ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' MORSE ATOMS, RHO=',PARAM1
         ELSE IF (ZSYM(NATOMS).EQ.'TT') THEN
            WRITE(*,'(A,I4,A,I4,A)') 
     1       ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' MENON AND SUBASWAMY APRIL 1997 PRB SI ATOMS'
            WRITE(*,'(A,F15.8,A,F15.8,A,F15.8,A,F15.8)') 
     1       ' FETCHZ> BOX LENGTHS: X ',PARAM1,', Y ',PARAM2,', Z ',PARAM3,', CUTOFF (FRACTIONAL) ',PARAM4
         ELSE IF (ZSYM(NATOMS).EQ.'LP') THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' LENNARD-JONES ATOMS'
            WRITE(*,'(A,F15.8,A,F15.8,A,F15.8,A,F15.8)') 
     1       ' FETCHZ> BOX LENGTHS: X ',PARAM1,', Y ',PARAM2,', Z ',PARAM3,', CUTOFF (FRACTIONAL) ',PARAM4
            IF (BINARY) WRITE(*,'(A,I4,A,I4,A,F11.5,A,F11.5,A,F11.5,A,F11.5)') 
     1         ' FETCHZ> BINARY MIXTURE: ',NTYPEA,' A ATOMS,',NATOMS-NTYPEA,' B ATOMS, EPS(AB)=',EPSAB,' EPS(BB)=',EPSBB,
     2         ' SIGMA(AB)=',SIGAB,' SIGMA(BB)=',SIGBB
         ELSE IF ((ZSYM(NATOMS).EQ.'LS').OR.(ZSYM(NATOMS).EQ.'BC')) THEN
!
! BINARY COULD BE TRUE OR FALSE FOR ATOM TYPE 'LS'. FOR ATOM TYPE 'BC'
! IT SHOULD HAVE BEEN SET TRUE USING THE CORRESPONDING KEYWORD IN ODATA
!
            IF ((ZSYM(NATOMS).EQ.'BC').AND.(.NOT.BINARY)) THEN
               PRINT '(A)',' FETCHZ> ERROR - ATOM TYPE BC REQUIRES THE BINARY KEYWORD IN ODATA'
               CALL FLUSH(6,ISTAT)
               STOP
            ENDIF
            WRITE(*,'(A,I4,A,I4,A)') 
     1        ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' SHIFTED, TRUNCATED LENNARD-JONES ATOMS'
            WRITE(*,'(A,F15.8,A,F15.8,A,F15.8,A,F15.8)') 
     1        ' FETCHZ> BOX LENGTHS: X ',PARAM1,', Y ',PARAM2,', Z ',PARAM3,', CUTOFF (FRACTIONAL) ',PARAM4
            IF (BINARY) WRITE(*,'(A,I4,A,I4,A,F11.5,A,F11.5,A,F11.5,A,F11.5)') 
     1         ' FETCHZ> BINARY MIXTURE: ',NTYPEA,' A ATOMS,',NATOMS-NTYPEA,' B ATOMS, EPS(AB)=',EPSAB,' EPS(BB)=',EPSBB,
     2         ' SIGMA(AB)=',SIGAB,' SIGMA(AB)=',SIGBB
         ELSE IF (ZSYM(NATOMS).EQ.'LK') THEN
            WRITE(*,'(A,I4,A,I4,A)') 
     1        ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' KOB/SCIORTINO LENNARD-JONES ATOMS'
            WRITE(*,'(A,F15.8,A,F15.8,A,F15.8,A,F15.8)') 
     1        ' FETCHZ> BOX LENGTHS: X ',PARAM1,', Y ',PARAM2,', Z ',PARAM3,', CUTOFF (FRACTIONAL) ',PARAM4
            IF (BINARY) WRITE(*,'(A,I4,A,I4,A,F11.5,A,F11.5,A,F11.5,A,F11.5)') 
     1         ' FETCHZ> BINARY MIXTURE: ',NTYPEA,' A ATOMS,',NATOMS-NTYPEA,' B ATOMS, EPS(AB)=',EPSAB,' EPS(BB)=',EPSBB,
     2         ' SIGMA(AB)=',SIGAB,' SIGMA(AB)=',SIGBB
         ELSE IF (ZSYM(NATOMS).EQ.'LC') THEN
            WRITE(*,'(A,I4,A,I4,A)') 
     1        ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' SHIFTED, TRUNCATED LENNARD-JONES ATOMS'
            WRITE(*,'(A,F15.8,A,F15.8,A,F15.8,A,F15.8)') 
     1        ' FETCHZ> BOX LENGTHS: X ',PARAM1,', Y ',PARAM2,', Z ',PARAM3,', CUTOFF (FRACTIONAL) ',PARAM4
            IF (BINARY) WRITE(*,'(A,I4,A,I4,A,F11.5,A,F11.5,A,F11.5,A,F11.5)') 
     1         ' FETCHZ> BINARY MIXTURE: ',NTYPEA,' A ATOMS,',NATOMS-NTYPEA,' B ATOMS, EPS(AB)=',EPSAB,' EPS(BB)=',EPSBB,
     2         ' SIGMA(AB)=',SIGAB,' SIGMA(AB)=',SIGBB
         ELSE IF (ZSYM(NATOMS).EQ.'MP') THEN
            WRITE(*,'(A,I4,A,I4,A,F12.4)') 
     1       ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' MORSE ATOMS, RHO=',PARAM1
            WRITE(*,'(A,F15.8,A,F15.8,A,F15.8,A,F15.8)') 
     1       ' FETCHZ> BOX LENGTHS: X ',PARAM2,', Y ',PARAM3,', Z ',PARAM4,', CUTOFF (FRACTIONAL) ',PARAM5
         ELSE IF (ZSYM(NATOMS).EQ.'DS') THEN
            WRITE(*,'(A,I4,A,I4,A,F12.4)') 
     1       ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' MORSE ATOMS, RHO=',PARAM1
            WRITE(*,'(A,F15.8,A,F15.8,A,F15.8,A,F15.8)') 
     1       ' FETCHZ> BOX LENGTHS: X ',PARAM2,', Y ',PARAM3,', Z ',PARAM4,', CUTOFF (FRACTIONAL) ',PARAM5
         ELSE IF (ZSYM(NATOMS).EQ.'GP') THEN
            WRITE(*,'(A,I6,A,I4,A,I4)') 
     1       ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' GUPTA ATOMS FOR ATOM TYPE',GUPTATYPE
         ELSE IF (ZSYM(NATOMS).EQ.'MS') THEN
            WRITE(*,'(A,I4,A,I4,A,F12.4)') 
     1       ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' MORSE ATOMS, RHO=',PARAM1
            WRITE(*,'(A,F15.8,A,F15.8,A,F15.8,A,F15.8)') 
     1       ' FETCHZ> BOX LENGTHS: X ',PARAM2,', Y ',PARAM3,', CUTOFF (FRACTIONAL) ',PARAM4
         ELSE IF (ZSYM(NATOMS).EQ.'CK') THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',2*NATOMS,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' 2D TRAPPED IONS'
         ELSE IF (EYTRAPT) THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ', 
     &                               NATOMS,' TRAPPED IONS'
            WRITE(*,'(A,G12.4,A,I4)') ' FETCHZ> WITH RADIAL POTENTIAL 0.5 * ',TRAPK,' * R**',NTRAPPOW
         ELSE IF (ZSYM(NATOMS).EQ.'BE') THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' TRAPPED IONS'
         ELSE IF ((ZSYM(NATOMS).EQ.'AU').OR.(ZSYM(NATOMS).EQ.'AG').OR.(ZSYM(NATOMS).EQ.'NI')) THEN
            IF (ZSYM(NATOMS).EQ.'AU') THEN
               WRITE(*,'(A,I4,A,I4,A)') 
     1          ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' SUTTON-CHEN AU-TYPE ATOMS'
               WRITE(*,'(A,F15.6,A,F15.6,A,F15.6)') ' FETCHZ> N=10, M=8, EPS=',PARAM1,' C=',PARAM2,' SIGMA=',PARAM3
            ELSE IF (ZSYM(NATOMS).EQ.'AG') THEN
               WRITE(*,'(A,I4,A,I4,A)') 
     1          ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' SUTTON-CHEN AG-TYPE ATOMS'
               WRITE(*,'(A,F15.6,A,F15.6,A,F15.6)') ' FETCHZ> N=12, M=6, EPS=',PARAM1,' C=',PARAM2,' SIGMA=',PARAM3
            ELSE IF (ZSYM(NATOMS).EQ.'NI') THEN
               WRITE(*,'(A,I4,A,I4,A)') 
     1          ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' SUTTON-CHEN NI-TYPE ATOMS'
               WRITE(*,'(A,F15.6,A,F15.6,A,F15.6)') ' FETCHZ> N=9, M=6, EPS=',PARAM1,' C=',PARAM2,' SIGMA=',PARAM3
            ENDIF
         ELSE IF (ZSYM(NATOMS).EQ.'PL') THEN
            WRITE(*,'(A,I4,A,I4,A)') 
     1       ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR THE 3-COLOUR 46-BEAD MODEL POLYPEPTIDE'
         ELSE IF (BLNT) THEN
            WRITE(*,'(A,I4,A,I4,A)')
     1       ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR THE GENERAL 3-COLOUR BEAD MODEL'
         ELSE IF (ZSYM(NATOMS).EQ.'GL') THEN
            WRITE(*,'(A,I4,A,I4,A)') 
     1         ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR THE GO-MODEL 3-COLOUR 46-BEAD MODEL POLYPEPTIDE'
         ELSE IF (ZSYM(NATOMS).EQ.'SC') THEN
            INQUIRE(FILE='SCPARAMS',EXIST=YESNO)
            IF (.NOT.YESNO) THEN
               NN=12
               MM=6
               EPS=2.5415D-03
               CSC=144.41
               SIG=1.414
            ELSE
               OPEN(UNIT=33,FILE='SCPARAMS',STATUS='OLD')
               READ(33,*) NN,MM,EPS,CSC,SIG
               CLOSE(33)
            ENDIF
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' SUTTON-CHEN ATOMS'
C           WRITE(*,'(A,F15.6,A,F15.6,A,F15.6)') ' FETCHZ> N=',NN,' M=',MM,' EPS=',PARAM1,' C=',PARAM2,' SIGMA=',PARAM3
            WRITE(*,'(A,F15.8,A,F15.8,A,F15.8,A,F15.8)') 
     1       ' FETCHZ> BOX LENGTHS: X ',PARAM1,', Y ',PARAM2,', Z ',PARAM3,', CUTOFF ',PARAM4
         ELSE IF (ZSYM(NATOMS).EQ.'PR') THEN
            WRITE(*,'(A,I4,A,I4,A)') 
     1       ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' PACHECO-RAMALHO C60 MOLECULES'
         ELSE IF (ZSYM(NATOMS).EQ.'C6') THEN
            WRITE(*,'(A,I4,A,I4,A)') 
     1       ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' GIRIFALCO C60 MOLECULES'
         ELSE IF ( ZSYM(NATOMS).EQ.'GOT') THEN
            WRITE(*,'(A,I4,A,I4,A)')
     1       ' SYSTEM ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' GO CALPHA SITES'
         ELSE IF (ZSYM(NATOMS).EQ.'P6') THEN
            WRITE(*,'(A,I4,A,I4,A)') 
     1       ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' GIRIFALCO C60 MOLECULES'
            WRITE(*,'(A,F15.8,A,F15.8,A,F15.8,A,F15.8)') 
     1       ' FETCHZ> BOX LENGTHS: X ',PARAM1,', Y ',PARAM2,', Z ',PARAM3,', CUTOFF ',PARAM4
         ELSE IF (ZSYM(NATOMS).EQ.'FH') THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' FENSKE-HALL ATOMS'
         ELSE IF (ZSYM(NATOMS)(1:1).EQ.'W') THEN
            IF (ZSYM(NATOMS).EQ.'W4') WRITE(*,'(A,I4,A,I4,A)') 
     2       ' FETCHZ> ',3*NATOMS,' COORDINATES WILL BE OPTIMISED FOR ',NATOMS/2,' TIP4P WATER MOLECULES'
            IF (ZSYM(NATOMS).EQ.'W3') WRITE(*,'(A,I4,A,I4,A)') 
     2       ' FETCHZ> ',3*NATOMS,' COORDINATES WILL BE OPTIMISED FOR ',NATOMS/2,' TIP3P WATER MOLECULES'
            IF (ZSYM(NATOMS).EQ.'W2') WRITE(*,'(A,I4,A,I4,A)') 
     2       ' FETCHZ> ',3*NATOMS,' COORDINATES WILL BE OPTIMISED FOR ',NATOMS/2,' TIPS2 WATER MOLECULES'
            IF (ZSYM(NATOMS).EQ.'W1') WRITE(*,'(A,I4,A,I4,A)') 
     2       ' FETCHZ> ',3*NATOMS,' COORDINATES WILL BE OPTIMISED FOR ',NATOMS/2,' TIPS1 WATER MOLECULES'
         ELSE IF (ZSYM(NATOMS).EQ.'ME') THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' MIE ATOMS'
            WRITE(*,'(A,I3,A,I3)') ' FETCHZ> N=',INT(PARAM1),' M=',INT(PARAM2)
            WRITE(*,'(A,F15.8,A,F15.8,A,F15.8,A,F15.8)') 
     1       '  SYSTEM BOX LENGTHS: X ',PARAM1,', Y ',PARAM2,', Z ',PARAM3,', CUTOFF ',PARAM4
         ELSE IF (CADPAC) THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' CADPAC ATOMS'
            WRITE(*,'(A,A,A,A)') ' FETCHZ> SYSTEM NAME: ',SYS(1:LSYS),', EDIT COMMAND: ',EDITIT
         ELSE IF (GAMESSUS) THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' GAMESS-US ATOMS'
            WRITE(*,'(A,A,A,A)') ' FETCHZ> SYSTEM NAME: ',SYS(1:LSYS),', EDIT COMMAND: ',EDITIT
         ELSE IF (GAMESSUK) THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' GAMESS-UK ATOMS'
            WRITE(*,'(A,A,A,A)') ' FETCHZ> SYSTEM NAME: ',SYS(1:LSYS),', EDIT COMMAND: ',EDITIT
         ELSE IF (GAUSSIAN) THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' GAUSSIAN ATOMS'
         ELSE IF (DFTBT) THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' TIFFANY TB ATOMS'
         ELSE IF (ZSYM(NATOMS).EQ.'SV') THEN
            WRITE(*,'(A,I4,A,I4,A)') ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' MSEVB ATOMS '

! SET SOME VALUES

            NUM_EIG = (NATOMS-1)/3
            NUM_HYD = NATOMS - NUM_EIG

! INITIALISE SOME MEMORY

            MAXNUMVBSTATES = 2

            DO J1 = 1, SHELLSTOCOUNT
               MAXNUMVBSTATES = MAXNUMVBSTATES + 4*(2**(J1-1))    ! 4 TO ACCOUNT FOR MULTIPLE PIVOT STATES
            ENDDO

! HARD LIMIT MAX NUMBER OF VB SHELLS AT THE MOMENT

            IF (MAXNUMVBSTATES.GT.1000) MAXNUMVBSTATES = 1000
         
            ALLOCATE(EACH_COULOMB(NATOMS,NATOMS), WATER_INTER_COULOMB(NATOMS,NATOMS), LJR(NATOMS,NATOMS))
            ALLOCATE(INTER_COULOMB(NATOMS,NATOMS), LJ_INTER(NATOMS,NATOMS), REPULSE_INTER(NATOMS,NATOMS))
            ALLOCATE(ATOM_COULOMB(NATOMS))

            ALLOCATE(ATMPL(MAXNUMVBSTATES,NATOMS), STATESINTERACT(MAXNUMVBSTATES,MAXNUMVBSTATES))
            ALLOCATE(ZUNDEL_SPECIES(MAXNUMVBSTATES,MAXNUMVBSTATES,7))
            ALLOCATE(ZUNDEL_F(MAXNUMVBSTATES,MAXNUMVBSTATES),ZUNDEL_G(MAXNUMVBSTATES,MAXNUMVBSTATES))

            ALLOCATE(PSIX(NATOMS), PSIY(NATOMS), PSIZ(NATOMS))
            ALLOCATE(INTERATOMICR(NATOMS,NATOMS))            
         ENDIF
         IF (CPMD) WRITE(*,'(A,I6,A,I6,A)') 
     1          ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,' CPMD ATOMS; BULK BOUNDARY CONDITIONS'
         IF (CPMDC) WRITE(*,'(A,I6,A,I6,A)')
     1          ' FETCHZ> ',NOPT,' CARTESIAN COORDINATES WILL BE OPTIMISED FOR ',NATOMS,
     1              ' CPMD ATOMS; CLUSTER BOUNDARY CONDITIONS'
         
         IF (TWOD) WRITE(*,'(A)') ' FETCHZ> TWO-DIMENSIONAL FLATLAND ENFORCED'
         IF (DOUBLET) WRITE(*,'(A,F12.5,A,F12.5,A,F12.5)') 
     1      ' FETCHZ> DOUBLE-WELL POTENTIAL BETWEEN FIRST TWO ATOMS, BARRIER=',PARAM5,
     1                               ' FIRST MINIMUM AT ',PARAM4,' SECOND AT ',PARAM4+2.0D0*PARAM6
      ENDIF
      IF (ZSYM(1)(1:1).EQ.'W') THEN ! MUST GENERALISE FOR OTHER RIGID BODIES SOMEHOW
         DEALLOCATE (IATNUM,ATMASS)
         ALLOCATE (IATNUM(3*(NATOMS/2)),ATMASS(3*(NATOMS/2)))
      ENDIF
C
C DAE ATMASS IS SET IN CHSETZSYMATMASS FOR CHARMM. PERTABLE WOULD OVERWRITE
C JMC SIMILARLY FOR UNRES IN UNRSETZSYMATMASS...
C
      IF (.NOT.(CHRMMT.OR.UNRST.OR.AMBERT.OR.NABT.OR.RINGPOLYMERT)) CALL PERTABLE
      IF (CASTEP) THEN
         INQUIRE(FILE='CASTEP.MASSES',EXIST=YESNO)
         IF (YESNO) THEN
            OPEN(UNIT=1,FILE='CASTEP.MASSES',STATUS='OLD')
            READ(1,*) (ATMASS(J1),J1=1,NATOMS)
            CLOSE(1)
            PRINT '(A)',' FETCHZ> MASSES REPLACED BY VALUES FROM CASTEP.MASSES FILE, VALUES ARE:'
            WRITE(*,'(F20.10)') (ATMASS(J1),J1=1,NATOMS)
         ENDIF
         DO J1=1,NATOMS
            DO J2=J1+1,NATOMS
               IF (ATMASS(J2).LT.ATMASS(J1)) THEN
                  PRINT '(A)',' FETCHZ> CASTEP INPUT ERROR: ATOMS MUST BE ORDERED BY ATOMIC NUMBER'
                  PRINT '(A,I6,A,G20.10)',' MASS FOR ATOM ',J2,' IS ',ATMASS(J2)
                  PRINT '(A,I6,A,G20.10)',' MASS FOR ATOM ',J1,' IS ',ATMASS(J1)
                  STOP
               ENDIF
            ENDDO
         ENDDO
      ENDIF
      DO J1=1,NOPT
         STPMAX(J1)=MXSTP
C        IF (ZSYM(NATOMS)(1:1).EQ.'W') STPMAX(J1+3*NATOMS)=MXSTP ! WCOMMENT
      ENDDO
C
C  MORE PRINTING
C
      PRINT*
      IF (TIMELIMIT.LT.HUGE(TIMELIMIT)/2)  WRITE(*,'(A,F20.1)') ' FETCHZ> TIME LIMIT (S): ',TIMELIMIT
      IF (PV.OR.PVTS) THEN
         WRITE(*,'(A,F20.10)') ' FETCHZ> BOX LENGTHS WILL BE VARIED TO GIVE A CONSTANT PRESSURE OF ',PRESS
         WRITE(*,'(A,F20.10)') ' FETCHZ> BOX LENGTH GRADIENT CONVERGENCE CRITERION ',PVCONV
         WRITE(*,'(A,G20.10)') ' FETCHZ> BOX LENGTH GRADIENT TOLERANCE FOR MULTIPLE STEPS ',PVTOL
         WRITE(*,'(A,G20.10)') ' FETCHZ> CONSTANT PRESSURE CALCULATION WILL USE USING FRACTIONAL COORDINATES'
         IF (CUBIC) WRITE(*,'(A)') ' FETCHZ> A CUBIC CELL WILL BE MAINTAINED IF INITIAL CELL IS CUBIC'
         IF (PVTS) THEN
            IF (NBOXTS.EQ.1) WRITE(*,'(A)') ' FETCHZ> SEARCHING FOR A TRANSITION STATE IN X BOX LENGTH'
            IF (NBOXTS.EQ.2) WRITE(*,'(A)') ' FETCHZ> SEARCHING FOR A TRANSITION STATE IN Y BOX LENGTH'
            IF (NBOXTS.EQ.3) WRITE(*,'(A)') ' FETCHZ> SEARCHING FOR A TRANSITION STATE IN Z BOX LENGTH'
         ENDIF
      ENDIF
      IF (FRACTIONAL) WRITE(*,'(A)') ' FETCHZ> FRACTIONAL COORDINATES TO BE USED IN BOX LENGTH OPTIMISATION AT CONSTANT PRESSURE'
      IF (REPELTST) THEN
         NREPELTS=0
         OPEN(UNIT=77,FILE='POINTS.REPEL',STATUS='OLD',ERR=10)
         DO J1=1,100
            READ(77,*,END=10) (REPELTS(J2,J1),J2=1,3*NATOMS)
            NREPELTS=NREPELTS+1
         ENDDO
10       CLOSE(77)
         WRITE(*,'(A,I5,A,F15.5)') 
     1          ' FETCHZ> SEARCH WILL BE DISPLACED FROM ',NREPELTS,' POINTS FOUND IN POINTS.REPEL, STEP=',REPELPUSH
      ENDIF
      IF (.NOT.(BFGSMINT.OR.BSMIN.OR.RKMIN)) THEN
         IF (ISTCRT.EQ.0) WRITE(*,'(A)') ' FETCHZ> SCALING STEPS ACCORDING TO THE TOTAL CARTESIAN DISPLACEMENT'
         IF (ISTCRT.EQ.1) WRITE(*,'(A)') ' FETCHZ> SCALING STEPS ACCORDING TO THE LARGEST ATOMIC CARTESIAN DISPLACEMENT'
         IF (ISTCRT.EQ.10) WRITE(*,'(A,F12.5)') ' FETCHZ> SCALING STEPS ACCORDING TO TRUST RADIUS=',TRAD
      ENDIF
      IF (FIXD) THEN
         IF (T12FAC.LE.1.0D0) THEN
            WRITE(*,'(A,F12.4)') ' FETCHZ> FIXED INITIAL UPHILL SEARCH DIRECTION, FRACTION OF FIRST COLLISION TIME USED=',T12FAC
         ELSE
            WRITE(*,'(A,F12.4)') ' FETCHZ> FIXED INITIAL UPHILL SEARCH DIRECTION, FIRST COLLIDING ATOMS WILL BE PLACED HALF WAY'
         ENDIF
      ENDIF
      IF (READV) WRITE(*,'(A)') ' FETCHZ> INITIAL EIGENVECTOR WILL BE READ FROM VECTOR.DUMP'
      IF (READSP) WRITE(*,'(A)') ' FETCHZ> STATIONARY POINT INFO WILL BE READ'
      IF (DUMPSP) WRITE(*,'(A)') ' FETCHZ> STATIONARY POINT INFO WILL BE DUMPED'
      IF (FREEZE) THEN
         WRITE(*,'(A,I6,A)') ' FETCHZ> ', NFREEZE,' ATOMS WILL BE FROZEN:'
         DO J1=1,NATOMS
            IF (FROZEN(J1)) WRITE(*,'(I6)') J1
         ENDDO
      ENDIF
      IF (NORESET) WRITE(*,'(A)') ' FETCHZ> ATOMS WILL NOT BE RETURNED TO THE PRIMARY SUPERCELL'

      IF (RTEST) THEN
         IF (JZ.NE.0.0D0) THEN 
            WRITE(*,'(A,F12.4)') ' FETCHZ> ADDING CENTRIFUGAL POTENTIAL FOR ANGULAR MOMENTUM JZ=',JZ
         ELSE
            WRITE(*,'(A,F12.4)') ' FETCHZ> ADDING CENTRIFUGAL POTENTIAL FOR ANGULAR VELOCITY OMEGA=',OMEGA
         ENDIF
      ENDIF

      IF ((INR.EQ.2).AND.(HINDEX.NE.1)) THEN
         WRITE(*,'(A,I4)') ' FETCHZ> SEARCHING FOR A SADDLE WITH HESSIAN INDEX=',HINDEX
      ENDIF
      IF ((INR.EQ.2).AND.(KEEPINDEX)) THEN
         WRITE(*,'(A)') ' FETCHZ> SEARCHING FOR A SADDLE WITH HESSIAN INDEX DETERMINED BY STARTING POINT'
      ENDIF
   
      IF (NOIT) THEN
         WRITE(*,'(A,I3,A)') ' FETCHZ> LOWEST ',HINDEX,' EIGENVALUES AND EIGENVECTORS WILL BE CALCULATED NON-ITERATIVELY'
      ENDIF
      IF (FIELDT) THEN
         WRITE(*,'(A,F12.4)') 'SETTINGS ADDING CENTRIFUGAL POTENTIAL FOR JZ=',JZ
         IF (D5HT) WRITE(*,'(A,F12.4)') ' FETCHZ> ADDING D5H SYMMETRY FIELD STRENGTH=',FD5H
         IF (OHT) WRITE(*,'(A,F12.4)') ' FETCHZ> ADDING D5H SYMMETRY FIELD STRENGTH=',FOH
         IF (IHT) WRITE(*,'(A,F12.4)') ' FETCHZ> ADDING D5H SYMMETRY FIELD STRENGTH=',FIH
         IF (TDT) WRITE(*,'(A,F12.4)') ' FETCHZ> ADDING D5H SYMMETRY FIELD STRENGTH=',FTD
      ENDIF

      IF (ADMT) WRITE(*,'(A,I4,A)') ' FETCHZ> DISTANCE MATRIX WILL BE PRINTED EVERY ',NADM,' CYCLES'
      IF (.NOT.BULKT) THEN
         WRITE(*,'(A,F15.8,A,I3)') 
     1  ' FETCHZ> POINT GROUP CHECKED WHEN RMS FORCE <',SYMCUT,', HIGHEST SYMMETRY AXIS TESTED FOR=',NHCHECK
         WRITE(*,'(A,2F15.8)') ' FETCHZ> INITIAL DISTANCE AND EIGENVALUE TOLERANCES IN SYMMETRY DETERMINATION=',TOLD,TOLE
      ENDIF
      WRITE(*,'(A,I6)') ' FETCHZ> MINIMUM NUMBER OF OPTIMIZATION STEPS=',NSTEPMIN
      IF (NEBT) THEN
          WRITE(*,'(A,I5,A,I5,A,F12.5)') ' FETCHZ> NEB PARAMETERS: ',NIMAGE,
     1          ' IMAGES, A MAXIMUM OF ',NSTEPNEB,' STEPS, AND RMS CONVERGENCE CRITERION ',RMSNEB
      ENDIF
      IF (NEBRESEEDT)  THEN
         WRITE(*,'(A,I5,A)') ' FETCHZ> DNEB IMAGES WILL BE RESEEDED EVERY ',NEBRESEEDINT,' STEPS'
         WRITE(*,'(A,G20.10)') '         FOR ENERGIES EXCEEDING ',NEBRESEEDEMAX
         WRITE(*,'(A,G20.10)') '         OR ENERGY ABOVE HIGHEST END POINT EXCEEDS ',NEBRESEEDBMAX
         WRITE(*,'(A,G20.10,I6)') '         FACTOR AND POWER PARAMETERS FOR REPULSIVE SITES A: ',NEBRESEEDDEL1,NEBRESEEDPOW1
         WRITE(*,'(A,G20.10,I6)') '         FACTOR AND POWER PARAMETERS FOR REPULSIVE SITES B: ',NEBRESEEDDEL2,NEBRESEEDPOW2
      ENDIF
      IF (INTLJT) THEN
         PRINT '(A,F15.5)',   ' FETCHZ> USING INTERPLJ POTENTIAL FOR INITIAL INTERPOLATION IN EACH CYCLE'
         PRINT '(A,I8)',      '         MAXIMUM OPTIMIZATION STEPS FOR INTERPLJ POTENTIAL=',INTLJSTEPS
         PRINT '(A,I8)',      '         NUMBER OF INTERMEDIATE IMAGES FOR INTERPLJ POTENTIAL=',INTIMAGE
         PRINT '(A,F15.5)',   '         RMS GRADIENT PER IMAGE TOLERANCE FOR CONSTRAINED POTENTIAL=',INTLJTOL
         PRINT '(A,F20.10)',  '         MINIMUM DISTANCE DIFFERENCE FOR INTERNAL MINIMUM=',INTLJDEL
         PRINT '(A,F20.10)',  '         MULTIPLYING FACTOR FOR INTERNAL MINIMUM PENALTY FUNCTION=',INTLJEPS
      ENDIF
      IF (INTCONSTRAINTT) THEN
         PRINT '(A,F15.5)',   ' FETCHZ> USING CONSTRAINT POTENTIAL FOR INITIAL INTERPOLATION IN EACH CYCLE'
         PRINT '(A,F15.5)',   '         WITH ABSOLUTE DISTANCE CHANGE TOLERANCE ',INTCONSTRAINTTOL
         PRINT '(A,F15.5)',   '         CONSTRAINT SPRING CONSTANT=',INTCONSTRAINTDEL
         PRINT '(2(A,F15.5))','         REPULSION FACTOR BETWEEN UNCONSTRAINED ATOMS=',INTCONSTRAINTREP 
         PRINT '(A,F15.5)',   '         CUTOFF FOR REPULSION WILL BE THE MINIMUM OF ',INTCONSTRAINREPCUT
         PRINT '(A)',         '         AND THE SHORTEST DISTANCE IN THE END POINTS'
         PRINT '(A,F15.5)',   '         FRACTION FOR RESTORING TRUE POTENTIAL=',INTCONFRAC
         PRINT '(A,I6)',      '         MAXIMUM SEPARATION OF ATOMS IN SEQUENCE FOR CONSTRAINT=',INTCONSEP
         PRINT '(A,I6)',      '         MINIMUM SEPARATION OF ATOMS IN SEQUENCE FOR REPULSION=',INTREPSEP
         PRINT '(A,I8)',      '         MAXIMUM OPTIMIZATION STEPS FOR CONSTRAINED POTENTIAL=',INTSTEPS1
         PRINT '(A,2I8)',      '         NUMBER OF INTERMEDIATE IMAGES FOR CONSTRAINED POTENTIAL AND MAXIMUM=',INTIMAGE,MAXINTIMAGE
         PRINT '(A,F15.5)',   '         RMS GRADIENT PER IMAGE TOLERANCE FOR CONSTRAINED POTENTIAL=',INTRMSTOL
         PRINT '(A,I8)',      '         MAXIMUM OPTIMIZATION STEPS FOR CONSTRAINED/REAL POTENTIAL=',INTCONSTEPS
         PRINT '(A,I8)',      '         MAXIMUM STEPS FOR RELAXATION AFTER ADDING A NEW ATOM BEFORE BACKTRACK=',INTRELSTEPS
         PRINT '(A,I6)',      '         MAXIMUM NUMBER OF CONSTRAINTS PER ATOM=',MAXCONUSE
         PRINT '(A,F20.10)',  '         MAXIMUM ENERGY PER IMAGE FOR CONVERGENCE DURING CONSTRAINT POTENTIAL PHASE=',MAXCONE
         IF (CHECKCONINT) THEN
            PRINT '(A,I6)',      '         ADDING TERMS FOR CONSTRAINT INTERNAL MINIMA'
         ELSE
            PRINT '(A,I6)',      '         NOT ADDING TERMS FOR CONSTRAINT INTERNAL MINIMA'
         ENDIF
!        IF (DOCROSSCHECK) PRINT '(A,F15.5)','         CHECK FOR CHAIN CROSSING OF CONSTRAINTS WITH DISTANCE < ',CROSSCUT
      ENDIF
      IF (INTLJT.OR.INTCONSTRAINTT) THEN
         PRINT '(A,2F15.5)','         MINIMUM AND MAXIMUM IMAGE SEPARATIONS: ',IMSEPMIN,IMSEPMAX
      ENDIF

      IF (NEBMAG.GT.0) WRITE(*,'(A,I5)') ' FETCHZ> NEB MAGNIFICATIONS=',NEBMAG
      IF (CONNECTT.AND.(.NOT.NEWCONNECTT)) THEN
         WRITE(*,'(A,I5)') ' FETCHZ> OLD CONNECT RUN, MAXIMUM TRANSITION STATES=',NCONNECT
         IF (FIXD) WRITE(*,'(A,F12.5)')
     1             ' FETCHZ> HARD SPHERE TRANSITION STATE GUESSES WILL BE APPLIED FOR MINIMA SPEARATED BY LESS THAN ',DTHRESH
         IF (STOPFIRST) WRITE(*,'(A)') ' FETCHZ> CALCULATION WILL STOP WHEN THE INITIAL MINIMUM BECOMES CONNECTED'
      ENDIF
      IF (CALCRATES) THEN
         WRITE(*,'(A,F12.5,A,E20.10)') 
     1          ' FETCHZ> RATE CONSTANTS WILL BE CALCULATED FOR TEMPERATURE ',TEMPERATURE,' AND PLANK;S CONSTANT=',HRED
         IF (READPATH)  WRITE(*,'(A)') ' FETCHZ> RATE CONSTANTS WILL BE CALCULATED FOR PATHWAY SAVED IN PATH.INFO'
      ENDIF
      IF (PATHT) WRITE(*,'(A,I6,A)')' FETCHZ> PATHWAYS WILL BE CALCULATED SAVING ',NPATHFRAME,' FRAMES ON EACH SIDE'
      IF (MACHINE) WRITE(*,'(A)') ' FETCHZ> WILL USE BINARY FILES FOR COMMUNICATION'
      IF (MACHINE) WRITE(*,'(A)')' FETCHZ> WARNING READING BINARY FILES IS NOT FULLY SUPPORTED. THOUROUGHLY TESTED FOR CHARMM ONLY'
      IF (DUMPPATH) WRITE(*,'(A)')' FETCHZ> PATHWAY INFORMATION WILL BE PRINTED TO PATH.INFO'
      IF (DUMPDATAT) WRITE(*,'(A)')' FETCHZ> STATIONARY POINT INFORMATION WILL BE PRINTED TO MIN.DATA'
      IF (ORDERPARAMT) THEN
         IF (.NOT.DUMPDATAT) THEN
            PRINT '(A)','FETCHZ> WARNING - ORDER PARAMETER CALCULATION REQUESTED, BUT DUMPDATA NOT SET IN ODATA'
         ELSE
            WRITE(*,'(A,I8)')' FETCHZ> NUMBER OF ORDER PARAMETERS AND DERIVATIVES TO BE PRINTED=',NORDER
            DO J1=1,NORDER
               WRITE(*,'(A,A,I8)')' FETCHZ> ORDER PARAMETER AND ADDITIONAL INFO=',WHICHORDER(J1),ORDERNUM(J1)
            ENDDO
         ENDIF
      ENDIF
      IF (BFGSMINT.OR.BFGSTST) THEN
         IF (GMAX.GT.CONVR) THEN
            CONVR=GMAX
            WRITE(*,'(A)') ' FETCHZ> RMS CONVERGENCE RESET TO THE LBFGS CONVERGENCE LIMIT'
         ENDIF
         WRITE(*,'(A,G15.8,A,I6)') 
     1           ' FETCHZ> CONVERGENCE CRITERION FOR LBFGS OPTIMIZATION: RMS FORCE<',GMAX,' MAXIMUM STEPS=',BFGSSTEPS
         WRITE(*,'(A,G20.10)') ' FETCHZ> MAXIMUM ENERGY RISE IN LBFGS MINIMIZATION=',MAXERISE
         WRITE(*,'(A,I4)') ' FETCHZ> NUMBER OF UPDATES BEFORE RESET IN LBFGS= ',MUPDATE
         IF (BFGSTST) WRITE(*,'(A,I4)') ' FETCHZ> NUMBER OF UPDATES BEFORE RESET IN XLBFGS=',XMUPDATE
         WRITE(*,'(A,I4)') ' FETCHZ> NUMBER OF UPDATES BEFORE RESET IN MIND=',5
         IF (NEBT.OR.NEWNEBT) WRITE(*,'(A,I4)') ' FETCHZ> NUMBER OF UPDATES BEFORE RESET IN NEB=',NEBMUPDATE
         WRITE(*,'(A,F10.4)') ' FETCHZ> INITIAL GUESS FOR DIAGONAL ELEMENTS IN LBFGS= ',DGUESS
         IF (BFGSTST) WRITE(*,'(A,F10.4)') ' FETCHZ> INITIAL GUESS FOR DIAGONAL ELEMENTS IN XLBFGS=',XDGUESS
         WRITE(*,'(A,F10.4)') ' FETCHZ> MAXIMUM STEP SIZE IN LBFGS ENERGY MINIMIZATION= ',MAXBFGS
         IF (BFGSTST) WRITE(*,'(A,F10.4)') ' FETCHZ> MAXIMUM STEP SIZE IN XLBFGS=',MAXXBFGS
         WRITE(*,'(A,F10.4)') ' FETCHZ> MAXIMUM STEP SIZE IN LBFGS NEB IMAGE MINIMIZATION=             ',MAXNEBBFGS
      ELSE IF (BSMIN) THEN
         IF (GMAX.GT.CONVR) THEN
            CONVR=GMAX
            WRITE(*,'(A)') ' FETCHZ> RMS CONVERGENCE RESET TO THE BS CONVERGENCE LIMIT'
         ENDIF
         WRITE(*,'(A,G15.8)') ' FETCHZ> CONVERGENCE CRITERION FOR BS STEEPEST-DESCENT: RMS FORCE<',GMAX
      ELSE IF (RKMIN) THEN
         IF (GMAX.GT.CONVR) THEN
            CONVR=GMAX
            WRITE(*,'(A)') ' FETCHZ> RMS CONVERGENCE RESET TO THE RK CONVERGENCE LIMIT'
         ENDIF
         WRITE(*,'(A,G15.8)') ' FETCHZ> CONVERGENCE CRITERION FOR RK STEEPEST-DESCENT: RMS FORCE<',GMAX
      ENDIF
      IF (REOPT) WRITE(*,'(A)') ' FETCHZ> SMALLEST EIGENVECTOR WILL BE RECONVERGED AFTER EF STEP BEFORE TANGENT SPACE MINIMISATION'
      IF (.NOT.(BFGSMINT.OR.BSMIN.OR.RKMIN)) 
     1       WRITE(*,'(A,G15.8,A,G15.8)') ' FETCHZ> CONVERGENCE CRITERIA: EF STEP<',CONVU,' RMS FORCE<',CONVR
      IF (CHECKINDEX) WRITE(*,'(A)') ' FETCHZ> HESSIAN INDEX WILL BE CHECKED'
      IF (CHECKCONT) WRITE(*,'(A)') 
     1    ' FETCHZ> SEARCH WILL RESUME AFTER PUSHOFF IF COVERGENCE TO THE WRONG HESSIAN INDEX IS DETECTED'
      IF (DCHECK) WRITE(*,'(A)') ' FETCHZ> WARNINGS WILL BE ISSUED IF ATOMS BECOME CLOSER THAN 0.5 UNITS'
      IF (DUMPV) THEN   
         IF (ALLSTEPS) THEN
            IF (ALLVECTORS) THEN
               WRITE(*,'(A)') ' FETCHZ> ALL EIGENVECTORS WILL BE DUMPED AT EVERY STEP'
            ELSE
               WRITE(*,'(A)') ' FETCHZ> EIGENVECTOR CORRESPONDING TO SMALLEST EIGENVALUE WILL BE DUMPED AT EVERY STEP'
            ENDIF
         ELSE
            IF (ALLVECTORS) THEN
               WRITE(*,'(A)') ' FETCHZ> ALL EIGENVECTORS WILL BE DUMPED AT THE FINAL STEP'
            ELSE
               WRITE(*,'(A)') ' FETCHZ> EIGENVECTOR CORRESPONDING TO SMALLEST EIGENVALUE WILL BE DUMPED AT THE FINAL STEP'
            ENDIF
            IF (MWVECTORS) THEN
               WRITE(*,'(A)') ' FETCHZ> THESE WILL BE THE VECTORS OF THE MASS WEIGHTED HESSIAN, WITH FREQENCIES IN WAVENUMBERS'
            ENDIF
            IF (KTWNT) THEN
               WRITE(*,'(A)') ' FETCHZ> EFFECT OF THERMALLY ACCESSIBLE MODES WILL BE OUTPUT'
            ENDIF
         ENDIF
      ENDIF
      IF (EVCUT.NE.0.0D0) WRITE(*,'(A,G15.8,A)') ' FETCHZ> EIGENVALUES SMALLER THAN ',EVCUT,' WILL BE TREATED AS ZERO'
      IF (DTEST) WRITE(*,'(A,I3,A,I3,A,G15.8)') 
     1       ' FETCHZ> GDIIS OF MAXIMUM DIMENSION ',NDIIA,' WILL BE USED EVERY ',NINTV,' STEPS WHEN RMS FORCE < ',PCUT
      IF (HUPDATE) THEN
         WRITE(*,'(A,F14.5)') ' FETCHZ> HESSIAN UPDATE PROCEDURE WILL BE APPLIED, PHI=',PHIG
         IF (NSTHUP.EQ.0) THEN
            WRITE(*,'(A)') ' SETTINGS NO ANALYTIC HESSIANS WILL BE CALCULATED'
         ELSE
            IF (INTHUP.EQ.0) THEN
               WRITE(*,'(A,I4)') ' SETTNIGS ANALYTIC HESSIANS WILL BE CALCULATED ONLY AT STEP ',NSTHUP
            ELSE
               WRITE(*,'(A,I4,A,I4)') ' SETTNIGS ANALYTIC HESSIANS WILL BE CALCULATED EVERY ',INTHUP,
     1                                ' STEPS STARTING FROM STEP ',NSTHUP
            ENDIF
         ENDIF
         IF (INTHUP.EQ.-1) WRITE(*,'(A)') ' FETCHZ> HESSIAN WILL BE FIXED FOR ALL STEPS'
      ENDIF
      IF (READHESS)  WRITE(*,'(A)') ' FETCHZ> HESSIAN WILL BE READ FROM FILE DERIVS FOR INITIAL GEOMETRY'
      IF (MASST) WRITE(*,'(A)') ' FETCHZ> FICTITIOUS KINETIC METRIC WILL BE USED'
      IF (.NOT.(BFGSMINT.OR.BSMIN.OR.RKMIN)) THEN
         WRITE(*,'(A,F15.8)') ' FETCHZ> INITIAL MAXIMUM FOR EF/SD STEPS=',MXSTP
         WRITE(*,'(A,F15.8)') ' FETCHZ> MAXIMUM VALUE FOR MAXIMUM ALLOWED EF/SD STEPS=',MAXMAX
         WRITE(*,'(A,F15.8)') ' FETCHZ> MINIMUM VALUE FOR MAXIMUM ALLOWED EF/SD STEPS=',MINMAX
      ENDIF
      IF (PRESSURE) WRITE(*,'(A)') ' FETCHZ> LATTICE CONSTANT WILL BE OPTIMISED FOR ZERO PRESSURE'
      IF (INR.NE.1) THEN
         IF (.NOT.(BFGSMINT.OR.BSMIN.OR.RKMIN)) 
     1         WRITE(*,'(A,F15.8)') ' FETCHZ> VALUE OF PUSHOFF FROM STATIONARY POINTS OF THE WRONG INDEX=',PUSHOFF
         IF (.NOT.(BFGSMINT.OR.BSMIN.OR.RKMIN)) WRITE(*,'(A,F15.8)') 
     1          ' FETCHZ> A PUSHOFF FROM STATIONARY POINTS OF THE WRONG INDEX MAY BE APPLIED WHEN THE RMS FORCE <',PUSHCUT
      ENDIF
      IF (RESIZE.NE.1.0D0) WRITE(*,'(A,F15.8)') ' FETCHZ> INITIAL COORDINATES WILL BE SCALED BY A FACTOR OF ',RESIZE
C     WRITE(*,'(A,E15.8)') ' FETCHZ> EIGENVALUE SHIFTING PARAMETER=',SHIFTV
      IF (FILTH.NE.0) WRITE(*,'(A,I6)') ' FETCHZ> NUMBER TO DISTINGUISH OUTPUT FILES=',FILTH
      IF (CONTAINER) WRITE(*,'(A,F15.5)') ' FETCHZ> SYSTEM WILL BE ENCLOSED IN A SPHERICAL CONTAINER RADIUS=',SQRT(RADIUS)
      IF (FIXAFTER.GE.0) WRITE(*,'(A,I6)') ' FETCHZ> FIXIMAGE WILL BE SET PERMANENTLY ON AFTER STEP ',FIXAFTER
      IF (.NOT.PRINTPTS) WRITE(*,'(A,I6)') ' FETCHZ> COORDINATES FOR INTERMEDIATE STEPS WILL NOT BE DUMPED TO FILE POINTS'
      PRINT*

      IF (IPRNT.NE.0) WRITE(*,'(A,I3)') ' FETCHZ> IPRNT SET TO ',IPRNT
      IF ((.NOT.BFGSMINT).AND.(.NOT.BFGSTST).AND.(.NOT.BSMIN.OR.RKMIN)) THEN
       IF (PGRAD) WRITE(*,'(A,I3,A)') ' FETCHZ> GRADIENTS ALONG HESSIAN EIGENVECTORS WILL BE PRINTED EVERY ',NGRADIENTS,' STEPS'
       IF (EFSTEPST) WRITE(*,'(A,I4,A)') ' FETCHZ> MAXIMUM UNSCALED STEPS FOR EACH MODE WILL BE PRINTED EVERY ',EFSTEPS,' STEPS'
       IF (VALUEST) WRITE(*,'(A,I4,A)') ' FETCHZ> HESSIAN EIGENVALUES WILL BE PRINTED EVERY ',NVALUES,' STEPS'
       IF (VECTORST) WRITE(*,'(A,I4,A)') ' FETCHZ> HESSIAN EIGENVECTORS WILL BE PRINTED EVERY ',NVECTORS,' STEPS'
       WRITE(*,'(A,I3,A)') ' FETCHZ> SUMMARY OF STEPS AND DERIVATIVES WILL BE PRINTED EVERY ',NSUMMARY,' STEPS'
      ENDIF
      PRINT*

      RETURN
      END
      
