!   OPTIM: A PROGRAM FOR OPTIMIZING GEOMETRIES AND CALCULATING REACTION PATHWAYS
!   COPYRIGHT (C) 1999-2006 DAVID J. WALES
!   THIS FILE IS PART OF OPTIM.
!   
!   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!   (AT YOUR OPTION) ANY LATER VERSION.
!   
!   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!   
!   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!
!###################################################################################
!############################ FMSEVB SUBROUTINE ####################################
!###################################################################################

	SUBROUTINE FMSEVB(NCOORD, Q, DQ, ASSIGNVBSTATES)

	USE COMMONS
	USE MSEVB_COMMON
	USE MSEVB_INTERFACES

	IMPLICIT NONE

!#####################################################################
! 24-09-00  R. A. CHRISTIE
!
! PARAMETER SET USED IS FROM:
!    U. SCHMITT AND G. A. VOTH, J. CHEM. PHYS. 111, 1999, 9361
! AND NOT THE EARLIER SET, NOR THE LATER ONE, OR EVEN THE BUGGY ONE.
!
! CALL THE VARIOUS ROUTINES NECESSARY TO BUILD UP THE HELLMAN-FEYNMAN
!
! *NB* THIS ROUTINE USED TO BE CALLED HELLFEYN, BUT THE NAME WAS 
!      ALTERED ON 3RD AUG 2002 WHEN INTRODUCED INTO OPTIM 2.3
!
!#####################################################################  

	INTEGER NCOORD
	DOUBLE PRECISION DQ(NCOORD), Q(NCOORD)
	LOGICAL ASSIGNVBSTATES

	DOUBLE PRECISION XF(NATOMS),YF(NATOMS),ZF(NATOMS)
	INTEGER ATOMPOS,ATOMPOS_TEMP,PROTON,ATOM_NUM
	INTEGER I,JJ,J,II
	DOUBLE PRECISION FXH(REDUCED_NUM_EIG,REDUCED_NUM_EIG),FYH(REDUCED_NUM_EIG,REDUCED_NUM_EIG), &
               FZH(REDUCED_NUM_EIG,REDUCED_NUM_EIG),DX,DY, &
      	       DZ,R1,R2,MINIMUM_X(NATOMS),SCALE,MINIMUM_Y(NATOMS),MINIMUM_Z(NATOMS), &
               PROBABLE_STATE(REDUCED_NUM_EIG),TEMPSCALE
	INTEGER M,EIGENSTATE,PIVOTOXYGEN,JK,POSN_IN_STATE1,POSITION,POSITION_TEMP
	DOUBLE PRECISION FXATOM1,FXATOM3,FXATOM4(NATOMS),OFFDIAGX,OFFDIAGY, &
      		OFFDIAGZ,ROO,ROH,FYATOM1,FZATOM1, &
      		FYATOM3,FZATOM4(NATOMS),FYATOM4(NATOMS),FZATOM3, &
      		FORCE_X,FORCE_Y,FORCE_Z, &
      		DROO(3),DROH(3),STARTENERGY,MAXFORCEMAG,KEECH
	CHARACTER*5 ATOMTYPE
	DOUBLE PRECISION DX1,DX2,DX3,DY1,DY2,DY3,DZ1,DZ2,DZ3,R12_1,R12_2,R12_3,ASYMM
	INTEGER HMIN,POSITIONI,POSITIONJ,JL,ATOMORDER(NATOMS)
	DOUBLE PRECISION ENEW
	DOUBLE PRECISION R,RCUT
	INTEGER CURRENTATOM,STATE1,POSITIONINSTATE1,STATE2,POSITIONINSTATE2
	DOUBLE PRECISION :: H2OINTERXFORCES(NATOMS,REDUCED_NUM_EIG)
	DOUBLE PRECISION :: H2OINTERYFORCES(NATOMS,REDUCED_NUM_EIG)
	DOUBLE PRECISION :: H2OINTERZFORCES(NATOMS,REDUCED_NUM_EIG)

!###################################################################
! CHECK THAT THERE IS NO ROO VECTORS SMALLER IN MAGNITUDE THAN
! THE RCUT CUTOFF VALUE
!  
! 	RCUT = 2.0
!         DO I = 3,NUM_ATOM-4,3
!            DO J = I+3,NUM_ATOM-1,3
!               DX = PSIX(I) - PSIX(J)
!               DY = PSIY(I) - PSIY(J)
!               DZ = PSIZ(I) - PSIZ(J)
!               R = DSQRT(DX**2 + DY**2 + DZ**2)
!               IF (R.LT.RCUT) THEN
! 		  DQ(3*I+1) = -1.0D02
! 	          DQ(3*I+2) = -1.0D02
!                 DQ(3*I+3) = -1.0D02
!                 DQ(3*J+1) = -1.0D02
!                 DQ(3*J+2) = -1.0D02
!                 DQ(3*J+3) = -1.0D02
!                 RETURN
!               ENDIF
!            ENDDO
!         ENDDO              
!
!#######################################################################################
! EVALUATION OF THE FORCE TERMS REQUIRES THE COORDINATES TO BE IN 
! VECTORS "PSIX,PSIY" ETC. HOWEVER, POLAK-RIBIERE ROUTINES PASS THE
! VECTOR WITH WHICH THE ENERGY IS TO BE MINIMIZED AS THE VECTOR "P".
! 
!########################################################################################

! NOT ALWAYS NECESSARY TO RECALL THE ENERGY STEP
! THE ONLY THINGS CARRIED OVER ARE THE VB ASSIGNMENTS AND THE EXCHANGE ENERGIES

	IF (ASSIGNVBSTATES) CALL MSEVB(NCOORD,Q,ASSIGNVBSTATES,ENEW)

! CALCULATE H2O-H2O INTERACTIONS ALL IN ONE GO

	CALL CALCULATEH2OINTERFORCES (H2OINTERXFORCES, H2OINTERYFORCES, H2OINTERZFORCES)

!#######################################################################################
! LOOP OVER ALL ATOMS
!
!####################################################################################### 
 	DO CURRENTATOM = 1,NATOMS

!#######################################################################################
! LOOP OVER THE EIGENSTATES OF SYSTEM
!#######################################################################################

	   DO STATE1 = 1, REDUCED_NUM_EIG

! WHICH ATOM IS THIS IN THE CURRENT VB STATE?

	      DO J = 1, NATOMS
		 IF (ATMPL(STATE1,J).EQ.CURRENTATOM) THEN
		    POSITIONINSTATE1 = J
		    EXIT
		 ENDIF
	      ENDDO

!###############################################################################################
! DETERMINE THE DIAGONAL MATRIX ELEMENT

	      CALL FDIAG(POSITIONINSTATE1,STATE1,FORCE_X,FORCE_Y,FORCE_Z)

	      FXH(STATE1,STATE1) = FORCE_X + H2OINTERXFORCES(CURRENTATOM,STATE1)
	      FYH(STATE1,STATE1) = FORCE_Y + H2OINTERYFORCES(CURRENTATOM,STATE1)
	      FZH(STATE1,STATE1) = FORCE_Z + H2OINTERZFORCES(CURRENTATOM,STATE1)

!###############################################################################################
! HAVING CALCULATED THE DIAGONAL ELEMENT, NOW DETERMINE THE OFF-DIAGONAL ELEMENTS

	      DO STATE2 = (STATE1+1),REDUCED_NUM_EIG

		 IF (STATESINTERACT(STATE1,STATE2)) THEN
		 
		    DO J = 1, NATOMS
		       IF (ATMPL(STATE2,J).EQ.CURRENTATOM) THEN
			  POSITIONINSTATE2 = J
			  EXIT
		       ENDIF
		    ENDDO  

! ALREADY HAVE DETERMINED THE ZUNDEL SPECIES FOR THIS COMBINATION

		    ROH = INTERATOMICR(ZUNDEL_SPECIES(STATE1,STATE2,4), ATMPL(STATE1,3))
    
		    IF (CURRENTATOM.EQ.ZUNDEL_SPECIES(STATE1,STATE2,4)) THEN
		       DROH(1) = PSIX(ZUNDEL_SPECIES(STATE1,STATE2,4)) - PSIX(ATMPL(STATE1,3))
		       DROH(2) = PSIY(ZUNDEL_SPECIES(STATE1,STATE2,4)) - PSIY(ATMPL(STATE1,3))
		       DROH(3) = PSIZ(ZUNDEL_SPECIES(STATE1,STATE2,4)) - PSIZ(ATMPL(STATE1,3))
		    ELSE
		       DROH(1) = PSIX(ATMPL(STATE1,3)) - PSIX(ZUNDEL_SPECIES(STATE1,STATE2,4))
		       DROH(2) = PSIY(ATMPL(STATE1,3)) - PSIY(ZUNDEL_SPECIES(STATE1,STATE2,4))
		       DROH(3) = PSIZ(ATMPL(STATE1,3)) - PSIZ(ZUNDEL_SPECIES(STATE1,STATE2,4))            
		    ENDIF

		    IF (CURRENTATOM.EQ.ATMPL(STATE2,3)) THEN
		       DROO(1) = PSIX(ATMPL(STATE2,3)) - PSIX(ATMPL(STATE1,3))
		       DROO(2) = PSIY(ATMPL(STATE2,3)) - PSIY(ATMPL(STATE1,3))
		       DROO(3) = PSIZ(ATMPL(STATE2,3)) - PSIZ(ATMPL(STATE1,3))  
		    ELSE
		       DROO(1) = PSIX(ATMPL(STATE1,3)) - PSIX(ATMPL(STATE2,3))
		       DROO(2) = PSIY(ATMPL(STATE1,3)) - PSIY(ATMPL(STATE2,3))
		       DROO(3) = PSIZ(ATMPL(STATE1,3)) - PSIZ(ATMPL(STATE2,3))  
		    ENDIF

		    ROO = INTERATOMICR(ATMPL(STATE1,3), ATMPL(STATE2,3))

!###############################################################################################
! DETERMINE THE APPROPRIATE OFF-DIAGONAL ROUTINE TO CALL
!

		    IF (MOD(CURRENTATOM,3).EQ.0) THEN
		       IF ((POSITIONINSTATE1.EQ.3).OR.(POSITIONINSTATE2.EQ.3)) THEN

! HYDRONIUM O ATOM IN EITHER OF THE VB STATES UNDER CONSIDERATION
			  CALL OFFD_ATOM3(CURRENTATOM,ROO,ROH,DROO,DROH,FXATOM3,FYATOM3,FZATOM3,STATE1,STATE2)
			  OFFDIAGX = FXATOM3
			  OFFDIAGY = FYATOM3
			  OFFDIAGZ = FZATOM3 

		       ELSE	
! PURE H2O O ATOM
			  CALL OFFD_ATOM1(CURRENTATOM,ROO,ROH,FXATOM1,FYATOM1,FZATOM1,STATE1,STATE2)
			  OFFDIAGX = FXATOM1
			  OFFDIAGY = FYATOM1
			  OFFDIAGZ = FZATOM1
		       ENDIF
!---		       ELSEIF (ATMPL(I,4).EQ.4) THEN
!---		       ELSEIF (POSITION.EQ.HMIN) THEN
		    ELSEIF (CURRENTATOM.EQ.ZUNDEL_SPECIES(STATE1,STATE2,4)) THEN

! EXCHANGING H ATOM
		       CALL OFFD_ATOM4(CURRENTATOM,ROO,ROH,DROO,DROH,FXATOM1,FYATOM1,FZATOM1,STATE1,STATE2)
		       OFFDIAGX = FXATOM1
		       OFFDIAGY = FYATOM1
		       OFFDIAGZ = FZATOM1 
		    ELSE

! EITHER A PURE WATER H OR A NON-EXCHANGING ZUNDEL H

		       CALL OFFD_ATOM1(CURRENTATOM,ROO,ROH,FXATOM1,FYATOM1,FZATOM1,STATE1,STATE2)
		       OFFDIAGX = FXATOM1
		       OFFDIAGY = FYATOM1
		       OFFDIAGZ = FZATOM1
		    ENDIF
		    
		    FXH(STATE1,STATE2) = OFFDIAGX
		    FYH(STATE1,STATE2) = OFFDIAGY
		    FZH(STATE1,STATE2) = OFFDIAGZ
		    FXH(STATE2,STATE1) = OFFDIAGX
		    FYH(STATE2,STATE1) = OFFDIAGY
		    FZH(STATE2,STATE1) = OFFDIAGZ

! DEBUGGING
!		       OFF_DIAG_FORCES(STATE1,STATE2,3*JJ-2)=OFFDIAGX
!		       OFF_DIAG_FORCES(STATE1,STATE2,3*JJ-1)=OFFDIAGY
!		       OFF_DIAG_FORCES(STATE1,STATE2,3*JJ)=OFFDIAGZ
		 
		 ELSE
		    FXH(STATE1,STATE2) = 0.0D0
		    FYH(STATE1,STATE2) = 0.0D0
		    FZH(STATE1,STATE2) = 0.0D0
		    FXH(STATE2,STATE1) = 0.0D0
		    FYH(STATE2,STATE1) = 0.0D0
		    FZH(STATE2,STATE1) = 0.0D0
		 ENDIF
	      ENDDO

!----SUM UP THE COMPONENTS TO MAKE THE ELEMENT HIJ

	   ENDDO

! SUM COMPONENTS

!#####################################################################
! ASSIGN THE GROUND STATE EIGENVECTOR AS CORRESPONDING TO THE 
! LOWEST EIGENVALUE
!  *NB* NO CONSIDERATION OF SIGN IS OBSERVED HERE
!
!#####################################################################

	   MINIMUM_X(CURRENTATOM) = 0.0D0
	   MINIMUM_Y(CURRENTATOM) = 0.0D0
	   MINIMUM_Z(CURRENTATOM) = 0.0D0

	   DO I = 1,REDUCED_NUM_EIG
	      DO J = 1,REDUCED_NUM_EIG
		 MINIMUM_X(CURRENTATOM) = MINIMUM_X(CURRENTATOM) + GRSTWFU(I)*GRSTWFU(J)*FXH(I,J)
		 MINIMUM_Y(CURRENTATOM) = MINIMUM_Y(CURRENTATOM) + GRSTWFU(I)*GRSTWFU(J)*FYH(I,J)
		 MINIMUM_Z(CURRENTATOM) = MINIMUM_Z(CURRENTATOM) + GRSTWFU(I)*GRSTWFU(J)*FZH(I,J)
	      ENDDO
	   ENDDO

!	   PRINT *, 'FORCE MATRIX: ATOM', CURRENTATOM
!	   DO I=1,REDUCED_NUM_EIG
!	   DO J=1,REDUCED_NUM_EIG
!	      PRINT *, '***', I, J, '***'
!	      PRINT *, '***', I, '***'
!	      WRITE(*, '(3(A3,F14.6))') 'X:', FXH(I,I), 'Y:', FYH(I,I), 'Z:', FZH(I,I) 
!	   ENDDO
!	   ENDDO

!#####################################################################
! END LOOP OVER ATOMS
!
!#####################################################################
 	ENDDO

	J = 1
	DO I = 1,NATOMS
	   DQ(J) = MINIMUM_X(I)
	   DQ(J+1) = MINIMUM_Y(I)
	   DQ(J+2) = MINIMUM_Z(I)
	   J = J + 3
	ENDDO

!	STOP

	RETURN 
        END

  !#####################################################################
!############### SUBROUTINE FDIAG ####################################
!#####################################################################

! H20-H2O INTERMOLECULAR FORCES ARE CALCULATED SEPARATELY

	SUBROUTINE FDIAG(ATOMPOS, VBSTATE, FORCE_X, FORCE_Y, FORCE_Z)

	USE MSEVB_COMMON

! ATOMPOS IS THE NUMBER OF THE ATOM IN VBSTATE, THE VB STATE OF INTEREST

	IMPLICIT NONE

!-----------------------------------------------------------------
! 23-7-00 R.A. CHRISTIE
! ROUTINE TO CALL THE DIAGONAL HELLMAN-FEYNMAN FORCE CALCULATIONS
!
! INCLUDES THE FOLLOWING ROUTINES:
! 	FH3OINTRA.F
!	FINTER.F
!	FH2OINTRA.F
!-----------------------------------------------------------------

!----VARIABLES TO BE PASSED
        INTEGER ATOMPOS,VBSTATE
	DOUBLE PRECISION FH3OINTRAX,FH3OINTRAY,FH3OINTRAZ
	DOUBLE PRECISION FINTERX,FINTERY,FINTERZ
	DOUBLE PRECISION FORCE_X,FORCE_Y,FORCE_Z
	DOUBLE PRECISION FH2OINTRAX,FH2OINTRAY,FH2OINTRAZ

!-----------------------------------------------------------------
! INITIALIZE VARIABLES
!
!----------------------------------------------------------------- 

	FH3OINTRAX = 0.0D0
	FH3OINTRAY = 0.0D0
	FH3OINTRAZ = 0.0D0
	FINTERX = 0.0D0
	FINTERY = 0.0D0
	FINTERZ = 0.0D0
	FH2OINTRAX = 0.0D0
	FH2OINTRAY = 0.0D0
	FH2OINTRAZ = 0.0D0
	FORCE_X = 0.0D0
	FORCE_Y = 0.0D0
	FORCE_Z = 0.0D0

!-----------------------------------------------------------------
! CALL SUBROUTINES ACCORDING TO THE ATOM IN QUESTION
!-----------------------------------------------------------------

        IF (ATOMPOS.LE.4) THEN  ! HYDRONIUM ATOM IN THIS STATE

           CALL FH3OINTRA(ATOMPOS,VBSTATE,FH3OINTRAX,FH3OINTRAY,FH3OINTRAZ)
           CALL FINTER(ATOMPOS,VBSTATE,FINTERX,FINTERY,FINTERZ)

	   FORCE_X = FH3OINTRAX + FINTERX 
	   FORCE_Y = FH3OINTRAY + FINTERY
           FORCE_Z = FH3OINTRAZ + FINTERZ 

        ELSE  ! WATER ATOM IN THIS STATE

           CALL FH2OINTRA(ATOMPOS,VBSTATE,FH2OINTRAX,FH2OINTRAY,FH2OINTRAZ)
           CALL FINTER(ATOMPOS,VBSTATE,FINTERX,FINTERY,FINTERZ)

	   FORCE_X = FH2OINTRAX + FINTERX
	   FORCE_Y = FH2OINTRAY + FINTERY
	   FORCE_Z = FH2OINTRAZ + FINTERZ
        ENDIF

        RETURN
        END

!#####################################################################
!################### SUBROUTINE FH3OINTRA ############################
!#####################################################################

        SUBROUTINE FH3OINTRA(ATOMPOS,VBSTATE,FH3OINTRAX,FH3OINTRAY,FH3OINTRAZ)

	USE MSEVB_COMMON

	IMPLICIT NONE

!-----------------------------------------------------------------
! 30-7-99 R.A. CHRISTIE
!
!   -- UPDATE: 21-07-00
! SUBROUTINE TO DETERMINE THE FORCES FROM THE INTRAMOLECULAR BEND
! AND STRETCH OF THE H3O+ MOLECULE
!
!-----------------------------------------------------------------

!----INCOMING VARIABLES
        INTEGER ATOMPOS,VBSTATE
	DOUBLE PRECISION FH3OINTRAX,FH3OINTRAY,FH3OINTRAZ

!----LOCAL VARIABLES
	INTEGER ATOMNO
        DOUBLE PRECISION DX,DY,DZ,EXPTERM,VROH(10),RFH3OSTR,FH3OSTR,RFH3OSTRX, &
             RFH3OSTRY,RFH3OSTRZ,ROH(3),THETA(3),DXROH(10),DYROH(10), &
             DZROH(10),RFH3OBENDX1,RFH3OBENDY1,RFH3OBENDZ1,ROHSTR, &
             RFH3OBENDX,RFH3OBENDY,RFH3OBENDZ,RFH3OBENDX2,ADOTA,ADOTB, &
      	     ADOTC,RFH3OBENDY2,RFH3OBENDZ2,FH3OSTR_TEMP,DXOH(10),DYOH(10), &
      	     DZOH(10),VECTSQ(3),ANGLEDIFF(3),PART1X,PART2X,PART3X,PART4X,PART1Y, &
      	     PART2Y,PART3Y,PART4Y,PART1Z,PART2Z,PART3Z,PART4Z,ANGLEDIFF2, &
      	     VECTSQ2,THETA_TEMP
        INTEGER I,J,OTHERB1,OTHERB2,BND,HYD
!	DOUBLE PRECISION RADS
!----NEW VARIABLES
	DOUBLE PRECISION ATOMPOSVECTOR,OTHERB1VECTOR,OTHERB2VECTOR,RFH3OBENDX_TEMP1, &
      		RFH3OBENDX_TEMP2,RFH3OBENDX_TEMP3,RFH3OBENDY_TEMP1, &
      		RFH3OBENDY_TEMP2,RFH3OBENDY_TEMP3,RFH3OBENDZ_TEMP1, &
      		RFH3OBENDZ_TEMP2,RFH3OBENDZ_TEMP3,TEMPR
	INTEGER PIVOTOXYGEN
	DOUBLE PRECISION CHECKED_ACOS

!-----INITIALIZE VARIABLES
	EXPTERM = 0.0D0
	FH3OSTR = 0.0D0
	RFH3OSTRX = 0.0D0
	FH3OSTR_TEMP = 0.0D0
	RFH3OSTRY = 0.0D0
	RFH3OSTRZ = 0.0D0
	RFH3OBENDX1 = 0.0D0
	RFH3OBENDY1 = 0.0D0
	RFH3OBENDZ1 = 0.0D0
	RFH3OBENDX = 0.0D0
        RFH3OBENDY = 0.0D0
        RFH3OBENDZ = 0.0D0
	DO I = 1,10
	   DXROH(I) = 0.0D0
	   DXOH(I) = 0.0D0
	   DYROH(I) = 0.0D0
	   DYOH(I) = 0.0D0
	   DZROH(I) = 0.0D0
	   DZOH(I) = 0.D0
	ENDDO

!----INITIALIZE NEW VARIABLES
	ATOMPOSVECTOR = 0.0D0
	OTHERB1VECTOR = 0.0D0
	OTHERB2VECTOR = 0.0D0
	RFH3OBENDX_TEMP1 = 0.0D0
	RFH3OBENDX_TEMP2 = 0.0D0
	RFH3OBENDX_TEMP3 = 0.0D0
	RFH3OBENDY_TEMP1 = 0.0D0
        RFH3OBENDY_TEMP2 = 0.0D0
        RFH3OBENDY_TEMP3 = 0.0D0
	RFH3OBENDZ_TEMP1 = 0.0D0
        RFH3OBENDZ_TEMP2 = 0.0D0
        RFH3OBENDZ_TEMP3 = 0.0D0
	DO I = 1,3
           VECTSQ(I) = 0.0D0
	   ANGLEDIFF(I) = 0.0D0
	ENDDO

! THE POSITION OF THE ATOM IN THE ORIGINAL INPUT VECTORS

	ATOMNO = ATMPL(VBSTATE, ATOMPOS)

!-----------------------------------------------------------------------
! CALCULATE THE STRETCH CONTRIBUTION TO THE FORCE FIRST.
!
!-----------------------------------------------------------------------

        IF (ATOMPOS.NE.3) THEN    ! H ATOM
           DX = PSIX(ATOMNO) - PSIX(ATMPL(VBSTATE,3))
           DY = PSIY(ATOMNO) - PSIY(ATMPL(VBSTATE,3))
           DZ = PSIZ(ATOMNO) - PSIZ(ATMPL(VBSTATE,3))
	   ROHSTR = INTERATOMICR(ATOMNO,ATMPL(VBSTATE,3))
           EXPTERM = DEXP(-1.0D0*AOHEQ*(ROHSTR-ROHEQ))
           FH3OSTR = (2.0D0/ROHSTR)*EXPTERM*AOHEQ*DOH*(1.0D0-EXPTERM)
	   RFH3OSTRX = DX*FH3OSTR
	   RFH3OSTRY = DY*FH3OSTR
           RFH3OSTRZ = DZ*FH3OSTR
        ELSE                    ! O ATOM
	   J = 1
           DO I = 1,3
              DXOH(I) = PSIX(ATOMNO) - PSIX(ATMPL(VBSTATE,J))
              DYOH(I) = PSIY(ATOMNO) - PSIY(ATMPL(VBSTATE,J))
              DZOH(I) = PSIZ(ATOMNO) - PSIZ(ATMPL(VBSTATE,J))
	      VROH(I) = INTERATOMICR(ATOMNO,ATMPL(VBSTATE,J))
              EXPTERM = DEXP(-1.0D0*AOHEQ*(VROH(I)-ROHEQ))
              FH3OSTR_TEMP = (2.0D0/VROH(I))*EXPTERM*AOHEQ*DOH*(1.0D0-EXPTERM)
              RFH3OSTRX = RFH3OSTRX + FH3OSTR_TEMP*DXOH(I)
 	      RFH3OSTRY = RFH3OSTRY + FH3OSTR_TEMP*DYOH(I) 
 	      RFH3OSTRZ = RFH3OSTRZ + FH3OSTR_TEMP*DZOH(I) 
              J = J+1
              IF (J.EQ.3) J = 4
           ENDDO
        ENDIF

!---------------------------------------------------------------------
! CALCULATE THE CONTRIBUTION TO THE FORCE FROM THE HARMONIC BENDING
! POTENTIAL
!
! 1. DETERMINE THE "OTHER ATOMS" WHICH THE ATOM IN QUESTION IS
!    INTERACTING WITH.
! 2. FIND THE MAGNITUDE OF THE POSITION VECTORS IN A GLOBAL COORDINATE
!    SYSTEM.
! 3. DETERMINE THE MAGNITUDE OF THE O-H VECTORS IN A LOCAL, MOLECULE,
!    COORDINATE SYSTEM.
! 4. CALCULATE THE ANGLE BETWEEN THE O AND H VECTORS
! 5. FINALLY, CALCULATE THE BENDING COMPONENT OF FORCE.
!
!---------------------------------------------------------------------

!----OXYGEN
        IF (ATOMPOS.EQ.3) THEN

	   DXOH(1) = PSIX(ATMPL(VBSTATE,1)) - PSIX(ATOMNO) 
	   DYOH(1) = PSIY(ATMPL(VBSTATE,1)) - PSIY(ATOMNO) 
	   DZOH(1) = PSIZ(ATMPL(VBSTATE,1)) - PSIZ(ATOMNO) 
	   VROH(1) = INTERATOMICR(ATMPL(VBSTATE,1),ATOMNO)

	   DXOH(2) = PSIX(ATMPL(VBSTATE,2)) - PSIX(ATOMNO) 
	   DYOH(2) = PSIY(ATMPL(VBSTATE,2)) - PSIY(ATOMNO) 
	   DZOH(2) = PSIZ(ATMPL(VBSTATE,2)) - PSIZ(ATOMNO) 
	   VROH(2) = INTERATOMICR(ATMPL(VBSTATE,2),ATOMNO)

	   DXOH(3) = PSIX(ATMPL(VBSTATE,4)) - PSIX(ATOMNO) 
	   DYOH(3) = PSIY(ATMPL(VBSTATE,4)) - PSIY(ATOMNO) 
	   DZOH(3) = PSIZ(ATMPL(VBSTATE,4)) - PSIZ(ATOMNO) 
	   VROH(3) = INTERATOMICR(ATMPL(VBSTATE,4),ATOMNO)

	   THETA_TEMP = DXOH(1)*DXOH(2) + DYOH(1)*DYOH(2) &
              + DZOH(1)*DZOH(2)
	   THETA(1) = CHECKED_ACOS(THETA_TEMP/(VROH(1)*VROH(2)))

	   THETA_TEMP = DXOH(1)*DXOH(3) + DYOH(1)*DYOH(3) &
              + DZOH(1)*DZOH(3)
	   THETA(2) = CHECKED_ACOS(THETA_TEMP/(VROH(1)*VROH(3)))

	   THETA_TEMP = DXOH(3)*DXOH(2) + DYOH(3)*DYOH(2) &
              + DZOH(3)*DZOH(2)
	   THETA(3) = CHECKED_ACOS(THETA_TEMP/(VROH(3)*VROH(2)))
 
	   ANGLEDIFF(1) = THETA(1) - ALPHAEQ
	   ANGLEDIFF(2) = THETA(2) - ALPHAEQ
	   ANGLEDIFF(3) = THETA(3) - ALPHAEQ

	   VECTSQ(1) = DXOH(1)*DXOH(2) + DYOH(1)*DYOH(2) + DZOH(1)*DZOH(2)
	   VECTSQ(2) = DXOH(1)*DXOH(3) + DYOH(1)*DYOH(3) + DZOH(1)*DZOH(3)
	   VECTSQ(3) = DXOH(2)*DXOH(3) + DYOH(2)*DYOH(3) + DZOH(2)*DZOH(3)
 
!---------------------------------------------------------------------
!  X
!---------------------------------------------------------------------
	   PART1X = (DXOH(1)*VECTSQ(1))/(VROH(2)*VROH(1)**3) + (DXOH(2)*VECTSQ(1))/(VROH(1)*VROH(2)**3)
	   PART2X = DXOH(1)/(VROH(1)*VROH(2)) + DXOH(2)/(VROH(1)*VROH(2))
	   PART3X = -1.0D0*DSIN(THETA(1))

	   IF (DABS(PART3X)<NUMERICALZEROLIMIT) THEN
	      RFH3OBENDX_TEMP1 = LARGE_FORCE
	   ELSE
	      RFH3OBENDX_TEMP1 = KALPHA*(THETA(1) - ALPHAEQ)*(PART1X - PART2X)/PART3X
	   ENDIF

	   RFH3OBENDX = RFH3OBENDX + RFH3OBENDX_TEMP1
	     
	   PART1X = (DXOH(1)*VECTSQ(2))/(VROH(3)*VROH(1)**3) + (DXOH(3)*VECTSQ(2))/(VROH(1)*VROH(3)**3)
	   PART2X = DXOH(1)/(VROH(1)*VROH(3)) + DXOH(3)/(VROH(1)*VROH(3))
	   PART3X = -1.0D0*DSIN(THETA(2))

	   IF (DABS(PART3X)<NUMERICALZEROLIMIT) THEN
	      RFH3OBENDX_TEMP1 = LARGE_FORCE
	   ELSE 
	      RFH3OBENDX_TEMP1 = KALPHA*(THETA(2) - ALPHAEQ)*(PART1X - PART2X)/PART3X
	   ENDIF

	   RFH3OBENDX = RFH3OBENDX + RFH3OBENDX_TEMP1 

	   PART1X = (DXOH(2)*VECTSQ(3))/(VROH(3)*VROH(2)**3) + (DXOH(3)*VECTSQ(3))/(VROH(2)*VROH(3)**3)
	   PART2X = DXOH(2)/(VROH(2)*VROH(3)) + DXOH(3)/(VROH(2)*VROH(3))
	   PART3X = -1.0D0*DSIN(THETA(3))

	   IF (DABS(PART3X)<NUMERICALZEROLIMIT) THEN
	      RFH3OBENDX_TEMP1 = LARGE_FORCE
	   ELSE     
	      RFH3OBENDX_TEMP1 = KALPHA*(THETA(3) - ALPHAEQ)*(PART1X - PART2X)/PART3X
	   ENDIF
	   
	   RFH3OBENDX = RFH3OBENDX + RFH3OBENDX_TEMP1 

!---------------------------------------------------------------------
!  Y
!---------------------------------------------------------------------
	   PART1Y = -1.0D0*DYOH(1)*VECTSQ(1)/(VROH(2)*VROH(1)**3)
	   PART2Y = (DYOH(2)+DYOH(1))/(VROH(2)*VROH(1))
	   PART3Y = -1.0D0*DYOH(2)*VECTSQ(1)/(VROH(1)*VROH(2)**3)
	   PART4Y = 1.0D0 - VECTSQ(1)**2/((VROH(2)**2)*(VROH(1)**2))

	   IF (DABS(PART4Y)<NUMERICALZEROLIMIT) THEN
	      RFH3OBENDY_TEMP1 = LARGE_FORCE
	   ELSE
	      RFH3OBENDY_TEMP1 = (KALPHA*(PART1Y + PART2Y + PART3Y)*ANGLEDIFF(1))/DSQRT(PART4Y)
	   ENDIF
		 
	   RFH3OBENDY = RFH3OBENDY + RFH3OBENDY_TEMP1
	   
	   PART1Y = -1.0D0*DYOH(2)*VECTSQ(3)/(VROH(3)*VROH(2)**3)
	   PART2Y = (DYOH(3)+DYOH(2))/(VROH(3)*VROH(2))
	   PART3Y = -1.0D0*DYOH(3)*VECTSQ(3)/(VROH(2)*VROH(3)**3)
	   PART4Y = 1.0D0 - VECTSQ(3)**2/((VROH(3)**2)*(VROH(2)**2))
	      
	   IF (DABS(PART4Y)<NUMERICALZEROLIMIT) THEN
	      RFH3OBENDY_TEMP1 = LARGE_FORCE
	   ELSE
	      RFH3OBENDY_TEMP1 = (KALPHA*(PART1Y + PART2Y + PART3Y)*ANGLEDIFF(3))/DSQRT(PART4Y)
	   ENDIF
	   
	   RFH3OBENDY = RFH3OBENDY + RFH3OBENDY_TEMP1 

	   PART1Y = -1.0D0*DYOH(3)*VECTSQ(2)/(VROH(1)*VROH(3)**3)
	   PART2Y = (DYOH(1)+DYOH(3))/(VROH(1)*VROH(3))
	   PART3Y = -1.0D0*DYOH(1)*VECTSQ(2)/(VROH(3)*VROH(1)**3)
	   PART4Y = 1.0D0 - VECTSQ(2)**2/((VROH(1)**2)*(VROH(3)**2))

	   IF (DABS(PART4Y)<NUMERICALZEROLIMIT) THEN
	      RFH3OBENDY_TEMP1 = LARGE_FORCE
	   ELSE
	      RFH3OBENDY_TEMP1 = (KALPHA*(PART1Y + PART2Y + PART3Y)*ANGLEDIFF(2))/DSQRT(PART4Y)
	   ENDIF

	   RFH3OBENDY = RFH3OBENDY + RFH3OBENDY_TEMP1 
!---------------------------------------------------------------------
!  Z
!---------------------------------------------------------------------
	   PART1Z = -1.0D0*DZOH(1)*VECTSQ(1)/(VROH(2)*VROH(1)**3)
	   PART2Z = (DZOH(2)+DZOH(1))/(VROH(2)*VROH(1))
	   PART3Z = -1.0D0*DZOH(2)*VECTSQ(1)/(VROH(1)*VROH(2)**3)
	   PART4Z = 1.0D0 - VECTSQ(1)**2/((VROH(2)**2)*(VROH(1)**2))

	   IF (DABS(PART4Z)<NUMERICALZEROLIMIT) THEN
	      RFH3OBENDZ_TEMP1 = LARGE_FORCE
	   ELSE
	      RFH3OBENDZ_TEMP1 = (KALPHA*(PART1Z + PART2Z + PART3Z)*ANGLEDIFF(1))/DSQRT(PART4Z)
	   ENDIF
	   
	   RFH3OBENDZ = RFH3OBENDZ + RFH3OBENDZ_TEMP1
	   
	   PART1Z = -1.0D0*DZOH(2)*VECTSQ(3)/(VROH(3)*VROH(2)**3)
	   PART2Z = (DZOH(3)+DZOH(2))/(VROH(3)*VROH(2))
	   PART3Z = -1.0D0*DZOH(3)*VECTSQ(3)/(VROH(2)*VROH(3)**3)
	   PART4Z = 1.0D0 - VECTSQ(3)**2/((VROH(3)**2)*(VROH(2)**2))

	   IF (DABS(PART4Z)<NUMERICALZEROLIMIT) THEN
	      RFH3OBENDZ_TEMP1 = LARGE_FORCE
	   ELSE
	      RFH3OBENDZ_TEMP1 = (KALPHA*(PART1Z + PART2Z + PART3Z)*ANGLEDIFF(3))/DSQRT(PART4Z)
	   ENDIF
	      
	   RFH3OBENDZ = RFH3OBENDZ + RFH3OBENDZ_TEMP1   

	   PART1Z = -1.0D0*DZOH(3)*VECTSQ(2)/(VROH(1)*VROH(3)**3)
	   PART2Z = (DZOH(1)+DZOH(3))/(VROH(1)*VROH(3))
	   PART3Z = -1.0D0*DZOH(1)*VECTSQ(2)/(VROH(3)*VROH(1)**3)
	   PART4Z = 1.0D0 - VECTSQ(2)**2/((VROH(1)**2)*(VROH(3)**2))

	   IF (DABS(PART4Z)<NUMERICALZEROLIMIT) THEN
	      RFH3OBENDZ_TEMP1 = LARGE_FORCE
	   ELSE
	      RFH3OBENDZ_TEMP1 = (KALPHA*(PART1Z + PART2Z + PART3Z)*ANGLEDIFF(2))/DSQRT(PART4Z)
	   ENDIF

	   RFH3OBENDZ = RFH3OBENDZ + RFH3OBENDZ_TEMP1   
 	     
	ELSE

!---------------------------------------------------------------------
!  HYDROGEN
!---------------------------------------------------------------------   
           IF (ATOMPOS.EQ.1) THEN
              OTHERB1 = ATMPL(VBSTATE,2)
              OTHERB2 = ATMPL(VBSTATE,4)
           ELSEIF (ATOMPOS.EQ.2) THEN
              OTHERB1 = ATMPL(VBSTATE,1)
              OTHERB2 = ATMPL(VBSTATE,4)
	   ELSE
	      OTHERB1 = ATMPL(VBSTATE,1)
	      OTHERB2 = ATMPL(VBSTATE,2)
           ENDIF

           DO I = 1,3
              ROH(I) = 0.0D0
              THETA(I) = 0.0D0
           ENDDO

!----DETERMINE THE O-H DISTANCES IN HYDRONIUM
           DXROH(1) = PSIX(ATOMNO) - PSIX(ATMPL(VBSTATE,3))
           DYROH(1) = PSIY(ATOMNO) - PSIY(ATMPL(VBSTATE,3))
           DZROH(1) = PSIZ(ATOMNO) - PSIZ(ATMPL(VBSTATE,3))
	   ROH(1) = INTERATOMICR(ATOMNO,ATMPL(VBSTATE,3))

           DXROH(2) = PSIX(OTHERB1) - PSIX(ATMPL(VBSTATE,3))
           DYROH(2) = PSIY(OTHERB1) - PSIY(ATMPL(VBSTATE,3))
           DZROH(2) = PSIZ(OTHERB1) - PSIZ(ATMPL(VBSTATE,3))
	   ROH(2) = INTERATOMICR(OTHERB1,ATMPL(VBSTATE,3))

           DXROH(3) = PSIX(OTHERB2) - PSIX(ATMPL(VBSTATE,3))
           DYROH(3) = PSIY(OTHERB2) - PSIY(ATMPL(VBSTATE,3))
           DZROH(3) = PSIZ(OTHERB2) - PSIZ(ATMPL(VBSTATE,3))
	   ROH(3) = INTERATOMICR(OTHERB2,ATMPL(VBSTATE,3))

!----DETERMINE THE BENDING ANGLES, ALPHA
           THETA(1) = DXROH(1)*DXROH(2)+DYROH(1)*DYROH(2) &
                        + DZROH(1)*DZROH(2)
	   THETA(1) = CHECKED_ACOS(THETA(1)/(ROH(1)*ROH(2)))

           THETA(2) = DXROH(3)*DXROH(1)+DYROH(3)*DYROH(1) &
                        + DZROH(3)*DZROH(1)
           THETA(2) = CHECKED_ACOS(THETA(2)/(ROH(3)*ROH(1)))

	   VECTSQ(1) = DXROH(1)*DXROH(2) + DYROH(1)*DYROH(2) + DZROH(1)*DZROH(2)
	   VECTSQ(2) = DXROH(1)*DXROH(3) + DYROH(1)*DYROH(3) + DZROH(1)*DZROH(3)
	   ANGLEDIFF(1) = THETA(1) - ALPHAEQ
	   ANGLEDIFF(2) = THETA(2) - ALPHAEQ

!---------------------------------------------------------------------
!  X
!---------------------------------------------------------------------
!----CONSIDER THE FIRST ANGLE
	   PART1X = DXROH(1)*VECTSQ(1)/(ROH(2)*ROH(1)**3)
	   PART2X = DXROH(2)/(ROH(1)*ROH(2))
	   PART3X = 1.0D0 - (VECTSQ(1)/(ROH(1)*ROH(2)))**2 ! = (SIN(ALPHA))^2

! CHECK, THERE IS A DISCONTINUITY IN THE POTENTIAL/FORCE WHEN ALPHA = 180

	   IF (DABS(PART3X)<NUMERICALZEROLIMIT) THEN
	      RFH3OBENDX_TEMP1 = LARGE_FORCE
	   ELSE
	      RFH3OBENDX_TEMP1 = (KALPHA*(PART1X - PART2X)*ANGLEDIFF(1))/DSQRT(PART3X)
	   ENDIF

!----CONSIDER THE SECOND ANGLE
	   PART1X = DXROH(1)*VECTSQ(2)/(ROH(3)*ROH(1)**3)
	   PART2X = DXROH(3)/(ROH(1)*ROH(3))
	   PART3X = 1.0D0 - VECTSQ(2)**2/((ROH(1)**2)*(ROH(3)**2))

	   IF (DABS(PART3X)<NUMERICALZEROLIMIT) THEN
	      RFH3OBENDX_TEMP1 = LARGE_FORCE
	   ELSE
	      RFH3OBENDX_TEMP2 = (KALPHA*(PART1X - PART2X)*ANGLEDIFF(2))/DSQRT(PART3X)
	   ENDIF

!----SUM UP THE CONTRIBUTIONS
	   RFH3OBENDX = RFH3OBENDX_TEMP1 + RFH3OBENDX_TEMP2
!---------------------------------------------------------------------
!  Y
!---------------------------------------------------------------------
!----CONSIDER THE FIRST ANGLE
	   PART1Y = DYROH(1)*VECTSQ(1)/(ROH(2)*ROH(1)**3)
	   PART2Y = DYROH(2)/(ROH(1)*ROH(2))
	   PART3Y = 1.0D0 - VECTSQ(1)**2/((ROH(1)**2)*(ROH(2)**2))

	   IF (DABS(PART3Y)<NUMERICALZEROLIMIT) THEN
	      RFH3OBENDY_TEMP1 = LARGE_FORCE
	   ELSE
	      RFH3OBENDY_TEMP1 = (KALPHA*(PART1Y - PART2Y)*ANGLEDIFF(1))/DSQRT(PART3Y)
	   ENDIF

!----CONSIDER THE SECOND ANGLE
	   PART1Y = DYROH(1)*VECTSQ(2)/(ROH(3)*ROH(1)**3)
	   PART2Y = DYROH(3)/(ROH(1)*ROH(3))
	   PART3Y = 1.0D0 - VECTSQ(2)**2/((ROH(1)**2)*(ROH(3)**2))

	   IF (DABS(PART3Y)<NUMERICALZEROLIMIT) THEN
	      RFH3OBENDY_TEMP2 = LARGE_FORCE
	   ELSE
	      RFH3OBENDY_TEMP2 = (KALPHA*(PART1Y - PART2Y)*ANGLEDIFF(2))/DSQRT(PART3Y)
	   ENDIF

!----SUM UP THE CONTRIBUTIONS
	   RFH3OBENDY = RFH3OBENDY_TEMP1 + RFH3OBENDY_TEMP2  

!---------------------------------------------------------------------
!  Z
!---------------------------------------------------------------------
!----CONSIDER THE FIRST ANGLE
	   PART1Z = DZROH(1)*VECTSQ(1)/(ROH(2)*ROH(1)**3)
	   PART2Z = DZROH(2)/(ROH(1)*ROH(2))
	   PART3Z = 1.0D0 - VECTSQ(1)**2/((ROH(1)**2)*(ROH(2)**2))

	   IF (DABS(PART3Z)<NUMERICALZEROLIMIT) THEN
	      RFH3OBENDZ_TEMP1 = LARGE_FORCE
	   ELSE
	      RFH3OBENDZ_TEMP1 = (KALPHA*(PART1Z - PART2Z)*ANGLEDIFF(1))/DSQRT(PART3Z)
	   ENDIF

!----CONSIDER THE SECOND ANGLE
	   PART1Z = DZROH(1)*VECTSQ(2)/(ROH(3)*ROH(1)**3)
	   PART2Z = DZROH(3)/(ROH(1)*ROH(3))
	   PART3Z = 1.0D0 - VECTSQ(2)**2/((ROH(1)**2)*(ROH(3)**2))

	   IF (DABS(PART3Z)<NUMERICALZEROLIMIT) THEN
	      RFH3OBENDZ_TEMP2 = LARGE_FORCE
	   ELSE
	      RFH3OBENDZ_TEMP2 = (KALPHA*(PART1Z - PART2Z)*ANGLEDIFF(2))/DSQRT(PART3Z)
	   ENDIF

!----SUM UP THE CONTRIBUTIONS
	   RFH3OBENDZ = RFH3OBENDZ_TEMP1 + RFH3OBENDZ_TEMP2  

!----END OF THE CONDITIONAL STATEMENT (IF(ATOMPOS.NE.3)---
        ENDIF

!---------------------------------------------------------------------
! FINALLY SUM THE FORCE COMPONENTS TO GET THE TOTAL FORCE
!
!---------------------------------------------------------------------

        FH3OINTRAX = RFH3OBENDX + RFH3OSTRX
        FH3OINTRAY = RFH3OBENDY + RFH3OSTRY
        FH3OINTRAZ = RFH3OBENDZ + RFH3OSTRZ

! DEBUGGING

!	H3O_INTRA_FORCES(VBSTATE,(3*ATOMNO)-2) = FH3OINTRAX
!	H3O_INTRA_FORCES(VBSTATE,(3*ATOMNO)-1) = FH3OINTRAY
!	H3O_INTRA_FORCES(VBSTATE,(3*ATOMNO)) = FH3OINTRAZ	

        RETURN
        END

!#####################################################################
!############## SUBROUTINE FINTER ####################################
!#####################################################################

	SUBROUTINE FINTER(ATOMPOS,VBSTATE,FINTERX,FINTERY,FINTERZ)

	USE COMMONS
	USE MSEVB_COMMON

	IMPLICIT NONE

!---------------------------------------------------------------------------
! 06/08/99 R.A. CHRISTIE
! ROUTINE TO DETERMINE THE FORCES RESULTING FROM THE H3O+ - H2O INTERACTION
!
! NEED AS INPUT INTO THIS ROUTINE: 	ATOMPOS (ATOM # IN QUESTION)
!
! TYPE SCENARIOS:
!	1. ATOM IN Q IS HYDROGEN ATOM; ONLY HAS COULOMB INTERACTION.
!	2. ATOM IN Q IS A OXYGEN ATOM; COULOMB, REPULSE AND LJ INTERACTION.
!---------------------------------------------------------------------------

!----INCOMING VARIABLES
	DOUBLE PRECISION FINTERX,FINTERY,FINTERZ
	INTEGER ATOMPOS,VBSTATE,ATOMNO
!----LOCAL VARIABLES 
	DOUBLE PRECISION QI,QJ,RFCOULOMB,DX,DY,DZ,RIJ,TRIG,RFREPULSE,FREPULSE, &
      	  	RFLJ,FLJ,ROO,ROO2,ROO8,ROO14,FCOULOMBX,FCOULOMBY,FCOULOMBZ	
	INTEGER I,J
!----NEW VARIABLES:
	DOUBLE PRECISION FLJX,FLJY,FLJZ,FREPULSEX,FREPULSEY,FREPULSEZ,ROO_SIGMA
	INTEGER WHEECH

! DEBUGGING VARIABLES

	INTEGER COORD_POS

!----INITIALIZE VARIABLES
	RFCOULOMB = 0.0D0
	FCOULOMBX = 0.0D0
	FCOULOMBY = 0.0D0
	FCOULOMBZ = 0.0D0
	FLJX = 0.0D0
	FLJY = 0.0D0
	FLJZ = 0.0D0
	RFLJ = 0.0D0
	FREPULSEX = 0.0D0
	FREPULSEY = 0.0D0
	FREPULSEZ = 0.0D0
	DX = 0.0D0
	DY = 0.0D0
	DZ = 0.0D0
	FREPULSE = 0.0D0
	WHEECH = 1
	ROO_SIGMA = 0.0D0

! NUMBER OF THE ATOM IN THE ORIGINAL INPUT VECTORS

	ATOMNO = ATMPL(VBSTATE,ATOMPOS)

!---------------------------------------------------------------------
! DETERMINE THE COULOMBIC PART OF THE INTERACTION FIRST
!
! TWO POSSIBILITIES:
!   1. ATOM IS IN HYDRONIUM UNIT
!   2. ATOM IS IN SOLVATING WATER MOLECULE
!
! THIS PART OF THE CODE CALCULATES THE COULOMBIC INTERACTION OF BOTH
! OXYGEN AND HYDROGEN ATOMS.
!
! ** NB ** UNITS FOR COULOMBIC  INTERACTION SHOULD BE KCAL/ANGSTROMS
!
!---------------------------------------------------------------------

	IF (ATOMPOS.LE.4) THEN
!----CASE 1. WHEN ATOM Q IS IN HYDRONIUM
	   IF (ATOMPOS.EQ.3) THEN
	      QI = QINTERO
	   ELSE
	      QI = QINTERH
	   ENDIF
	   DO J = 5,NATOMS
	      WHEECH = ATMPL(VBSTATE,J)
	      IF (MOD(WHEECH,3).EQ.0) THEN
                 QJ = QTIP3P_O
              ELSE
                 QJ = QTIP3P_H
              ENDIF
              DX = PSIX(ATOMNO) - PSIX(WHEECH)
              DY = PSIY(ATOMNO) - PSIY(WHEECH)
              DZ = PSIZ(ATOMNO) - PSIZ(WHEECH)
	      RIJ = INTERATOMICR(ATOMNO,WHEECH)
 	      RFCOULOMB = -1.0D0*DAMPCHGE*(QI*QJ*FOURPIEO)/(RIJ**3)
	      FCOULOMBX = RFCOULOMB*DX + FCOULOMBX
	      FCOULOMBY = RFCOULOMB*DY + FCOULOMBY
	      FCOULOMBZ = RFCOULOMB*DZ + FCOULOMBZ
           ENDDO 
	ELSE

!----CASE 2. WHEN ATOM IN Q IS IN WATER MOLECULE
	   IF (MOD(ATOMPOS,3).EQ.0) THEN
              QI = QTIP3P_O
           ELSE
              QI = QTIP3P_H
           ENDIF
	   DO J = 1,4
	      WHEECH = ATMPL(VBSTATE,J)
              IF (MOD(J,3).EQ.0) THEN
                 QJ = QINTERO
              ELSE
                 QJ = QINTERH
              ENDIF
              DX = PSIX(ATOMNO) - PSIX(WHEECH)
              DY = PSIY(ATOMNO) - PSIY(WHEECH)
              DZ = PSIZ(ATOMNO) - PSIZ(WHEECH)
	      RIJ = INTERATOMICR(ATOMNO,WHEECH)
   	      RFCOULOMB = -1.0D0*DAMPCHGE*(QI*QJ*FOURPIEO)/(RIJ**3)
              FCOULOMBX = RFCOULOMB*DX + FCOULOMBX
	      FCOULOMBY = RFCOULOMB*DY + FCOULOMBY
	      FCOULOMBZ = RFCOULOMB*DZ + FCOULOMBZ
	   ENDDO
	ENDIF

!---------------------------------------------------------------------
! CALCULATE THE LJ AND REPULSIVE INTERACTIONS
!
! THIS PART OF THE CODE ONLY APPLIES TO OXYGEN ATOMS, AND APPLIES TO
! BOTH HYDRONIUM AND SOLVATING WATER MOLECULE OXYGEN ATOMS
!
!
!---------------------------------------------------------------------

	IF (MOD(ATOMPOS,3).EQ.0) THEN
!----------------OXYGEN ATOM ON WATER MOLECULE
	   IF (ATOMPOS.NE.3) THEN
	       DX = PSIX(ATOMNO) - PSIX(ATMPL(VBSTATE,3))
	       DY = PSIY(ATOMNO) - PSIY(ATMPL(VBSTATE,3))
	       DZ = PSIZ(ATOMNO) - PSIZ(ATMPL(VBSTATE,3))
	       ROO = INTERATOMICR(ATOMNO,ATMPL(VBSTATE,3))
 	       ROO_SIGMA = SIGMA_MIX/ROO
	       ROO14 = ROO_SIGMA**14
	       ROO8 = ROO_SIGMA**8
 	       RFLJ = (-6.0D0/SIGMA_MIX**2)*EPSILON_MIX*(2.0D0*ROO14 - ROO8)
	       FLJX = RFLJ*DX
	       FLJY = RFLJ*DY
	       FLJZ = RFLJ*DZ	
	       TRIG = DTANH(SMALL_B*(ROO-DOOEQ))
	       FREPULSE = (-1.0D00/ROO)*SMALL_B*BIG_B*(1.0D0 - TRIG**2)
	       FREPULSEX = FREPULSE*DX
	       FREPULSEY = FREPULSE*DY
	       FREPULSEZ = FREPULSE*DZ
	   ELSE
!----------------OXYGEN ATOM ON HYDRONIUM ION
	       DO I = 6,(NATOMS-1),3
 		  DX = PSIX(ATOMNO) - PSIX(ATMPL(VBSTATE,I))
 	          DY = PSIY(ATOMNO) - PSIY(ATMPL(VBSTATE,I))
 	 	  DZ = PSIZ(ATOMNO) - PSIZ(ATMPL(VBSTATE,I))
		  ROO = INTERATOMICR(ATOMNO,ATMPL(VBSTATE,I))
 	          ROO_SIGMA = SIGMA_MIX/ROO
                  ROO8 = ROO_SIGMA**8
                  ROO14 = ROO_SIGMA**14 
                  RFLJ = (-6.0D0/SIGMA_MIX**2)*EPSILON_MIX*(2.0D0*ROO14 - ROO8)
                  TRIG = DTANH(SMALL_B*(ROO-DOOEQ))
		  RFREPULSE = (-1.0D00/ROO)*SMALL_B*BIG_B*(1.0D0 - TRIG**2)
	          FLJX = FLJX + RFLJ*DX
		  FLJY = FLJY + RFLJ*DY
                  FLJZ = FLJZ + RFLJ*DZ
	          FREPULSEX = FREPULSEX + RFREPULSE*DX
		  FREPULSEY = FREPULSEY + RFREPULSE*DY
		  FREPULSEZ = FREPULSEZ + RFREPULSE*DZ
	      ENDDO
	   ENDIF
!----END OF OXYGEN-ATOM CASE
	ENDIF

 	IF (MOD(ATOMPOS,3).EQ.0) THEN
 	   FINTERX = 1.0D0*(FLJX+FREPULSEX+FCOULOMBX)
 	   FINTERY = 1.0D0*(FLJY+FREPULSEY+FCOULOMBY)
 	   FINTERZ = 1.0D0*(FLJZ+FREPULSEZ+FCOULOMBZ)
 	ELSE
 	   FINTERX = 1.0D0*FCOULOMBX
 	   FINTERY = 1.0D0*FCOULOMBY
 	   FINTERZ = 1.0D0*FCOULOMBZ
 	ENDIF

! DEBUGGING

!	COORD_POS=3*ATOMNO-2

!	LJ_FORCES(EIGENSTATE,COORD_POS) = FLJX
!	LJ_FORCES(EIGENSTATE,COORD_POS+1) = FLJY
!	LJ_FORCES(EIGENSTATE,COORD_POS+2) = FLJZ
!	COULOMB_FORCES(EIGENSTATE,COORD_POS) = FCOULOMBX
!	COULOMB_FORCES(EIGENSTATE,COORD_POS+1) = FCOULOMBY
!	COULOMB_FORCES(EIGENSTATE,COORD_POS+2) = FCOULOMBZ
!	REP_FORCES(EIGENSTATE,COORD_POS) = FREPULSEX
!	REP_FORCES(EIGENSTATE,COORD_POS+1) = FREPULSEY
!	REP_FORCES(EIGENSTATE,COORD_POS+2) = FREPULSEZ

!	H3O_H2O_FORCES(VBSTATE,COORD_POS) = FINTERX
!	H3O_H2O_FORCES(VBSTATE,COORD_POS+1) = FINTERY
!	H3O_H2O_FORCES(VBSTATE,COORD_POS+2) = FINTERZ	

	RETURN
	END

!#####################################################################

! CALCULATE THE H2O-H2O INTERACTION FORCES ALL IN ONE GO

	SUBROUTINE CALCULATEH2OINTERFORCES (H2OINTERXFORCES, H2OINTERYFORCES, H2OINTERZFORCES)

	USE COMMONS
	USE MSEVB_COMMON

	IMPLICIT NONE

! SUBROUTINE ARGUMENTS

	DOUBLE PRECISION, INTENT(OUT) :: H2OINTERXFORCES(NATOMS, REDUCED_NUM_EIG)
	DOUBLE PRECISION, INTENT(OUT) :: H2OINTERYFORCES(NATOMS, REDUCED_NUM_EIG)
	DOUBLE PRECISION, INTENT(OUT) :: H2OINTERZFORCES(NATOMS, REDUCED_NUM_EIG)

! LOCAL VARIABLES

	DOUBLE PRECISION :: XFORCES(NATOMS, NATOMS)
	DOUBLE PRECISION :: YFORCES(NATOMS, NATOMS)
	DOUBLE PRECISION :: ZFORCES(NATOMS, NATOMS)
	
	INTEGER :: ATOM1, ATOM2, CURRENTOATOM, HATOM1, HATOM2
	INTEGER :: CURRENTVBSTATE
	DOUBLE PRECISION :: CHARGEONATOM1, CHARGEONATOM2
	DOUBLE PRECISION :: DX, DY, DZ
	DOUBLE PRECISION :: COULOMBPREFACTOR
	DOUBLE PRECISION :: INVROO2, SIGMAINVROO6, LJPREFACTOR
	DOUBLE PRECISION, PARAMETER :: LJCONSTANT = -24.0D0*H2OINTEREPSILON
	DOUBLE PRECISION, PARAMETER :: H2OINTERSIGMA_SQ = H2OINTERSIGMA**2

! INITIALISE

	XFORCES = 0.0
	YFORCES = 0.0
	ZFORCES = 0.0

	H2OINTERXFORCES = 0.0
	H2OINTERYFORCES = 0.0
	H2OINTERZFORCES = 0.0

! CALCULATE THE INTERACTIONS

	DO ATOM1 = 1, (NATOMS-1)

	   IF (MOD(ATOM1,3).EQ.0) THEN
	      CHARGEONATOM1 = QTIP3P_O
	   ELSE
	      CHARGEONATOM1 = QTIP3P_H
	   ENDIF

	   DO ATOM2 = (ATOM1+1), NATOMS

	      IF (MOD(ATOM2,3).EQ.0) THEN
		 CHARGEONATOM2 = QTIP3P_O
	      ELSE
		 CHARGEONATOM2 = QTIP3P_H
	      ENDIF

! DETERMINE THE COULOMBIC PART OF THE FORCE

	      DX = PSIX(ATOM1) - PSIX(ATOM2)   ! DEFINED THIS WAY AROUND FOR CONSISTENCY
	      DY = PSIY(ATOM1) - PSIY(ATOM2)
	      DZ = PSIZ(ATOM1) - PSIZ(ATOM2)      

	      COULOMBPREFACTOR = -1.0D0*FOURPIEO*CHARGEONATOM1*CHARGEONATOM2/((INTERATOMICR(ATOM1,ATOM2))**3)

! XFORCES(I,J) IS THE FORCE ON ATOM I DUE TO PRESENCE OF ATOM J
! XFORCES(J,I) = -XFORCES(I,J) BECAUSE NEWTON`S LAW HOLDS

	      XFORCES(ATOM1,ATOM2) = COULOMBPREFACTOR * DX
	      YFORCES(ATOM1,ATOM2) = COULOMBPREFACTOR * DY
	      ZFORCES(ATOM1,ATOM2) = COULOMBPREFACTOR * DZ

! DETERMINE THE LJ PART OF THE FORCE IF NECESSARY

	      IF (CHARGEONATOM1.EQ.QTIP3P_O .AND. CHARGEONATOM2.EQ.QTIP3P_O) THEN
		 INVROO2 = 1.0D0/(INTERATOMICR(ATOM1,ATOM2)**2)
		 SIGMAINVROO6 = H2OINTERSIGMA_SQ*INVROO2
		 SIGMAINVROO6 = SIGMAINVROO6**3

		 LJPREFACTOR = LJCONSTANT*(2.0D0*(SIGMAINVROO6**2) - SIGMAINVROO6)*INVROO2

		 XFORCES(ATOM1,ATOM2) = XFORCES(ATOM1,ATOM2) + LJPREFACTOR*DX
		 YFORCES(ATOM1,ATOM2) = YFORCES(ATOM1,ATOM2) + LJPREFACTOR*DY
		 ZFORCES(ATOM1,ATOM2) = ZFORCES(ATOM1,ATOM2) + LJPREFACTOR*DZ
	      ENDIF

! FILL IN THE LOWER TRIANGLE EXPLICITLY
! THIS MAKES IT EASIER THAN TRYING TO WORK OUT WHICH NUMBER IS LOWER ALL THE TIME IN THE NEXT SECTION

	      XFORCES(ATOM2,ATOM1) = -1.0D0 *  XFORCES(ATOM1,ATOM2)
	      YFORCES(ATOM2,ATOM1) = -1.0D0 *  YFORCES(ATOM1,ATOM2)	      
	      ZFORCES(ATOM2,ATOM1) = -1.0D0 *  ZFORCES(ATOM1,ATOM2)	      

! ADD THE NEW FORCES TO THE ACCUMULATING TOTALS

	      H2OINTERXFORCES(ATOM1,1) = H2OINTERXFORCES(ATOM1,1) + XFORCES(ATOM1,ATOM2)
	      H2OINTERXFORCES(ATOM2,1) = H2OINTERXFORCES(ATOM2,1) - XFORCES(ATOM1,ATOM2)	      

	      H2OINTERYFORCES(ATOM1,1) = H2OINTERYFORCES(ATOM1,1) + YFORCES(ATOM1,ATOM2)
	      H2OINTERYFORCES(ATOM2,1) = H2OINTERYFORCES(ATOM2,1) - YFORCES(ATOM1,ATOM2)

	      H2OINTERZFORCES(ATOM1,1) = H2OINTERZFORCES(ATOM1,1) + ZFORCES(ATOM1,ATOM2)
	      H2OINTERZFORCES(ATOM2,1) = H2OINTERZFORCES(ATOM2,1) - ZFORCES(ATOM1,ATOM2)
	   ENDDO
	ENDDO
	
! COPY ACROSS THE ACCUMULATED TOTALS

	DO CURRENTVBSTATE = 2, REDUCED_NUM_EIG
	   H2OINTERXFORCES(:,CURRENTVBSTATE) =  H2OINTERXFORCES(:,1)
	   H2OINTERYFORCES(:,CURRENTVBSTATE) =  H2OINTERYFORCES(:,1)
	   H2OINTERZFORCES(:,CURRENTVBSTATE) =  H2OINTERZFORCES(:,1)
	ENDDO

! SUBTRACT FOR EACH VB STATE THOSE INTERACTIONS WHICH ARE WRONGLY INCLUDED IN THE TOTALS

	DO CURRENTVBSTATE = 1, REDUCED_NUM_EIG

! FIRSTLY MAKE ZERO THE FORCES FOR THOSE ATOMS IN THE HYDRONIUM SPECIES

	   DO ATOM1 = 1, 4
	      H2OINTERXFORCES(ATMPL(CURRENTVBSTATE,ATOM1),CURRENTVBSTATE) = 0.0	      
	      H2OINTERYFORCES(ATMPL(CURRENTVBSTATE,ATOM1),CURRENTVBSTATE) = 0.0	      
	      H2OINTERZFORCES(ATMPL(CURRENTVBSTATE,ATOM1),CURRENTVBSTATE) = 0.0	      
	   ENDDO

! OTHER ATOMS

	   DO ATOM1 = 6, (NATOMS-1), 3

	      CURRENTOATOM = ATMPL(CURRENTVBSTATE,ATOM1)
	      HATOM1 = ATMPL(CURRENTVBSTATE,ATOM1-1)
	      HATOM2 = ATMPL(CURRENTVBSTATE,ATOM1+1)

! REMOVE INTERACTIONS BETWEEN OTHER ATOMS AND THE HYDRONIUM ATOM

	      DO ATOM2 = 1,4
! O-ATOM
		 H2OINTERXFORCES(CURRENTOATOM,CURRENTVBSTATE) =   &
      		 H2OINTERXFORCES(CURRENTOATOM,CURRENTVBSTATE) - XFORCES(CURRENTOATOM, ATMPL(CURRENTVBSTATE,ATOM2))
  		 H2OINTERYFORCES(CURRENTOATOM,CURRENTVBSTATE) =   &
      		 H2OINTERYFORCES(CURRENTOATOM,CURRENTVBSTATE) - YFORCES(CURRENTOATOM, ATMPL(CURRENTVBSTATE,ATOM2))
		 H2OINTERZFORCES(CURRENTOATOM,CURRENTVBSTATE) =   &
      		 H2OINTERZFORCES(CURRENTOATOM,CURRENTVBSTATE) - ZFORCES(CURRENTOATOM, ATMPL(CURRENTVBSTATE,ATOM2))

! H-ATOM 1
		 H2OINTERXFORCES(HATOM1,CURRENTVBSTATE) =   &
      		 H2OINTERXFORCES(HATOM1,CURRENTVBSTATE) - XFORCES(HATOM1, ATMPL(CURRENTVBSTATE,ATOM2))
		 H2OINTERYFORCES(HATOM1,CURRENTVBSTATE) =   &
      		 H2OINTERYFORCES(HATOM1,CURRENTVBSTATE) - YFORCES(HATOM1, ATMPL(CURRENTVBSTATE,ATOM2))
		 H2OINTERZFORCES(HATOM1,CURRENTVBSTATE) =   &
      		 H2OINTERZFORCES(HATOM1,CURRENTVBSTATE) - ZFORCES(HATOM1, ATMPL(CURRENTVBSTATE,ATOM2))

! H-ATOM 2
		 H2OINTERXFORCES(HATOM2,CURRENTVBSTATE) =  &
      		 H2OINTERXFORCES(HATOM2,CURRENTVBSTATE) - XFORCES(HATOM2, ATMPL(CURRENTVBSTATE,ATOM2))
		 H2OINTERYFORCES(HATOM2,CURRENTVBSTATE) =  &
      		 H2OINTERYFORCES(HATOM2,CURRENTVBSTATE) - YFORCES(HATOM2, ATMPL(CURRENTVBSTATE,ATOM2))
		 H2OINTERZFORCES(HATOM2,CURRENTVBSTATE) =  &
      		 H2OINTERZFORCES(HATOM2,CURRENTVBSTATE) - ZFORCES(HATOM2, ATMPL(CURRENTVBSTATE,ATOM2))
	      ENDDO

! REMOVE INTERACTIONS BETWEEN ATOMS IN THE SAME WATER MOLECULE

! O-ATOM
		 H2OINTERXFORCES(CURRENTOATOM,CURRENTVBSTATE) = H2OINTERXFORCES(CURRENTOATOM,CURRENTVBSTATE) - &
      		 XFORCES(CURRENTOATOM, HATOM1) - XFORCES(CURRENTOATOM, HATOM2)
		 H2OINTERYFORCES(CURRENTOATOM,CURRENTVBSTATE) = H2OINTERYFORCES(CURRENTOATOM,CURRENTVBSTATE) - &
      		 YFORCES(CURRENTOATOM, HATOM1) - YFORCES(CURRENTOATOM, HATOM2)
		 H2OINTERZFORCES(CURRENTOATOM,CURRENTVBSTATE) = H2OINTERZFORCES(CURRENTOATOM,CURRENTVBSTATE) - &
      		 ZFORCES(CURRENTOATOM, HATOM1) - ZFORCES(CURRENTOATOM, HATOM2)

! H-ATOM 1
		 H2OINTERXFORCES(HATOM1,CURRENTVBSTATE) = H2OINTERXFORCES(HATOM1,CURRENTVBSTATE) - &
      		 XFORCES(HATOM1, CURRENTOATOM) - XFORCES(HATOM1, HATOM2)
		 H2OINTERYFORCES(HATOM1,CURRENTVBSTATE) = H2OINTERYFORCES(HATOM1,CURRENTVBSTATE) - &
      		 YFORCES(HATOM1, CURRENTOATOM) - YFORCES(HATOM1, HATOM2)
		 H2OINTERZFORCES(HATOM1,CURRENTVBSTATE) = H2OINTERZFORCES(HATOM1,CURRENTVBSTATE) - &
      		 ZFORCES(HATOM1, CURRENTOATOM) - ZFORCES(HATOM1, HATOM2)

! H-ATOM 2
		 H2OINTERXFORCES(HATOM2,CURRENTVBSTATE) = H2OINTERXFORCES(HATOM2,CURRENTVBSTATE) - &
      		 XFORCES(HATOM2, CURRENTOATOM) - XFORCES(HATOM2, HATOM1)
		 H2OINTERYFORCES(HATOM2,CURRENTVBSTATE) = H2OINTERYFORCES(HATOM2,CURRENTVBSTATE) - &
      		 YFORCES(HATOM2, CURRENTOATOM) - YFORCES(HATOM2, HATOM1)
		 H2OINTERZFORCES(HATOM2,CURRENTVBSTATE) = H2OINTERZFORCES(HATOM2,CURRENTVBSTATE) - &
      		 ZFORCES(HATOM2, CURRENTOATOM) - ZFORCES(HATOM2, HATOM1)
	   ENDDO
	ENDDO

	RETURN

	END SUBROUTINE

!#####################################################################
!###################### SUBROUTINE FH2OINTER #########################
!#####################################################################

	SUBROUTINE FH2OINTER(ATOMPOS,VBSTATE,FH2OINTERX,FH2OINTERY,FH2OINTERZ)

	USE COMMONS
	USE MSEVB_COMMON

	IMPLICIT NONE

!---------------------------------------------------------------------------
!  06/08/99 R.A. CHRISTIE
! ROUTINE FOR DETERMINING THE INTERMOLECULAR WATER-WATER FORCES
!
!---------------------------------------------------------------------------

	DOUBLE PRECISION FH2OINTERX,FH2OINTERY,FH2OINTERZ
	INTEGER ATOMPOS,VBSTATE,ATOMNO
	DOUBLE PRECISION RFLJ,RFCOULOMB,FCOULOMBX,FCOULOMBY,FCOULOMBZ,QI,QJ,DX_OO, &
                DY_OO,DZ_OO, &
      		ROO,ROO2,ROO8,ROO14,RIJ,DX,DY,DZ,FLJX,FLJY,FLJZ
	INTEGER I,J,AVOID2,AVOID3

	DOUBLE PRECISION, PARAMETER :: LJPREFACTOR = -2.4D01*1.522D-01
	DOUBLE PRECISION :: COULOMBPREFACTOR

!----INITIALIZE VARIABLES
	COULOMBPREFACTOR = -1.0D0*FOURPIEO

	RFLJ = 0.0D0
	FLJX = 0.0D0
	FLJY = 0.0D0
	FLJZ = 0.0D0
	RFCOULOMB = 0.0D0
	FCOULOMBX = 0.0D0
	FCOULOMBY = 0.0D0
	FCOULOMBZ = 0.0D0
	
	AVOID2 = 0
	AVOID3 = 0
	DX_OO = 0.0D0
	DY_OO = 0.0D0
	DZ_OO = 0.0D0

! POSITION OF THE ATOM IN THE ORIGINAL INPUT VECTOR

	ATOMNO = ATMPL(VBSTATE,ATOMPOS)

!----FIND OUT WHICH TYPE OF ATOM IS: 

	IF (MOD(ATOMPOS,3).EQ.0) THEN	
	   QI = QTIP3P_O
	   AVOID2 = ATOMPOS - 1 
	   AVOID3 = ATOMPOS + 1

!----DETEMINE LJ PART OF FORCE IF CONSIDERING AN OXYGEN ATOM

           DO J = 6,(NATOMS-1),3

	      IF (J.EQ.ATOMPOS) CYCLE

              DX_OO = PSIX(ATOMNO) - PSIX(ATMPL(VBSTATE,J))
              DY_OO = PSIY(ATOMNO) - PSIY(ATMPL(VBSTATE,J))
              DZ_OO = PSIZ(ATOMNO) - PSIZ(ATMPL(VBSTATE,J))
	      ROO = DSQRT(DX_OO**2 + DY_OO**2 + DZ_OO**2)
	      ROO2 = ROO**2
	      ROO = 3.1506D0/ROO
	      ROO8 = ROO**6
	      ROO14 = ROO8**2
!	      RFLJ = -2.4D01*1.522D-01*(2.0D0*ROO14 - ROO8)*(1.0D0/ROO2)
	      RFLJ = LJPREFACTOR*(2.0D0*ROO14 - ROO8)/ROO2
	      FLJX = FLJX + RFLJ*DX_OO
	      FLJY = FLJY + RFLJ*DY_OO
	      FLJZ = FLJZ + RFLJ*DZ_OO
	   ENDDO

	ELSEIF (MOD(ATOMPOS+1,3).EQ.0) THEN
	   AVOID2 = ATOMPOS + 1
	   AVOID3 = ATOMPOS + 2
	   QI = QTIP3P_H
	ELSEIF (MOD(ATOMPOS-1,3).EQ.0) THEN
	   QI = QTIP3P_H
	   AVOID2 = ATOMPOS-1
	   AVOID3 = ATOMPOS-2
	ELSE
	   PRINT *, " STOPPING HERE..........#$%^&***"
	   STOP
	ENDIF

!----DETERMINE COULOMB PART OF TIP3P POTENTIAL
	DO I = 5,NATOMS
	   IF ((I.EQ.ATOMPOS).OR.(I.EQ.AVOID2).OR.(I.EQ.AVOID3)) CYCLE
	   IF (MOD(I,3).EQ.0) THEN
	      QJ = QTIP3P_O
	   ELSE
	      QJ = QTIP3P_H
	   ENDIF
	   DX = PSIX(ATOMNO) - PSIX(ATMPL(VBSTATE,I))
	   DY = PSIY(ATOMNO) - PSIY(ATMPL(VBSTATE,I))
	   DZ = PSIZ(ATOMNO) - PSIZ(ATMPL(VBSTATE,I))
	   RIJ = DSQRT(DX**2+DY**2+DZ**2)  
!	   RFCOULOMB = -1.0D0*QI*QJ*FOURPIEO/(RIJ**3)
	   RFCOULOMB = COULOMBPREFACTOR*QI*QJ/(RIJ**3)   
	   FCOULOMBX = RFCOULOMB*DX + FCOULOMBX 
	   FCOULOMBY = RFCOULOMB*DY + FCOULOMBY 
	   FCOULOMBZ = RFCOULOMB*DZ + FCOULOMBZ 
	ENDDO

	FH2OINTERX = 1.0D0*(FLJX + FCOULOMBX)
	FH2OINTERY = 1.0D0*(FLJY + FCOULOMBY)
	FH2OINTERZ = 1.0D0*(FLJZ + FCOULOMBZ)

! DEBUGGING

!	H2O_H2O_FORCES(VBSTATE,(3*ATOMNO)-2) = FH2OINTERX
!	H2O_H2O_FORCES(VBSTATE,(3*ATOMNO)-1) = FH2OINTERY
!	H2O_H2O_FORCES(VBSTATE,(3*ATOMNO)) = FH2OINTERZ	

	RETURN
	END

!#####################################################################
!####################### SUBROUTINE FH2OINTRA ########################
!#####################################################################

	SUBROUTINE FH2OINTRA(ATOMPOS,VBSTATE,FH2OINTRAX,FH2OINTRAY,FH2OINTRAZ)

	USE MSEVB_COMMON

	IMPLICIT NONE

!-------------------------------------------------------------------------
! 07/08/99 R.A. CHRISTIE
!
! ROUTINE FOR DETERMINING THE INTRAMOLECULAR WATER FORCES
!
!-------------------------------------------------------------------------

!----INCOMING VARIABLES
	INTEGER ATOMPOS,VBSTATE,ATOMNO
	DOUBLE PRECISION FH2OINTRAX,FH2OINTRAY,FH2OINTRAZ
!----LOCAL
	DOUBLE PRECISION DXROH(2),DYROH(2),DZROH(2),ROH(2),RFH2OSTRX,RFH2OSTRY, &
      		RFH2OSTRZ,RFH2OBENDX,RFH2OBENDY,RFH2OBENDZ,THETA, &
      		RFH2OBENDX1,RFH2OBENDY1,RFH2OBENDZ1,ADOTA,ADOTB,VECTSQ, &
      		ANGLEDIFF,PART1X,PART2X,PART3X,PART1Y,PART2Y,PART3Y,PART1Z, &
      		PART2Z,PART3Z,PART4X,PART4Y,PART4Z,THETA_TEMP
	INTEGER I,J,OTHERB1,OTHERB2
	CHARACTER*2 TYPE
	DOUBLE PRECISION CHECKED_ACOS

! POSITION OF THE ATOM IN THE ORIGINAL INPUT VECTOR

	ATOMNO = ATMPL(VBSTATE,ATOMPOS)

!#####################################################################
! CONSIDER WHETHER ATOM SELECTED WAS ORIGINALLY IN A HYDRONIUM
! POSITION, OR A WATER POSITION
!##################################################################### 

	IF (MOD(ATOMPOS,3).EQ.0) THEN
           TYPE = "OX"
	   OTHERB1 = ATMPL(VBSTATE,ATOMPOS+1)
           OTHERB2 = ATMPL(VBSTATE,ATOMPOS-1)
	ELSEIF (MOD((ATOMPOS+1),3).EQ.0) THEN
           TYPE = "HG"
           OTHERB1 = ATMPL(VBSTATE,ATOMPOS+1)
           OTHERB2 = ATMPL(VBSTATE,ATOMPOS+2)
	ELSEIF (MOD((ATOMPOS-1),3).EQ.0) THEN
           TYPE = "LW"
           OTHERB1 = ATMPL(VBSTATE,ATOMPOS-1)
           OTHERB2 = ATMPL(VBSTATE,ATOMPOS-2)
	ENDIF
	
!----DETERMINE THE ROH DISTANCES IN WATER
	IF (MOD(ATOMPOS,3).EQ.0) THEN 
           DXROH(1) = PSIX(OTHERB1) - PSIX(ATOMNO)
           DYROH(1) = PSIY(OTHERB1) - PSIY(ATOMNO)
           DZROH(1) = PSIZ(OTHERB1) - PSIZ(ATOMNO)
	   ROH(1) = INTERATOMICR(OTHERB1,ATOMNO)

           DXROH(2) = PSIX(OTHERB2) - PSIX(ATOMNO)
           DYROH(2) = PSIY(OTHERB2) - PSIY(ATOMNO)
           DZROH(2) = PSIZ(OTHERB2) - PSIZ(ATOMNO)
	   ROH(2) = INTERATOMICR(OTHERB2,ATOMNO)
	ELSE
	   DXROH(1) = PSIX(OTHERB1) - PSIX(ATOMNO)
           DYROH(1) = PSIY(OTHERB1) - PSIY(ATOMNO)
           DZROH(1) = PSIZ(OTHERB1) - PSIZ(ATOMNO)
	   ROH(1) = INTERATOMICR(OTHERB1,ATOMNO)
           DXROH(2) = PSIX(OTHERB1) - PSIX(OTHERB2)
           DYROH(2) = PSIY(OTHERB1) - PSIY(OTHERB2)
           DZROH(2) = PSIZ(OTHERB1) - PSIZ(OTHERB2)
	   ROH(2) = INTERATOMICR(OTHERB1,OTHERB2)
	ENDIF

!---------------------------------------------------------------------
! CALCULATE THE BENDING TERMS:
!
!---------------------------------------------------------------------

        THETA_TEMP = DXROH(1)*DXROH(2)+DYROH(1)*DYROH(2) &
                        + DZROH(1)*DZROH(2)
	THETA = CHECKED_ACOS(THETA_TEMP/(ROH(1)*ROH(2)))

        ANGLEDIFF = THETA - THETAEQ
        VECTSQ = DXROH(1)*DXROH(2) + DYROH(1)*DYROH(2) + DZROH(1)*DZROH(2)

!----INITIALLY CONSIDER THE OXYGEN
        IF (MOD(ATOMPOS,3).EQ.0) THEN 
!---------------------------------------------------------------------
!  X
!---------------------------------------------------------------------
	   PART1X = (DXROH(1)*VECTSQ)/(ROH(2)*ROH(1)**3) + (DXROH(2)*VECTSQ)/(ROH(1)*ROH(2)**3)
	   PART2X = DXROH(1)/(ROH(1)*ROH(2)) + DXROH(2)/(ROH(1)*ROH(2))
	   PART3X = -1.0D0*DSIN(THETA)

	   IF (DABS(PART3X)<NUMERICALZEROLIMIT) THEN
	      RFH2OBENDZ = LARGE_FORCE
	   ELSE
	      RFH2OBENDX = H2OKTHETA*(THETA - THETAEQ)*(PART1X - PART2X)/PART3X 
	   ENDIF
!---------------------------------------------------------------------
!  Y
!---------------------------------------------------------------------
            PART1Y = DYROH(2)*VECTSQ/(ROH(1)*ROH(2)**3)
            PART2Y = -1.0D0*(DYROH(1)+DYROH(2))/(ROH(1)*ROH(2))
            PART3Y = DYROH(1)*VECTSQ/(ROH(2)*ROH(1)**3)
            PART4Y = 1.0D0 - VECTSQ**2/((ROH(1)**2)*(ROH(2)**2))

	    IF (DABS(PART4Y)<NUMERICALZEROLIMIT) THEN
	       RFH2OBENDY = LARGE_FORCE
	    ELSE
	       RFH2OBENDY = -1.0D0*(H2OKTHETA*(PART1Y + PART2Y + PART3Y)*ANGLEDIFF)/DSQRT(PART4Y)
	    ENDIF
!---------------------------------------------------------------------
!  Z
!---------------------------------------------------------------------
            PART1Z = DZROH(2)*VECTSQ/(ROH(1)*ROH(2)**3)
            PART2Z = -1.0D0*(DZROH(1)+DZROH(2))/(ROH(1)*ROH(2))
            PART3Z = DZROH(1)*VECTSQ/(ROH(2)*ROH(1)**3)
            PART4Z = 1.0D0 - VECTSQ**2/((ROH(1)**2)*(ROH(2)**2))

	    IF (DABS(PART4Z)<NUMERICALZEROLIMIT) THEN
	       RFH2OBENDZ = LARGE_FORCE
	    ELSE
	       RFH2OBENDZ = -1.0D0*(H2OKTHETA*(PART1Z + PART2Z + PART3Z)*ANGLEDIFF)/DSQRT(PART4Z)
	    ENDIF

!----NOW CONSIDER HYDROGEN
	 ELSE
!---------------------------------------------------------------------
!  X
!--------------------------------------------------------------------- 
	    PART1X = DXROH(1)*VECTSQ/(ROH(2)*ROH(1)**3) 
	    PART2X = DXROH(2)/(ROH(1)*ROH(2))
	    PART3X = 1.0D0 - VECTSQ**2/((ROH(1)**2)*(ROH(2)**2))

	    IF (DABS(PART3X)<NUMERICALZEROLIMIT) THEN
	       RFH2OBENDX = LARGE_FORCE
	    ELSE
	       RFH2OBENDX = -1.0D0*(H2OKTHETA*(PART1X - PART2X)*ANGLEDIFF)/DSQRT(PART3X)
	    ENDIF
!---------------------------------------------------------------------
!  Y
!---------------------------------------------------------------------
            PART1Y = DYROH(1)*VECTSQ/(ROH(2)*ROH(1)**3)
            PART2Y = DYROH(2)/(ROH(1)*ROH(2))
            PART3Y = 1.0D0 - VECTSQ**2/((ROH(1)**2)*(ROH(2)**2))
	    
	    IF (DABS(PART3Y)<NUMERICALZEROLIMIT) THEN
	       RFH2OBENDY = LARGE_FORCE
	    ELSE
	       RFH2OBENDY = -1.0D0*(H2OKTHETA*(PART1Y - PART2Y)*ANGLEDIFF)/DSQRT(PART3Y) 
	    ENDIF
!---------------------------------------------------------------------
!  Z
!---------------------------------------------------------------------
            PART1Z = DZROH(1)*VECTSQ/(ROH(2)*ROH(1)**3)
            PART2Z = DZROH(2)/(ROH(1)*ROH(2))
            PART3Z = 1.0D0 - VECTSQ**2/((ROH(1)**2)*(ROH(2)**2))

	    IF (DABS(PART3Z)<NUMERICALZEROLIMIT) THEN
	       RFH2OBENDZ = LARGE_FORCE
	    ELSE
	       RFH2OBENDZ = -1.0D0*(H2OKTHETA*(PART1Z - PART2Z)*ANGLEDIFF)/DSQRT(PART3Z) 
	    ENDIF
	 ENDIF
!---------------------------------------------------------------------
! CALCULATE THE STRETCHING TERMS:
!
!---------------------------------------------------------------------

	 RFH2OSTRX = -1.0D0*DXROH(1)*(H2OKB/ROH(1))*(ROH(1)-H2OROHEQ) 
	 RFH2OSTRY = -1.0D0*DYROH(1)*(H2OKB/ROH(1))*(ROH(1)-H2OROHEQ)
	 RFH2OSTRZ = -1.0D0*DZROH(1)*(H2OKB/ROH(1))*(ROH(1)-H2OROHEQ)
	
	 IF (TYPE.EQ."OX") THEN
	    RFH2OSTRX = RFH2OSTRX - 1.0D0*DXROH(2)*(H2OKB/ROH(2))*(ROH(2)-H2OROHEQ) 
	    RFH2OSTRY = RFH2OSTRY - 1.0D0*DYROH(2)*(H2OKB/ROH(2))*(ROH(2)-H2OROHEQ)
	    RFH2OSTRZ = RFH2OSTRZ - 1.0D0*DZROH(2)*(H2OKB/ROH(2))*(ROH(2)-H2OROHEQ)
	 ENDIF

	 FH2OINTRAX = 1.0D0*(RFH2OSTRX + RFH2OBENDX)
	 FH2OINTRAY = 1.0D0*(RFH2OSTRY + RFH2OBENDY)
	 FH2OINTRAZ = 1.0D0*(RFH2OSTRZ + RFH2OBENDZ)

! DEBUGGING

!	H2O_INTRA_FORCES(VBSTATE,(3*ATOMNO)-2) = FH2OINTRAX
!	H2O_INTRA_FORCES(VBSTATE,(3*ATOMNO)-1) = FH2OINTRAY
!	H2O_INTRA_FORCES(VBSTATE,(3*ATOMNO)) = FH2OINTRAZ

	RETURN 
	END

!#####################################################################
!##################### SUBROUTINE OFFD_ATOM1 #########################
!#####################################################################

! CALCULATE THE OFF DIAGONAL CONTRIBUTIONS TO THE FORCE FOR AN H2O ATOM (O OR H)
! OR A HYDRONIUM H WHICH IS NOT THE EXCHANGING H

	SUBROUTINE OFFD_ATOM1(ATOMNO,ROO,ROH,FXATOM1,FYATOM1,FZATOM1,VBSTATE1,VBSTATE2) 

	USE COMMONS
	USE MSEVB_COMMON
	
	IMPLICIT NONE

!========================================================================
! 29/7/99 R.A. CHRISTIE
!
! ROUTINE FOR CALCULATING THE FORCES ON ATOM TYPE 1
! *NB* THIS ROUTINE ALSO INCLUDES F2_FORCE
! *NB* ROO TAKES ON THE DISTANCE OF THE H5O2+ DIMER BEING CONSIDERED
! INPUT:
!	1. ATOM NUMBER(POSITION)
!
!  -- UPDATE: 21-07-00
! ATOM 1 UNDERGOES INTERACTIONS WITH THE H3O+ ATOMS, THE H2O ATOMS OF A
! WATER MOLECULE AND THE EXCHANGE-COUPLING TERMS.
! THUS THE DERIVATIVES OF THE V(H3O+), V(H3O+,H2O) AND V(OFFDIAG) ARE
! INCLUDED IN THIS ROUTINE.
!
!========================================================================

! SUBROUTINE ARGUMENTS

        INTEGER, INTENT(IN) :: ATOMNO
        DOUBLE PRECISION, INTENT(IN) :: ROO,ROH
	DOUBLE PRECISION, INTENT(OUT) :: FXATOM1,FYATOM1,FZATOM1
        INTEGER, INTENT(IN) :: VBSTATE1, VBSTATE2

! LOCAL VARIABLES

	DOUBLE PRECISION DX,DY,DZ,Q	
	INTEGER I,J,WHEECH
        DOUBLE PRECISION KROO,TANHROO,ALPHAROO
	DOUBLE PRECISION DHIJ_TEMP
	LOGICAL ZUNDELH

!       DOUBLE PRECISION, INTENT(IN) :: DROO(3),DROH(3)
!       DOUBLE PRECISION F,G,RIJ,VEX,DVEXDRIJ
!	DOUBLE PRECISION SECHROO,DGDQ,DROODX,DROODY,DROODZ,DROHDX,DROHDY,DROHDZ,DQDX,DQDY,DQDZ,GAMMAROO

	FXATOM1 = 0.0D0
	FYATOM1 = 0.0D0
	FZATOM1 = 0.0D0
        
 	IF (NUM_EIG.GT.2) THEN
 
!---------------------------------------------------------------------
! DETERMINE INITIAL INFORMATION TO BE UTILISED IN THE LOOP
! THIS IS NOW STORED FROM THE ENERGY CALCULATIONS RATHER THAN RECALCULATED
!---------------------------------------------------------------------  

!	   Q = 5.0D-1*ROO - ROH
!	   ALPHAROO = DEXP(-1.0D0*ALPHA_BLEH*(ROO - ROOEQ))
!	   KROO = DEXP(-1.0D0*KEXP*(ROO - DOO)**2)
!	   TANHROO = DTANH(BETA*(ROO - BIG_ROOEQ))
!	   F = (1.0D0 + P*KROO)*(5.0D-01*(1.0D0 - TANHROO) + 1.0D01*(ALPHAROO))
!	   G = DEXP(-1.0D0*GAMMA_MSEVB*(Q)**2)

!	   GAMMAROO = DEXP(-1.0D0*GAMMA_MSEVB*(Q)**2)
!	   SECHROO = 1.0D0 - TANHROO**2
!	   DGDQ = -2.0D0*GAMMAROO*GAMMA_MSEVB*Q
!	   DROODX = DROO(1)/ROO
!	   DROODY = DROO(2)/ROO
!	   DROODZ = DROO(3)/ROO
!	   DROHDX = DROH(1)/ROH
!	   DROHDY = DROH(2)/ROH
!	   DROHDZ = DROH(3)/ROH
!	   DQDX = 5.0D-01*DROODX - DROHDX
!	   DQDY = 5.0D-01*DROODY - DROHDY
!	   DQDZ = 5.0D-01*DROODZ - DROHDZ    

! DECIDE WHETHER THIS IS AN H2O ATOM OR A ZUNDEL ATOM

	   ZUNDELH = .FALSE.

 	   IF (MOD(ATOMNO,3).NE.0) THEN
 	      DO I=1,7
 		 IF (ZUNDEL_SPECIES(VBSTATE1,VBSTATE2,I).EQ.ATOMNO) THEN
 		    ZUNDELH = .TRUE.
 		    EXIT
 		 ENDIF
 	      ENDDO
 	   ENDIF

 	   IF (ZUNDELH) THEN

 	      INTERACT: DO I = 1, NATOMS
 		 DO J = 1, 7
 		    IF (ATMPL(VBSTATE1,I).EQ.ZUNDEL_SPECIES(VBSTATE1,VBSTATE2,J)) CYCLE INTERACT
 		 ENDDO

 		 WHEECH = ATMPL(VBSTATE1,I)

 		 DX = PSIX(ATOMNO) - PSIX(WHEECH)
 		 DY = PSIY(ATOMNO) - PSIY(WHEECH)
 		 DZ = PSIZ(ATOMNO) - PSIZ(WHEECH)

! 		 RIJ = INTERATOMICR(ATOMNO,WHEECH)
! 		 VEX = EACH_COULOMB(ATOMNO,WHEECH)     ! SUBSCRIPTS HAVE TO BE THIS WAY AROUND
! 		 DVEXDRIJ = -1.0D0*VEX/RIJ 
!		 DHIJ_TEMP = DVEXDRIJ*F*G/RIJ

		 DHIJ_TEMP = -1.0D0*EACH_COULOMB(ATOMNO,WHEECH)*ZUNDEL_F(VBSTATE1,VBSTATE2)*ZUNDEL_G(VBSTATE1,VBSTATE2)/ &
                             (INTERATOMICR(ATOMNO,WHEECH)**2)

 		 FXATOM1 = FXATOM1 + DHIJ_TEMP*DX
 		 FYATOM1 = FYATOM1 + DHIJ_TEMP*DY
 		 FZATOM1 = FZATOM1 + DHIJ_TEMP*DZ

 	      ENDDO INTERACT

 	   ELSE  ! H2O ATOM

 	      DO I = 1, 7
 		 WHEECH = ZUNDEL_SPECIES(VBSTATE1,VBSTATE2,I)

 		 DX = PSIX(ATOMNO) - PSIX(WHEECH)
 		 DY = PSIY(ATOMNO) - PSIY(WHEECH)
 		 DZ = PSIZ(ATOMNO) - PSIZ(WHEECH)

!!		 VEX = (QEXCHI*QEXCHJ*FOURPIEO)/RIJ
!!		 DVEXDRIJ = -1.0D0*QEXCHI*QEXCHJ*FOURPIEO/(RIJ**2)

! 		 RIJ = INTERATOMICR(ATOMNO,WHEECH)
! 		 VEX = EACH_COULOMB(WHEECH,ATOMNO)
! 		 DVEXDRIJ = -1.0D0*VEX/RIJ
!		 DHIJ_TEMP = DVEXDRIJ*F*G/RIJ

		 DHIJ_TEMP = -1.0D0*EACH_COULOMB(WHEECH,ATOMNO)*ZUNDEL_F(VBSTATE1,VBSTATE2)*ZUNDEL_G(VBSTATE1,VBSTATE2)/ &
                             (INTERATOMICR(ATOMNO,WHEECH)**2)

 		 FXATOM1 = FXATOM1 + DHIJ_TEMP*DX
 		 FYATOM1 = FYATOM1 + DHIJ_TEMP*DY
 		 FZATOM1 = FZATOM1 + DHIJ_TEMP*DZ
 	      ENDDO
	   ENDIF 
	ENDIF

	RETURN
	END

!##############################################################################
!####################### SUBROUTINE OFFD_ATOM3 ################################
!##############################################################################

! CALLED WHEN THE ATOM IN QUESTION IS THE HYDRONIUM O ATOM IN ONE OF THE TWO
! INTERACTING VB STATES

	SUBROUTINE OFFD_ATOM3(ATOMNO,ROO,ROH,DROO,DROH,FXATOM3,FYATOM3,FZATOM3, &
      		VBSTATE1,VBSTATE2)

	USE COMMONS
	USE MSEVB_COMMON

	IMPLICIT NONE

! ATOMNO IS THE POSITION OF THE O ATOM IN THE INITIAL COORDINATE VECTOR

!===============================================================
! 23-7-00 R.A. CHRISTIE
! ROUTINE TO DETERMINE THE ATOM-TYPE-3 FORCES. 
!
! NEED TO DETERMINE THE FORCE ON THE PARTICLE IN QUESTION 
! RESULTING FROM BOTH THE COULOMBIC INTERACTION, THE ASYMMETRIC
! STRETCH AND THE ROO REPULSION
!
!===============================================================

!----VARIABLES TO BE PASSED
	DOUBLE PRECISION ROO,ROH,DROO(3),DROH(3),FXATOM3,FYATOM3,FZATOM3

	INTEGER ATOMNO,VBSTATE1,VBSTATE2
!----LOCAL VARIABLES
	DOUBLE PRECISION DX,DY,DZ,RIJ,RCOULOMB,COULOMB,COULOMBSQ,QEXCHJ, &
      		PART1F,PART2F,PART3FAI,PART3FA,COEFF,DERF2F, &
      		ALPHAROO,F2_F,PART3F,DERF2_F,F2FORCE,F2ROO,QEXCHI, &
      		RCOULOMBSQ
	INTEGER I,START,END,WHEECH,J,NINTERACTIONS,COUNT
!----NEW METHOD VARIABLES
	DOUBLE PRECISION KROO,GAMMAROO,TANHROO,SECHROO,DXOO,DYOO,DZOO,DXOH,DYOH, &
      		DZOH,Q
!----EVEN MORE RECENT METHOD VARIABLES
	DOUBLE PRECISION F,DFDROO,G,DGDQ,DROODX,DROODY,DROODZ,DROHDX,DROHDY,DROHDZ, &
      	   DQDX,DQDY,DQDZ,DHIJDX,DHIJDY,DHIJDZ, &
           DVEXDRIJ,VEX,F1,F2,DF2DROO,DVEXDRIJADIVRIJ
	LOGICAL INEXCHANGE

!	PRINT *, 'ATOM:', POSITION, 'X-COORD:', 

!----INITIALIZE VARIABLES

	FXATOM3 = 0.0D0
	FYATOM3 = 0.0D0
	FZATOM3 = 0.0D0

	DHIJDX = 0.0D0
	DHIJDY = 0.0D0
	DHIJDZ = 0.0D0

!----DETERMINE THE INITIAL INFORMATION 
	Q = 5.0D-1*ROO - ROH
	ALPHAROO = DEXP(-1.0D0*ALPHA_BLEH*(ROO - ROOEQ))
	KROO = DEXP(-1.0D0*KEXP*(ROO - DOO)*(ROO - DOO))
	GAMMAROO = DEXP(-1.0D0*GAMMA_MSEVB*Q*Q)
	TANHROO = DTANH(BETA*(ROO - BIG_ROOEQ))
	SECHROO = 1.0D0 - TANHROO**2
	QEXCHI = QEXCHO
	DXOO = DROO(1)
	DYOO = DROO(2)
	DZOO = DROO(3)
	DXOH = DROH(1)
	DYOH = DROH(2)
	DZOH = DROH(3)

!#####################################################################
! NEW METHOD VARIABLES:
!
 	F = (1.0D0 + P*KROO)*(5.0D-01*(1.0D0 - TANHROO) + 1.0D01*(ALPHAROO))

	DFDROO = (1.0D0+ KROO*P)*(-1.0D01*ALPHA_BLEH*ALPHAROO - 5.0D-01*BETA*SECHROO) - &
      		2.0D0*KROO*KEXP*P*(ROO - DOO)*(1.0D01*ALPHAROO + 5.0D-01*(1.0D0 - TANHROO))

!
!----AFTER REVIEW OF DERIVATIVES - 19/08/02 - ATOM3_OFFD_FORCES.NB:
!----THIS NOW AGREES WITH MATHEMATICA VERSION OF DF/DROO.
! TRJ25 22/10/03 - NOT ACCORDING TO MATHEMATICA4 IT DOESN`T, PREVIOUS EXPRESSION WAS CORRECT 
!	DFDROO = KROO*P*(-1.0D01*ALPHA_BLEH*ALPHAROO - 5.0D-01*BETA*SECHROO) -
!     &         2.0D0*KROO*KEXP*P*(ROO - DOO)*(1.0D01*ALPHAROO + 5.0D-01*(1.0D0 - TANHROO)) 

!	F1 = (1.0D0 + P*KROO)
!	F2 = 5.0D-01*(1.0D0 - TANHROO) + 1.0D01*(ALPHAROO)
!	DF2DROO = (-1.0D01*ALPHA_BLEH*ALPHAROO - 5.0D-01*BETA*SECHROO)
	G = GAMMAROO
	DGDQ = -2.0D0*GAMMAROO*GAMMA_MSEVB*Q
	DROODX = DXOO/ROO
	DROODY = DYOO/ROO 
	DROODZ = DZOO/ROO
	DROHDX = DXOH/ROH
	DROHDY = DYOH/ROH
	DROHDZ = DZOH/ROH

! TRJ25 CHANGE SO THAT DQ/DCOORDINATE NOW INCLUDES THE INFLUENCE OF D(ROH)/DCOORDINATE
! IN A MANNER CONSISTENT WITH THE ENERGY CALCULATION

	IF (ATOMNO.EQ.ZUNDEL_SPECIES(VBSTATE1,VBSTATE2,3)) THEN
	   DQDX = 0.5D0*DROODX - DROHDX 
	   DQDY = 0.5D0*DROODY - DROHDY
	   DQDZ = 0.5D0*DROODZ - DROHDZ
	ELSE
	   DQDX = 0.5D0*DROODX
	   DQDY = 0.5D0*DROODY
	   DQDZ = 0.5D0*DROODZ
	ENDIF

!---------------------------------------------------------------------
! DETERMINE THE COULOMBIC INTERACTION ARISING FROM THE EXCHANGE TERM
! FIRST. 
! NOTE THAT THIS IS CALCULATED AS THE SUM OF ALL INTERACTIONS TO BE 
! USED LATER IN THE FULL FOR THIS OFF-DIAGONAL TERM
!
!---------------------------------------------------------------------

 	IF (NUM_EIG.GT.2) THEN

	   COUNT = 0

	   EXCHANGE: DO I = 1,NATOMS
	      IF (COUNT.EQ.(NATOMS-7)) EXIT

! CHECK THAT WE ARE NOT CALCULATING A HYDRONIUM-HYDRONIUM EXCHANGE INTERACTION
	      DO J = 1,7
		 IF (ATMPL(VBSTATE2,I).EQ.ZUNDEL_SPECIES(VBSTATE1,VBSTATE2,J)) CYCLE EXCHANGE
	      ENDDO

	      WHEECH = ATMPL(VBSTATE2,I)
	      QEXCHI = QEXCHO
	      COUNT = COUNT + 1
 
	      IF (MOD(WHEECH,3).EQ.0) THEN
		 QEXCHJ = QTIP3P_O
	      ELSE
		 QEXCHJ = QTIP3P_H
	      ENDIF
	   
	      DX = PSIX(ATOMNO) - PSIX(WHEECH)
	      DY = PSIY(ATOMNO) - PSIY(WHEECH)
	      DZ = PSIZ(ATOMNO) - PSIZ(WHEECH)
	      RIJ = INTERATOMICR(ATOMNO,WHEECH)
	      VEX = (QEXCHI*QEXCHJ*FOURPIEO)/RIJ
	      DVEXDRIJ = -1.0D0*VEX/RIJ

	      DVEXDRIJADIVRIJ = DVEXDRIJ*F*G/RIJ

!	   IF (INEXCHANGE) THEN
!	      DHIJDX_TEMP = (GAMMAROO*F1*(VIJ+VEX)*DF2DROO*(DXOO/ROO)) - 
!     &  (FOURPIEO*GAMMAROO*F1*QEXCHI*QEXCHJ*DX*F2)/(RIJ)**3 - 
!     &  (2.0D0*GAMMAROO*KROO*KEXP*P*DXOO*(VIJ+VEX)*(ROO-DOO)*F2)/ROO -
!     &  (2.0D0*GAMMA_MSEVB*F1*(VIJ+VEX)*(DXOO/(2.0D0*ROO)-DXOH/ROH)*(ROO/2.0D0 - ROH)*F2)
!	      DHIJDY_TEMP = (GAMMAROO*F1*(VIJ+VEX)*DF2DROO*(DYOO/ROO)) -
!     &  (FOURPIEO*GAMMAROO*F1*QEXCHI*QEXCHJ*DY*F2)/(RIJ)**3 -
!     &  (2.0D0*GAMMAROO*KROO*KEXP*P*DYOO*(VIJ+VEX)*(ROO-DOO)*F2)/ROO -
!     &  (2.0D0*GAMMA_MSEVB*F1*(VIJ+VEX)*(DYOO/(2.0D0*ROO)-DYOH/ROH)*(ROO/2.0D0 - ROH)*F2) 
!	      DHIJDZ_TEMP = (GAMMAROO*F1*(VIJ+VEX)*DF2DROO*(DZOO/ROO)) -
!     &  (FOURPIEO*GAMMAROO*F1*QEXCHI*QEXCHJ*DZ*F2)/(RIJ)**3 -
!     &  (2.0D0*GAMMAROO*KROO*KEXP*P*DZOO*(VIJ+VEX)*(ROO-DOO)*F2)/ROO -
!     &  (2.0D0*GAMMA_MSEVB*F1*(VIJ+VEX)*(DZOO/(2.0D0*ROO)-DZOH/ROH)*(ROO/2.0D0 - ROH)*F2) 
!	PRINT *, "DHIJDX_TEMP = ", DHIJDX_TEMP

	      DHIJDX = DHIJDX + DVEXDRIJADIVRIJ*DX
	      DHIJDY = DHIJDY + DVEXDRIJADIVRIJ*DY
	      DHIJDZ = DHIJDZ + DVEXDRIJADIVRIJ*DZ

!----END OF LOOP OVER THE SOLVATING ATOMS

	   ENDDO EXCHANGE

!----END OF IF STATEMENT FOR > 2 EIGENSTATES

! ADD THE SECOND PART OF THE DERIVATIVES, USE THE TOTAL EXCHANGE ENERGY BETWEEN THESE TWO VB STATES	

	   DHIJDX = DHIJDX + (VIJ+VIJEXCH(VBSTATE1,VBSTATE2))*(DFDROO*DROODX*G + F*DGDQ*DQDX)
	   DHIJDY = DHIJDY + (VIJ+VIJEXCH(VBSTATE1,VBSTATE2))*(DFDROO*DROODY*G + F*DGDQ*DQDY)
	   DHIJDZ = DHIJDZ + (VIJ+VIJEXCH(VBSTATE1,VBSTATE2))*(DFDROO*DROODZ*G + F*DGDQ*DQDZ)

	ELSE
!----DETERMINE THE OFF-DIAGONAL ELEMENT FOR 2 EIGENSTATE SYSTEM

	    DHIJDX = VIJ*(DFDROO*G*DROODX + F*DGDQ*DQDX)
	    DHIJDY = VIJ*(DFDROO*G*DROODY + F*DGDQ*DQDY)  
	    DHIJDZ = VIJ*(DFDROO*G*DROODZ + F*DGDQ*DQDZ)  
	ENDIF

!	    PRINT *, 'AT END:'
!	PRINT *, 'VIJ:', VIJ
!	PRINT *, 'ROO:', ROO
!	PRINT *, 'ROH:', ROH
!	PRINT *, 'F:', F
!	PRINT *, 'DF/DROO:', DFDROO
!	PRINT *, 'G:', G
!	PRINT *, 'DG/DQ:', DGDQ
!	PRINT *, 'Q:', Q
!	PRINT *, 'DQ/DX:', DQDX
!	PRINT *, 'DQ/DY:', DQDY
!	PRINT *, 'DQ/DZ:', DQDZ
!	PRINT *, 'DROO/DX:', DROODX
!	PRINT *, 'DROO/DY:', DROODY	
!	PRINT *, 'DROO/DZ:', DROODZ
!	PRINT *, 'TOTAL EXCHANGE ENERGY: ', VIJEXCH(EIGENSTATE1,EIGENSTATE2)

!	PRINT *, 'DHIJ/DX:', DHIJDX
!	PRINT *, 'DHIJ/DY:', DHIJDY
!	PRINT *, 'DHIJ/DZ:', DHIJDZ

	FXATOM3 = DHIJDX
	FYATOM3 = DHIJDY
	FZATOM3 = DHIJDZ

	RETURN
	END

!#####################################################################
!#################### SUBROUTINE OFFD_ATOM4 ##########################
!#####################################################################

	SUBROUTINE OFFD_ATOM4(ATOMNO,ROO,ROH,DROO,DROH,FXATOM4,FYATOM4,FZATOM4,VBSTATE1,VBSTATE2) 

	USE COMMONS
	USE MSEVB_COMMON
	  
	IMPLICIT NONE

! CALCULATE THE OFF-DIAGONAL FORCES FOR THE EXCHANGING H ATOM

!===============================================================
! 30/7/99 R.A. CHRISTIE
! ROUTINE TO CALCULATE THE ATOM-4-TYPE FORCES. APPLIES ONLY TO
! ATOM4
!
! *NB* FUNCTION F2FORCE IS IN ROUTINE F_ATOM1
! *NB* NEED TWO ROO DISTANCES AS INPUT
!
!===============================================================

!----INCOMING VARIABLES
	DOUBLE PRECISION ROO,ROH,DROO(3),DROH(3),FXATOM4,FYATOM4,FZATOM4
        INTEGER ATOMNO,VBSTATE1,VBSTATE2
!----LOCAL VARIABLES
	DOUBLE PRECISION DX,DY,DZ,REXCH,COULOMB,TMPFX,TMPFY,TMPFZ,QEXCHJ, &
      		QEXCHI,PART1F,PART2F,ALPHAROO,Q,RIJ,RCOULOMB
	INTEGER I,J,START,WHEECH,COUNT
!----NEW METHOD VARIABLES
        DOUBLE PRECISION KROO,GAMMAROO,TANHROO,SECHROO,DXOO,DYOO,DZOO,DXOH,DYOH, &
                DZOH
!----NEW METHOD VARIABLES
        DOUBLE PRECISION F,G,DGDQ,DROHDX,DROHDY,DROHDZ,DQDX,DQDY,DQDZ,DHIJDX,DHIJDY, &
      		DHIJDZ,VEX,DVEXDRIJ
	LOGICAL INEXCHANGE

!---------------------------------------------------------------------
! INITIALIZE VARIABLES
!
!---------------------------------------------------------------------  

	FXATOM4 = 0.0D0
	FYATOM4 = 0.0D0
	FZATOM4 = 0.0D0

        DHIJDX = 0.0D0
        DHIJDY = 0.0D0
        DHIJDZ = 0.0D0  
	COUNT = 0

!---------------------------------------------------------------------
! DETERMINE THE INITIAL INFORMATION
!
!---------------------------------------------------------------------
	Q = ROO*5.0D-01 - ROH
	ALPHAROO = DEXP(-1.0D0*ALPHA_BLEH*(ROO - ROOEQ))
        KROO = DEXP(-1.0D0*KEXP*(ROO - DOO)**2)
        GAMMAROO = DEXP(-1.0D0*GAMMA_MSEVB*(Q)**2)
        TANHROO = DTANH(BETA*(ROO - BIG_ROOEQ))
        SECHROO = 1.0D0 - TANHROO**2
        QEXCHI = QEXCHH
        DXOO = DROO(1)
        DYOO = DROO(2)
        DZOO = DROO(3)
        DXOH = DROH(1)
        DYOH = DROH(2)
        DZOH = DROH(3) 

!#####################################################################
! NEW METHOD VARIABLES
!
	F = (1.0D0 + P*KROO)*(5.0D-01*(1.0D0 - TANHROO) + 1.0D01*(ALPHAROO))
        G = GAMMAROO
        DGDQ = -2.0D0*GAMMAROO*GAMMA_MSEVB*Q
        DROHDX = DXOH/ROH
        DROHDY = DYOH/ROH
        DROHDZ = DZOH/ROH
        DQDX = -1.0D0*DROHDX
        DQDY = -1.0D0*DROHDY
        DQDZ = -1.0D0*DROHDZ    

!################################################################################
! CALCULATE THE OFF-DIAGONAL ELEMENT.
! TWO CASES:
!   (1) ANY SYSTEM OTHER THAN H5O2+
!   (2) H5O2+
!
! LOOP OVER ALL ATOMS IN THIS EIGENSTATE, GIVEN BY ATMPL(EIGENSTATE,J), WHICH 
! ARE NOT PART OF THE H5O2+ IN THIS EIGENSTATE, IF THE ATOM IN QUESTION, ATOMPOS,
! IS PART OF THE H5O2+ IN THIS EIGENSTATE. IF ATOMPOS ISN'T PART OF THE H5O2+
! IN THIS EIGENSTATE, THEN THE LOOP OVER ATOMS SHOULD ONLY INCLUDE THE H5O2+
! ATOMS FOR THIS EIGENSTATE.
!
!################################################################################ 

 	IF (NUM_EIG.GT.2) THEN

!----DETERMINE WHICH ATOMS ATOMNO SHOULD BE INTERACTING WITH

	   EXCHANGE: DO I = 1,NATOMS
	      IF (COUNT.EQ.(NATOMS-7)) EXIT

!----DETERMINE WHETHER ATOM I IS IN H5O2+

	      DO J = 1,7
		 IF (ATMPL(VBSTATE1,I).EQ.ZUNDEL_SPECIES(VBSTATE1,VBSTATE2,J)) CYCLE EXCHANGE
	      ENDDO 
	      WHEECH = ATMPL(VBSTATE1,I) 
	      COUNT = COUNT + 1

	      IF (MOD(WHEECH,3).EQ.0) THEN 
		 QEXCHJ = QTIP3P_O
	      ELSE 
		 QEXCHJ = QTIP3P_H
	      ENDIF

	      DX = PSIX(ATOMNO) - PSIX(WHEECH)
	      DY = PSIY(ATOMNO) - PSIY(WHEECH)
	      DZ = PSIZ(ATOMNO) - PSIZ(WHEECH)

	      RIJ = INTERATOMICR(ATOMNO,WHEECH)
	      VEX = (QEXCHI*QEXCHJ*FOURPIEO)/RIJ 
	      DVEXDRIJ = -1.0D0*QEXCHI*QEXCHJ*FOURPIEO/(RIJ**2)

	      DHIJDX = DHIJDX + DVEXDRIJ*(DX/RIJ)
	      DHIJDY = DHIJDY + DVEXDRIJ*(DY/RIJ)
	      DHIJDZ = DHIJDZ + DVEXDRIJ*(DZ/RIJ)	      

	   ENDDO EXCHANGE

! COMPLETE THE EXCHANGE TERMS

	   DHIJDX = F*G*DHIJDX + (VIJ+VIJEXCH(VBSTATE1,VBSTATE2))*DGDQ*F*DQDX 
	   DHIJDY = F*G*DHIJDY + (VIJ+VIJEXCH(VBSTATE1,VBSTATE2))*DGDQ*F*DQDY
	   DHIJDZ = F*G*DHIJDZ + (VIJ+VIJEXCH(VBSTATE1,VBSTATE2))*DGDQ*F*DQDZ	

!----CONSIDER NOW THE CASE WHEN HAVE ONLY H5O2+ I.E. NO EXCHANGE TERM
	ELSE

	   DHIJDX = VIJ*F*DGDQ*DQDX  
	   DHIJDY = VIJ*F*DGDQ*DQDY 
	   DHIJDZ = VIJ*F*DGDQ*DQDZ 

	ENDIF

	FXATOM4 = DHIJDX
	FYATOM4 = DHIJDY
	FZATOM4 = DHIJDZ

	RETURN
	END

















