!     COPYRIGHT (C) 1999-2008 DAVID J. WALES
!  THIS FILE IS PART OF OPTIM.
!
!  OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!  IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!  THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!  (AT YOUR OPTION) ANY LATER VERSION.
!
!  OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!  BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!  MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!  GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!
!  YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!  ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!  FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!  COORDSA BECOMES THE OPTIMAL ALIGNMENT OF THE OPTIMAL PERMUTATION(-INVERSION)
!  ISOMER, BUT WITHOUT THE PERMUTATIONS. DISTANCE IS THE RESIDUAL SQUARE DISTANCE
!  FOR THE BEST ALIGNMENT WITH RESPECT TO PERMUTATION(-INVERSION)S AS WELL AS
!  ORIENTATION AND CENTRE OF MASS.
!
!  MYORIENT IS CALLED FIRST FOR BOTH COORDSA AND COORDSB TO PUT THEM INTO
!  A STANDARD ORIENTATION IN DUMMYA AND DUMMYB (WHICH BOTH HAVE THE CENTRE OF
!  COORDINATES AT THE ORIGIN). 
!  THE OBJECTIVE IS TO IDENTIFY PERMUTATION-INVERSION ISOMERS WITHOUT FAIL. 
!  HOWEVER, WE HAVE TO CYCLE OVER ALL EQUIVALENT ATOMS IN TWO PARTICULAR ORBITS FOR DUMMYA
!  TO ACHIEVE THIS.
!  WE ITERATE PERMUTATIONS AND NEWMINDIST MINIMISATIONS UP TO A MAXIMUM NUMBER OR
!  UNTIL NO MORE PERMUTATIONS ARE REQUIRED FOR EACH INSTANCE OF DUMMYA ALIGNED 
!  ACCORDING TO NCHOOSE1 AND NCHOOSE2 BY MYORIENT. THE CUMULATIVE ROTATION
!  MATRIX THAT TAKES THE INITIAL DUMMYA TO THE ONE THAT ALIGNS BEST WITH DUMMYB
!  IS SAVED IN RMATCUMUL.
!  THEN, IF WE'VE NOT GOING BULK, AMBER, OR CHARMM, WE TRY AGAIN FOR THE INVERTED
!  VERSION OF COORDSA. THE TRANSFORMATION CORRESPONDING TO THE MINIMUM DISTANCE
!  IS SAVED WHENEVER IT IS IMPROVED - THE BEST ALIGNMENT INCLUDING PERMUTATIONS
!  IS SAVED IN XBEST, AND THE LAST STEP IS TO ROTATE THIS BACK TO COINCIDE BEST
!  WITH COORDSB (RATHER THAN DUMMYB) USING ROTINVBBEST. THIS GIVES SUITABLE
!  FIXED END POINTS FOR DNEB.
!  FINALLY, WE TRANSFORM COORDSA TO BE IN OPTIMAL ALIGNMENT, BUT WITHOUT THE
!  PERMUTATIONS IN XBEST. THE OVERALL TRANSFORMATION IS
!  COORDSA -> +/- ROTINVB RMATCUMUL ROTA (COORDSA - CMA) 
!
!  THE CORRESPONDENCE BETWEEN COORDSA AND DUMMYA AFTER DUMMYA HAS BEEN ALIGNED BY
!  NEWMINDIST IS
!  +/- RMATCUMUL ROTA (COORDSA - CMA) = PERMUTATION(DUMMYA)
!  WHERE +/- IS GIVEN BY THE VALUE OF INVERT.
!  THE CENTRES OF COORDINATES FOR COORDSA AND COORDSB CAN BE ANYWHERE. ON RETURN, THE
!  CENTRE OF COORDINATES OF COORDSA WILL BE THE SAME AS FOR COORDSB.
!
SUBROUTINE MINPERMDIST(COORDSB,COORDSA,NATOMS,DEBUG,BOXLX,BOXLY,BOXLZ,BULKT,TWOD,DISTANCE,DIST2,RIGID,RMATBEST)

USE KEY,ONLY : NPERMGROUP, NPERMSIZE, PERMGROUP, NSETS, SETS, STOCKT, GEOMDIFFTOL, AMBERT, &
  &            NFREEZE, NABT, RBAAT, ANGLEAXIS2, BESTPERM, LOCALPERMDIST, PULLT, EFIELDT, NTSITES, RIGIDBODY, PERMDIST
USE MODCHARMM,ONLY : CHRMMT
USE MODAMBER9, ONLY: NOPERMPROCHIRAL, PROCHIRALH
USE INTCOMMONS, ONLY : INTMINPERMT, INTINTERPT, DESMINT, OLDINTMINPERMT, INTDISTANCET
USE INTCUTILS, ONLY : INTMINPERM, OLD_INTMINPERM, INTMINPERM_CHIRAL, INTDISTANCE
IMPLICIT NONE

INTEGER, PARAMETER :: MAXIMUMTRIES=100
INTEGER NATOMS, NPERM, PATOMS, NTRIES, NRB
INTEGER J3, J4, INVERT, NORBIT1, NORBIT2, NCHOOSE2, NDUMMY, LPERM(NATOMS), J1, J2, NCHOOSE1
DOUBLE PRECISION DIST2, COORDSA(3*NATOMS), COORDSB(3*NATOMS), DISTANCE, DUMMYA(3*NATOMS), &
  &              BESTA(3*NATOMS), DUMMYB(3*NATOMS), DUMMY(3*NATOMS)
DOUBLE PRECISION BOXLX,BOXLY,BOXLZ,WORSTRAD,RMAT(3,3),ENERGY, VNEW(3*NATOMS), DX, DY, DZ, RMS, DBEST, XBEST(3*NATOMS)
DOUBLE PRECISION CMXA, CMXB, CMXC, QBEST(4), SITESA(3*NTSITES), SITESB(3*NTSITES)
DOUBLE PRECISION ROTA(3,3), ROTINVA(3,3), ROTB(3,3), ROTINVB(3,3), ROTINVBBEST(3,3), ROTABEST(3,3), RMATBEST(3,3), TMAT(3,3)
DOUBLE PRECISION CMAX, CMAY, CMAZ, CMBX, CMBY, CMBZ, RMATCUMUL(3,3), PVEC(3), RTEMP1(3,3), RTEMP2(3,3)
DOUBLE PRECISION REFXZ(3,3)
LOGICAL DEBUG, TWOD, RIGID, BULKT, PITEST
DOUBLE PRECISION PDUMMYA(3*NATOMS), PDUMMYB(3*NATOMS), LDISTANCE, DUMMYC(3*NATOMS), XDUMMY, DUMMYD(3*NATOMS), LDBEST
INTEGER NEWPERM(NATOMS), ALLPERM(NATOMS), SAVEPERM(NATOMS)
DOUBLE PRECISION TIME0, TIME1, BSX, BSY, BSZ
DOUBLE PRECISION, ALLOCATABLE :: TEMPA(:), TEMPB(:)
COMMON /BULKSHIFT/ BSX, BSY, BSZ

! CALL POTENTIAL(COORDSA,ENERGY,VNEW,.TRUE.,.FALSE.,RMS,.FALSE.,.FALSE.)
! PRINT '(2(A,F25.15))',' INTIAL ENERGY FOR A=             ',ENERGY,' RMS=',RMS
! CALL POTENTIAL(COORDSB,ENERGY,VNEW,.TRUE.,.FALSE.,RMS,.FALSE.,.FALSE.)
! PRINT '(2(A,F25.15))',' INTIAL ENERGY FOR B=             ',ENERGY,' RMS=',RMS
!
! FOR ANGLE-AXIS COORDINATES WITH PERMDIST: 
! (1) USE MINPERM TO PERMUTE THE CENTRE-OF-MASS COORDINATES IN THE USUAL WAY,
!     USING A METRIC BASED ON JUST THE CENTRE OF MASS. THESE COORDINATES ARE
!     STORED IN THE FIRST 3*NATOMS ENTRIES.
! (2) FOR EACH REORIENTATION OF THE CENTRE OF MASS CORRDINATES WE HAVE TO
!     ROTATE THE ORIENTATIONAL COORDINATES. THEN WE NEED A LOOP OVER THE
!     RIGID BODIES TO MINIMISE THE DISTANCE METRIC BASED UPON ALL THE SITES
!     FOR THE ALLOWED INTERNAL SYMMETRY OPERATIONS OF EVERY RIGID BODY.
!

  IF (RBAAT) THEN
     CALL RBMINPERMDIST(COORDSB,COORDSA,DISTANCE,DIST2,QBEST,RMATBEST,DEBUG,BOXLX,BOXLY,BOXLZ,BULKT,SITESB,SITESA)
     RETURN
  ENDIF
!
REFXZ(1:3,1:3)=0.0D0
REFXZ(1,1)=1.0D0; REFXZ(2,2)=-1.0D0; REFXZ(3,3)=1.0D0
!
! THE INTMINPERM KEYWORD MAY NOW BE OK FOR MOVIE MAKING. IT WAS PRODUCING JUMPS
! BUT I THINK SETTING RMATBEST HAS FIXED THIS. DJW 18/2/11.
!

IF (NOPERMPROCHIRAL.AND.(AMBERT.OR.NABT).AND..NOT.INTMINPERMT) THEN
   CALL NEWMINDIST(COORDSB,COORDSA,NATOMS,DISTANCE,BULKT,TWOD,'AX   ',.FALSE.,RIGID,DEBUG,RMAT)
   IF (.NOT.ALLOCATED(PROCHIRALH)) CALL FINDCHIRALH(DEBUG)
   CALL MINPERM_CHIRAL(COORDSB, COORDSA,DISTANCE,RMAT, DEBUG)
   CALL CHECK_VALLEU_CHIRALITY(COORDSB, COORDSA,DEBUG)
   CALL NEWMINDIST(COORDSB,COORDSA,NATOMS,DISTANCE,BULKT,TWOD,'AX   ',.TRUE.,RIGID,DEBUG,RMAT)
   RMATBEST = RMAT 
   RETURN
ENDIF

IF (.NOT.PERMDIST) THEN
!
! NEWMINDIST IS ALWAYS CALLED WITH PRESERVET .FALSE. HERE. HENCE COORDSA WILL GENERALLY BE
! CHANGED TO BE PUT INTO BEST CORRESPONDENCE WITH COORDSB.
!
   CALL NEWMINDIST(COORDSB,COORDSA,NATOMS,DISTANCE,BULKT,TWOD,'AX   ',.FALSE.,RIGIDBODY,DEBUG,RMAT)
   RETURN
ENDIF

IF (INTMINPERMT.AND.(INTINTERPT.OR.DESMINT)) THEN
    IF (CHRMMT.OR.OLDINTMINPERMT) THEN
      !CALL MYCPU_TIME(TIME0,.FALSE.)
      CALL OLD_INTMINPERM(COORDSB, COORDSA, DISTANCE, RMAT, DEBUG)
      CALL NEWMINDIST(COORDSB,COORDSA,NATOMS,DISTANCE,BULKT,TWOD,'AX    ',.FALSE.,RIGID,DEBUG,RMAT)
      !CALL MYCPU_TIME(TIME1,.FALSE.)
      !PRINT*, "ALIGNMENT TOOK", TIME1-TIME0
      IF (DEBUG) PRINT '(A,G20.10)', "MINPERMDIST> NEWMIN-DISTANCE ", DISTANCE
      DISTANCE = DISTANCE**2
      RMATBEST=RMAT
    ELSEIF (AMBERT.OR.NABT) THEN
      IF (NOPERMPROCHIRAL) THEN
        IF (.NOT.ALLOCATED(PROCHIRALH)) CALL FINDCHIRALH(DEBUG)
        CALL INTMINPERM_CHIRAL(COORDSB, COORDSA, DISTANCE, RMAT, DEBUG)
      ELSE
        CALL INTMINPERM(COORDSB,COORDSA,DISTANCE,RMAT,DEBUG)
      ENDIF
      IF (DEBUG) PRINT*, "DISTANCE IN MINPERM", SQRT(DISTANCE)
      CALL CHECK_VALLEU_CHIRALITY(COORDSB, COORDSA,DEBUG)
      CALL NEWMINDIST(COORDSB,COORDSA,NATOMS,DISTANCE,BULKT,TWOD,'AX   ',.FALSE.,RIGID,DEBUG,RMAT)
      IF (DEBUG) PRINT '(A,G20.10)',"MINPERMDIST> NEWMIN-DISTANCE ", DISTANCE
      DISTANCE = DISTANCE**2 ! SEE BELOW
      RMATBEST=RMAT
    ELSE
      PRINT*, "MINPERMDIST> ERROR *** USING INTMINPERM WITHOUT CHARMM/AMBER"
      STOP
    ENDIF
    IF (INTDISTANCET) THEN
      CALL INTDISTANCE(COORDSB, COORDSA, DISTANCE, DEBUG)
      IF (DEBUG) PRINT*, "MSB50 MINPERMDIST USING INTDISTANCE", DISTANCE
    ENDIF
   DISTANCE=SQRT(DISTANCE)
   RETURN
ENDIF
!
!  CALCULATE ORIGINAL CENTRES OF MASS.
!
CMAX=0.0D0; CMAY=0.0D0; CMAZ=0.0D0
IF (NFREEZE.GT.0) GOTO 11 ! DON;T SHIFT OR REORIENT COORDINATES WITH FROZEN ATOMS
IF (STOCKT) THEN 
   NRB=(NATOMS/2)
   DO J1=1,NRB
      CMAX=CMAX+COORDSA(3*(J1-1)+1)
      CMAY=CMAY+COORDSA(3*(J1-1)+2)
      CMAZ=CMAZ+COORDSA(3*(J1-1)+3)
   ENDDO
   CMAX=CMAX/NRB; CMAY=CMAY/NRB; CMAZ=CMAZ/NRB
   CMBX=0.0D0; CMBY=0.0D0; CMBZ=0.0D0
   DO J1=1,NRB
      CMBX=CMBX+COORDSB(3*(J1-1)+1)
      CMBY=CMBY+COORDSB(3*(J1-1)+2)
      CMBZ=CMBZ+COORDSB(3*(J1-1)+3)
   ENDDO
   CMBX=CMBX/NRB; CMBY=CMBY/NRB; CMBZ=CMBZ/NRB
ELSE
   DO J1=1,NATOMS
      CMAX=CMAX+COORDSA(3*(J1-1)+1)
      CMAY=CMAY+COORDSA(3*(J1-1)+2)
      CMAZ=CMAZ+COORDSA(3*(J1-1)+3)
   ENDDO
   CMAX=CMAX/NATOMS; CMAY=CMAY/NATOMS; CMAZ=CMAZ/NATOMS
   CMBX=0.0D0; CMBY=0.0D0; CMBZ=0.0D0
   DO J1=1,NATOMS
      CMBX=CMBX+COORDSB(3*(J1-1)+1)
      CMBY=CMBY+COORDSB(3*(J1-1)+2)
      CMBZ=CMBZ+COORDSB(3*(J1-1)+3)
   ENDDO
   CMBX=CMBX/NATOMS; CMBY=CMBY/NATOMS; CMBZ=CMBZ/NATOMS
ENDIF
11 CONTINUE

INVERT=1
DBEST=1.0D100
60 NCHOOSE1=0
65 NCHOOSE1=NCHOOSE1+1
40 NCHOOSE2=0
30 NCHOOSE2=NCHOOSE2+1
DUMMYB(1:3*NATOMS)=COORDSB(1:3*NATOMS)
DUMMYA(1:3*NATOMS)=COORDSA(1:3*NATOMS)
DO J1=1,NATOMS
   ALLPERM(J1)=J1
ENDDO

! THE OPTIMAL ALIGNMENT RETURNED BY MINPERDIST IS A LOCAL MINIMUM, BUT MAY NOT
! BE THE GLOBAL MINIMUM. CALLING MYORIENT FIRST SHOULD PUT PERMUTATIONAL ISOMERS
! INTO A STANDARD ALIGNMENT AND SPOT THE GLOBAL MINIMUM ZEDRO DISTANCE IN ONE
! GO. HOWEVER, WE ALSO NEED TO CYCLE OVER EQUIVALENT ATOMS IN ORBITS USING NCHOOSE2.
!
! PROBLEMS CAN OCCUR IF WE DON'T USE ALL THE ATOMS SPECIFIED BY NORBIT1 AND NORBIT2
! BECAUSE OF THE NUMERICAL CUTOFFS EMPLOYED IN MYORIENT. WE COULD MISS THE
! RIGHT ORIENTATION! 
!
! IF WE USE MYORIENT TO PRODUCE PARTICULAR ORIENTATIONS THEN WE END UP ALIGNING 
! COORDSA NOT WITH COORDSB BUT WITH THE STANDARD ORIENTATION OF COORDSB IN DUMMYB.
! WE NOW DEAL WITH THIS BY TRACKING THE COMPLETE TRANSFORMATION, INCLUDING THE
! CONTRIBUTION OF MYORIENT USING ROTB AND ROTINVB.
!

DISTANCE=0.0D0
IF (NFREEZE.LE.0) THEN
   IF (BULKT) THEN
      NORBIT1=1; NORBIT2=1
      CALL BULKMINDIST(DUMMYB,DUMMYA,NATOMS,DISTANCE,TWOD,DEBUG,BOXLX,BOXLY,BOXLZ,PITEST,.TRUE.)
      IF (PITEST) THEN
         COORDSA(1:3*NATOMS)=DUMMYA(1:3*NATOMS)
         RMATBEST(1:3,1:3)=0.0D0
         RMATBEST(1,1)=1.0D0; RMATBEST(2,2)=1.0D0; RMATBEST(3,3)=1.0D0
         DISTANCE=SQRT(DISTANCE)
         RETURN
      ELSE
         CALL NEWMINDIST(DUMMYB,DUMMYA,NATOMS,DISTANCE,BULKT,TWOD,'AX    ',.FALSE.,RIGID,DEBUG,RMAT)
         IF (DEBUG) PRINT '(A,G20.10)',' MINPERMDIST> AFTER INITIAL CALL TO BULK/NEWMINDIST DISTANCE=',DISTANCE
         DISTANCE=DISTANCE**2 ! MINPERDIST RETURNS THE DISTANCE SQUARED FOR HISTORICAL REASONS
      ENDIF
   ELSEIF (STOCKT) THEN
      TMAT(1:3,1:3)=0.0D0
      TMAT(1,1)=INVERT*1.0D0; TMAT(2,2)=INVERT*1.0D0; TMAT(3,3)=INVERT*1.0D0
      CALL NEWROTGEOMSTOCK(NATOMS,DUMMYA,TMAT,0.0D0,0.0D0,0.0D0)
      DUMMY(1:3*NATOMS)=DUMMYA(1:3*NATOMS)
      CALL MYORIENT(DUMMYA,DUMMYC,NORBIT1,NCHOOSE1,NORBIT2,NCHOOSE2,NATOMS/2,DEBUG,ROTA,ROTINVA,STOCKT)
      CALL NEWROTGEOMSTOCK(NATOMS,DUMMY,ROTA,0.0D0,0.0D0,0.0D0)
      DUMMYA(1:3*NATOMS)=DUMMY(1:3*NATOMS)

      DUMMY(1:3*NATOMS)=DUMMYB(1:3*NATOMS)
      CALL MYORIENT(DUMMYB,DUMMYC,NORBIT1,1,NORBIT2,1,NATOMS/2,DEBUG,ROTB,ROTINVB,STOCKT)
      CALL NEWROTGEOMSTOCK(NATOMS,DUMMY,ROTB,0.0D0,0.0D0,0.0D0)
      DUMMYB(1:3*NATOMS)=DUMMY(1:3*NATOMS)
      DO J1=1,3*(NATOMS/2)
         DISTANCE=DISTANCE+(DUMMYA(J1)-DUMMYB(J1))**2
      ENDDO
   ELSE
      DUMMYC(1:3*NATOMS)=INVERT*DUMMYA(1:3*NATOMS)
      IF ((PULLT.OR.EFIELDT).AND.(INVERT.EQ.-1)) THEN ! REFLECT IN XZ PLANE
         DO J1=1,NATOMS
            DUMMYC(3*(J1-1)+1)=DUMMYA(3*(J1-1)+1)
            DUMMYC(3*(J1-1)+2)=-DUMMYA(3*(J1-1)+2)
            DUMMYC(3*(J1-1)+3)=DUMMYA(3*(J1-1)+3)
         ENDDO
      ENDIF 
      CALL MYORIENT(DUMMYC,DUMMY,NORBIT1,NCHOOSE1,NORBIT2,NCHOOSE2,NATOMS,DEBUG,ROTA,ROTINVA,STOCKT)
      DUMMYA(1:3*NATOMS)=DUMMY(1:3*NATOMS)
      CALL MYORIENT(DUMMYB,DUMMY,NORBIT1,1,NORBIT2,1,NATOMS,DEBUG,ROTB,ROTINVB,STOCKT)
      DUMMYB(1:3*NATOMS)=DUMMY(1:3*NATOMS)
      DISTANCE=0.0D0
      DO J1=1,3*NATOMS
         DISTANCE=DISTANCE+(DUMMYA(J1)-DUMMYB(J1))**2
      ENDDO
   ENDIF

!     PRINT *, 'DUMMYA'
!     PRINT *, DUMMYA
!     PRINT *, 'DUMMYB'
!     PRINT *, DUMMYB
!      STOP

!  IF (DEBUG) PRINT '(A,G20.10,A,I6,A)', &
! &       ' MINPERMDIST> AFTER INITIAL CALL TO MYORIENT DISTANCE=',SQRT(DISTANCE), ' FOR ',NATOMS,' ATOMS'
!  IF (DEBUG) PRINT '(A,4I8)',' MINPERMDIST> SIZE OF ORBITS AND SELECTED ATOMS: ', &
! &       NORBIT1,NORBIT2,NCHOOSE1,NCHOOSE2
ELSE
   NORBIT1=1; NORBIT2=1
   CALL NEWMINDIST(DUMMYB,DUMMYA,NATOMS,DISTANCE,BULKT,TWOD,'AX    ',.FALSE.,RIGID,DEBUG,RMAT)
   IF (DEBUG) PRINT '(A,G20.10)',' MINPERMDIST> AFTER INITIAL CALL TO NEWMINDIST DISTANCE=',DISTANCE
   DISTANCE=DISTANCE**2
ENDIF
!
!  BIPARTITE MATCHING ROUTINE FOR PERMUTATIONS. COORDINATES IN DUMMYB DO NOT CHANGE
!  BUT THE COORDINATES IN DUMMYA DO. DISTANCE IS THE DISTANCE^2 IN THIS CASE.
!  WE RETURN TO LABEL 10 AFTER EVERY ROUND OF PERMUTATIONAL/ORIENTATIONAL ALIGNMENT
!  UNLESS WE HAVE CONVERGED TO THE IDENTITY PERMUTATION.
!
!  ATOMS ARE NOT ALLOWED TO APPEAR IN MORE THAN ONE GROUP.
!  THE MAXIMUM NUMBER OF PAIR EXCHANGES ASSOCIATED WITH A GROUP IS TWO.
!
NTRIES=0
!
!  RMATCUMUL CONTAINS THE ACCUMULATED ROTATION MATRIX THAT RELATES THE ORIGINAL 
!  DUMMYA OBTAINED FROM COORDSA TO THE FINAL ONE.
!
RMATCUMUL(1:3,1:3)=0.0D0
RMATCUMUL(1,1)=1.0D0; RMATCUMUL(2,2)=1.0D0; RMATCUMUL(3,3)=1.0D0
10 CONTINUE
NTRIES=NTRIES+1

NDUMMY=1
DO J1=1,NATOMS
   NEWPERM(J1)=J1
ENDDO
!
! ALLPERM SAVES THE PERMUTATION FROM THE PREVIOUS CYCLE.
! NEWPERM CONTAINS THE PERMUTATION FOR THIS CYCLE, RELATIVE TO THE IDENTITY.
! SAVEPERM IS TEMPORARY STORAGE FOR NEWPERM.
! NEWPERM MUST BE APPLIED TO ALLPERM AFTER THE LOOP OVER NPERMGROUP AND
! CORRESPONDING SWAPS.
!
! NEW VERSION ALLOWS FOR OVERLAPPING ATOMS IN NPERMGROUP, SO THAT ATOMS
! CAN APPEAR IN MORE THSAN ONE GROUP. THIS WAS NEEDED TO FLEXIBLE WATER POTENTIALS.
!
DO J1=1,NPERMGROUP
   PATOMS=NPERMSIZE(J1)
   DO J2=1,PATOMS
      PDUMMYA(3*(J2-1)+1)=DUMMYA(3*(NEWPERM(PERMGROUP(NDUMMY+J2-1))-1)+1)
      PDUMMYA(3*(J2-1)+2)=DUMMYA(3*(NEWPERM(PERMGROUP(NDUMMY+J2-1))-1)+2)
      PDUMMYA(3*(J2-1)+3)=DUMMYA(3*(NEWPERM(PERMGROUP(NDUMMY+J2-1))-1)+3)
      PDUMMYB(3*(J2-1)+1)=DUMMYB(3*(NEWPERM(PERMGROUP(NDUMMY+J2-1))-1)+1)
      PDUMMYB(3*(J2-1)+2)=DUMMYB(3*(NEWPERM(PERMGROUP(NDUMMY+J2-1))-1)+2)
      PDUMMYB(3*(J2-1)+3)=DUMMYB(3*(NEWPERM(PERMGROUP(NDUMMY+J2-1))-1)+3)
   ENDDO
!
! ALL PERMUTATIONS WITHIN THIS GROUP OF SIZE NPERMSIZE(J1) ARE NOW TRIED.
!
   CALL MINPERM(PATOMS, PDUMMYB, PDUMMYA, BOXLX, BOXLY, BOXLZ, BULKT, LPERM, LDISTANCE, DIST2, WORSTRAD)
   SAVEPERM(1:NATOMS)=NEWPERM(1:NATOMS)
   DO J2=1,PATOMS
      SAVEPERM(PERMGROUP(NDUMMY+J2-1))=NEWPERM(PERMGROUP(NDUMMY+LPERM(J2)-1))
   ENDDO
!
! UPDATE PERMUTATION OF ASSOCIATED ATOMS, IF ANY. 
! WE MUST DO THIS AS WE GO ALONG, BECAUSE THESE ATOMS COULD MOVE IN MORE THAN
! ONE PERMUTATIONAL GROUP NOW.
!
   IF (NSETS(J1).GT.0) THEN
      DO J2=1,PATOMS
         DO J3=1,NSETS(J1)
            SAVEPERM(SETS(PERMGROUP(NDUMMY+J2-1),J3))=SETS(NEWPERM(PERMGROUP(NDUMMY+LPERM(J2)-1)),J3)
         ENDDO
      ENDDO
   ENDIF
   NDUMMY=NDUMMY+NPERMSIZE(J1)
   NEWPERM(1:NATOMS)=SAVEPERM(1:NATOMS)
ENDDO
!
! UPDATE THE OVERALL PERMUTATION HERE.
!
DO J1=1,NATOMS
   SAVEPERM(ALLPERM(J1))=ALLPERM(NEWPERM(J1))
ENDDO
ALLPERM(1:NATOMS)=SAVEPERM(1:NATOMS)

DUMMY(1:3*NATOMS)=DUMMYA(1:3*NATOMS)
NPERM=0
DISTANCE=0.0D0
IF (STOCKT) THEN ! ADDITIONAL PERMUTATION OF DIPOLES.
   DO J1=(NATOMS/2)+1,NATOMS
      ALLPERM(J1)=ALLPERM(J1-(NATOMS/2))+(NATOMS/2)
      NEWPERM(J1)=NEWPERM(J1-(NATOMS/2))+(NATOMS/2)
   ENDDO
ELSE IF (ANGLEAXIS2) THEN ! ADDITIONAL PERMUTATION FOR ANGLE-AXIS VARIABLES - THIS IS THE OBSOLETE ANGLEAXIS!
   DO J1=(NATOMS/2)+1,NATOMS
      ALLPERM(J1)=ALLPERM(J1-(NATOMS/2))+(NATOMS/2)
      NEWPERM(J1)=NEWPERM(J1-(NATOMS/2))+(NATOMS/2)
   ENDDO
ENDIF
!
! UPDATE COORDINATES IN DUMMYA TO OVERALL PERMUTATION USING NEWPERM.
!
DO J3=1,NATOMS
   DUMMYA(3*(J3-1)+1)=DUMMY(3*(NEWPERM(J3)-1)+1)
   DUMMYA(3*(J3-1)+2)=DUMMY(3*(NEWPERM(J3)-1)+2)
   DUMMYA(3*(J3-1)+3)=DUMMY(3*(NEWPERM(J3)-1)+3)

   IF (J3.NE.NEWPERM(J3)) THEN
!     IF (DEBUG) WRITE(*,'(A,I5,A,I5)') ' MINPERMDIST> MOVE POSITION ',NEWPERM(J3),' TO ',J3
      NPERM=NPERM+1
   ENDIF
   IF (STOCKT.OR.ANGLEAXIS2) THEN
      IF (J3.LE.(NATOMS/2)) THEN
         DISTANCE=DISTANCE+(DUMMYA(3*(J3-1)+1)-DUMMYB(3*(J3-1)+1))**2 &
  &                       +(DUMMYA(3*(J3-1)+2)-DUMMYB(3*(J3-1)+2))**2 &
  &                       +(DUMMYA(3*(J3-1)+3)-DUMMYB(3*(J3-1)+3))**2
      ENDIF
   ELSEIF (.NOT.BULKT) THEN
      DISTANCE=DISTANCE+(DUMMYA(3*(J3-1)+1)-DUMMYB(3*(J3-1)+1))**2 &
  &                    +(DUMMYA(3*(J3-1)+2)-DUMMYB(3*(J3-1)+2))**2 &
  &                    +(DUMMYA(3*(J3-1)+3)-DUMMYB(3*(J3-1)+3))**2
   ELSE
      DISTANCE=DISTANCE + (DUMMYA(3*(J3-1)+1)-DUMMYB(3*(J3-1)+1)- BOXLX*NINT((DUMMYA(3*(J3-1)+1)-DUMMYB(3*(J3-1)+1))/BOXLX))**2 &
  &                     + (DUMMYA(3*(J3-1)+2)-DUMMYB(3*(J3-1)+2)- BOXLY*NINT((DUMMYA(3*(J3-1)+2)-DUMMYB(3*(J3-1)+2))/BOXLY))**2 
      IF (.NOT.TWOD) DISTANCE=DISTANCE+(DUMMYA(3*(J3-1)+3)-DUMMYB(3*(J3-1)+3) -  &
  &                                                               BOXLZ*NINT((DUMMYA(3*(J3-1)+3)-DUMMYB(3*(J3-1)+3))/BOXLZ))**2
   ENDIF
ENDDO

! CALL POTENTIAL(DUMMYA,ENERGY,VNEW,.TRUE.,.FALSE.,RMS,.FALSE.,.FALSE.)
! PRINT '(2(A,F25.15))',' ENERGY FOR A NOW          ',ENERGY,' RMS=',RMS

! IF (DEBUG) WRITE(*,'(A,I6,A,G20.10)') ' MINPERMDIST> DISTANCE AFTER MOVING ',NPERM,' ATOMS=',SQRT(DISTANCE)

! CALL OCHARMM(DUMMYA,VNEW,ENERGY,.FALSE.,.FALSE.)
! PRINT '(A,F25.15,A)',' ENERGY=',ENERGY,' KCAL/MOL'
! CALL UPDATENBONDS(DUMMYA)
! PRINT '(A,F25.15,A)',' ENERGY=',ENERGY,' KCAL/MOL AFTER UPDATE'
! WRITE(*,'(A,I6,A,G20.10)') ' MINPERMDIST> DISTANCE AFTER PERMUTING ',NPERM,' PAIRS OF ATOMS=',SQRT(DISTANCE)
!
!  OPTIMAL ALIGNMENT. COORDINATES IN DUMMYA ARE RESET BY NEWMINDIST (SECOND ARGUMENT).
!  MUST ALLOW AT LEAST ONE CALL TO NEWMINDIST IN CASE THE MYORIENT RESULT IS TERRIBLE
!  BUT GIVES ZERO PERMUTATIONS!
!  
 
! PRINT '(A,I6,2G20.10)','NPERM,DBEST,DISTANCE=',NPERM,DBEST,DISTANCE
IF ((NPERM.NE.0).OR.(NTRIES.EQ.1)) THEN 
   CALL NEWMINDIST(DUMMYB,DUMMYA,NATOMS,DISTANCE,BULKT,TWOD,'AX    ',.FALSE.,RIGID,DEBUG,RMAT)
   RMATCUMUL=MATMUL(RMAT,RMATCUMUL)
   DISTANCE=DISTANCE**2 ! WE ARE USING DISTANCE^2 FURTHER DOWN
!  IF (DEBUG) WRITE(*,'(A,G20.10)') ' MINPERMDIST> DISTANCE AFTER NEWMINDIST=                     ', &
! &                                    SQRT(DISTANCE) 
   IF (NTRIES.LT.MAXIMUMTRIES) THEN
      GOTO 10
   ELSE ! PREVENT INFINITE LOOP
      PRINT '(A)',' MINPERMDIST> WARNING - NUMBER OF TRIES EXCEEDED, GIVING UP'
   ENDIF
ENDIF

IF (DISTANCE.LT.DBEST) THEN
   DBEST=DISTANCE
!  PRINT *, 'DBEST=', DBEST
   XBEST(1:3*NATOMS)=DUMMYA(1:3*NATOMS)
!  PRINT *, 'XBEST'
!  PRINT *, XBEST
   BESTPERM(1:NATOMS)=ALLPERM(1:NATOMS)
   RMATBEST(1:3,1:3)=RMATCUMUL(1:3,1:3)
   ROTINVBBEST(1:3,1:3)=ROTINVB(1:3,1:3) 
   ROTABEST(1:3,1:3)=ROTA(1:3,1:3)      
   RMATBEST=MATMUL(RMATBEST,ROTABEST)
   IF (INVERT.EQ.-1) THEN
      IF (PULLT.OR.EFIELDT) THEN ! REFLECT IN XZ PLANE RATHER THAN INVERT!
         RMATBEST(1:3,1:3)=MATMUL(RMATBEST,REFXZ)
      ELSE
         RMATBEST(1:3,1:3)=-RMATBEST(1:3,1:3)
      ENDIF
   ENDIF
ENDIF

!
! IF GEOMDIFFTOL IS SET TOO SMALL WE COULD MISS THE BEST SOLUTION BY EXITING PREMATURELY. 
! TURN OFF THE NEXT LINE?!
!
! IF (SQRT(DBEST).LT.GEOMDIFFTOL) GOTO 50
IF (NCHOOSE2.LT.NORBIT2) GOTO 30
IF (NCHOOSE1.LT.NORBIT1) GOTO 65
!
!  NOW TRY THE ENANTIOMER (OR XZ REFLECTED STRUCTURE FOR PULLT.OR.EFIELDT).
!
!  GO TO 50
IF ((NCHOOSE2.EQ.NORBIT2).AND.(NCHOOSE1.EQ.NORBIT1).AND.(INVERT.EQ.1)) THEN
!
! DON'T TRY INVERSION FOR BULK OR CHARMM OR AMBER OR FROZEN ATOMS
!
   IF (BULKT.OR.CHRMMT.OR.AMBERT.OR.NABT.OR.(NFREEZE.GT.0)) GOTO 50 
  IF (DEBUG) PRINT '(A)',' MINPERMDIST> INVERTING GEOMETRY FOR COMPARISON WITH TARGET'
   INVERT=-1
   GOTO 60
ENDIF

50 DISTANCE=DBEST
!
!  XBEST CONTAINS THE BEST ALIGNMENT OF A COORDINATES FOR THE ORIENTATION OF B COORDINATES IN DUMMYB.
!  ROTATE XBEST BY ROTINVBBEST TO PUT IN BEST CORRESPONDENCE WITH COORDSB, UNDOING THE REORIENTATION TO DUMMYB FROM MYORIENT. 
!  WE SHOULD GET THE SAME RESULT FOR ROTINVBBEST * RMATBEST * (COORDSA-CMA) 
!  WHERE RMATBEST = +/- RMATCUMUL * ROTA FOR THE BEST ALIGNMENT 
!  (ASIDE FROM A POSSIBLE PERMUTATION OF THE ATOM ORDERING)
!
   IF (NFREEZE.GT.0) THEN
      XDUMMY=0.0D0
      DO J1=1,NATOMS
         XDUMMY=XDUMMY+(COORDSB(3*(J1-1)+1)-XBEST(3*(J1-1)+1))**2+ &
  &                    (COORDSB(3*(J1-1)+2)-XBEST(3*(J1-1)+2))**2+ &
  &                    (COORDSB(3*(J1-1)+3)-XBEST(3*(J1-1)+3))**2
      ENDDO
   ELSE IF (STOCKT) THEN
      CALL NEWROTGEOMSTOCK(NATOMS,XBEST,ROTINVBBEST,0.0D0,0.0D0,0.0D0)
      XDUMMY=0.0D0
      DO J1=1,(NATOMS/2)
         XBEST(3*(J1-1)+1)=XBEST(3*(J1-1)+1)+CMBX
         XBEST(3*(J1-1)+2)=XBEST(3*(J1-1)+2)+CMBY
         XBEST(3*(J1-1)+3)=XBEST(3*(J1-1)+3)+CMBZ
         XDUMMY=XDUMMY+(COORDSB(3*(J1-1)+1)-XBEST(3*(J1-1)+1))**2+ &
  &                    (COORDSB(3*(J1-1)+2)-XBEST(3*(J1-1)+2))**2+ &
  &                    (COORDSB(3*(J1-1)+3)-XBEST(3*(J1-1)+3))**2
      ENDDO
   ELSEIF (BULKT) THEN
      XDUMMY=0.0D0
      DO J1=1,NATOMS
         XDUMMY=XDUMMY+(COORDSB(3*(J1-1)+1)-XBEST(3*(J1-1)+1) - BOXLX*NINT((COORDSB(3*(J1-1)+1)-XBEST(3*(J1-1)+1))/BOXLX))**2+ &
  &                    (COORDSB(3*(J1-1)+2)-XBEST(3*(J1-1)+2) - BOXLY*NINT((COORDSB(3*(J1-1)+2)-XBEST(3*(J1-1)+2))/BOXLY))**2
         IF (.NOT.TWOD) XDUMMY=XDUMMY+(COORDSB(3*(J1-1)+3)-XBEST(3*(J1-1)+3) - &
  &                                                             BOXLZ*NINT((COORDSB(3*(J1-1)+3)-XBEST(3*(J1-1)+3))/BOXLZ))**2
      ENDDO   
   ELSE
      XDUMMY=0.0D0
!     PRINT *, CMBX, CMBY, CMBZ
!     PRINT *, 'ROTINVBBEST'
!     PRINT *, ROTINVBBEST
      DO J1=1,NATOMS
         XBEST(3*(J1-1)+1:3*(J1-1)+3)=MATMUL(ROTINVBBEST,XBEST(3*(J1-1)+1:3*(J1-1)+3))
         XBEST(3*(J1-1)+1)=XBEST(3*(J1-1)+1)+CMBX
         XBEST(3*(J1-1)+2)=XBEST(3*(J1-1)+2)+CMBY
         XBEST(3*(J1-1)+3)=XBEST(3*(J1-1)+3)+CMBZ
         XDUMMY=XDUMMY+(COORDSB(3*(J1-1)+1)-XBEST(3*(J1-1)+1))**2+ &
  &                    (COORDSB(3*(J1-1)+2)-XBEST(3*(J1-1)+2))**2+ &
  &                    (COORDSB(3*(J1-1)+3)-XBEST(3*(J1-1)+3))**2
      ENDDO
   ENDIF
   IF (ABS(SQRT(XDUMMY)-SQRT(DISTANCE)).GT.GEOMDIFFTOL) THEN
      PRINT '(2(A,F20.10))',' MINPERMDIST> ERROR *** DISTANCE BETWEEN TRANSFORMED XBEST AND COORDSB=',SQRT(XDUMMY), &
  &                         ' SHOULD BE ',SQRT(DISTANCE)
      STOP
   ENDIF

   IF (NFREEZE.GT.0) THEN
      RMATBEST(1:3,1:3)=0.0D0
      RMATBEST(1,1)=1.0D0; RMATBEST(2,2)=1.0D0; RMATBEST(3,3)=1.0D0
   ELSE
      RMATBEST=MATMUL(ROTINVBBEST,RMATBEST)
   ENDIF
   COORDSA(1:3*NATOMS)=XBEST(1:3*NATOMS) ! FINALLY, BEST COORDSA SHOULD INCLUDE PERMUTATIONS FOR DNEB INPUT!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!  DO J1=1,(NATOMS/2)
!     XDUMMY=XDUMMY+(COORDSB(3*(J1-1)+1)-COORDSA(3*(J1-1)+1))**2+ &
! &                 (COORDSB(3*(J1-1)+2)-COORDSA(3*(J1-1)+2))**2+ &
! &                 (COORDSB(3*(J1-1)+3)-COORDSA(3*(J1-1)+3))**2
!  ENDDO
!  PRINT '(A,F20.10)','XDUMMY=',XDUMMY
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!     CLOSE(10)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! CALL POTENTIAL(COORDSA,ENERGY,VNEW,.TRUE.,.FALSE.,RMS,.FALSE.,.FALSE.)
! PRINT '(2(A,F25.15))',' BEFORE CHECK_VALLEAU A=',ENERGY,' RMS=',RMS
! CALL POTENTIAL(COORDSB,ENERGY,VNEW,.TRUE.,.FALSE.,RMS,.FALSE.,.FALSE.)
! PRINT '(2(A,F25.15))',' BEFORE CHECK_VALLEAU B=',ENERGY,' RMS=',RMS
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
      IF ((AMBERT.OR.NABT).AND.(.NOT.LOCALPERMDIST)) THEN
         CALL CHECK_VALLEU_CHIRALITY(COORDSB, COORDSA,DEBUG)
         CALL NEWMINDIST(COORDSB,COORDSA,NATOMS,DISTANCE,BULKT,TWOD,'AX    ',.TRUE.,RIGID,DEBUG,RMAT)
         DISTANCE=DISTANCE**2 ! MINPERMDIST USED TO RETURN THE DISTANCE SQUARED FOR HISTORICAL REASONS!
      ENDIF
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! CALL POTENTIAL(COORDSA,ENERGY,VNEW,.TRUE.,.FALSE.,RMS,.FALSE.,.FALSE.)
! PRINT '(2(A,F25.15))',' BEFORE CHECK_VALLEAU A=',ENERGY,' RMS=',RMS
! CALL POTENTIAL(COORDSB,ENERGY,VNEW,.TRUE.,.FALSE.,RMS,.FALSE.,.FALSE.)
! PRINT '(2(A,F25.15))',' BEFORE CHECK_VALLEAU B=',ENERGY,' RMS=',RMS
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! IF (DEBUG) PRINT '(A)',' MINPERMDIST> OVERALL PERMUTATION FOR COORDSA (SECOND ARGUMENT):'
! IF (DEBUG) PRINT '(20I6)',BESTPERM(1:NATOMS)
! PRINT '(I6)',NATOMS
! PRINT '(A)','COORDSA IN MINPERMDIST:'
! PRINT '(A,3F20.10)',('LA ',COORDSA(3*(J1-1)+1),COORDSA(3*(J1-1)+2),COORDSA(3*(J1-1)+3),J1=1,NATOMS)
! PRINT '(I6)',NATOMS
! PRINT '(A)','COORDSB IN MINPERMDIST:'
! PRINT '(A,3F20.10)',('LB ',COORDSB(3*(J1-1)+1),COORDSB(3*(J1-1)+2),COORDSB(3*(J1-1)+3),J1=1,NATOMS)

DISTANCE=SQRT(DISTANCE) ! NOW CHANGED TO RETURN DISTANCE, NOT DISTANCE^2 22/11/10 DJW

RETURN
END SUBROUTINE MINPERMDIST
