!   OPTIM: A PROGRAM FOR OPTIMIZING GEOMETRIES AND CALCULATING REACTION PATHWAYS
!   COPYRIGHT (C) 1999-2006 DAVID J. WALES
!   THIS FILE IS PART OF OPTIM.
!   
!   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!   (AT YOUR OPTION) ANY LATER VERSION.
!   
!   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!   
!   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!

MODULE MODAMBER
      IMPLICIT NONE
      SAVE

      DOUBLE PRECISION  TOP,BOTTOM,AX,BX,CX,AY,BY,CY,AZ,BZ,CZ,MU,LAMBDA,NUMER,DENOM,DX,DY,DZ
      DOUBLE PRECISION  TOTENERGY,BENERGY,TENERGY,PENERGY,ANSWER,IMPENERGY,QENERGY,VDWENERGY
      
      INTEGER ATOMS,ANG,IMP,COUNT,T
      INTEGER  A,B,IOS,D,E,F,G,H,I,J,K,L,COLIN,FISH,ANS,RINGS
      INTEGER  MATCH,BEAN,BONDNUMBER
      INTEGER NDIHEDRALS
      INTEGER, ALLOCATABLE, DIMENSION(:) :: DATOM1, DATOM2
      INTEGER LOOPATOM(20)
      INTEGER,ALLOCATABLE, DIMENSION (:,:) :: BONDARRAY
      DOUBLE PRECISION TINY
      PARAMETER  (TINY=1.0D-12)
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION (:) ::  X,Y,Z,PQ
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION (:,:) ::  R,VDWA,VDWB
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION (:) ::  MASS

      DOUBLE PRECISION GENTORSPARAMS(100,6),SPECTORSPARAMS(100,14),SPECIMPPARAMS(15,7)
      DOUBLE PRECISION MIDIMPPARAMS(4,6),GENIMPPARAMS(15,5)
  
      INTEGER, ALLOCATABLE, DIMENSION (:) :: AA1,AA2,AA3
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION (:) ::  THETA

      INTEGER, ALLOCATABLE, DIMENSION (:) :: DA1,DA2,DA3,DA4
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION (:) :: DPHI,DID,DVN,DVN2
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION (:) :: DVN3,DDELTA,DDELTA2,DDELTA3
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION (:) :: DN,DN2,DN3

      INTEGER, ALLOCATABLE, DIMENSION (:) :: IA1,IA2,IA3,IA4
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION (:) :: IPHI,IVN,IDELTA,IN1

      DOUBLE PRECISION  QX(3),QY(3),QZ(3)
      INTEGER, ALLOCATABLE, DIMENSION (:) :: ATNUM,BONDEDTO,TYPE
      INTEGER, ALLOCATABLE, DIMENSION (:,:) :: BONDS
      INTEGER, ALLOCATABLE, DIMENSION (:,:) :: ONE_FOUR,ONE_THREE
      CHARACTER(LEN=2)  TYPECHB,TYPECHC,TYPECHD,TYPECHE
      CHARACTER(LEN=20)  FILENAME
      CHARACTER, ALLOCATABLE, DIMENSION(:) ::  LABEL
      CHARACTER(LEN=2), ALLOCATABLE, DIMENSION(:) :: TYPECH
!
! VARIABLES FOR ENERGY CALCULATION
!
      CHARACTER(LEN=10)  CHECK
      DOUBLE PRECISION DIELEC
      PARAMETER  (DIELEC=1)
      LOGICAL FAKEWATER
      DOUBLE PRECISION RSTAR,EPSILON
      DOUBLE PRECISION VDWR(42),VDWE(42)
      DOUBLE PRECISION KR(42,42),RO(42,42)

      DOUBLE PRECISION KT(42,42,42),TO(42,42,42),DEGTO(42,42,42)
      DOUBLE PRECISION PK,PHASE,PK2,PK3,PHASE2,PHASE3,IPK,IPHASE

      INTEGER PN,IDIVF,PN2,PN3,IPN
!
! VARIABLES FOR DERIVATIVE CALCULATION
!
      DOUBLE PRECISION,ALLOCATABLE, DIMENSION(:) :: DBONDEBYDX,DBONDEBYDY,DBONDEBYDZ,DANGEBYDX, &
     &                 DANGEBYDY,DANGEBYDZ, &
     &                 DTORSEBYDX,DTORSEBYDY,DTORSEBYDZ,DVDWEBYDX, &
     &                 DVDWEBYDY,DVDWEBYDZ, &
     &                 DEBYDX,DEBYDY,DEBYDZ,DIMPEBYDX, &
     &                 DIMPEBYDY,DIMPEBYDZ, &
     &                 DQEBYDX,DQEBYDY,DQEBYDZ
!
! VARIABLES FOR SECOND DERIVATIVE CALCULATION
!
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) :: BONDHELL,ANGLEHELL,TORSHELL,  &
     &                 IMPHELL,QHELL,VDWHELL,HELL
      INTEGER HELLCOUNT
      INTEGER,ALLOCATABLE,DIMENSION(:) :: CHIRAL
      INTEGER,ALLOCATABLE,DIMENSION(:,:) :: CHIRALARRAY

END MODULE MODAMBER
