!   OPTIM: A PROGRAM FOR OPTIMIZING GEOMETRIES AND CALCULATING REACTION PATHWAYS
!   COPYRIGHT (C) 1999-2006 DAVID J. WALES
!   THIS FILE IS PART OF OPTIM.
!   
!   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!   (AT YOUR OPTION) ANY LATER VERSION.
!   
!   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!   
!   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!
MODULE MODCHARMM
   IMPLICIT NONE
   SAVE

! DAE OLD CHARMM-RELATED COMMON BLOCKS

      INTEGER, DIMENSION(:), ALLOCATABLE  :: NPHIPSI,NOMEGAC,NSIDECHAIN,NCHIRAL  ! CHDIHE
      INTEGER :: NPHIPSITOT,NOMEGACTOT,NSIDECHAINTOT,NCHIRALTOT
      INTEGER, DIMENSION(:), ALLOCATABLE :: PHIPSI,OMEGAC,SIDECHAIN,PSFPHI  ! CHDIHE
      INTEGER, ALLOCATABLE, DIMENSION(:) :: NSEGATOMS     ! DIMENSION WILL BE NSEG
      INTEGER :: CHARMMTYPE, CHSEEDI, CHSEEDJ, CHSEEDK    ! CHARMMWORD
      LOGICAL, DIMENSION(:), ALLOCATABLE :: ISSIDECHAIN
      LOGICAL :: TOMEGAC,TSIDECHAIN     ! CHARMMTWIST
      INTEGER, DIMENSION(:), ALLOCATABLE :: CHIRAL(:)
      LOGICAL :: CALCDIHE,OSASAT,ODIHET,CHECKCHIRALT,CHECKOMEGAT, ICINTERPT, CHBIT
      DOUBLE PRECISION :: MINOMEGA

      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: REFCOORD, REFPPSANGLE   ! CHREF
      INTEGER, DIMENSION(:), ALLOCATABLE :: REFIHB, REFJHB, REFKHB
      INTEGER  :: REFNHB

      INTEGER :: NMINB,NORDERB
      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: EMINB, ITXMINB, ITYMINB, ITZMINB, OMEGASTART
      DOUBLE PRECISION, DIMENSION(:) :: ORDERBPARAM(2)
      LOGICAL :: ORDERBT
      CHARACTER(LEN=8) ORDERBLABEL(2)

      LOGICAL :: FAILT, REBUILDSCT   ! USED TO BE PASSED TO NEB
      INTEGER :: TWISTTYPE, NGUESS, NCHENCALLS, ACEUPSTEP
      LOGICAL :: TRYNEB, ACESOLV, CHDEBUG, EDEBUG
      DOUBLE PRECISION  :: GUESSTHRESH, REBUILDSC
      DOUBLE PRECISION :: RPRO,PTRANS,TRANSMAX,PROT,ROTMAX

! FORMERLY IN KEY.H

      INTEGER :: NPERMDIHE
      LOGICAL :: CHRMMT,TWISTDIHET,PERTDIHET,GUESSTST,NOCISTRANS,NORANDOM,ENDHESS,ENDNUMHESS,PERMDIHET,INTMINT
      DOUBLE PRECISION :: MAXBFGSB,MAXBFGST,MAXBFGSP,MAXBFGSI,IMINCUT,RANDOMCUTOFF,PERMDIHE(20), EXTRASTEPS

END MODULE
