!   OPTIM: A PROGRAM FOR OPTIMIZING GEOMETRIES AND CALCULATING REACTION PATHWAYS
!   COPYRIGHT (C) 1999-2006 DAVID J. WALES
!   THIS FILE IS PART OF OPTIM.
!   
!   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!   (AT YOUR OPTION) ANY LATER VERSION.
!   
!   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!   
!   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!
MODULE MSEVB_INTERFACES
  
  INTERFACE
     SUBROUTINE MSEVB(NCOORDS, SYSTEMCOORDS, ASSIGNVBSTATES, ENERGY, ONLYASSIGNSTATES)
       USE MSEVB_COMMON
       INTEGER, INTENT(IN) :: NCOORDS  
       DOUBLE PRECISION, INTENT(IN) :: SYSTEMCOORDS(NCOORDS)
       LOGICAL, INTENT(IN) :: ASSIGNVBSTATES
       DOUBLE PRECISION, INTENT(OUT) :: ENERGY
       LOGICAL, OPTIONAL, INTENT(IN) :: ONLYASSIGNSTATES
     END SUBROUTINE MSEVB

     SUBROUTINE ASSIGNZUNDELSPECIES(FIRSTVBSTATE, SECONDVBSTATE, EXCHANGEH, CHECKEDHBOND, MINHBONDANGLERAD)
       USE MSEVB_COMMON     
       INTEGER, INTENT(IN) :: FIRSTVBSTATE, SECONDVBSTATE, EXCHANGEH
       LOGICAL, INTENT(IN) :: CHECKEDHBOND
       DOUBLE PRECISION, INTENT(IN) :: MINHBONDANGLERAD

     END SUBROUTINE ASSIGNZUNDELSPECIES

  END INTERFACE

END MODULE MSEVB_INTERFACES
