!   OPTIM: A PROGRAM FOR OPTIMIZING GEOMETRIES AND CALCULATING REACTION PATHWAYS
!   COPYRIGHT (C) 1999-2006 DAVID J. WALES
!   THIS FILE IS PART OF OPTIM.
!   
!   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!   (AT YOUR OPTION) ANY LATER VERSION.
!   
!   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!   
!   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!
SUBROUTINE MYCPU_TIME(POO,CHECKLIMIT)
USE PORFUNCS
USE KEY
IMPLICIT NONE
DOUBLE PRECISION MYTIME
DOUBLE PRECISION, INTENT(OUT) :: POO
LOGICAL, INTENT(IN) :: CHECKLIMIT

CALL CPU_TIME(MYTIME)
POO=MYTIME ! WITHOUT THIS EXTRA ASSIGNMENT NAG F95 RETURNS A RANDOM NUMBER!
           ! SAVING TSTART IS NECESSARY FOR PG COMPILER, WHERE INITIAL TIME IS
           ! NOT ZERO!
IF (.NOT.CHECKLIMIT) RETURN ! WE DON;T WANT TO STOP HALF WAY THROUGH A PATH, FOR EXAMPLE
IF (MYTIME-TSTART.GT.TIMELIMIT) THEN
   PRINT '(A,F12.1,A,F12.1)','CPU TIME LIMIT EXCEEDED: TIME=',MYTIME-TSTART,' LIMIT=',TIMELIMIT
   IF (DUMPSP) CALL DODUMPSP
   STOP
ENDIF

RETURN
END SUBROUTINE MYCPU_TIME
