C   COPYRIGHT (C) 1999-2006 DAVID J. WALES
C   THIS FILE IS PART OF GMIN.
C
C   GMIN IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C   (AT YOUR OPTION) ANY LATER VERSION.
C
C   GMIN IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
C   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
C   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
C   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
C
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C  PUT PERMUTATIONAL ISOMERS INTO A STANDARD ORIENTATION.
C
      SUBROUTINE MYORIENT(Q1,T1,NORBIT1,NCHOOSE1,NORBIT2,NCHOOSE2,NATOMS,DEBUG,ROT,ROTINV,STOCKT)
      USE KEY, ONLY : LPDGEOMDIFFTOL, LOCALPERMDIST, PULLT, EFIELDT
      IMPLICIT NONE
      INTEGER J1, I, JMAX1, JMAX2, NORBIT1, NCHOOSE1, NORBIT2, NCHOOSE2, NATOMS, J2, J3
      DOUBLE PRECISION Q1(3*NATOMS), DIST(NATOMS), DMAX, RVEC(3), T1(3*NATOMS), CMX, CMY, CMZ, T2(3*NATOMS),
     1                 COST, SINT, RDOTN, TX, TY, TZ, IT(3,3), IV(3,3), PROJ, DMAX2, CUTOFF1
      DOUBLE PRECISION ROT(3,3), XVEC(3), YVEC(3), ZVEC(3), ROTINV(3,3), TEMP(3,3), TVEC(3*NATOMS), DUMMY
      DOUBLE PRECISION TXVEC(3), TYVEC(3), TZVEC(3)
      LOGICAL DEBUG, STOCKT
      DOUBLE PRECISION ENERGY, RMS, VNEW(3*NATOMS), DTEMP

      CUTOFF1=1.0D-3
      IF (LOCALPERMDIST) CUTOFF1=LPDGEOMDIFFTOL
C
C  USE UNIT VECTORS ALONG THE X, Y, Z AXES TO KEEP TRACK OF OVERALL TRANSFORMATION MATRIX.
C
      XVEC(1)=1.0D0; XVEC(2)=0.0D0; XVEC(3)=0.0D0
      YVEC(1)=0.0D0; YVEC(2)=1.0D0; YVEC(3)=0.0D0
      ZVEC(1)=0.0D0; ZVEC(2)=0.0D0; ZVEC(3)=1.0D0
C
C  MOVE CENTRE OF MASS TO THE ORIGIN.
C
      CMX=0.0D0
      CMY=0.0D0
      CMZ=0.0D0
      DO I=1,NATOMS
         CMX=CMX+Q1(3*(I-1)+1)
         CMY=CMY+Q1(3*(I-1)+2)
         CMZ=CMZ+Q1(3*(I-1)+3)
      ENDDO
      CMX=CMX/NATOMS
      CMY=CMY/NATOMS
      CMZ=CMZ/NATOMS
C     PRINT*,'CMX,CMY,CMZ=',CMX,CMY,CMZ
      DO I=1,NATOMS
         Q1(3*(I-1)+1)=Q1(3*(I-1)+1)-CMX
         Q1(3*(I-1)+2)=Q1(3*(I-1)+2)-CMY
         Q1(3*(I-1)+3)=Q1(3*(I-1)+3)-CMZ
      ENDDO

      DMAX=-1.0D0
      NORBIT1=1
!
! WE CAN ONLY ROTATE AROUND THE Z AXIS WITH A PULLING POTENTIAL!
!
      IF (PULLT.OR.EFIELDT) THEN
         T1(1:3*NATOMS)=Q1(1:3*NATOMS)
         GOTO 10
      ENDIF
      DO J1=1,NATOMS
         DIST(J1)=SQRT(Q1(3*(J1-1)+1)**2+Q1(3*(J1-1)+2)**2+Q1(3*(J1-1)+3)**2)
!        PRINT '(A,I8,4F20.10)','J1,DMAX,DIST(J1),ABS(DIST(J1)-DMAX),CUTOFF1=',J1,DMAX,DIST(J1),ABS(DIST(J1)-DMAX),CUTOFF1
         IF (ABS(DIST(J1)-DMAX).LT.CUTOFF1) THEN
            NORBIT1=NORBIT1+1
            IF (NORBIT1.EQ.NCHOOSE1) THEN
               JMAX1=J1
            ENDIF
!           IF (DIST(J1).GT.DMAX) THEN ! TRY TO CATCH THE CASE WHERE 0.001 ISN;T SMALL ENOUGH!
!              DMAX=DIST(J1)
!              JMAX1=J1
!           ENDIF
         ELSE IF (DIST(J1).GT.DMAX) THEN
            DMAX=DIST(J1)
            NORBIT1=1
            JMAX1=J1
         ENDIF
!        PRINT '(A,I8,2G20.10,3I8)','J1,DIST,DMAX,JMAX1,NCHOOSE1,NORBIT1=',J1,DIST(J1),DMAX,JMAX1,NCHOOSE1,NORBIT1
      ENDDO

C
C  FOR TAGGED ATOMS THE CHOICE OF THE FIRST ATOM MATTERS IF IT BELONGS TO AN ORBIT OF SIZE > 1.
C
!     WRITE(*,'(A,G20.10,A,G20.10)') 'ATOM ',JMAX1,' WILL BE MOVED ONTO THE Z AXIS, DISTANCE=',DIST(JMAX1) 
      IF ((ABS(Q1(3*(JMAX1-1)+1)).LT.1.0D-8).AND.(ABS(Q1(3*(JMAX1-1)+2)).LT.1.0D-8)) THEN
         IF (Q1(3*(JMAX1-1)+3).GT.0.0D0) THEN
            T1(1:3*NATOMS)=Q1(1:3*NATOMS)
         ELSE  ! ROTATE ABOUT THE X AXIS DO NOT INVERT!!
            DO J1=1,NATOMS
               T1(3*(J1-1)+1)=Q1(3*(J1-1)+1)
               T1(3*(J1-1)+2)=-Q1(3*(J1-1)+2)
               T1(3*(J1-1)+3)=-Q1(3*(J1-1)+3)
            ENDDO
            YVEC(2)=-1.0D0
            ZVEC(3)=-1.0D0
         ENDIF
         GOTO 10
      ENDIF
!
! FOR SLOPPY CUTOFFS WE CANNOT ASSUME THAT DMAX IS EXACTLY THE SAME FOR MEMBERS OF THE SAME ORBIT!!
!
!     COST=Q1(3*(JMAX1-1)+3)/DMAX
!     SINT=SQRT(Q1(3*(JMAX1-1)+1)**2+Q1(3*(JMAX1-1)+2)**2)/DMAX
!
      COST=Q1(3*(JMAX1-1)+3)/DIST(JMAX1)
      SINT=SQRT(Q1(3*(JMAX1-1)+1)**2+Q1(3*(JMAX1-1)+2)**2)/DIST(JMAX1)
C
C  ROTATE ATOM JMAX1 ONTO THE Z AXIS.
C  ROTATE ALL THE ATOMS THROUGH ANGLE ABOUT RVEC. USE ROTATION FORMULA
C  FROM GOLDSTEIN P. 165.
C
      RVEC(1)= Q1(3*(JMAX1-1)+2)/SQRT(Q1(3*(JMAX1-1)+1)**2+Q1(3*(JMAX1-1)+2)**2)
      RVEC(2)=-Q1(3*(JMAX1-1)+1)/SQRT(Q1(3*(JMAX1-1)+1)**2+Q1(3*(JMAX1-1)+2)**2)
      RVEC(3)=0.0D0
C
      DO J1=1,NATOMS
C        IF (DIST(J1).NE.0.0D0) THEN
            RDOTN=Q1(3*(J1-1)+1)*RVEC(1)+Q1(3*(J1-1)+2)*RVEC(2)+Q1(3*(J1-1)+3)*RVEC(3)
            T1(3*(J1-1)+1)=Q1(3*(J1-1)+1)*COST + RVEC(1)*RDOTN*(1-COST)-(Q1(3*(J1-1)+2)*RVEC(3)-Q1(3*(J1-1)+3)*RVEC(2))*SINT
            T1(3*(J1-1)+2)=Q1(3*(J1-1)+2)*COST + RVEC(2)*RDOTN*(1-COST)-(Q1(3*(J1-1)+3)*RVEC(1)-Q1(3*(J1-1)+1)*RVEC(3))*SINT
            T1(3*(J1-1)+3)=Q1(3*(J1-1)+3)*COST + RVEC(3)*RDOTN*(1-COST)-(Q1(3*(J1-1)+1)*RVEC(2)-Q1(3*(J1-1)+2)*RVEC(1))*SINT
C        ENDIF
      ENDDO
C
C
C  TRACK TRANSFORMATION OF UNIT VECTORS.
C
      RDOTN=RVEC(1)
      XVEC(1)=COST + RVEC(1)*RDOTN*(1-COST)
      XVEC(2)=       RVEC(2)*RDOTN*(1-COST)+RVEC(3)*SINT
      XVEC(3)=       RVEC(3)*RDOTN*(1-COST)-RVEC(2)*SINT

      RDOTN=RVEC(2)
      YVEC(1)=       RVEC(1)*RDOTN*(1-COST)-RVEC(3)*SINT
      YVEC(2)=COST + RVEC(2)*RDOTN*(1-COST)
      YVEC(3)=       RVEC(3)*RDOTN*(1-COST)+RVEC(1)*SINT

      RDOTN=RVEC(3)
      ZVEC(1)=       RVEC(1)*RDOTN*(1-COST)+RVEC(2)*SINT
      ZVEC(2)=       RVEC(2)*RDOTN*(1-COST)-RVEC(1)*SINT
      ZVEC(3)=COST + RVEC(3)*RDOTN*(1-COST)

C     DO J1=1,3*NATOMS
C        Q1(J1)=T1(J1)
C     ENDDO

10    CONTINUE
C     IF (DEBUG) THEN
C        WRITE(4,'(I5)') NATOMS
C        WRITE(4,'(A)') 'AFTER FIRST ORIENT ROTATION:'
C        WRITE(4,'(A5,3F20.10)') 'LA   ',T1(1),T1(2),T1(3)
C        DO J1=2,NATOMS
C           WRITE(4,'(A5,3F20.10)') 'LB   ',T1(3*(J1-1)+1),T1(3*(J1-1)+2),T1(3*(J1-1)+3)
C        ENDDO
C     ENDIF
C
C  FIND THE ATOM WITH THE LARGEST DISTANCE FROM THE Z AXIS.
C
      DMAX=-1.0D0
      DO J1=1,NATOMS
         DIST(J1)=SQRT(T1(3*(J1-1)+1)**2+T1(3*(J1-1)+2)**2)
         IF (DIST(J1).GT.DMAX) DMAX=DIST(J1) 
      ENDDO
      DMAX2=-1.0D100

C  PROJ IS THE SUM OF THE X COMPONENTS. TVEC ARGUMENTS ARE DUMMYS HERE.
C  USE T2 AS A DUMMY IN ORDER NOT TO CHANGE T1 UNTIL WE HAVE DECIDED WHICH 
C  ATOM TO PUT IN THE XZ PLANE.
C
      TXVEC(1:3)=0.0D0; TYVEC(1:3)=0.0D0;TZVEC(1:3)=0.0D0
      DO J1=1,NATOMS
!        PRINT '(A,I8,3F20.10)','Z J1,DMAX,DIST(J1),ABS(DIST(J1)-DMAX)=',J1,DMAX,DIST(J1),ABS(DIST(J1)-DMAX)
!        PRINT '(A,2F20.10,L5)','ABS(DIST(J1)-DMAX),CUTOFF1,TEST=',ABS(DIST(J1)-DMAX),CUTOFF1,ABS(DIST(J1)-DMAX).LT.CUTOFF1
         IF (ABS(DIST(J1)-DMAX).LT.CUTOFF1) THEN
            T2(1:3*NATOMS)=T1(1:3*NATOMS)
            CALL ROTXZ(NATOMS,J1,T2,PROJ,DIST,TXVEC,TYVEC,TZVEC,CUTOFF1)
!           PRINT '(A,I8,3G20.10)','J1,DMAX2,PROJ,ABS(ABS(PROJ-DMAX2)=',J1,DMAX2,PROJ,ABS(PROJ-DMAX2)
            IF (ABS(PROJ-DMAX2).LT.CUTOFF1) THEN
               NORBIT2=NORBIT2+1
               IF (NORBIT2.EQ.NCHOOSE2) THEN
                  JMAX2=J1
               ENDIF
            ELSE IF (PROJ.GT.DMAX2) THEN
               NORBIT2=1
               DMAX2=PROJ
               JMAX2=J1
            ENDIF
!           PRINT '(A,2G20.10)','PROJ,DMAX2=',PROJ,DMAX2
         ENDIF
      ENDDO
!     IF (DEBUG) PRINT '(A,6I6)','MYORIENT> NORBIT1,NCHOOSE1,NORBIT2,NCHOOSE2,JMAX1,JMAX2=',
!    &                            NORBIT1,NCHOOSE1,NORBIT2,NCHOOSE2,JMAX1,JMAX2
C
C  AND ROTATE IT INTO THE XZ PLANE.
C
!     IF (DEBUG) PRINT '(A,I6,A,G20.10,A)','ATOM ',JMAX2,' IS NOW THE FURTHEST FROM THE  Z AXIS, DISTANCE=', 
!    &                                        DIST(JMAX2),' ROTATE INTO XZ PLANE'
!
! THE CORRECT DISTANCE FROM THE Z AXIS IS USED FOR EACH ATOM - THEY ARE SAVED IN THE VECTOR DIST
! DMAX2 IS A DUMMY HERE.
!

      CALL ROTXZ(NATOMS,JMAX2,T1,DMAX2,DIST,XVEC,YVEC,ZVEC,CUTOFF1)

!     IF (DEBUG) PRINT*,'AFTER MYORIENT'
!     IF (DEBUG) WRITE(*,'(3F20.10)') (T1(J1),J1=1,3*NATOMS)

      ROT(1:3,1)=XVEC(1:3); ROT(1:3,2)=YVEC(1:3); ROT(1:3,3)=ZVEC(1:3)
      ROTINV(1,1:3)=XVEC(1:3); ROTINV(2,1:3)=YVEC(1:3); ROTINV(3,1:3)=ZVEC(1:3) ! TRANSPOSE
C
C  CHECK ORTHOGONALITY:
C
C     DO J1=1,3
C        DO J2=1,3
C           DUMMY=0.0D0
C           DO J3=1,3
C              DUMMY=DUMMY+ROT(J1,J3)*ROTINV(J3,J2)
C           ENDDO
C           TEMP(J1,J2)=DUMMY
C        ENDDO
C     ENDDO
C     PRINT '(A)','MYORIENT> TRANSFORMATION PRODUCT:'
C     PRINT '(3F20.10)',TEMP(1:3,1:3)
C
C  COMPARE Q1, ROT * T1, ROTINV * T1
C
C     PRINT '(A)','MYORIENT> ORIGINAL COORDINATES:'
C     PRINT '(6F20.10)',Q1(1:12)
C     DO J1=1,NATOMS
C        DO J2=1,3
C           DUMMY=0.0D0
C           DO J3=1,3
C              DUMMY=DUMMY+ROT(J2,J3)*T1(3*(J1-1)+J3)
C           ENDDO
C           TVEC(3*(J1-1)+J2)=DUMMY
C        ENDDO
C     ENDDO
C     PRINT '(A)','MYORIENT> ROT * T1:'
C     PRINT '(6F20.10)',TVEC(1:12)
C     DO J1=1,NATOMS
C        DO J2=1,3
C           DUMMY=0.0D0
C           DO J3=1,3
C              DUMMY=DUMMY+ROTINV(J2,J3)*T1(3*(J1-1)+J3)
C           ENDDO
C           TVEC(3*(J1-1)+J2)=DUMMY
C        ENDDO
C     ENDDO
C     PRINT '(A)','MYORIENT> ROTINV * T1:'
C     PRINT '(6F20.10)',TVEC(1:12)

      RETURN
      END

      SUBROUTINE ROTXZ(NATOMS,JDO,T1,PROJ,DIST,XVEC,YVEC,ZVEC,CUTOFF1)
      IMPLICIT NONE
      INTEGER NATOMS, JDO, J1, J3
      DOUBLE PRECISION T1(3*NATOMS), PROJ, DIST(NATOMS), RVEC(3), COST, SINT, RDOTN, TX, TY, TZ, CUTOFF1
      DOUBLE PRECISION XVEC(3), YVEC(3), ZVEC(3)

C     PRINT '(I6)',NATOMS
C     PRINT '(A,I6,G20.10)','BEFORE ROTATION'
C     WRITE(*,'(A2,2X,3G20.10)') ('LA',T1(3*(J3-1)+1),T1(3*(J3-1)+2),T1(3*(J3-1)+3),J3=1,NATOMS)

      IF (ABS(T1(3*(JDO-1)+2)).LT.1.0D-8) THEN
         IF (T1(3*(JDO-1)+1).LT.0.0D0) THEN ! ROTATE ABOUT THE Z AXIS DO NOT INVERT!!
            DO J1=1,NATOMS
               T1(3*(J1-1)+1)=-T1(3*(J1-1)+1)
               T1(3*(J1-1)+2)=-T1(3*(J1-1)+2)
            ENDDO
            XVEC(1)=-XVEC(1); XVEC(2)=-XVEC(2)
            YVEC(1)=-YVEC(1); YVEC(2)=-YVEC(2)
            ZVEC(1)=-ZVEC(1); ZVEC(2)=-ZVEC(2)
         ENDIF
         GOTO 20
      ENDIF

      COST=T1(3*(JDO-1)+1)/DIST(JDO)
      SINT=T1(3*(JDO-1)+2)/DIST(JDO)
C     PRINT '(A,4G20.10)','T1(3*(JDO-1)+2),COST,SINT,1=',T1(3*(JDO-1)+2),COST,SINT,COST**2+SINT**2
      IF (ABS(COST**2+SINT**2-1.0D0).GT.2.0D-3) THEN
         WRITE(*, '(A,G20.10)') 'ERROR - IN ROTXZ COS**2+SIN**2=',COST**2+SINT**2
         STOP
      ENDIF
      RVEC(1)=0.0D0
      RVEC(2)=0.0D0
      RVEC(3)=1.0D0
      DO J1=1,NATOMS
         IF (DIST(J1).NE.0.0D0) THEN
            RDOTN=T1(3*(J1-1)+1)*RVEC(1)+T1(3*(J1-1)+2)*RVEC(2)+T1(3*(J1-1)+3)*RVEC(3)
            TX=T1(3*(J1-1)+1)*COST + RVEC(1)*RDOTN*(1-COST)+(T1(3*(J1-1)+2)*RVEC(3)-T1(3*(J1-1)+3)*RVEC(2))*SINT
            TY=T1(3*(J1-1)+2)*COST + RVEC(2)*RDOTN*(1-COST)+(T1(3*(J1-1)+3)*RVEC(1)-T1(3*(J1-1)+1)*RVEC(3))*SINT
            TZ=T1(3*(J1-1)+3)*COST + RVEC(3)*RDOTN*(1-COST)+(T1(3*(J1-1)+1)*RVEC(2)-T1(3*(J1-1)+2)*RVEC(1))*SINT
            T1(3*(J1-1)+1)=TX
            T1(3*(J1-1)+2)=TY
            T1(3*(J1-1)+3)=TZ
         ENDIF
      ENDDO
      RDOTN=XVEC(1)*RVEC(1)+XVEC(2)*RVEC(2)+XVEC(3)*RVEC(3)
      TX=XVEC(1)*COST + RVEC(1)*RDOTN*(1-COST)+(XVEC(2)*RVEC(3)-XVEC(3)*RVEC(2))*SINT
      TY=XVEC(2)*COST + RVEC(2)*RDOTN*(1-COST)+(XVEC(3)*RVEC(1)-XVEC(1)*RVEC(3))*SINT
      TZ=XVEC(3)*COST + RVEC(3)*RDOTN*(1-COST)+(XVEC(1)*RVEC(2)-XVEC(2)*RVEC(1))*SINT
      XVEC(1)=TX; XVEC(2)=TY; XVEC(3)=TZ
      RDOTN=YVEC(1)*RVEC(1)+YVEC(2)*RVEC(2)+YVEC(3)*RVEC(3)
      TX=YVEC(1)*COST + RVEC(1)*RDOTN*(1-COST)+(YVEC(2)*RVEC(3)-YVEC(3)*RVEC(2))*SINT
      TY=YVEC(2)*COST + RVEC(2)*RDOTN*(1-COST)+(YVEC(3)*RVEC(1)-YVEC(1)*RVEC(3))*SINT
      TZ=YVEC(3)*COST + RVEC(3)*RDOTN*(1-COST)+(YVEC(1)*RVEC(2)-YVEC(2)*RVEC(1))*SINT
      YVEC(1)=TX; YVEC(2)=TY; YVEC(3)=TZ
      RDOTN=ZVEC(1)*RVEC(1)+ZVEC(2)*RVEC(2)+ZVEC(3)*RVEC(3)
      TX=ZVEC(1)*COST + RVEC(1)*RDOTN*(1-COST)+(ZVEC(2)*RVEC(3)-ZVEC(3)*RVEC(2))*SINT
      TY=ZVEC(2)*COST + RVEC(2)*RDOTN*(1-COST)+(ZVEC(3)*RVEC(1)-ZVEC(1)*RVEC(3))*SINT
      TZ=ZVEC(3)*COST + RVEC(3)*RDOTN*(1-COST)+(ZVEC(1)*RVEC(2)-ZVEC(2)*RVEC(1))*SINT
      ZVEC(1)=TX; ZVEC(2)=TY; ZVEC(3)=TZ

20    CONTINUE

      PROJ=0.0D0
!
! FOR POSSIBLY SLOPPY ALIGNMENTS WITH LOCALPERMDIST IT MAY BE IMPORTANT TO
! INCREASE THE CUTOFF AND USE CUTOFF1 ! DJW 27/8/09
!
      DO J1=1,NATOMS
C        IF (T1(3*(J1-1)+3).GT.1.0D-2) PROJ=PROJ+T1(3*(J1-1)+1)
         IF (T1(3*(J1-1)+3).GT.CUTOFF1) PROJ=PROJ+T1(3*(J1-1)+1)
      ENDDO
C     PRINT '(I6)',NATOMS
C     PRINT '(A,I6,G20.10)','AFTER ROTATION ATOM,PROJ=',JDO,PROJ
C     WRITE(*,'(A2,2X,3G20.10)') ('LA',T1(3*(J3-1)+1),T1(3*(J3-1)+2),T1(3*(J3-1)+3),J3=1,NATOMS)

      RETURN
      END
