C
C GPL LICENSE INFO {{{
C   OPTIM: A PROGRAM FOR OPTIMIZING GEOMETRIES AND CALCULATING REACTION PATHWAYS
C   COPYRIGHT (C) 1999-2006 DAVID J. WALES
C   THIS FILE IS PART OF OPTIM.
C
C   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C   (AT YOUR OPTION) ANY LATER VERSION.
C
C   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
C   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
C   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
C   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
C }}}
C
C JMC NOTE NOTHING HAS BEEN DONE HERE TO FIX THE UNRES PATHLENGTH COORDINATE RESETTING PROBLEM...
C
      SUBROUTINE PATH(Q,ENERGY,VNEW,RMS,EVTS,VECS,POTCALL,QPLUS,QMINUS,PTEST,ETS,EPLUS,EMINUS,SLENGTH,DISP,GAMMA,NTILDE,
     1                FRQSTS,FRQSPLUS,FRQSMINUS,ITSTRING,EOFSSTRING,PATHFAILT)
! DECLARATIONS {{{
      ! MODULE DECLARATIONS {{{
      USE COMMONS
      USE KEY
      USE SYMINF
      USE MODCHARMM
      USE MODUNRES
      USE MODHESS
      USE MODEFOL
      USE PORFUNCS
      USE AMHGLOBALS, ONLY : NMRES
      ! }}}

      IMPLICIT NONE

! SUBROUTINE PARAMETERS {{{

      DOUBLE PRECISION ENERGY, VNEW(3*NATOMS), RMS, EVTS, VECS(3*NATOMS)
      DOUBLE PRECISION Q(3*NATOMS), QPLUS(3*NATOMS), QMINUS(3*NATOMS)
      DOUBLE PRECISION ETS, EPLUS, EMINUS, SLENGTH, DISP, GAMMA, NTILDE
      DOUBLE PRECISION FRQSTS(3*NATOMS), FRQSPLUS(3*NATOMS), FRQSMINUS(3*NATOMS)
       
      LOGICAL POTCALL, PTEST
      LOGICAL PATHFAILT
      CHARACTER(LEN=*) ITSTRING,EOFSSTRING

! }}}

! LOCAL PARAMETERS {{{

      INTEGER NSTEPPLUS, ITDONE, NSTEPMINUS, J1, J2, NPATHFRAME, NATOMSSAVE, NEWINR, 
     1        INEG, HORDER, INFO, IVECSAVE, IVEC2SAVE, IPOT, J3, NFPLUS, NFMINUS, RECLEN, ISTAT, NUSE
      INTEGER, PARAMETER :: NSTEPMAX=50000, NFMAX=20000

      DOUBLE PRECISION EVALMAX, RANDOM,
     1                 DIAG(3*NATOMS), EREAL, RMS2, STEP(3*NATOMS), QINIT(3*NATOMS),
     2                 EOFS(NSTEPMAX), PATHLENGTH(NSTEPMAX), TEMP, MINIM, EOFSFRAMEP(NSTEPMAX),
     3                 SUM2, SUM4, EVPLUS, EVMINUS, EOFSFRAMEM(NSTEPMAX),
     4                 SPLUS, SMINUS, STS, STEMP, ETEMP, DUMMY, TIME, TIME0,
     5                 OVEC(3), H1VEC(3), H2VEC(3),
     6                 TEMPA(9*NATOMS), CAPSCOORDS1(18), CAPSCOORDS2(18), 
     7                 DPRAND, PPLUS, PMINUS, LAMBDATS, LAMBDAP, LAMBDAM, DISTP, DISTM, RMAT(3,3) !, P(3)
      LOGICAL CONNECTT, DUMPPATH, READPATH, CALCRATES, STOPFIRST, ETEST, NOSHIFTSAVE, NOHESSSAVE
      DOUBLE PRECISION TEMPERATURE, HRED, DIHE, ALLANG, LASTE
      INTEGER NCONNECT
      COMMON /CONN/ STOPFIRST, CONNECTT, NCONNECT, DUMPPATH, READPATH, CALCRATES, TEMPERATURE, HRED
      DOUBLE PRECISION CAPSRHO, EPS2, RAD, HEIGHT
      COMMON /CAPS/ CAPSRHO, EPS2, RAD, HEIGHT

C JMC
      CHARACTER(LEN=80) ITSTRING2
      DOUBLE PRECISION NEWINT(NINTS),TSINT(NINTS)
      DOUBLE PRECISION PEPCOORDS(3*NATOMS), INERTIA(3,3)
      INTEGER K1,K2,KD,NNZ,NINTB
C JMC

C    LOCAL AMH VARIABLES
      INTEGER GLY_COUNT
C      CHARACTER(LEN=5) TARFL

      LOGICAL MFLAG, BFGSTSTSAVE
      LOGICAL PATHT, DRAGT
      COMMON /RUNTYPE/ DRAGT, PATHT, NPATHFRAME
      LOGICAL KNOWE, KNOWG, KNOWH
      COMMON /KNOWN/ KNOWE, KNOWG, KNOWH
      INTEGER NATOMSIMUL
      CHARACTER(LEN=5) ZSYMSAVE
      COMMON /SYS/ ZSYMSAVE
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: Q1, Q2, QW
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) :: QFRAMEP, QFRAMEM
! }}}
! }}}
! SUBROUTINE BODY {{{ 
      PATHFAILT=.FALSE.

      IF (BULKT.AND.(PARAM1*PARAM2*PARAM3.EQ.0.0D0)) THEN
        ! ACCOUNT FOR ZERO BOX SIZE {{{
         IF (TWOD) THEN
            IF (PARAM1*PARAM2.EQ.0.0D0) THEN
               PRINT '(A)',' PATH> ERROR - BULKT IS TRUE BUT A BOX PARAMETER IS ZERO' 
               STOP
            ENDIF
         ELSE 
            PRINT '(A)',' PATH> ERROR - BULKT IS TRUE BUT A BOX PARAMETER IS ZERO' 
            STOP
         ENDIF
         ! }}}
      ENDIF

C  CALLS TO DUMPP DUMP ENERGIES AND COORDINATES ON UNITS 1 AND 2. MUST REWIND FOR PATH TO WORK.
C  IF PRINTPTS IS .FALSE. THEN REDUCE THE I/O TO A BARE MINIMUM. USE
C  QPLUS, QINIT AND QMINUS FOR THE STATIONARY POINTS RATHER THAN READING THROUGH
C  POINTS SAVED ON DISK.
C
      IF (PRINTPTS) THEN 
         REWIND(1)  ! POINTS FILE
         REWIND(2)  ! ENERGIES FILE
      ENDIF
      BFGSTSTSAVE=BFGSTST
      IVECSAVE=IVEC
      IVEC2SAVE=IVEC2
C
C  PLUS SIDE FIRST. {{{
C
      IVEC=1
      DO J1=1,NOPT
         QINIT(J1)=Q(J1)
      ENDDO
!     IF (DEBUG) PRINT*,'TS POINTS IN PATH:'
!     IF (DEBUG) WRITE(*,'(3G20.10)') (Q(J1),J1=1,NOPT)

      CALL MYCPU_TIME(TIME0,.FALSE.)
      IF (HYBRIDMINT) THEN
        ! USE HYBRID MINIMIZATION, KEYWORDS: HYBRIDMIN {{{
!
! WE MUST HAVE THE TS ENERGY SOMEWHERE ALREADY. SHOULD;T REALLY NEED THE CALL TO POTENTIAL.
!
         CALL POTENTIAL(Q,ETS,VNEW,.TRUE.,.FALSE.,RMS,.FALSE.,.FALSE.)
         ENERGY=ETS
         POTCALL=.TRUE.
         CALL DUMPP(Q,ENERGY)
         CALL HYBRIDMIN(HMNSTEPS,Q,ENERGY,VNEW,MFLAG,RMS,EVTS,EVALMAX,VECS,ITDONE,POTCALL,PTEST)
         NSTEPPLUS=ITDONE
         IF (.NOT.MFLAG) THEN
            IF (PTEST) PRINT '(A,I8,A)','EFOL> SWITCHING TO LBFGS MINIMISATION AFTER ',NSTEPPLUS,' HYBRID MINIMISATION STEPS'
            KNOWE=.FALSE.
            KNOWG=.FALSE.
            IF (CHRMMT.AND.INTMINT) THEN
               CALL MYLBFGS(NINTS,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                      .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
            ELSE
               CALL MYLBFGS(NOPT,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                      .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
            END IF
            NSTEPPLUS=NSTEPPLUS+ITDONE
         ENDIF
         ! }}}
      ELSE IF (BFGSTST) THEN
        ! KEYWORDS: BFGSTS BFGSSTEP 
        !       BFGSTS: HYBRID BFGS/EIGENVECTOR-FOLLOWING TRANSITION STATE SEARCH {{{
         BFGSSTEP=.TRUE.
         IF (UNRST) THEN
            CALL INTBFGSTS(NSTEPS,Q,ENERGY,VNEW,MFLAG,RMS,EVTS,EVALMAX,VECS,ITDONE,POTCALL,PTEST)
         ELSE
            CALL BFGSTS(NSTEPS,Q,ENERGY,VNEW,MFLAG,RMS,EVTS,EVALMAX,VECS,ITDONE,POTCALL,PTEST)
         ENDIF
         ETS=ENERGY
!        IF (DEBUG) PRINT*,'TS STEP OFF PLUS POINTS IN PATH:'
!        IF (DEBUG) WRITE(*,'(3G20.10)') (Q(J1),J1=1,NOPT)
         DO J1=1,NOPT
            STEP(J1)=Q(J1)-QINIT(J1)
         ENDDO
         
         IF (RKMIN) RMS=1.0D0
         MFLAG=.FALSE.
         BFGSSTEP=.FALSE.
         BFGSTST=.FALSE.
         IF (BFGSMINT) THEN
            IF (UNRST.OR.(CHRMMT.AND.INTMINT)) THEN
                CALL MYLBFGS(NINTS,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                       .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
            ELSE
                CALL MYLBFGS(NOPT,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                       .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
            ENDIF
            NSTEPPLUS=ITDONE+1
         ELSE IF (BBRSDMT) THEN
            CALL BBRSDM(Q,MFLAG,ITDONE,ENERGY,RMS,.FALSE.,VNEW,PTEST)
            NSTEPPLUS=ITDONE+1
C
C DAE TO SWITCH TO BFGS AFTER NSTEPS SD
C
            IF (.NOT.MFLAG) THEN
               KNOWE=.FALSE.
               KNOWG=.FALSE.
               IF (CHRMMT.AND.INTMINT) THEN
                  CALL MYLBFGS(NINTS,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                         .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
               ELSE
                  CALL MYLBFGS(NOPT,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                         .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
               ENDIF
               NSTEPPLUS=NSTEPPLUS+ITDONE
            ENDIF
         ELSE IF (BSMIN.OR.RKMIN) THEN
            NUSE=NSTEPS
            IF (PATHSDSTEPS.GT.0) NUSE=PATHSDSTEPS
            CALL ODESD(NUSE,Q,MFLAG,ITDONE,PTEST)
            NSTEPPLUS=ITDONE+1
C
C DAE TO SWITCH TO BFGS AFTER NSTEPS SD
C
            IF (.NOT.MFLAG) THEN
               KNOWE=.FALSE.
               KNOWG=.FALSE.
               IF (CHRMMT.AND.INTMINT) THEN
                  CALL MYLBFGS(NINTS,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                         .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
               ELSE
                  CALL MYLBFGS(NOPT,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                         .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
               ENDIF
               NSTEPPLUS=NSTEPPLUS+ITDONE
            ELSE
!
!  ODESD DOES NOT RETURN THE ENERGY!
!
               CALL POTENTIAL(Q,ENERGY,VNEW,.FALSE.,.FALSE.,RMS,.FALSE.,.FALSE.)
            ENDIF
C END DAE
         ELSE
            IF (INR.LT.6) THEN
               NEWINR=0 ! SO WE CAN USE PAGE-MCIVER
            ELSE
               NEWINR=INR
            ENDIF
C BS360 (29/07/08): ACE DOES NOT CONVERGE WITH SD. I WILL INVESTIGATE IT LATER.
            IF (ACESOLV) THEN
               NUSE=20
            ELSE
               NUSE=NSTEPS
            ENDIF
            IF ((PATHSDSTEPS.GT.0).AND.(INR.LE.6)) NUSE=PATHSDSTEPS
            NOSHIFTSAVE=NOSHIFT; NOHESSSAVE=NOHESS
            NOSHIFT=.FALSE.; NOHESS=.FALSE.
            CALL EFOL(Q,MFLAG,NUSE,ENERGY,ITDONE,EVPLUS,PTEST,FRQSPLUS,NEWINR)
            NOSHIFT=NOSHIFTSAVE; NOHESS=NOHESSSAVE
            NSTEPPLUS=ITDONE
!
!  SWITCH TO LBFGS IF SD DID NOT FINISH.
!
            IF (.NOT.MFLAG) THEN
               IF (PTEST) PRINT '(A,I8,A)','EFOL> SWITCHING TO LBFGS MINIMISATION AFTER ',NUSE,' STEEPEST-DESCENT STEPS'
               KNOWE=.FALSE.
               KNOWG=.FALSE.
               IF (CHRMMT.AND.INTMINT) THEN
                  CALL MYLBFGS(NINTS,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                         .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
               ELSE
                  CALL MYLBFGS(NOPT,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                         .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
               ENDIF
               NSTEPPLUS=NSTEPPLUS+ITDONE
            ENDIF
         ENDIF
         ! }}}
      ELSE
         ! {{{
         CALL EFOL(Q,MFLAG,1,ENERGY,ITDONE,EVTS,PTEST,FRQSTS,0)
         ETS=ENERGY
         DO J1=1,NOPT
            STEP(J1)=Q(J1)-QINIT(J1)
         ENDDO
         KNOWE=.FALSE.
         KNOWG=.FALSE. ! WE DON`T KNOW THE GRADIENT AT THE POINT IN Q BECAUSE VNEW ISN`T PASSED FROM EFOL?
         IF (BFGSMINT) THEN
C           NOSHIFT=.FALSE.
            IF (CHRMMT.AND.INTMINT) THEN
               CALL MYLBFGS(NINTS,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                      .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
            ELSE
               CALL MYLBFGS(NOPT,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                      .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
            END IF

            NSTEPPLUS=ITDONE+1
         ELSE IF (BBRSDMT) THEN
            CALL BBRSDM(Q,MFLAG,ITDONE,ENERGY,RMS,.FALSE.,VNEW,PTEST)
            NSTEPPLUS=ITDONE+1
C
C DAE TO SWITCH TO BFGS AFTER NSTEPS SD
C
            IF (.NOT.MFLAG) THEN
               KNOWE=.FALSE.
               KNOWG=.FALSE.
               IF (CHRMMT.AND.INTMINT) THEN
                  CALL MYLBFGS(NINTS,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                         .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
               ELSE
                  CALL MYLBFGS(NOPT,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                         .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
               ENDIF
               NSTEPPLUS=NSTEPPLUS+ITDONE
            ENDIF
         ELSE IF (BSMIN.OR.RKMIN) THEN
C           NOSHIFT=.FALSE.
            NUSE=NSTEPS
            IF (PATHSDSTEPS.GT.0) NUSE=PATHSDSTEPS
            CALL ODESD(NUSE,Q,MFLAG,ITDONE,PTEST)
            NSTEPPLUS=ITDONE+1
C DAE TO SWITCH TO BFGS AFTER NSTEPS SD
            IF (.NOT.MFLAG) THEN
               KNOWE=.FALSE.
               KNOWG=.FALSE.
               IF (CHRMMT.AND.INTMINT) THEN
                  CALL MYLBFGS(NINTS,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                         .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
               ELSE
                  CALL MYLBFGS(NOPT,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                         .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
               ENDIF
               NSTEPPLUS=NSTEPPLUS+ITDONE
            ELSE
!
!  ODESD DOES NOT RETURN THE ENERGY!
!
               CALL POTENTIAL(Q,ENERGY,VNEW,.FALSE.,.FALSE.,RMS,.FALSE.,.FALSE.)
            ENDIF
C END DAE
         ELSE
            IF (INR.LT.6) THEN
               NEWINR=0 ! SO WE CAN USE PAGE-MCIVER
            ELSE
               NEWINR=INR
            ENDIF
            NUSE=NSTEPS
            IF ((PATHSDSTEPS.GT.0).AND.(INR.LE.6)) NUSE=PATHSDSTEPS
            NOSHIFTSAVE=NOSHIFT; NOHESSSAVE=NOHESS
            NOSHIFT=.FALSE.; NOHESS=.FALSE.
            CALL EFOL(Q,MFLAG,NUSE,ENERGY,ITDONE,EVPLUS,PTEST,FRQSPLUS,NEWINR)
            NOSHIFT=NOSHIFTSAVE; NOHESS=NOHESSSAVE
            NSTEPPLUS=ITDONE ! BUG FIX DJW 7/10/08
!
!  SWITCH TO LBFGS IF SD DID NOT FINISH.
!
            IF (.NOT.MFLAG) THEN
               IF (PTEST) PRINT '(A,I8,A)','EFOL> SWITCHING TO LBFGS MINIMISATION AFTER ',NUSE,' STEEPEST-DESCENT STEPS'
               KNOWE=.FALSE.
               KNOWG=.FALSE.
               IF (CHRMMT.AND.INTMINT) THEN
                  CALL MYLBFGS(NINTS,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                         .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
               ELSE
                  CALL MYLBFGS(NOPT,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                         .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
               ENDIF
               NSTEPPLUS=NSTEPPLUS+ITDONE
            ENDIF
         ENDIF
         ! }}}
      ENDIF
      CALL MYCPU_TIME(TIME,.FALSE.)
      IF (MFLAG) THEN
         ! {{{
         WRITE(*,'(A,I20,A,G20.10,2X,A,F11.2)') ' PLUS  SIDE OF PATH:    ',NSTEPPLUS,' STEPS. ENERGY=',ENERGY,' TIME=',TIME-TIME0
         CALL FLUSH(6,ISTAT)
         ! }}}
      ELSE
         ! {{{
         WRITE(*,'(A,I20,A)') ' PLUS  SIDE OF PATH FAILED TO CONVERGE IN ',NSTEPPLUS,' STEPS'
C        STOP
         PATHFAILT=.TRUE.
         BFGSTST=BFGSTSTSAVE
         IVEC=IVECSAVE
         IVEC2=IVEC2SAVE
C
C JMC NOTE THAT BEFORE THE PLUS-SIDE MINIMIZATION ABOVE, BFGSTST IS SET TO FALSE, SO IF WE`RE DOING A CONNECT RUN (AND BFGSTS
C WAS INITIALLY TRUE), THE NEXT TS SEARCH WILL MESS UP, CALLING EFOL NOT INTBFGSTS.  RESET TO BFGSTSTSAVE AND ALSO RESET IVEC
C AND IVEC2 HERE (AS AT THE END OF THIS SUBROUTINE).
C
         IF (ALLOCATED(Q1)) DEALLOCATE(Q1)
         IF (ALLOCATED(Q2)) DEALLOCATE(Q2)
         IF (ALLOCATED(QW)) DEALLOCATE(QW)
         IF (ALLOCATED(QFRAMEP)) DEALLOCATE(QFRAMEP)
         IF (ALLOCATED(QFRAMEM)) DEALLOCATE(QFRAMEM)
         ! }}}
         RETURN
      ENDIF

C CHECK HESSIAN INDEX  

      IF ((MFLAG.AND.CHECKINDEX).AND.(BFGSMINT.OR.BFGSTST.OR.BSMIN.OR.RKMIN)) THEN
C  {{{
         IF (NOHESS) THEN
            CALL CHECKIND2(Q,MFLAG,INEG,ENERGY)
C }}}
         ELSE
C  WE NEED THE HESSIAN IN CHECKIND. {{{
C
            IF (BFGSMINT.OR.BSMIN.OR.RKMIN) CALL POTENTIAL(Q,ENERGY,VNEW,.TRUE.,.TRUE.,RMS,.FALSE.,.FALSE.)
            CALL CHECKIND(Q,MFLAG,INEG,ENERGY,EVPLUS,EVALMAX,.FALSE.)
         ENDIF
C }}}
      ENDIF
C }}}
C  MINUS SIDE. {{{
C
      IVEC=-1
      IF (REDOPATH1) THEN
         REDOPATH1=.FALSE.
         REDOPATH2=.TRUE.
      ELSEIF (REDOPATH2) THEN
         REDOPATH1=.TRUE.
         REDOPATH2=.FALSE.
      ENDIF
      DO J1=1,NOPT
         QPLUS(J1)=Q(J1)
         IF (.NOT.UNRST) Q(J1)=QINIT(J1)-STEP(J1)
         IF (HYBRIDMINT) Q(J1)=QINIT(J1)
      ENDDO
      EPLUS=ENERGY
! }}}
!     IF (DEBUG) PRINT*,'TS STEP OFF MINUS POINTS IN PATH:'
!     IF (DEBUG) WRITE(*,'(3G20.10)') (Q(J1),J1=1,NOPT)

      IF (UNRST) THEN ! JMC NEW INTSTEP STUFF 
         ! {{{
         DO J1=1,NRES
            C(1,J1)=QINIT(6*(J1-1)+1)
            C(2,J1)=QINIT(6*(J1-1)+2)
            C(3,J1)=QINIT(6*(J1-1)+3)
            C(1,J1+NRES)=QINIT(6*(J1-1)+4)
            C(2,J1+NRES)=QINIT(6*(J1-1)+5)
            C(3,J1+NRES)=QINIT(6*(J1-1)+6)
         END DO
         CALL UPDATEDC
!CALL INT_FROM_CART(.TRUE.,.FALSE.)
!CALL GEOM_TO_VAR(NINTS,TSINT)
         NEWINT=TSINT-INTSTEP
!CALL VAR_TO_GEOM(NINTS,NEWINT)
!CALL CHAINBUILD
         DO J1=1,NRES
            Q(6*(J1-1)+1)=C(1,J1)
            Q(6*(J1-1)+2)=C(2,J1)
            Q(6*(J1-1)+3)=C(3,J1)
            Q(6*(J1-1)+4)=C(1,J1+NRES)
            Q(6*(J1-1)+5)=C(2,J1+NRES)
            Q(6*(J1-1)+6)=C(3,J1+NRES)
         END DO
         ! }}}
      ENDIF ! JMC END NEW STUFF

      KNOWE=.FALSE.
      KNOWG=.FALSE.

      CALL MYCPU_TIME(TIME0,.FALSE.)
      
      ! HYBRIDMINT BFGSMIT BBRSDMT BSMIN RKMIN;  ELSE
! {{{
      IF (HYBRIDMINT) THEN
        ! {{{
         POTCALL=.TRUE.
         ENERGY=ETS
         CALL HYBRIDMIN(HMNSTEPS,Q,ENERGY,VNEW,MFLAG,RMS,EVTS,EVALMAX,VECS,ITDONE,POTCALL,PTEST)
         NSTEPMINUS=ITDONE
         IF (.NOT.MFLAG) THEN
            IF (PTEST) PRINT '(A,I8,A)','EFOL> SWITCHING TO LBFGS MINIMISATION AFTER ',NSTEPMINUS,' HYBRID MINIMISATION STEPS'
            KNOWE=.FALSE.
            KNOWG=.FALSE.
            IF (CHRMMT.AND.INTMINT) THEN
               CALL MYLBFGS(NINTS,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                      .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
            ELSE
               CALL MYLBFGS(NOPT,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                      .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
            ENDIF
            NSTEPMINUS=NSTEPMINUS+ITDONE
         ENDIF
         ! }}}
      ELSE IF (BFGSMINT) THEN
         ! {{{
         IF (UNRST.OR.(CHRMMT.AND.INTMINT)) THEN
            CALL MYLBFGS(NINTS,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                   .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
         ELSE
            CALL MYLBFGS(NOPT,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                   .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
         ENDIF
         NSTEPMINUS=ITDONE+1
         ! }}}
      ELSE IF (BBRSDMT) THEN
         ! {{{
         CALL BBRSDM(Q,MFLAG,ITDONE,ENERGY,RMS,.FALSE.,VNEW,PTEST)
         NSTEPMINUS=ITDONE+1
C
C DAE TO SWITCH TO BFGS AFTER NSTEPS SD
C
         IF (.NOT.MFLAG) THEN
            KNOWE=.FALSE.
            KNOWG=.FALSE.
            IF (CHRMMT.AND.INTMINT) THEN
               CALL MYLBFGS(NINTS,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                      .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
            ELSE
               CALL MYLBFGS(NOPT,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                      .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
            ENDIF
            NSTEPMINUS=NSTEPMINUS+ITDONE
         ENDIF
         ! }}}
      ELSE IF (BSMIN.OR.RKMIN) THEN
         ! {{{
         NUSE=NSTEPS
         IF (PATHSDSTEPS.GT.0) NUSE=PATHSDSTEPS
         CALL ODESD(NUSE,Q,MFLAG,ITDONE,PTEST)
         NSTEPMINUS=ITDONE+1
C DAE TO SWITCH TO BFGS AFTER NSTEPS SD
         IF (.NOT.MFLAG) THEN
            KNOWE=.FALSE.
            KNOWG=.FALSE.
            IF (CHRMMT.AND.INTMINT) THEN
               CALL MYLBFGS(NINTS,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                      .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
            ELSE
               CALL MYLBFGS(NOPT,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                      .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
            ENDIF
            NSTEPMINUS=NSTEPMINUS+ITDONE
         ELSE
!
!  ODESD DOES NOT RETURN THE ENERGY!
!
            CALL POTENTIAL(Q,ENERGY,VNEW,.FALSE.,.FALSE.,RMS,.FALSE.,.FALSE.)
         ENDIF
C END DAE
         ! }}}
      ELSE
        ! {{{
         IF (INR.LT.6) THEN
            NEWINR=0 ! SO WE CAN USE PAGE-MCIVER
         ELSE
            NEWINR=INR
         ENDIF
C BS360 (29/07/08): ACE DOES NOT CONVERGE WITH SD. I WILL INVESTIGATE IT LATER.
         IF (ACESOLV) THEN
            NUSE=20
         ELSE
            NUSE=NSTEPS
         ENDIF
         IF ((PATHSDSTEPS.GT.0).AND.(INR.LE.6)) NUSE=PATHSDSTEPS
         NOSHIFTSAVE=NOSHIFT; NOHESSSAVE=NOHESS
         NOSHIFT=.FALSE.; NOHESS=.FALSE.
         CALL EFOL(Q,MFLAG,NUSE,ENERGY,ITDONE,EVMINUS,PTEST,FRQSMINUS,NEWINR)
         NOSHIFT=NOSHIFTSAVE; NOHESS=NOHESSSAVE
         NSTEPMINUS=ITDONE
!
!  SWITCH TO LBFGS IF SD DID NOT FINISH.
!
         IF (.NOT.MFLAG) THEN
            IF (PTEST) PRINT '(A,I8,A)','EFOL> SWITCHING TO LBFGS MINIMISATION AFTER ',NUSE,' STEEPEST-DESCENT STEPS'
            KNOWE=.FALSE.
            KNOWG=.FALSE.
            IF (CHRMMT.AND.INTMINT) THEN
               CALL MYLBFGS(NINTS,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                      .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
            ELSE
               CALL MYLBFGS(NOPT,MUPDATE,Q,.FALSE.,MFLAG,ENERGY,RMS2,EREAL,RMS,BFGSSTEPS,
     1                      .TRUE.,ITDONE,PTEST,VNEW,.FALSE.,.FALSE.)
            ENDIF
            NSTEPMINUS=NSTEPMINUS+ITDONE
         ENDIF
         ! }}}
      ENDIF
      ! }}}

      CALL MYCPU_TIME(TIME,.FALSE.)

      ! WRITE INFO ABOUT MINUS SIDE OF ENERGY {{{
      IF (MFLAG) THEN
        ! {{{
         WRITE(*,'(A,I20,A,G20.10,2X,A,F11.2)') ' MINUS SIDE OF PATH:    ',NSTEPMINUS,' STEPS. ENERGY=',ENERGY,' TIME=',TIME-TIME0
         CALL FLUSH(6,ISTAT)
         ! }}}
      ELSE
        ! {{{
         WRITE(*,'(A,I20,A)') ' MINUS SIDE OF PATH FAILED TO CONVERGE IN ',NSTEPMINUS,' STEPS'
C        STOP
         PATHFAILT=.TRUE.
         BFGSTST=BFGSTSTSAVE
         IVEC=IVECSAVE
         IVEC2=IVEC2SAVE
C JMC NOTE THAT BEFORE THE PLUS-SIDE MINIMIZATION ABOVE, BFGSTST IS SET TO FALSE, SO IF WE`RE DOING A CONNECT RUN (AND BFGSTS 
C WAS INITIALLY TRUE), THE NEXT TS SEARCH WILL MESS UP, CALLING EFOL NOT INTBFGSTS.  RESET TO BFGSTSTSAVE AND ALSO RESET IVEC
C AND IVEC2 HERE (AS AT THE END OF THIS SUBROUTINE).
         IF (ALLOCATED(Q1)) DEALLOCATE(Q1)
         IF (ALLOCATED(Q2)) DEALLOCATE(Q2)
         IF (ALLOCATED(QW)) DEALLOCATE(QW)
         IF (ALLOCATED(QFRAMEP)) DEALLOCATE(QFRAMEP)
         IF (ALLOCATED(QFRAMEM)) DEALLOCATE(QFRAMEM)
         ! }}}
         RETURN
      ENDIF

      ! }}}

      DO J1=1,NOPT
         QMINUS(J1)=Q(J1)
      ENDDO
      EMINUS=ENERGY
C
C  CHECK HESSIAN INDEX {{{
C
      IF ((MFLAG.AND.CHECKINDEX).AND.(BFGSMINT.OR.BFGSTST.OR.BSMIN.OR.RKMIN)) THEN
         IF (NOHESS) THEN
            CALL CHECKIND2(Q,MFLAG,INEG,ENERGY)
         ELSE
C }}}
C  WE NEED THE HESSIAN IN CHECKIND. {{{
C
            IF (BFGSMINT.OR.BSMIN.OR.RKMIN) CALL POTENTIAL(Q,ENERGY,VNEW,.TRUE.,.TRUE.,RMS,.FALSE.,.FALSE.)
            CALL CHECKIND(Q,MFLAG,INEG,ENERGY,EVMINUS,EVALMAX,.FALSE.)
         ENDIF
      ENDIF
C }}}
C  THE TOTAL NUMBER OF ENERGIES AND COORDINATES IS NSTEPPLUS + NSTEPMINUS + 1 FOR THE TRANSITION STATE.
C  THE REST OF THIS SUBROUTINE IS POST-PROCESSING {{{
C  MINIMISE IO IF PRINTPTS IS .FALSE.
C
      IF (ZSYMSAVE(1:1).EQ.'W') THEN  !  WCOMMENT
         ALLOCATE(QFRAMEP(9*(NATOMS/2),NFMAX),QFRAMEM(9*(NATOMS/2),NFMAX))
      ELSE
         ALLOCATE(QFRAMEP(3*NATOMS,NFMAX),QFRAMEM(3*NATOMS,NFMAX))
      ENDIF
      IF (.NOT.PRINTPTS) THEN 
         ! {{{
         NSTEPPLUS=1
         NSTEPMINUS=1
         NFPLUS=1
         NFMINUS=1
         EOFS(1)=EPLUS
         EOFS(2)=ETS
         EOFS(3)=EMINUS
         EOFSFRAMEP(1)=EPLUS
         EOFSFRAMEM(1)=EMINUS
         PATHLENGTH(1)=0.0D0
         DUMMY=0.0D0
C        PRINT*,'WARNING - S,N,GAMMA ARE NOT CALCULATED FROM CARTESIAN COORDINATES HERE'
         DO J2=1,NOPT
            DUMMY=DUMMY+(QINIT(J2)-QPLUS(J2))**2
         ENDDO
         PATHLENGTH(2)=SQRT(DUMMY)
         DUMMY=0.0D0
         DO J2=1,NOPT
            DUMMY=DUMMY+(QINIT(J2)-QMINUS(J2))**2
         ENDDO
         PATHLENGTH(3)=SQRT(DUMMY)+PATHLENGTH(2)
         DO J2=1,NOPT
            QFRAMEP(J2,1)=QPLUS(J2)
            QFRAMEM(J2,1)=QMINUS(J2)
         ENDDO
         GOTO 555
         ! }}}
      ENDIF

      REWIND(1)
      REWIND(2)
      READ(2,*) EOFS(NSTEPPLUS+1)
      IF (ZSYMSAVE(1:1).EQ.'W') THEN  !  WCOMMENT
         ALLOCATE(Q1(9*(NATOMS/2)),Q2(9*(NATOMS/2)),QW(9*(NATOMS/2)))
C        READ(1,*) (Q1(J1),J1=1,9*NATOMS)
         READ(1,*) (Q1(J1),J1=1,9*(NATOMS/2))
      ELSE
         ALLOCATE(Q1(3*NATOMS),Q2(3*NATOMS))
         READ(1,*) (Q1(J1),J1=1,NOPT)
      ENDIF
      PATHLENGTH(NSTEPPLUS+1)=0.0D0
C     
C  THE NUMBER OF FRAMES FOR EACH SIDE OF THE PATH, NPATHFRAME, IS NOW TREATED 
C  IN AN AVERAGE WAY. WE MUST DUMP THE THREE STATIONARY POINTS AT THE VERY LEAST,
C  AND OTHER FRAMES ON THE TWO PATHS ARE THEN DUMPED WITH A PROBABILITY PROPORTIONAL
C  TO NPATHFRAME. IF NPATHFRAME IS > NFMAX THEN USE NFMAX IN ITS PLACE, OTHERWISE
C  WE DON;T HAVE ENOUGH STORAGE DECLARED FOR THE FRAMES.
C
C  THE NEW VARIABLE FRAMEDIST CAN BE USED TO EXCLUDE FRAMES WITH CONFIGURATIONS THAT
C  ARE SEPARATED BY LESS THAN FRAMEDIST DISTANCE UNITS.
C
!     PPLUS=MIN(MIN(MIN(NPATHFRAME,NSTEPPLUS),NFMAX)*1.0D0/(1.0D0*(NSTEPPLUS-1)),1.0D0)
!     PMINUS=MIN(MIN(MIN(NPATHFRAME,NSTEPMINUS),NFMAX)*1.0D0/(1.0D0*(NSTEPMINUS-1)),1.0D0)

      IF (NSTEPPLUS.LT.NPATHFRAME .OR. NSTEPPLUS.EQ.1) THEN
         PPLUS = 1.0D0
      ELSE
         PPLUS = MIN(MIN(NPATHFRAME,NFMAX)*1.0D0/(1.0D0*(NSTEPPLUS-1)),1.0D0)
      ENDIF

      IF (NSTEPMINUS.LT.NPATHFRAME .OR. NSTEPMINUS.EQ.1) THEN
         PMINUS = 1.0D0
      ELSE
         PMINUS=MIN(MIN(NPATHFRAME,NFMAX)*1.0D0/(1.0D0*(NSTEPMINUS-1)),1.0D0)
      ENDIF

      IF (PTEST) WRITE(*,'(A,F10.4,A,F10.4,A)') ' FRAMES WILL BE DUMPED TO POINTS.PATH.XYZ WITH PROBABILITY ',
     1                          PPLUS,'/',PMINUS,' STEPS ON THE PLUS/MINUS SIDES'
      NFPLUS=0
      DO J1=1,NSTEPPLUS
         ! {{{
         READ(2,*) EOFS(NSTEPPLUS+1-J1)
         IF (ZSYMSAVE(1:1).EQ.'W') THEN  
C           READ(1,*) (Q2(J2),J2=1,9*NATOMS)  !  WCOMMENT
            READ(1,*) (Q2(J2),J2=1,9*(NATOMS/2))
         ELSE
            READ(1,*) (Q2(J2),J2=1,NOPT)
         ENDIF

         ETEST=.FALSE.
         IF ((J1.EQ.1).OR.(J1.EQ.NSTEPPLUS)) THEN ! ALWAYS TAKE THE END POINTS
            ETEST=.TRUE.
         ELSE
            IF (ABS(EOFS(NSTEPPLUS+1-J1)-LASTE).GE.FRAMEEDIFF) ETEST=.TRUE. ! ENERGY MUST HAVE CHANGED ENOUGH
         ENDIF
         IF (ETEST) LASTE=EOFS(NSTEPPLUS+1-J1)
         IF (((DPRAND().LE.PPLUS).OR.(J1.EQ.NSTEPPLUS)).AND.(NFPLUS.LT.NFMAX).AND.ETEST) THEN
            IF ((J1.EQ.NSTEPPLUS).OR.(NFPLUS.LT.NFMAX-1)) THEN ! SAVE ROOM FOR THE LAST ENDPOINT
               NFPLUS=NFPLUS+1
               EOFSFRAMEP(NFPLUS)=EOFS(NSTEPPLUS+1-J1)
               LASTE=EOFS(NSTEPPLUS+1-J1)
               IF (ZSYMSAVE(1:1).EQ.'W') THEN
C                 DO J2=1,9*NATOMS  !  WCOMMENT
                  DO J2=1,9*(NATOMS/2)
                     QFRAMEP(J2,NFPLUS)=Q2(J2)
                  ENDDO
               ELSE IF (ZSYMSAVE(1:2).EQ.'CD') THEN
                   DO J2=1,NATOMS/2
                      CALL CAPSIDIO(Q2(3*(J2-1)+1),Q2(3*(J2-1)+2),Q2(3*(J2-1)+3),
     1                              Q2(3*(NATOMS/2+J2-1)+1),Q2(3*(NATOMS/2+J2-1)+2),Q2(3*(NATOMS/2+J2-1)+3),
     2                              CAPSCOORDS2,RAD,HEIGHT)
                      DO J3=1,18
                         QFRAMEP(18*(J2-1)+J3,NFPLUS)=CAPSCOORDS2(J3)
                      ENDDO
                  ENDDO
               ELSE
                  DO J2=1,NOPT
                     QFRAMEP(J2,NFPLUS)=Q2(J2)
                  ENDDO
               ENDIF
!              PRINT '(A,I6,A,I6,A,G20.10)','DUMPING PLUS FRAME ',J1,' NFPLUS=',NFPLUS,' ENERGY=',EOFSFRAMEP(NFPLUS)
            ENDIF
         ENDIF
         TEMP=0.0D0
         IF (BULKT) THEN
            DO J2=1,NATOMS
               TEMP=TEMP+MINIM(Q2(3*(J2-1)+1),Q1(3*(J2-1)+1),PARAM1)**2
     1                  +MINIM(Q2(3*(J2-1)+2),Q1(3*(J2-1)+2),PARAM2)**2
               IF (.NOT.TWOD) TEMP=TEMP+MINIM(Q2(3*(J2-1)+3),Q1(3*(J2-1)+3),PARAM3)**2
            ENDDO
         ELSE
            IF (ZSYMSAVE(1:1).EQ.'W') THEN
C              DO J2=1,9*NATOMS  !  WCOMMENT
               DO J2=1,9*(NATOMS/2)
                  TEMP=TEMP+(Q2(J2)-Q1(J2))**2
               ENDDO
            ELSE IF (ZSYMSAVE.EQ.'CD') THEN
               DO J2=1,NATOMS/2
                  CALL CAPSIDIO(Q2(3*(J2-1)+1),Q2(3*(J2-1)+2),Q2(3*(J2-1)+3),
     1                          Q2(3*(NATOMS/2+J2-1)+1),Q2(3*(NATOMS/2+J2-1)+2),Q2(3*(NATOMS/2+J2-1)+3),
     2                          CAPSCOORDS2,RAD,HEIGHT)
                  CALL CAPSIDIO(Q1(3*(J2-1)+1),Q1(3*(J2-1)+2),Q1(3*(J2-1)+3),
     1                          Q1(3*(NATOMS/2+J2-1)+1),Q1(3*(NATOMS/2+J2-1)+2),Q1(3*(NATOMS/2+J2-1)+3),
     2                          CAPSCOORDS1,RAD,HEIGHT)
                  DO J3=1,18
                      TEMP=TEMP+(CAPSCOORDS1(J3)-CAPSCOORDS2(J3))**2
                  ENDDO
               ENDDO
            ELSE IF((PYGPERIODICT.OR.PYBINARYT).AND.UNIAXT) THEN
C           CALCULATE PATH LENGTHS WRT. CARTESIAN COORDINATE OF THE CENTRE AND TWO COORDINATES ALONG THE SYMMETRY AXIS ONLY
               CALL UNIAXGETPATHLENGTH(Q1,Q2,TEMP)
            ELSE
               DO J2=1,NOPT
                  TEMP=TEMP+(Q2(J2)-Q1(J2))**2
               ENDDO
            ENDIF
         ENDIF
         PATHLENGTH(NSTEPPLUS+1-J1)=PATHLENGTH(NSTEPPLUS+2-J1)-SQRT(TEMP)
         IF (ZSYMSAVE(1:1).EQ.'W') THEN
C           DO J2=1,9*NATOMS  !  WCOMMENT
            DO J2=1,9*(NATOMS/2)
               Q1(J2)=Q2(J2)
            ENDDO
         ELSE
            DO J2=1,NOPT
               Q1(J2)=Q2(J2)
            ENDDO
         ENDIF
         ! }}}
      ENDDO
      IF (PTEST) WRITE(*,'(A,I6,A,I6,A)') ' TRANSITION STATE WILL BE FRAME NUMBER ',NFPLUS+1

      IF (ZSYMSAVE(1:1).EQ.'W') THEN
         ! {{{
C        DO J1=1,NATOMS  !  WCOMMENT
         DO J1=1,NATOMS/2
            CALL CONVERT(QINIT(3*(J1-1)+1),QINIT(3*(J1-1)+2),QINIT(3*(J1-1)+3),
C    1                   QINIT(3*(NATOMS+J1-1)+1),QINIT(3*(NATOMS+J1-1)+2),QINIT(3*(NATOMS+J1-1)+3),
     1                   QINIT(3*(NATOMS/2+J1-1)+1),QINIT(3*(NATOMS/2+J1-1)+2),QINIT(3*(NATOMS/2+J1-1)+3),
     2                   OVEC,H1VEC,H2VEC)
            Q1(9*(J1-1)+1)=OVEC(1)
            Q1(9*(J1-1)+2)=OVEC(2)
            Q1(9*(J1-1)+3)=OVEC(3)
            Q1(9*(J1-1)+4)=H1VEC(1)
            Q1(9*(J1-1)+5)=H1VEC(2)
            Q1(9*(J1-1)+6)=H1VEC(3)
            Q1(9*(J1-1)+7)=H2VEC(1)
            Q1(9*(J1-1)+8)=H2VEC(2)
            Q1(9*(J1-1)+9)=H2VEC(3)
         ENDDO
         ! }}}
      ELSE
         ! {{{
         DO J1=1,NOPT
            Q1(J1)=QINIT(J1)
         ENDDO
         ! }}}
      ENDIF

      NFMINUS=0
      DO J1=1,NSTEPMINUS
      ! {{{
         READ(2,*) EOFS(NSTEPPLUS+1+J1)
         IF (ZSYMSAVE(1:1).EQ.'W') THEN
C           READ(1,*) (Q2(J2),J2=1,9*NATOMS)  !  WCOMMENT
            READ(1,*) (Q2(J2),J2=1,9*(NATOMS/2))
         ELSE
            READ(1,*) (Q2(J2),J2=1,NOPT)
         ENDIF

         ETEST=.FALSE.
         IF ((J1.EQ.1).OR.(J1.EQ.NSTEPMINUS)) THEN ! ALWAYS TAKE THE END POINTS
            ETEST=.TRUE.
         ELSE
            IF (ABS(EOFS(NSTEPPLUS+1+J1)-LASTE).GE.FRAMEEDIFF) ETEST=.TRUE. ! ENERGY MUST HAVE CHANGED ENOUGH
         ENDIF
         IF (ETEST) LASTE=EOFS(NSTEPPLUS+1+J1)
         RANDOM=DPRAND()
         IF (((RANDOM.LE.PMINUS).OR.(J1.EQ.NSTEPMINUS)).AND.(NFMINUS.LE.NFMAX).AND.ETEST) THEN
            IF ((J1.EQ.NSTEPMINUS).OR.(NFMINUS.LT.NFMAX-1)) THEN ! SAVE A SPACE FOR THE STATIONARY POINT AT THE END
               NFMINUS=NFMINUS+1
               EOFSFRAMEM(NFMINUS)=EOFS(NSTEPPLUS+1+J1)
               LASTE=EOFS(NSTEPPLUS+1+J1)
               IF (ZSYMSAVE(1:1).EQ.'W') THEN
C                 DO J2=1,9*NATOMS  !  WCOMMENT
                     DO J2=1,9*(NATOMS/2)
                     QFRAMEM(J2,NFMINUS)=Q2(J2)
                  ENDDO
               ELSE IF (ZSYMSAVE.EQ.'CD') THEN
                   DO J2=1,NATOMS/2
                      CALL CAPSIDIO(Q2(3*(J2-1)+1),Q2(3*(J2-1)+2),Q2(3*(J2-1)+3),
     1                              Q2(3*(NATOMS/2+J2-1)+1),Q2(3*(NATOMS/2+J2-1)+2),Q2(3*(NATOMS/2+J2-1)+3),
     2                              CAPSCOORDS2,RAD,HEIGHT)
                      DO J3=1,18
                         QFRAMEM(18*(J2-1)+J3,NFMINUS)=CAPSCOORDS2(J3)
                      ENDDO
                  ENDDO
               ELSE
                  DO J2=1,NOPT
                     QFRAMEM(J2,NFMINUS)=Q2(J2)
                  ENDDO
               ENDIF
!              PRINT '(A,I6,A,I6,A,G20.10)','DUMPING MINUS FRAME ',J1,' NFMINUS=',NFMINUS,' ENERGY=',EOFSFRAMEM(NFMINUS)

            ENDIF
         ENDIF
         TEMP=0.0D0
         IF (BULKT) THEN
            DO J2=1,NATOMS
               TEMP=TEMP+MINIM(Q2(3*(J2-1)+1),Q1(3*(J2-1)+1),PARAM1)**2
     1                  +MINIM(Q2(3*(J2-1)+2),Q1(3*(J2-1)+2),PARAM2)**2
               IF (.NOT.TWOD) TEMP=TEMP+MINIM(Q2(3*(J2-1)+3),Q1(3*(J2-1)+3),PARAM3)**2
            ENDDO
         ELSE
            IF (ZSYMSAVE(1:1).EQ.'W') THEN
C              DO J2=1,9*NATOMS  !  WCOMMENT
               DO J2=1,9*(NATOMS/2)
                  TEMP=TEMP+(Q2(J2)-Q1(J2))**2
               ENDDO
            ELSE IF (ZSYMSAVE.EQ.'CD') THEN
               DO J2=1,NATOMS/2
                  CALL CAPSIDIO(Q2(3*(J2-1)+1),Q2(3*(J2-1)+2),Q2(3*(J2-1)+3),
     1                          Q2(3*(NATOMS/2+J2-1)+1),Q2(3*(NATOMS/2+J2-1)+2),Q2(3*(NATOMS/2+J2-1)+3),
     2                          CAPSCOORDS2,RAD,HEIGHT)
                  CALL CAPSIDIO(Q1(3*(J2-1)+1),Q1(3*(J2-1)+2),Q1(3*(J2-1)+3),
     1                          Q1(3*(NATOMS/2+J2-1)+1),Q1(3*(NATOMS/2+J2-1)+2),Q1(3*(NATOMS/2+J2-1)+3),
     2                          CAPSCOORDS1,RAD,HEIGHT)
                  DO J3=1,18
                      TEMP=TEMP+(CAPSCOORDS1(J3)-CAPSCOORDS2(J3))**2
                  ENDDO
               ENDDO
            ELSE IF((PYGPERIODICT.OR.PYBINARYT).AND.UNIAXT) THEN
C           CALCULATE PATH LENGTHS WRT. CARTESIAN COORDINATE OF THE CENTRE AND TWO COORDINATES ALONG THE SYMMETRY AXIS ONLY
               CALL UNIAXGETPATHLENGTH(Q1,Q2,TEMP)
            ELSE
               DO J2=1,NOPT
                  TEMP=TEMP+(Q2(J2)-Q1(J2))**2
               ENDDO
            ENDIF
         ENDIF
         PATHLENGTH(NSTEPPLUS+1+J1)=PATHLENGTH(NSTEPPLUS+J1)+SQRT(TEMP)
         IF (ZSYMSAVE(1:1).EQ.'W') THEN
C           DO J2=1,9*NATOMS  !  WCOMMENT
            DO J2=1,9*(NATOMS/2)
               Q1(J2)=Q2(J2)
            ENDDO
         ELSE
            DO J2=1,NOPT
               Q1(J2)=Q2(J2)
            ENDDO
         ENDIF
         ! }}}
      ENDDO

555   CONTINUE
      OPEN(UNIT=3,FILE=EOFSSTRING,STATUS='UNKNOWN')
      WRITE(3,'(2G20.10,I6)') (PATHLENGTH(J1),EOFS(J1),J1,J1=1,NSTEPPLUS+NSTEPMINUS+1)
      CLOSE(3)
      
      SUM2=0.0D0
      SUM4=0.0D0
C     NDUMMY=1 !  WCOMMENT
C     IF (ZSYMSAVE(1:1).EQ.'W') NDUMMY=9  !  WCOMMENT 9 SHOULD HAVE BEEN 3?
      NATOMSIMUL=NATOMS
      IF (ZSYMSAVE(1:1).EQ.'W') NATOMSIMUL=3*(NATOMS/2)
      IF (ZSYMSAVE(1:1).EQ.'W') THEN
        ! {{{
         DO J1=1,NATOMSIMUL  !  WCOMMENT
            SUM2=SUM2+
     1           (QFRAMEP(3*(J1-1)+1,NFPLUS)-QFRAMEM(3*(J1-1)+1,NFMINUS))**2
     2          +(QFRAMEP(3*(J1-1)+2,NFPLUS)-QFRAMEM(3*(J1-1)+2,NFMINUS))**2
     3          +(QFRAMEP(3*(J1-1)+3,NFPLUS)-QFRAMEM(3*(J1-1)+3,NFMINUS))**2
            SUM4=SUM4+
     1          ((QFRAMEP(3*(J1-1)+1,NFPLUS)-QFRAMEM(3*(J1-1)+1,NFMINUS))**2
     2          +(QFRAMEP(3*(J1-1)+2,NFPLUS)-QFRAMEM(3*(J1-1)+2,NFMINUS))**2
     3          +(QFRAMEP(3*(J1-1)+3,NFPLUS)-QFRAMEM(3*(J1-1)+3,NFMINUS))**2)**2
         ENDDO
         ! }}}
      ELSE IF (BULKT) THEN
        ! {{{
         IF (TWOD) THEN
            DO J1=1,NATOMSIMUL  !  WCOMMENT
               SUM2=SUM2+
     1              MINIM(QPLUS(3*(J1-1)+1),Q(3*(J1-1)+1),PARAM1)**2
     2             +MINIM(QPLUS(3*(J1-1)+2),Q(3*(J1-1)+2),PARAM2)**2
               SUM4=SUM4+
     1             (MINIM(QPLUS(3*(J1-1)+1),Q(3*(J1-1)+1),PARAM1)**2
     2             +MINIM(QPLUS(3*(J1-1)+2),Q(3*(J1-1)+2),PARAM2)**2)**2
            ENDDO
         ELSE
C           DO J1=1,NATOMS*NDUMMY
            DO J1=1,NATOMSIMUL  !  WCOMMENT
               SUM2=SUM2+
     1              MINIM(QPLUS(3*(J1-1)+1),Q(3*(J1-1)+1),PARAM1)**2
     2             +MINIM(QPLUS(3*(J1-1)+2),Q(3*(J1-1)+2),PARAM2)**2
     3             +MINIM(QPLUS(3*(J1-1)+3),Q(3*(J1-1)+3),PARAM3)**2
               SUM4=SUM4+
     1             (MINIM(QPLUS(3*(J1-1)+1),Q(3*(J1-1)+1),PARAM1)**2
     2             +MINIM(QPLUS(3*(J1-1)+2),Q(3*(J1-1)+2),PARAM2)**2
     3             +MINIM(QPLUS(3*(J1-1)+3),Q(3*(J1-1)+3),PARAM3)**2)**2
            ENDDO
         ENDIF
         ! }}}
      ELSE IF (ZSYMSAVE.EQ.'CD') THEN
        ! {{{
         DO J2=1,NATOMS/2
            CALL CAPSIDIO(QPLUS(3*(J2-1)+1),QPLUS(3*(J2-1)+2),QPLUS(3*(J2-1)+3),
     1                    QPLUS(3*(NATOMS/2+J2-1)+1),QPLUS(3*(NATOMS/2+J2-1)+2),QPLUS(3*(NATOMS/2+J2-1)+3),
     2                    CAPSCOORDS2,RAD,HEIGHT)
            CALL CAPSIDIO(Q(3*(J2-1)+1),Q(3*(J2-1)+2),Q(3*(J2-1)+3),
     1                    Q(3*(NATOMS/2+J2-1)+1),Q(3*(NATOMS/2+J2-1)+2),Q(3*(NATOMS/2+J2-1)+3),
     2                    CAPSCOORDS1,RAD,HEIGHT)
            DO J1=1,18
               SUM2=SUM2+
     1              (CAPSCOORDS1(3*(J1-1)+1)-CAPSCOORDS2(3*(J1-1)+1))**2
     2             +(CAPSCOORDS1(3*(J1-1)+2)-CAPSCOORDS2(3*(J1-1)+2))**2
     3             +(CAPSCOORDS1(3*(J1-1)+3)-CAPSCOORDS2(3*(J1-1)+3))**2
               SUM4=SUM4+
     1             ((CAPSCOORDS1(3*(J1-1)+1)-CAPSCOORDS2(3*(J1-1)+1))**2
     2             +(CAPSCOORDS1(3*(J1-1)+2)-CAPSCOORDS2(3*(J1-1)+2))**2
     3             +(CAPSCOORDS1(3*(J1-1)+3)-CAPSCOORDS2(3*(J1-1)+3))**2)**2
            ENDDO
         ENDDO
         ! }}}
      ELSEIF (RINGPOLYMERT) THEN
      ! {{{
         SUM2=1.0D0
         SUM4=1.0D0
         ! }}}
      ELSE
        ! {{{
C        DO J1=1,NATOMS*NDUMMY  !  WCOMMENT
         DO J1=1,NATOMSIMUL
            SUM2=SUM2+
     1           (QPLUS(3*(J1-1)+1)-Q(3*(J1-1)+1))**2
     2          +(QPLUS(3*(J1-1)+2)-Q(3*(J1-1)+2))**2
     3          +(QPLUS(3*(J1-1)+3)-Q(3*(J1-1)+3))**2
            SUM4=SUM4+
     1          ((QPLUS(3*(J1-1)+1)-Q(3*(J1-1)+1))**2
     2          +(QPLUS(3*(J1-1)+2)-Q(3*(J1-1)+2))**2
     3          +(QPLUS(3*(J1-1)+3)-Q(3*(J1-1)+3))**2)**2
         ENDDO
         ! }}}
      ENDIF

      ETS=EOFS(NSTEPPLUS+1)
      EPLUS=EOFS(1)
      EMINUS=EOFS(NSTEPPLUS+NSTEPMINUS+1)
      PRINT*

      IF (RINGPOLYMERT) THEN
        ! {{{
         WRITE(*,'(A)')
     1'         E+        ETS - E+           ETS       ETS - E-           E-'
         WRITE(*,60) EPLUS,ETS-EPLUS,ETS,ETS-EMINUS,EMINUS
      ELSE
         WRITE(*,'(A)')
     1'         E+        ETS - E+           ETS       ETS - E-           E-          S       D' //
     2 '      GAMMA   ~N'
         WRITE(*,60) EPLUS,ETS-EPLUS,ETS,ETS-EMINUS,EMINUS,
     1         PATHLENGTH(NSTEPPLUS+NSTEPMINUS+1)-PATHLENGTH(1),SQRT(SUM2),SUM4*NATOMSIMUL/SUM2**2,SUM2**2/SUM4
60       FORMAT(F17.7,G12.5,F17.7,G12.5,F17.7,F8.3,F8.3,F8.3,F8.3)
         ! }}}
      ENDIF
C
C TVB CALCULATION OF CATASTROPHE RATIOS
      IF (RATIOS) THEN
            ! {{{
            CALL POTENTIAL(QPLUS,EPLUS,VNEW,.TRUE.,.TRUE.,RMS,.FALSE.,.FALSE.)
            CALL DSYEV('V','U',NOPT,HESS,SIZE(HESS,1),DIAG,TEMPA,9*NATOMS,INFO) 
            CALL EIGENSORT_VAL_ASC(DIAG,HESS,NOPT,3*NATOMS)
            LAMBDAP=DIAG(3*NATOMS-6)
            CALL POTENTIAL(QMINUS,EMINUS,VNEW,.TRUE.,.TRUE.,RMS,.FALSE.,.FALSE.)
            CALL DSYEV('N','U',NOPT,HESS,SIZE(HESS,1),DIAG,TEMPA,9*NATOMS,INFO) 
            CALL EIGENSORT_VAL_ASC(DIAG,HESS,NOPT,3*NATOMS)
            LAMBDAM=DIAG(3*NATOMS-6)
            CALL POTENTIAL(QINIT,EOFS(NSTEPPLUS+1),VNEW,.TRUE.,.TRUE.,RMS,.FALSE.,.FALSE.)
            CALL DSYEV('N','U',NOPT,HESS,SIZE(HESS,1),DIAG,TEMPA,9*NATOMS,INFO) 
            CALL EIGENSORT_VAL_ASC(DIAG,HESS,NOPT,3*NATOMS)
            LAMBDATS=DIAG(3*NATOMS)
            CALL NEWMINDIST(QPLUS,QINIT,NATOMS,DISTP,.FALSE.,.FALSE.,ZSYMSAVE,.FALSE.,RIGIDBODY,DEBUG,RMAT)
            CALL NEWMINDIST(QMINUS,QINIT,NATOMS,DISTM,.FALSE.,.FALSE.,ZSYMSAVE,.FALSE.,RIGIDBODY,DEBUG,RMAT)
            OPEN(UNIT=24,FILE='FOLDDATA',STATUS='UNKNOWN')
C           FOLDDATA: EM1, EM2, ETS, SM1, SM2, EVTS, EV1, EV2, SM1MIN, SM2MIN
            WRITE(24,'(10F13.7)') EOFS(1), EOFS(NSTEPPLUS+NSTEPMINUS+1), EOFS(NSTEPPLUS+1), PATHLENGTH(1),
     1      PATHLENGTH(NSTEPPLUS+NSTEPMINUS+1), LAMBDATS, LAMBDAP, LAMBDAM, DISTP, DISTM
            ! }}}
      ENDIF
C END TVB
C
      SLENGTH=PATHLENGTH(NSTEPPLUS+NSTEPMINUS+1)-PATHLENGTH(1)
      DISP=SQRT(SUM2)
C     GAMMA=SUM4*NDUMMY*NATOMS/SUM2**2  !  WCOMMENT
      GAMMA=SUM4*NATOMSIMUL/SUM2**2
      NTILDE=SUM2**2/SUM4
      IF (CHECKINDEX) THEN
        ! {{{
         SMINUS=PATHLENGTH(NSTEPPLUS+NSTEPMINUS+1)
         SPLUS=PATHLENGTH(1)
         STS=PATHLENGTH(NSTEPPLUS+1)
         IF (EPLUS.LT.EMINUS) THEN
            ETEMP=EPLUS
            STEMP=SPLUS
            DUMMY=EVPLUS
            EPLUS=EMINUS
            SPLUS=SMINUS
            EVPLUS=EVMINUS
            EMINUS=ETEMP
            SMINUS=STEMP
            EVMINUS=DUMMY
         ENDIF
         PRINT*
         WRITE(*,'(A)')
     1      '         EVTS         EVPLUS/TS    EVMINUS/TS  DEL E PLUS      DEL E MINUS      S PLUS         S MINUS          FRAT +'
     2        // '    FRAT -  '

         WRITE(*,'(A5,3F13.7,4G16.8,2F10.4)') 'FOLD ',EVTS,EVPLUS/ABS(EVTS),EVMINUS/ABS(EVTS),ETS-EPLUS,ETS-EMINUS,ABS(STS-SPLUS),
     1              ABS(SMINUS-STS),6*(ETS-EPLUS)/(ABS(EVTS)*(STS-SPLUS)**2),6*(ETS-EMINUS)/(ABS(EVTS)*(STS-SMINUS)**2)

         WRITE(*,'(A)') '        DEL E PLUS      DEL E MINUS     S PLUS           S MINUS       '
     1        // '   EVRAT     DEV1      DEV2      DEV3      RAT+      RAT-'

         WRITE(*,'(A5,4G16.8,6F10.4)') 'CUSP ',ETS-EPLUS,ETS-EMINUS,ABS(STS-SPLUS),ABS(SMINUS-STS),
     1                           EVPLUS*EVMINUS/((EVPLUS+EVMINUS)*EVTS),
     2                           (ETS-EPLUS)*EVMINUS**3*(EVMINUS+2.0D0*EVPLUS)/((ETS-EMINUS)*EVPLUS**3*(EVPLUS+2.0D0*EVMINUS)),
     3                           (ETS-EPLUS)*EVTS**3*(EVTS+2.0D0*EVPLUS)/((ETS-EMINUS)*(EVTS-EVPLUS)*(EVPLUS+EVTS)**3),
     4                           (ETS-EPLUS)*(EVTS-EVMINUS)*(EVMINUS+EVTS)**3/((ETS-EMINUS)*EVTS**3*(2.0D0*EVMINUS+EVTS)),
     5                           12*(ETS-EPLUS) /((EVPLUS -EVTS)*(STS-SPLUS )**2),
     6                           12*(ETS-EMINUS)/((EVMINUS-EVTS)*(STS-SMINUS)**2)
         ! }}}
      ENDIF

      OPEN(UNIT=3,FILE=ITSTRING,STATUS='UNKNOWN')

      ! ZSYMSAVE == W CD; ELSE  {{{
C     IF (ZSYMSAVE(1:1).EQ.'W') THEN
         ! {{{
C        WRITE(3,'(I6)') 3*NATOMS
C        WRITE(3,'(G20.10)') EOFS(1)
C        DO J1=1,NATOMS
C           CALL CONVERT(QPLUS(3*(J1-1)+1),QPLUS(3*(J1-1)+2),QPLUS(3*(J1-1)+3),
C    1                   QPLUS(3*(NATOMS+J1-1)+1),QPLUS(3*(NATOMS+J1-1)+2),QPLUS(3*(NATOMS+J1-1)+3),OVEC,H1VEC,H2VEC)
C           WRITE(3,'(A2,4X,3G20.10)') 'O  ',OVEC(1),OVEC(2),OVEC(3)
C           WRITE(3,'(A2,4X,3G20.10)') 'H  ',H1VEC(1),H1VEC(2),H1VEC(3)
C           WRITE(3,'(A2,4X,3G20.10)') 'H  ',H2VEC(1),H2VEC(2),H2VEC(3)
C        ENDDO
         ! }}}
C     ELSE IF (ZSYMSAVE.EQ.'CD') THEN
         ! {{{
C        WRITE(3,'(I6)') NATOMS*6/2
C        WRITE(3,'(G20.10)') EOFS(1)
C        DO J2=1,NATOMS/2
C           CALL CAPSIDIO(QPLUS(3*(J2-1)+1),QPLUS(3*(J2-1)+2),QPLUS(3*(J2-1)+3),
C    1                    QPLUS(3*(NATOMS/2+J2-1)+1),QPLUS(3*(NATOMS/2+J2-1)+2),QPLUS(3*(NATOMS/2+J2-1)+3),CAPSCOORDS2,RAD,HEIGHT)
C           WRITE(3,'(A2,4X,3G20.10)') 'C1  ',CAPSCOORDS2(1),CAPSCOORDS2(2),CAPSCOORDS2(3)
C           WRITE(3,'(A2,4X,3G20.10)') 'C1  ',CAPSCOORDS2(4),CAPSCOORDS2(5),CAPSCOORDS2(6)
C           WRITE(3,'(A2,4X,3G20.10)') 'C1  ',CAPSCOORDS2(7),CAPSCOORDS2(8),CAPSCOORDS2(9)
C           WRITE(3,'(A2,4X,3G20.10)') 'C1  ',CAPSCOORDS2(10),CAPSCOORDS2(11),CAPSCOORDS2(12)
C           WRITE(3,'(A2,4X,3G20.10)') 'C1  ',CAPSCOORDS2(13),CAPSCOORDS2(14),CAPSCOORDS2(15)
C           WRITE(3,'(A2,4X,3G20.10)') 'C4  ',CAPSCOORDS2(16),CAPSCOORDS2(17),CAPSCOORDS2(18)
C        ENDDO
         ! }}}
C     ELSE
         ! {{{
C        WRITE(3,'(I6)') NATOMS
C        WRITE(3,'(G20.10)') EOFS(1)
C        WRITE(3,'(A2,4X,3G20.10)') (ZSYM(J1),QPLUS(3*(J1-1)+1),QPLUS(3*(J1-1)+2),QPLUS(3*(J1-1)+3),J1=1,NATOMS)
         ! }}}
C     ENDIF
         ! }}}

      DO J1=NFPLUS,1,-1
         ! {{{
         IF (ZSYMSAVE(1:1).EQ.'W') THEN
           ! {{{
C           WRITE(3,'(I6)') 3*NATOMS  !  WCOMMENT
            WRITE(3,'(I6)') 3*(NATOMS/2)
            WRITE(3,'(A,G25.15)') 'ENERGY=',EOFSFRAMEP(J1)
C           IF (J1.EQ.NFPLUS) THEN 
C              WRITE(3,'(G20.10)') EOFS(1)
C           ELSE
C              WRITE(3,'(A)') ' '
C           ENDIF
            WRITE(3,'(A2,4X,3G20.10)') 
     1   ('O  ',QFRAMEP(9*(J2-1)+1,J1),QFRAMEP(9*(J2-1)+2,J1),QFRAMEP(9*(J2-1)+3,J1),
     1    'H  ',QFRAMEP(9*(J2-1)+4,J1),QFRAMEP(9*(J2-1)+5,J1),QFRAMEP(9*(J2-1)+6,J1),
C    2    'H  ',QFRAMEP(9*(J2-1)+7,J1),QFRAMEP(9*(J2-1)+8,J1),QFRAMEP(9*(J2-1)+9,J1),J2=1,NATOMS)
     2    'H  ',QFRAMEP(9*(J2-1)+7,J1),QFRAMEP(9*(J2-1)+8,J1),QFRAMEP(9*(J2-1)+9,J1),J2=1,NATOMS/2)
            ! }}}
         ELSE IF (ZSYMSAVE.EQ.'CD') THEN
           ! {{{
            WRITE(3,'(I6)') NATOMS*6/2
            WRITE(3,'(A,G25.15)') 'ENERGY=',EOFSFRAMEP(J1)
C           IF (J1.EQ.NFPLUS) THEN
C              WRITE(3,'(G20.10)') EOFS(1)
C           ELSE
C              WRITE(3,'(A)') ' '
C           ENDIF
            WRITE(3,'(A)') ' '
            DO J2=1,NATOMS/2
               WRITE(3,'(A2,4X,3G20.10)') 'C1  ',QFRAMEP(18*(J2-1)+1,J1),QFRAMEP(18*(J2-1)+2,J1),QFRAMEP(18*(J2-1)+3,J1)
               WRITE(3,'(A2,4X,3G20.10)') 'C1  ',QFRAMEP(18*(J2-1)+4,J1),QFRAMEP(18*(J2-1)+5,J1),QFRAMEP(18*(J2-1)+6,J1)
               WRITE(3,'(A2,4X,3G20.10)') 'C1  ',QFRAMEP(18*(J2-1)+7,J1),QFRAMEP(18*(J2-1)+8,J1),QFRAMEP(18*(J2-1)+9,J1)
               WRITE(3,'(A2,4X,3G20.10)') 'C1  ',QFRAMEP(18*(J2-1)+10,J1),QFRAMEP(18*(J2-1)+11,J1),QFRAMEP(18*(J2-1)+12,J1)
               WRITE(3,'(A2,4X,3G20.10)') 'C1  ',QFRAMEP(18*(J2-1)+13,J1),QFRAMEP(18*(J2-1)+14,J1),QFRAMEP(18*(J2-1)+15,J1)
               WRITE(3,'(A2,4X,3G20.10)') 'C4  ',QFRAMEP(18*(J2-1)+16,J1),QFRAMEP(18*(J2-1)+17,J1),QFRAMEP(18*(J2-1)+18,J1)
            ENDDO
            ! }}}
         ELSEIF (STOCKT) THEN
            ! {{{
            WRITE(3,'(I6)') (NATOMS/2)
            WRITE(3,'(A,G25.15)') 'ENERGY=',EOFSFRAMEP(J1)
            DO J2=1,(NATOMS/2)
               WRITE(3,'(A2,4X,3G20.10,A13,3G20.10)')
     &         ZSYM(J2),QFRAMEP(3*(J2-1)+1,J1),QFRAMEP(3*(J2-1)+2,J1),QFRAMEP(3*(J2-1)+3,J1),
     &                        ' ATOM_VECTOR ',
     &                        SIN(QFRAMEP(3*((NATOMS/2)+J2-1)+1,J1))*COS(QFRAMEP(3*((NATOMS/2)+J2-1)+2,J1)),
     &                        SIN(QFRAMEP(3*((NATOMS/2)+J2-1)+1,J1))*SIN(QFRAMEP(3*((NATOMS/2)+J2-1)+2,J1)),
     &                        COS(QFRAMEP(3*((NATOMS/2)+J2-1)+1,J1))
            ENDDO

            ! }}}
!         ELSEIF (STOCKAAT) THEN
            ! {{{
!            WRITE(3,'(I6)') (NATOMS/2)
!            WRITE(3,'(A,G25.15)') 'ENERGY=',EOFSFRAMEP(J1)
!            DO J2=1,(NATOMS/2)
               
!               P(:) = QFRAMEP(3*((NATOMS/2)+J2-1)+1:3*((NATOMS/2)+J2-1)+3,J1)
!               CALL ROTMAT(P(:), RMAT(:,:))
!               P(:) = RMAT(:,3)     ! THE DIPOLE-VECTOR HAS TO BE ALONG THE Z-AXIS IN THE BODY-FRAME

!               WRITE(3,'(A1,4X,3G20.10,A13,3G20.10)')
!     &         'O', QFRAMEP(3*(J2-1)+1,J1), QFRAMEP(3*(J2-1)+2,J1), QFRAMEP(3*(J2-1)+3,J1),
!     &         ' ATOM_VECTOR ', P(1), P(2), P(3)
!            ENDDO
        ! }}}
         ELSEIF (RBAAT) THEN
         ! {{{
            WRITE(3,'(I6)') (NATOMS/2)
            WRITE(3,'(A,G25.15)') 'ENERGY=',EOFSFRAMEP(J1)
            DO J2=1,(NATOMS/2)
               WRITE(3,'(A1,4X,6G20.10)')
     &         'O', QFRAMEP(3*(J2-1)+1,J1), QFRAMEP(3*(J2-1)+2,J1), QFRAMEP(3*(J2-1)+3,J1),
     &         QFRAMEP(3*((NATOMS/2)+J2-1)+1,J1), QFRAMEP(3*((NATOMS/2)+J2-1)+2,J1),
     &         QFRAMEP(3*((NATOMS/2)+J2-1)+3,J1) 
            ENDDO
            ! }}}
         ELSEIF (AMHT) THEN
         ! {{{
            GLY_COUNT = 0
            DO J2=1,NMRES
               IF (SEQ(J2).EQ.8) GLY_COUNT = GLY_COUNT +1
            ENDDO
            WRITE(3,'(I6)') NATOMS+GLY_COUNT
            WRITE(3,'(A,G25.15)') 'ENERGY=',EOFSFRAMEP(J1)

            GLY_COUNT = 0
            DO J2=1,NMRES
              IF (SEQ(J2).EQ.8) THEN
          WRITE(3,'(A5,1X,3F20.10)') 'C1   ',QFRAMEP(9*(J2-1)+1-GLY_COUNT*3,J1),QFRAMEP(9*(J2-1)+2-GLY_COUNT*3,J1),
     &                                  QFRAMEP(9*(J2-1)+3-GLY_COUNT*3,J1)
          WRITE(3,'(A5,1X,3F20.10)') 'C1   ',QFRAMEP(9*(J2-1)+1-GLY_COUNT*3,J1),QFRAMEP(9*(J2-1)+2-GLY_COUNT*3,J1),
     &                                  QFRAMEP(9*(J2-1)+3-GLY_COUNT*3,J1)
          WRITE(3,'(A5,1X,3F20.10)') 'O    ',QFRAMEP(9*(J2-1)+4-GLY_COUNT*3,J1),QFRAMEP(9*(J2-1)+5-GLY_COUNT*3,J1),
     &                                  QFRAMEP(9*(J2-1)+6-GLY_COUNT*3,J1)
                GLY_COUNT = GLY_COUNT +1
              ELSE
          WRITE(3,'(A5,1X,3F20.10)') 'C1   ',QFRAMEP(9*(J2-1)+1-GLY_COUNT*3,J1),QFRAMEP(9*(J2-1)+2-GLY_COUNT*3,J1),
     &                                  QFRAMEP(9*(J2-1)+3-GLY_COUNT*3,J1)
          WRITE(3,'(A5,1X,3F20.10)') 'C2   ',QFRAMEP(9*(J2-1)+4-GLY_COUNT*3,J1),QFRAMEP(9*(J2-1)+5-GLY_COUNT*3,J1),
     &                                  QFRAMEP(9*(J2-1)+6-GLY_COUNT*3,J1)
          WRITE(3,'(A5,1X,3F20.10)') 'O    ',QFRAMEP(9*(J2-1)+7-GLY_COUNT*3,J1),QFRAMEP(9*(J2-1)+8-GLY_COUNT*3,J1),
     &                                  QFRAMEP(9*(J2-1)+9-GLY_COUNT*3,J1)
              ENDIF
          ENDDO
          ! }}}
         ELSEIF (RINGPOLYMERT.AND.(RPSYSTEM(1:4).EQ.'AECK')) THEN
         ! {{{
            WRITE(3,'(I6)') NOPT
            WRITE(3,'(A,G25.15)') 'ENERGY=',EOFSFRAMEP(J1)
            WRITE(3,'(A2,4X,3G20.10)') (ZSYM(J2),QFRAMEP(J2,J1),0.0D0,0.0D0,J2=1,NOPT)
            ! }}}
         ELSE
           ! {{{
            WRITE(3,'(I6)') NATOMS
            WRITE(3,'(A,G25.15)') 'ENERGY=',EOFSFRAMEP(J1)
C           IF (J1.EQ.NFPLUS) THEN
C              WRITE(3,'(G20.10)') EOFS(1)
C           ELSE
C              WRITE(3,'(A)') ' '
C           ENDIF
            IF (ZSYM(NATOMS).EQ.'SV') THEN
               DO J2=1, NATOMS
                  IF (MOD(J2,3).EQ.0) THEN
                     WRITE(3,'(A,4X,3G20.10)') 'O',QFRAMEP(3*(J2-1)+1,J1),QFRAMEP(3*(J2-1)+2,J1),QFRAMEP(3*(J2-1)+3,J1)
                  ELSE
                     WRITE(3,'(A,4X,3G20.10)') 'H',QFRAMEP(3*(J2-1)+1,J1),QFRAMEP(3*(J2-1)+2,J1),QFRAMEP(3*(J2-1)+3,J1)
                  ENDIF
               ENDDO
            ELSE
               WRITE(3,'(A2,4X,3G20.10)') 
     &         (ZSYM(J2),QFRAMEP(3*(J2-1)+1,J1),QFRAMEP(3*(J2-1)+2,J1),QFRAMEP(3*(J2-1)+3,J1),J2=1,NATOMS)
            ENDIF
            ! }}}
         ENDIF
         ! }}}
      ENDDO
!
!  ZSYMSAVE=W,CD  
!  STOCKT RBAAT AMHT RINGPOLYMERT ELSE
!  {{{
      IF (ZSYMSAVE(1:1).EQ.'W') THEN
        ! {{{
C        WRITE(3,'(I6)') 3*NATOMS ! WCOMMENT
         WRITE(3,'(I6)') 3*(NATOMS/2)
         WRITE(3,'(A,G25.15)') 'ENERGY=',EOFS(NSTEPPLUS+1)
C        DO J1=1,NATOMS ! WCOMMENT
         DO J1=1,NATOMS/2
            CALL CONVERT(QINIT(3*(J1-1)+1),QINIT(3*(J1-1)+2),QINIT(3*(J1-1)+3),
C    1                   QINIT(3*(NATOMS+J1-1)+1),QINIT(3*(NATOMS+J1-1)+2),QINIT(3*(NATOMS+J1-1)+3),
     1                   QINIT(3*(NATOMS/2+J1-1)+1),QINIT(3*(NATOMS/2+J1-1)+2),QINIT(3*(NATOMS/2+J1-1)+3),
     2                   OVEC,H1VEC,H2VEC)
            WRITE(3,'(A2,4X,3G20.10)') 'O  ',OVEC(1),OVEC(2),OVEC(3)
            WRITE(3,'(A2,4X,3G20.10)') 'H  ',H1VEC(1),H1VEC(2),H1VEC(3)
            WRITE(3,'(A2,4X,3G20.10)') 'H  ',H2VEC(1),H2VEC(2),H2VEC(3)
         ENDDO
         ! }}}
      ELSE IF (ZSYMSAVE.EQ.'CD') THEN
        ! {{{
         WRITE(3,'(I6)') NATOMS*6/2
         WRITE(3,'(A,G25.15)') 'ENERGY=',EOFS(NSTEPPLUS+1)
         DO J2=1,NATOMS/2
            CALL CAPSIDIO(QINIT(3*(J2-1)+1),QINIT(3*(J2-1)+2),QINIT(3*(J2-1)+3),
     1                    QINIT(3*(NATOMS/2+J2-1)+1),QINIT(3*(NATOMS/2+J2-1)+2),QINIT(3*(NATOMS/2+J2-1)+3),
     2                    CAPSCOORDS2,RAD,HEIGHT)
            WRITE(3,'(A2,4X,3G20.10)') 'C1  ',CAPSCOORDS2(1),CAPSCOORDS2(2),CAPSCOORDS2(3)
            WRITE(3,'(A2,4X,3G20.10)') 'C1  ',CAPSCOORDS2(4),CAPSCOORDS2(5),CAPSCOORDS2(6)
            WRITE(3,'(A2,4X,3G20.10)') 'C1  ',CAPSCOORDS2(7),CAPSCOORDS2(8),CAPSCOORDS2(9)
            WRITE(3,'(A2,4X,3G20.10)') 'C1  ',CAPSCOORDS2(10),CAPSCOORDS2(11),CAPSCOORDS2(12)
            WRITE(3,'(A2,4X,3G20.10)') 'C1  ',CAPSCOORDS2(13),CAPSCOORDS2(14),CAPSCOORDS2(15)
            WRITE(3,'(A2,4X,3G20.10)') 'C4  ',CAPSCOORDS2(16),CAPSCOORDS2(17),CAPSCOORDS2(18)
         ENDDO
         ! }}}
      ELSEIF (STOCKT) THEN
         ! {{{
         WRITE(3,'(I6)') (NATOMS/2)
         WRITE(3,'(A,G25.15)') 'ENERGY=',EOFS(NSTEPPLUS+1)
         DO J2=1,(NATOMS/2)
            WRITE(3,'(A2,4X,3G20.10,A13,3G20.10)')
     &         ZSYM(J2),QINIT(3*(J2-1)+1),QINIT(3*(J2-1)+2),QINIT(3*(J2-1)+3),
     &                                  ' ATOM_VECTOR ',
     &                                  SIN(QINIT(3*((NATOMS/2)+J2-1)+1))*COS(QINIT(3*((NATOMS/2)+J2-1)+2)),
     &                                  SIN(QINIT(3*((NATOMS/2)+J2-1)+1))*SIN(QINIT(3*((NATOMS/2)+J2-1)+2)),
     &                                  COS(QINIT(3*((NATOMS/2)+J2-1)+1))
         ENDDO
         ! }}}
      ELSEIF (RBAAT) THEN
         ! {{{
         WRITE(3,'(I6)') (NATOMS/2)
         WRITE(3,'(A,G25.15)') 'ENERGY=',EOFS(NSTEPPLUS+1)
         DO J2=1,(NATOMS/2)
            WRITE(3,'(A1,4X,6G20.10)')
     &      'O', QINIT(3*(J2-1)+1), QINIT(3*(J2-1)+2), QINIT(3*(J2-1)+3),
     &       QINIT(3*((NATOMS/2)+J2-1)+1), QINIT(3*((NATOMS/2)+J2-1)+2),
     &       QINIT(3*((NATOMS/2)+J2-1)+3)
         ENDDO
         ! }}}
      ELSEIF (AMHT) THEN
         ! {{{
            GLY_COUNT = 0
            DO J2=1,NMRES
               IF (SEQ(J2).EQ.8) GLY_COUNT = GLY_COUNT +1
            ENDDO
            WRITE(3,'(I6)') NATOMS+GLY_COUNT
            WRITE(3,'(A,G25.15)') 'ENERGY=',EOFS(NSTEPPLUS+1)
            GLY_COUNT = 0
            DO J2=1,NMRES
              IF (SEQ(J2).EQ.8) THEN
        WRITE(3,'(A5,1X,3F20.10)') 'C1   ',QINIT(9*(J2-1)+1-GLY_COUNT*3),QINIT(9*(J2-1)+2-GLY_COUNT*3),QINIT(9*(J2-1)+3-GLY_COUNT*3)
        WRITE(3,'(A5,1X,3F20.10)') 'C1   ',QINIT(9*(J2-1)+1-GLY_COUNT*3),QINIT(9*(J2-1)+2-GLY_COUNT*3),QINIT(9*(J2-1)+3-GLY_COUNT*3)
        WRITE(3,'(A5,1X,3F20.10)') 'O    ',QINIT(9*(J2-1)+4-GLY_COUNT*3),QINIT(9*(J2-1)+5-GLY_COUNT*3),QINIT(9*(J2-1)+6-GLY_COUNT*3)
                GLY_COUNT = GLY_COUNT +1
              ELSE
        WRITE(3,'(A5,1X,3F20.10)') 'C1   ',QINIT(9*(J2-1)+1-GLY_COUNT*3),QINIT(9*(J2-1)+2-GLY_COUNT*3),QINIT(9*(J2-1)+3-GLY_COUNT*3)
        WRITE(3,'(A5,1X,3F20.10)') 'C2   ',QINIT(9*(J2-1)+4-GLY_COUNT*3),QINIT(9*(J2-1)+5-GLY_COUNT*3),QINIT(9*(J2-1)+6-GLY_COUNT*3)
        WRITE(3,'(A5,1X,3F20.10)') 'O    ',QINIT(9*(J2-1)+7-GLY_COUNT*3),QINIT(9*(J2-1)+8-GLY_COUNT*3),QINIT(9*(J2-1)+9-GLY_COUNT*3)
              ENDIF
          ENDDO

          ! }}}
      ELSEIF (RINGPOLYMERT.AND.(RPSYSTEM(1:4).EQ.'AECK')) THEN
         ! {{{
         WRITE(3,'(I6)') NOPT
         WRITE(3,'(A,G25.15)') 'ENERGY=',EOFSFRAMEP(NSTEPPLUS+1)
         WRITE(3,'(A2,4X,3G20.10)') (ZSYM(J2),QINIT(J2),0.0D0,0.0D0,J2=1,NOPT)

         ! }}}
      ELSE
         ! {{{
         WRITE(3,'(I6)') NATOMS
         WRITE(3,'(A,G25.15)') 'ENERGY=',EOFS(NSTEPPLUS+1)

         IF (ZSYM(NATOMS).EQ.'SV') THEN
            DO J1=1, NATOMS
               IF (MOD(J1,3).EQ.0) THEN
                  WRITE(3,'(A,4X,3G20.10)') 'O',QINIT(3*(J1-1)+1),QINIT(3*(J1-1)+2),QINIT(3*(J1-1)+3)
               ELSE
                  WRITE(3,'(A,4X,3G20.10)') 'H',QINIT(3*(J1-1)+1),QINIT(3*(J1-1)+2),QINIT(3*(J1-1)+3)
               ENDIF
            ENDDO
         ELSE
            WRITE(3,'(A2,4X,3G20.10)') (ZSYM(J1),QINIT(3*(J1-1)+1),QINIT(3*(J1-1)+2),QINIT(3*(J1-1)+3),J1=1,NATOMS)
         ENDIF
         ! }}}
      ENDIF
! }}}

      DO J1=1,NFMINUS
         ! {{{
         IF (ZSYMSAVE(1:1).EQ.'W') THEN
           ! {{{
C           WRITE(3,'(I6)') 3*NATOMS  !  WCOMMENT
            WRITE(3,'(I6)') 3*(NATOMS/2)
            WRITE(3,'(A,G25.15)') 'ENERGY=',EOFSFRAMEM(J1)
C           IF (J1.EQ.NFMINUS) THEN
C              WRITE(3,'(G20.10)') EOFS(NSTEPPLUS+NSTEPMINUS+1)
C           ELSE
C              WRITE(3,'(A)') ' '
C           ENDIF
            WRITE(3,'(A2,4X,3G20.10)') 
     1            ('O  ',QFRAMEM(9*(J2-1)+1,J1),QFRAMEM(9*(J2-1)+2,J1),QFRAMEM(9*(J2-1)+3,J1),
     1             'H  ',QFRAMEM(9*(J2-1)+4,J1),QFRAMEM(9*(J2-1)+5,J1),QFRAMEM(9*(J2-1)+6,J1),
C    2             'H  ',QFRAMEM(9*(J2-1)+7,J1),QFRAMEM(9*(J2-1)+8,J1),QFRAMEM(9*(J2-1)+9,J1),J2=1,NATOMS)
     2             'H  ',QFRAMEM(9*(J2-1)+7,J1),QFRAMEM(9*(J2-1)+8,J1),QFRAMEM(9*(J2-1)+9,J1),J2=1,NATOMS/2)
            ! }}}
         ELSE IF (ZSYMSAVE.EQ.'CD') THEN
           ! {{{
            WRITE(3,'(I6)') NATOMS*6/2
            WRITE(3,'(A,G25.15)') 'ENERGY=',EOFSFRAMEM(J1)
C           IF (J1.EQ.NFMINUS) THEN
C              WRITE(3,'(G20.10)') EOFS(NSTEPPLUS+NSTEPMINUS+1)
C           ELSE
C              WRITE(3,'(A)') ' '
C           ENDIF
            DO J2=1,NATOMS/2
               WRITE(3,'(A2,4X,3G20.10)') 'C1  ',QFRAMEM(18*(J2-1)+1,J1),QFRAMEM(18*(J2-1)+2,J1),QFRAMEM(18*(J2-1)+3,J1)
               WRITE(3,'(A2,4X,3G20.10)') 'C1  ',QFRAMEM(18*(J2-1)+4,J1),QFRAMEM(18*(J2-1)+5,J1),QFRAMEM(18*(J2-1)+6,J1)
               WRITE(3,'(A2,4X,3G20.10)') 'C1  ',QFRAMEM(18*(J2-1)+7,J1),QFRAMEM(18*(J2-1)+8,J1),QFRAMEM(18*(J2-1)+9,J1)
               WRITE(3,'(A2,4X,3G20.10)') 'C1  ',QFRAMEM(18*(J2-1)+10,J1),QFRAMEM(18*(J2-1)+11,J1),QFRAMEM(18*(J2-1)+12,J1)
               WRITE(3,'(A2,4X,3G20.10)') 'C1  ',QFRAMEM(18*(J2-1)+13,J1),QFRAMEM(18*(J2-1)+14,J1),QFRAMEM(18*(J2-1)+15,J1)
               WRITE(3,'(A2,4X,3G20.10)') 'C4  ',QFRAMEM(18*(J2-1)+16,J1),QFRAMEM(18*(J2-1)+17,J1),QFRAMEM(18*(J2-1)+18,J1)
            ENDDO
            ! }}}
         ELSEIF (STOCKT) THEN
            ! {{{
            WRITE(3,'(I6)') (NATOMS/2)
            WRITE(3,'(A,G25.15)') 'ENERGY=',EOFSFRAMEM(J1)
            DO J2=1,(NATOMS/2)
               WRITE(3,'(A2,4X,3G20.10,A13,3G20.10)')
     &         ZSYM(J2),QFRAMEM(3*(J2-1)+1,J1),QFRAMEM(3*(J2-1)+2,J1),QFRAMEM(3*(J2-1)+3,J1),
     &                  ' ATOM_VECTOR ',
     &                  SIN(QFRAMEM(3*((NATOMS/2)+J2-1)+1,J1))*COS(QFRAMEM(3*((NATOMS/2)+J2-1)+2,J1)),
     &                  SIN(QFRAMEM(3*((NATOMS/2)+J2-1)+1,J1))*SIN(QFRAMEM(3*((NATOMS/2)+J2-1)+2,J1)),
     &                  COS(QFRAMEM(3*((NATOMS/2)+J2-1)+1,J1))
            ENDDO
            ! }}}
         ELSEIF (RBAAT) THEN
            ! {{{
            WRITE(3,'(I6)') (NATOMS/2)
            WRITE(3,'(A,G25.15)') 'ENERGY=',EOFSFRAMEM(J1)
            DO J2=1,(NATOMS/2)
               WRITE(3,'(A1,4X,6G20.10)')
     &         'O', QFRAMEM(3*(J2-1)+1,J1), QFRAMEM(3*(J2-1)+2,J1), QFRAMEM(3*(J2-1)+3,J1),
     &         QFRAMEM(3*((NATOMS/2)+J2-1)+1,J1), QFRAMEM(3*((NATOMS/2)+J2-1)+2,J1),
     &         QFRAMEM(3*((NATOMS/2)+J2-1)+3,J1)
            ENDDO
            ! }}}
         ELSEIF (AMHT) THEN
           ! {{{
            GLY_COUNT = 0
            DO J2=1,NMRES
               IF (SEQ(J2).EQ.8) GLY_COUNT = GLY_COUNT +1
            ENDDO
            WRITE(3,'(I6)') NATOMS+GLY_COUNT
            WRITE(3,'(A,G25.15)') 'ENERGY=',EOFSFRAMEM(J1)

            GLY_COUNT = 0
            DO J2=1,NMRES
              IF (SEQ(J2).EQ.8) THEN
          WRITE(3,'(A5,1X,3F20.10)') 'C1   ',QFRAMEM(9*(J2-1)+1-GLY_COUNT*3,J1),QFRAMEM(9*(J2-1)+2-GLY_COUNT*3,J1),
     &                                  QFRAMEM(9*(J2-1)+3-GLY_COUNT*3,J1)
          WRITE(3,'(A5,1X,3F20.10)') 'C1   ',QFRAMEM(9*(J2-1)+1-GLY_COUNT*3,J1),QFRAMEM(9*(J2-1)+2-GLY_COUNT*3,J1),
     &                                  QFRAMEM(9*(J2-1)+3-GLY_COUNT*3,J1)
          WRITE(3,'(A5,1X,3F20.10)') 'O    ',QFRAMEM(9*(J2-1)+4-GLY_COUNT*3,J1),QFRAMEM(9*(J2-1)+5-GLY_COUNT*3,J1),
     &                                  QFRAMEM(9*(J2-1)+6-GLY_COUNT*3,J1)
                GLY_COUNT = GLY_COUNT +1
              ELSE
          WRITE(3,'(A5,1X,3F20.10)') 'C1   ',QFRAMEM(9*(J2-1)+1-GLY_COUNT*3,J1),QFRAMEM(9*(J2-1)+2-GLY_COUNT*3,J1),
     &                                  QFRAMEM(9*(J2-1)+3-GLY_COUNT*3,J1)
          WRITE(3,'(A5,1X,3F20.10)') 'C2   ',QFRAMEM(9*(J2-1)+4-GLY_COUNT*3,J1),QFRAMEM(9*(J2-1)+5-GLY_COUNT*3,J1),
     &                                  QFRAMEM(9*(J2-1)+6-GLY_COUNT*3,J1)
          WRITE(3,'(A5,1X,3F20.10)') 'O    ',QFRAMEM(9*(J2-1)+7-GLY_COUNT*3,J1),QFRAMEM(9*(J2-1)+8-GLY_COUNT*3,J1),
     &                                  QFRAMEM(9*(J2-1)+9-GLY_COUNT*3,J1)
              ENDIF
          ENDDO
        ! }}}
         ELSEIF (RINGPOLYMERT.AND.(RPSYSTEM(1:4).EQ.'AECK')) THEN
         ! {{{
            WRITE(3,'(I6)') NOPT
            WRITE(3,'(A,G25.15)') 'ENERGY=',EOFSFRAMEM(J1)
            WRITE(3,'(A2,4X,3G20.10)') (ZSYM(J2),QFRAMEM(J2,J1),0.0D0,0.0D0,J2=1,NOPT)
        ! }}}
         ELSE
           ! {{{
            WRITE(3,'(I6)') NATOMS
            WRITE(3,'(A,G25.15)') 'ENERGY=',EOFSFRAMEM(J1)
C           IF (J1.EQ.NFMINUS) THEN
C              WRITE(3,'(G20.10)') EOFS(NSTEPPLUS+NSTEPMINUS+1)
C           ELSE
C              WRITE(3,'(A)') ' '
C           ENDIF

            IF (ZSYM(NATOMS).EQ.'SV') THEN
               DO J2=1, NATOMS
                  IF (MOD(J2,3).EQ.0) THEN
                     WRITE(3,'(A,4X,3G20.10)') 'O',QFRAMEM(3*(J2-1)+1,J1),QFRAMEM(3*(J2-1)+2,J1),QFRAMEM(3*(J2-1)+3,J1)
                  ELSE
                     WRITE(3,'(A,4X,3G20.10)') 'H',QFRAMEM(3*(J2-1)+1,J1),QFRAMEM(3*(J2-1)+2,J1),QFRAMEM(3*(J2-1)+3,J1)
                  ENDIF
               ENDDO
            ELSE
               WRITE(3,'(A2,4X,3G20.10)') 
     &         (ZSYM(J2),QFRAMEM(3*(J2-1)+1,J1),QFRAMEM(3*(J2-1)+2,J1),QFRAMEM(3*(J2-1)+3,J1),J2=1,NATOMS)
            ENDIF
            ! }}}
         ENDIF
         ! }}}
      ENDDO
      ! COMMENTED {{{
C     IF (ZSYMSAVE(1:1).EQ.'W') THEN
C        WRITE(3,'(I6)') 3*NATOMS
C        WRITE(3,'(G20.10)') EOFS(NSTEPPLUS+NSTEPMINUS+1)
C        DO J1=1,NATOMS
C           CALL CONVERT(Q(3*(J1-1)+1),Q(3*(J1-1)+2),Q(3*(J1-1)+3),
C    1                   Q(3*(NATOMS+J1-1)+1),Q(3*(NATOMS+J1-1)+2),Q(3*(NATOMS+J1-1)+3),OVEC,H1VEC,H2VEC)
C           WRITE(3,'(A2,4X,3G20.10)') 'O  ',OVEC(1),OVEC(2),OVEC(3)
C           WRITE(3,'(A2,4X,3G20.10)') 'H  ',H1VEC(1),H1VEC(2),H1VEC(3)
C           WRITE(3,'(A2,4X,3G20.10)') 'H  ',H2VEC(1),H2VEC(2),H2VEC(3)
C        ENDDO
C     ELSE IF (ZSYMSAVE.EQ.'CD') THEN
C        WRITE(3,'(I6)') NATOMS*6/2
C        WRITE(3,'(G20.10)') EOFS(NSTEPPLUS+NSTEPMINUS+1)
C        DO J2=1,NATOMS/2
C           CALL CAPSIDIO(Q(3*(J2-1)+1),Q(3*(J2-1)+2),Q(3*(J2-1)+3),
C    1                    Q(3*(NATOMS/2+J2-1)+1),Q(3*(NATOMS/2+J2-1)+2),Q(3*(NATOMS/2+J2-1)+3),CAPSCOORDS2,RAD,HEIGHT)
C           WRITE(3,'(A2,4X,3G20.10)') 'C1  ',CAPSCOORDS2(1),CAPSCOORDS2(2),CAPSCOORDS2(3)
C           WRITE(3,'(A2,4X,3G20.10)') 'C1  ',CAPSCOORDS2(4),CAPSCOORDS2(5),CAPSCOORDS2(6)
C           WRITE(3,'(A2,4X,3G20.10)') 'C1  ',CAPSCOORDS2(7),CAPSCOORDS2(8),CAPSCOORDS2(9)
C           WRITE(3,'(A2,4X,3G20.10)') 'C1  ',CAPSCOORDS2(10),CAPSCOORDS2(11),CAPSCOORDS2(12)
C           WRITE(3,'(A2,4X,3G20.10)') 'C1  ',CAPSCOORDS2(13),CAPSCOORDS2(14),CAPSCOORDS2(15)
C           WRITE(3,'(A2,4X,3G20.10)') 'C4  ',CAPSCOORDS2(16),CAPSCOORDS2(17),CAPSCOORDS2(18)
C        ENDDO
C     ELSE
C        WRITE(3,'(I6)') NATOMS
C        WRITE(3,'(G20.10)') EOFS(NSTEPPLUS+NSTEPMINUS+1)
C        WRITE(3,'(A2,4X,3G20.10)') (ZSYM(J1),Q(3*(J1-1)+1),Q(3*(J1-1)+2),Q(3*(J1-1)+3),J1=1,NATOMS)
C     ENDIF
      ! }}}

      CLOSE(3)

C JMC FOR UNRES, TO PUT IN THE DUMMY PEPTIDE GROUPS
      IF (UNRST) THEN
        ! {{{
         WRITE(ITSTRING2,'(A)') 'UNR.'//TRIM(ADJUSTL(ITSTRING))
         OPEN(UNIT=3,FILE=ITSTRING2,STATUS='UNKNOWN')
         DO J1=NFPLUS,1,-1
            DO K1=1,(NATOMS/2)-1
               DO K2=1,3
                  PEPCOORDS(6*(K1-1)+K2)=(2.0D0*QFRAMEP(6*(K1-1)+K2,J1)+QFRAMEP(6*K1+K2,J1))/3.0D0
                  PEPCOORDS(6*(K1-1)+K2+3)=(QFRAMEP(6*(K1-1)+K2,J1)+2.0D0*QFRAMEP(6*K1+K2,J1))/3.0D0
               END DO
            END DO
            WRITE(3,'(I6)') 2*NATOMS-2
            WRITE(3,'(A,G25.15)') 'ENERGY=',EOFSFRAMEP(J1)
C           IF (J1.EQ.NFPLUS) THEN
C              WRITE(3,'(G20.10)') EOFS(1)
C           ELSE
C              WRITE(3,'(A)') ' '
C           ENDIF
            WRITE(3,'(A2,4X,3G20.10)') (ZSYM(J2),QFRAMEP(3*(J2-1)+1,J1),QFRAMEP(3*(J2-1)+2,J1),QFRAMEP(3*(J2-1)+3,J1),J2=1,NATOMS)
            WRITE(3,'(A2,4X,3G20.10)') ('O ',PEPCOORDS(6*(K1-1)+1),PEPCOORDS(6*(K1-1)+2),PEPCOORDS(6*(K1-1)+3),K1=1,(NATOMS/2)-1)
            WRITE(3,'(A2,4X,3G20.10)') ('N ',PEPCOORDS(6*(K1-1)+4),PEPCOORDS(6*(K1-1)+5),PEPCOORDS(6*(K1-1)+6),K1=1,(NATOMS/2)-1)
         ENDDO
         DO K1=1,(NATOMS/2)-1
            DO K2=1,3
               PEPCOORDS(6*(K1-1)+K2)=(2.0D0*QINIT(6*(K1-1)+K2)+QINIT(6*K1+K2))/3.0D0
               PEPCOORDS(6*(K1-1)+K2+3)=(QINIT(6*(K1-1)+K2)+2.0D0*QINIT(6*K1+K2))/3.0D0
            END DO
         END DO
         WRITE(3,'(I6)') 2*NATOMS-2
         WRITE(3,'(A,G25.15)') 'ENERGY=',EOFS(NSTEPPLUS+1)
         WRITE(3,'(A2,4X,3G20.10)') (ZSYM(J1),QINIT(3*(J1-1)+1),QINIT(3*(J1-1)+2),QINIT(3*(J1-1)+3),J1=1,NATOMS)
         WRITE(3,'(A2,4X,3G20.10)') ('O ',PEPCOORDS(6*(K1-1)+1),PEPCOORDS(6*(K1-1)+2),PEPCOORDS(6*(K1-1)+3),K1=1,(NATOMS/2)-1)
         WRITE(3,'(A2,4X,3G20.10)') ('N ',PEPCOORDS(6*(K1-1)+4),PEPCOORDS(6*(K1-1)+5),PEPCOORDS(6*(K1-1)+6),K1=1,(NATOMS/2)-1)
         DO J1=1,NFMINUS
            DO K1=1,(NATOMS/2)-1
               DO K2=1,3
                  PEPCOORDS(6*(K1-1)+K2)=(2.0D0*QFRAMEM(6*(K1-1)+K2,J1)+QFRAMEM(6*K1+K2,J1))/3.0D0
                  PEPCOORDS(6*(K1-1)+K2+3)=(QFRAMEM(6*(K1-1)+K2,J1)+2.0D0*QFRAMEM(6*K1+K2,J1))/3.0D0
               END DO
            END DO
            WRITE(3,'(I6)') 2*NATOMS-2
            WRITE(3,'(A,G25.15)') 'ENERGY=',EOFSFRAMEM(J1)
C           IF (J1.EQ.NFMINUS) THEN
C              WRITE(3,'(G20.10)') EOFS(NSTEPPLUS+NSTEPMINUS+1)
C           ELSE
C              WRITE(3,'(A)') ' '
C           ENDIF
            WRITE(3,'(A2,4X,3G20.10)') (ZSYM(J2),QFRAMEM(3*(J2-1)+1,J1),QFRAMEM(3*(J2-1)+2,J1),QFRAMEM(3*(J2-1)+3,J1),J2=1,NATOMS)
            WRITE(3,'(A2,4X,3G20.10)') ('O ',PEPCOORDS(6*(K1-1)+1),PEPCOORDS(6*(K1-1)+2),PEPCOORDS(6*(K1-1)+3),K1=1,(NATOMS/2)-1)
            WRITE(3,'(A2,4X,3G20.10)') ('N ',PEPCOORDS(6*(K1-1)+4),PEPCOORDS(6*(K1-1)+5),PEPCOORDS(6*(K1-1)+6),K1=1,(NATOMS/2)-1)
         ENDDO
         CLOSE(3)
         ! }}}
      END IF ! UNRST

      IF ((DUMPPATH.OR.DUMPALLPATHS).AND.(.NOT.CONNECTT)) THEN
        ! {{{
         IF (UNRST) WRITE(*,'(A)') '*** NOTE - PATHLENGTHS CALCULATED FROM SAVED CARTESIAN COORDS WILL BE RUBBISH
     & AS THEY HAVE BEEN PLACED IN THE STANDARD UNRES ORIENTATION.'
         IF (ZSYMSAVE.EQ.'CD') WRITE(*,'(A)') 'WARNING, SYMMETRY AND NORMAL MODES NOT IMPLEMENTED PROPERLY FOR CAPSID'
         IF (UNRST) THEN
           ! {{{
            IF (CALCDIHE) THEN
                CALL UNRESCALCDIHEREF(DIHE,ALLANG,QPLUS)
            ELSE
                DIHE=0.5D0 ! DUMMY ORDER PARAM FOR PATHSAMPLE RELATED PURPOSES
            ENDIF
C JMC         WRITE(88,'(3G20.10)') EPLUS, DIHE, ALLANG
            WRITE(88,'(2G20.10)') EPLUS, DIHE
            ! }}}
         ELSE
            WRITE(88,'(G20.10)') EPLUS
         ENDIF
         IF (ZSYMSAVE(1:1).EQ.'W') THEN
           ! {{{
            IF (ZSYMSAVE.EQ.'W4') IPOT=4
            IF (ZSYMSAVE.EQ.'W3') IPOT=3
            IF (ZSYMSAVE.EQ.'W2') IPOT=2
            IF (ZSYMSAVE.EQ.'W1') IPOT=1
C           DO J2=1,NATOMS
            DO J2=1,NATOMS/2 ! WCOMMENT
               CALL CONVERT(QPLUS(3*(J2-1)+1),QPLUS(3*(J2-1)+2),QPLUS(3*(J2-1)+3),
C    1                      QPLUS(3*(NATOMS+J2-1)+1),QPLUS(3*(NATOMS+J2-1)+2),QPLUS(3*(NATOMS+J2-1)+3),
     1                      QPLUS(3*(NATOMS/2+J2-1)+1),QPLUS(3*(NATOMS/2+J2-1)+2),QPLUS(3*(NATOMS/2+J2-1)+3),
     2                      OVEC,H1VEC,H2VEC)
               QW(9*(J2-1)+1)=OVEC(1) ! WCOMMENT
               QW(9*(J2-1)+2)=OVEC(2)
               QW(9*(J2-1)+3)=OVEC(3)
               QW(9*(J2-1)+4)=H1VEC(1)
               QW(9*(J2-1)+5)=H1VEC(2)
               QW(9*(J2-1)+6)=H1VEC(3)
               QW(9*(J2-1)+7)=H2VEC(1)
               QW(9*(J2-1)+8)=H2VEC(2)
               QW(9*(J2-1)+9)=H2VEC(3)
            ENDDO 
C           NATOMS=NATOMS*3 ! WCOMMENT
            NATOMSSAVE=NATOMS
            NATOMS=(NATOMS/2)*3
            CALL SYMMETRY(HORDER,.FALSE.,QW,INERTIA) ! WCOMMENT
C           NATOMS=NATOMS/3 ! WCOMMENT
            NATOMS=2*(NATOMS/3)
            NATOMS=NATOMSSAVE
            WRITE(88,'(I6,1X,A4)') HORDER,FPGRP
C           DO J2=1,6*NATOMS ! WCOMMENT
            DO J2=1,3*NATOMS
               Q(J2)=QPLUS(J2)
            ENDDO
C           CALL H2OMODES(NATOMS,IPOT,Q,DIAG) ! WCOMMENT
            CALL H2OMODES(NATOMS/2,IPOT,Q,DIAG)
C           WRITE(88,'(3G20.10)') (DIAG(J2),J2=1,6*NATOMS) ! WCOMMENT
            IF (.NOT.NOFRQS) WRITE(88,'(3G20.10)') (DIAG(J2),J2=1,3*NATOMS)
            ! }}}
         ELSE IF ((FRQSPLUS(NOPT).EQ.0.0D0).OR.CHRMMT.OR.UNRST.OR.AMBERT.OR.NABT) THEN
           ! {{{
            DO J2=1,3*NATOMS
               Q(J2)=QPLUS(J2)
            ENDDO
!           IF (.NOT.UNRST) CALL POTENTIAL(Q,EPLUS,VNEW,.TRUE.,.TRUE.,RMS,.FALSE.,.FALSE.)
            IF (CHRMMT) THEN
              ! {{{
               HORDER=1
               FPGRP='C1'
               IF (ENDNUMHESS) THEN
                  CALL MAKENUMHESS(Q,NATOMS)
               ELSEIF (.NOT.NOFRQS) THEN
                  CALL POTENTIAL(Q,EPLUS,VNEW,.TRUE.,.TRUE.,RMS,.FALSE.,.FALSE.)
               ENDIF
               IF (.NOT.NOFRQS) CALL MASSWT2(NATOMS,ATMASS,Q,VNEW,.TRUE.)
               ! }}}
            ELSE IF (AMBERT) THEN
               ! {{{
               HORDER=1
               FPGRP='C1'
               IF (ENDNUMHESS) THEN
                   CALL MAKENUMHESS(Q,NATOMS)
               ENDIF
               IF (.NOT.NOFRQS) CALL MASSWT2(NATOMS,ATMASS,Q,VNEW,.TRUE.)
               ! }}}
            ELSE IF (NABT) THEN
               ! {{{
               HORDER=1
               FPGRP='C1'
               IF (ENDNUMHESS) THEN
                  CALL MAKENUMHESS(Q,NATOMS)
               ELSEIF (.NOT.NOFRQS) THEN
                  CALL POTENTIAL(Q,EPLUS,VNEW,.TRUE.,.TRUE.,RMS,.FALSE.,.FALSE.)
               ENDIF
               IF (.NOT.NOFRQS) CALL MASSWT2(NATOMS,ATMASS,Q,VNEW,.TRUE.)
               ! }}}
            ELSE IF (UNRST) THEN
               ! {{{
               DO J2=1,NRES
                  C(1,J2)=Q(6*(J2-1)+1)
                  C(2,J2)=Q(6*(J2-1)+2)
                  C(3,J2)=Q(6*(J2-1)+3)
                  C(1,J2+NRES)=Q(6*(J2-1)+4)
                  C(2,J2+NRES)=Q(6*(J2-1)+5)
                  C(3,J2+NRES)=Q(6*(J2-1)+6)
               ENDDO
               CALL UPDATEDC
!CALL INT_FROM_CART(.TRUE.,.FALSE.)
!CALL CHAINBUILD
               HORDER=1
               FPGRP='C1'
               IF (ENDNUMHESS) THEN
                  CALL MAKENUMINTHESS(NINTS,NATOMS)
                  CALL GETSTUFF(KD,NNZ,NINTB)
                  CALL INTSECDET(Q,3*NATOMS,KD,NNZ,NINTB,DIAG)
               ELSEIF (.NOT.NOFRQS) THEN
                  CALL POTENTIAL(Q,EPLUS,VNEW,.TRUE.,.TRUE.,RMS,.FALSE.,.FALSE.)
               ENDIF
               ! }}}
            ELSE
               ! {{{
               IF (ENDNUMHESS) THEN
                  CALL MAKENUMHESS(Q,NATOMS)
               ELSEIF (.NOT.NOFRQS) THEN
                  CALL POTENTIAL(Q,EPLUS,VNEW,.TRUE.,.TRUE.,RMS,.FALSE.,.FALSE.)
               ENDIF
               CALL SYMMETRY(HORDER,.FALSE.,Q,INERTIA)
               IF (.NOT.NOFRQS) CALL MASSWT(NATOMS,ATMASS,Q,VNEW,.TRUE.)
               ! }}}
            ENDIF
            IF (MACHINE) THEN
                 WRITE(88) HORDER,FPGRP
            ELSE
                 WRITE(88,'(I6,1X,A4)') HORDER,FPGRP
            ENDIF
            IF (.NOT.(UNRST.OR.NOFRQS)) THEN
               CALL DSYEV('N','U',3*NATOMS,HESS,SIZE(HESS,1),DIAG,TEMPA,9*NATOMS,INFO)
               IF (DIAG(1).LT.DIAG(3*NATOMS)) CALL EIGENSORT_VAL_ASC(DIAG,HESS,3*NATOMS,3*NATOMS)
            ENDIF
            IF (CHRMMT.OR.AMBERT.OR.NABT) THEN
               IF (MACHINE) THEN
                    IF (.NOT.NOFRQS) WRITE(88) (DIAG(J2)*4.184D26,J2=1,3*NATOMS)
               ELSE
                    IF (.NOT.NOFRQS) WRITE(88,'(3G20.10)') (DIAG(J2)*4.184D26,J2=1,3*NATOMS)
               ENDIF
            ELSE
               IF (.NOT.NOFRQS) WRITE(88,'(3G20.10)') (DIAG(J2),J2=1,3*NATOMS)
            ENDIF
            ! }}}
         ELSE
           ! {{{
            DO J2=1,3*NATOMS
               Q(J2)=QPLUS(J2)
            ENDDO
            CALL SYMMETRY(HORDER,.FALSE.,Q,INERTIA)
            WRITE(88,'(I6,1X,A4)') HORDER,FPGRP
            WRITE(88,'(3G20.10)') (FRQSPLUS(J2),J2=1,3*NATOMS)
            ! }}}
         ENDIF

         IF (MACHINE) THEN
              WRITE(88) (QPLUS(J2),J2=1,NOPT)
              WRITE(88) ETS

         ELSE
              WRITE(88,'(3F25.15)') (QPLUS(J2),J2=1,NOPT)
              WRITE(88,'(F20.10)') ETS
         ENDIF

         IF (ZSYMSAVE(1:1).EQ.'W') THEN
           ! {{{
            IF (ZSYMSAVE.EQ.'W4') IPOT=4
            IF (ZSYMSAVE.EQ.'W3') IPOT=3
            IF (ZSYMSAVE.EQ.'W2') IPOT=2
            IF (ZSYMSAVE.EQ.'W1') IPOT=1
C           DO J2=1,NATOMS ! WCOMMENT
            DO J2=1,NATOMS/2
               CALL CONVERT(QINIT(3*(J2-1)+1),QINIT(3*(J2-1)+2),QINIT(3*(J2-1)+3),
C    1                      QINIT(3*(NATOMS+J2-1)+1),QINIT(3*(NATOMS+J2-1)+2),QINIT(3*(NATOMS+J2-1)+3),
     1                      QINIT(3*(NATOMS/2+J2-1)+1),QINIT(3*(NATOMS/2+J2-1)+2),QINIT(3*(NATOMS/2+J2-1)+3),
     2                      OVEC,H1VEC,H2VEC)
               QW(9*(J2-1)+1)=OVEC(1)
               QW(9*(J2-1)+2)=OVEC(2)
               QW(9*(J2-1)+3)=OVEC(3)
               QW(9*(J2-1)+4)=H1VEC(1)
               QW(9*(J2-1)+5)=H1VEC(2)
               QW(9*(J2-1)+6)=H1VEC(3)
               QW(9*(J2-1)+7)=H2VEC(1)
               QW(9*(J2-1)+8)=H2VEC(2)
               QW(9*(J2-1)+9)=H2VEC(3)
            ENDDO 
C           NATOMS=NATOMS*3 ! WCOMMENT
            NATOMSSAVE=NATOMS
            NATOMS=(NATOMS/2)*3
            CALL SYMMETRY(HORDER,.FALSE.,QW,INERTIA) ! WCOMMENT
C           NATOMS=NATOMS/3 ! WCOMMENT
            NATOMS=2*(NATOMS/3)
            NATOMS=NATOMSSAVE
            WRITE(88,'(I6,1X,A4)') HORDER,FPGRP
C           DO J2=1,6*NATOMS ! WCOMMENT
            DO J2=1,3*NATOMS
               Q(J2)=QINIT(J2)
            ENDDO
C           CALL H2OMODES(NATOMS,IPOT,Q,DIAG) ! WCOMMENT
            CALL H2OMODES(NATOMS/2,IPOT,Q,DIAG)
C           WRITE(88,'(3G20.10)') (DIAG(J2),J2=1,6*NATOMS) ! WCOMMENT
            IF (.NOT.NOFRQS) WRITE(88,'(3G20.10)') (DIAG(J2),J2=1,3*NATOMS)
            ! }}}
         ELSE IF ((FRQSTS(NOPT).EQ.0.0D0).OR.CHRMMT.OR.UNRST.OR.AMBERT.OR.NABT) THEN
           ! {{{
            DO J2=1,3*NATOMS
               Q(J2)=QINIT(J2)
            ENDDO
!           IF (.NOT.UNRST) CALL POTENTIAL(Q,ETS,VNEW,.TRUE.,.TRUE.,RMS,.FALSE.,.FALSE.)
            IF (CHRMMT) THEN
               ! {{{
               HORDER=1
               FPGRP='C1'
               IF (ENDNUMHESS) THEN
                  CALL MAKENUMHESS(Q,NATOMS)
               ELSEIF (.NOT.NOFRQS) THEN
                  CALL POTENTIAL(Q,ETS,VNEW,.TRUE.,.TRUE.,RMS,.FALSE.,.FALSE.)
               ENDIF
               IF (.NOT.NOFRQS) CALL MASSWT2(NATOMS,ATMASS,Q,VNEW,.TRUE.) ! ?SHOULD THIS BE MASSWT2 FOR CHARMM?
               ! }}}
            ELSE IF (AMBERT) THEN
               ! {{{
               HORDER=1
               FPGRP='C1'
               IF (.NOT.NOFRQS) THEN
                  CALL MAKENUMHESS(Q,NATOMS)
                  CALL MASSWT2(NATOMS,ATMASS,Q,VNEW,.TRUE.)
               ENDIF
               ! }}}
            ELSE IF (NABT) THEN
               ! {{{
               HORDER=1
               FPGRP='C1'
               IF (ENDNUMHESS) THEN
                CALL MAKENUMHESS(Q,NATOMS)
               ELSEIF (.NOT.NOFRQS) THEN
                CALL POTENTIAL(Q,ETS,VNEW,.TRUE.,.TRUE.,RMS,.FALSE.,.FALSE.)
               END IF
               IF (.NOT.NOFRQS) CALL MASSWT2(NATOMS,ATMASS,Q,VNEW,.TRUE.)
               ! }}}
            ELSEIF (UNRST) THEN
               ! {{{
               DO J2=1,NRES
                  C(1,J2)=Q(6*(J2-1)+1)
                  C(2,J2)=Q(6*(J2-1)+2)
                  C(3,J2)=Q(6*(J2-1)+3)
                  C(1,J2+NRES)=Q(6*(J2-1)+4)
                  C(2,J2+NRES)=Q(6*(J2-1)+5)
                  C(3,J2+NRES)=Q(6*(J2-1)+6)
               ENDDO
               CALL UPDATEDC
!CALL INT_FROM_CART(.TRUE.,.FALSE.)
!CALL CHAINBUILD
               HORDER=1
               FPGRP='C1'
               IF (ENDNUMHESS) THEN
                  CALL MAKENUMINTHESS(NINTS,NATOMS)
                  CALL GETSTUFF(KD,NNZ,NINTB)
                  CALL INTSECDET(Q,3*NATOMS,KD,NNZ,NINTB,DIAG)
               ELSEIF (.NOT.NOFRQS) THEN
                  CALL POTENTIAL(Q,ETS,VNEW,.TRUE.,.TRUE.,RMS,.FALSE.,.FALSE.)
               ENDIF
               ! }}}
            ELSE
               ! {{{
               IF (ENDNUMHESS) THEN
                  CALL MAKENUMHESS(Q,NATOMS)
               ELSEIF (.NOT.NOFRQS) THEN
                  CALL POTENTIAL(Q,ETS,VNEW,.TRUE.,.TRUE.,RMS,.FALSE.,.FALSE.)
               ENDIF
               CALL SYMMETRY(HORDER,.FALSE.,Q,INERTIA)
               IF (.NOT.NOFRQS) CALL MASSWT(NATOMS,ATMASS,Q,VNEW,.TRUE.)
               ! }}}
            ENDIF
            IF (MACHINE) THEN
                 WRITE(88) HORDER,FPGRP
            ELSE
                 WRITE(88,'(I6,1X,A4)') HORDER,FPGRP
            ENDIF
            IF (.NOT.(UNRST.OR.NOFRQS)) THEN
               CALL DSYEV('N','U',3*NATOMS,HESS,SIZE(HESS,1),DIAG,TEMPA,9*NATOMS,INFO)
               IF (DIAG(1).LT.DIAG(3*NATOMS)) CALL EIGENSORT_VAL_ASC(DIAG,HESS,3*NATOMS,3*NATOMS)
            ENDIF
            IF (CHRMMT.OR.AMBERT.OR.NABT) THEN
               IF (MACHINE) THEN
                    IF (.NOT.NOFRQS) WRITE(88) (DIAG(J2)*4.184D26,J2=1,3*NATOMS)
               ELSE
                    IF (.NOT.NOFRQS) WRITE(88,'(3G20.10)') (DIAG(J2)*4.184D26,J2=1,3*NATOMS)
               ENDIF
            ELSE
               IF (.NOT.NOFRQS) WRITE(88,'(3G20.10)') (DIAG(J2),J2=1,3*NATOMS)
            ENDIF
            ! }}}
         ELSE
           ! {{{
            DO J2=1,3*NATOMS
               Q(J2)=QINIT(J2)
            ENDDO
            CALL SYMMETRY(HORDER,.FALSE.,Q,INERTIA)
            WRITE(88,'(I6,1X,A4)') HORDER,FPGRP
            IF (.NOT.NOFRQS) WRITE(88,'(3G20.10)') (FRQSTS(J2),J2=1,3*NATOMS)
            ! }}}
         ENDIF
         IF (MACHINE) THEN
              WRITE(88) (QINIT(J2),J2=1,NOPT)
         ELSE
              WRITE(88,'(3F25.15)') (QINIT(J2),J2=1,NOPT)
         ENDIF

         IF (UNRST) THEN
            ! {{{
            IF (CALCDIHE) THEN
                CALL UNRESCALCDIHEREF(DIHE,ALLANG,QMINUS)
            ELSE
                DIHE=0.5D0 ! DUMMY ORDER PARAM FOR PATHSAMPLE RELATED PURPOSES
            ENDIF
C JMC         WRITE(88,'(3G20.10)') EPLUS, DIHE, ALLANG
            WRITE(88,'(2G20.10)') EMINUS, DIHE
            ! }}}
         ELSE
            WRITE(88,'(G20.10)') EMINUS
         ENDIF

         IF (ZSYMSAVE(1:1).EQ.'W') THEN
            ! {{{
            IF (ZSYMSAVE.EQ.'W4') IPOT=4
            IF (ZSYMSAVE.EQ.'W3') IPOT=3
            IF (ZSYMSAVE.EQ.'W2') IPOT=2
            IF (ZSYMSAVE.EQ.'W1') IPOT=1
C           DO J2=1,NATOMS ! WCOMMENT
            DO J2=1,NATOMS/2
            ! {{{
               CALL CONVERT(QMINUS(3*(J2-1)+1),QMINUS(3*(J2-1)+2),QMINUS(3*(J2-1)+3),
C    1                   QMINUS(3*(NATOMS+J2-1)+1),QMINUS(3*(NATOMS+J2-1)+2),QMINUS(3*(NATOMS+J2-1)+3),
     1                   QMINUS(3*(NATOMS/2+J2-1)+1),QMINUS(3*(NATOMS/2+J2-1)+2),QMINUS(3*(NATOMS/2+J2-1)+3),
     2                   OVEC,H1VEC,H2VEC)
               QW(9*(J2-1)+1)=OVEC(1) ! WCOMMENT
               QW(9*(J2-1)+2)=OVEC(2)
               QW(9*(J2-1)+3)=OVEC(3)
               QW(9*(J2-1)+4)=H1VEC(1)
               QW(9*(J2-1)+5)=H1VEC(2)
               QW(9*(J2-1)+6)=H1VEC(3)
               QW(9*(J2-1)+7)=H2VEC(1)
               QW(9*(J2-1)+8)=H2VEC(2)
               QW(9*(J2-1)+9)=H2VEC(3)
               ! }}}
            ENDDO 
C           NATOMS=NATOMS*3 ! WCOMMENT
            NATOMSSAVE=NATOMS
            NATOMS=(NATOMS/2)*3
            CALL SYMMETRY(HORDER,.FALSE.,QW,INERTIA) ! WCOMMENT
C           NATOMS=NATOMS/3 ! WCOMMENT
            NATOMS=2*(NATOMS/3)
            NATOMS=NATOMSSAVE
            WRITE(88,'(I6,1X,A4)') HORDER,FPGRP
C           DO J2=1,6*NATOMS ! WCOMMENT
            DO J2=1,3*NATOMS
               Q(J2)=QMINUS(J2)
            ENDDO
C           CALL H2OMODES(NATOMS,IPOT,Q,DIAG)
            CALL H2OMODES(NATOMS/2,IPOT,Q,DIAG)
C           WRITE(88,'(3G20.10)') (DIAG(J2),J2=1,6*NATOMS) ! WCOMMENT
            IF (.NOT.NOFRQS) WRITE(88,'(3G20.10)') (DIAG(J2),J2=1,3*NATOMS)
            ! }}}
         ELSE IF ((FRQSMINUS(NOPT).EQ.0.0D0).OR.CHRMMT.OR.UNRST.OR.AMBERT.OR.NABT) THEN
           ! {{{
            DO J2=1,3*NATOMS
               Q(J2)=QMINUS(J2)
            ENDDO
!           IF (.NOT.UNRST) CALL POTENTIAL(Q,EMINUS,VNEW,.TRUE.,.TRUE.,RMS,.FALSE.,.FALSE.)
            IF (CHRMMT) THEN
               HORDER=1
               FPGRP='C1'
               IF (ENDNUMHESS) THEN
                  CALL MAKENUMHESS(Q,NATOMS)
               ELSEIF (.NOT.NOFRQS) THEN
                  CALL POTENTIAL(Q,EMINUS,VNEW,.TRUE.,.TRUE.,RMS,.FALSE.,.FALSE.)
               ENDIF
               IF (.NOT.NOFRQS) CALL MASSWT2(NATOMS,ATMASS,Q,VNEW,.TRUE.) ! ?SHOULD THIS BE MASSWT2 FOR CHARMM?
            ELSE IF (AMBERT) THEN
               HORDER=1
               FPGRP='C1'
               IF (.NOT.NOFRQS) THEN
                  CALL MAKENUMHESS(Q,NATOMS)
                  CALL MASSWT2(NATOMS,ATMASS,Q,VNEW,.TRUE.)
               ENDIF
            ELSE IF (NABT) THEN
               ! {{{
               HORDER=1
               FPGRP='C1'
               IF (ENDNUMHESS) THEN              
                CALL MAKENUMHESS(Q,NATOMS)
               ELSEIF (.NOT.NOFRQS) THEN
                CALL POTENTIAL(Q,EMINUS,VNEW,.TRUE.,.TRUE.,RMS,.FALSE.,.FALSE.)
               END IF
               IF (.NOT.NOFRQS) CALL MASSWT2(NATOMS,ATMASS,Q,VNEW,.TRUE.)
               ! }}}
            ELSE IF (UNRST) THEN
               ! {{{
               DO J2=1,NRES
                  C(1,J2)=Q(6*(J2-1)+1)
                  C(2,J2)=Q(6*(J2-1)+2)
                  C(3,J2)=Q(6*(J2-1)+3)
                  C(1,J2+NRES)=Q(6*(J2-1)+4)
                  C(2,J2+NRES)=Q(6*(J2-1)+5)
                  C(3,J2+NRES)=Q(6*(J2-1)+6)
               ENDDO
               CALL UPDATEDC
!CALL INT_FROM_CART(.TRUE.,.FALSE.)
!CALL CHAINBUILD
               HORDER=1
               FPGRP='C1'
               IF (ENDNUMHESS) THEN
                  CALL MAKENUMINTHESS(NINTS,NATOMS)
                  CALL GETSTUFF(KD,NNZ,NINTB)
                  CALL INTSECDET(Q,3*NATOMS,KD,NNZ,NINTB,DIAG)
               ELSEIF (.NOT.NOFRQS) THEN
                  CALL POTENTIAL(Q,EMINUS,VNEW,.TRUE.,.TRUE.,RMS,.FALSE.,.FALSE.)
               ENDIF
               ! }}}
            ELSE
               ! {{{
               IF (ENDNUMHESS) THEN
                  CALL MAKENUMHESS(Q,NATOMS)
               ELSEIF (.NOT.NOFRQS) THEN
                  CALL POTENTIAL(Q,EMINUS,VNEW,.TRUE.,.TRUE.,RMS,.FALSE.,.FALSE.)
               ENDIF
               CALL SYMMETRY(HORDER,.FALSE.,Q,INERTIA)
               IF (.NOT.NOFRQS) CALL MASSWT(NATOMS,ATMASS,Q,VNEW,.TRUE.)
               ! }}}
            ENDIF
            IF (MACHINE) THEN
                 WRITE(88) HORDER,FPGRP
            ELSE
                 WRITE(88,'(I6,1X,A4)') HORDER,FPGRP
            ENDIF
            IF (.NOT.(UNRST.OR.NOFRQS)) THEN
               CALL DSYEV('N','U',3*NATOMS,HESS,SIZE(HESS,1),DIAG,TEMPA,9*NATOMS,INFO)
               IF (DIAG(1).LT.DIAG(3*NATOMS)) CALL EIGENSORT_VAL_ASC(DIAG,HESS,3*NATOMS,3*NATOMS)
            ENDIF
            IF (CHRMMT.OR.AMBERT.OR.NABT) THEN
               IF (MACHINE) THEN
                    IF (.NOT.NOFRQS) WRITE(88) (DIAG(J2)*4.184D26,J2=1,3*NATOMS)
               ELSE
                    IF (.NOT.NOFRQS) WRITE(88,'(3G20.10)') (DIAG(J2)*4.184D26,J2=1,3*NATOMS)
               ENDIF
            ELSE
               IF (.NOT.NOFRQS) WRITE(88,'(3G20.10)') (DIAG(J2),J2=1,3*NATOMS)
            ENDIF
            ! }}}
         ELSE
           ! {{{
            DO J2=1,3*NATOMS
               Q(J2)=QMINUS(J2)
            ENDDO
            CALL SYMMETRY(HORDER,.FALSE.,Q,INERTIA)
            WRITE(88,'(I6,1X,A4)') HORDER,FPGRP
            IF (.NOT.NOFRQS) WRITE(88,'(3G20.10)') (FRQSMINUS(J2),J2=1,3*NATOMS)
            ! }}}
         ENDIF
         IF (MACHINE) THEN
              WRITE(88) (QMINUS(J2),J2=1,NOPT)

         ELSE
              WRITE(88,'(3F25.15)') (QMINUS(J2),J2=1,NOPT)
         ENDIF
         CLOSE(88)
         ! }}}
      ELSE IF (MACHINE.AND..NOT.CONNECTT) THEN
        ! {{{
C SAT THIS IS FOR THE CASE WHEN WE NEED POINTS FOR MINIMA TO BE OUTPUT IN BINARY FORMAT, BUT DO NOT WANT EXPENSIVE HESSIAN
C DIAGONALIZATION, WHICH IS REQUIRED TO PRODUCE "PATH.INFO" FILE
         INQUIRE(IOLENGTH=RECLEN) (DIAG(J1),J1=1,3*NATOMS)
         OPEN(UNIT=38,FILE="POINTS1.OUT",STATUS='UNKNOWN',FORM='UNFORMATTED',ACCESS='DIRECT',RECL=RECLEN)
         WRITE(38,REC=1) (QPLUS(J2),J2=1,NOPT)
         CLOSE(38)
         OPEN(UNIT=38,FILE="POINTS2.OUT",STATUS='UNKNOWN',FORM='UNFORMATTED',ACCESS='DIRECT',RECL=RECLEN)
         WRITE(38,REC=1) (QMINUS(J2),J2=1,NOPT)
         CLOSE(38)
         ! }}}
      ENDIF

      BFGSTST=BFGSTSTSAVE
      IVEC=IVECSAVE
      IVEC2=IVEC2SAVE

      IF (ALLOCATED(Q1)) DEALLOCATE(Q1)
      IF (ALLOCATED(Q2)) DEALLOCATE(Q2)
      IF (ALLOCATED(QW)) DEALLOCATE(QW)
      IF (ALLOCATED(QFRAMEP)) DEALLOCATE(QFRAMEP)
      IF (ALLOCATED(QFRAMEM)) DEALLOCATE(QFRAMEM)
! }}}
      ! }}}
      RETURN
      END

