C   OPTIM: A PROGRAM FOR OPTIMIZING GEOMETRIES AND CALCULATING REACTION PATHWAYS
C   COPYRIGHT (C) 1999-2006 DAVID J. WALES
C   THIS FILE IS PART OF OPTIM.
C
C   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C   (AT YOUR OPTION) ANY LATER VERSION.
C
C   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
C   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
C   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
C   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
C
C
C  USES TWO CALLS TO POTENTIAL PER VARIABLE BOX LENGTH TO MAKE NUMERICAL FIRST
C  AND SECOND DERIVATIVES FOR BOX LENGTH OPTIMISATION BY EIGENVECTOR-FOLLOWING.
C  ZERO SECOND DERIVATIVE RESULTS IF THE ENERGY IS LINEAR IN THE BOX LENGTH IF
C  FRACTIONAL COORDINATES ARE NOT USED.
C  THIS CAN OCCUR IF FIXIMAGE IS TURNED OFF FOR A LINE MINIMISATION AND LBFGS
C  TAKES A DAFT STEP, GIVING SILLY ANV, WHICH DOES NOT GET FIXED.
C
C  ANALYTIC DERIVATIVES FOR NORMAL AND FRACTIONAL COORDINATES ADDED FOR 'LS' 
C  ATOM TYPE 26/6/01.
C
      SUBROUTINE PVOPT(COORDS,EZERO,VNEW)
      USE COMMONS
      USE KEY
      IMPLICIT NONE
      LOGICAL PVAGAIN, PVFLAG
      DOUBLE PRECISION EZERO, COORDS(3*NATOMS), DIFF, GRAD, SECOND, SMAX, VNEW(3*NATOMS), 
     1                 EPLUS, EMINUS, RMS, EXP, EXM, EYP, EYM, EZP, EZM, GRADX, GRADY, GRADZ, SECONDX, SECONDY, SECONDZ,
     2                 PPARAM1, PPARAM2, PPARAM3, STEPX, STEPY, STEPZ, EPREV, EEST
      INTEGER NCOUNT, J1
      LOGICAL CUBIC, NRLOCAL, ANALYTIC
      COMMON /PVF/ PVFLAG
      COMMON /CUB/ CUBIC
      COMMON /BOXDERIVS/ GRADX, GRADY, GRADZ, SECONDX, SECONDY, SECONDZ
      
      ANALYTIC=.FALSE.
      IF (ZSYM(NATOMS).EQ.'LS') ANALYTIC=.TRUE.
      DIFF=0.001D0  
      SMAX=0.05D0
      TRAD=1.0D0
      PVFLAG=.FALSE.
C     FIXIMAGE=.TRUE.
C     IF (NORESET) THEN
C        NRLOCAL=.TRUE.
C        NORESET=.FALSE.
C     ENDIF
      NCOUNT=0
10    PVAGAIN=.FALSE.

      IF ((DABS(PARAM1-PARAM2).LT.1.0D-10).AND.(DABS(PARAM3-PARAM2).LT.1.0D-10).AND.CUBIC) THEN
         IF (ANALYTIC) THEN
            CALL POTENTIAL(COORDS,EZERO,VNEW,.FALSE.,.FALSE.,RMS,.FALSE.,.TRUE.)
            GRAD=GRADX
            SECOND=SECONDX
         ELSE
            PARAM1=PARAM1+DIFF
            PARAM2=PARAM2+DIFF
            PARAM3=PARAM3+DIFF
            CALL POTENTIAL(COORDS,EPLUS,VNEW,.FALSE.,.FALSE.,RMS,.FALSE.,.FALSE.)
            PARAM1=PARAM1-2*DIFF
            PARAM2=PARAM2-2*DIFF
            PARAM3=PARAM3-2*DIFF
            CALL POTENTIAL(COORDS,EMINUS,VNEW,.FALSE.,.FALSE.,RMS,.FALSE.,.FALSE.)
            PARAM1=PARAM1+DIFF
            PARAM2=PARAM2+DIFF
            PARAM3=PARAM3+DIFF

            GRAD=(EPLUS-EMINUS)/(2.0D0*DIFF) 
      
            SECOND=(EPLUS+EMINUS-2.0D0*EZERO)/(DIFF*DIFF) 
         ENDIF

         WRITE(*,'(A)') ' '
         WRITE(*,'(A,T50,F20.10)') 'ENTHALPY IN LATTICE OPTIMISATION IS ',EZERO
         WRITE(*,'(A,T50,F20.10)') 'GRADIENT WRT BOX LENGTH=',GRAD
         WRITE(*,'(A,T50,F20.10)') 'SECOND DERIVATIVE WRT BOX LENGTH=',SECOND
         WRITE(*,'(A,T50,F20.10)') 'FULL STEP SIZE=',-GRAD/SECOND
         IF (SECOND.LT.0.0D0) SECOND=-SECOND
         PPARAM1=PARAM1
         PPARAM2=PARAM2
         PPARAM3=PARAM3
         IF (DABS(GRAD/SECOND).GT.SMAX) THEN
            PARAM1=PARAM1-SMAX*GRAD*DABS(SECOND)/(SECOND*DABS(GRAD))
            WRITE(*,'(A,T50,F20.10,A,F15.10)') 'SCALED STEP=',-SMAX*GRAD*DABS(SECOND)/(SECOND*DABS(GRAD)),' NEW BOX LENGTH=',PARAM1
         ELSE
            PARAM1=PARAM1-GRAD/SECOND
            WRITE(*,'(A,T50,F20.10,A,F15.10)') 'BOX LENGTH STEP=',-GRAD/SECOND,' NEW BOX LENGTH=',PARAM1
         ENDIF
         PARAM2=PARAM1
         PARAM3=PARAM1
         IF (ABS(GRAD).LT.PVCONV) PVFLAG=.TRUE.
         IF (ABS(GRAD).GT.PVTOL) PVAGAIN=.TRUE.
      ELSE
         IF (NCOUNT.GT.0) THEN
            EEST=EZERO+GRADX*STEPX+GRADY*STEPY+GRADZ*STEPZ
     1                   +(SECONDX*STEPX**2+SECONDY*STEPY**2+SECONDZ*STEPZ**2)/2.0D0
            EPREV=EZERO
         ENDIF
         IF (ANALYTIC) THEN
            CALL POTENTIAL(COORDS,EZERO,VNEW,.FALSE.,.FALSE.,RMS,.FALSE.,.TRUE.)
         ELSE
            PARAM1=PARAM1+DIFF
            IF (FRACTIONAL) THEN
               DO J1=1,NATOMS
                  COORDS(3*(J1-1)+1)=COORDS(3*(J1-1)+1)*PARAM1/(PARAM1-DIFF)
               ENDDO
            ENDIF
            CALL POTENTIAL(COORDS,EXP,VNEW,.FALSE.,.FALSE.,RMS,.FALSE.,.FALSE.)
            PARAM1=PARAM1-2*DIFF
            IF (FRACTIONAL) THEN
               DO J1=1,NATOMS
                  COORDS(3*(J1-1)+1)=COORDS(3*(J1-1)+1)*PARAM1/(PARAM1+2*DIFF)
               ENDDO
            ENDIF
            CALL POTENTIAL(COORDS,EXM,VNEW,.FALSE.,.FALSE.,RMS,.FALSE.,.FALSE.)
            PARAM1=PARAM1+DIFF
            IF (FRACTIONAL) THEN
               DO J1=1,NATOMS
                  COORDS(3*(J1-1)+1)=COORDS(3*(J1-1)+1)*PARAM1/(PARAM1-DIFF)
               ENDDO
            ENDIF
   
            PARAM2=PARAM2+DIFF
            IF (FRACTIONAL) THEN
               DO J1=1,NATOMS
                  COORDS(3*(J1-1)+2)=COORDS(3*(J1-1)+2)*PARAM2/(PARAM2-DIFF)
               ENDDO
            ENDIF
            CALL POTENTIAL(COORDS,EYP,VNEW,.FALSE.,.FALSE.,RMS,.FALSE.,.FALSE.)
            PARAM2=PARAM2-2*DIFF
            IF (FRACTIONAL) THEN
               DO J1=1,NATOMS
                  COORDS(3*(J1-1)+2)=COORDS(3*(J1-1)+2)*PARAM2/(PARAM2+2*DIFF)
               ENDDO
            ENDIF
            CALL POTENTIAL(COORDS,EYM,VNEW,.FALSE.,.FALSE.,RMS,.FALSE.,.FALSE.)
            PARAM2=PARAM2+DIFF
            IF (FRACTIONAL) THEN
               DO J1=1,NATOMS
                  COORDS(3*(J1-1)+2)=COORDS(3*(J1-1)+2)*PARAM2/(PARAM2-DIFF)
               ENDDO
            ENDIF
   
            PARAM3=PARAM3+DIFF
            IF (FRACTIONAL) THEN
               DO J1=1,NATOMS
                  COORDS(3*(J1-1)+3)=COORDS(3*(J1-1)+3)*PARAM3/(PARAM3-DIFF)
               ENDDO
            ENDIF
            CALL POTENTIAL(COORDS,EZP,VNEW,.FALSE.,.FALSE.,RMS,.FALSE.,.FALSE.)
            PARAM3=PARAM3-2*DIFF
            IF (FRACTIONAL) THEN
               DO J1=1,NATOMS
                  COORDS(3*(J1-1)+3)=COORDS(3*(J1-1)+3)*PARAM3/(PARAM3+2*DIFF)
               ENDDO
            ENDIF
            CALL POTENTIAL(COORDS,EZM,VNEW,.FALSE.,.FALSE.,RMS,.FALSE.,.FALSE.)
            PARAM3=PARAM3+DIFF
            IF (FRACTIONAL) THEN
               DO J1=1,NATOMS
                  COORDS(3*(J1-1)+3)=COORDS(3*(J1-1)+3)*PARAM3/(PARAM3-DIFF)
               ENDDO
            ENDIF
   
            GRADX=(EXP-EXM)/(2.0D0*DIFF)
            SECONDX=(EXP+EXM-2.0D0*EZERO)/(DIFF*DIFF) 
            GRADY=(EYP-EYM)/(2.0D0*DIFF)
            SECONDY=(EYP+EYM-2.0D0*EZERO)/(DIFF*DIFF) 
            GRADZ=(EZP-EZM)/(2.0D0*DIFF)
            SECONDZ=(EZP+EZM-2.0D0*EZERO)/(DIFF*DIFF) 
         ENDIF

C        IF (NCOUNT.GT.0) THEN
C           IF (ABS((EZERO-EEST)/(EZERO-EPREV)).LT.TRAD) THEN
C              SMAX=SMAX*1.05D0
C           ELSE
C              SMAX=SMAX/1.1D0
C           ENDIF
C           WRITE(*,'(A,4F20.10)') 'DELTA E ACTUAL AND PREDICTED, RATIO, SMAX: ',EZERO-EPREV,EEST-EPREV,
C    1                             ABS((EZERO-EEST)/(EZERO-EPREV)),SMAX
C        ENDIF

         WRITE(*,'(A)') ' '
         WRITE(*,'(A,T50,F20.10)') 'ENTHALPY IN LATTICE OPTIMISATION IS ',EZERO
         WRITE(*,'(A,T50,3F20.10)') 'GRADIENT WRT X,Y,Z BOX LENGTHS=',GRADX,GRADY,GRADZ
         WRITE(*,'(A,T50,3F20.10)') 'SECOND DERIVATIVES WRT X,Y,Z BOX LENGTHS=',SECONDX,SECONDY,SECONDZ
         IF ((.NOT.PVTS).AND.((MIN(MIN(SECONDX,SECONDY),SECONDZ).LT.MAX(MAX(SECONDX,SECONDY),SECONDZ)/10.0D0).OR.
     1        (MAX(MAX(SECONDX,SECONDY),SECONDZ).LT.1.0D0))) THEN
            PRINT*,'SMALL BOX LENGTH CURVATURE DETECTED - SKIPPING BOX LENGTH OPTIMISATION'
            RETURN
         ENDIF

         IF (SECONDX.EQ.0.0D0) SECONDX=1.0D0
         IF (SECONDY.EQ.0.0D0) SECONDY=1.0D0
         IF (SECONDZ.EQ.0.0D0) SECONDZ=1.0D0
C
C  FRACTIONAL COORDINATES - STEPS SEEM TO NEED DAMPING
C    
         IF (FRACTIONAL) THEN
            SECONDX=SECONDX*1.2D0
            SECONDY=SECONDY*1.2D0
            SECONDZ=SECONDZ*1.2D0
         ENDIF

         STEPX=-2.0D0*GRADX/(DABS(SECONDX)*(1.0D0+DSQRT(1.0D0 + 4.0D0*(GRADX/SECONDX)**2)))
         STEPY=-2.0D0*GRADY/(DABS(SECONDY)*(1.0D0+DSQRT(1.0D0 + 4.0D0*(GRADY/SECONDY)**2)))
         STEPZ=-2.0D0*GRADZ/(DABS(SECONDZ)*(1.0D0+DSQRT(1.0D0 + 4.0D0*(GRADZ/SECONDZ)**2)))
         WRITE(*,'(A,T50,3F20.10)') 'FULL   STEP SIZE FOR X,Y,Z =',STEPX,STEPY,STEPZ

         IF (PVTS) THEN
            IF (NBOXTS.EQ.1) THEN
               STEPX=-STEPX
               IF (SECONDX.GT.0.0D0) STEPX=PUSHOFF*ABS(STEPX)/STEPX
            ELSE IF (NBOXTS.EQ.2) THEN
               STEPY=-STEPY
               IF (SECONDY.GT.0.0D0) STEPY=PUSHOFF*ABS(STEPY)/STEPY
            ELSE 
               STEPZ=-STEPZ
               IF (SECONDZ.GT.0.0D0) STEPZ=PUSHOFF*ABS(STEPZ)/STEPZ
            ENDIF
         ENDIF

         PPARAM1=PARAM1
         IF (DABS(STEPX).GT.SMAX) THEN
            PARAM1=PARAM1+SMAX*DABS(STEPX)/STEPX
         ELSE
            PARAM1=PARAM1+STEPX
         ENDIF

         PPARAM2=PARAM2
         IF (DABS(STEPY).GT.SMAX) THEN
            PARAM2=PARAM2+SMAX*DABS(STEPY)/STEPY
         ELSE
            PARAM2=PARAM2+STEPY
         ENDIF

         PPARAM3=PARAM3
         IF (DABS(STEPZ).GT.SMAX) THEN
            PARAM3=PARAM3+SMAX*DABS(STEPZ)/STEPZ
         ELSE
            PARAM3=PARAM3+STEPZ
         ENDIF
         STEPX=PARAM1-PPARAM1
         STEPY=PARAM2-PPARAM2
         STEPZ=PARAM3-PPARAM3
         WRITE(*,'(A,T50,3F20.10)') 'ACTUAL STEP SIZE FOR X,Y,Z =',PARAM1-PPARAM1,PARAM2-PPARAM2,PARAM3-PPARAM3
         WRITE(*,'(A,T50,3F20.10)') 'NEW X,Y,Z BOX LENGTHS:',PARAM1,PARAM2,PARAM3
         IF ((ABS(GRADX).LT.PVCONV).AND.(ABS(GRADY).LT.PVCONV).AND.(ABS(GRADZ).LT.PVCONV)) PVFLAG=.TRUE.
         IF ((ABS(GRADX).GT.PVTOL).OR.(ABS(GRADY).GT.PVTOL).OR.(ABS(GRADZ).GT.PVTOL)) PVAGAIN=.TRUE.
      ENDIF

      IF (FRACTIONAL) THEN
         DO J1=1,NATOMS
            COORDS(3*(J1-1)+1)=COORDS(3*(J1-1)+1)*PARAM1/PPARAM1
            COORDS(3*(J1-1)+2)=COORDS(3*(J1-1)+2)*PARAM2/PPARAM2
            COORDS(3*(J1-1)+3)=COORDS(3*(J1-1)+3)*PARAM3/PPARAM3
         ENDDO
      ENDIF

      IF (PVAGAIN) THEN
C        FIXIMAGE=.FALSE.
         PRINT*,'WARNING - NRLOCAL WAS UNSET - NOT TESTED!'
C        IF (NRLOCAL) NORESET=.TRUE.
         IF (.NOT.ANALYTIC) CALL POTENTIAL(COORDS,EZERO,VNEW,.FALSE.,.FALSE.,RMS,.FALSE.,.FALSE.)
C        FIXIMAGE=.TRUE.
C        IF (NRLOCAL) NORESET=.FALSE.
         NCOUNT=NCOUNT+1
         IF (NCOUNT.LT.PVSTEPS) GOTO 10
         WRITE(*,'(A)') 'WARNING, MAXIMUM NUMBER OF BOX LENGTH STEPS EXCEEDED IN PVOPT'
      ENDIF
C     FIXIMAGE=.FALSE.
C     IF (NRLOCAL) NORESET=.TRUE.

      RETURN
      END
