
MODULE PYMODULE

 INTEGER          :: I, J, J1, J2, J3, J4, J5, J6, K1, K2, OFFSET, REALNATOMS
 DOUBLE PRECISION, ALLOCATABLE :: RMIVEC(:,:,:), DPI1RMVEC(:,:,:), DPI2RMVEC(:,:,:), DPI3RMVEC(:,:,:)
 DOUBLE PRECISION, ALLOCATABLE :: PSCALEFAC1VEC(:),PSCALEFAC2VEC(:),EPSILON1(:,:,:),AEZR1(:,:,:), AEZR2(:,:,:)


 DOUBLE PRECISION :: BOXLX,BOXLY,BOXLZ,ANGLE,ANGLE2,PI,TWOPI,SIGMA1(4),CUT,RON,RON2,RANGE2INV3,ATTR(4),VECSBF(3)

 DOUBLE PRECISION ::I3(3,3) 
END MODULE PYMODULE


