C
C*************************************************************************
C
C  SUBROUTINE QSPCFW CALCULATES THE ENERGY AND CARTESIAN GRADIENT ANALYTICALLY. 
C  THIS CORRESPONDS TO A FLEXIBLE WATER MODEL INTRODUCED 
C  BY PAESANI ET AL. (JCP 125, 184507 (2006))
C
C*************************************************************************
C
      SUBROUTINE QSPCFW (NMOL,X,V,ENERGY,GTEST)
      IMPLICIT NONE
      INTEGER N, J1, J2, J3, J4, J5, J6, J7, J8, J9, J10, NMOL
      LOGICAL GTEST
C      INCLUDE 'PARAM_ATOMS.H'
      DOUBLE PRECISION X(9*NMOL), V(9*NMOL), ENERGY, EPSILON, SIGMA, QM,
     1                 GAMMA, REQ, KR, KTHETA, THETAEQ, R6, R12, DIST, 
     2                 ENERGY_LJ, ENERGY_Q, Q(4), HTOKCAL, RMX, RMY, RMZ,
     3                 FLJ, DFLJ, FC, DFC, C12, C6, Q1, Q2, ENERGY_OH, ENERGY_THETA,
     4                 XDUMM, FOH, DFOH, FTHETA, DFTHETA, X0(12*NMOL), THETA,
     5                 OH1VECX,OH1VECY,OH1VECZ,OH2VECX,OH2VECY,OH2VECZ,COSTHETA,
     6                 RDIST, DUMMY, DRO(4,4),DRH1(4,4),DRH2(4,4),RDIST1,RDIST2,
     7                 DTXH1,DTYH1,DTZH1,DTXH2,DTYH2,DTZH2,DOTNORMA,
     8                 GTX1,GTY1,GTZ1,GTX2,GTY2,GTZ2

      PARAMETER (HTOKCAL=331.952261D0)

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     STATEMENT FUNCTIONS
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      FLJ(XDUMM)=(C12/XDUMM**6-C6)/XDUMM**6
      DFLJ(XDUMM)=-6.0D0*(-C6+2.0D0*C12/XDUMM**6)/XDUMM**7
      FC(Q1,Q2,XDUMM)=Q1*Q2/XDUMM
      DFC(Q1,Q2,XDUMM)=-Q1*Q2/XDUMM**2
      FOH(XDUMM)=0.5D0*KR*(XDUMM-REQ)**2
      DFOH(XDUMM)=1.D0*KR*(XDUMM-REQ)
      FTHETA(XDUMM)=0.5D0*KTHETA*(XDUMM-THETAEQ)**2
      DFTHETA(XDUMM)=1.D0*KTHETA*(XDUMM-THETAEQ)

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C    DEFINE THE PARAMETERS OF THE POTENTIAL
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      EPSILON=0.1554D0
      SIGMA=3.1655D0
      QM=0.84D0
      GAMMA=1.0D0
      REQ=1.0D0
      KR=1059.162D0
      KTHETA=75.90D0
      THETAEQ=112.0D0*DACOS(-1.D0)/180.D0

      C6=4.D0*EPSILON*(SIGMA)**6
      C12=C6*(SIGMA)**6
      Q(1)=0.D0
      Q(2)=QM/2.D0
      Q(3)=QM/2.D0
      Q(4)=-QM

      N=NMOL

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C      DEFINE THE M POINT FOR ALL WATER MOLECULES
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
       
      DO J1=1,N
       J2=9*(J1-1)
       J3=12*(J1-1)
       X0(J3+1)=X(J2+1)
       X0(J3+2)=X(J2+2)
       X0(J3+3)=X(J2+3)
       X0(J3+4)=X(J2+4)
       X0(J3+5)=X(J2+5)
       X0(J3+6)=X(J2+6)
       X0(J3+7)=X(J2+7)
       X0(J3+8)=X(J2+8)
       X0(J3+9)=X(J2+9)
       RMX=GAMMA*X(J2+1)+(1.D0-GAMMA)*(X(J2+4)+X(J2+7))/2.D0
       RMY=GAMMA*X(J2+2)+(1.D0-GAMMA)*(X(J2+5)+X(J2+8))/2.D0  ! CARTESIAN COORDINATES OF THE M POINT
       RMZ=GAMMA*X(J2+3)+(1.D0-GAMMA)*(X(J2+6)+X(J2+9))/2.D0
       X0(J3+10)=RMX
       X0(J3+11)=RMY
       X0(J3+12)=RMZ
      END DO

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      DO J1=1,9*N
       V(J1)=0.D0         ! THREE POINTS PER MOLECULE
      END DO

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       INTERMOLECULAR POTENTIAL
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      ENERGY_LJ=0.0D0
      ENERGY_Q=0.0D0

      DO J1=1,4
       DO J2=1,4
        DRO(J1,J2)=0.D0
        DRH1(J1,J2)=0.D0
        DRH2(J1,J2)=0.D0
       END DO
      END DO

      DO J2=1,4
       DRO(1,J2)=0.D0
       DRH1(1,J2)=0.D0
       DRH2(1,J2)=0.D0
       DRO(2,J2)=0.D0
       DRH1(2,J2)=1.D0
       DRH2(2,J2)=0.D0
       DRO(3,J2)=0.D0
       DRH1(3,J2)=0.D0
       DRH2(3,J2)=1.D0
       DRO(4,J2)=GAMMA
       DRH1(4,J2)=0.5D0*(1.D0-GAMMA)
       DRH2(4,J2)=0.5D0*(1.D0-GAMMA)
      END DO

      DO J1=1,N
        J3=12*(J1-1)
        J9=9*(J1-1)
        DO J2=1,N
          IF (J1.NE.J2) THEN
          J4=12*(J2-1)
          J10=9*(J1-1)
           DIST=(X0(J3+1)-X0(J4+1))**2
     1         +(X0(J3+2)-X0(J4+2))**2
     2         +(X0(J3+3)-X0(J4+3))**2
           DIST=DSQRT(DIST)
C           IF (DIST.LT.1.8D0) THEN
C             ENERGY=1.D10
C             RETURN
C           END IF
           ENERGY_LJ=ENERGY_LJ+FLJ(DIST)   ! LJ CONTRIBUTION	

           IF (GTEST) THEN
            RDIST=1.D0/DIST
            V(J9+1)=V(J9+1)+DFLJ(DIST)*RDIST*(X0(J3+1)-X0(J4+1))
            V(J9+2)=V(J9+2)+DFLJ(DIST)*RDIST*(X0(J3+2)-X0(J4+2))
            V(J9+3)=V(J9+3)+DFLJ(DIST)*RDIST*(X0(J3+3)-X0(J4+3))
           END IF

           DO J5=2,4
            J7=J3+3*J5-3
            DO J6=2,4
             J8=J4+3*J6-3
             DUMMY=(X0(J7+1)-X0(J8+1))**2
     1            +(X0(J7+2)-X0(J8+2))**2
     2            +(X0(J7+3)-X0(J8+3))**2
             DUMMY=DSQRT(DUMMY)
             ENERGY_Q=ENERGY_Q+HTOKCAL*FC(Q(J5),Q(J6),DUMMY)  ! COULOMB CONTRIBUTION

            IF (GTEST) THEN
              RDIST=1.D0/DUMMY
              V(J9+1)=V(J9+1)+HTOKCAL*DFC(Q(J5),Q(J6),DUMMY)*RDIST*(X0(J7+1)-X0(J8+1))*DRO(J5,J6)
              V(J9+2)=V(J9+2)+HTOKCAL*DFC(Q(J5),Q(J6),DUMMY)*RDIST*(X0(J7+2)-X0(J8+2))*DRO(J5,J6)
              V(J9+3)=V(J9+3)+HTOKCAL*DFC(Q(J5),Q(J6),DUMMY)*RDIST*(X0(J7+3)-X0(J8+3))*DRO(J5,J6)
              V(J9+4)=V(J9+4)+HTOKCAL*DFC(Q(J5),Q(J6),DUMMY)*RDIST*(X0(J7+1)-X0(J8+1))*DRH1(J5,J6)
              V(J9+5)=V(J9+5)+HTOKCAL*DFC(Q(J5),Q(J6),DUMMY)*RDIST*(X0(J7+2)-X0(J8+2))*DRH1(J5,J6)
              V(J9+6)=V(J9+6)+HTOKCAL*DFC(Q(J5),Q(J6),DUMMY)*RDIST*(X0(J7+3)-X0(J8+3))*DRH1(J5,J6)
              V(J9+7)=V(J9+7)+HTOKCAL*DFC(Q(J5),Q(J6),DUMMY)*RDIST*(X0(J7+1)-X0(J8+1))*DRH2(J5,J6)
              V(J9+8)=V(J9+8)+HTOKCAL*DFC(Q(J5),Q(J6),DUMMY)*RDIST*(X0(J7+2)-X0(J8+2))*DRH2(J5,J6)
              V(J9+9)=V(J9+9)+HTOKCAL*DFC(Q(J5),Q(J6),DUMMY)*RDIST*(X0(J7+3)-X0(J8+3))*DRH2(J5,J6)
             END IF

            END DO
           END DO
         END IF
        ENDDO 
      ENDDO 


CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       INTRAMOLECULAR POTENTIAL
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      ENERGY_OH=0.0D0
      ENERGY_THETA=0.0D0

      DO J1=1,N
       J2=9*(J1-1)
       OH1VECX=X(J2+4)-X(J2+1)
       OH1VECY=X(J2+5)-X(J2+2)
       OH1VECZ=X(J2+6)-X(J2+3)
       DIST=OH1VECX**2+OH1VECY**2+OH1VECZ**2
       DIST=DSQRT(DIST)                        !OH1 DISTANCE
       RDIST1=1.D0/DIST

       OH2VECX=X(J2+7)-X(J2+1)
       OH2VECY=X(J2+8)-X(J2+2)
       OH2VECZ=X(J2+9)-X(J2+3)
       DUMMY=OH2VECX**2+OH2VECY**2+OH2VECZ**2
       DUMMY=DSQRT(DUMMY)                     !OH2 DISTANCE
       RDIST2=1.D0/DUMMY

       ENERGY_OH=ENERGY_OH+FOH(DIST)+FOH(DUMMY)

       COSTHETA=(OH1VECX*OH2VECX+OH1VECY*OH2VECY+OH1VECZ*OH2VECZ)/(DIST*DUMMY)
       DOTNORMA=COSTHETA
       THETA=DACOS(COSTHETA)
       ENERGY_THETA=ENERGY_THETA+FTHETA(THETA)   ! HOH 

       IF (GTEST) THEN
        DTXH1=-(1.D0/DSQRT(1.D0-DOTNORMA*DOTNORMA))*
     &          (OH2VECX/(DIST*DUMMY)-DOTNORMA*OH1VECX/DIST**2)
        DTYH1=-(1.D0/DSQRT(1.D0-DOTNORMA*DOTNORMA))*
     &          (OH2VECY/(DIST*DUMMY)-DOTNORMA*OH1VECY/DIST**2)
        DTZH1=-(1.D0/DSQRT(1.D0-DOTNORMA*DOTNORMA))*
     &          (OH2VECZ/(DIST*DUMMY)-DOTNORMA*OH1VECZ/DIST**2)
        DTXH2=-(1.D0/DSQRT(1.D0-DOTNORMA*DOTNORMA))*
     &          (OH1VECX/(DIST*DUMMY)-DOTNORMA*OH2VECX/DUMMY**2)
        DTYH2=-(1.D0/DSQRT(1.D0-DOTNORMA*DOTNORMA))*
     &          (OH1VECY/(DIST*DUMMY)-DOTNORMA*OH2VECY/DUMMY**2)
        DTZH2=-(1.D0/DSQRT(1.D0-DOTNORMA*DOTNORMA))*
     &          (OH1VECZ/(DIST*DUMMY)-DOTNORMA*OH2VECZ/DUMMY**2)

        GTX1=DFOH(DIST)*RDIST1*OH1VECX+DFTHETA(THETA)*DTXH1
        GTY1=DFOH(DIST)*RDIST1*OH1VECY+DFTHETA(THETA)*DTYH1
        GTZ1=DFOH(DIST)*RDIST1*OH1VECZ+DFTHETA(THETA)*DTZH1
        GTX2=DFOH(DUMMY)*RDIST2*OH2VECX+DFTHETA(THETA)*DTXH2
        GTY2=DFOH(DUMMY)*RDIST2*OH2VECY+DFTHETA(THETA)*DTYH2
        GTZ2=DFOH(DUMMY)*RDIST2*OH2VECZ+DFTHETA(THETA)*DTZH2
        V(J2+4)=V(J2+4)+GTX1
        V(J2+5)=V(J2+5)+GTY1
        V(J2+6)=V(J2+6)+GTZ1
        V(J2+7)=V(J2+7)+GTX2
        V(J2+8)=V(J2+8)+GTY2
        V(J2+9)=V(J2+9)+GTZ2
        V(J2+1)=V(J2+1)-GTX1-GTX2
        V(J2+2)=V(J2+2)-GTY1-GTY2
        V(J2+3)=V(J2+3)-GTZ1-GTZ2
       END IF

      END DO


      ENERGY=0.5D0*ENERGY_LJ+0.5D0*ENERGY_Q+ENERGY_OH+ENERGY_THETA

C      WRITE (*,*) 'LJ ',ENERGY_LJ
C      WRITE (*,*) 'Q ',ENERGY_Q
C      WRITE (*,*) 'OH ',ENERGY_OH
C      WRITE (*,*) 'THETA ',ENERGY_THETA
       

      RETURN
      END
