C   OPTIM: A PROGRAM FOR OPTIMIZING GEOMETRIES AND CALCULATING REACTION PATHWAYS
C   COPYRIGHT (C) 1999-2006 DAVID J. WALES
C   THIS FILE IS PART OF OPTIM.
C
C   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C   (AT YOUR OPTION) ANY LATER VERSION.
C
C   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
C   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
C   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
C   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
C
C
C  ADD ENERGY AND GRADIENT CORRECTION TERMS FOR THE CONTAINER SEPARATELY.
C
C     SUBROUTINE RAD(X,ENERGY,GRAD,GTEST)
      SUBROUTINE RAD(X)
      USE COMMONS
      USE KEY
      IMPLICIT NONE
      INTEGER J1, J3, NEIGH, J2
      DOUBLE PRECISION X(3*NATOMS), DIST, CMX, CMY, CMZ, NEARD, DUMMY, ALPHA
      LOGICAL RADMOVED, OVERLP
      COMMON /DISCON/ RADMOVED, OVERLP

      RADMOVED=.FALSE.
      IF (BULKT) RETURN

      ALPHA=1.0D0

      CMX=0.0D0
      CMY=0.0D0
      CMZ=0.0D0
      DO J1=1,NATOMS
         CMX=CMX+X(3*(J1-1)+1)
         CMY=CMY+X(3*(J1-1)+2)
         CMZ=CMZ+X(3*(J1-1)+3)
      ENDDO
      CMX=CMX/NATOMS
      CMY=CMY/NATOMS
      CMZ=CMZ/NATOMS
C     CMX=0.0D0
C     CMY=0.0D0
C     CMZ=0.0D0
      DO J1=1,NATOMS
         J3=3*J1
         DIST=(X(J3-2)-CMX)**2+(X(J3-1)-CMY)**2+(X(J3)-CMZ)**2
         IF (DIST.GT.RADIUS) THEN
            PRINT*,'IN RAD DIST,RADIUS=',SQRT(DIST),SQRT(RADIUS)

C            ENERGY=ENERGY+ALPHA*(SQRT(DIST)-SQRT(RADIUS))**2/2.0D0

C            IF (GTEST) THEN
C               GRAD(J3-2)=GRAD(J3-2)-ALPHA*(SQRT(DIST)-SQRT(RADIUS))*(X(J3-2)-CMX)/SQRT(DIST)
C               GRAD(J3-1)=GRAD(J3-1)-ALPHA*(SQRT(DIST)-SQRT(RADIUS))*(X(J3-1)-CMY)/SQRT(DIST)
C               GRAD(J3)=  GRAD(J3)  -ALPHA*(SQRT(DIST)-SQRT(RADIUS))*(X(J3)-CMZ)/SQRT(DIST)
C            ENDIF

            NEARD=1.0D90
            DO J2=1,NATOMS
               IF (J2.NE.J1) THEN
                  DUMMY=(X(3*(J1-1)+1)-X(3*(J2-1)+1))**2+(X(3*(J1-1)+2)-X(3*(J2-1)+2))**2+(X(3*(J1-1)+3)-X(3*(J2-1)+3))**2
                  IF (DUMMY.LT.NEARD) THEN
                     NEARD=DUMMY
                     NEIGH=J2
                  ENDIF
               ENDIF
            ENDDO
            NEARD=SQRT(NEARD)
C           IF (NEARD.GT.1.2D0) THEN
C              PRINT*,'COORDS BEFORE:'
C              WRITE(*,'(3F20.10)') (X(J2),J2=1,3*NATOMS)
C              PRINT*,'MOVING ATOM ',J1,' NEARER TO ATOM ',NEIGH,' NEARD=',NEARD
C              PRINT*,'ATOM ',J1,' INITIALLY AT ',X(3*(J1-1)+1),X(3*(J1-1)+2),X(3*(J1-1)+3)
C              PRINT*,'ATOM ',NEIGH,'           AT ',X(3*(NEIGH-1)+1),X(3*(NEIGH-1)+2),X(3*(NEIGH-1)+3)
               X(3*(J1-1)+1)=X(3*(NEIGH-1)+1)+(X(3*(J1-1)+1)-X(3*(NEIGH-1)+1))*1.2D0/NEARD
               X(3*(J1-1)+2)=X(3*(NEIGH-1)+2)+(X(3*(J1-1)+2)-X(3*(NEIGH-1)+2))*1.2D0/NEARD
               X(3*(J1-1)+3)=X(3*(NEIGH-1)+3)+(X(3*(J1-1)+3)-X(3*(NEIGH-1)+3))*1.2D0/NEARD
               X(3*(J1-1)+1)=X(3*(NEIGH-1)+1)+(X(3*(J1-1)+1)-X(3*(NEIGH-1)+1))*0.95D0
               X(3*(J1-1)+2)=X(3*(NEIGH-1)+2)+(X(3*(J1-1)+2)-X(3*(NEIGH-1)+2))*0.95D0
               X(3*(J1-1)+3)=X(3*(NEIGH-1)+3)+(X(3*(J1-1)+3)-X(3*(NEIGH-1)+3))*0.95D0
               RADMOVED=.TRUE.
C              PRINT*,'ATOM ',J1,'       NOW AT ',X(3*(J1-1)+1),X(3*(J1-1)+2),X(3*(J1-1)+3)
C              PRINT*,'DIST IS NOW=',SQRT((X(J3-2)-CMX)**2+(X(J3-1)-CMY)**2+(X(J3)-CMZ)**2)
C              PRINT*,'COORDS AFTER:'
C              WRITE(*,'(3F20.10)') (X(J2),J2=1,3*NATOMS)
C           ENDIF
C           DIST=SQRT(RADIUS*0.7D0/DIST)
C           X(J3-2)=CMX+(X(J3-2)-CMX)*DIST
C           X(J3-1)=CMY+(X(J3-1)-CMY)*DIST
C           X(J3)=CMZ+(X(J3)-CMZ)*DIST
         ENDIF
      ENDDO

      RETURN
      END
