!
!     COORDSA BECOMES THE OPTIMAL ALIGNMENT OF THE OPTIMAL PERMUTATION(-INVERSION) ISOMER, BUT 
!     WITHOUT THE PERMUTATIONS. DISTANCE IS THE RESIDUAL SQUARE DISTANCE FOR THE BEST ALIGNMENT WITH
!     RESPECT TO PERMUTATION(-INVERSION)S AS WELL AS ORIENTATION AND CENTRE OF MASS.
!
!     RBSITESORIENT IS CALLED FIRST FOR BOTH COORDSA AND COORDSB TO PUT THEM INTO A STANDARD
!     ORIENTATION IN DUMMYA AND DUMMYB (WHICH BOTH HAVE THE CENTRE OF COORDINATES AT THE ORIGIN)
!     WITH RESPECT TO THE SITES VIA ROTATIONS CORRESPONDING TO THE QUATERNIONS QA AND QB, 
!     RESPECTIVELY. THE OBJECTIVE IS TO IDENTIFY PERMUTATION-INVERSION ISOMERS WITHOUT FAIL.
!     HOWEVER, WE HAVE TO CYCLE OVER ALL EQUIVALENT RIGID BODIES IN TWO PARTICULAR ORBITS FOR DUMMYA
!     TO ACHIEVE THIS.
!     WE ITERATE PERMUTATIONS AND RBMINDIST MINIMISATIONS UP TO A MAXIMUM NUMBER OR UNTIL NO MORE
!     PERMUTATIONS ARE REQUIRED FOR EACH INSTANCE OF DUMMYA ALIGNED ACCORDING TO NCHOOSE1 AND 
!     NCHOOSE2 BY RBSITESORIENT. THE CUMULATIVE ROTATION THAT TAKES THE INITIAL DUMMYA TO THE ONE
!     THAT ALIGNS BEST WITH DUMMYB IS SAVED IN THE QUATERNION QCUMUL.

!     THEN, IF WE'VE NOT GOING WITH BULK, WE TRY AGAIN FOR THE INVERTED
!     VERSION OF COORDSA. THE TRANSFORMATION CORRESPONDING TO THE MINIMUM DISTANCE
!     IS SAVED WHENEVER IT IS IMPROVED - THE BEST ALIGNMENT INCLUDING PERMUTATIONS
!     IS SAVED IN XBEST, AND THE LAST STEP IS TO ROTATE THIS BACK TO COINCIDE BEST
!     WITH COORDSB (RATHER THAN DUMMYB) USING QBINV WHICH IS OBTAINED FROM QB. THIS GIVES SUITABLE
!     FIXED END POINTS FOR DNEB.

!     FINALLY, WE TRANSFORM COORDSA TO BE IN OPTIMAL ALIGNMENT, BUT WITHOUT THE
!     PERMUTATIONS IN XBEST. THE OVERALL TRANSFORMATION IS
!     COORDSA -> +/- QBINV QCUMUL QA (COORDSA - CMA) 
!
!     THE CORRESPONDENCE BETWEEN COORDSA AND DUMMYA AFTER DUMMYA HAS BEEN ALIGNED BY RBMINDIST IS
!     +/- RMATCUMUL ROTA (COORDSA - CMA) = PERMUTATION(DUMMYA)
!     WHERE +/- IS GIVEN BY THE VALUE OF INVERT WHICH CAN ASSUME +1 OR -1.
!     THE CENTRES OF COORDINATES FOR COORDSA AND COORDSB CAN BE ANYWHERE. ON RETURN, THE
!     CENTRE OF COORDINATES OF COORDSA WILL BE THE SAME AS FOR COORDSB.
!
!     ----------------------------------------------------------------------------------------------
 
      SUBROUTINE RBMINPERMDIST(COORDSB,COORDSA,DISTANCE,DIST2,QBEST,RMATBEST,DEBUG,BOXLX,BOXLY,BOXLZ,BULKT,SITESB,SITESA)

      USE COMMONS, ONLY : NATOMS, NRBSITES, RBSITE
      USE KEY,ONLY : NTSITES, NPERMGROUP, NPERMSIZE, PERMGROUP, NSETS, SETS, GEOMDIFFTOL, BESTPERM, EFIELDT, &
     &               RBOPS, NRBGROUP, RBSYMT, DBPTDT

      IMPLICIT NONE

      INTEGER, PARAMETER :: MAXIMUMTRIES = 100
      INTEGER            :: NPERM, PATOMS, NTRIES, NSIZE, JMAX, LOCMAX(1), J1, J2, J3, INFO, NRB
      INTEGER            :: INVERT, NORBIT1, NORBIT2, PERM(NATOMS), NCHOOSE2, NDUMMY, LPERM(NATOMS), NCHOOSE1
      INTEGER            :: NEWPERM(NATOMS), ALLPERM(NATOMS)
      DOUBLE PRECISION   :: COORDSA(3*NATOMS), COORDSB(3*NATOMS), DISTANCE, DISTWP, DIST2, TEMPA(9*NATOMS) 
      DOUBLE PRECISION   :: DUMMYA(3*NATOMS), DUMMYB(3*NATOMS), DUMMY(3*NATOMS), DUMMYWP(3*NATOMS)
      DOUBLE PRECISION   :: XA(3*NTSITES),  XB(3*NTSITES), XBS(3*NTSITES), XTMP(3*NATOMS)
      DOUBLE PRECISION   :: SITESA(3*NTSITES),  SITESB(3*NTSITES)
      DOUBLE PRECISION   :: RMAT(3,3), RMATI(3,3), ENERGY, VNEW(3*NATOMS), DX, DY, DZ, RMS, DBEST, XBEST(3*NATOMS)
      DOUBLE PRECISION   :: ROTA(3,3), ROTINVA(3,3), ROTB(3,3), ROTINVB(3,3), RMATCUMUL(3,3), LMAT(3,3)
      DOUBLE PRECISION   :: ROTINVBBEST(3,3), ROTABEST(3,3), RMATBEST(3,3), RMATWP(3,3)
      DOUBLE PRECISION   :: CMAX, CMAY, CMAZ, CMBX, CMBY, CMBZ
      DOUBLE PRECISION   :: PDUMMYA(3*NATOMS), PDUMMYB(3*NATOMS), LDISTANCE, XDUMMY, BOXLX, BOXLY, BOXLZ, WORSTRAD
      DOUBLE PRECISION   :: Q(4), Q1(4), Q2(4), AMAT(4,4), BMAT(4,4), DIAG(4), P(3)
      DOUBLE PRECISION   :: ST, THETA, THETAH, FCT, DUMMYC(3*NATOMS), DUMMYD(3*NATOMS)
      LOGICAL            :: DEBUG, BULKT
      DOUBLE PRECISION   :: BESTA(3*NATOMS), RBDISTANCE, PVEC(3), RTEMP1(3,3), RTEMP2(3,3), SITEDIST
      DOUBLE PRECISION   :: QCUMUL(4), QBEST(4), QA(4), QB(4), QBINV(4), QTMP(4), QI(4)
      DOUBLE PRECISION   :: COORDSAS(3*NATOMS), COORDSBS(3*NATOMS), COORDSCOMA(3*NATOMS/2), COORDSCOMB(3*NATOMS/2)

!      IF (EFIELDT) GOTO 100

      COORDSCOMA(:) = COORDSA(1:3*NATOMS/2)
      COORDSCOMB(:) = COORDSB(1:3*NATOMS/2)

      NATOMS = NATOMS/2

      CALL  MINPERMDISTRBCOM(COORDSCOMB,COORDSCOMA,DISTANCE,DIST2,QBEST,RMATBEST,DEBUG,BOXLX,BOXLY,BOXLZ,BULKT)

      NATOMS = 2*NATOMS

      IF (SQRT(DIST2) <= GEOMDIFFTOL) THEN
         IF (DEBUG) PRINT '(A)',' RBPERMDIST> MINPERMDISTRBCOM SUGGESTS IDENTICAL'
         CMAX = 0.0D0; CMAY = 0.0D0; CMAZ = 0.0D0
         CMBX = 0.0D0; CMBY = 0.0D0; CMBZ = 0.0D0
         DO J1 = 1, NATOMS/2
            CMAX = CMAX + COORDSA(3*(J1-1)+1)
            CMAY = CMAY + COORDSA(3*(J1-1)+2)
            CMAZ = CMAZ + COORDSA(3*(J1-1)+3)
            CMBX = CMBX + COORDSB(3*(J1-1)+1)
            CMBY = CMBY + COORDSB(3*(J1-1)+2)
            CMBZ = CMBZ + COORDSB(3*(J1-1)+3)
         ENDDO
         CMAX = 2*CMAX/NATOMS; CMAY = 2*CMAY/NATOMS; CMAZ = 2*CMAZ/NATOMS
         CMBX = 2*CMBX/NATOMS; CMBY = 2*CMBY/NATOMS; CMBZ = 2*CMBZ/NATOMS
         DO J1 = 1, NATOMS/2
            COORDSA(3*(J1-1)+1) = COORDSA(3*(J1-1)+1) - CMAX
            COORDSA(3*(J1-1)+2) = COORDSA(3*(J1-1)+2) - CMAY
            COORDSA(3*(J1-1)+3) = COORDSA(3*(J1-1)+3) - CMAZ
            COORDSB(3*(J1-1)+1) = COORDSB(3*(J1-1)+1) - CMBX
            COORDSB(3*(J1-1)+2) = COORDSB(3*(J1-1)+2) - CMBY
            COORDSB(3*(J1-1)+3) = COORDSB(3*(J1-1)+3) - CMBZ
         ENDDO
         CALL SITEPOS(COORDSB,SITESB)
         CALL SITEPOS(COORDSA,SITESA)
         DO J1 = 1, NTSITES
            J2 = 3*J1
            SITESA(J2-2:J2) = MATMUL(RMATBEST,SITESA(J2-2:J2))
         ENDDO
         RETURN
      ENDIF

100   CONTINUE

      COORDSAS(1:3*NATOMS) = COORDSA(1:3*NATOMS) ! TO TRACE ERROR, SEE AT THE END
      COORDSBS(1:3*NATOMS) = COORDSB(1:3*NATOMS) ! TO TRACE ERROR, SEE AT THE END

      NRB   = (NATOMS/2)
      IF (DBPTDT) THEN
         NSIZE = NTSITES
      ELSE
         NSIZE = NRB*NRBSITES
      ENDIF

      CMBX = 0.0D0; CMBY = 0.0D0; CMBZ = 0.0D0
      DO J1 = 1, NATOMS/2
         CMBX = CMBX + COORDSB(3*(J1-1)+1)
         CMBY = CMBY + COORDSB(3*(J1-1)+2)
         CMBZ = CMBZ + COORDSB(3*(J1-1)+3)
       ENDDO
      CMBX = 2*CMBX/NATOMS; CMBY = 2*CMBY/NATOMS; CMBZ = 2*CMBZ/NATOMS
!
!     BRING COORDSB INTO STANDARD ORIENTATION WITH RESPECT TO THE SITE POSITION
!     THE STANDARD ORIENTATION NEEDS TO BE DONE FOR THE SITES IF WE ARE GOING TO IDENTIFY
!     PERMUTATION-INVERSION ISOMERS WITH RESPECT TO THE SITES METRIC!
!
!     DUMMY(1:3*NATOMS)=DUMMYB(1:3*NATOMS)
!     CALL RBSITESORIENT(DUMMY,DUMMYB,NORBIT1,1,NORBIT2,1,NATOMS,DEBUG,ROTB,ROTINVB)
!
!     ----------------------------------------------------------------------------------------------
!     !
!     CALL POTENTIAL(COORDSB,ENERGY,VNEW,.TRUE.,.FALSE.,RMS,.FALSE.,.FALSE.)
!     PRINT '(2(A,F25.15))','BEFORE ENERGYB =',ENERGY,' RMS=',RMS
!     CALL POTENTIAL(DUMMYB,ENERGY,VNEW,.TRUE.,.FALSE.,RMS,.FALSE.,.FALSE.)
!     PRINT '(2(A,F25.15))',' AFTER ENERGYB =',ENERGY,' RMS=',RMS
!     !
!     ---------------------------------------------------------------------------------------------- 
!
!     CALL SITEPOS(DUMMYB,XB)
!     WRITE(975,'(I6)') NRB*NRBSITES
!     WRITE(975,'(A,F20.10)') 'B SITES 1'
!     WRITE(975,'(A,3F20.10)') ('LA ',XB(3*(J3-1)+1:3*(J3-1)+3),J3=1,NRB*NRBSITES)

      INVERT = 1

      DBEST    = 1.0D100
60    NCHOOSE1 = 0
65    NCHOOSE1 = NCHOOSE1+1
40    NCHOOSE2 = 0
30    NCHOOSE2 = NCHOOSE2+1

      DUMMYB(1:3*NATOMS) = COORDSB(1:3*NATOMS)
      DUMMYA(1:3*NATOMS) = COORDSA(1:3*NATOMS)

      DO J1 = 1, NATOMS
         ALLPERM(J1) = J1
         NEWPERM(J1) = J1
      ENDDO
 
!     THE OPTIMAL ALIGNMENT RETURNED BY MINPERDIST IS A LOCAL MINIMUM, BUT MAY NOT
!     BE THE GLOBAL MINIMUM. CALLING RBORIENT FIRST SHOULD PUT PERMUTATIONAL ISOMERS
!     INTO A STANDARD ALIGNMENT AND SPOT THE GLOBAL MINIMUM ZEDRO DISTANCE IN ONE
!     GO. HOWEVER, WE ALSO NEED TO CYCLE OVER EQUIVALENT ATOMS IN ORBITS USING NCHOOSE2.
!
!     PROBLEMS CAN OCCUR IF WE DON'T USE ALL THE ATOMS SPECIFIED BY NORBIT1 AND NORBIT2
!     BECAUSE OF THE NUMERICAL CUTOFFS EMPLOYED IN MYORIENT. WE COULD MISS THE
!     RIGHT ORIENTATION! 
!
!     IF WE USE RBORIENT TO PRODUCE PARTICULAR ORIENTATIONS THEN WE END UP ALIGNING 
!     COORDSA NOT WITH COORDSB BUT WITH THE STANDARD ORIENTATION OF COORDSB IN DUMMYB.
!     WE NOW DEAL WITH THIS BY TRACKING THE COMPLETE TRANSFORMATION, INCLUDING THE
!     CONTRIBUTION OF MYORIENT USING ROTB AND ROTINVB.
!

!      IF (INVERT.NE.1) THEN
!         PRINT '(A)',' RBMINPERMDIST> ERROR *** INVERSION NOT YET PROGRAMMED'
!         STOP
!      ENDIF

      DUMMYC(1:3*NATOMS) = DUMMYA(1:3*NATOMS)

      CALL RBSITESORIENT(DUMMYC,DUMMY,NORBIT1,NCHOOSE1,NORBIT2,NCHOOSE2,NATOMS,QA,DEBUG)

      DUMMYA(1:3*NATOMS)=DUMMY(1:3*NATOMS)
      DUMMYC(1:3*NATOMS)=DUMMYB(1:3*NATOMS)

!     CALL POTENTIAL(DUMMYA,ENERGY,VNEW,.TRUE.,.FALSE.,RMS,.FALSE.,.FALSE.)
!     PRINT '(2(A,F25.15))','BEFORE DUMMYA =',ENERGY,' RMS=',RMS

      CALL RBSITESORIENT(DUMMYC,DUMMY,NORBIT1,1,NORBIT2,1,NATOMS,QB,DEBUG)

      DUMMYB(1:3*NATOMS)=DUMMY(1:3*NATOMS)

!     CALL POTENTIAL(DUMMYB,ENERGY,VNEW,.TRUE.,.FALSE.,RMS,.FALSE.,.FALSE.)
!     PRINT '(2(A,F25.15))','BEFORE DUMMYB =',ENERGY,' RMS=',RMS

!     ----------------------------------------------------------------------------------------------
!     !
!      CALL POTENTIAL(DUMMYB,ENERGY,VNEW,.TRUE.,.FALSE.,RMS,.FALSE.,.FALSE.)
!      PRINT '(2(A,F25.15))', ' ENERGYBD =',ENERGY,' RMS=',RMS
!      CALL POTENTIAL(DUMMYA,ENERGY,VNEW,.TRUE.,.FALSE.,RMS,.FALSE.,.FALSE.)
!      PRINT '(2(A,F25.15))', ' ENERGYAD =',ENERGY,' RMS=',RMS
!
!      DISTANCE = 0.D0
!      DO J1 = 1, 3*NRB
!         DISTANCE = DISTANCE + (DUMMYA(J1) - DUMMYB(J1))**2
!      ENDDO
!     !
!     ----------------------------------------------------------------------------------------------
      
!      IF (INVERT == -1) ROTA(:,:) = MATMUL(ROTA(:,:),RMATI(:,:))  
!     RMATI WAS RETURNED ON INVERSION FOLLOWED BY ROTATION TO BRING ABOUT BEST SUPERPOSITION ON DUMMYB IN ONE GO

      IF (INVERT == -1) THEN
         QTMP(1:4) = QI(1:4)
         CALL QROTQ(QA,QTMP)
         QA(1:4) = QTMP(1:4)
      ENDIF  

      CALL SITEPOS(DUMMYA,XA)
      CALL SITEPOS(DUMMYB,XB)

      DISTANCE = 0.D0
      DO J1 = 1, 3*NSIZE
         DISTANCE = DISTANCE + (XA(J1) - XB(J1))**2
      ENDDO

!     ----------------------------------------------------------------------------------------------
!     !
!      WRITE(975,'(I6)') NRB*NRBSITES
!      WRITE(975,'(A,2I6,A,F20.10)') 'A SITES BEFORE ROTATION'
!      WRITE(975,'(A,3F20.10)') ('LA ',XA(3*(J3-1)+1:3*(J3-1)+3),J3=1,NRB*NRBSITES)
!      WRITE(975,'(I6)') NRB*NRBSITES
!      WRITE(975,'(A,2I6,A,F20.10)') 'B SITES BEFORE ROTATION'
!      WRITE(975,'(A,3F20.10)') ('LA ',XB(3*(J3-1)+1:3*(J3-1)+3),J3=1,NRB*NRBSITES)
!     !
!     ----------------------------------------------------------------------------------------------

      IF (DEBUG) PRINT '(A,G20.10)',' RBMINPERMDIST> AFTER INITIAL CALL TO RBSITESORIENT DISTANCE=',SQRT(DISTANCE)
!
!     BIPARTITE MATCHING ROUTINE FOR PERMUTATIONS. COORDINATES IN DUMMYB DO NOT CHANGE
!     BUT THE COORDINATES IN DUMMYA DO. DISTANCE IS THE DISTANCE IN THIS CASE.
!     WE RETURN TO LABEL 10 AFTER EVERY ROUND OF PERMUTATIONAL/ORIENTATIONAL ALIGNMENT
!     UNLESS WE HAVE CONVERGED TO THE IDENTITY PERMUTATION.
!
!     ATOMS ARE NOT ALLOWED TO APPEAR IN MORE THAN ONE GROUP.
!     THE MAXIMUM NUMBER OF PAIR EXCHANGES ASSOCIATED WITH A GROUP IS TWO.
!
      NTRIES = 0
!
!     QCUMUL IS A QUATERNION CONTAINING THE INFORMATION OF ACCUMULATED ROTATION THAT RELATES THE  
!     ORIGINAL DUMMYA OBTAINED FROM COORDSA TO THE FINAL ONE. INITIALIZE QCUMUL.
!
      QCUMUL(1:4) = (/1.D0, 0.D0, 0.D0, 0.D0/)

10    CONTINUE

      NTRIES = NTRIES + 1
      NDUMMY = 1

      DO J1 = 1, NATOMS
         PERM(J1) = J1
      ENDDO

      DO J1 = 1, NPERMGROUP

         PATOMS = NPERMSIZE(J1)
          IF (PATOMS.GT.NRB) THEN
             PRINT '(A,I6,A,I6,A,I6)',' RBMINPERMDIST> ERROR *** NUMBER OF PERMUTABLE SITES IN GROUP ',J1,' IS ',PATOMS, &
  &                                   ' WHICH EXCEEDS THE NUMBER OF RIGID BODIES ',NRB
             STOP
         ENDIF

         DO J2 = 1, PATOMS
            PDUMMYA(3*(J2-1)+1) = DUMMYA(3*(PERMGROUP(NDUMMY+J2-1)-1)+1)
            PDUMMYA(3*(J2-1)+2) = DUMMYA(3*(PERMGROUP(NDUMMY+J2-1)-1)+2)
            PDUMMYA(3*(J2-1)+3) = DUMMYA(3*(PERMGROUP(NDUMMY+J2-1)-1)+3)
            PDUMMYB(3*(J2-1)+1) = DUMMYB(3*(PERMGROUP(NDUMMY+J2-1)-1)+1)
            PDUMMYB(3*(J2-1)+2) = DUMMYB(3*(PERMGROUP(NDUMMY+J2-1)-1)+2)
            PDUMMYB(3*(J2-1)+3) = DUMMYB(3*(PERMGROUP(NDUMMY+J2-1)-1)+3)
         ENDDO
!
!     ALL PERMUTATIONS WITHIN THIS GROUP OF SIZE NPERMSIZE(J1) ARE NOW TRIED.
!     NOTE THAT WE ARE JUST USING A METRIC BASED ON THE RIGID BODY CENTRE OF MASS COORDINATES HERE!
!

         CALL MINPERM(PATOMS, PDUMMYB, PDUMMYA, BOXLX, BOXLY, BOXLZ, BULKT, LPERM, LDISTANCE, DIST2, WORSTRAD)

         DO J2 = 1, PATOMS
            PERM(PERMGROUP(NDUMMY+J2-1)) = PERMGROUP(NDUMMY+LPERM(J2)-1)
         ENDDO
!
!  WILL THIS BRANCH EVER BE EXECUTED FOR RIGID BODIES?!
!
         IF (NSETS(J1).GT.0) THEN
            PRINT '(A)',' RBPERM> ERROR *** ASSOCIATED ATOM SWAPS NOT ALLOWED FOR RIGID BODIES'
            STOP
         ENDIF

         NDUMMY = NDUMMY + NPERMSIZE(J1)

      ENDDO
!
!     DUE TO POSSIBLE SWAPS ABOVE, WE NEED TO UPDATE THE OVERALL PERMUTATION HERE.
!
      ALLPERM(1:NATOMS) = NEWPERM(1:NATOMS)
      DUMMY(1:3*NATOMS) = DUMMYA(1:3*NATOMS)
      NPERM    = 0
      DISTANCE = 0.0D0
!
!     NOW PERMUTE THE ROTATIONAL COORDINATES TO CORRESPOND TO THE CENTRE OF MASS COORDINATE PERMUTATION.
!
      DO J1 = (NATOMS/2)+1, NATOMS
         IF (PERM(J1).NE.J1) THEN
            PRINT '(A,2I8)',' RBMINPERMDIST> ERROR - J1,PERM(J1) SHOULD BE EQUAL', J1,PERM(J1)
         ENDIF
         PERM(J1) = PERM(J1-(NATOMS/2)) + (NATOMS/2)
      ENDDO

      DO J3 = 1, NATOMS

         DUMMYA(3*(J3-1)+1) = DUMMY(3*(PERM(J3)-1)+1)
         DUMMYA(3*(J3-1)+2) = DUMMY(3*(PERM(J3)-1)+2)
         DUMMYA(3*(J3-1)+3) = DUMMY(3*(PERM(J3)-1)+3)

         IF (J3.NE.PERM(J3)) THEN

            IF (DEBUG) WRITE(*,'(A,I5,A,I5)') ' RBPERMDIST> PERMUTE RIGID BODIES ',J3,' AND ',PERM(J3)
            NPERM = NPERM + 1
            NEWPERM(J3) = ALLPERM(PERM(J3))

         ENDIF

      ENDDO

!     SITE-SITE DISTANCE

      CALL SITEPOS(DUMMYA,XA)      ! DUMMYB REMAINED UNALTERED, SO AS XB.

!     WRITE(975,'(I6)') NRB*NRBSITES
!     WRITE(975,'(A,F20.10)') 'A SITES AFTER MINPERM'
!     WRITE(975,'(A,3F20.10)') ('LA ',XA(3*(J3-1)+1:3*(J3-1)+3),J3=1,NRB*NRBSITES)

      DO J1 = 1, 3*NSIZE
         DISTANCE = DISTANCE + (XA(J1) - XB(J1))**2
      ENDDO
!
!     UPDATE ALLPERM AGAIN. NEWPERM IS THE SAME AS ALLPERM AT THE START OF THE NEXT PASS.
!
      ALLPERM(1:NATOMS) = NEWPERM(1:NATOMS)

      IF (DEBUG) WRITE(*,'(A,I6,A,G20.10)') ' RBMINPERMDIST> SITES DISTANCE AFTER PERMUTING ',NPERM,'    &
     &                                        PAIRS OF RIGID BODIES=', SQRT(DISTANCE)
!
!     FURTHER ALIGNMENT. COORDINATES IN DUMMYA ARE RESET BY RBMINDIST (SECOND ARGUMENT).
!     MUST ALLOW AT LEAST ONE CALL TO RBMINDIST IN CASE THE STANDARD ORIENTATION RESULT IS TERRIBLE
!     BUT GIVES ZERO PERMUTATIONS!
!     WE TRY INTERNAL SYMMETRY OPERATIONS FIRST FOR EACH RIGID BODY, THEN MINIMISE THE
!     DISTANCE FURTHER (IF POSSIBLE) .
!  
      IF ((NPERM.NE.0) .OR. (NTRIES.EQ.1)) THEN 
!
!     NOW IF RBSYMT IS .TRUE. WE SHOULD MINIMISE THE DISTANCE METRIC FOR ALL THE RIGID BODIES
!     BY CONSIDERING ALL THE ALLOWED SYMMETRY OPERATIONS FOR EACH RIGID BODY IN TURN.
!     DO THIS BY ALTERING THE ORIENTATIONAL COORDINATES IN DUMMYA FOR EACH RIGID BODY IN TURN,
!     AFTER SAVING THEM, CALCULATE THE NEW DISTANCE USING THE ALL SITES METRIC, AND ACCEPT THE
!     NEW ORIENTATION IF THE DISTANCE IS LOWER.
!     COULD GENERALISE TO MORE THAN ONE SORT OF RIGID BODY AS WELL.
! 
         IF (RBSYMT) THEN
!
!     THIS CALL BLOCK DOES NOT DO ANY FURTHER ALIGNMENT SO AS NOT TO BREAK THE STANDARD REFERENCE GEOMETRY.
!
            CALL SITEPOS(DUMMYB,SITESB) 
            RBDISTANCE=1.0D10
            DO J1=1,NRB
               DO J2=1,NRBGROUP
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!DEBUG
!                  CALL SITEPOS(DUMMYA,SITESA)
!                  WRITE(975,'(I6)') NRB*NRBSITES
!                  WRITE(975,'(A,2I6,A,F20.10)') 'A SITES BEFORE ROTATION'
!                  WRITE(975,'(A,3F20.10)') ('LA ',SITESA(3*(J3-1)+1:3*(J3-1)+3),J3=1,NRB*NRBSITES)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!DEBUG

                  P(:)      = DUMMYA(3*(NRB+J1-1)+1:3*(NRB+J1-1)+3)
                  IF (J2 /= 1) THEN
                     CALL ROTMAT(P,RTEMP1)
                     PVEC(1:3) = MATMUL(RTEMP1,RBOPS(1:3,J2))
                     PVEC(1:3) = PVEC(1:3)/SQRT(DOT_PRODUCT(PVEC(1:3),PVEC(1:3)))
                     THETAH    = 0.5D0*RBOPS(4,J2) 
                     QTMP(1)   = COS(THETAH)
                     QTMP(2:4) = SIN(THETAH)*PVEC(1:3)
                     CALL QROTAA(QTMP,P)
                  ENDIF
                  DUMMYC(1:6*NRB) = DUMMYA(1:6*NRB)
                  DUMMYC(3*(NRB+J1-1)+1:3*(NRB+J1-1)+3) = P(1:3)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!DEBUG
!                  CALL POTENTIAL(DUMMYC,ENERGY,VNEW,.TRUE.,.FALSE.,RMS,.FALSE.,.FALSE.)
!                  PRINT '(A,I6,2(A,F25.15))',' RBMINPERMDIST> AFTER RBROT FOLLOWING INTERNAL SYMMETRY  & 
!     &                                          OPERATION ',J2,' ENERGY FOR A=',  ENERGY,' RMS=',RMS
!
!     CALCULATE NEW DISTANCE BASED ON ALL SITES METRIC RATHER THAN JUST CENTRE-OF-MASS RIGID BODY COORDINATES.
! 
                  CALL SITEPOS(DUMMYC,SITESA)
                  SITEDIST=0.D0
                  DO J3=1,3*NRB*NRBSITES
                     SITEDIST=SITEDIST+(SITESA(J3)-SITESB(J3))**2
                  ENDDO
!                  WRITE(975,'(I6)') NRB*NRBSITES
!                  WRITE(975,'(A,2I6,A,F20.10)') 'C SITES FOR J1,J2=',J1,J2,' DISTANCE=',SQRT(SITEDIST)
!                  WRITE(975,'(A,3F20.10)') ('LA ',SITESA(3*(J3-1)+1:3*(J3-1)+3),J3=1,NRB*NRBSITES)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!DEBUG

                  IF (SITEDIST.LT.RBDISTANCE) THEN
                     RBDISTANCE=SITEDIST
                     BESTA(1:6*NRB)=DUMMYC(1:6*NRB)
                  ENDIF
!                  PRINT '(A,2F20.10)',' RBPERMDIST> SITES DISTANCE, RBDISTANCE, =',SQRT(SITEDIST), SQRT(RBDISTANCE)
               ENDDO
               DUMMYA(1:6*NRB)=BESTA(1:6*NRB)
            ENDDO
!
!     THIS CALL ALIGNS THE OVERALL ORIENTATION WITH RESPECT TO THE SITES METRIC. WE SHOULD ALREADY
!     HAVE IDENTIFIED PERMUTATION-INVERSION ISOMERS USING THE ALIGNMENT BASED ON CENTRES OF MASS
!     ABOVE, IF APPLICABLE. WE NOW REPEAT BUT WITH AN ORIENTATIONAL ALIGNMENT WITH RESPECT TO SITES.
!
            CALL RBMINDIST2(DUMMYB,DUMMYA,NATOMS,DISTANCE,Q2,DEBUG)
 
            CALL QROTQ(Q2,QCUMUL)

            DO J1=1,NRB
               DO J2=1,NRBGROUP
!
!     MUST NOT USE RMAT HERE - BECAUSE RMAT IS ACCUMULATED BELOW.
! 
                  P(:)      = DUMMYA(3*(NRB+J1-1)+1:3*(NRB+J1-1)+3)
                  IF (J2 /= 1) THEN
                     CALL ROTMAT(P,RTEMP1)
                     PVEC(1:3) = MATMUL(RTEMP1,RBOPS(1:3,J2))
                     PVEC(1:3) = PVEC(1:3)/SQRT(DOT_PRODUCT(PVEC(1:3),PVEC(1:3)))
                     THETAH    = 0.5D0*RBOPS(4,J2)
                     QTMP(1)   = COS(THETAH)
                     QTMP(2:4) = SIN(THETAH)*PVEC(1:3)
                     CALL QROTAA(QTMP,P)
                  ENDIF
                  DUMMYC(1:6*NRB) = DUMMYA(1:6*NRB)
                  DUMMYC(3*(NRB+J1-1)+1:3*(NRB+J1-1)+3) = P(1:3)
!
!                 CALL POTENTIAL(DUMMYC,ENERGY,VNEW,.TRUE.,.FALSE.,RMS,.FALSE.,.FALSE.)
!                 PRINT '(A,I6,2(A,F25.15))',' RBMINPERMDIST> AFTER RBROT FOLLOWING INTERNAL SYMMETRY 
!                                              OPERATION ',J2,' ENERGY FOR A=', ENERGY,' RMS=',RMS
!
!     CALCULATE NEW DISTANCE BASED ON ALL SITES METRIC RATHER THAN JUST CENTRE-OF-MASS RIGID BODY COORDINATES.
! 
                  CALL SITEPOS(DUMMYC,SITESA)
                  SITEDIST=0.D0
                  DO J3=1,3*NRB*NRBSITES
                     SITEDIST=SITEDIST+(SITESA(J3)-SITESB(J3))**2
                  ENDDO
!                 PRINT '(A,2F20.10)',' RBMINPERMDIST> SITES DISTANCE^2,RBDISTANCE=',SITEDIST,RBDISTANCE
                  IF (SITEDIST.LT.RBDISTANCE) THEN
                     RBDISTANCE=SITEDIST
                     BESTA(1:6*NRB)=DUMMYC(1:6*NRB)
                  ENDIF
               ENDDO
               DUMMYA(1:6*NRB)=BESTA(1:6*NRB)
            ENDDO
         ELSE
!
!     THIS CALL ALIGNS THE OVERALL ORIENTATION WITH RESPECT TO THE SITES METRIC.
!     INTERNAL SYMMETRY OPERATIONS OF THE RIGID BODIES ARE NOT CONSIDERED.
!
            CALL RBMINDIST2(DUMMYB,DUMMYA,NATOMS,DISTANCE,Q2,DEBUG)

         ENDIF

!         DISTANCE  = DISTANCE*DISTANCE

!     ACCUMULATE ROTATION
         CALL QROTQ(Q2,QCUMUL)

         IF (NTRIES .LT. MAXIMUMTRIES) THEN
            GOTO 10
         ELSE ! PREVENT INFINITE LOOP
            IF (INVERT == -1) THEN
               IF(DEBUG) PRINT '(A)',' RBMINPERMDIST> WARNING - NUMBER OF TRIES EXCEEDED, GIVING UP'
            ELSE
               PRINT '(A)',' RBMINPERMDIST> WARNING - NUMBER OF TRIES EXCEEDED, GIVING UP'
            ENDIF
         ENDIF

      ENDIF

      IF (DISTANCE .LT. DBEST) THEN

         DBEST                = DISTANCE
         XBEST(1:3*NATOMS)    = DUMMYA(1:3*NATOMS)
         BESTPERM(1:NATOMS)   = ALLPERM(1:NATOMS)
         QTMP(1:4)  = QA(1:4)
         CALL QROTQ(QCUMUL,QTMP)
         QBEST(1:4) = QTMP(1:4)
         QBINV(1:4) = (/QB(1), -QB(2:4)/)

      ENDIF
!
! IF GEOMDIFFTOLL IS SET TOO SLOPPY WE COULD MISS THE BEST SOLUTION BY EXITING VIA THE LINE
! BELOW WITHOUT TRYING OTHER ORBITS. TURN OFF THIS ESCAPE?!
! THE TURN OFF SEEMS TO BE A BUG FOR NON-RBPERM RUNS. LJ38 TESTS FAIL WITH ALL COMPILERS, PRODUCING
! A "DISTANCE IS ZERO: THIS SHOULD NOT HAPPEN" ERROR!!! DJW
! PUT THE ESCAPE BACK IN FOR NOW.
!
      IF (SQRT(DBEST).LT.GEOMDIFFTOL) GOTO 50
      IF (NCHOOSE2.LT.NORBIT2) GOTO 30
      IF (NCHOOSE1.LT.NORBIT1) GOTO 65
      IF (EFIELDT) GOTO 50
!
50    DISTANCE = DBEST       ! SQUARED DISTANCE
!
!     XBEST CONTAINS THE BEST ALIGNMENT OF A COORDINATES FOR THE ORIENTATION OF B COORDINATES IN DUMMYB.
!     ROTATE XBEST BY ROTINVBBEST TO PUT IN BEST CORRESPONDENCE WITH COORDSB, UNDOING THE REORIENTATION TO  
!     DUMMYB FROM RBORIENT. 
!     WE SHOULD GET THE SAME RESULT FOR ROTINVBBEST * RMATBEST * (COORDSA-CMA), 
!     WHERE RMATBEST = +/- RMATCUMUL * ROTA FOR THE BEST ALIGNMENT 
!     (ASIDE FROM A POSSIBLE PERMUTATION OF THE ATOM ORDERING)
!
      CALL RBROT(XBEST, XTMP, QBINV, NATOMS)
      XBEST(1:3*NATOMS) = XTMP(1:3*NATOMS)

      DO J1 = 1, (NATOMS/2)
         XBEST(3*(J1-1)+1) = XBEST(3*(J1-1)+1) + CMBX
         XBEST(3*(J1-1)+2) = XBEST(3*(J1-1)+2) + CMBY
         XBEST(3*(J1-1)+3) = XBEST(3*(J1-1)+3) + CMBZ
      ENDDO

!     SITE-SITE DISTANCE

      CALL SITEPOS(XBEST,XA)

      CALL SITEPOS(COORDSB,XB)

      XDUMMY = 0.D0
      DO J1 = 1, 3*NSIZE
         XDUMMY = XDUMMY + (XA(J1) - XB(J1))**2
      ENDDO

      IF (ABS(SQRT(XDUMMY)-SQRT(DISTANCE)).GT.GEOMDIFFTOL) THEN
          PRINT '(2(A,F20.10))','RBMINPERMDIST> ERROR *** DISTANCE BETWEEN TRANSFORMED XBEST AND COORDSB=',  &
     &    SQRT(XDUMMY),  ' SHOULD BE ', SQRT(DISTANCE)
          PRINT *, 'COORDSB'
          DO J1 = 1, NATOMS
             J2 = 3*J1
             PRINT *, COORDSBS(J2-2), COORDSBS(J2-1), COORDSBS(J2)
          ENDDO 
          PRINT *, 'COORDSA'
          DO J1 = 1, NATOMS
             J2 = 3*J1
             PRINT *, COORDSAS(J2-2), COORDSAS(J2-1), COORDSAS(J2)
          ENDDO 

          STOP

      ENDIF

      CALL QROTQ(QBINV,QBEST)

      CALL QROTMAT(QBEST,RMATBEST)

      COORDSA(1:3*NATOMS)=XBEST(1:3*NATOMS) ! FINALLY, BEST COORDSA SHOULD INCLUDE PERMUTATIONS FOR DNEB INPUT!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!DEBUG
!      CALL POTENTIAL(COORDSA,ENERGY,VNEW,.TRUE.,.FALSE.,RMS,.FALSE.,.FALSE.)
!      PRINT '(2(A,F25.15))',' FINALLY A ENERGY=',ENERGY,' RMS=',RMS
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!DEBUG

      DISTANCE=SQRT(DISTANCE)

      END SUBROUTINE RBMINPERMDIST

!     ----------------------------------------------------------------------------------------------

      SUBROUTINE SITEPOS(Q, X)

!     GENERATE SITE POSITIONS FROM THE RIGID-BODY COORDINATES

      USE COMMONS, ONLY: NATOMS, NRBSITES, RBSITE
      USE KEY, ONLY: NTSITES, DBPTDT

      IMPLICIT NONE

      INTEGER :: J1, J2, J3, J4
      DOUBLE PRECISION :: Q(3*NATOMS), X(3*NTSITES), R(3), P(3), RM(3,3)
      DOUBLE PRECISION :: RBSITETD(4,3), SIGTD(4), SIGDB(2)

!      PRINT '(A)','DEFTD IS MISSING - STOP'
!      STOP

      IF (DBPTDT) CALL DEFTD(RBSITETD,SIGTD,SIGDB)

      DO J1 = 1, NATOMS/2

         J2   = 3*J1
         R(:) = Q(J2-2:J2)
         J2   = 3*NATOMS/2 + J2
         P(:) = Q(J2-2:J2)

         CALL ROTMAT(P, RM)

         IF (DBPTDT) THEN
            IF (J1 < NATOMS/2) THEN
               DO J3 = 1, NRBSITES
                  J4          = 3*((J1-1)*NRBSITES + J3)
                  X(J4-2:J4)  = R(:) + MATMUL(RM(:,:), RBSITE(J3,:))
               ENDDO
            ELSE
               DO J3 = 1, 4
                  J4          = 3*((J1-1)*NRBSITES + J3)
                  X(J4-2:J4)  = R(:) + MATMUL(RM(:,:), RBSITETD(J3,:))
               ENDDO
            ENDIF
         ELSE
            DO J3 = 1, NRBSITES
               J4          = 3*((J1-1)*NRBSITES + J3)
               X(J4-2:J4)  = R(:) + MATMUL(RM(:,:), RBSITE(J3,:))
            ENDDO
         ENDIF
      ENDDO

      END SUBROUTINE SITEPOS

!     ----------------------------------------------------------------------------------------------

      SUBROUTINE RBSITESORIENT(X, T1, NORBIT1, NCHOOSE1, NORBIT2, NCHOOSE2, NATOMS, Q2, DEBUG)

      USE COMMONS, ONLY: NRBSITES      
      USE KEY, ONLY : NTSITES, EFIELDT 
!                        
!     THIS SUBROUTINE PUTS PERMUTATIONAL ISOMERS OF A RIGID-BODY SYSTEM INTO A STANDARD ORIENTATION
!     WITH RESPECT TO THE SITES
!
      IMPLICIT NONE
      INTEGER          :: NATOMS, I, J, J1, J2, JMAX1, JMAX2, NORBIT1, NCHOOSE1, NORBIT2, NCHOOSE2, OFFSET, NSIZE
      DOUBLE PRECISION :: X(3*NATOMS), T1(3*NATOMS)
!      DOUBLE PRECISION :: XS(3*NATOMS*NRBSITES/2), T1S(3*NATOMS*NRBSITES/2), T2S(3*NATOMS*NRBSITES/2), DIST(NATOMS*NRBSITES/2)
      DOUBLE PRECISION :: XS(3*NTSITES), T1S(3*NTSITES), T2S(3*NTSITES), DIST(NTSITES)
      DOUBLE PRECISION :: AX(3), P(3), Q2(4), ROTM(3,3), ROTMINV(3,3)
      DOUBLE PRECISION :: THETA, THETAH, COST, SINT, COSTH, SINTH, ST, FCT
      DOUBLE PRECISION :: CMX, CMY, CMZ, DMAX, DUMMY, PROJ, DMAX2, CUTOFF1, DTEMP
      LOGICAL          :: DEBUG

      NSIZE = NTSITES
      OFFSET  = 3*NATOMS/2
      CUTOFF1 = 1.D-03

      CALL SITEPOS(X, XS)
!
!     MOVE CENTRE OF MASS TO THE ORIGIN.
!
      CMX = 0.D0; CMY = 0.D0; CMZ = 0.D0
      DO I = 1, NSIZE
         J = 3*I
         CMX = CMX + XS(J-2)
         CMY = CMY + XS(J-1)
         CMZ = CMZ + XS(J)
      ENDDO

      CMX = CMX/NSIZE; CMY = CMY/NSIZE; CMZ = CMZ/NSIZE
      DO I = 1, NSIZE
         J = 3*I
         XS(J-2) = XS(J-2) - CMX
         XS(J-1) = XS(J-1) - CMY
         XS(J)   = XS(J)   - CMZ
      ENDDO

      DMAX    = -1.D0
      NORBIT1 = 1

      IF (EFIELDT) THEN
         T1S(:) = XS(:)
         GOTO 100
      ENDIF
!
!     FIND THE RBSITE WHICH IS AT THE LARGEST DISTANCE FROM THE CENTRE OF MASS
!
      DO J1 = 1, NSIZE

         J = 3*J1
         DIST(J1) = SQRT(XS(J-2)**2 + XS(J-1)**2 + XS(J)**2)

         IF (ABS(DIST(J1) - DMAX) < CUTOFF1) THEN

            NORBIT1 = NORBIT1 + 1
            IF (NORBIT1 == NCHOOSE1) JMAX1 = J1

         ELSE IF (DIST(J1) > DMAX) THEN

            DMAX = DIST(J1)
            NORBIT1 = 1
            JMAX1 = J1

         ENDIF

      ENDDO

!     FOR TAGGED RBSITES, THE CHOICE OF THE FIRST RBSITE MATTERS IF IT BELONGS TO AN ORBIT OF SIZE > 1.
!
      IF ((ABS(XS(3*JMAX1-2)) < 1.D-08) .AND. (ABS(XS(3*JMAX1-1)) < 1.D-08)) THEN 
!
!     RB JMAX1 IS ALREADY ON THE Z AXIS!
!
         IF (XS(3*(JMAX1-1)+3) > 0.D0) THEN

            T1S(1:3*NSIZE) = XS(1:3*NSIZE)
            Q2(1:4)   = (/1.D0, 0.D0, 0.D0, 0.D0/)   ! IDENTITY OPERATION       
                  
         ELSE  ! ROTATE ABOUT THE X-AXIS BY \PI, DO NOT INVERT!

!            P(:) = (/4.D0*DATAN(1.D0), 0.D0, 0.D0/)
!            CALL ROTMAT(P(:), ROTM(:,:))
            Q2(1:4) = (/0.D0, 1.D0, 0.D0, 0.D0/)      ! THE CORRESPONDING QUATERNION

            DO J1 = 1, NATOMS/2
               J       = 3*J1
               T1S(J-2) = XS(J-2)
               T1S(J-1) =-XS(J-1)
               T1S(J)   =-XS(J)
            ENDDO

         ENDIF

      ELSE
!
!     ROTATE ALL RB'S THROUGH AN ANGLE THETA ABOUT THE AXIS P(:), SO AS TO ROTATE THE RBSITE JMAX1 ONTO THE Z AXIS 
!
!       THETA = DACOS(XS(3*JMAX1)/DMAX)
!     FOR SLOPPY CUTOFFS WE CANNOT ASSUME THAT DMAX IS EXACTLY THE SAME FOR MEMBERS OF THE SAME ORBIT!

        THETA = DACOS(XS(3*JMAX1)/DIST(JMAX1))

!     THE AXIS IS ON THE XY-PLANE AND PERPENDICULAR TO THE PROJECTION OF THE TRANSLATION VECTOR OF THE RB JMAX1
!     ON THE XY-PLANE. THE AXIS IS SO CHOSEN THAT A RIGHT-HANDED ROTATION IN THE RIGHT-HANDED COORDINATE SYSTEM
!     WILL RESULT IN THE REQUIRED TRANSFORMATION.

         AX(3) = 0.D0
         FCT   = DSQRT(XS(3*JMAX1-2)**2 + XS(3*JMAX1-1)**2)
         AX(1) = THETA*XS(3*JMAX1-1)/FCT
         AX(2) =-THETA*XS(3*JMAX1-2)/FCT

         CALL ROTMAT(AX(:), ROTM(:,:))
         THETAH  = 0.5D0*THETA
         AX(1:3) = AX(1:3)/SQRT(DOT_PRODUCT(AX(1:3),AX(1:3)))
         Q2(1:4) = (/COS(THETAH), SIN(THETAH)*AX(1:3)/)          ! THE CORRESPONDING QUATERNION 
          
         DO J1 = 1, NSIZE
            J2 = 3*J1
            T1S(J2-2:J2) = MATMUL(ROTM(:,:),XS(J2-2:J2))
         ENDDO   

      ENDIF

!
!     NOW FIND THE RBSITE WITH THE LARGEST DISTANCE FROM THE Z-AXIS 
!
100   DMAX = -1.0D0

      DO J1 = 1, NSIZE
         J2 = 3*J1 
         DIST(J1) = SQRT(T1S(J2-2)**2 + T1S(J2-1)**2)
         IF (DIST(J1) > DMAX) DMAX = DIST(J1)
      ENDDO

      DMAX2 = -1.0D100
!
!     PROJ IS THE SUM OF THE X COMPONENTS. USE T2S AS A DUMMY IN ORDER NOT TO 
!     CHANGE T1 UNTIL WE HAVE DECIDED WHICH ATOM TO PUT IN THE XZ PLANE.
!
      DO J1 = 1, NSIZE

         IF (ABS(DIST(J1) - DMAX) < CUTOFF1) THEN

            T2S(1:3*NSIZE) = T1S(1:3*NSIZE)

            CALL RBSITESROTXZ(NSIZE, J1, T2S, PROJ, DIST, Q2, .FALSE.)

            IF (ABS(PROJ - DMAX2) < CUTOFF1) THEN
               NORBIT2 = NORBIT2+1
               IF (NORBIT2 == NCHOOSE2) THEN
                  JMAX2 = J1
                  DTEMP = PROJ
               ENDIF
            ELSE IF (PROJ > DMAX2) THEN
               NORBIT2 = 1
               DMAX2   = PROJ
               DTEMP   = PROJ
               JMAX2   = J1
            ENDIF

         ENDIF

      ENDDO

!      PRINT '(A,I6,F20.10)', 'JMAX2,DMAX2=', JMAX2,DMAX2
!
!     AND NOW ROTATE IT INTO THE XZ PLANE.
!
      CALL RBSITESROTXZ(NSIZE, JMAX2, T1S, DTEMP, DIST, Q2, .TRUE.)

!     NOW CHANGE THE COORDINATES BY THE ROTATION MATRIX CORRESPONDING TO THE NET TRANSFORMATION

      CALL RBROT(X, T1, Q2, NATOMS)

      END SUBROUTINE RBSITESORIENT

!     ----------------------------------------------------------------------------------------------

      SUBROUTINE RBSITESROTXZ(NSIZE, JDO, T1S, PROJ, DIST, Q1, ROTT)

      USE KEY, ONLY : EFIELDT

      IMPLICIT NONE
      INTEGER          :: NSIZE, JDO, I, J, J2
      DOUBLE PRECISION :: T1S(3*NSIZE), PROJ, DIST(NSIZE), THETA, THETAH, COST, SINT, ST
      DOUBLE PRECISION :: COSTH, SINTH, FCT, P(3), Q2(4), Q1(4), RM(3,3), ROTM(3,3) 
      LOGICAL          :: ROTT

      J2     = 3*JDO
 
      IF (ABS(T1S(J2-1)) < 1.0D-8) THEN            ! ALREADY ON THE XZ PLANE

         Q2(1:4) = (/1.D0, 0.D0, 0.D0, 0.D0/) 

         IF (T1S(J2-2) < 0.D0) THEN                ! ROTATE ABOUT THE Z AXIS BY \PI, DO NOT INVERT!!

            Q2(1:4) = (/0.D0, 0.D0, 0.D0, 1.D0/) 

            DO I = 1, NSIZE
               J = 3*I
               T1S(J-2) =-T1S(J-2)
               T1S(J-1) =-T1S(J-1)
            ENDDO

         ENDIF

      ELSE

         COST   = T1S(J2-2)/DIST(JDO)       
         SINT   = T1S(J2-1)/DIST(JDO)
         THETA  =-ATAN2(SINT,COST)              ! THE NEGATIVE SIGN APPEARS AS THE ROTATION IS REVERSED  
         THETAH = 0.5D0*THETA
         Q2(1:4) = (/COS(THETAH), 0.D0, 0.D0, SIN(THETAH)/)     ! THE QUATERNION CORRESPONDING TO R_{Z}(-\THETA)
         RM(1:3,1:3) = 0.D0                           ! THE ROTATION MATRIX FOR R_{Z}(-\THETA)
         RM(1,1) = COST
         RM(2,2) = COST
         RM(3,3) = 1.D0
         RM(1,2) = SINT
         RM(2,1) =-SINT

         CALL QROTMAT(Q2,RM)

         DO I = 1, NSIZE
            IF (DIST(I) /= 0.0D0) THEN
               J = 3*I
               T1S(J-2:J) = MATMUL(RM(:,:),T1S(J-2:J))
            ENDIF  
         ENDDO

      ENDIF

      IF (ROTT) THEN

         IF (EFIELDT) THEN
            Q1(1:4) = Q2(1:4)
         ELSE
!            ROTM(:,:) = MATMUL(RM(:,:),ROTM(:,:))
            CALL QROTQ(Q2,Q1)
         ENDIF

      ELSE

         PROJ = 0.D0

         DO I = 1, NSIZE

            J = 3*I
            IF (T1S(J) > 1.0D-2) PROJ = PROJ + T1S(J-2)

         ENDDO

      ENDIF

      END SUBROUTINE RBSITESROTXZ

!     ----------------------------------------------------------------------------------------------

      SUBROUTINE INVMTRX(S, SINV)
!     INVERTS A 3X3 MATRIX S

      IMPLICIT NONE

      DOUBLE PRECISION   :: S(3,3), SINV(3,3), A(3,3), DET

!     ADJOINT

      A(1,1) = S(2,2)*S(3,3) - S(2,3)*S(3,2)
      A(1,2) = S(1,3)*S(3,2) - S(1,2)*S(3,3)
      A(1,3) = S(1,2)*S(2,3) - S(1,3)*S(2,2)
      A(2,1) = S(3,1)*S(2,3) - S(2,1)*S(3,3)
      A(2,2) = S(1,1)*S(3,3) - S(1,3)*S(3,1)
      A(2,3) = S(1,3)*S(2,1) - S(1,1)*S(2,3)
      A(3,1) = S(2,1)*S(3,2) - S(3,1)*S(2,2)
      A(3,2) = S(1,2)*S(3,1) - S(1,1)*S(3,2)
      A(3,3) = S(1,1)*S(2,2) - S(1,2)*S(2,1)

      DET    =  S(1,1)* A(1,1) + S(1,2) * A(2,1) + S(1,3) * A(3,1)

      SINV(:,:) = A(:,:)/DET

      END SUBROUTINE INVMTRX

!     ----------------------------------------------------------------------------------------------

      SUBROUTINE RBROT(T, X, Q2, NATOMS)
!     TAKES THE SET OF RIGID-BODY COORDINATES T AND RETURNS X AFTER ROTATION VIA THE QUATERNION Q2 
!     ABOUT THE ORIGIN

      IMPLICIT NONE

      INTEGER          :: I, J, NATOMS
      DOUBLE PRECISION :: T(3*NATOMS), X(3*NATOMS), T1(1:3), Q2(4), P(3), RM(3,3) 
      DOUBLE PRECISION :: CMX, CMY, CMZ
!
!     MOVE CENTRE OF MASS TO THE ORIGIN.
!
      CMX = 0.D0; CMY = 0.D0; CMZ = 0.D0
      DO I = 1, NATOMS/2
         J = 3*I
         CMX = CMX + T(J-2)
         CMY = CMY + T(J-1)
         CMZ = CMZ + T(J)
      ENDDO
      CMX = 2*CMX/NATOMS; CMY = 2*CMY/NATOMS; CMZ = 2*CMZ/NATOMS
      DO I = 1, NATOMS/2
         J      = 3*I
         X(J-2) = T(J-2) - CMX
         X(J-1) = T(J-1) - CMY
         X(J)   = T(J)   - CMZ
      ENDDO

!     EXTRACT THE ROTATION MATRIX CORRESPONDING TO ROTATION VIA Q

      CALL QROTMAT(Q2,RM)

!      PRINT *, 'RM'
!      PRINT *, RM

      DO I = 1, NATOMS/2

         J        = 3*I
         T1(1:3)  = MATMUL(RM(:,:), X(J-2:J))
         X(J-2:J) = T1(1:3)  
!     CONVERT THE ANGLE-AXIS COORDINATES

         J        = 3*NATOMS/2 + J
         P(:)     = T(J-2:J)
         CALL QROTAA(Q2,P)
         X(J-2:J) = P(1:3)

      ENDDO

      END SUBROUTINE RBROT

!     ----------------------------------------------------------------------------------------------

      SUBROUTINE QROTAA(Q2,P)

!     TRANSFORMS THE ANGLE-AXIS VARIABLES P CORRESPONDING TO ROTATION VIA QUATERNION Q2 AND RETURNS 
!     THE TRANSFORMED VARIABLES IN P

      IMPLICIT NONE

      DOUBLE PRECISION :: Q(4), Q1(4), Q2(4), P(3), THETA, THETAH, ST, FCT

      THETA   = DSQRT(DOT_PRODUCT(P,P))
      THETAH  = 0.5D0*THETA
      ST      = SIN(THETAH)
      Q1(1)   = COS(THETAH)
      Q1(2:4) = P(:)*ST/THETA

      Q(1)   = Q2(1)*Q1(1) - Q2(2)*Q1(2) - Q2(3)*Q1(3) - Q2(4)*Q1(4)
      Q(2)   = Q2(1)*Q1(2) + Q2(2)*Q1(1) + Q2(3)*Q1(4) - Q2(4)*Q1(3)
      Q(3)   = Q2(1)*Q1(3) + Q2(3)*Q1(1) + Q2(4)*Q1(2) - Q2(2)*Q1(4)
      Q(4)   = Q2(1)*Q1(4) + Q2(4)*Q1(1) + Q2(2)*Q1(3) - Q2(3)*Q1(2)

      THETA  = 2.D0*ACOS(Q(1))

      IF (THETA == 0.D0) THEN
         P (1:3) = 0.D0
      ELSE
         FCT = DSQRT(DOT_PRODUCT(Q(2:4),Q(2:4)))
         P(1:3) = THETA*Q(2:4)/FCT
      ENDIF

      END SUBROUTINE

!     ----------------------------------------------------------------------------------------------

      SUBROUTINE QROTQ(Q2,Q1)

!     TRANSFORMS THE QUATERNION Q1 CORRESPONDING TO ROTATION VIA QUATERNION Q2 AND RETURNS THE
!     TRANSFORMED VARIABLES IN Q1

      IMPLICIT NONE

      DOUBLE PRECISION :: Q(4), Q1(4), Q2(4)

      Q(1)   = Q2(1)*Q1(1) - Q2(2)*Q1(2) - Q2(3)*Q1(3) - Q2(4)*Q1(4)
      Q(2)   = Q2(1)*Q1(2) + Q2(2)*Q1(1) + Q2(3)*Q1(4) - Q2(4)*Q1(3)
      Q(3)   = Q2(1)*Q1(3) + Q2(3)*Q1(1) + Q2(4)*Q1(2) - Q2(2)*Q1(4)
      Q(4)   = Q2(1)*Q1(4) + Q2(4)*Q1(1) + Q2(2)*Q1(3) - Q2(3)*Q1(2)

      Q1(1:4) = Q(1:4)

      END SUBROUTINE

!     ----------------------------------------------------------------------------------------------

      SUBROUTINE QROTMAT(Q,RM)

!     PROVIDES THE ROTATION MATRIX RM CORRESPONDING TO QUATERNION Q
!     RIGHT-HANDED ROTATION IN THE RIGHT-HANDED COORDINATE SYSTEM

      IMPLICIT NONE

      DOUBLE PRECISION :: Q(4), RM(3,3)

      RM(1,1) = Q(1)**2 + Q(2)**2 - Q(3)**2 - Q(4)**2
      RM(1,2) = 2.D0*(Q(2)*Q(3) - Q(1)*Q(4))
      RM(1,3) = 2.D0*(Q(2)*Q(4) + Q(1)*Q(3))
      RM(2,1) = 2.D0*(Q(2)*Q(3) + Q(1)*Q(4))
      RM(2,2) = Q(1)**2 + Q(3)**2 - Q(2)**2 - Q(4)**2
      RM(2,3) = 2.D0*(Q(3)*Q(4) - Q(1)*Q(2))
      RM(3,1) = 2.D0*(Q(2)*Q(4) - Q(1)*Q(3))
      RM(3,2) = 2.D0*(Q(3)*Q(4) + Q(1)*Q(2))
      RM(3,3) = Q(1)**2 + Q(4)**2 - Q(2)**2 - Q(3)**2

      END SUBROUTINE

!     ----------------------------------------------------------------------------------------------

      SUBROUTINE RBORIENT(X, T1, NORBIT1, NCHOOSE1, NORBIT2, NCHOOSE2, NATOMS, Q2, DEBUG)
      
      USE KEY, ONLY : EFIELDT 
!                        
!     THIS SUBROUTINE PUTS PERMUTATIONAL ISOMERS OF A RIGID-BODY SYSTEM INTO A STANDARD ORIENTATION.
!
      IMPLICIT NONE
      INTEGER          :: NATOMS, I, J, J1, J2, JMAX1, JMAX2, NORBIT1, NCHOOSE1, NORBIT2, NCHOOSE2, OFFSET
      DOUBLE PRECISION :: X(3*NATOMS), DIST(NATOMS), T1(3*NATOMS), T2(3*NATOMS)
      DOUBLE PRECISION :: RM(3,3), AX(3), P(3), Q1(4), Q2(4), Q(4), ROTM(3,3), ROTMINV(3,3)
      DOUBLE PRECISION :: THETA, THETAH, COST, SINT, COSTH, SINTH, ST, FCT
      DOUBLE PRECISION :: CMX, CMY, CMZ, DMAX, DUMMY, PROJ, DMAX2, CUTOFF1, DTEMP
      LOGICAL          :: DEBUG

      OFFSET  = 3*NATOMS/2
      CUTOFF1 = 1.D-03
!
!     MOVE CENTRE OF MASS TO THE ORIGIN.
!
      CMX = 0.D0; CMY = 0.D0; CMZ = 0.D0
      DO I = 1, NATOMS/2
         J = 3*I
         CMX = CMX + X(J-2)
         CMY = CMY + X(J-1)
         CMZ = CMZ + X(J)
      ENDDO

      CMX = 2*CMX/NATOMS; CMY = 2*CMY/NATOMS; CMZ = 2*CMZ/NATOMS
      DO I = 1, NATOMS/2
         J = 3*I
         X(J-2) = X(J-2) - CMX
         X(J-1) = X(J-1) - CMY
         X(J)   = X(J)   - CMZ
      ENDDO

      DMAX    = -1.D0
      NORBIT1 = 1

      IF (EFIELDT) THEN

         T1(:) = X(:)
         GOTO 100

      ENDIF
!
!     FIND THE RB WHICH IS AT THE LARGEST DISTANCE FROM THE CENTRE OF MASS
!
      DO J1 = 1, NATOMS/2

         J = 3*J1
         DIST(J1) = SQRT(X(J-2)**2 + X(J-1)**2 + X(J)**2)

         IF (ABS(DIST(J1) - DMAX) < CUTOFF1) THEN

            NORBIT1 = NORBIT1 + 1
            IF (NORBIT1 == NCHOOSE1) JMAX1 = J1

         ELSE IF (DIST(J1) > DMAX) THEN

            DMAX = DIST(J1)
            NORBIT1 = 1
            JMAX1 = J1

         ENDIF

      ENDDO

!     FOR TAGGED RBS, THE CHOICE OF THE FIRST RB MATTERS IF IT BELONGS TO AN ORBIT OF SIZE > 1.
!
      IF ((ABS(X(3*JMAX1-2)) < 1.D-08) .AND. (ABS(X(3*JMAX1-1)) < 1.D-08)) THEN 
!
!     RB JMAX1 IS ALREADY ON THE Z AXIS!
!
         IF (X(3*(JMAX1-1)+3) > 0.D0) THEN

            T1(1:3*NATOMS) = X(1:3*NATOMS)
            Q2(1:4) = (/1.D0, 0.D0, 0.D0, 0.D0/)
 
         ELSE  ! ROTATE ABOUT THE X-AXIS BY \PI, DO NOT INVERT!

            Q2(1:4) = (/0.D0, 1.D0, 0.D0, 0.D0/)

            DO J1 = 1, NATOMS/2
               J       = 3*J1
               T1(J-2) = X(J-2)
               T1(J-1) =-X(J-1)
               T1(J)   =-X(J)
            ENDDO

         ENDIF

      ELSE
!
!     ROTATE ALL RB'S THROUGH AN ANGLE THETA ABOUT THE AXIS P(:), SO AS TO ROTATE THE RB JMAX1 ONTO THE Z AXIS 
!
!     FOR SLOPPY CUTOFFS WE CANNOT ASSUME THAT DMAX IS EXACTLY THE SAME FOR MEMBERS OF THE SAME ORBIT!

        THETA = DACOS(X(3*JMAX1)/DIST(JMAX1))

!     THE AXIS IS ON THE XY-PLANE AND PERPENDICULAR TO THE PROJECTION OF THE TRANSLATION VECTOR OF THE RB JMAX1
!     ON THE XY-PLANE. THE AXIS IS SO CHOSEN THAT A RIGHT-HANDED ROTATION IN THE RIGHT-HANDED COORDINATE SYSTEM
!     WILL RESULT IN THE REQUIRED TRANSFORMATION.

         AX(3) = 0.D0
         FCT   = DSQRT(X(3*JMAX1-2)**2 + X(3*JMAX1-1)**2)
         AX(1) = THETA*X(3*JMAX1-1)/FCT
         AX(2) =-THETA*X(3*JMAX1-2)/FCT

         CALL ROTMAT(AX(:), ROTM(:,:))

         THETAH  = 0.5D0*THETA
         AX(1:3) = AX(1:3)/SQRT(DOT_PRODUCT(AX(1:3),AX(1:3)))
         Q2(1:4) = (/COS(THETAH), SIN(THETAH)*AX(1:3)/)          ! THE CORRESPONDING QUATERNION

         CALL RBROT(X, T1, Q2, NATOMS)

      ENDIF

!
!     NOW FIND THE RB WITH THE LARGEST DISTANCE FROM THE Z-AXIS 
!
100   DMAX = -1.0D0

      DO J1 = 1, NATOMS/2

         J2 = 3*J1 
         DIST(J1) = SQRT(T1(J2-2)**2 + T1(J2-1)**2)
         IF (DIST(J1) > DMAX) DMAX = DIST(J1)
         
      ENDDO

      DMAX2 = -1.0D100
!
!     PROJ IS THE SUM OF THE X COMPONENTS. USE T2 AS A DUMMY IN ORDER NOT TO 
!     CHANGE T1 UNTIL WE HAVE DECIDED WHICH ATOM TO PUT IN THE XZ PLANE.
!
      DO J1 = 1, NATOMS/2

         IF (ABS(DIST(J1) - DMAX) < CUTOFF1) THEN

            T2(1:3*NATOMS) = T1(1:3*NATOMS)
            CALL RBROTXZ(NATOMS, J1, T2, PROJ, DIST, Q2, .FALSE.)

            IF (ABS(PROJ - DMAX2) < CUTOFF1) THEN
               NORBIT2 = NORBIT2+1
               IF (NORBIT2 == NCHOOSE2) THEN
                  JMAX2 = J1
                  DTEMP = PROJ
               ENDIF
            ELSE IF (PROJ > DMAX2) THEN
               NORBIT2 = 1
               DMAX2   = PROJ
               DTEMP   = PROJ
               JMAX2   = J1
            ENDIF

         ENDIF

      ENDDO
!
!     AND NOW ROTATE IT INTO THE XZ PLANE.
!
!      CALL RBROTXZ(NATOMS, JMAX2, T1, DMAX2, DIST, ROTM, .TRUE.)

      CALL RBROTXZ(NATOMS, JMAX2, T1, DTEMP, DIST, Q2, .TRUE.)

!      CALL INVMTRX(ROTM(:,:), ROTMINV(:,:))

!      EFIELDT = .TRUE.
      END SUBROUTINE RBORIENT

!     ----------------------------------------------------------------------------------------------

      SUBROUTINE RBROTXZ(NATOMS, JDO, T1, PROJ, DIST, Q1, ROTT)

      USE KEY, ONLY : EFIELDT

      IMPLICIT NONE
      INTEGER          :: NATOMS, JDO, I, J, J2, OFFSET
      DOUBLE PRECISION :: T1(3*NATOMS), X(3*NATOMS), PROJ, DIST(NATOMS/2), THETA, THETAH, COST, SINT, ST
      DOUBLE PRECISION :: COSTH, SINTH, FCT, P(3), Q2(4), Q1(4), RM(3,3), ROTM(3,3), CMX, CMY, CMZ
      LOGICAL          :: ROTT

      J2     = 3*JDO
      OFFSET = 3*NATOMS/2

      X(1:3*NATOMS) = T1(1:3*NATOMS)

      IF (ABS(T1(J2-1)) < 1.0D-8) THEN            ! ALREADY ON THE XZ PLANE

         RM(:,:) = 0.D0
         RM(1,1) = 1.D0; RM(2,2) = 1.D0; RM(3,3) = 1.D0
         Q2(1:4) = (/1.D0, 0.D0, 0.D0, 0.D0/)

         IF (T1(J2-2) < 0.D0) THEN                ! ROTATE ABOUT THE Z AXIS BY \PI, DO NOT INVERT!!

            P(:) = (/0.D0, 0.D0, 4.D0*DATAN(1.D0)/)
            CALL ROTMAT(P(:), RM(:,:))
            Q2(1:4) = (/0.D0, 0.D0, 0.D0, 1.D0/)

            DO I = 1, NATOMS/2
               J = 3*I
               X(J-2) = -T1(J-2)
               X(J-1) = -T1(J-1)
            ENDDO

         ENDIF

      ELSE

         COST   = T1(J2-2)/DIST(JDO)
         SINT   = T1(J2-1)/DIST(JDO)
         THETA  =-ATAN2(SINT,COST)              ! THE NEGATIVE SIGN APPEARS AS THE ROTATION IS REVERSED
         THETAH = 0.5D0*THETA
         Q2(1:4) = (/COS(THETAH), 0.D0, 0.D0, SIN(THETAH)/)
         RM(:,:) = 0.D0                           ! THE ROTATION MATRIX FOR R_{Z}(-\THETA)
         RM(1,1) = COST
         RM(2,2) = COST
         RM(3,3) = 1.D0
         RM(1,2) = SINT
         RM(2,1) =-SINT

         DO I = 1, NATOMS/2
            IF (DIST(I) /= 0.0D0) THEN
               J = 3*I
               X(J-2:J) = MATMUL(RM(:,:),T1(J-2:J))
            ENDIF
         ENDDO

      ENDIF

      IF (ROTT) THEN

         IF (EFIELDT) THEN
            ROTM(:,:) = RM(:,:)
         ELSE
!            ROTM(:,:) = MATMUL(RM(:,:),ROTM(:,:))
!            CALL QROTQ(Q2,Q1)
         ENDIF

!     NOW CHANGE THE ANGLE-AXIS COORDINATES VIA QUATERNION MULTIPLICATION EQUIVALENT TO ROTATION BY ROTM

         CALL RBROT(T1, X, Q2, NATOMS)
!         T1(3*NATOMS/2+1:3*NATOMS) = X(3*NATOMS/2+1:3*NATOMS)
         T1(1:3*NATOMS) = X(1:3*NATOMS)

      ELSE

         PROJ = 0.D0
         DO I = 1, NATOMS/2
            J = 3*I
            IF (X(J) > 1.0D-2) PROJ = PROJ + X(J-2)
         ENDDO

      ENDIF

      T1(1:3*NATOMS) = X(1:3*NATOMS)

      END SUBROUTINE RBROTXZ

!     ----------------------------------------------------------------------------------------------

      SUBROUTINE RBFRAME(C,XS,Q)

      USE COMMONS, ONLY: NATOMS, NRBSITES
      USE KEY, ONLY    : DBPTDT, NTIPT, MSSTOCKT, PAHAT, PATCHYDT, NTSITES, NCARBON

      IMPLICIT NONE
      
      INTEGER :: J1, J2, J3
      DOUBLE PRECISION :: XS(3*NTSITES)
      CHARACTER(LEN=132),INTENT(IN) :: C
      DOUBLE PRECISION :: Q(3*NATOMS)

      IF (DBPTDT) THEN
         WRITE(55,'(I6)') (NATOMS/2-1)*NRBSITES + 4
         WRITE(55,'(1X,A)') TRIM(ADJUSTL(C))
         IF (J1 < NATOMS/2) THEN
            DO J2 = 1, NRBSITES - 1
               J3 = ((J1-1)*NRBSITES + (J2-1))*3
               IF (J2 == 1) THEN
                  WRITE(55,'(A5,1X,3F20.10)') 'O ', XS(J3+1), XS(J3+2), XS(J3+3)
               ELSE
                  WRITE(55,'(A5,1X,3F20.10)') 'C ', XS(J3+1), XS(J3+2), XS(J3+3)
               ENDIF
            ENDDO
         ELSE
            DO J2 = 1, 4
               J3          = ((J1-1)*NRBSITES + (J2-1))*3
               IF (J2 == 1) THEN
                  WRITE(55,'(A5,1X,3F20.10)') 'H ', XS(J3+1), XS(J3+2), XS(J3+3)
               ELSEIF (J2 == 2) THEN
                  WRITE(55,'(A5,1X,3F20.10)') 'N ', XS(J3+1), XS(J3+2), XS(J3+3)
               ELSEIF (J2 == 3) THEN
                  WRITE(55,'(A5,1X,3F20.10)') 'B ', XS(J3+1), XS(J3+2), XS(J3+3)
               ELSE
                  WRITE(55,'(A5,1X,3F20.10)') 'S ', XS(J3+1), XS(J3+2), XS(J3+3)
               ENDIF
            ENDDO
         ENDIF

      ELSEIF (NTIPT) THEN

         WRITE(55,'(I6)') (NATOMS/2)*(NRBSITES-1)
         WRITE(55,'(1X,A)') TRIM(ADJUSTL(C))
         DO J1 = 1, NATOMS/2
            J2 = 4*(J1-1)*3 
            WRITE(55,'(A5,1X,3F20.10)') 'O ', XS(J2+1), XS(J2+2), XS(J2+3)
            WRITE(55,'(A5,1X,3F20.10)') 'H ', XS(J2+4), XS(J2+5), XS(J2+6)
            WRITE(55,'(A5,1X,3F20.10)') 'H ', XS(J2+7), XS(J2+8), XS(J2+9)
         ENDDO

      ELSEIF (MSSTOCKT) THEN

         WRITE(55,'(I6)') (NATOMS/2)*NRBSITES
         WRITE(55,'(1X,A)') TRIM(ADJUSTL(C))
         DO J1 = 1, NATOMS/2
            DO J2 = 1, NRBSITES
               J3 = ((J1-1)*NRBSITES + (J2-1))*3
               WRITE(55,'(A5,1X,3F20.10)') 'O ', XS(J3+1), XS(J3+2), XS(J3+3)
            ENDDO
         ENDDO

      ELSEIF (PAHAT) THEN 

         WRITE(55,'(I6)') (NATOMS/2)*NRBSITES
         WRITE(55,'(1X,A)') TRIM(ADJUSTL(C))
         DO J1 = 1, NATOMS/2
            DO J2 = 1, NRBSITES
               J3 = ((J1-1)*NRBSITES + (J2-1))*3
               IF (J2 <= NCARBON) THEN
                  WRITE(55,'(A5,1X,3F20.10)') 'C ', XS(J3+1), XS(J3+2), XS(J3+3)
               ELSE
                  WRITE(55,'(A5,1X,3F20.10)') 'H ', XS(J3+1), XS(J3+2), XS(J3+3)
               ENDIF
            ENDDO
         ENDDO

      ELSEIF (PATCHYDT) THEN

         WRITE(55,'(I6)') (NATOMS/2)*(NRBSITES+1)
         WRITE(55,'(1X,A)') TRIM(ADJUSTL(C))
         DO J1 = 1, NATOMS/2
            J3 = (J1-1)*3
            WRITE(55,'(A5,1X,3F20.10)') 'O ', Q(J3+1), Q(J3+2), Q(J3+3)
            DO J2 = 1, NRBSITES 
               J3 = ((J1-1)*NRBSITES + (J2-1))*3
               WRITE(55,'(A5,1X,3F20.10)') 'H ', XS(J3+1), XS(J3+2), XS(J3+3)
            ENDDO
         ENDDO

      ENDIF

      END SUBROUTINE RBFRAME

!     ----------------------------------------------------------------------------------------------

      SUBROUTINE RBROTMAT(T, X, ROTMAT, NTSITES)
!     TAKES THE SET OF RIGID-BODY COORDINATES T AND RETURNS X AFTER ROTATION VIA THE QUATERNION Q2
!     ABOUT THE ORIGIN

      IMPLICIT NONE

      INTEGER          :: I, J, NTSITES
      DOUBLE PRECISION :: T(3*NTSITES), X(3*NTSITES), T1(1:3), Q2(4), ROTMAT(3,3)
      DOUBLE PRECISION :: CMX, CMY, CMZ
!
!     MOVE CENTRE OF MASS TO THE ORIGIN.
!
      CMX = 0.D0; CMY = 0.D0; CMZ = 0.D0
      DO I = 1, NTSITES
         J = 3*I
         CMX = CMX + T(J-2)
         CMY = CMY + T(J-1)
         CMZ = CMZ + T(J)
      ENDDO
      CMX = CMX/NTSITES; CMY = CMY/NTSITES; CMZ = CMZ/NTSITES
      DO I = 1, NTSITES
         J      = 3*I
         X(J-2) = T(J-2) - CMX
         X(J-1) = T(J-1) - CMY
         X(J)   = T(J)   - CMZ
      ENDDO

!     EXTRACT THE ROTATION MATRIX CORRESPONDING TO ROTATION VIA Q

!      CALL QROTMAT(Q2,RM)

      DO I = 1, NTSITES

         J        = 3*I
         T1(1:3)  = MATMUL(ROTMAT(:,:), X(J-2:J))
         X(J-2:J) = T1(1:3)

      ENDDO

      END SUBROUTINE RBROTMAT

