C   OPTIM: A PROGRAM FOR OPTIMIZING GEOMETRIES AND CALCULATING REACTION PATHWAYS
C   COPYRIGHT (C) 1999-2006 DAVID J. WALES
C   THIS FILE IS PART OF OPTIM.
C
C   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C   (AT YOUR OPTION) ANY LATER VERSION.
C
C   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
C   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
C   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
C   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
C
      SUBROUTINE SECDIAG(VEC,COORDS,ENERGY,GL,DIAG,GTEST,XRMS)
      USE COMMONS
      USE KEY
      USE MODCHARMM
      USE PORFUNCS
      IMPLICIT NONE
      INTEGER J1
      LOGICAL GTEST, FPLUS, FMINUS
      DOUBLE PRECISION DUMMY3(3*NATOMS), DIFF, VEC(3*NATOMS), COORDS(3*NATOMS), DIAG2, DIAG3,
     1                 EPLUS,EMINUS,ENERGY,GRAD1(3*NATOMS),LOCALV(3*NATOMS),
     2                 RMS,DIAG,XRMS,GL(3*NATOMS),GRAD2(3*NATOMS), VECL, ZETA, PROJ

      DIFF=1.0D-3
      IF (AMHT) DIFF=1.0D-2
      IF (ZSYM(NATOMS).EQ.'GO') DIFF=2.0D-3
      IF (GAMESSUK.OR.GAMESSUS) DIFF=1.0D-2
      IF (CADPAC) DIFF=1.0D-2
      IF (CASTEP) DIFF=0.01D0
      IF (ONETEP) DIFF=0.01D0
      IF (CP2K) DIFF=0.001D0 
      IF (CPMD) DIFF=0.04D0
C     IF (CHRMMT) DIFF=5.0D-2
      IF (CHRMMT) DIFF=0.01D0
C     IF (DFTBT) DIFF=1.0D-3
C
C  MUST READ VEC INTO LOCALV BECAUSE WE ARE GOING TO PLAY WITH THE VECTOR IN
C  QUESTION. THIS WOULD MESS UP CASES WHERE WE NEED TO RETRY WITH A SMALLER
C  STEP SIZE, BECAUSE WE CANNOT UNDO THE PREVIOUS STEP CLEANLY IF THE MAGNITUDE
C  OF VEC IS CHANGED! 1/7/04 DJW
C
      LOCALV(1:NOPT)=VEC(1:NOPT)
C     PRINT '(A)','SECDIAG> VEC BEFORE ORTHOGOPT'
C     PRINT '(6G20.10)',LOCALV(1:NOPT)
      IF (NFREEZE.LT.3) THEN
        CALL ORTHOGOPT(LOCALV,COORDS,.TRUE.)
      ELSE
         CALL VECNORM(LOCALV,NOPT)
      ENDIF
C     PRINT '(A)','SECDIAG> VEC AFTER ORTHOGOPT'
C     PRINT '(6G20.10)',LOCALV(1:NOPT)

      IF (FREEZE) THEN
         DO J1=1,NATOMS
            IF (FROZEN(J1)) THEN
               LOCALV(3*(J1-1)+1)=0.0D0
               LOCALV(3*(J1-1)+2)=0.0D0
               LOCALV(3*(J1-1)+3)=0.0D0
            ENDIF
         ENDDO
      ENDIF

      VECL=1.0D0
      ZETA=DIFF

      DO J1=1,NOPT
         DUMMY3(J1)=COORDS(J1)+ZETA*LOCALV(J1)
      ENDDO
      IF (CPMD) THEN
         INQUIRE(FILE='RESTART.1.PLUS',EXIST=FPLUS)
         IF (FPLUS) THEN
            CALL SYSTEM(' CP RESTART.1.PLUS RESTART.1 ')
         ELSE
            CALL SYSTEM(' CP RESTART.1.SAVE RESTART.1 ')
         ENDIF
      ELSE IF (CASTEP) THEN
C        INQUIRE(FILE=SYS(1:LSYS) // '.WVFN.PLUS',EXIST=FPLUS)
C        IF (FPLUS) THEN
C           CALL SYSTEM(' CP ' // SYS(1:LSYS) // '.WVFN.PLUS ' // SYS(1:LSYS) // '.WVFN.1 ')
C        ELSE
C           CALL SYSTEM(' CP ' // SYS(1:LSYS) // '.WVFN.SAVE ' // SYS(1:LSYS) // '.WVFN.1 ')
C        ENDIF
      ENDIF
C     PRINT*,'DUMMY3:'
      CALL POTENTIAL(DUMMY3,EPLUS,GRAD1,GTEST,.FALSE.,RMS,.FALSE.,.FALSE.)
      IF (CPMD) CALL SYSTEM(' CP RESTART.1 RESTART.1.PLUS ')
C     IF (CASTEP) CALL SYSTEM(' CP ' // SYS(1:LSYS) // '.WVFN.1 ' // SYS(1:LSYS) // '.WVFN.PLUS ')
      DO J1=1,NOPT
         DUMMY3(J1)=COORDS(J1)-ZETA*LOCALV(J1)
      ENDDO
      IF (CPMD) THEN
         INQUIRE(FILE='RESTART.1.MINUS',EXIST=FMINUS)
         IF (FMINUS) THEN
            CALL SYSTEM(' CP RESTART.1.MINUS RESTART.1 ')
         ELSE
            CALL SYSTEM(' CP RESTART.1.SAVE RESTART.1 ')
         ENDIF
      ELSE IF (CASTEP) THEN
C        INQUIRE(FILE=SYS(1:LSYS) // '.WVFN.MINUS',EXIST=FMINUS)
C        IF (FMINUS) THEN
C           CALL SYSTEM(' CP ' // SYS(1:LSYS) // '.WVFN.MINUS ' // SYS(1:LSYS) // '.WVFN.1 ')
C        ELSE
C           CALL SYSTEM(' CP ' // SYS(1:LSYS) // '.WVFN.SAVE ' // SYS(1:LSYS) // '.WVFN.1 ')
C        ENDIF
      ENDIF
C     PRINT*,'DUMMY3:'
      CALL POTENTIAL(DUMMY3,EMINUS,GRAD2,GTEST,.FALSE.,RMS,.FALSE.,.FALSE.)
      IF (CPMD) CALL SYSTEM(' CP RESTART.1 RESTART.1.MINUS ')
C     IF (CASTEP) CALL SYSTEM(' CP ' // SYS(1:LSYS) // '.WVFN.1 ' // SYS(1:LSYS) // '.WVFN.MINUS ')
      DIAG=(EPLUS+EMINUS-2.0D0*ENERGY)/(ZETA**2*VECL)
C     IF (DEBUG) WRITE(*,'(A,G15.5)') 'SECDIAG> DIFF',ZETA

      DIAG2=0.0D0
      DO J1=1,NOPT
         DIAG2=DIAG2+(GRAD1(J1)-GRAD2(J1))*LOCALV(J1)
C        WRITE(*,'(A,I4,4F20.10)') 'J1,GRAD1,GRAD2,LOCALV,DIAG2=',J1,GRAD1(J1),GRAD2(J1),LOCALV(J1),DIAG2
      ENDDO
      DIAG2=DIAG2/(2.0D0*ZETA)
      DIAG3=2*(DIAG-DIAG2/2)
C     IF (.NOT.GTEST) WRITE(*,'(A,6F20.10)') 'D,D2,D3,E+,E-,E=',DIAG,DIAG2,DIAG3,EPLUS,EMINUS,ENERGY
C
C  ALTHOUGH DIAG3 IS A MORE ACCURATE ESTIMATE OF THE DIAGONAL SECOND DERIVATIVE, IT
C  CANNOT BE DIFFERENTIATED ANALYTICALLY.
C
      IF (GTEST) THEN
         DO J1=1,NOPT
            IF (NSECDIAG.EQ.2) THEN
               GL(J1)=(GRAD1(J1)-GRAD2(J1))/(ZETA*VECL**2)-2.0D0*DIAG2*LOCALV(J1)/VECL**2
            ELSE
               GL(J1)=(GRAD1(J1)-GRAD2(J1))/(ZETA*VECL**2)-2.0D0*DIAG*LOCALV(J1)/VECL**2
            ENDIF
!           WRITE(*,'(A,I4,4G16.7)') 'SECDIAG> J1,GRAD1,GRAD2,LOCALV,GL=',J1,GRAD1(J1),GRAD2(J1),LOCALV(J1),GL(J1)
         ENDDO
         IF (NFREEZE.LT.3) CALL ORTHOGOPT(GL,COORDS,.FALSE.)
C        PRINT *,'SECDIAG> BEFORE PROJ STUFF GL:'
C        PRINT '(3F20.10)',GL(1:NOPT)
C        CALL ORTHOGOPT(GL,COORDS,.FALSE.) ! SEEMS TO DO SOME GOOD FOR MSEVB
C
C  PROJECT OUT ANY COMPONENT OF THE GRADIENT ALONG LOCALV (WHICH IS A UNIT VECTOR)
C  THIS IS A BIG IMPROVEMENT FOR DFTB.
C
         PROJ=0.0D0
         DO J1=1,NOPT
            PROJ=PROJ+GL(J1)*LOCALV(J1)
         ENDDO
         DO J1=1,NOPT
            GL(J1)=GL(J1)-PROJ*LOCALV(J1)
         ENDDO
         XRMS=0.0D0
         DO J1=1,NOPT
            XRMS=XRMS+GL(J1)**2
         ENDDO
         XRMS=DSQRT(XRMS/NOPT)
!        PRINT *,'SECDIAG> AFTER PROJ STUFF GL:'
!        PRINT '(3F20.10)',GL(1:NOPT)

         IF (DEBUG) WRITE(*,'(A,3G15.5,3G20.12,G10.3)') 'D,D2,D3,E+,E-,E,RMS=',DIAG,DIAG2,DIAG3,EPLUS,EMINUS,ENERGY,XRMS
         IF (DEBUG) WRITE(*,'(A,G20.10)') 'PREDICTED GRADIENT COMPONENT=',(EPLUS-EMINUS)/(2*ZETA)
      ENDIF
!     PRINT '(A)','LOCALV:'
!     PRINT '(3G20.10)',LOCALV(1:NOPT)

      IF (NSECDIAG.EQ.2) DIAG=DIAG2

      RETURN
      END
