C
C GPL LICENSE INFO {{{
C   OPTIM: A PROGRAM FOR OPTIMIZING GEOMETRIES AND CALCULATING REACTION PATHWAYS
C   COPYRIGHT (C) 1999-2006 DAVID J. WALES
C   THIS FILE IS PART OF OPTIM.
C
C   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
C   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
C   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
C   (AT YOUR OPTION) ANY LATER VERSION.
C
C   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
C   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
C   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
C   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
C
C   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
C   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
C   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
C
C }}}
C
C     SORTS VECTOR OF NUCLEAR COORDINATES - TO CHECK FOR EQUIVALENCE
C     OF TWO ORIENTATIONS - NEEDS Q VECTOR AND ATOMIC MASS VECTOR (ATMAS
C
      SUBROUTINE SORTXYZ(XX,Y,NORD,TOL)
! DOXYGEN {{{
!> \NAME SORTXYZ
!> \BRIEF SORT VECTOR OF NUCLEAR COORDINATES 
!> \PARAM[IN] XX DP(3*NATOMS)  - INPUT VECTOR TO BE SORTED
!> \PARAM Y  DP(3*NATOMS)      - OUTPUT SORTED VECTOR
!> \PARAM NORD INT(2*NATOMS+1) - VECTOR CONTAINING PERMUTATIONS 
!> \PARAM TOL DP - TOLERANCE FACTOR
! }}}
! DECLARATIONS {{{ 
      USE COMMONS
      IMPLICIT NONE
! SUBROUTINE PARAMETERS  
      DOUBLE PRECISION XX(3*NATOMS),Y(3*NATOMS),TOL
      INTEGER NORD(2*NATOMS+1)
! LOCAL PARAMETERS 
!      DOUBLE PRECISION X(3*NATOMS),XX(*),Y(*),TOL
!      INTEGER I, J, JK, NORD(NATOMS), ILINE
      DOUBLE PRECISION X(3*NATOMS)
      INTEGER I, J, JK, ILINE
! }}}
! SUBROUTINE BODY {{{
C
      ILINE(J)=1+J/3
C
C     SORT ON THE X - IF TWO X'S ARE EQUIVALENT, SORT ON Y AND SO ON.
C     IF THE COORDINATE < THE TOLERANCE WE SHOULD IGNORE IT! HOWEVER,
C     IF THE TOLERANCE IS SLOPPY THAT CAN LEAD TO THE SORTING IGNORING
C     GENUINE SMALL DIFFERENCES BETWEEN COORDINATES. SIGH. 
C
      DO I=1,3*NATOMS
         X(I)=XX(I)
      ENDDO
C
C     FIRST GIVE DUMMY ATOMS RIDICULOUS SCRATCH COORDINATES - ENSURES
C     THAT THEY WILL WIND UP AT THE BOTTOM OF THE LIST
C
      DO I=1,3*NATOMS-2,3
         IF (DABS(ATMASS(ILINE(I))).LT.1D-3) THEN
            DO J=0,2
               X(J+I) = -99995.0D0
            ENDDO
         ENDIF
      ENDDO
      JK=1
40    J=1
      DO I=1,3*NATOMS-2,3
         IF (X(I)-X(J).GT.TOL) J=I
         IF (DABS(X(I)-X(J)).LT.TOL) THEN
            IF (X(I+1)-X(J+1).GT.TOL) J=I
            IF (DABS(X(I+1)-X(J+1)).LT.TOL) THEN
               IF (X(I+2)-X(J+2).GT.TOL) J=I
            ENDIF
         ENDIF
      ENDDO
C
C     MASS-WEIGHT SORTED VECTOR - WILL ZERO ELEMENTS CORRESPONDING
C     TO DUMMY ATOMS SO THEY DONT MUCK UP THE SYMMETRY CHECKING.
C
      DO I=0,2
         Y(3*JK-2+I)=X(J+I)*NINT(ATMASS(ILINE(J)))
         X(J)=-99999.D0
      ENDDO
      NORD(JK)=(J+2)/3
      JK=JK+1
      IF (JK.EQ.NATOMS+1) GOTO 70
      GOTO 40
70    CONTINUE

! }}}
      RETURN
      END
