MODULE BOWMANWATER

IMPLICIT NONE

CONTAINS

SUBROUTINE BOWMANINIT(NW, PES, DNAME)
INTEGER, INTENT(IN) :: NW, PES
CHARACTER (LEN=*), INTENT(IN) :: DNAME
PRINT *, "MUST COMPILE WITH IFORT IN ORDER TO USE BOWMANS WATER POTENTIAL"
STOP
END SUBROUTINE BOWMANINIT

DOUBLE PRECISION FUNCTION BOWMANPOT(X)
DOUBLE PRECISION, DIMENSION(:), INTENT(IN) :: X
PRINT *, "MUST COMPILE WITH IFORT IN ORDER TO USE BOWMANS WATER POTENTIAL"
STOP
END FUNCTION BOWMANPOT

END MODULE BOWMANWATER
