SUBROUTINE RCA
! declarations {{{
USE PORFUNCS
USE DV
USE COMMONS

IMPLICIT NONE

INTEGER NARGS, I
CHARACTER(LEN=80) BFF,VAR,S
! }}}
! subroutine body {{{

CALL IARGC_SUBR(NARGS)
I=0

IF (NARGS.GT.0) THEN
  DO WHILE(I.LT.NARGS) ; I=I+1 ; CALL GETARG_SUBR(I,BFF)
     SELECTCASE(BFF)
       CASE('-v')  ; CALL DISPLAY_VERSION(0) ; STOP
       CASE DEFAULT
         CALL GETARG_SUBR(I+1,VAR)
         SELECTCASE(BFF)
             CASE('-g') ;  DEBUG=.TRUE.
	                CASE DEFAULT
         ENDSELECT
     ENDSELECT
  ENDDO
ENDIF
! }}}
END SUBROUTINE RCA

