
      MODULE COMMONS

      USE NOA

      IMPLICIT NONE
      SAVE

     INTEGER :: NATOMS,NS,NACCEPT,MAXIT,MAXIT2,NTARGETS,NSEED,NSAVE,MCSTEPS(3)
     INTEGER :: NRUNS,MUPDATE,NRELAX,MYUNIT
     INTEGER :: MYEUNIT, MYMUNIT, MYBUNIT, MYRUNIT, MYPUNIT, MYNODE 

     DOUBLE PRECISION :: RADIUS,BQMAX,MAXBFGS,ECONV,GMAX
     DOUBLE PRECISION :: TFAC(3),RMS,DGUESS,EPSSPHERE
     DOUBLE PRECISION :: MAXERISE,MAXEFALL

     INTEGER :: NPAIRS
     INTEGER, ALLOCATABLE :: PAIRDIST(:,:)
     LOGICAL :: PAIRDISTT
      
     CHARACTER(LEN=80) :: SYS
     CHARACTER(LEN=1), ALLOCATABLE :: BEADLETTER(:), BLNSSTRUCT(:)
     CHARACTER(LEN=130) DUMPFILE, MYFILENAME, INTEDUMPFILE

!   allocatables

      INTEGER, ALLOCATABLE, DIMENSION(:) :: NQ, NCORE ! dimension will be NPAR
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: TEMP, STEP, OSTEP, ASTEP, ACCRAT, EPREV ! dimension will be NPAR 
      DOUBLE PRECISION, ALLOCATABLE :: TARGETS(:) ! allocated NTARGETS in keyword.f
      DOUBLE PRECISION, ALLOCATABLE :: ESAVE(:,:) ! dimension will be NTAB,NPAR
      DOUBLE PRECISION, ALLOCATABLE :: XINSAVE(:,:) ! dimension will be NTAB,NPAR
      DOUBLE PRECISION, ALLOCATABLE :: MASSES(:)
      LOGICAL, ALLOCATABLE, DIMENSION(:) :: FIXBOTH, FIXTEMP, FIXSTEP, JUMPMOVE, JDUMP, TMOVE, OMOVE ! dimension will be NPAR
      INTEGER,ALLOCATABLE :: ANV(:,:,:)

      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) :: TCOORDS
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: VT
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) :: COORDS,COORDSO
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) ::  VAT,  VATO    
      DOUBLE PRECISION ::   TSTART

      ! BLN/Go parameters
      LOGICAL :: GOTYPE=.FALSE.
      DOUBLE PRECISION :: GOFACTOR=0D0

      ! logicals
      LOGICAL :: P46,G46,BLNT,SEEDT,NORESET,BSPT
      LOGICAL :: CENT,BFGS,LBFGST,DEBUG,CHECKMARKOVT,FIXCOM,STEPOUT
      LOGICAL :: TARGET,DUMPT,TRACKDATAT
      INTEGER ::    dumpint

      DOUBLE PRECISION ::   CQMAX,MCTEMP
      INTEGER :: NPAR

      CONTAINS

      SUBROUTINE MODCOMMONINIT
         IMPLICIT NONE
         
         NATOMS = NUMBER_OF_ATOMS
         ALLOCATE( ANV(NATOMS,NATOMS,3))         
      END SUBROUTINE MODCOMMONINIT

      SUBROUTINE MODCOMMONDEINIT
         IMPLICIT NONE
         
         IF (ALLOCATED(ANV)) DEALLOCATE(ANV)
      END SUBROUTINE MODCOMMONDEINIT
END MODULE COMMONS
