
      MODULE COMMONS

      USE NOA

      IMPLICIT NONE
      SAVE

      ! integer {{{
     INTEGER :: NATOMS,NS,NACCEPT,MAXIT,MAXIT2,NTARGETS,NSEED,NSAVE,MCSTEPS(3)
     INTEGER :: NSSTOP
     INTEGER :: NRUNS,MUPDATE,NRELAX,MYUNIT
     INTEGER :: MYEUNIT, MYMUNIT, MYBUNIT, MYRUNIT, MYPUNIT, MYNODE 
     INTEGER ::    DUMPINT
     INTEGER :: NPAR
     INTEGER :: DUMPXYZUNIT, DUMPVUNIT
     INTEGER :: NHSRESTART
     ! for GMINdump
     INTEGER :: NMSBSAVE
     INTEGER :: MAXSAVE
     ! }}}
     ! dp {{{
     DOUBLE PRECISION :: RADIUS,BQMAX,MAXBFGS,ECONV,GMAX
     DOUBLE PRECISION :: TFAC(3),RMS,DGUESS,EPSSPHERE
     DOUBLE PRECISION :: MAXERISE,MAXEFALL
     DOUBLE PRECISION ::    ARMA,ARMB
     DOUBLE PRECISION ::   TSTART
     DOUBLE PRECISION ::   CQMAX,MCTEMP
     DOUBLE PRECISION ::    EAMP,EFAC
     DOUBLE PRECISION ::    CENTX,CENTY,CENTZ
     ! used in BLN
     DOUBLE PRECISION ::    RK_R, RK_THETA
     ! hsmove
     DOUBLE PRECISION ::    BOXLX
     ! }}}
     ! pairdist {{{
     INTEGER :: NPAIRS
     INTEGER, ALLOCATABLE :: PAIRDIST(:,:)
     LOGICAL :: PAIRDISTT
     ! }}}
!   allocatables {{{

      DOUBLE PRECISION, ALLOCATABLE :: MSBCOORDS(:,:)
      DOUBLE PRECISION, ALLOCATABLE :: MSBE(:)

      DOUBLE PRECISION, ALLOCATABLE :: LJREP_BLN(:,:), LJATT_BLN(:,:)
      DOUBLE PRECISION,ALLOCATABLE ::  A_BLN(:), B_BLN(:), C_BLN(:), D_BLN(:), HYDRO_BLN(:)

      CHARACTER(LEN=1), ALLOCATABLE :: BEADLETTER(:), BLNSSTRUCT(:)
      INTEGER, ALLOCATABLE, DIMENSION(:) :: NQ, NCORE! DIMENSION WILL BE NPAR
      INTEGER,ALLOCATABLE,DIMENSION(:)   :: JUMPTO    
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: TEMP, STEP, OSTEP, ASTEP, ACCRAT, EPREV ! dimension will be NPAR 
      DOUBLE PRECISION, ALLOCATABLE :: TARGETS(:) ! allocated NTARGETS in keyword.f
      DOUBLE PRECISION, ALLOCATABLE :: ESAVE(:,:) ! dimension will be NTAB,NPAR
      DOUBLE PRECISION, ALLOCATABLE :: XINSAVE(:,:) ! dimension will be NTAB,NPAR
      DOUBLE PRECISION, ALLOCATABLE :: MASSES(:)
      LOGICAL, ALLOCATABLE, DIMENSION(:) :: FIXBOTH, FIXTEMP, FIXSTEP, JUMPMOVE, JDUMP, TMOVE, OMOVE ! dimension will be NPAR
      INTEGER,ALLOCATABLE :: ANV(:,:,:)

      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) :: TCOORDS
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: VT
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) :: COORDS,COORDSO
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) ::  VAT,  VATO    
! }}}
      ! LOGICALS {{{
      LOGICAL :: P46,G46,BLNT,SEEDT,NORESET,BSPT,FIXIMAGE,PERIODIC,RIGID,TWOD
      LOGICAL :: CENT,BFGS,LBFGST,DEBUG,CHECKMARKOVT,FIXCOM,STEPOUT
      LOGICAL :: TARGET,DUMPT,TRACKDATAT,RESTART
       LOGICAL ::  ARMT 
       LOGICAL ::   CENTXY
       LOGICAL ::   BINARY
      
      ! }}}
! chr {{{
      CHARACTER(LEN=80) :: SYS
      CHARACTER(LEN=130) DUMPFILE, MYFILENAME, INTEDUMPFILE
! }}}
      ! BLN/Go parameters {{{
      LOGICAL :: GOTYPE=.FALSE.
      DOUBLE PRECISION :: GOFACTOR=0D0
      ! }}}
      !pulling  {{{
      INTEGER :: PATOM1,PATOM2
      DOUBLE PRECISION ::   PFORCE
      LOGICAL :: PULLT
      ! }}}

      CONTAINS

      SUBROUTINE MODCOMMONINIT
         IMPLICIT NONE
         
         NATOMS = NUMBER_OF_ATOMS
         ALLOCATE( ANV(NATOMS,NATOMS,3))         
      END SUBROUTINE MODCOMMONINIT

      SUBROUTINE MODCOMMONDEINIT
         IMPLICIT NONE
         
         IF (ALLOCATED(ANV)) DEALLOCATE(ANV)
      END SUBROUTINE MODCOMMONDEINIT
END MODULE COMMONS
