
      MODULE COMMONS

      IMPLICIT NONE

      SAVE

      !files, from sim/v.f90 {{{
INTEGER, PARAMETER :: FH=20
INTEGER :: LFH
INTEGER :: ENERGY_FH
INTEGER :: MARKOV_FH
INTEGER :: BEST_FH
INTEGER :: PAIRDIST_FH
INTEGER :: COORDS_FH
INTEGER :: DATA_FH
INTEGER :: RMSD_FH

CHARACTER(LEN=100) LFN
PARAMETER(LFN="gmi.log")
      ! }}}
      ! integer {{{
     INTEGER :: NATOMS,NS,NACCEPT,MAXIT,MAXIT2,NTARGETS,NSEED,NSAVE,MCSTEPS(3)
     INTEGER :: NSSTOP
     INTEGER :: NRUNS,MUPDATE,NRELAX,NHSRESTART
     INTEGER :: MYEUNIT, MYMUNIT, MYBUNIT, MYRUNIT, MYPUNIT, MYNODE 
     INTEGER ::    DUMPINT
     INTEGER :: NPAR
     INTEGER :: DUMPXYZUNIT, DUMPVUNIT
     ! for GMINdump
     INTEGER :: NMSBSAVE
     INTEGER :: MAXSAVE
     ! nargs - number of cmd-line arguments
     INTEGER :: NARGS
     INTEGER :: MAXNARGS,SLEN
     PARAMETER (SLEN=100,MAXNARGS=100)
     ! }}}
     ! dp {{{
     DOUBLE PRECISION :: RADIUS,SQMAX,MAXBFGS,EDIFF,GMAX
     DOUBLE PRECISION :: TFAC(3),RMS,DGUESS,EPSSPHERE
     DOUBLE PRECISION :: MAXERISE,MAXEFALL
     DOUBLE PRECISION ::    ARMA,ARMB
     DOUBLE PRECISION ::   TSTART
     DOUBLE PRECISION ::   FQMAX,MCTEMP
     DOUBLE PRECISION ::    EAMP,EFAC
     DOUBLE PRECISION ::    CENTX,CENTY,CENTZ
     ! used in BLN
     DOUBLE PRECISION ::    RK_R, RK_THETA
     ! hsmove
     DOUBLE PRECISION ::    BOXLX
     ! 
     DOUBLE PRECISION ::    PI,ZERO,ONE
     ! }}}
     ! pairdist {{{
     INTEGER :: NPAIRS
     INTEGER, ALLOCATABLE :: PAIRDIST(:,:)
     LOGICAL :: PAIRDISTT
     ! }}}
!   allocatables {{{

      DOUBLE PRECISION, ALLOCATABLE :: MSBCOORDS(:,:)
      DOUBLE PRECISION, ALLOCATABLE :: MSBE(:)

      DOUBLE PRECISION, ALLOCATABLE :: LJREP_BLN(:,:), LJATT_BLN(:,:)
      DOUBLE PRECISION,ALLOCATABLE ::  A_BLN(:), B_BLN(:), C_BLN(:), D_BLN(:), HYDRO_BLN(:)

      CHARACTER(LEN=1), ALLOCATABLE :: BEADLETTER(:), BLNSSTRUCT(:)
      INTEGER, ALLOCATABLE, DIMENSION(:) :: NQ, NCORE! DIMENSION WILL BE NPAR
      INTEGER,ALLOCATABLE,DIMENSION(:)   :: JUMPTO    
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: TEMP, STEP, OSTEP, ASTEP, ACCRAT, EPREV ! dimension will be NPAR 
      DOUBLE PRECISION, ALLOCATABLE :: TARGETS(:) ! allocated NTARGETS in keyword.f
      DOUBLE PRECISION, ALLOCATABLE :: ESAVE(:,:) ! dimension will be NTAB,NPAR
      DOUBLE PRECISION, ALLOCATABLE :: XINSAVE(:,:) ! dimension will be NTAB,NPAR
      DOUBLE PRECISION, ALLOCATABLE :: MASSES(:)
      LOGICAL, ALLOCATABLE, DIMENSION(:) :: FIXBOTH, FIXTEMP, FIXSTEP, JUMPMOVE, JDUMP, TMOVE, OMOVE ! dimension will be NPAR
      INTEGER,ALLOCATABLE :: ANV(:,:,:)

      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) :: TCOORDS
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: VT
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) :: COORDS,COORDSO
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) ::  VAT,  VATO    
! }}}
      ! LOGICALS {{{
      LOGICAL :: P46,G46,BLNT,SEEDT,NORESET,BSPT,FIXIMAGE,PERIODIC,RIGID,TWOD
      LOGICAL :: CENT,BFGS,LBFGST,DEBUG,CHECKMARKOVT,FIXCOM,STEPOUT
      LOGICAL :: TARGET,DUMPT,TRACKDATAT,RESTART,RESTORET
      LOGICAL ::  ARMT 
      LOGICAL ::   CENTXY
      LOGICAL ::   BINARY
      LOGICAL ::    USEKW
      ! do a final quench?
      LOGICAL ::    FQFLAG
      
      ! }}}
! chr {{{
      ! name for the model system
      CHARACTER(LEN=100) MODEL

      CHARACTER(LEN=80) :: SYS
      CHARACTER(LEN=130) DUMPFILE, MYFILENAME, INTEDUMPFILE
      CHARACTER(LEN=SLEN), DIMENSION(MAXNARGS) :: ARGS
      ! D_FILE - data
      ! C_FILE - coords
      CHARACTER(LEN=SLEN) :: D_FILE,C_FILE
      ! LE_FILE - lowest
      CHARACTER(LEN=SLEN) :: LE_FILE
      ! E_FILE - e.tex
      CHARACTER(LEN=SLEN) :: E_FILE
      ! log file - out
      CHARACTER(LEN=SLEN) :: LF_FILE
      
! }}}
      ! BLN/Go parameters {{{
      LOGICAL :: GOTYPE=.FALSE.
      DOUBLE PRECISION :: GOFACTOR=0D0
      ! }}}
      !pulling  {{{
      INTEGER :: PATOM1,PATOM2
      DOUBLE PRECISION ::   PFORCE
      LOGICAL :: PULLT
      ! }}}
      !parameters {{{
		PARAMETER (PI=3.141592654D0)
		PARAMETER (ZERO=1.0D-100)
		PARAMETER (ONE=1.0D0)
      ! }}}


END MODULE COMMONS
