#!/usr/bin/env bash

# copy into ef.*.sh from ../ef.*.tex

deps=( ea ef ) 
for dep in ${deps[@]}; do 
	ff=( ${ff[@]} ` find ../ -name $dep.\*.tex ` )
done 
ss=( P46 G46 )

for f in ${ff[@]}; do
	for sys in ${ss[@]}; do
		dep=` echo $f | sed 's/^\.\.\///g' | sed 's/\..*$//g' `
	  	hf="$dep.$sys.sh"
		if [ -f $f ]; then
			echo "# adat: $f, $sys, $dep, `date` " >> $hf
	  		cat $f | awk "/$sys/" >> $hf
	  	fi
	done
		rm -f $f
done
