#!/usr/bin/env bash

# copy into ef.*.sh from ../ef.*.tex

#ff=( ` find ../ -name ef.\*.tex ` )
deps=( ea ef ) 
for dep in ${deps[@]}; do 
	ff=( ${ff[@]} ` ack -f $dep.*.tex ` )
done 
ss=( P46 G46 )

for ff in ${ff[@]}; do
	for sys in ${ss[@]}; do
	  	hf="$dep.$sys.sh"
		if [ -f $f ]; then
			echo "# aef: $f, $sys, `date` " >> $hf
	  		cat $f | awk "/$sys/" >> $hf
	  	fi
	done
		rm -f $f
done
