
        IMPLICIT NONE
        
        ! number of particles
        INTEGER, INTENT(IN) :: N

        ! input vector of coordinates
        DOUBLE PRECISION QO(3*N)
        
        LOGICAL GRADT

        DOUBLE PRECISION ENERGY

        ! A => array A, B, C, D coefficients for the generic BLN model
        DOUBLE PRECISION, DIMENSION(N,4) :: A

        ! AB(,1)=>A_PARAM(N,N)
        ! AB(,2)=>B_PARAM(N,N)
        ! CD(,1)=>C_PARAM(N)
        ! CD(,2)=>D_PARAM(N)
        DOUBLE PRECISION, DIMENSION(N,N,2) AB
        DOUBLE PRECISION, DIMENSION(N,2)   CD

        DOUBLE PRECISION, DIMENSION(N,3) :: R
        DOUBLE PRECISION, DIMENSION(N,N,3) :: DR
        DOUBLE PRECISION, DIMENSION(N,N) :: RADII
        DOUBLE PRECISION, DIMENSION(N) :: X_PROD, COSTOR, BOND_ANGLE, TOR_ANGLE
        DOUBLE PRECISION, DIMENSION(N,3) :: DOT_PROD 

        INTEGER NTYPE(46), I, J
        DOUBLE PRECISION RK_R, RK_THETA

        DOUBLE PRECISION E_NBOND, E_BOND, E_BANGLE, E_TANGLE, RAD6
        DOUBLE PRECISION RMASS, SIGMA, EPSILON, DELTA
        DOUBLE PRECISION THETA_0

        DOUBLE PRECISION GRAD(3*N)
      
        ! LJREP => repulsion
        ! LJATT => attraction
        DOUBLE PRECISION, DIMENSION(N,N) :: LJREP,LJATT

        ! 1.8326 RADIANS IS 105 DEGREES
        DOUBLE PRECISION, PARAMETER :: THETA_0 = 1.8326D0, PI4=0.7853981633974483096D0 
        PARAMETER (RMASS = 40.0, EPSILON = 0.0100570)
        PARAMETER (SIGMA=3.4, DELTA=1.0D-6, THETA_0 = 1.8326)
        PARAMETER (RK_R = 20.0*0.0100570, RK_THETA = 20.0*0.0100570)

      
