
     DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) :: COORDS, COORDSO, VAT, VATO
     DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) :: HESS
     DOUBLE PRECISION ::     RMASS(3)
     DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: GRAD
     ! initial time
     DOUBLE PRECISION :: TSTART
     INTEGER :: NATOMS=46
     
