
     DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) :: COORDS, COORDSO
     DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) :: HESS
     DOUBLE PRECISION ::     RMASS(3)
     DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: GRAD
     ! initial time
     DOUBLE PRECISION :: TSTART, TFINISH
     INTEGER :: NATOMS=46

     ! potential type
     CHARACTER(LEN=SLEN) PTYPE
     
