!   NEB MODULE IS AN IMPLEMENTATION OF THE NUDGED ELASTIC BAND METHOD FOR PERFORMING DOUBLE-ENDED PATHWAY SEARCHES.
!   COPYRIGHT (C) 2003-2006 SEMEN A. TRYGUBENKO AND DAVID J. WALES
!   THIS FILE IS PART OF NEB MODULE. NEB MODULE IS PART OF OPTIM.
!
!   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!   (AT YOUR OPTION) ANY LATER VERSION.
!
!   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!
!   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!
MODULE KEYGRAD
     IMPLICIT NONE
     SAVE
     LOGICAL :: ORT               = .FALSE.
     CHARACTER(LEN=5) :: GRADTYPE = "DNEB"
     CONTAINS

     SUBROUTINE KEYGRADPRINT
          USE CHARUTILS
          IMPLICIT NONE
          IF (ORT) THEN
               WRITE(*,'(1X,A)') 'KEYGRAD> OVERALL ROTATION AND TRANSLATION WILL BE REMOVED'
          ELSE
               WRITE(*,'(1X,A)') 'KEYGRAD> OVERALL ROTATION AND TRANSLATION WILL NOT BE REMOVED'
          ENDIF
          
          SELECT CASE (GRADTYPE)
               CASE ("JNEW")
                    WRITE(*,'(1X,A)') 'KEYGRAD> GRADIENT WILL BE CONSTRUCTED ACCORDING TO NEW RECOMMENDATIONS OF JONSSON'
               CASE ("JOLD")
                    WRITE(*,'(1X,A)') 'KEYGRAD> GRADIENT WILL BE CONSTRUCTED ACCORDING TO OLD RECOMMENDATIONS OF JONSSON'
               CASE ("DNEB")
                    WRITE(*,'(1X,A)') 'KEYGRAD> USING DOUBLY NUDGED ELASTIC BAND GRADIENT'
          END SELECT
     END SUBROUTINE KEYGRADPRINT
END MODULE KEYGRAD
