!   NEB MODULE IS AN IMPLEMENTATION OF THE NUDGED ELASTIC BAND METHOD FOR PERFORMING DOUBLE-ENDED PATHWAY SEARCHES.
!   COPYRIGHT (C) 2003-2006 SEMEN A. TRYGUBENKO AND DAVID J. WALES
!   THIS FILE IS PART OF NEB MODULE. NEB MODULE IS PART OF OPTIM.
!
!   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!   (AT YOUR OPTION) ANY LATER VERSION.
!
!   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!
!   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!
MODULE KEYMINIMIZER
     IMPLICIT NONE
     SAVE
     INTEGER :: NITERMIN         = 0
     INTEGER :: NITERMAX         = 1
     DOUBLE PRECISION :: RMSTOL           = 0.01D0
     CHARACTER(LEN=5) :: MINTYPE = "LBFGS"
     CONTAINS
     
     SUBROUTINE KEYMINIMIZERPRINT(VARIABLEIN)
          USE CHARUTILS
          USE KEYLBFGS,ONLY:KEYLBFGSPRINT
          USE KEYSQVV,ONLY:KEYSQVVPRINT
          IMPLICIT NONE
          LOGICAL,INTENT(IN),OPTIONAL :: VARIABLEIN

          LOGICAL :: VARIABLE

          VARIABLE=.FALSE.
          IF (PRESENT(VARIABLEIN)) VARIABLE=VARIABLEIN

          IF (VARIABLE) THEN
               WRITE(*,'(1X,A)') 'KEYMIN> MAXIMAL NUMBER OF ITERATIONS WILL VARY,'//&
               &' DEPENDING ON THE NUMBER OF IMAGES IN THE BAND'
          ELSE
               INTSTR=WI(NITERMIN)
               INTSTR2=WI(NITERMAX)
               WRITE(*,'(1X,A)') 'KEYMIN> NUMBER OF ITERATIONS: MIN, MAX = '//TRIM(INTSTR)//', '//TRIM(INTSTR2)
          ENDIF

          REALSTR=RM0S(WR(RMSTOL,9))
          WRITE(*,'(1X,A)') 'KEYMIN> RMS CONVERGENCE CRITERION IS SET TO '//TRIM(REALSTR)

          SELECT CASE (MINTYPE)
          CASE ("LBFGS")
               WRITE(*,'(1X,A)') 'KEYMIN> L-BFGS MINIMIZATION'
               CALL KEYLBFGSPRINT
          CASE ("SQVV")
               WRITE(*,'(1X,A)') 'KEYMIN> SQVV MINIMISATION'
               CALL KEYSQVVPRINT
          END SELECT
     END SUBROUTINE KEYMINIMIZERPRINT
END MODULE KEYMINIMIZER
