!   NEB MODULE IS AN IMPLEMENTATION OF THE NUDGED ELASTIC BAND METHOD FOR PERFORMING DOUBLE-ENDED PATHWAY SEARCHES.
!   COPYRIGHT (C) 2003-2006 SEMEN A. TRYGUBENKO AND DAVID J. WALES
!   THIS FILE IS PART OF NEB MODULE. NEB MODULE IS PART OF OPTIM.
!
!   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!   (AT YOUR OPTION) ANY LATER VERSION.
!
!   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!
!   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!
MODULE KEYNEB
     USE KEY,ONLY: DEBUG,NEBK,NEBKINITIAL,NEBKFINAL,NEBFACTOR
     USE KEYGRAD
     USE KEYOUTPUT
     USE KEYMINIMIZER
     USE KEYSQVV
     USE KEYLBFGS
     USE KEYTAU
     IMPLICIT NONE
     SAVE
     INTEGER :: NIMAGE              = 3
     LOGICAL :: MOREPRINTING        = .FALSE.
     LOGICAL :: DUMPNEBXYZ          = .FALSE.
     INTEGER :: DUMPNEBXYZFREQ      = 100
     LOGICAL :: DUMPNEBPTS          = .FALSE.
     INTEGER :: DUMPNEBPTSFREQ      = 100
     LOGICAL :: DUMPNEBEOS          = .FALSE.
     INTEGER :: DUMPNEBEOSFREQ      = 100
     LOGICAL :: READGUESS           = .FALSE.
     CHARACTER(LEN=10) :: XYZFILE   = 'NEB.XYZ   '
     CHARACTER(LEN=12) :: RBXYZFILE = 'RBNEB.XYZ   '
     CHARACTER(LEN=10) :: PTSFILE   = 'NEB.OUT   '
     CHARACTER(LEN=10) :: EOFSFILE  = 'NEB.EOFS  '
     CHARACTER(LEN=80) :: GUESSFILE = 'GUESS.XYZ '
     LOGICAL :: OLDCONNECT          = .FALSE.
     !LOGICAL :: DEBUG               = .FALSE.
     CONTAINS

     SUBROUTINE KEYNEBPRINT(VARIABLEIN)
          USE CHARUTILS
          USE KEY, ONLY : DESMAXAVGE, DESMAXEJUMP, DNEBSWITCH
          IMPLICIT NONE
          LOGICAL,INTENT(IN),OPTIONAL :: VARIABLEIN
          
          LOGICAL :: VARIABLE
          
          WRITE(*,'(1X,A,2G19.10,A,G19.10)') 'KEYNEB> INITIAL AND FINAL NEB FORCE CONSTANTS ', &
  &                                           NEBKINITIAL,NEBKFINAL,' FACTOR=',NEBFACTOR
          VARIABLE=.FALSE.
          IF (PRESENT(VARIABLEIN)) VARIABLE=VARIABLEIN
          IF (DNEBSWITCH.GT.0.0D0) WRITE(*,'(A,G20.10)') &
  &               ' KEYNEB> GRADIENT WILL SWITCH TO SINGLE-NUDGED FORMULATION FOR RMS<',DNEBSWITCH
          IF (VARIABLE) THEN
               WRITE(*,'(1X,A)') 'KEYNEB> NUMBER OF IMAGES WILL VARY DEPENDING ON THE SEPARATION OF THE ENDPOINTS'
          ELSE
               INTSTR=WI(NIMAGE)
               WRITE(*,'(1X,A)') 'KEYNEB> USING '//TRIM(INTSTR)//' IMAGES'
          ENDIF
          
          IF (DUMPNEBXYZ) THEN
               INTSTR=WI(DUMPNEBXYZFREQ)
               WRITE(*,'(1X,A)') 'KEYNEB> NEB COORDINATES WILL BE SAVED TO XYZ FILE "'//TRIM(XYZFILE)//'" EVERY '&
               &//TRIM(INTSTR)//' ITERATIONS'
          ENDIF
          IF (DUMPNEBPTS) THEN
               INTSTR=WI(DUMPNEBPTSFREQ)
               WRITE(*,'(1X,A)') 'KEYNEB> NEB COORDINATES WILL BE SAVED TO BINARY FILE "'//TRIM(PTSFILE)//'" EVERY '&
               &//TRIM(INTSTR)//' ITERATIONS'
          ENDIF
          IF (DUMPNEBEOS) THEN
               INTSTR=WI(DUMPNEBEOSFREQ)
               WRITE(*,'(1X,A)') 'KEYNEB> ENERGY PROFILE WILL BE SAVED TO FILE "'//TRIM(EOFSFILE)//'" EVERY '&
               &//TRIM(INTSTR)//' ITERATIONS'
          ENDIF

          IF (READGUESS) WRITE(*,'(1X,A)') 'KEYNEB> GUESS WILL BE READ FROM FILE "'//TRIM(GUESSFILE)//'"'
          IF (OLDCONNECT) WRITE(*,'(1X,A)') "KEYNEB> TRANSITION STATE CANDIDATE WILL BE RETURNED IN FIRST ENDPOINT'S COORD ARRAY"
          IF (DEBUG) THEN
               WRITE(*,'(1X,A)') "KEYNEB> VERBOSE PRINTING IS ON"
               WRITE(*,'(1X,A)') 'KEYNEB> EVOLUTION OF AVDEV, E, RMS AND S WILL BE SAVED TO '&
               &//'FILES "AVDEVOFI", "EOFI", "RMSOFI" AND "SOFI"'
          ENDIF
          IF (DESMAXAVGE.LT.0.99*HUGE(1.0D0)) WRITE(*,'(1X,A,G20.10)') 'KEYGS> MAX AVERAGE ENERGY: ', DESMAXAVGE
          IF (DESMAXEJUMP.LT.0.99*HUGE(1.0D0)) WRITE(*,'(1X,A,G20.10)') 'KEYGS> MAX ENERGY JUMP PER IMAGE: ', DESMAXEJUMP
          
     END SUBROUTINE KEYNEBPRINT

     SUBROUTINE ALLKEYNEBPRINT(VARIABLE)
          IMPLICIT NONE
          LOGICAL,INTENT(IN),OPTIONAL :: VARIABLE
          IF (PRESENT(VARIABLE)) THEN
               CALL KEYNEBPRINT(VARIABLE)
          ELSE
               CALL KEYNEBPRINT
          ENDIF
          CALL KEYGRADPRINT
          CALL KEYOUTPUTPRINT
          IF (PRESENT(VARIABLE)) THEN
               CALL KEYMINIMIZERPRINT(VARIABLE)
          ELSE
               CALL KEYMINIMIZERPRINT
          ENDIF
          CALL KEYTAUPRINT
     END SUBROUTINE ALLKEYNEBPRINT
END MODULE KEYNEB
