!   NEB MODULE IS AN IMPLEMENTATION OF THE NUDGED ELASTIC BAND METHOD FOR PERFORMING DOUBLE-ENDED PATHWAY SEARCHES.
!   COPYRIGHT (C) 2003-2006 SEMEN A. TRYGUBENKO AND DAVID J. WALES
!   THIS FILE IS PART OF NEB MODULE. NEB MODULE IS PART OF OPTIM.
!
!   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!   (AT YOUR OPTION) ANY LATER VERSION.
!
!   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!
!   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!
MODULE KEYSQVV
     IMPLICIT NONE
     SAVE

     DOUBLE PRECISION :: DT                = 0.01D0
     
     LOGICAL :: LIMITSQVVSTEP     = .FALSE.
     DOUBLE PRECISION :: STEPDOFMAX        = 0.01D0

     LOGICAL :: SQVVGUESS         = .FALSE.
     INTEGER :: NITERSQVVGUESSMAX = 300
     DOUBLE PRECISION :: SQVVGUESSRMSTOL   = 2.0D0

     LOGICAL :: READVEL           = .FALSE.
     CONTAINS

     SUBROUTINE KEYSQVVPRINT
          USE CHARUTILS
          IMPLICIT NONE
          REALSTR=RM0S(WR(DT,9))          
          WRITE(*,'(1X,A)') 'KEYSQVV> USING TIME INTEGRATION STEP OF '//TRIM(REALSTR)

          IF (LIMITSQVVSTEP) THEN
               REALSTR=RM0S(WR(STEPDOFMAX,9))
               WRITE(*,'(1X,A)') 'KEYSQVV> MAXIMAL STEP SIZE FOR EACH DEGREE OF FREEDOM = '//TRIM(REALSTR)
          ELSE
               WRITE(*,'(1X,A)') 'KEYSQVV> UNLIMITED STEP'
          ENDIF

          IF (SQVVGUESS) THEN
               INTSTR=WI(NITERSQVVGUESSMAX)
               WRITE(*,'(1X,A)') 'KEYSQVV> UP TO '//TRIM(INTSTR)//' STEPS OF SQVV INITIAL RELAXATION ARE ALLOWED'
               REALSTR=RM0S(WR(SQVVGUESSRMSTOL,9))
               WRITE(*,'(1X,A)') 'KEYSQVV> RMS CONVERGENCE TOLERANCE IS '//TRIM(REALSTR)
          ELSE
               WRITE(*,'(1X,A)') 'KEYSQVV> NO PREOPTIMIZATION WAS REQUESTED'
          ENDIF

          IF (READVEL) THEN
               WRITE(*,'(1X,A)') 'KEYSQVV> READING IN VELOCITY FILE'
          ENDIF
     END SUBROUTINE KEYSQVVPRINT
END MODULE KEYSQVV
