!   NEB MODULE IS AN IMPLEMENTATION OF THE NUDGED ELASTIC BAND METHOD FOR PERFORMING DOUBLE-ENDED PATHWAY SEARCHES.
!   COPYRIGHT (C) 2003-2006 SEMEN A. TRYGUBENKO AND DAVID J. WALES
!   THIS FILE IS PART OF NEB MODULE. NEB MODULE IS PART OF OPTIM.
!
!   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!   (AT YOUR OPTION) ANY LATER VERSION.
!
!   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!
!   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!
MODULE NEBTOCONNECT
     IMPLICIT NONE
     SAVE
     
     INTEGER,PARAMETER :: NTSMAX = 3000 !MAXIMAL NUMBER OF TS TO BE CHECKED IN ONE DNEB RUN
     
     TYPE TSFOUNDTYPE
          DOUBLE PRECISION,POINTER :: E
          DOUBLE PRECISION,POINTER :: EVALMIN
          DOUBLE PRECISION,POINTER :: COORD(:)
          DOUBLE PRECISION,POINTER :: VECS(:)
     END TYPE TSFOUNDTYPE

     TYPE (TSFOUNDTYPE) :: TSFOUND(NTSMAX)

     INTEGER :: NTSFOUND=0

     INTEGER,PARAMETER :: NMINMAX = 3000 !MAXIMAL NUMBER OF MIN TO BE CHECKED IN ONE DNEB RUN
     
     TYPE MINFOUNDTYPE
          DOUBLE PRECISION,POINTER :: E
          DOUBLE PRECISION,POINTER :: COORD(:)
     END TYPE MINFOUNDTYPE

     TYPE (MINFOUNDTYPE) :: MINFOUND(NMINMAX)

     INTEGER :: NMINFOUND=0
END MODULE NEBTOCONNECT
