#!/bin/bash

odir=$leonov:~/p46/

if [  -z $1 ]; then 
cat << EOF
======================================
SCRIPT NAME: cpt
OPTS:
	ef X	copy ef.dat from directory X to ef/ef_X.dat
	-d DIR
	a	copy from DIR to ef and xyz on leonov	
======================================
EOF
else
  		while [ ! -z "$1" ]; do
			case "$1" in
	  			"-ef") cp $2/ef.dat ef/ef_$2.dat ;;
				-d) dir=$2 ;;
				a) 
					scp $dir/gm.xyz $odir/xyz/$dir.xyz
					scp $dir/ef.dat $odir/ef/ef_$dir.dat
					exit
				;;
			esac
			shift
	        done
fi
