#!/bin/bash 
## pbs stuff {{{
#PBS -q s1
#PBS -j oe
#PBS -N gmGof
##PBS -l walltime=24:00:00
## Needed for clust, not mek-quake
##PBS -W x=NACCESSPOLICY:SINGLEJOB
##PBS -l nodes=1:ppn=1

cd $PBS_O_WORKDIR
wc $PBS_NODEFILE > nodes.info
cat $PBS_NODEFILE >> nodes.info
echo $USER >> nodes.info

pbs_job_id=` echo ${PBS_JOBID}  | sed "s/[\.a-zA-Z]*$//" `
clust_id=` echo ${PBS_JOBID}  | sed "s/^[0-9]*\.//" `

echo "PBS job id: $pbs_job_id" >> pre.log
echo "========================" >> pre.log
cat pre.log >> q.log
# end pbs stuff }}}

prog="GMIN"

export shd="`dirname $(readlink -f $0)`"
export shd="/home/op226/p46/sh"
source $shd/sh_header.sh

source $shd/set_base_pars.sh
source $shd/set_pbs_pars.sh
source $shd/set_gmin_pars.sh
source $shd/read_cmd_args.sh
source $shd/start_time.sh
source $shd/print_job_info.sh
source $shd/set_output_pars.sh
source $shd/switch_mode.sh

echo
qstat -f ${PBS_JOBID}@clust
echo

# vim:fdm=marker:ff=unix:noet:ts=4:sw=4:nowrap
