#!/bin/bash

export shd="`dirname $(readlink -f $0)`"
export this_script=` basename $0 `

use(){

source $shd/"$this_script"_$1.sh

}

use set_pars

if [ $no_rotate -eq 1 ]; then
  	xamax=$xamin
  	yamax=$yamin
  	zamax=$zamin
fi 

mkdir -p $tmp_dir
mkdir -p $pics_dir

if [ -z "$1" ]; then
  		use print_help
	else
	  cmd_args=( "$@" ) 
	  use read_cmd_args

	  echo "*********************"
	  echo "Starting $this_script..."
	  echo "Command-line arguments supplied:"
	  echo "${cmd_args[@]}"
	  echo 

	  old_full_file=${full_file%.xyz}.old.xyz
	  cp $full_file $old_full_file 

	  file=$file0.xyz ; full_file=$xyz_dir/$file
	  source "$this_script"_bln.sh

	  # now sort with respect to forces #source sort_forces.sh

	  case "$reset_f" in
	    	0)
	  		frame_max=1
	  		frame_min=1
			;;
		2)	frame_min=1
			frame_max=$num_frames
		;;
	  esac

	  mkdir -p $pics_dir

	  echo "Input XYZ file: $file0 "
	  echo "Input XYZ-directory: $xyz_dir"
	  echo "Number of frames: $num_frames"
	  echo "Output image directory: $pics_dir"
 	  echo "====================================="

	  source "$this_script"_loop_over_frames.sh	  
	  cp $old_full_file $full_file
fi
