#!/bin/bash
  	
files="r q0 vo vf c ao rmo pl vpl"
vim_opts="-n -p" 

if [ -z "$*" ]; then 
cat << EOF
SCRIPT NAME: vf
PURPOSE: view source files with vim
USAGE: vf OPTS
OPTS:
		display this help message
	b	base files 
	pl	pl, plot_arg.sh, plot_energy_markov_dat.sh
	r	set_runs.sh rrr rr0 rr
	1	base files + *.sh ao
	o	vo + set_output_pars.sh

	awk

REMARKS:
	base files are $files
EOF

else

while [ ! -z "$1" ] 
	do
		case "$1" in
		  "1") files="$files *.sh ao" ;;
		  "o") files="vo set_output_pars.sh" ;;
		  "pl") files="pl vpl plot_arg.sh plot_energy_markov_dat.sh" ;;
		  "r") files="set_runs.sh sub rrr.log rrr_switch_mode.sh define_forces_0.sh plot_energy_markov_dat.sh rrr.tex set_rrr_pars.sh rrr rr0 rr" ;;
		  "awk") files="awk/*a"  ;;
		  "b") ;;
		  *) exit ;;
		esac
		shift
done 

vim $vim_opts $files

fi

