!   CONNECT MODULE IS AN IMPLEMENTATION OF A CONNECTION ALGORITHM FOR FINDING REARRANGEMENT PATHWAYS.
!   COPYRIGHT (C) 2003-2006 SEMEN A. TRYGUBENKO AND DAVID J. WALES
!   THIS FILE IS PART OF CONNECT MODULE. CONNECT MODULE IS PART OF OPTIM.
!
!   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!   (AT YOUR OPTION) ANY LATER VERSION.
!
!   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!
!   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!
MODULE CONNECTDATA
     IMPLICIT NONE
     SAVE

     INTEGER :: NDIJPAIRS,LISTLENGTH=0
     INTEGER, ALLOCATABLE :: DIJPAIR(:,:)
     DOUBLE PRECISION, ALLOCATABLE :: DIJPAIRDIST(:)
     LOGICAL :: FINISHED
!--------------------------------------------------------

     INTEGER :: NMIN=0,NTS=0 !NUMBER OF TS/MIN FOUND SO FAR
     INTEGER :: NTSOLD=0
     INTEGER :: NATOMS,NOPT,NCONDONE,DEPTH
     INTEGER :: TSRACKSIZE=100,MINRACKSIZE=150
     DOUBLE PRECISION :: RMS
     DOUBLE PRECISION,ALLOCATABLE :: G(:)
     DOUBLE PRECISION :: D

     LOGICAL :: MOREPRINTING,ENDREACHED
     LOGICAL :: RANDOM

     CHARACTER(LEN=7)  :: CHR,CHR2
     CHARACTER(LEN=20) :: STR1,STR2,STR3,STR4,STR5,STR6

!--------------------------------------------------------
     TYPE MINDATA
          DOUBLE PRECISION,POINTER :: E
          DOUBLE PRECISION,POINTER :: X(:)
          DOUBLE PRECISION,POINTER :: D(:)      ! HOLDS DISTANCES TO ALL MINIMA KNOWN AT THE MOMENT OF ADDITION OF THIS MINIMUM
          DOUBLE PRECISION,POINTER :: INTERP(:) ! HOLDS DISTANCES TO ALL MINIMA KNOWN AT THE MOMENT OF ADDITION OF THIS MINIMUM
          INTEGER,POINTER :: NTRIES(:) ! HOLDS NUMBER OF TRIES THIS MINIMA WAS TRIED TO BE CONNECTED WITH ANY OTHER MINIMA -//-;
                                       ! THIS AFFECTS NUMBER OF IMAGES USED IN NEXT TRY (IF ANY)
          INTEGER,POINTER :: C(:)      ! TOTAL NUMBER OF CONNECTIONS TO THIS MINIMUM (SAME AS CURRENT SIZE OF CTS AND CMIN!)
          INTEGER,POINTER :: CTS(:)
          INTEGER,POINTER :: CMIN(:)
          LOGICAL         :: S,F
     END TYPE MINDATA

     TYPE TSDATA
          DOUBLE PRECISION,POINTER :: E
          DOUBLE PRECISION,POINTER :: X(:)
          DOUBLE PRECISION,POINTER :: EVALMIN
          DOUBLE PRECISION,POINTER :: VECS(:)
          INTEGER         :: P,M !NUMBERS OF MINIMA PLUS AND MINUS WHICH TS IS CONNECTING
          DOUBLE PRECISION         :: SLENGTH,SLP,DISP,GAMMA,NTILDE ! SLP - SLENGTHPLUS
          LOGICAL         :: BAD ! IS SET TO .TRUE. IF PATH RUN DID NOT CONVERGE
     END TYPE TSDATA

     TYPE MINTYPE
          TYPE(MINDATA) :: DATA
     END TYPE MINTYPE

     TYPE TSTYPE
          TYPE(TSDATA) :: DATA
     END TYPE TSTYPE

     TYPE(MINTYPE),POINTER :: MI(:),TEMPMINRACK(:)
     TYPE(TSTYPE),POINTER  ::  TS(:),TEMPTSRACK(:)
!--------------------------------------------------------
     TYPE CHAIN
          INTEGER :: I,J ! MINIMA I IS CONNECTED TO NEXT%I VIA TS J; J IS INDEX OF TS IN ARRAY CTS OF MINIMA I
          TYPE(CHAIN),POINTER :: NEXT
     END TYPE CHAIN

     TYPE(CHAIN),POINTER :: START,NEW,DUMMY
!--------------------------------------------------------
     TYPE CHAIN2
          INTEGER :: I
          TYPE(CHAIN2),POINTER :: NEXT
     END TYPE CHAIN2

     TYPE(CHAIN2),POINTER :: START2,NEW2,DUMMY2,ONEUP
!--------------------------------------------------------
     DOUBLE PRECISION :: EV
     DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: FRQSTS, EVEC, FRQSPLUS, FRQSMINUS, GDUMMY
END MODULE CONNECTDATA
