#!/usr/bin/env bash

# set_base_vars {{{
set_base_vars(){
# {{{
# directory where this script resides
export shd="`dirname $(readlink -f $0)`"
# name of this script 
export this_script=` basename $0 `
export gopsdir="$shd/../../"
vim_opts="-n -p"
v="vim $vim_opts"
s_purpose="fork a project"
s_project="~/gops/scripts/all"
# }}}
}

set_base_vars
#}}}

display_help(){
# {{{
# general beginning part {{{
cat << EOF
=============================================
SCRIPT NAME: $this_script 
PROJECT: $s_project
PURPOSE: $s_purpose
USAGE: $this_script [ OPTIONS ] 

	OPTIONS:

	============
	General
	============

			display the help message

	vm		v(iew) m(yself), i.e., edit this script
	-g		gvim invocation
	
	============
EOF
# }}}
# actual interesting part {{{
cat << EOF

	

EOF
# }}}
# final general part {{{
cat << EOF
REMARKS:
AUTHOR: O. Poplavskyy
=============================================
EOF
# }}}
# }}}
}

[ -z "$*" ] && ( display_help; exit 0 )

main(){
# read cmd line args{{{

while [ ! -z "$1" ]; do
		case "$1" in
		  "") ;;
		  # -b name of the base project
		  -b) base=$2; shift 
		  ;;
		  # -f name of the fork project
		  -f) fork=$2; shift ;;
		  *) $0 -b G -f $1; exit ;;
		esac
		shift
done 

#}}}
#do the forking  {{{

ffork=$base$fork
fdir=$gopsdir/$ffork ; mkdir -p $fdir
bdir=$gopsdir/$base; 
mkfiles=( makefile inc.mk t.mk nu.mk old.mk )

echo "$this_script> Base project: $base"
echo -e "$this_script> Base directory: \n $bdir"
echo "$this_script> Fork project: $ffork"
echo -e "$this_script> Fork directory: \n $fdir"

cd $bdir; 
# ${base_files[@]} base files {{{
bsrc=$bdir/base_source.in
base_files=( ` cat $bsrc ` )
for ff in ` cat $bsrc ` ; do
  	ffname=${ff%.*}
    base_files=( ${base_files[@]} ` ls $ffname.*i.* 2> /dev/null | sed '/~$/d' ` )
done
#}}}
# ${ffiles[@]} forked project files {{{
fsrc=$bdir/"$fork_source".in
if [ -f $fsrc ]; then
	ffiles=( ` cat $fsrc ` )
	for ff in `cat $fsrc ` ; do
  		ffname=${ff%.*}
    	ffiles=( ${ffiles[@]} ` ls $ffname.*i.* 2> /dev/null | sed '/~$/d'` )
	done
fi
#}}}

#*.num => not used modules (in the fork); num => Not Used Modules; nuv => Not Used Variables;
# nus => not used subroutines

cat $bsrc > $fdir/source."in"

if [ -f $fsrc ]; then 
	cat $fsrc  >> $fdir/source."in"
fi

echo "$this_script> In fork dir: Created source.in"
exts=( num nuv nus data )

for ext in ${exts[@]}; do  
	f=$fork.$ext
	if [ -f $f ]; then
	 	 cp $f $fdir/$ext."in"
		 echo "$this_script> Copied $f"
	fi
done 

files=( ${base_files[@]} ${ffiles[@]} )
echo "${files[@]}"

# copy source files: the base and the fork ones
for f in ${files[@]}; do
  	fname=${f%.*}
	fext=${f##*.}
	cp $bdir/$f $fdir/$fname.o.$fext
	#cp $bdir/$f $fdir
done
# copy make files
#for f in ${mkfiles[@]}; do
	#cp $bdir/$f $fdir/
#done

#rcaf=rca.$ffork.i.sh
#cp $shd/rca.$base.i.sh $shd/$rcaf
#echo "$this_script> In scripts dir: Created $rcaf"
#cp $gopsdir/sim/v $fdir/v
#echo "$this_script> Copied v "

# }}}
}

# main part 
# {{{

while [ ! -z "$1" ]; do
  	case "$1" in
		  #{{{
	  	vm) $v $0; exit ;;
		h) display_help $*; exit ;;
		-g) v="$v -g" ;;
	  	*) main $* && exit 0 ;;
	esac
  	shift
        #}}}
done

# }}}


