#!/usr/bin/env bash

# set_base_vars set_base_dirs display_help  {{{

set_base_dirs(){
# {{{
# main Wales group software directory
export rootdir="$shd/../../"
salldir=$rootdir/scripts/all/
incdir=$rootdir/include/
# }}}
}

set_base_vars(){
# {{{

# directory where this script resides
export shd="`dirname $(readlink -f $0)`"
# name of this script 
export this_script=` basename $0 `
# name of the current directory => program name
export PROGNAME=` basename $PWD `

vim_opts="-n -p"
v="vim $vim_opts"
repos=( "config" "scripts" "templates" "vrt" "install" "doc-coms" "doc-cit" )

s_purpose="view source files with vim"
s_project="~/gops/"
# }}}
}

set_base_vars

display_help(){
# {{{
# general beginning part {{{
cat << EOF
=============================================
SCRIPT NAME: $this_script 
PROJECT: $s_project
PURPOSE: $s_purpose
USAGE: $this_script [ OPTIONS ] 

	OPTIONS:

	============
	General
	============

			display the help message

	vm		v(iew) m(yself), i.e., edit this script
	-g		gvim invocation
	
	============
EOF
# }}}
# actual interesting part {{{
cat << EOF

		bln 
		v
		main

EOF
# }}}
# final general part {{{
cat << EOF
REMARKS:
AUTHOR: O. Poplavskyy
SCRIPT LOCATION: 
	$shd/$this_script
=============================================
EOF
# }}}
# }}}
}

# }}}

[ -z "$*" ] && ( display_help; exit 0 )

main(){
# {{{

case "$1" in
  gmi) $v $0 gmi.main.f90 func.f90 kw.f90 ../scripts/all/rca.sh ../include/fmt.i.f90 \
  `ls mc*.f90` v.f90 ../doc/wg.gmin.tex ../doc/wg.gmin.topics.tex .gdbinit
  ;;
  bln) $v bln*.f90 ;;
  m) 
  [ -f makefile ] && mkf="makefile"
  [ -f Makefile ] && mkf="Makefile"
  $v $0 $mkf old.mk deps.mk $incdir/nu_$PROGNAME.mk \
 		 $incdir/inc.mk inc.mk $incdir/def.mk $incdir/t.mk t.mk \
 		$salldir/rca.sh $salldir/dv.sh $salldir/mkdep.pl \
		base_source.in 
		;;
  o)
  $v ` ls n.*.f90 n.*.f n.*.F ` keyword*.f true.in false.in num.in source.in data.in rif.log ;;
  mn)
  $v main.f mcruns.f io.f90 mc.f90 kw.f90 func.f90 commons.f90 quench.f mylbfgs.f \
  n/keyword.if.i.f ;;
  lp) $v $0 myfunc.f90 potential.f90 commons.f90 `cat $incdir/lpu_$PROGNAME.mk | sed '/^#/d' ` `ls keyword*.f`  \
  			` find $incdir -name lpu_\*.mk -o -name nu_\*.mk ` ;;
esac    # --- end of case ---

# }}}
}

# main part 
# {{{

script_opts=( $* )
set_base_dirs

while [ ! -z "$1" ]; do
  	case "$1" in
		  #{{{
	  	vm) $v $0; exit ;;
		h) display_help $*; exit ;;
		-g) v="$v -g" ;;
	  	*) main $* && exit 0 ;;
	esac
  	shift
        #}}}
done

# }}}


