!   CONNECT MODULE IS AN IMPLEMENTATION OF A CONNECTION ALGORITHM FOR FINDING REARRANGEMENT PATHWAYS.
!   COPYRIGHT (C) 2003-2006 SEMEN A. TRYGUBENKO AND DAVID J. WALES
!   THIS FILE IS PART OF CONNECT MODULE. CONNECT MODULE IS PART OF OPTIM.
!
!   OPTIM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
!   IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
!   THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
!   (AT YOUR OPTION) ANY LATER VERSION.
!
!   OPTIM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
!   BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
!   MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
!   GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!
!   YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
!   ALONG WITH THIS PROGRAM; IF NOT, WRITE TO THE FREE SOFTWARE
!   FOUNDATION, INC., 59 TEMPLE PLACE, SUITE 330, BOSTON, MA  02111-1307  USA
!
MODULE KEYDECIDE
     IMPLICIT NONE 
     SAVE
     INTEGER :: COSTFUNCTIONPOWER = 1
     DOUBLE PRECISION :: INTERPDIFF
     DOUBLE PRECISION :: DIJKSTRADMAX=0.0D0
     LOGICAL :: EXPCOSTFUNCTION = .FALSE.
     LOGICAL :: INDEXCOSTFUNCTION = .FALSE.
     LOGICAL :: INTERPCOSTFUNCTION = .FALSE.

     CONTAINS

     SUBROUTINE KEYDECIDEPRINT
          USE CHARUTILS
          USE KEY, ONLY : INTCONSTRAINTT, INTLJT
          IMPLICIT NONE

          IF (INDEXCOSTFUNCTION) THEN
               WRITE(*,'(A)') ' KEYDECIDE> COST FUNCTION IN DIJKSTRA ALGORITHM IS BASED ON THE POSITION OF MINIMA IN LIST'
          ELSEIF (EXPCOSTFUNCTION) THEN
               WRITE(*,'(A)') ' KEYDECIDE> COST FUNCTION IN DIJKSTRA ALGORITHM IS EXP[D]'
          ELSEIF (INTERPCOSTFUNCTION) THEN
             IF (INTCONSTRAINTT) THEN
                WRITE(*,'(A,I6)') ' KEYDECIDE> COST FUNCTION IN DIJKSTRA ALGORITHM FROM INTERP FUNCTION, POWER=', COSTFUNCTIONPOWER
             ELSEIF (INTLJT) THEN
                WRITE(*,'(A,F15.5)') ' KEYDECIDE> COST FUNCTION IN DIJKSTRA ALGORITHM FROM INTERPLJ FUNCTION'
             ELSE
                WRITE(*,'(A,F15.5)') ' KEYDECIDE> COST FUNCTION IN DIJKSTRA ALGORITHM FROM MAXIMUM ENERGY ON INTERPOLATION, DIST=',&
   &                                 INTERPDIFF  
             ENDIF
          ELSE
               INTSTR=WI(COSTFUNCTIONPOWER)
               WRITE(*,'(A)') ' KEYDECIDE> COST FUNCTION IN DIJKSTRA ALGORITHM IS D^'//TRIM(INTSTR)
          ENDIF
     END SUBROUTINE KEYDECIDEPRINT
END MODULE KEYDECIDE
