
!     --------------------- MOVE  ----------------------

      SUBROUTINE MOVE(JSTRT,JFINS,ISHKIT,NMDIFV,I_QUENCH)
 
!     --------------------------------------------------

!     MOVE   IS THE DRIVING SUBROUTINE FOR CARRYING OUT
!            THE MOLECULAR DYNAMICS: ANNEALING SCHEDULE,
!            VERLET ALGORITHM, AND OBSERVABLE STATISTICS

!     ARGUMENTS:

!        JSTRT - FIRST MODIFIED SITE
!        JFINS - LAST MODIFIES SITE
!        ISHKIT- USED TO TRACK NUMBER OF SHAKE 
!                ITERATIONS
!        NMDIFV- NUMBER OF INTERMEDIATE STRUCTURES SAVED
!                ON MOVIE TAPE
!     ---------------------------------------------------

!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
!                               FILTRATION
!        I_PRO                        INDEX OVER PROTEINS
!        I_STEP                        INDEX OVER TIME STEPS PER TEMPERATURE
!        I_TEMP                        INDEX OVER TEMPERATURES
!        ITCNT                        INCREMENT T (TEMPERATURE) COUNTER

!     NMSTEP IS THE NUMBER OF TIME STEPS PER TEMPERATURE

!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

     USE GLOBALS, ONLY:SO,WEIGHT_P_AP, I513,NUMPRO,I1,AVEP,NMRES,PRCORD,QRCORD, &
       SRCORD,TRCORD,ZRCORD,VELOCP,BONDLN,TEMTUR,TOLSHK,MAXSHK, &
       TIMSTP,NUMCRD,OARCHV,WORK1,WORK3,WORK4,ISEED,IRES,NMTEMP, &
       MOVANAL,INCMOV,OMOVI,OMOVISEG,NMSTEP,OPE_NO_BIAS,OKE, &
       OHDRGN,ORAMA,OOXY,OCHIRAL,OAMH,OAMHSR,OREP,OPE_WITH_BIAS, &
       OCCEV,OOEV,I526,I525,I527,I528,I514,NMDIF,OAMHLR, &
       OAMHMR,OBIAS_RG,OHDRGN_S,OHDRGN_M,OHDRGN_L,OHDRGN_SEQ, &
       ONONADD,OCON_P_AP,I_ETIM_STEP,OPE_PLUS_KE, &
       I_ETIM,QUENCH,NQUENCH,N_Q_ANNEAL_A,N_Q_ANNEAL_B, &
       Q0_A,Q0_B,Q0_INC_A,Q0_INC_B,QVALUE_A,QVALUE_B, &
       MAXPRO,OOBIASSEGA,OOBIASSEGB,Q0_SAFE_A, Q0_SAFE_B, &
       ITGRD,TEMTUR_QUENCH

!       USE AMH_INTERFACES, ONLY:E_WRITE,PTR_SUB,ARBITRATE
       USE AMH_INTERFACES, ONLY:E_WRITE,PTR_SUB
      USE GLOBALS_ALT, ONLY:DO_SEND_OUTPUT,COUNT_ALT,T_ALT

      IMPLICIT NONE

!     PASSED ARGUMENT DECLARATIONS:

         INTEGER :: JSTRT,JFINS,ISHKIT,I_QUENCH,I504,I501

!     INTERNAL VARIABLES:

         LOGICAL :: TEMPAV,BDSHAK
 
         INTEGER :: ITCNT,NMDIFV,IBEGN,IDUMMY,NMOVIES,I
         REAL :: TEMPH,TOTKE(MAXPRO)

!,ARBITRATE

     INTEGER :: I_PRO, I_STEP, I_TEMP, I_GRID_NUM
     INTEGER :: REPOUT_MOVE, REP_MOVE
     DOUBLE PRECISION :: E_TEMP(5),T_TEMP(5)

     DOUBLE PRECISION :: DD(5), VARRRR(5)
     DOUBLE PRECISION:: CC(5), VARRR(5)
     INTEGER :: A(10), VARA(10) 
     INTEGER :: B(10), VARB(10)
     INTEGER :: C(10), VARC(10) 
     INTEGER :: D(10), VARD(10) 
     INTEGER :: BB(5), VARR(5)

     POINTER (EE, VARRRR)
     POINTER (TT, VARRR)
     POINTER (INET1, VARA) ! VAR IS THE POINTEE
                          ! P IS THE INTEGER POINTER
     POINTER (INET2, VARB) ! VAR IS THE POINTEE
     POINTER (INET3, VARC) ! VAR IS THE POINTEE
     POINTER (INET4, VARD) ! VAR IS THE POINTEE
     POINTER (PORT_NUMBER, VARR)

!     REQUIRED SUBROUTINES
        EXTERNAL MDCTRL,YNORM,INITV
      
          EE = LOC(DD)
          TT = LOC(CC)
          INET1 = LOC (A)
          INET2 = LOC(B)
          INET3 = LOC(C)
          INET4 = LOC(D)
          PORT_NUMBER = LOC(BB)

          A(1) = 132
          B(1) = 239
          C(1) = 157
          D(1) = 126
          BB(1) = 123457

!         WRITE(6,*) 'SERVER IP INFO'
!         WRITE(6,*) 'INET1 = ', INET2
!         WRITE(6,*) 'INET2 = ', INET2
!         WRITE(6,*) 'INET3 = ', INET3
!         WRITE(6,*) 'INET4 = ', INET4 

        NMDIFV = 0
        TEMPH = 0.0

!     --------------------- BEGIN -----------------------

!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
!     INITIALIZE ARCHIVE ARRAYS

      DO 513 I513=1,NMDIF
         DO 516 I_PRO=1,NUMPRO
            DO 100 I1=1,50
              AVEP(I_PRO,1,I1,I513)=0.0
              AVEP(I_PRO,2,I1,I513)=0.0
100            CONTINUE
  516    CONTINUE
  513 CONTINUE

!     ISHKIT TRACKS THE NUMBER OF SHAKE ITERATIONS

      ISHKIT=0

!     IF BDSHAK IS TRUE, THEN SHAKE FAILED

      BDSHAK=.FALSE.

!    NEW ANNEALLING SCHEDULE FOR QUENCHING   
!    MOVE TEMTUR_QUENCH INTO TEMTUR FROM RESTRT.F
     
         IF (QUENCH) THEN
          DO 504 I504=1, NQUENCH
!           DO 540 I_GRID_NUM=1,4
            IF( ITGRD(1).GT.0 )THEN
             DO 501 I501=1,ITGRD(1)
              TEMTUR(I501)=TEMTUR_QUENCH(I501,I_QUENCH)
!          WRITE(6,*)'IN MOVE TEMTUR_QUENCH STEPS STRUCTURE',
!     * TEMTUR(I501),TEMTUR_QUENCH(I501,I504),I_GRID_NUM,I501,I_QUENCH

501          CONTINUE
            ENDIF  !  ITGRD(GRID_NUM)
!540        CONTINUE
504       CONTINUE
         ENDIF

!     IF NO HEATBATH, THEN SET INITIAL VELOCITIES

!################# START OF NORMAL RUN #################

       CALL INITV(PRCORD,QRCORD,SRCORD, &
                  TRCORD,ZRCORD,VELOCP,BONDLN,TEMTUR(1), &
                  JSTRT,JFINS,TOLSHK,MAXSHK,BDSHAK, &
                  TIMSTP,NUMPRO,ISHKIT, &
                  NUMCRD,OARCHV,WORK1, &
                  WORK3,WORK4,ISEED,IRES)
         IBEGN=1

!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC


!     SET COUNTER FOR T AVERAGES
      ITCNT=1

!     WRITE HEADER FOR MOVIE FILE
      IF( .NOT.MOVANAL )THEN
         NMDIFV=INT( FLOAT(NMTEMP)/FLOAT(INCMOV) )

         IF ( .NOT.QUENCH ) THEN
         WRITE(OMOVI,334)NMRES,NUMCRD,NUMPRO,NMDIFV
         WRITE(OMOVISEG,334)NMRES,NUMCRD,NUMPRO,NMDIFV
         ELSEIF (I_QUENCH.EQ.1) THEN
         WRITE(OMOVI,334)NMRES,NUMCRD,NUMPRO,NQUENCH
         ENDIF
  334    FORMAT(4(I8,1X),' NMRES NMCRD NUMPRO NMSNAP')
      ENDIF


!     SET COUNTER FOR NUMBER OF SAVED STRUCTURES FOR
!     EVALUATING |R|

      NMDIFV=0

!!!!!!!!!!!!!!!!  START OF LOOP OVER TEMPERATURES  !!!!!!!!!!!!!!!!!!!!!!
!     PERFORM NMTEMP TIMESTEPS FOR EACH PROTEIN


      IF (MOVANAL) THEN
        WRITE(SO,*) 'OPENING MOVIE FILE'
        OPEN(11,FILE='MOVIE_IN',STATUS='OLD')

          READ(11,1040) NMOVIES
          NMTEMP=NMOVIES
          INCMOV=1
1040        FORMAT(31X,I4)
      ENDIF

      DO 509 I_TEMP=IBEGN,NMTEMP
        IF (I_TEMP.LT.N_Q_ANNEAL_A) THEN
!  TEMP FIX DIVIDING BY 0 !!!!!
         Q0_A = Q0_SAFE_A +  &
                Q0_INC_A*REAL(N_Q_ANNEAL_A-I_TEMP)/REAL(N_Q_ANNEAL_A)
         Q0_B = Q0_SAFE_B +  &
                Q0_INC_B*REAL(N_Q_ANNEAL_B-I_TEMP)/REAL(N_Q_ANNEAL_B)
        ELSE
          Q0_A=Q0_SAFE_A
          Q0_B=Q0_SAFE_B
        ENDIF

      WRITE(SO,474)I_TEMP,TEMTUR(I_TEMP),QVALUE_A,QVALUE_B
474    FORMAT('ITEMP,TEMP,QA,QB',  &
                         1X,I5,1X,F4.2,1X,F6.4,1X,F6.4)

        IF (I_TEMP.EQ.NMTEMP) THEN
            WRITE(SO,*) 'SIMULATION COMPLETED'
        ENDIF

        IF (MOVANAL) THEN
          READ(11,1041) IDUMMY,IDUMMY,IDUMMY,TEMTUR(I_TEMP),IDUMMY
          WRITE(SO,*) 'TEMPERATURE IS',TEMTUR(I_TEMP)
1041      FORMAT(3(I6,1X),F8.4,1X,I5)
          DO 10175 I=1,NMRES
               READ(11,1020) PRCORD(I,1,1,1), &
               PRCORD(I,2,1,1),PRCORD(I,3,1,1), &
               PRCORD(I,1,1,2), &
               PRCORD(I,2,1,2),PRCORD(I,3,1,2), &
               PRCORD(I,1,1,3), &
               PRCORD(I,2,1,3),PRCORD(I,3,1,3)
1020       FORMAT(4X,3(F8.3,1X),4X,3(F8.3,1X),4X,3(F8.3,1X))

10175     CONTINUE
        ENDIF

!        SET RMS VELOCITY FOR CURRENT T

         TEMPH=SQRT(TEMTUR(I_TEMP))

!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
!        DETERMINE WHETHER AVERAGES SHOULD BE CARRIED
!        AT THIS T

         IF (QUENCH) THEN
           IF (I_TEMP.EQ.NMTEMP) THEN !IF QUENCH ONLY PRINT INFO AT END
              TEMPAV=.TRUE.
           ELSE
             TEMPAV=.FALSE.
           ENDIF
         ELSE
           IF( MOD(I_TEMP,INCMOV).EQ.0 )THEN !IN NORMAL CASE PRINT INFO EVERY INCMOV STEPS
              TEMPAV=.TRUE.
           ELSE
              TEMPAV=.FALSE.
           ENDIF
         ENDIF

!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
!        PERFORM NMSTEP TIMESTEPS FOR THE CURRENT TEMPERATURE

         IF (MOVANAL) NMSTEP=1
 
         DO 510 I_STEP=1,NMSTEP
            COUNT_ALT=I_TEMP/INCMOV                   ! START FOR ALTPOT
            T_ALT=TEMTUR(I_TEMP)                                   
            DO_SEND_OUTPUT=.FALSE.                                 
            IF( (TEMPAV .AND. I_STEP.EQ.NMSTEP)     &              
             .OR. (I_ETIM .AND. MOD(I_STEP,I_ETIM_STEP).EQ.0) )THEN 
              DO_SEND_OUTPUT=.TRUE.                                 
            ENDIF                                     ! END FOR ALTPOT

            CALL MDCTRL(JSTRT,JFINS,TEMPAV,ISHKIT,BDSHAK,ITCNT,TOTKE)
            IF( (TEMPAV .AND. I_STEP.EQ.NMSTEP) &
             .OR. (I_ETIM .AND. MOD(I_STEP,I_ETIM_STEP).EQ.0) )THEN
              CALL E_WRITE(AVEP(:,:,:,ITCNT),TOTKE,TEMTUR(I_TEMP), &
                                       NUMPRO,I_TEMP,INCMOV)

      E_TEMP(1)=  &
         DBLE(AVEP(1,1,1,ITCNT)+AVEP(1,1,2,ITCNT)+AVEP(1,1,3,ITCNT) + &
          AVEP(1,1,4,ITCNT)+AVEP(1,1,5,ITCNT)+AVEP(1,1,9,ITCNT) + &
                     AVEP(1,1,11,ITCNT)+AVEP(1,1,17,ITCNT) + &
                       -WEIGHT_P_AP(1)*AVEP(1,1,40,ITCNT) + &
                       -WEIGHT_P_AP(2)*AVEP(1,1,41,ITCNT) + &
                       -WEIGHT_P_AP(3)*AVEP(1,1,42,ITCNT))

         T_TEMP(1)=DBLE(TEMTUR(I_TEMP))
          CC(1) = T_TEMP(1)
          DD(1) = E_TEMP(1)
        WRITE(SO,*) "ENERGY TEMP BEFORE ARB CALL  ",E_TEMP(1),T_TEMP(1)

      REP_MOVE=20
!      IF ( MOD(I_TEMP,REP_MOVE) .EQ. 0)THEN 
!        WRITE(SO,*)"REPLICA MOVE I_STEP REP_MOVE MOD  ", &
!                         I_TEMP,REP_MOVE,MOD(I_TEMP,REP_MOVE)
!       CALL ARBITRATE (EE,TT,INET1,INET2,INET3,INET4,PORT_NUMBER)
!      ENDIF

      REPOUT_MOVE=5
!      IF ( MOD(I_TEMP,REPOUT_MOVE) .EQ. 0) THEN
!        WRITE(SO,*)"OUTPUT I_TEMP REP_MOVE MOD  ",       &
!                    I_TEMP,REPOUT_MOVE,MOD(I_TEMP,REP_MOVE)
!      ENDIF

      ENDIF

!CCCCCCCCCCCCCCCCCCCCCC
!           SHAKE WAS UNSUCCESSFUL, RETURN AND PERFORM FINAL
!           ANALYSIS

            IF( BDSHAK )THEN
               WRITE(OARCHV,144)I_TEMP,TEMTUR(I_TEMP),I_STEP
  144          FORMAT(/'SORRY BUCKY -- SHAKE MISFIRE ', &
                     I6,' T ',1PE10.3,' T ',I5)
               GO TO 300

            ENDIF


              WRITE(OARCHV,*)'XXXXXXXXXXXXXXXXXXXXXXXXXXX'


!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
!   SAVE STRUCTURE FOR LATER MOVIE ANALYSIS, IF THE TIME IS RIGHT
       IF( MOD(I_TEMP,INCMOV).EQ.0 .AND. (.NOT.MOVANAL)  &
             .AND. (I_STEP.EQ.NMSTEP-1.OR.NMSTEP.EQ.1)) THEN
!        IF( 
!    *        MOD(I_STEP,20).EQ.0) THEN

!           SAVE THE CURENT STRUCTURE

            NMDIFV=NMDIFV + 1

            DO 526 I526=1,NUMPRO
                IF (.NOT. QUENCH) THEN
              WRITE(OMOVI,683)I526,NMDIFV,I_STEP-1,TEMTUR(I_TEMP),I_TEMP
 683          FORMAT(3(I6,1X),F8.4,1X,I5,' STUCT SNAP T T TID')
              DO 525 I525=1,NMRES
                  WRITE(OMOVI,332) &
                 (PRCORD(I525,I1,I526,1),I1=1,3), &
                 (PRCORD(I525,I1,I526,2),I1=1,3), &
                 (PRCORD(I525,I1,I526,3),I1=1,3)

332     FORMAT('CA: ',3(F8.3,1X),'CB: ',3(F8.3,1X),'OX: ', 3(F8.3,1X))
  525         CONTINUE
                ENDIF   ! QUENCH

  526       CONTINUE


            IF (I_TEMP.EQ.NMTEMP) THEN
            DO 527 I527=1,NUMPRO
                IF (QUENCH) THEN
                WRITE(OMOVI,683)I527,NQUENCH,I_QUENCH, &
                                        TEMTUR(I_TEMP),I_TEMP
                ELSE
                WRITE(OMOVISEG,683)I527,NMDIFV,I_STEP-1, &
                                        TEMTUR(I_TEMP),I_TEMP
                ENDIF
                DO 528 I528=1,NMRES
                    IF (QUENCH) THEN
                     WRITE(OMOVI,332)                &
                   (PRCORD(I528,I1,I527,1),I1=1,3), &
                   (PRCORD(I528,I1,I527,2),I1=1,3), &
                   (PRCORD(I528,I1,I527,3),I1=1,3)
                    ELSE
                    WRITE(OMOVISEG,332)              &
                    (PRCORD(I528,I1,I527,1),I1=1,3), &
                    (PRCORD(I528,I1,I527,2),I1=1,3), &
                    (PRCORD(I528,I1,I527,3),I1=1,3)
                    ENDIF
  528           CONTINUE
  527         CONTINUE
            ENDIF

         ENDIF

!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC




  510    CONTINUE
!%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

!        INCREMENT COUNTER FOR OBSERVABLES AS 
!        FUNCTION OF T

         IF( TEMPAV )ITCNT=ITCNT + 1

!        PERFORM COLLISIONS FOR NEXT T

         CALL INITV(PRCORD,QRCORD,SRCORD,  &
                   TRCORD,ZRCORD,VELOCP,BONDLN, &
                   TEMTUR(I_TEMP),JSTRT,JFINS,TOLSHK, &
                   MAXSHK,BDSHAK,TIMSTP,NUMPRO, &
                   ISHKIT,NUMCRD,  &
                   OARCHV,WORK1,WORK3, &
                   WORK4,ISEED,IRES)

  509 CONTINUE

        IF (I_QUENCH.EQ.NQUENCH) THEN
        CLOSE(OHDRGN)
        CLOSE(OHDRGN_S)
        CLOSE(OHDRGN_M)
        CLOSE(OHDRGN_L)
        CLOSE(OHDRGN_SEQ)
        CLOSE(ORAMA)
        CLOSE(OOXY)
        CLOSE(OCHIRAL)
        CLOSE(OPE_NO_BIAS)
        CLOSE(OPE_WITH_BIAS)
        CLOSE(OPE_PLUS_KE)
        CLOSE(OKE)
        CLOSE(OAMH)
        CLOSE(OAMHSR)
        CLOSE(OAMHLR)
        CLOSE(OAMHMR)
        CLOSE(OREP)
        CLOSE(OCON_P_AP)
        CLOSE(ONONADD)
        CLOSE(OCCEV)
        CLOSE(OOEV)
!        CLOSE(OBIAS)
!        CLOSE(OBIAS_RG)
        CLOSE(OOBIASSEGA)
        CLOSE(OOBIASSEGB)

        ENDIF



!       WRITE(6,*)' MOVE '
!       WRITE(6,*)'OARCHV 30 ',OARCHV
!       WRITE(6,*)'OMOVI 55 ',OMOVI
!       WRITE(6,*)'OHDRGN  ',OHDRGN
!       WRITE(6,*)'OHDRGN_S 81 ',OHDRGN_S
!       WRITE(6,*)'OHDRGN_M 82',OHDRGN_M
!       WRITE(6,*)'OHDRGN_L 83',OHDRGN_L
!       WRITE(6,*)'OHDRGN_SEQ 85',OHDRGN_SEQ
!       WRITE(6,*)'ORAMA 61 ',ORAMA
!       WRITE(6,*)'OOXY 62',OOXY
!       WRITE(6,*)'OCHIRAL 63 ',OCHIRAL
!       WRITE(6,*)'OAMH  64',OAMH
!       WRITE(6,*)'OTOTAL 65 ',OTOTAL
!       WRITE(6,*)'OAMHSR 66 ',OAMHSR
!       WRITE(6,*)'OPE 67 ',OPE
!       WRITE(6,*)'OKE  73',OKE
!       WRITE(6,*)'OAMHLR 68 ',OAMHLR
!       WRITE(6,*)'OAMHMR 78 ',OAMHMR
!       WRITE(6,*)'ONONADD 84 ',ONONADD
!       WRITE(6,*)'OAMHLR 68 ',OAMHLR
!       WRITE(6,*)'OAMHMR 78 ',OAMHMR
!       WRITE(6,*)'ONONADD  84',ONONADD
!       WRITE(6,*)'OCON_P_AP 86',OCON_P_AP
!       WRITE(6,*)'OBIAS_RG 77',OBIAS_RG
!       WRITE(6,*)'OMOVISEG 75',OMOVISEG
!       WRITE(6,*)'OOBIASSEGA 87 ',OOBIASSEGA
!       WRITE(6,*)'OOBIASSEGB 88',OOBIASSEGB


!!!!!!!!!!!!!!!!!!!!   END OF LOOP OVER TEMPERATURES !!!!!!!!!!!!!!!!!!!!!!!!

  300 CONTINUE

!     PREPARE 'OBSERVABLES' FOR PRINTING AS A 
!     FUNCTION OF T

!     SET NORMALIZATION FACTORS

      ITCNT=ITCNT - 1

      TEMPH=1.0/FLOAT(NMSTEP)

!        NORMALIZE 1ST MOMENTS

      DO 514 I514=1,ITCNT
         CALL YNORM(NUMPRO,1,NUMPRO,AVEP(1,1,5,I514), &
                   TEMPH)
514 CONTINUE


!     ---------------------- DONE -----------------------

      RETURN
      END
