      MODULE ALTPOT_INTERFACES
        
        
!!!!!!!!!!!!!!! PUBLIC !!!!!!!!!!!!!!!!!!!!!!
        INTERFACE
           SUBROUTINE READ_INPUT_ALT()
             USE GLOBALS_ALT, ONLY : ALTPOTFLAG,KAPPA_ALT,TRESHOLD_ALT,KAPPA_WELL,ONEBODYFLAG &
                  , ONEBODY_TYPE,KAPPA_OB,ALIMITS_OB, DEBUG_NUMER_FORCES
             IMPLICIT NONE
           END SUBROUTINE READ_INPUT_ALT
        END INTERFACE

        INTERFACE
           SUBROUTINE ALTPOT_MASTER(PRO_CORD,F_CORD,E,TEMPAV,NMRES)
             USE AMHGLOBALS,  ONLY : MAXSIZ,MAXCRD,R_MIN,R_MAX, IRES
             USE GLOBALS_ALT, ONLY : DEBUG_NUMER_FORCES, DEBUGFLAG,KAPPA_ALT,TRESHOLD_ALT &
                  ,ALTPOTFLAG,MAX_WELL_ALT,KAPPA_WELL,OUTPUT_STEPSIZE_ALT &
                  , OUTPUT_STEP_ALT ,DO_SEND_OUTPUT , ONEBODYFLAG, ONEBODY_TYPE 
             IMPLICIT NONE
             INTEGER, INTENT(IN):: NMRES
              DOUBLE PRECISION, INTENT(IN) ::  PRO_CORD(MAXSIZ,3,MAXCRD)
             LOGICAL, INTENT(IN):: TEMPAV
!              DOUBLE PRECISION, INTENT(OUT) :: F_CORD(MAXSIZ,3,MAXCRD),E(:,:)
              DOUBLE PRECISION F_CORD(MAXSIZ,3,MAXCRD),E
           END SUBROUTINE ALTPOT_MASTER
        END INTERFACE

!!!!!!!!!!!!!!! PRIVATE !!!!!!!!!!!!!!!!!!!!!!

        INTERFACE
           SUBROUTINE CALC_THETA_ALT(THETA, THETA_DOT, XYZ_DIST, RMIN, RMAX,KAPPA,NMRES,  I_WELL)
             USE AMHGLOBALS,  ONLY : MAXSIZ,IRES
             USE GLOBALS_ALT, ONLY : MAX_WELL_ALT
             IMPLICIT NONE
             INTEGER, INTENT(IN) ::  I_WELL,NMRES
              DOUBLE PRECISION, INTENT(IN) ::  KAPPA,RMIN,RMAX
              DOUBLE PRECISION, INTENT(IN) ::  XYZ_DIST(MAXSIZ,MAXSIZ)
              DOUBLE PRECISION, INTENT(OUT) ::  THETA(MAXSIZ,MAXSIZ,MAX_WELL_ALT),THETA_DOT(MAXSIZ,MAXSIZ,MAX_WELL_ALT)
           END SUBROUTINE CALC_THETA_ALT
        END INTERFACE



        INTERFACE
           SUBROUTINE CALC_SUM_THETA_DOT_ALT(SUM_THETA_DOT,THETA_DOT,XYZ_UNIT_VECT,NMRES)
             USE GLOBALS_ALT, ONLY : MAX_WELL_ALT
             USE AMHGLOBALS,  ONLY : MAXSIZ
             IMPLICIT NONE
             INTEGER, INTENT(IN) ::  NMRES
              DOUBLE PRECISION, INTENT(IN) ::  THETA_DOT(MAXSIZ,MAXSIZ,MAX_WELL_ALT)
              DOUBLE PRECISION, INTENT(IN) :: XYZ_UNIT_VECT(MAXSIZ,MAXSIZ,3)
              DOUBLE PRECISION, INTENT(OUT) :: SUM_THETA_DOT(MAXSIZ,3)
           END SUBROUTINE CALC_SUM_THETA_DOT_ALT
        END INTERFACE


        INTERFACE
           SUBROUTINE CALC_A_ALT(A,THETA,NMRES)
             USE GLOBALS_ALT, ONLY : MAX_WELL_ALT
             USE AMHGLOBALS,  ONLY : MAXSIZ
             IMPLICIT NONE
             INTEGER, INTENT(IN) ::  NMRES
              DOUBLE PRECISION, INTENT(IN) ::   THETA(MAXSIZ,MAXSIZ,MAX_WELL_ALT)
              DOUBLE PRECISION, INTENT(OUT) ::  A(MAXSIZ)
           END SUBROUTINE CALC_A_ALT
        END INTERFACE

        INTERFACE
           DOUBLE PRECISION FUNCTION CALC_DDA_ONEBODY(A_I,ITYPE)
             USE GLOBALS_ALT, ONLY : ONEBODY_GAMMA,KAPPA_OB,ALIMITS_OB,ONEBODY_TYPE
             USE AMHGLOBALS,  ONLY : MAXSIZ
             IMPLICIT NONE
!             INTEGER, INTENT(IN) :: ITYPE
!             DOUBLE PRECISION, INTENT(IN) :: A_I(MAXSIZ)
!             INTEGER ITYPE
             DOUBLE PRECISION A_I
             INTEGER ITYPE
           END FUNCTION CALC_DDA_ONEBODY
        END INTERFACE

        INTERFACE
           DOUBLE PRECISION FUNCTION CALC_ENERGY_ALT(THETA,SIGMA,E_ALT,NMRES,I_WELL)
             USE AMHGLOBALS,  ONLY : MAXSIZ,MAXCRD,IRES
             USE GLOBALS_ALT, ONLY : MAX_WELL_ALT,ALTGAMMA
             IMPLICIT NONE
             INTEGER NMRES,I_WELL
             DOUBLE PRECISION THETA(MAXSIZ,MAXSIZ,MAX_WELL_ALT),E_ALT(2,MAX_WELL_ALT)
             DOUBLE PRECISION SIGMA(MAXSIZ,MAXSIZ),TIJ
           END FUNCTION CALC_ENERGY_ALT
        END INTERFACE


        INTERFACE
           SUBROUTINE CALC_FORCE_ALT(F_CORD,PRO_CORD,THETA,THETA_DOT,SIGMA,XYZ_UNIT_VECT,NMRES &
                , I_WELL, A, KAPPA, TRESHOLD)
             USE AMHGLOBALS,  ONLY : MAXSIZ,MAXCRD,IRES
             USE GLOBALS_ALT, ONLY : ALTGAMMA,MAX_WELL_ALT,DEBUGFLAG,ACCUMULATED_TIME
             IMPLICIT NONE
             INTEGER, INTENT(IN) :: I_WELL, NMRES
              DOUBLE PRECISION, INTENT(IN) :: KAPPA, TRESHOLD
              DOUBLE PRECISION, INTENT(IN) :: THETA(MAXSIZ,MAXSIZ,MAX_WELL_ALT),THETA_DOT(MAXSIZ,MAXSIZ,MAX_WELL_ALT)
              DOUBLE PRECISION, INTENT(IN) :: SIGMA(MAXSIZ,MAXSIZ), A(MAXSIZ), XYZ_UNIT_VECT(MAXSIZ,MAXSIZ,3)
              DOUBLE PRECISION, INTENT(IN) :: PRO_CORD(MAXSIZ,3,MAXCRD)
              DOUBLE PRECISION, INTENT(OUT):: F_CORD(MAXSIZ,3,MAXCRD)
           END SUBROUTINE CALC_FORCE_ALT
        END INTERFACE


        INTERFACE
           SUBROUTINE CALC_FORCE_ALT_1(F_CORD,PRO_CORD,THETA,THETA_DOT,SIGMA,XYZ_UNIT_VECT,NMRES &
                , I_WELL, A, KAPPA, TRESHOLD, HEAVISIDE, HEAVISIDE_DOT)
             USE AMHGLOBALS,  ONLY : MAXSIZ,MAXCRD,IRES
             USE GLOBALS_ALT, ONLY : ALTGAMMA,MAX_WELL_ALT,DEBUGFLAG,ACCUMULATED_TIME
             IMPLICIT NONE
             INTEGER, INTENT(IN) :: I_WELL, NMRES
              DOUBLE PRECISION, INTENT(IN) :: KAPPA, TRESHOLD
              DOUBLE PRECISION, INTENT(IN) :: THETA(MAXSIZ,MAXSIZ,MAX_WELL_ALT),THETA_DOT(MAXSIZ,MAXSIZ,MAX_WELL_ALT)
              DOUBLE PRECISION, INTENT(IN) :: SIGMA(MAXSIZ,MAXSIZ), A(MAXSIZ), XYZ_UNIT_VECT(MAXSIZ,MAXSIZ,3)
              DOUBLE PRECISION, INTENT(IN) :: PRO_CORD(MAXSIZ,3,MAXCRD)
              DOUBLE PRECISION, INTENT(IN) :: HEAVISIDE(MAXSIZ), HEAVISIDE_DOT(MAXSIZ)
              DOUBLE PRECISION, INTENT(OUT):: F_CORD(MAXSIZ,3,MAXCRD)
           END SUBROUTINE CALC_FORCE_ALT_1
         END INTERFACE


        INTERFACE
           SUBROUTINE CALC_FORCE_ALT_2(F_CORD,PRO_CORD,THETA,THETA_DOT,SIGMA,XYZ_UNIT_VECT,NMRES &
                , I_WELL, A, KAPPA, TRESHOLD, HEAVISIDE, HEAVISIDE_DOT)
             USE AMHGLOBALS,  ONLY : MAXSIZ,MAXCRD,IRES
             USE GLOBALS_ALT, ONLY : ALTGAMMA,MAX_WELL_ALT,DEBUGFLAG,ACCUMULATED_TIME
             IMPLICIT NONE
             INTEGER, INTENT(IN) :: I_WELL, NMRES
              DOUBLE PRECISION, INTENT(IN) :: KAPPA, TRESHOLD
              DOUBLE PRECISION, INTENT(IN) :: THETA(MAXSIZ,MAXSIZ,MAX_WELL_ALT),THETA_DOT(MAXSIZ,MAXSIZ,MAX_WELL_ALT)
              DOUBLE PRECISION, INTENT(IN) :: SIGMA(MAXSIZ,MAXSIZ), A(MAXSIZ), XYZ_UNIT_VECT(MAXSIZ,MAXSIZ,3)
              DOUBLE PRECISION, INTENT(IN) :: PRO_CORD(MAXSIZ,3,MAXCRD)
              DOUBLE PRECISION, INTENT(IN) :: HEAVISIDE(MAXSIZ), HEAVISIDE_DOT(MAXSIZ)
              DOUBLE PRECISION, INTENT(OUT):: F_CORD(MAXSIZ,3,MAXCRD)
           END SUBROUTINE CALC_FORCE_ALT_2
        END INTERFACE



        INTERFACE
           SUBROUTINE CALC_FORCE_ALT_3(F_CORD,PRO_CORD,THETA,THETA_DOT,SIGMA,XYZ_UNIT_VECT,NMRES &
                , I_WELL, A, KAPPA, TRESHOLD, HEAVISIDE, HEAVISIDE_DOT)
             USE AMHGLOBALS,  ONLY : MAXSIZ,MAXCRD,IRES
             USE GLOBALS_ALT, ONLY : ALTGAMMA,MAX_WELL_ALT,DEBUGFLAG,ACCUMULATED_TIME
             IMPLICIT NONE
             INTEGER, INTENT(IN) :: I_WELL, NMRES
              DOUBLE PRECISION, INTENT(IN) :: KAPPA, TRESHOLD
              DOUBLE PRECISION, INTENT(IN) :: THETA(MAXSIZ,MAXSIZ,MAX_WELL_ALT),THETA_DOT(MAXSIZ,MAXSIZ,MAX_WELL_ALT)
              DOUBLE PRECISION, INTENT(IN) :: SIGMA(MAXSIZ,MAXSIZ), A(MAXSIZ), XYZ_UNIT_VECT(MAXSIZ,MAXSIZ,3)
              DOUBLE PRECISION, INTENT(IN) :: PRO_CORD(MAXSIZ,3,MAXCRD)
              DOUBLE PRECISION, INTENT(IN) :: HEAVISIDE(MAXSIZ), HEAVISIDE_DOT(MAXSIZ)
              DOUBLE PRECISION, INTENT(OUT):: F_CORD(MAXSIZ,3,MAXCRD)
           END SUBROUTINE CALC_FORCE_ALT_3
        END INTERFACE



        INTERFACE
           SUBROUTINE CALC_HEAVISIDE_ALT(HEAVISIDE,HEAVISIDE_DOT,A,TRESHOLD,KAPPA)
             USE AMHGLOBALS,  ONLY : MAXSIZ
             IMPLICIT NONE
              DOUBLE PRECISION, INTENT(OUT) :: HEAVISIDE(MAXSIZ), HEAVISIDE_DOT(MAXSIZ)
              DOUBLE PRECISION, INTENT(IN) :: KAPPA,TRESHOLD
              DOUBLE PRECISION, INTENT(IN) ::  A(MAXSIZ)
           END SUBROUTINE CALC_HEAVISIDE_ALT
        END INTERFACE



        INTERFACE
           SUBROUTINE CALC_NUMERICAL_FORCE_ALT(PRO_CORD,F_ALT_NUMER_PAIR_POT,F_ALT_NUMER_OB_POT,NMRES)
             USE AMHGLOBALS,  ONLY : MAXSIZ,MAXCRD,R_MIN,R_MAX, IRES
             USE GLOBALS_ALT, ONLY : KAPPA_ALT,TRESHOLD_ALT &
                  ,ALTPOTFLAG,MAX_WELL_ALT,KAPPA_WELL, ONEBODYFLAG,ACCUMULATED_TIME
             IMPLICIT NONE
             INTEGER, INTENT(IN) :: NMRES
             DOUBLE PRECISION PRO_CORD(MAXSIZ,3,MAXCRD)
              DOUBLE PRECISION, INTENT(OUT) :: F_ALT_NUMER_PAIR_POT(MAXSIZ,3,MAXCRD), F_ALT_NUMER_OB_POT(MAXSIZ,3,MAXCRD)
           END SUBROUTINE CALC_NUMERICAL_FORCE_ALT
        END INTERFACE



        INTERFACE
           SUBROUTINE CALC_OB_DENSITY(A,NMRES)
             USE AMHGLOBALS,  ONLY : IRES,MAXSIZ
             USE GLOBALS_ALT, ONLY :MAX_LETTERS,OB_DNS_COUNT,OB_DENSITY,ALIMITS_OB
             IMPLICIT NONE
!            INTEGER, INTENT(IN) ::   NMRES
!               DOUBLE PRECISION, INTENT(IN) ::  A(MAXSIZ)
              INTEGER  NMRES
              DOUBLE PRECISION  A(MAXSIZ)
           END SUBROUTINE CALC_OB_DENSITY
        END INTERFACE



        INTERFACE
           SUBROUTINE CALC_ONEBODY_FORCE(F_CORD,THETA_DOT,XYZ_UNIT_VECT,NMRES,A)
             USE AMHGLOBALS,  ONLY : MAXSIZ,MAXCRD,IRES
             USE GLOBALS_ALT, ONLY : MAX_WELL_ALT,OB_DENSITY,OB_DNS_COUNT,MAX_LETTERS,ACCUMULATED_TIME
             IMPLICIT NONE
             INTEGER, INTENT(IN) :: NMRES

              DOUBLE PRECISION  A(MAXSIZ),THETA_DOT(MAXSIZ,MAXSIZ,MAX_WELL_ALT)
!              DOUBLE PRECISION, INTENT(IN) ::  A(MAXSIZ),THETA_DOT(MAXSIZ,MAXSIZ,MAX_WELL_ALT)
             DOUBLE PRECISION XYZ_UNIT_VECT(MAXSIZ,MAXSIZ,3)
              DOUBLE PRECISION, INTENT(OUT) :: F_CORD(MAXSIZ,3,MAXCRD)
           END SUBROUTINE CALC_ONEBODY_FORCE
        END INTERFACE



        INTERFACE
           DOUBLE PRECISION FUNCTION CALC_ONEBODY_POT(A,NMRES,E_OB)
             USE AMHGLOBALS,  ONLY : MAXSIZ,IRES
             USE GLOBALS_ALT, ONLY : ONEBODY_GAMMA,KAPPA_OB,ALIMITS_OB,ONEBODY_TYPE
             IMPLICIT NONE
!             INTEGER, INTENT(IN) ::  NMRES
!              DOUBLE PRECISION, INTENT(IN) ::  A(MAXSIZ)
!              DOUBLE PRECISION, INTENT(OUT) ::  E_OB(3)
              INTEGER  NMRES
              DOUBLE PRECISION A(MAXSIZ)
              DOUBLE PRECISION E_OB(3)
           END FUNCTION CALC_ONEBODY_POT
        END INTERFACE



        INTERFACE
           SUBROUTINE CALC_SIGMA_ALT(SIGMA,A,TRESHOLD,KAPPA,NMRES)
             USE AMHGLOBALS,  ONLY : MAXSIZ
             USE GLOBALS_ALT, ONLY : MAX_WELL_ALT
             IMPLICIT NONE
             INTEGER, INTENT(IN) ::   NMRES
              DOUBLE PRECISION, INTENT(IN) ::   KAPPA,TRESHOLD
              DOUBLE PRECISION, INTENT(OUT) ::   SIGMA(MAXSIZ,MAXSIZ),A(MAXSIZ)
           END SUBROUTINE CALC_SIGMA_ALT
        END INTERFACE




        INTERFACE
           SUBROUTINE CALC_XYZ(XYZ_DIST,XYZ_UNIT_VECT,PRO_CORD,NMRES)
             USE AMHGLOBALS,  ONLY : MAXSIZ,MAXCRD,IRES
             USE GLOBALS_ALT, ONLY : OB_DNS_COUNT,OUTFILE1_ALT
             IMPLICIT NONE
             INTEGER, INTENT(IN) :: NMRES
              DOUBLE PRECISION, INTENT(IN):: PRO_CORD(MAXSIZ,3,MAXCRD)
              DOUBLE PRECISION, INTENT(OUT) :: XYZ_DIST(MAXSIZ,MAXSIZ),XYZ_UNIT_VECT(MAXSIZ,MAXSIZ,3)
           END SUBROUTINE CALC_XYZ
        END INTERFACE



        INTERFACE
           SUBROUTINE DEFAULT_ALT()
             USE GLOBALS_ALT, ONLY : ALTPOTFLAG,KAPPA_ALT,TRESHOLD_ALT,KAPPA_WELL,KAPPA_OB, & 
                  DEBUG_NUMER_FORCES,OUTFILE1_ALT, OUTPUT_STEP_ALT, OUTPUT_STEPSIZE_ALT, & 
                  DO_SEND_OUTPUT,ONEBODYFLAG, ONEBODY_TYPE , TIMINGS_FILE_ALT, ACCUMULATED_TIME
             IMPLICIT NONE
           END SUBROUTINE DEFAULT_ALT
        END INTERFACE



        INTERFACE
           SUBROUTINE FINALIZE_ALT()
             USE GLOBALS_ALT, ONLY : OUTFILE1_ALT
             IMPLICIT NONE
           END SUBROUTINE FINALIZE_ALT
        END INTERFACE



        INTERFACE
           SUBROUTINE INIT_ONEBODY()
             USE GLOBALS_ALT, ONLY : ONEBODY_GAMMA,HP_SCALE,KAPPA_OB,ALIMITS_OB,ONEBODYFLAG &
                  ,MAX_LETTERS
           END SUBROUTINE INIT_ONEBODY
        END INTERFACE



        INTERFACE
           SUBROUTINE LONGSCALE()
             USE AMHGLOBALS,  ONLY:SO,  AB_C_OF_N_OLD,AB_C_OF_N_NEW,MAX_WELL,ALPHA_C_OF_N &
                  ,NUM_WELL,NMRES,N_LETTERS_CON
             USE GLOBALS_ALT, ONLY : ALTGAMMA
             IMPLICIT NONE
           END SUBROUTINE LONGSCALE
        END INTERFACE



        INTERFACE
           SUBROUTINE READ_ALTGAMMA()
             USE AMHGLOBALS,  ONLY : N_LETTERS_CON
             USE GLOBALS_ALT, ONLY : ALTGAMMA,ALTPOTFLAG,MAX_WELL_ALT,ONEBODY_GAMMA,ONEBODYFLAG
             IMPLICIT NONE
           END SUBROUTINE READ_ALTGAMMA
        END INTERFACE



        INTERFACE
           SUBROUTINE SEND_OUTPUT_ALT(A,E_ALT,NMRES,E_OB)
             USE AMHGLOBALS,  ONLY:SO, MAXSIZ
             USE GLOBALS_ALT, ONLY : OUTPUT_STEP_ALT, OUTPUT_STEPSIZE_ALT,OUTFILE1_ALT,DO_SEND_OUTPUT &
                  ,COUNT_ALT,T_ALT,MAX_WELL_ALT,TRESHOLD_ALT,OB_DENSITY,OB_DNS_COUNT &
                  , MAX_LETTERS,AMINOACIDS,ACCUMULATED_TIME
             IMPLICIT NONE
             INTEGER, INTENT(IN) ::  NMRES
              DOUBLE PRECISION, INTENT(IN) :: A(MAXSIZ),E_ALT(2,MAX_WELL_ALT),E_OB(3)
           END SUBROUTINE SEND_OUTPUT_ALT
        END INTERFACE



      END MODULE ALTPOT_INTERFACES

