      DOUBLE PRECISION FUNCTION CALC_ENERGY_ALT(THETA,SIGMA,E_ALT,NMRES,I_WELL)

        USE AMHGLOBALS,  ONLY : MAXSIZ,CUTOFF_CONT_LOW,TGSEQUENCES_AMW,NUMSEQ_AMW
        USE GLOBALS_ALT, ONLY : MAX_WELL_ALT,ALTGAMMA

        IMPLICIT NONE
        INTEGER I,J,I_WELL,NMRES,ITYPE,JTYPE,ISEQ
        DOUBLE PRECISION THETA(MAXSIZ,MAXSIZ,MAX_WELL_ALT),E_ALT(2,MAX_WELL_ALT)
        DOUBLE PRECISION SIGMA(MAXSIZ,MAXSIZ),TIJ

        E_ALT(1,I_WELL)=0.0D0
        E_ALT(2,I_WELL)=0.0D0

        DO ISEQ=1,NUMSEQ_AMW
          DO I=1,NMRES-CUTOFF_CONT_LOW 
!               ITYPE=IRES(I)
                ITYPE=TGSEQUENCES_AMW(I,ISEQ)
             DO J=I+CUTOFF_CONT_LOW,NMRES
!               JTYPE=IRES(J)
                JTYPE=TGSEQUENCES_AMW(J,ISEQ)

                TIJ=THETA(I,J,I_WELL)
                E_ALT(1,I_WELL)= E_ALT(1,I_WELL) - &
                  TIJ*(1.0-SIGMA(I,J)) * ALTGAMMA(ITYPE,JTYPE,1,I_WELL)
                E_ALT(2,I_WELL)= E_ALT(2,I_WELL) - & 
                  TIJ*SIGMA(I,J) * ALTGAMMA(ITYPE,JTYPE,2,I_WELL)
              IF(SIGMA(I,J).GT.1.01D0)THEN
                 WRITE(*,*)'SIGMA ',I,' ',J,' BIGGER THAN ONE',SIGMA(I,J)
                 STOP
              ELSEIF(SIGMA(I,J).LT. -0.01D0)THEN
                 WRITE(*,*)'SIGMA ',I,' ',J,' LESS THAN ZERO',SIGMA(I,J)
                 STOP
              ENDIF
           ENDDO
        ENDDO
       ENDDO

         E_ALT(1,I_WELL)=E_ALT(1,I_WELL)/REAL(NUMSEQ_AMW)
         E_ALT(2,I_WELL)=E_ALT(2,I_WELL)/REAL(NUMSEQ_AMW)

        CALC_ENERGY_ALT=E_ALT(1,I_WELL)+E_ALT(2,I_WELL)

        RETURN

      END FUNCTION CALC_ENERGY_ALT

      !------------------------------



      SUBROUTINE CALC_FORCE_ALT(F_CORD,PRO_CORD,THETA,THETA_DOT,SIGMA,XYZ_UNIT_VECT,NMRES &
                , I_WELL, A, KAPPA, TRESHOLD)
        USE AMHGLOBALS,  ONLY : MAXSIZ,MAXCRD, TGSEQUENCES_AMW,NUMSEQ_AMW
        USE GLOBALS_ALT, ONLY : MAX_WELL_ALT,DEBUG_NUMER_FORCES, DO_SEND_OUTPUT,ACCUMULATED_TIME
        USE ALTPOT_INTERFACES, ONLY: CALC_HEAVISIDE_ALT, CALC_FORCE_ALT_1, CALC_FORCE_ALT_2, CALC_FORCE_ALT_3

        IMPLICIT NONE
        INTEGER, INTENT(IN) :: I_WELL, NMRES
         DOUBLE PRECISION, INTENT(IN) :: KAPPA, TRESHOLD
         DOUBLE PRECISION, INTENT(IN) :: THETA(MAXSIZ,MAXSIZ,MAX_WELL_ALT),THETA_DOT(MAXSIZ,MAXSIZ,MAX_WELL_ALT)
         DOUBLE PRECISION, INTENT(IN) :: SIGMA(MAXSIZ,MAXSIZ), A(MAXSIZ), XYZ_UNIT_VECT(MAXSIZ,MAXSIZ,3)
         DOUBLE PRECISION, INTENT(IN) :: PRO_CORD(MAXSIZ,3,MAXCRD)
         DOUBLE PRECISION, INTENT(OUT):: F_CORD(MAXSIZ,3,MAXCRD)

        !LOCAL
        INTEGER I,J,IATOM,ISEQ,ITYPE
        DOUBLE PRECISION FORCES1(MAXSIZ,3,MAXCRD),FORCES2(MAXSIZ,3,MAXCRD),FORCES3(MAXSIZ,3,MAXCRD)
        DOUBLE PRECISION HEAVISIDE(MAXSIZ), HEAVISIDE_DOT(MAXSIZ)

        DOUBLE PRECISION START_TIME, END_TIME

!        EXTERNAL CPU_TIME   

        CALL CPU_TIME(START_TIME)

        FORCES1=0.D0
        FORCES2=0.D0
        FORCES3=0.D0

        CALL CALC_HEAVISIDE_ALT(HEAVISIDE,HEAVISIDE_DOT,A,TRESHOLD,KAPPA)

        CALL CALC_FORCE_ALT_1 (FORCES1,PRO_CORD,THETA,THETA_DOT,SIGMA,XYZ_UNIT_VECT,NMRES &
                              , I_WELL, A, KAPPA, TRESHOLD, HEAVISIDE, HEAVISIDE_DOT)
        CALL CALC_FORCE_ALT_2 (FORCES2,PRO_CORD,THETA,THETA_DOT,SIGMA,XYZ_UNIT_VECT,NMRES &
                              , I_WELL, A, KAPPA, TRESHOLD, HEAVISIDE, HEAVISIDE_DOT)
        CALL CALC_FORCE_ALT_3 (FORCES3,PRO_CORD,THETA,THETA_DOT,SIGMA,XYZ_UNIT_VECT,NMRES &
                              , I_WELL, A, KAPPA, TRESHOLD, HEAVISIDE, HEAVISIDE_DOT)

        
        F_CORD=F_CORD+FORCES1/REAL(NUMSEQ_AMW)+FORCES2/REAL(NUMSEQ_AMW)+FORCES3/REAL(NUMSEQ_AMW)


        IF(DO_SEND_OUTPUT .AND. DEBUG_NUMER_FORCES) THEN
           OPEN(UNIT=1561,FILE='ALT_ANAL_FORCE_DETAILED_1_PP',STATUS='UNKNOWN')  
           OPEN(UNIT=1562,FILE='ALT_ANAL_FORCE_DETAILED_2_PP',STATUS='UNKNOWN')  
           OPEN(UNIT=1563,FILE='ALT_ANAL_FORCE_DETAILED_3_PP',STATUS='UNKNOWN')  

          DO ISEQ=1,NUMSEQ_AMW
           DO I=1,NMRES
              ITYPE=TGSEQUENCES_AMW(I,ISEQ)
              IATOM=2
              IF (ITYPE .EQ. 8) IATOM=1
              WRITE(1561,1100) (FORCES1(I,J,IATOM),J=1,3), A(I)
              WRITE(1562,1100) (FORCES2(I,J,IATOM),J=1,3), A(I)
              WRITE(1563,1100) (FORCES3(I,J,IATOM),J=1,3), A(I)
           ENDDO
          ENDDO
           CLOSE(1561)
           CLOSE(1562)
           CLOSE(1563)
1100       FORMAT(400(1X,E12.6))
        ENDIF

        CALL CPU_TIME(END_TIME)
        ACCUMULATED_TIME(2)=ACCUMULATED_TIME(2)+(END_TIME-START_TIME)

        RETURN
      END SUBROUTINE CALC_FORCE_ALT

      !-----------------------------------------------

      SUBROUTINE CALC_FORCE_ALT_1 (F_CORD,PRO_CORD,THETA,THETA_DOT,SIGMA,XYZ_UNIT_VECT,NMRES &
           , I_WELL, A, KAPPA, TRESHOLD, HEAVISIDE, HEAVISIDE_DOT)
        USE AMHGLOBALS,  ONLY : MAXSIZ,MAXCRD,IRES, & 
                         CUTOFF_CONT_LOW,TGSEQUENCES_AMW,NUMSEQ_AMW
        USE GLOBALS_ALT, ONLY : ALTGAMMA,MAX_WELL_ALT,DEBUGFLAG,ACCUMULATED_TIME

        IMPLICIT NONE
        INTEGER, INTENT(IN) :: I_WELL, NMRES
         DOUBLE PRECISION, INTENT(IN) :: KAPPA, TRESHOLD
         DOUBLE PRECISION, INTENT(IN) :: THETA(MAXSIZ,MAXSIZ,MAX_WELL_ALT)
         DOUBLE PRECISION, INTENT(IN) :: THETA_DOT(MAXSIZ,MAXSIZ,MAX_WELL_ALT)
         DOUBLE PRECISION, INTENT(IN) :: SIGMA(MAXSIZ,MAXSIZ), A(MAXSIZ)
         DOUBLE PRECISION, INTENT(IN) :: XYZ_UNIT_VECT(MAXSIZ,MAXSIZ,3)
         DOUBLE PRECISION, INTENT(IN) :: PRO_CORD(MAXSIZ,3,MAXCRD)
         DOUBLE PRECISION, INTENT(IN) :: HEAVISIDE(MAXSIZ), HEAVISIDE_DOT(MAXSIZ)
         DOUBLE PRECISION, INTENT(OUT):: F_CORD(MAXSIZ,3,MAXCRD)


        ! LOCAL
        INTEGER K,I,J,KATOM,ITYPE,JTYPE,ISEQ
        DOUBLE PRECISION GAMMA1,GAMMA2,DELTAGAMMA_THETA,START_TIME, END_TIME

         DOUBLE PRECISION, PARAMETER :: EPSILON=0.0001D0

!        EXTERNAL CPU_TIME


        CALL CPU_TIME(START_TIME)

       DO ISEQ=1,NUMSEQ_AMW
         DO I=1,NMRES-CUTOFF_CONT_LOW,1 
          ITYPE=TGSEQUENCES_AMW(I,ISEQ)
!           ITYPE=IRES(I)
           DO J=I+CUTOFF_CONT_LOW,NMRES,1
! THIS OPTIMIZES THE SUBROUTINE 15-FOLD
              IF(ABS(THETA(I,J,I_WELL))<EPSILON) CYCLE 
              DO K=1,NMRES,1 
                 IF(I.EQ.K .OR. J.EQ.K) CYCLE
                 KATOM=2
                 IF (IRES(K) .EQ. 8) KATOM=1
                 JTYPE=TGSEQUENCES_AMW(J,ISEQ)
!                 JTYPE=IRES(J)
                 GAMMA1=ALTGAMMA(ITYPE,JTYPE,1,I_WELL)
                 GAMMA2=ALTGAMMA(ITYPE,JTYPE,2,I_WELL)
                 DELTAGAMMA_THETA=(GAMMA2-GAMMA1)*THETA(I,J,I_WELL)
                 
                 IF(ABS(I-K)>1 .AND. ABS(THETA_DOT(I,K,1))>EPSILON) THEN
                    F_CORD(K,:,KATOM)=F_CORD(K,:,KATOM) + &
                       DELTAGAMMA_THETA*HEAVISIDE_DOT(I)*HEAVISIDE(J)* &
                        THETA_DOT(I,K,1)*XYZ_UNIT_VECT(K,I,:)
                 ENDIF
                 IF(ABS(J-K)>1 .AND. ABS(THETA_DOT(J,K,1))>EPSILON) THEN
                    F_CORD(K,:,KATOM)=F_CORD(K,:,KATOM) + & 
                       DELTAGAMMA_THETA*HEAVISIDE(I)*HEAVISIDE_DOT(J)* & 
                        THETA_DOT(J,K,1)*XYZ_UNIT_VECT(K,J,:) 
                 ENDIF
              ENDDO
           ENDDO
        ENDDO
       ENDDO
        
        CALL CPU_TIME(END_TIME)
        ACCUMULATED_TIME(11)= ACCUMULATED_TIME(11) + END_TIME-START_TIME

        RETURN
      END SUBROUTINE CALC_FORCE_ALT_1

      !-----------------------------------------------


      SUBROUTINE CALC_FORCE_ALT_2 (F_CORD,PRO_CORD,THETA,THETA_DOT,SIGMA, & 
                XYZ_UNIT_VECT,NMRES &
           , I_WELL, A, KAPPA, TRESHOLD, HEAVISIDE, HEAVISIDE_DOT)
        USE AMHGLOBALS,  ONLY : MAXSIZ,MAXCRD,IRES, CUTOFF_CONT_LOW,TGSEQUENCES_AMW,NUMSEQ_AMW
        USE GLOBALS_ALT, ONLY : ALTGAMMA,MAX_WELL_ALT,DEBUGFLAG,ACCUMULATED_TIME

        IMPLICIT NONE
        INTEGER, INTENT(IN) :: I_WELL, NMRES
         DOUBLE PRECISION, INTENT(IN) :: KAPPA, TRESHOLD
         DOUBLE PRECISION, INTENT(IN) :: THETA(MAXSIZ,MAXSIZ,MAX_WELL_ALT)
         DOUBLE PRECISION, INTENT(IN) :: THETA_DOT(MAXSIZ,MAXSIZ,MAX_WELL_ALT)
         DOUBLE PRECISION, INTENT(IN) :: SIGMA(MAXSIZ,MAXSIZ), A(MAXSIZ)
         DOUBLE PRECISION, INTENT(IN) ::  XYZ_UNIT_VECT(MAXSIZ,MAXSIZ,3)
         DOUBLE PRECISION, INTENT(IN) :: PRO_CORD(MAXSIZ,3,MAXCRD)
         DOUBLE PRECISION, INTENT(IN) :: HEAVISIDE(MAXSIZ), HEAVISIDE_DOT(MAXSIZ)
         DOUBLE PRECISION, INTENT(OUT):: F_CORD(MAXSIZ,3,MAXCRD)


        ! LOCAL
        INTEGER K,I,KATOM,IATOM,ITYPE,KTYPE,ISEQ
        DOUBLE PRECISION GAMMA1,GAMMA2,SUM_GAMMA_SIGMA_THETA_DOT
        DOUBLE PRECISION FORCE(3)

        DOUBLE PRECISION START_TIME, END_TIME

!        EXTERNAL CPU_TIME

        CALL CPU_TIME(START_TIME)

       DO ISEQ=1,NUMSEQ_AMW
 
        DO K=1,NMRES-CUTOFF_CONT_LOW,1
           KATOM=2

!           IF (IRES(K) .EQ. 8) KATOM=1
!           KTYPE=IRES(K)
!   HACK FOR CONSISTENCY
            IF (TGSEQUENCES_AMW(K,1) .EQ. 8) KATOM=1

            KTYPE=TGSEQUENCES_AMW(K,ISEQ)

           DO I=K+CUTOFF_CONT_LOW,NMRES,1
              IATOM=2

              IF (IRES(I) .EQ. 8) IATOM=1
!              ITYPE=IRES(I)
!   HACK FOR CONSISTENCY
            IF (TGSEQUENCES_AMW(I,1) .EQ. 8) IATOM=1

              ITYPE=TGSEQUENCES_AMW(I,ISEQ)
              GAMMA1=ALTGAMMA(KTYPE,ITYPE,1,I_WELL)
              GAMMA2=ALTGAMMA(KTYPE,ITYPE,2,I_WELL)
              SUM_GAMMA_SIGMA_THETA_DOT=(GAMMA1*(1.0D0-SIGMA(K,I)) + & 
                               GAMMA2*SIGMA(K,I))*THETA_DOT(K,I,I_WELL)
              FORCE(:)=XYZ_UNIT_VECT(K,I,:)*SUM_GAMMA_SIGMA_THETA_DOT
              F_CORD(K,:,KATOM)=F_CORD(K,:,KATOM)+FORCE(:)
              F_CORD(I,:,IATOM)=F_CORD(I,:,IATOM)-FORCE(:)
           ENDDO
        ENDDO
       ENDDO

        CALL CPU_TIME(END_TIME)
        ACCUMULATED_TIME(12)= ACCUMULATED_TIME(12)+(END_TIME-START_TIME)
        RETURN

      END SUBROUTINE CALC_FORCE_ALT_2

      !-----------------------------------------------



      SUBROUTINE CALC_FORCE_ALT_3 (F_CORD,PRO_CORD,THETA,THETA_DOT,SIGMA,XYZ_UNIT_VECT,NMRES &
           , I_WELL, A, KAPPA, TRESHOLD, HEAVISIDE, HEAVISIDE_DOT)
        USE AMHGLOBALS,  ONLY : MAXSIZ,MAXCRD, CUTOFF_CONT_LOW,TGSEQUENCES_AMW,NUMSEQ_AMW
        USE GLOBALS_ALT, ONLY : ALTGAMMA,MAX_WELL_ALT,DEBUGFLAG,ACCUMULATED_TIME
        USE ALTPOT_INTERFACES, ONLY: CALC_SUM_THETA_DOT_ALT 

        IMPLICIT NONE
        INTEGER, INTENT(IN) :: I_WELL, NMRES
         DOUBLE PRECISION, INTENT(IN) :: KAPPA, TRESHOLD
         DOUBLE PRECISION, INTENT(IN) :: THETA(MAXSIZ,MAXSIZ,MAX_WELL_ALT)
         DOUBLE PRECISION, INTENT(IN) :: THETA_DOT(MAXSIZ,MAXSIZ,MAX_WELL_ALT)
         DOUBLE PRECISION, INTENT(IN) :: SIGMA(MAXSIZ,MAXSIZ), A(MAXSIZ)
         DOUBLE PRECISION, INTENT(IN) :: XYZ_UNIT_VECT(MAXSIZ,MAXSIZ,3)
         DOUBLE PRECISION, INTENT(IN) :: PRO_CORD(MAXSIZ,3,MAXCRD)
         DOUBLE PRECISION, INTENT(IN) :: HEAVISIDE(MAXSIZ), HEAVISIDE_DOT(MAXSIZ)
         DOUBLE PRECISION, INTENT(OUT):: F_CORD(MAXSIZ,3,MAXCRD)


        ! LOCAL
        INTEGER K,I,KATOM,IATOM,ITYPE,KTYPE,ISEQ
        DOUBLE PRECISION GAMMA1,GAMMA2,DELTAGAMMA_THETA
        DOUBLE PRECISION FORCE_K(3), FORCE_I(3)
        DOUBLE PRECISION SUM_THETA_DOT(MAXSIZ,3)


        DOUBLE PRECISION START_TIME, END_TIME

!        EXTERNAL CPU_TIME

        CALL CPU_TIME(START_TIME)

        CALL CALC_SUM_THETA_DOT_ALT(SUM_THETA_DOT,THETA_DOT,XYZ_UNIT_VECT,NMRES)

      DO ISEQ=1,NUMSEQ_AMW

        DO K=1,NMRES-CUTOFF_CONT_LOW,1
           KATOM=2

           IF (TGSEQUENCES_AMW(K,1) .EQ. 8) KATOM=1
           KTYPE=TGSEQUENCES_AMW(K,ISEQ)
                                                                                                     
!           IF (IRES(K) .EQ. 8) KATOM=1
!           KTYPE=IRES(K)
           DO I=K+CUTOFF_CONT_LOW,NMRES,1
              IATOM=2

           IF (TGSEQUENCES_AMW(I,1) .EQ. 8) IATOM=1
           ITYPE=TGSEQUENCES_AMW(I,ISEQ)

!              IF (IRES(I) .EQ. 8) IATOM=1
!              ITYPE=IRES(I)

              GAMMA1=ALTGAMMA(KTYPE,ITYPE,1,I_WELL)
              GAMMA2=ALTGAMMA(KTYPE,ITYPE,2,I_WELL)
              DELTAGAMMA_THETA=(GAMMA2-GAMMA1)*THETA(K,I,I_WELL) 
              FORCE_K=0.D0
              FORCE_I=0.D0
              FORCE_K(:)=FORCE_K(:)+XYZ_UNIT_VECT(K,I,:)*DELTAGAMMA_THETA*HEAVISIDE_DOT(I)*HEAVISIDE(K)*THETA_DOT(K,I,1) 
              FORCE_I(:)=FORCE_I(:)+XYZ_UNIT_VECT(I,K,:)*DELTAGAMMA_THETA*HEAVISIDE_DOT(K)*HEAVISIDE(I)*THETA_DOT(I,K,1) 
              FORCE_K(:)=FORCE_K(:)+DELTAGAMMA_THETA*HEAVISIDE(I)*HEAVISIDE_DOT(K)*SUM_THETA_DOT(K,:)
              FORCE_I(:)=FORCE_I(:)+DELTAGAMMA_THETA*HEAVISIDE(K)*HEAVISIDE_DOT(I)*SUM_THETA_DOT(I,:)
              F_CORD(K,:,KATOM)=F_CORD(K,:,KATOM)+FORCE_K(:)
              F_CORD(I,:,IATOM)=F_CORD(I,:,IATOM)+FORCE_I(:)
           ENDDO
        ENDDO
      ENDDO

        CALL CPU_TIME(END_TIME)
        ACCUMULATED_TIME(13)= ACCUMULATED_TIME(13) + (END_TIME-START_TIME) 

        RETURN
      END SUBROUTINE CALC_FORCE_ALT_3

      !-----------------------------------------------

