
!                             DISTANCE             
      SUBROUTINE CALC_XYZ(XYZ_DIST,XYZ_UNIT_VECT,PRO_CORD,NMRES)
        USE AMHGLOBALS,  ONLY : MAXSIZ,MAXCRD,TGSEQUENCES_AMW
!        USE GLOBALS_ALT, ONLY : OB_DNS_COUNT,OUTFILE1_ALT

        IMPLICIT NONE
        INTEGER I,J,IATOM,JATOM
        INTEGER, INTENT(IN) :: NMRES
        DOUBLE PRECISION XYZ_DIST(MAXSIZ,MAXSIZ),XYZ_UNIT_VECT(MAXSIZ,MAXSIZ,3)
         DOUBLE PRECISION, INTENT(IN):: PRO_CORD(MAXSIZ,3,MAXCRD)
        DOUBLE PRECISION DIST_TEMP
        !      DOUBLE PRECISION DENS(MAXSIZ)  !  DEBUGGING


        !      DENS=0.0  !  DEBUGGING
        XYZ_DIST=0.0D0
        XYZ_UNIT_VECT=0.0D0
        DO I=1,NMRES-1   
           DO J=I+1,NMRES
              IATOM=2
              JATOM=2
!              IF (IRES(I) .EQ. 8) IATOM=1
!              IF (IRES(J) .EQ. 8) JATOM=1
!  BIT OF A HACK ONLY LOOK AT ISEQ 1              
!              IF (TGSEQUENCES_AMW(I,ISEQ) .EQ. 8) IATOM=1
!              IF (TGSEQUENCES_AMW(J,ISEQ) .EQ. 8) JATOM=1
              IF (TGSEQUENCES_AMW(I,1) .EQ. 8) IATOM=1
              IF (TGSEQUENCES_AMW(J,1) .EQ. 8) JATOM=1

              XYZ_DIST(I,J)=SQRT (  &
                   (PRO_CORD(J,1,JATOM)-PRO_CORD(I,1,IATOM))**2 + &
                   (PRO_CORD(J,2,JATOM)-PRO_CORD(I,2,IATOM))**2 + &
                   (PRO_CORD(J,3,JATOM)-PRO_CORD(I,3,IATOM))**2 )
              DIST_TEMP=XYZ_DIST(I,J)
              XYZ_UNIT_VECT(I,J,:)=(PRO_CORD(I,:,IATOM)-PRO_CORD(J,:,JATOM))/DIST_TEMP
              XYZ_UNIT_VECT(J,I,:)=-XYZ_UNIT_VECT(I,J,:)
              !          IF((DIST_TEMP.LT.6.5) .AND. (DIST_TEMP.GE.4.5))DENS(I)=DENS(I)+1.0 !  DEBUGGING
              !          IF((DIST_TEMP.LT.6.5) .AND. (DIST_TEMP.GE.4.5))DENS(J)=DENS(J)+1.0 !  DEBUGGING
           ENDDO
        ENDDO
!              WRITE(6,*)'DIST_TEMP CALC XYZ', DIST_TEMP
!              WRITE(6,*)'PRO_CORD 1 2  ',PRO_CORD(1,1,1), PRO_CORD(2,1,1)

        !      IF(MOD(OB_DNS_COUNT,1000.).LT.0.5)WRITE(OUTFILE1_ALT(7),1000)'RESIDUE DENSITY',DENS  !  DEBUGGING
        RETURN
        ! 1000   FORMAT(A,200(1X,F6.3)) !  DEBUGGING

      END SUBROUTINE CALC_XYZ

      !---------------------------

      SUBROUTINE CALC_THETA_ALT(THETA, THETA_DOT, XYZ_DIST, RMIN, RMAX,KAPPA,NMRES,  I_WELL)
        ! CALCULATES THETA FOR ALTERNATIVE POTENTIAL
        ! E = THETA * [SIGMA(W)*GAMMA(W) + (1-SIGMA(W))*GAMMA(D)] 

        USE AMHGLOBALS,  ONLY : MAXSIZ
        USE GLOBALS_ALT, ONLY : MAX_WELL_ALT

        !     KAPPA = STEEPNESS OF "STEPFUNCTION" TANH 
        IMPLICIT NONE
        INTEGER I,J,I_WELL,NMRES
        DOUBLE PRECISION KAPPA,T_MIN,T_MAX,RMIN,RMAX
        DOUBLE PRECISION THETA(MAXSIZ,MAXSIZ,MAX_WELL_ALT),THETA_DOT(MAXSIZ,MAXSIZ,MAX_WELL_ALT)
        DOUBLE PRECISION XYZ_DIST(MAXSIZ,MAXSIZ)

        THETA(:,:,I_WELL)=0.D0
        THETA_DOT(:,:,I_WELL)=0.D0

!C              WRITE(6,*)'RMIN AND MAX I_WELL'RMIN,RMAX,I_WELL
               
        DO I=1,NMRES-2   ! WORK OUT THETA VALUES BETWEEN ALL PAIRS
           DO J=I+2,NMRES   ! THETA(IJ)=K*(1+TMIN)*(1+TMAX))
              T_MIN=TANH(KAPPA*(XYZ_DIST(I,J)-RMIN))
               
              T_MAX=TANH(KAPPA*(RMAX-XYZ_DIST(I,J) ))
              THETA(I,J,I_WELL) = 0.25D0*( 1.0D0+T_MIN )*( 1.0D0+T_MAX ) 
              THETA(J,I,I_WELL) =  THETA(I,J,I_WELL) 
              THETA_DOT(I,J,I_WELL)=KAPPA*THETA(I,J,I_WELL)*(T_MAX-T_MIN)
              THETA_DOT(J,I,I_WELL)=THETA_DOT(I,J,I_WELL)
           ENDDO
!           WRITE(6,*)'XYZDIST THETA CALC ',XYZ_DIST(I,J)
        ENDDO

        RETURN
      END SUBROUTINE CALC_THETA_ALT

      !----------------------------

      SUBROUTINE CALC_SUM_THETA_DOT_ALT(SUM_THETA_DOT,THETA_DOT,XYZ_UNIT_VECT,NMRES)
        USE GLOBALS_ALT, ONLY : MAX_WELL_ALT
        USE AMHGLOBALS,  ONLY : MAXSIZ

        IMPLICIT NONE
        INTEGER, INTENT(IN) ::  NMRES
         DOUBLE PRECISION, INTENT(IN) ::  THETA_DOT(MAXSIZ,MAXSIZ,MAX_WELL_ALT)
         DOUBLE PRECISION, INTENT(IN) :: XYZ_UNIT_VECT(MAXSIZ,MAXSIZ,3)
         DOUBLE PRECISION, INTENT(OUT) :: SUM_THETA_DOT(MAXSIZ,3)

        INTEGER P,K

        SUM_THETA_DOT=0.D0

        DO K=1,NMRES-2,1     !CALCULATE DENSITIES, A
           DO P=K+2,NMRES,1
              SUM_THETA_DOT(K,:)=SUM_THETA_DOT(K,:)+THETA_DOT(P,K,1)*XYZ_UNIT_VECT(K,P,:)
              SUM_THETA_DOT(P,:)=SUM_THETA_DOT(P,:)+THETA_DOT(K,P,1)*XYZ_UNIT_VECT(P,K,:)
           ENDDO
        ENDDO

        RETURN
      END SUBROUTINE CALC_SUM_THETA_DOT_ALT

      SUBROUTINE CALC_A_ALT(A,THETA,NMRES)

        USE GLOBALS_ALT, ONLY : MAX_WELL_ALT
        USE AMHGLOBALS,  ONLY : MAXSIZ

        IMPLICIT NONE
        INTEGER I,J,NMRES
        DOUBLE PRECISION THETA(MAXSIZ,MAXSIZ,MAX_WELL_ALT),A(MAXSIZ)

        A=0.D0

        DO I=1,NMRES-2,1     !CALCULATE DENSITIES, A
           DO J=I+2,NMRES,1
              
              A(I)=A(I)+THETA(I,J,1)
              A(J)=A(J)+THETA(I,J,1)
!              WRITE(6,*)'AI AJ THETA(I,J,1)',A(I),A(J),THETA(I,J,1)
           ENDDO
        ENDDO

        RETURN
      END SUBROUTINE CALC_A_ALT


      !--------------------------------




      SUBROUTINE CALC_SIGMA_ALT(SIGMA,A,TRESHOLD,KAPPA,NMRES)
        ! CALCULATES SIGMA = WEIGHTING FUNCTIONS FOR ALTERNATIVE POTENTIAL
        ! E = THETA * [SIGMA(W)*GAMMA(W) + SIGMA(D)*GAMMA(D)] 


        USE AMHGLOBALS,  ONLY : MAXSIZ, CUTOFF_CONT_LOW
!        USE GLOBALS_ALT, ONLY : MAX_WELL_ALT

        IMPLICIT NONE
        INTEGER I,J,NMRES
        DOUBLE PRECISION G(MAXSIZ),KAPPA,TRESHOLD
        DOUBLE PRECISION SIGMA(MAXSIZ,MAXSIZ),A(MAXSIZ)
        DOUBLE PRECISION HEAVISIDE(MAXSIZ)

        SIGMA=0.D0

        G=KAPPA*(A(:) - TRESHOLD) ! CALCULATE G

        HEAVISIDE=0.5D0*(1.0D0-TANH(G) )
!      OPEN(UNIT=1383,FILE='ALT_SIGMA_DATA',STATUS='UNKNOWN',ACCESS='APPEND')
!           WRITE(1383,*)'TRESHOLD KAPPA NMRES ' , TRESHOLD, KAPPA 
!           WRITE(1383,*)'CUTOFF_CONT_LOW ', CUTOFF_CONT_LOW
!           WRITE(1383,291) (SIGMA(32,J),J=1,NMRES)
!           WRITE(1383,291) (SIGMA(32,J),J=1,NMRES)

        DO I=1,NMRES-CUTOFF_CONT_LOW,1
           DO J=I+CUTOFF_CONT_LOW,NMRES,1
              SIGMA(I,J)=HEAVISIDE(I)*HEAVISIDE(J)
              SIGMA(J,I)=SIGMA(I,J)
           ENDDO
        ENDDO

!      OPEN(UNIT=1382,FILE='ALT_A_DATA',STATUS='UNKNOWN',ACCESS='APPEND')  
!           WRITE(1382,291) (A(I),I=1,NMRES)

!           WRITE(1383,291) (SIGMA(32,J),J=1,NMRES)
!           WRITE(1383,291) (HEAVISIDE(J),J=1,NMRES)
!           291 FORMAT(110(1X,E12.6))

!              CLOSE (1382)
!             CLOSE (1383)


        RETURN
      END SUBROUTINE CALC_SIGMA_ALT


      SUBROUTINE CALC_HEAVISIDE_ALT(HEAVISIDE,HEAVISIDE_DOT,A,TRESHOLD,KAPPA)

        USE AMHGLOBALS,  ONLY : MAXSIZ

        IMPLICIT NONE
         DOUBLE PRECISION, INTENT(OUT) :: HEAVISIDE(MAXSIZ), HEAVISIDE_DOT(MAXSIZ)
         DOUBLE PRECISION, INTENT(IN) :: KAPPA,TRESHOLD,A(MAXSIZ)

        !LOCAL
        DOUBLE PRECISION G(MAXSIZ)

        HEAVISIDE=0.D0
        HEAVISIDE_DOT=0.D0

        G=KAPPA*(A(:) - TRESHOLD) ! CALCULATE G
        HEAVISIDE=0.5D0*(1.0D0-TANH(G) )
        HEAVISIDE_DOT=-0.5D0*KAPPA*( 1.0D0 - TANH(G)*TANH(G) ) ! NOTE: GDOT IS EXPLICITLY CALCULATED BELOW
        RETURN
      END SUBROUTINE CALC_HEAVISIDE_ALT

