      SUBROUTINE E_WRITE(AVEP,T,NUMPRO,I_TEMP)

      USE AMHGLOBALS,  ONLY: WEIGHT_P_AP,OKE,OPE_NO_BIAS, & 
            OPE_WITH_BIAS, OPE_BACKBONE,OPE_BACKBONE_NORAMA, &
            OPE_PLUS_KE,OHDRGN,OHDRGN_S,OHDRGN_M,&
            OHDRGN_L,OHDRGN_SEQ,ONONADD,OCON_P_AP,ORAMA,OOXY, &
            OCHIRAL,OAMH,OAMHSR,&
            OAMHMR,OAMHLR,OCCEV,OOEV,OBIAS_RG,MAXPRO,IGOMB,OREP, &
            OOBIASSEGA,OOBIASSEGB,OHARMSPRING,E_HARM_SPRINGS

      IMPLICIT NONE
      
       DOUBLE PRECISION, INTENT(IN):: T,AVEP(:,:,:)
       INTEGER, INTENT(IN):: NUMPRO,I_TEMP

       DOUBLE PRECISION, DIMENSION(SIZE(AVEP,1)):: E_P_AP,E_PE_NO_BIAS
       DOUBLE PRECISION, DIMENSION(SIZE(AVEP,1)):: E_PE_WITH_BIAS
       DOUBLE PRECISION, DIMENSION(SIZE(AVEP,1)):: E_PE_BACKBONE
       DOUBLE PRECISION, DIMENSION(SIZE(AVEP,1)):: E_PE_BACKBONE_NORAMA
       INTEGER:: I_PRO

! PRELIMINARY CALCULATIONS
!  BIASSEG_A  AVEP(:,1,10)
!  BIAS SEG_B AVEP(:,1,18)

       E_P_AP(:)=-WEIGHT_P_AP(1)*AVEP(:,1,40)-WEIGHT_P_AP(2)*AVEP(:,1,41)-WEIGHT_P_AP(3)*AVEP(:,1,42)
       E_PE_NO_BIAS(:)=AVEP(:,1,1)+AVEP(:,1,2)+AVEP(:,1,3)+AVEP(:,1,4)+AVEP(:,1,5)+AVEP(:,1,9)+ &
               AVEP(:,1,11)+AVEP(:,1,17)+E_P_AP+E_HARM_SPRINGS
       E_PE_WITH_BIAS(:)=E_PE_NO_BIAS(:)+AVEP(:,1,10)+AVEP(:,1,12)+AVEP(:,1,18)
       E_PE_BACKBONE(:)= AVEP(:,1,2)+AVEP(:,1,3)+AVEP(:,1,4)+AVEP(:,1,9)+AVEP(:,1,11)
       E_PE_BACKBONE_NORAMA(:)= AVEP(:,1,3)+AVEP(:,1,4)+AVEP(:,1,9)+AVEP(:,1,11)

!   10 BIAS QA  12 RG BIAS 18 BIAS QB
1000      FORMAT(I8,2X,100(F22.10,2X))

! POTENTIAL/KINETIC ENERGIES ETC
!          WRITE(6,*)'IN E_WRITE ' 
          WRITE(OPE_NO_BIAS,1000)  I_TEMP,T,E_PE_NO_BIAS(1:NUMPRO)
          WRITE(OPE_WITH_BIAS,1000) I_TEMP,T,E_PE_WITH_BIAS(1:NUMPRO)
          WRITE(OPE_BACKBONE,1000) I_TEMP,T,E_PE_BACKBONE(1:NUMPRO)
          WRITE(OPE_BACKBONE_NORAMA,1000) I_TEMP,T,E_PE_BACKBONE_NORAMA(1:NUMPRO)

! REPLICA BIAS ENERGY

! HBOND CONTRIBUTIONS
! OHDRGN    I_TEMP,T,AVEP(1:NUMPRO,1,1)  =  NUMBER , TEMP  ,   TOTAL HBOND
! OHDRGN_S  I_TEMP,T,AVEP(1:NUMPRO,1,14),AVEP(I_PRO,1,21:24)  = NUMBER, TEMP, PRE PNAS AB HBOND, PNAS AB SHORT RANGE
! OHDRGN_M  I_TEMP,T,AVEP(1:NUMPRO,1,15),AVEP(I_PRO,1,25:28)  = NUMBER, TEMP, PRE PNAS AB HBOND, PNAS AB MEDIUM RANGE
! OHDRGN_L  I_TEMP,T,AVEP(1:NUMPRO,1,16),AVEP(I_PRO,1,29:32)  = NUMBER, TEMP, PRE PNAS AB HBOND, PNAS AB LONG RANGE
! OHDRGN_SEQ  I_TEMP,T,AVEP(1:NUMPRO,1,16),AVEP(I_PRO,1,33:39)  = NUMBER, TEMP, PRE PNAS AB HBOND, PNAS AB SEQ

       WRITE(OHDRGN,1000) I_TEMP,T,AVEP(1:NUMPRO,1,1)
       WRITE(OHDRGN_S,1000) I_TEMP,T,(AVEP(I_PRO,1,14),AVEP(I_PRO,1,21:24),I_PRO=1,NUMPRO)
       WRITE(OHDRGN_M,1000) I_TEMP,T,(AVEP(I_PRO,1,15),AVEP(I_PRO,1,25:28),I_PRO=1,NUMPRO)
       WRITE(OHDRGN_L,1000) I_TEMP,T,(AVEP(I_PRO,1,16),AVEP(I_PRO,1,29:32),I_PRO=1,NUMPRO)
       WRITE(OHDRGN_SEQ,1000) I_TEMP,T,(AVEP(I_PRO,1,33:39),I_PRO=1,NUMPRO)

! OTHER CONTRIBUTIONS

          WRITE(ONONADD,1000) I_TEMP,T,AVEP(1:NUMPRO,1,17)
          WRITE(OCON_P_AP,1000) I_TEMP,T,(E_P_AP(I_PRO),AVEP(I_PRO,1,40), &
                                AVEP(I_PRO,1,41),AVEP(I_PRO,1,42),I_PRO=1,NUMPRO)
          WRITE(ORAMA,1000) I_TEMP,T,AVEP(1:NUMPRO,1,2)
          WRITE(OOXY,1000) I_TEMP,T,AVEP(1:NUMPRO,1,3)
          WRITE(OCHIRAL,1000) I_TEMP, T,AVEP(1:NUMPRO,1,4)
          WRITE(OAMH,1000) I_TEMP,T,AVEP(1:NUMPRO,1,5)

!          IF (.NOT.IGOMB) THEN
          WRITE(OAMHSR,1000) I_TEMP,T,AVEP(1:NUMPRO,1,7)
          WRITE(OAMHMR,1000) I_TEMP,T,AVEP(1:NUMPRO,1,13)
          WRITE(OAMHLR,1000) I_TEMP,T,AVEP(1:NUMPRO,1,8)
!          ENDIF

          WRITE(OCCEV,1000) I_TEMP, T,AVEP(1:NUMPRO,1,9)
          WRITE(OOEV,1000) I_TEMP,T,AVEP(1:NUMPRO,1,11)
!        WRITE(OBIAS,1000) I_TEMP,T,AVEP(1:NUMPRO,1,10)
          WRITE(OOBIASSEGA,1000) I_TEMP,T,AVEP(1:NUMPRO,1,10)
          WRITE(OOBIASSEGB,1000) I_TEMP,T,AVEP(1:NUMPRO,1,18)
          WRITE(OBIAS_RG,1000) I_TEMP, T,AVEP(1:NUMPRO,1,12)
          WRITE(OHARMSPRING,1000) I_TEMP,T,E_HARM_SPRINGS 

      END
