      SUBROUTINE EV_GAMMA(PRO_CORD,F_CORD,E,TEMPAV)

! EXCLUDED VOLUME BETWEEN GAMMA ATOMS

      USE AMHGLOBALS,  ONLY:SO, MAXSIZ,MAXCRD,NMRES,PEXCLD_GAMMA, & 
           EXVMIN_GAMMA, I_TYPE_EV_GAMMA,C_OF_M_DIST,IRES

      IMPLICIT NONE

       DOUBLE PRECISION, INTENT(IN):: PRO_CORD(MAXSIZ,3,MAXCRD)
       DOUBLE PRECISION, INTENT(OUT):: F_CORD(MAXSIZ,3,MAXCRD),E(:,:)
      LOGICAL, INTENT(IN):: TEMPAV

      DOUBLE PRECISION :: GAMMA_CORD(MAXSIZ,3),DIFF(3),DIST,FACTOR(3),XI
      DOUBLE PRECISION :: PEXCLD_MCP, EXVMIN_MCP,DISTMCP


      INTEGER :: I,J

!     ZERO FORCE AND ENERGY

      F_CORD=0.0D0
      E=0.0D0
      
! CALCULATE GAMMA POSITIONS

      DO I=1,NMRES
        GAMMA_CORD(I,:)=PRO_CORD(I,:,1)+C_OF_M_DIST(I)*(PRO_CORD(I,:,2)-PRO_CORD(I,:,1))
      ENDDO
      
      IF (I_TYPE_EV_GAMMA.EQ.1) THEN !QUADRATIC (HARD FUNCTION)
        DO I=1,NMRES-13
        DO J=I+13,NMRES 
          DIFF(:)=GAMMA_CORD(I,:)-GAMMA_CORD(J,:)
          DIST=DSQRT( DOT_PRODUCT( DIFF,DIFF ) )
          IF (DIST.GT.EXVMIN_GAMMA(I,J)) CYCLE
          FACTOR(:)=-2.0D0*PEXCLD_GAMMA*( DIST-EXVMIN_GAMMA(I,J) )*DIFF(:)/DIST
          F_CORD(I,:,1)=F_CORD(I,:,1)+FACTOR*(1.0D0-C_OF_M_DIST(I))
          F_CORD(J,:,1)=F_CORD(J,:,1)-FACTOR*(1.0D0-C_OF_M_DIST(J))
          F_CORD(I,:,2)=F_CORD(I,:,2)+FACTOR*C_OF_M_DIST(I)
          F_CORD(J,:,2)=F_CORD(J,:,2)-FACTOR*C_OF_M_DIST(J)
          IF (TEMPAV) E(1,9)=E(1,9)+PEXCLD_GAMMA*( DIST-EXVMIN_GAMMA(I,J) )**2
        ENDDO
        ENDDO
      ELSEIF (I_TYPE_EV_GAMMA.EQ.2) THEN !TANH (SOFT FUNCTION)
        XI=0.5D0
        DO I=1,NMRES-1
        DO J=I+1,NMRES
          DIFF(:)=GAMMA_CORD(I,:)-GAMMA_CORD(J,:)
          DIST=DSQRT( DOT_PRODUCT( DIFF,DIFF ) )
          FACTOR(:)=(PEXCLD_GAMMA/(2.0D0*XI))*( COSH((EXVMIN_GAMMA(I,J)-DIST)/XI)**(-2) ) *DIFF(:)/DIST
          F_CORD(I,:,1)=F_CORD(I,:,1)+FACTOR*(1.0D0-C_OF_M_DIST(I))
          F_CORD(J,:,1)=F_CORD(J,:,1)-FACTOR*(1.0D0-C_OF_M_DIST(J))
          F_CORD(I,:,2)=F_CORD(I,:,2)+FACTOR*C_OF_M_DIST(I)
          F_CORD(J,:,2)=F_CORD(J,:,2)-FACTOR*C_OF_M_DIST(J)
          IF (TEMPAV) E(1,9)=E(1,9)+0.5D0*PEXCLD_GAMMA*(1.0D0+TANH((EXVMIN_GAMMA(I,J)-DIST)/XI))
        ENDDO
        ENDDO
      ELSEIF (I_TYPE_EV_GAMMA.EQ.3) THEN !TANH (SOFT FUNCTION MCP)


        XI=0.5D0
        PEXCLD_MCP=10.0D0
        EXVMIN_MCP=2.0D0

        DO I=1,NMRES-10
        DO J=I+10,NMRES

!          IF( (IRES(J).EQ.8) .OR. (IRES(I).EQ.8) ) CYCLE

          DIFF(1)=PRO_CORD(I,1,2)-PRO_CORD(J,1,2)
          DIFF(2)=PRO_CORD(I,2,2)-PRO_CORD(J,2,2)
          DIFF(3)=PRO_CORD(I,3,2)-PRO_CORD(J,3,2)
          DISTMCP=DSQRT( DIFF(1)*DIFF(1) + DIFF(2)*DIFF(2) + DIFF(3)*DIFF(3) )


         FACTOR(1)=(PEXCLD_MCP/(2.0D0*XI))*(COSH((EXVMIN_MCP-DISTMCP)/XI)**(-2))*DIFF(1)/DISTMCP
         FACTOR(2)=(PEXCLD_MCP/(2.0D0*XI))*(COSH((EXVMIN_MCP-DISTMCP)/XI)**(-2))*DIFF(2)/DISTMCP
         FACTOR(3)=(PEXCLD_MCP/(2.0D0*XI))*(COSH((EXVMIN_MCP-DISTMCP)/XI)**(-2))*DIFF(3)/DISTMCP

          F_CORD(I,1,2)=F_CORD(I,1,2)+FACTOR(1)
          F_CORD(J,1,2)=F_CORD(J,1,2)-FACTOR(1)

          F_CORD(I,2,2)=F_CORD(I,2,2)+FACTOR(2)
          F_CORD(J,2,2)=F_CORD(J,2,2)-FACTOR(2)

          F_CORD(I,3,2)=F_CORD(I,3,2)+FACTOR(3)
          F_CORD(J,3,2)=F_CORD(J,3,2)-FACTOR(3)

          E(1,9)=E(1,9)+0.5D0*PEXCLD_MCP*(1.0D0+TANH((EXVMIN_MCP-DISTMCP)/XI))
        ENDDO
        ENDDO

!        XI=0.5D0

!        DO I=1,NMRES
!          GAMMA_CORD(I,:)=PRO_CORD(I,:,2)
!        ENDDO

!        DO I=1,NMRES-3
!        DO J=I+3,NMRES
!          DIFF(:)=GAMMA_CORD(I,:)-GAMMA_CORD(J,:)
!          DIST=DSQRT( DOT_PRODUCT( DIFF,DIFF ) )
!          FACTOR(:)=(PEXCLD_GAMMA/(2.0D0*XI))*( COSH((EXVMIN_GAMMA(I,J)-DIST)/XI)**(-2) ) *DIFF(:)/DIST
!          F_CORD(I,:,1)=F_CORD(I,:,1)+FACTOR(:)
!          F_CORD(J,:,1)=F_CORD(J,:,1)-FACTOR(:)
!          F_CORD(I,:,2)=F_CORD(I,:,2)+FACTOR(:)
!          F_CORD(J,:,2)=F_CORD(J,:,2)-FACTOR(:)
!          IF (TEMPAV) E(1,9)=E(1,9)+0.5D0*PEXCLD_GAMMA*(1.0D0+TANH((EXVMIN_GAMMA(I,J)-DIST)/XI))
!        ENDDO
!        ENDDO

      ELSE
        WRITE(SO,*) 'I_TYPE_EV_GAMMA COCK-UP',I_TYPE_EV_GAMMA
        STOP
      ENDIF

      RETURN
      END
