      MODULE GLOBALS_ALT

        IMPLICIT NONE

        SAVE

        ! PARAMETERS TO BE SET BEFORE COMPILATION:
        ! N_ALTGAMTYPES = # OF DIFFERENT GAMMAS FOR A PARTICULAR WELL
        ! CURRENTLY THIS CAN ONLY BE SET TO 2 
        ! MAX_WELL_ALT = MAX WELLS FOR ALTERNATIVE GAMMA POTENTIAL
        ! ALIMITS SET THE DENSITYLIMITS FOR DEFINING THE WELLS OF THE 1-BODY POTENTIAL

        INTEGER MAX_WELL_ALT,N_ALTGAMTYPES,MAX_LETTERS,DEBUGFLAG
        INTEGER OUTFILE1_ALT(10),N_OB_WELLS,TIMINGS_FILE_ALT
        PARAMETER(N_ALTGAMTYPES=2)
        PARAMETER(MAX_WELL_ALT=2)
        PARAMETER(MAX_LETTERS=20)
        PARAMETER(DEBUGFLAG=0)
        PARAMETER(N_OB_WELLS=3)


        CHARACTER, DIMENSION(20) ::  AMINOACIDS*3 = (/"ALA",  "ARG",   "ASN",   "ASP",   "CYS", &
             "GLN",   "GLU",   "GLY",   "HIS",   "ILE",   "LEU", &
             "LYS",   "MET",   "PHE",   "PRO",   "SER",   "THR", &
             "TRP",   "TYR",   "VAL" /) 
         DOUBLE PRECISION, DIMENSION(20) :: HP_SCALE = (/ 0.45D0,  0.08D0,  0.15D0,  0.12D0, &      ! RESIDUE HYDROPHOBICITY SCALE
             0.40D0,  0.11D0,  0.11D0,  0.35D0,  0.16D0,  1.00D0,  0.61D0,  0.00D0,  0.18D0, &
             0.41D0,  0.23D0,  0.25D0,  0.23D0, 0.39D0,  0.25D0,  0.70D0 /)


        ! PARAMETERS TO BE READ IN FROM INPUTFILE:
        ! ALTPOTFLAG DECIDES WETHER OR NOT TO USE ALTERNATIVE ANISOTROPIC POTENTIAL
        ! (WHICH IS MANYBODY AND THEREFORE PROBABLY A BIT SLOWING DOWN)

        INTEGER ALTPOTFLAG(MAX_WELL_ALT)                             ! ALTPOT
        DOUBLE PRECISION KAPPA_ALT,TRESHOLD_ALT,KAPPA_WELL
        INTEGER ONEBODYFLAG,ONEBODY_TYPE                          ! ONEBODY
        DOUBLE PRECISION KAPPA_OB
        LOGICAL DEBUG_NUMER_FORCES

        ! VARIABLES TO BE SET DURING EXECUTION:

        INTEGER OUTPUT_STEPSIZE_ALT , OUTPUT_STEP_ALT ,COUNT_ALT                 ! ALTPOT
        DOUBLE PRECISION ALTGAMMA(MAX_LETTERS,MAX_LETTERS,N_ALTGAMTYPES,MAX_WELL_ALT),T_ALT
        DOUBLE PRECISION ONEBODY_GAMMA(MAX_LETTERS,N_OB_WELLS)     ! ONEBODY
        DOUBLE PRECISION ALIMITS_OB(2,N_OB_WELLS) 
        LOGICAL DO_SEND_OUTPUT


        !  DIAGNOSTIC VARIABLES (NOT NECESSARY FOR EXECUTION)
        !  OBSERVE!  N_OB_WELLS MUST BE 3 CURRENTLY !!!
        DOUBLE PRECISION OB_DENSITY(MAX_LETTERS,N_OB_WELLS),OB_DNS_COUNT
         DOUBLE PRECISION, DIMENSION(20) :: ACCUMULATED_TIME=0.0D0


      END MODULE GLOBALS_ALT
