      SUBROUTINE  NON_ADD_CONTACT(PRO_CORD,NMRES,TEMPAV,F_CORD,E)

! DOES NON-ADDITIVE CONTACT POTENTIAL

      USE AMHGLOBALS,  ONLY : MAXSIZ,MAXCRD,IRES,R_MIN,R_MAX,SORT_NON_ADD,&
            GAMMA_NON_ADD,CLASS_OF_RES_2

      IMPLICIT NONE

       DOUBLE PRECISION, INTENT(IN):: PRO_CORD(MAXSIZ,3,MAXCRD)
      INTEGER, INTENT(IN):: NMRES
      LOGICAL, INTENT(IN):: TEMPAV

       DOUBLE PRECISION, INTENT(OUT):: F_CORD(MAXSIZ,3,MAXCRD)
       DOUBLE PRECISION, INTENT(OUT):: E

      DOUBLE PRECISION :: DIST,DIST_FACTOR(MAXSIZ,MAXSIZ,3),THETA(MAXSIZ,MAXSIZ,3),A(MAXSIZ,2,3),&
       WEIGHT(MAXSIZ,MAXSIZ,3),WEIGHT2(MAXSIZ,2,3),F_NON_ADD(MAXSIZ,MAXSIZ),&
       THETA_DOT(MAXSIZ,MAXSIZ,3),T_MIN,T_MAX
      INTEGER :: I,J,IATOM,JATOM,I_WELL,I_WELL2,T_I,T_J,IGAM1,IGAM2,I_TYPE

!     ZERO FORCE AND ENERGY

      F_CORD=0.0D0
      E=0.0D0

      DO I=1,NMRES-1   !WORK OUT THETA VALUES BETWEEN ALL PAIRS
      DO J=I+1,NMRES
        IATOM=2
        JATOM=2
        IF (IRES(I) .EQ. 8) IATOM=1
        IF (IRES(J) .EQ. 8) JATOM=1
        DIST=SQRT (  &
              (PRO_CORD(J,1,JATOM)-PRO_CORD(I,1,IATOM))**2 + &
              (PRO_CORD(J,2,JATOM)-PRO_CORD(I,2,IATOM))**2 + &
              (PRO_CORD(J,3,JATOM)-PRO_CORD(I,3,IATOM))**2 )
        DIST_FACTOR(I,J,:)=(PRO_CORD(I,:,IATOM)-PRO_CORD(J,:,JATOM))/DIST
        DO I_WELL=1,2
          T_MIN=TANH(7.0D0*(DIST-R_MIN(I_WELL)))
          T_MAX=TANH(7.0D0*(R_MAX(I_WELL)-DIST))
          THETA(I,J,I_WELL) = 0.25D0*( 1.0D0+T_MIN )*( 1.0D0+T_MAX ) 
          THETA_DOT(I,J,I_WELL)=7.0D0*THETA(I,J,I_WELL)*(T_MAX-T_MIN) 
        ENDDO
      ENDDO
      ENDDO


      A=0.0D0
      DO I=1,NMRES-1     !CALCULATE LOCAL DENSITIES, A
      DO J=I+1,NMRES
        DO I_WELL=1,2
          A(I,CLASS_OF_RES_2(J),I_WELL)=A(I,CLASS_OF_RES_2(J),I_WELL)+THETA(I,J,I_WELL)
          A(J,CLASS_OF_RES_2(I),I_WELL)=A(J,CLASS_OF_RES_2(I),I_WELL)+THETA(I,J,I_WELL)
        ENDDO
      ENDDO 
      ENDDO


      WEIGHT=0.0D0
      DO I=1,NMRES-1     !CALCULATE WEIGHTS GIVEN TO BARE INTERACTIONS
      T_I=CLASS_OF_RES_2(I)
      DO J=I+1,NMRES
      T_J=CLASS_OF_RES_2(J)
        IGAM1=SORT_NON_ADD(T_I,T_J,1,1,1)
        IGAM2=SORT_NON_ADD(T_J,T_I,1,1,1)
        DO I_WELL=1,2
          DO I_TYPE=1,2
          DO I_WELL2=1,2
            WEIGHT(I,J,I_WELL)=WEIGHT(I,J,I_WELL)+ &
                 GAMMA_NON_ADD(IGAM1)*A(I,I_TYPE,I_WELL2)+ &
                 GAMMA_NON_ADD(IGAM2)*A(J,I_TYPE,I_WELL2)
            IGAM1=IGAM1+1
            IGAM2=IGAM2+1
          ENDDO
          ENDDO
        ENDDO
      ENDDO
      ENDDO



      WEIGHT2=0.0D0
      DO I=1,NMRES-13
      T_I=CLASS_OF_RES_2(I)
      DO J=I+13,NMRES
      T_J=CLASS_OF_RES_2(J)
      IGAM1=SORT_NON_ADD(T_I,T_J,1,1,1)
      IGAM2=SORT_NON_ADD(T_J,T_I,1,1,1)
      DO I_WELL=1,2
      DO I_TYPE=1,2
      DO I_WELL2=1,2
        WEIGHT2(I,I_TYPE,I_WELL2)=WEIGHT2(I,I_TYPE,I_WELL2)+  &
                    THETA(I,J,I_WELL)*GAMMA_NON_ADD(IGAM1)
        WEIGHT2(J,I_TYPE,I_WELL2)=WEIGHT2(J,I_TYPE,I_WELL2)+  &
                    THETA(I,J,I_WELL)*GAMMA_NON_ADD(IGAM2)
        IGAM1=IGAM1+1
        IGAM2=IGAM2+1
      ENDDO
      ENDDO
      ENDDO
      ENDDO
      ENDDO
  

      IF (TEMPAV) THEN        !CALCULATE E
        E=0.0D0
        DO I=1,NMRES-13
        DO J=I+13,NMRES
        DO I_WELL=1,2
          E=E-THETA(I,J,I_WELL)*WEIGHT(I,J,I_WELL)
        ENDDO
        ENDDO
        ENDDO
      ENDIF

      F_NON_ADD=0.0D0    !CALCULATE 1ST CONTRIBUTION TO F_IJ
      DO I=1,NMRES-13
      DO J=I+13,NMRES
      DO I_WELL=1,2
        F_NON_ADD(I,J)=F_NON_ADD(I,J)+THETA_DOT(I,J,I_WELL)*WEIGHT(I,J,I_WELL)
      ENDDO
      ENDDO
      ENDDO

      DO I=1,NMRES-1   !ADD 2ND CONTRIBUTION TO F_IJ
      T_I=CLASS_OF_RES_2(I)
      DO J=I+1,NMRES
      T_J=CLASS_OF_RES_2(J)
      DO I_WELL2=1,2
        F_NON_ADD(I,J)=F_NON_ADD(I,J)+THETA_DOT(I,J,I_WELL2)* &
                ( WEIGHT2(I,T_J,I_WELL2) + WEIGHT2(J,T_I,I_WELL2) )
      ENDDO
      ENDDO
      ENDDO


      DO I=1,NMRES-1                  !CALCULATE F_CORD
      IATOM=2
      IF (IRES(I) .EQ. 8) IATOM=1
      DO J=I+1,NMRES
      JATOM=2
      IF (IRES(J) .EQ. 8) JATOM=1
        F_CORD(I,:,IATOM)=F_CORD(I,:,IATOM)+DIST_FACTOR(I,J,:)*F_NON_ADD(I,J)
        F_CORD(J,:,JATOM)=F_CORD(J,:,JATOM)-DIST_FACTOR(I,J,:)*F_NON_ADD(I,J)
      ENDDO
      ENDDO


      END
