
C     --------------------- OPNFIL ----------------------

      SUBROUTINE OPNFIL(IPROLST,IPROLSTSCL,INPUT_AMH,OARCHV,
     *          OMOVI,OHDRGN,OHDRGN_S,OHDRGN_M,OHDRGN_L,OHDRGN_SEQ,
     *          ORAMA,OOXY,OCHIRAL,OAMH,OAMHSR,OREP,
     *          OPE_NO_BIAS,OPE_WITH_BIAS,OPE_BACKBONE,
     *          OPE_BACKBONE_NORAMA,OAMHLR,OAMHMR,ONONADD,
     *          OCON_P_AP,OCCEV,OOEV,OBIAS_RG,OMOVISEG,
     *          OOBIASSEGA,OOBIASSEGB,OHARMSPRING)

      USE AMHGLOBALS,  ONLY:SO

C     ---------------------------------------------------

C     OPNFIL OPENS THE REQUIRED I/O FILES

C     INPUT_AMH:

C        IPROLST  - PROTEIN LIST (INPUT_AMH) (I)
C        INPUT_AMH - INPUT_AMH PARAMETERS (INPUT_AMH) (I)
C        OARCHV- OUTPUT/DIAGNOSTIC FILE (OUTPUT) (I)
C        OMOVI - INTERMEDIATE STRUCTURES 
C                THROUGHOUT RUN (OUTPUT) (I)

C     ---------------------------------------------------

      IMPLICIT NONE

C     ARGUMENT DECLARATIONS:

       INTEGER IPROLST,IPROLSTSCL,INPUT_AMH,OARCHV,OMOVI,
     *           OHDRGN,ORAMA,OOXY,OCHIRAL,OAMH,OAMHSR,OREP,
     *           OKE,OAMHLR,OCCEV,OOEV,OAMHMR,OBIAS_RG,OMOVISEG,OHDRGN_S,
     *           OHDRGN_M,OHDRGN_L,OHDRGN_SEQ,ONONADD,OCON_P_AP,
     *           OPE_NO_BIAS,OPE_WITH_BIAS,OPE_PLUS_KE,OPE_BACKBONE,
     *           OPE_BACKBONE_NORAMA,OOBIASSEGA,OOBIASSEGB,OHARMSPRING
C     --------------------- BEGIN -----------------------

C     OPEN SPECIFIED FILES

C     INPUT_AMH FILES:

C        TARGET PROTEINS AND MEMORIES

       OPEN(UNIT=IPROLST,FILE='PRO.LIST',STATUS='UNKNOWN',FORM='FORMATTED')
C      OPEN(UNIT=IPROLSTSCL,FILE='PRO.LIST.SCL',STATUS='UNKNOWN',FORM='FORMATTED')

C        INPUT_AMH PARAMETERS

       OPEN(UNIT=INPUT_AMH,FILE='INPUT_AMH',STATUS='UNKNOWN',FORM='FORMATTED')

C     OUTPUT FILES:

C        ARCHIVE FILE

       OPEN(UNIT=OARCHV,FILE='ARCHIVE_AMH',STATUS='UNKNOWN',FORM='FORMATTED')

C        HYDROGEN BOND POTENTIAL PLOT FILE

       OPEN(UNIT=OHDRGN,FILE='HDRGN.PLOT',STATUS='UNKNOWN')
       OPEN(UNIT=OHDRGN_S,FILE='HDRGN_S.PLOT',STATUS='UNKNOWN')
       OPEN(UNIT=OHDRGN_M,FILE='HDRGN_M.PLOT',STATUS='UNKNOWN')
       OPEN(UNIT=OHDRGN_L,FILE='HDRGN_L.PLOT',STATUS='UNKNOWN')
       OPEN(UNIT=OHDRGN_SEQ,FILE='HDRGN_SEQ.PLOT',STATUS='UNKNOWN')

C        RAMA POTENTIAL PLOT FILE

       OPEN(UNIT=ORAMA,FILE='RAMA.PLOT',STATUS='UNKNOWN')
        
C        OXY POTENTIAL PLOT FILE

       OPEN(UNIT=OOXY,FILE='OXY.PLOT',STATUS='UNKNOWN')

C        CHIRAL POTENTIAL PLOT FILE

       OPEN(UNIT=OCHIRAL,FILE='CHIRAL.PLOT',STATUS='UNKNOWN')

C        AMH POTENTIAL PLOT FILE

       OPEN(UNIT=OAMH,FILE='AMH.PLOT',STATUS='UNKNOWN')

       OPEN(UNIT=OAMHSR,FILE='AMHSR.PLOT',STATUS='UNKNOWN')

C   REPLICA INTERACTION ENERGY 
C        OPEN(UNIT=OREP,FILE='REP_BIAS.PLOT',STATUS='UNKNOWN')
 
C        TOTAL POTENTIAL AT EVERY TIME STEP

        OPEN(UNIT=OPE_NO_BIAS,FILE='PE_NO_BIAS.PLOT',STATUS='UNKNOWN')
        OPEN(UNIT=OPE_WITH_BIAS,FILE='PE_WITH_BIAS.PLOT',STATUS='UNKNOWN')
C        OPEN(UNIT=OPE_PLUS_KE,FILE='PE_AND_KE.PLOT',STATUS='UNKNOWN')
        OPEN(UNIT=OPE_BACKBONE,FILE='BACKBONE.PLOT',STATUS='UNKNOWN')
         OPEN(UNIT=OPE_BACKBONE_NORAMA,FILE='BACKBONE_NORAMA.PLOT',STATUS='UNKNOWN')


        OPEN(UNIT=OAMHLR,FILE='AMHLR.PLOT',STATUS='UNKNOWN')
        OPEN(UNIT=OAMHMR,FILE='AMHMR.PLOT',STATUS='UNKNOWN')

C       NON-ADDITIVE CONTACT POTENTIAL 
        OPEN(UNIT=ONONADD,FILE='NONADD.PLOT',STATUS='UNKNOWN')

C       P-AP CONTACT POTENTIAL 
        OPEN(UNIT=OCON_P_AP,FILE='CON_P_AP.PLOT',STATUS='UNKNOWN')

C       POTENTIAL DUE TO CARBON (A/B) EXCLUDED VOLUME

        OPEN(UNIT=OCCEV,FILE='CCEV.PLOT',STATUS='UNKNOWN')

C       POTENTIAL DUE TO OXY EXCLUDED VOLUME

        OPEN(UNIT=OOEV,FILE='OOEV.PLOT',STATUS='UNKNOWN')

C       POTENTIAL DUE TO BIASING POTENTIAL

C               OPEN(UNIT=OBIAS,FILE='BIAS.PLOT',STATUS='UNKNOWN')

C       POTENTIAL DUE TO RG-DEPENDENT BIASING POTENTIAL

        OPEN(UNIT=OBIAS_RG,FILE='RG_BIAS.PLOT',STATUS='UNKNOWN')

C       PARTIAL BIASING POTENTIAL
        OPEN(UNIT=OOBIASSEGA,FILE='BIASSEG_A.PLOT',STATUS='UNKNOWN')
        OPEN(UNIT=OOBIASSEGB,FILE='BIASSEG_B.PLOT',STATUS='UNKNOWN')

        OPEN(UNIT=OHARMSPRING,FILE='HARM_SPRING.PLOT',STATUS='UNKNOWN')


C        MOVIE CONFIGURATIONS
 
           OPEN(UNIT=OMOVI,FILE='MOVIE',STATUS='UNKNOWN',
     *        FORM='FORMATTED')
 
C        FINAL MOVIE CONFIGURATION
 
C           OPEN(UNIT=OMOVISEG,FILE='MOVIESEG_FINAL',STATUS='UNKNOWN',
C     *        FORM='FORMATTED')

C    
C          WRITE(6,*)'SO', SO 
           OPEN(UNIT=SO,FILE='OUTPUT_AMH',STATUS='UNKNOWN')

C     END I/O TAPE OPENINGS

C     ---------------------- DONE -----------------------

      RETURN
      END
