      SUBROUTINE RG_BIAS(PRO_CORD,F_CORD,E,TEMPAV)


!     CALCULATES THE CONTRIBUTION TO FORCES (IE F_CORD) 
!     AND ENERGIES DUE TO
!     A POTENTIAL THAT IS POLYNOMIAL IN RADIUS OF GYRATION
!     (NOTE RG CALC FROM C-ALPHA CARBONS ONLY)


      USE AMHGLOBALS,  ONLY:SO, MAXSIZ,MAXCRD,N_RG_BIAS,RG_BIASPOLY,NMRES,RG_BOUNDS,&
           I_RG_COREY, RG_SHIFT, RG_SCL,&
           I_RG_GARYK, I_RG_FIRST, D_RG, T_RG, DELR_RG, M_RG, KAPPA_RG, &
           OARCHV

     
!     ARGUMENT DECLARATIONS

      IMPLICIT NONE
      
      LOGICAL, INTENT(IN):: TEMPAV
       DOUBLE PRECISION, INTENT(IN), DIMENSION(MAXSIZ,3,MAXCRD)::  PRO_CORD
       DOUBLE PRECISION, INTENT(OUT), DIMENSION(MAXSIZ,3,MAXCRD):: F_CORD
       DOUBLE PRECISION, INTENT(OUT):: E(:,:)

!     INTERNAL VARIABLES
      
      INTEGER :: I_AXIS,I_RES,I
      DOUBLE PRECISION, DIMENSION(3):: R_CM=0.0D0
      DOUBLE PRECISION :: RG,V,DV_DRG,FACTOR,RG_PREDICTED
      DOUBLE PRECISION :: ALPHA, BETA, D, D_CRITICAL, M_RG_CRITICAL
      DOUBLE PRECISION ::  RG_MAX, DELR_RG_CRITICAL,  V_MAX

!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
!     ZERO FORCE AND ENERGY

      F_CORD=0.0D0
      E=0.0D0
      D=0.0D0
     
!           CALCULATE CENTRE OF MASS AND RADIUS OF GYRATION


      
      DO I_AXIS=1,3
        R_CM(I_AXIS)=0.0D0
        DO I_RES=1,NMRES
          R_CM(I_AXIS)=R_CM(I_AXIS)+PRO_CORD(I_RES,I_AXIS,1)
!         WRITE(SO,*) I_RES,PRO_CORD(I_RES,I_AXIS,1),R_CM(I_AXIS)
        ENDDO
        R_CM(I_AXIS)=R_CM(I_AXIS)/DBLE(NMRES)
!        WRITE(SO,*) 'FINAL C OF M',I_AXIS,R_CM(I_AXIS)
      ENDDO
!       WRITE(SO,*) 'FINAL C OF M',(R_CM(I_AXIS),I_AXIS=1,3)

      RG=0.0D0
      DO I_AXIS=1,3
      DO I_RES=1,NMRES
        RG=RG+(PRO_CORD(I_RES,I_AXIS,1)-R_CM(I_AXIS))**2
      ENDDO
      ENDDO
      RG=DSQRT(RG/DBLE(NMRES))

      RG_PREDICTED = RG_SHIFT*2.2D0*(DBLE(NMRES)**0.38D0)
      
      IF(I_RG_GARYK) THEN
         ! TO REQUEST A MAPLE WORKSHEET FOR THIS POTENTIAL, SEND AN EMAIL TO GPAPOIAN@UNC.EDU 
         ! V=(D+ALPHA*(R-R_0)^2)/(1+BETA*(R-R_0)^4), MINIMUM AT R_0, GOES TO 0 AT LARGE R
         !I_RG_GARYK, D_RG, T_RG, DELR_RG, M_RG, KAPPA_RG
         D=D_RG*DBLE(NMRES)
         ! TWO STRATEGIES TO DEAL FOR THE POLE WHICH DEVELOP FOR SHALLOW D VALUES: 
         ! 1. TO INCREASE DELR_RG, I.E. ALLOWING LARGER RG FLUCTUATIONS, OR  
         ! 2. TO DECREASE M_RG, I.E. DECREASING THE CAPTURE RADIUS OF THE POTENTIAL
         ! AN UNPHYSICALLY LARGE VALUE OF M_RG (>100 INSTEAD OF ~3) IN THE INPUT FILE 
         ! INDICATES THAT IT NEEDS TO BE CALCULATED HERE, OTHERWISE DELR_RG IS ADJUSTED
         IF(M_RG.LT.100) THEN ! PHYSICAL M_RG, THE USER WANTS TO ADJUST DELR_RG, IF NECESSARY
            DELR_RG_CRITICAL=DSQRT((T_RG*(1+M_RG**2-2*M_RG))/(2*D*(KAPPA_RG-1)))
            IF(DELR_RG.LT.DELR_RG_CRITICAL) DELR_RG=DELR_RG_CRITICAL+0.01D0
         ENDIF
         M_RG_CRITICAL=1+DSQRT((2.0D0*KAPPA_RG*DELR_RG**2*D-2.0D0*D*DELR_RG**2)/(T_RG))
         IF ((M_RG+0.1D0).GT.M_RG_CRITICAL) M_RG=M_RG_CRITICAL-0.1D0
         ALPHA=T_RG/(2.0D0*(DELR_RG**2)*(RG_PREDICTED**2))
         BETA=-1.0D0*(2.0D0*KAPPA_RG*DELR_RG**2*D-2.0D0*D*DELR_RG**2-T_RG*M_RG**2+2.0D0*T_RG*M_RG-T_RG)&
              /(2.0D0*KAPPA_RG*DELR_RG**2*D*RG_PREDICTED**4 &
                *(M_RG**4-4.0D0*M_RG**3+6.0D0*M_RG**2-4.0D0*M_RG+1))
         RG_MAX=(2.0D0*ALPHA*BETA*RG_PREDICTED+2* &
                 DSQRT(-1.0D0*ALPHA*BETA**2*D+ALPHA*BETA*DSQRT(BETA**2*D**2+ALPHA**2*BETA)))&
                 /(2.0D0*ALPHA*BETA)
         D_CRITICAL=-1.0D0*(T_RG*(1+M_RG**2-2.0D0*M_RG))/(2.0D0*(1-KAPPA_RG)*DELR_RG**2)
         V_MAX=(D+ALPHA*(RG_MAX-RG_PREDICTED)**2)/(1+BETA*(RG_MAX-RG_PREDICTED)**4)
         IF(I_RG_FIRST) THEN
            WRITE(OARCHV,99) 'RG_BIAS: D_RG, DELR_RG, ALPHA, BETA, M_RG, RG_MIN, RG_MAX', & 
                              D_RG, DELR_RG, ALPHA, BETA, M_RG, RG_PREDICTED, RG_MAX
            WRITE(OARCHV,98) 'RG_BIAS: V_MIN-V_MAX=', D-V_MAX
98          FORMAT(A,2X,F16.8)
            IF(RG_MAX<3.0D0*RG_PREDICTED) THEN 
               WRITE (OARCHV,99)'RG_BIAS WARNING: CAPTURE RADIUS MAY BE TOO SHORT, RG_MAX/RG_MIN=',RG_MAX/RG_PREDICTED
               WRITE (OARCHV,99) 'RG_BIAS WARNING: CONSIDER SETTING M_RG ABOVE 100'
            ENDIF
99          FORMAT(A,2X,F12.8,2X,F12.8,2X,F12.8,2X,F12.8,2X,F12.8,2X,F12.8,2X,F12.8)
            I_RG_FIRST=.FALSE.
         ENDIF
         IF(D.GT.D_CRITICAL) THEN
            WRITE(SO,100) 'SERIOUS BUG: BY DESIGN D_RG CAN NOT BE LESS THAN D_RG_CRITICAL', D/REAL(NMRES), D_CRITICAL/REAL(NMRES)
100         FORMAT(A,2X,F12.8,F12.8)
            STOP
         ENDIF
      ENDIF
         
!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
!           CALCULATE V(RG) (IF NEEDED) 

      IF (TEMPAV) THEN
         V=0.0D0
         IF (I_RG_COREY) THEN
            IF (RG/RG_PREDICTED .LT. RG_BOUNDS(1)) THEN
               V=RG_SCL*10.0D0*(RG_BOUNDS(1)*RG_PREDICTED - RG_PREDICTED)**2
               DV_DRG=0.0D0      
            ELSEIF (RG/RG_PREDICTED .GT. RG_BOUNDS(2)) THEN
               V=RG_SCL*10.0D0*(RG_BOUNDS(2)*RG_PREDICTED - RG_PREDICTED)**2
               DV_DRG=0.0D0      
            ELSE
               V=RG_SCL*10.0D0*(RG - RG_PREDICTED)**2
               DV_DRG= RG_SCL*20.0D0*(RG - RG_PREDICTED)
            ENDIF
         ELSEIF(I_RG_GARYK) THEN
            IF(RG.LT.RG_MAX) THEN
               V=(D+ALPHA*(RG-RG_PREDICTED)**2)/(1+BETA*(RG-RG_PREDICTED)**4)
               DV_DRG=(2*ALPHA*(RG-RG_PREDICTED))/(1+BETA*(RG-RG_PREDICTED)**4)-&
                    (4*BETA*(D+ALPHA*(RG-RG_PREDICTED)**2)*(RG-RG_PREDICTED)**3)/ &
                                      (1+BETA*(RG-RG_PREDICTED)**4)**2
            ELSE
               V=(D+ALPHA*(RG_MAX-RG_PREDICTED)**2)/ &
                         (1+BETA*(RG_MAX-RG_PREDICTED)**4)
               DV_DRG=0.0D0
            ENDIF
            WRITE(SO,1000) 'RG, RG_PREDICTED, RG_MAX, V, DV_DRG', &
                          RG, RG_PREDICTED, RG_MAX, V, DV_DRG
1000   FORMAT(A,2X,F9.3,2X,F9.3,2X,F9.3,2X,F9.3,2X,F9.3)
         ELSE
            DO I=1,N_RG_BIAS
               V=V+RG_BIASPOLY(I)*RG**I
            ENDDO
            DV_DRG=0.0D0      
            DO I=1,N_RG_BIAS
               DV_DRG=DV_DRG+DBLE(I)*RG_BIASPOLY(I)*RG**(I-1)
            ENDDO
         ENDIF
         E(1,12)=E(1,12)+V
      ENDIF

!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
! CALCULATE DV(RG)/DRG  


      DV_DRG=0.0D0      
      IF (I_RG_COREY) THEN
         IF ( (RG/RG_PREDICTED .GT. RG_BOUNDS(1)) .AND.&
              (RG/RG_PREDICTED .LT. RG_BOUNDS(2)) ) THEN
            DV_DRG= RG_SCL*20.0D0*(RG - RG_PREDICTED)
         ENDIF
      ELSEIF(I_RG_GARYK) THEN
         IF(RG.LT.RG_MAX) THEN
            DV_DRG=(2*ALPHA*(RG-RG_PREDICTED))/(1+BETA*(RG-RG_PREDICTED)**4)-&
                 (4*BETA*(D+ALPHA*(RG-RG_PREDICTED)**2)*&
                    (RG-RG_PREDICTED)**3)/(1+BETA*(RG-RG_PREDICTED)**4)**2
         ENDIF
      ELSE
         DO I=1,N_RG_BIAS
            DV_DRG=DV_DRG+DBLE(I)*RG_BIASPOLY(I)*RG**(I-1)
         ENDDO
      ENDIF

!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
!        CALCULATE CONTRIBUTION TO FORCE, AND ADD TO F_CORD

      FACTOR=-DV_DRG/(DBLE(NMRES)*RG)
!     WRITE(SO,*) (F_CORD(50,I_AXIS,1),I_AXIS=1,3)
      DO I_AXIS=1,3
      DO I_RES=1,NMRES
        F_CORD(I_RES,I_AXIS,1)=F_CORD(I_RES,I_AXIS,1)+          &
                 (PRO_CORD(I_RES,I_AXIS,1)-R_CM(I_AXIS))*FACTOR
      ENDDO
      ENDDO


      END
