#!/usr/bin/env bash
 
# directory where this script resides
export shd="`dirname $(readlink -f $0)`"
# name of this script 
export this_script=` basename $0 `

case $HOSTNAME in 
  	mek-quake) suff="mek-" ;;
esac

wdirs=( `find $shd -name \*.$suff\*` )

vim_opts="-n -p"
v="vim $vim_opts"
repos=( "config" "scripts" "templates" "vrt" "install" "doc-coms" "doc-cit" )

define_base_dirs(){
# {{{
# main Wales group software directory
export wg_dir="$shd/../../"
packdir=$HOME/arch/packed
unpackdir=$HOME/arch/unpacked
# }}}
}


set_base_vars(){
# {{{
s_purpose="plotting with gnuplot"
s_project="~/gops/pbs/s"
# }}}
}

set_base_vars

display_help(){
# {{{
# general beginning part {{{
cat << EOF
=============================================
SCRIPT NAME: $this_script 
PROJECT: $s_project
PURPOSE: $s_purpose
USAGE: $this_script [ OPTIONS ] 

	OPTIONS:

	============
	General
	============

			display the help message

	vm		v(iew) m(yself), i.e., edit this script
	-g		gvim invocation
	
	============
EOF
# }}}
# actual interesting part {{{
cat << EOF

some option

EOF
# }}}
# final general part {{{
cat << EOF
REMARKS:
AUTHOR: O. Poplavskyy
=============================================
EOF
# }}}
# }}}
}

[ -z "$*" ] && ( display_help; exit 0 )

main(){
# {{{

case "$1" in
  m) 
    dfiles=( markov best energy )  
	gpf=0.gp
  	for wdir in ${wdirs[@]}; do 
	  	cd $wdir 

		 for dfile in ${dfiles[@]}; do
		 #plotting {{{

		case $dfile in 
	 		markov) 	  		;;
	 		best) 	  		;;
	 		energy)		;;
	    esac		
		title=$dfile
		gp_opts="with points "

cat >& $gpf << EOF

		set term postscript enhanced
		set output "$dfile.ps"
		set title "$title"

		set xlabel "STEP"
		#set ylabel "$ylabel"

		plot "$dfile" using 1:2 $gp_opts

EOF
#}}}
		 done

gnuplot $gpf	
		~
  	done 
  ;;
  *)
  ;;
esac    # --- end of case ---

# }}}
}

# main part 
# {{{

script_opts=( $* )
define_base_dirs

while [ ! -z "$1" ]; do
  	case "$1" in
		  #{{{
	  	vm) $v $0; exit ;;
		h) display_help $*; exit ;;
		-g) v="$v -g" ;;
	  	*) main $* && exit 0 ;;
	esac
  	shift
        #}}}
done

# }}}


